### ISSUE TITLE
EntityFramework version should be included in model snapshot

### ISSUE THREAD

**Issue by lukewaters** [aspnet/EntityFramework#1010]
The migrations pipeline needs to know what version of the product was used to generate a model snapshot so it can compensate for changes that are introduced to model generation

**Comment by smitpatel** [comment]
ProductVersion is included in Designer.cs file for each migration.
Though ModelSnapshot doesn't store the version. 
What is task here?

@bricelam - ModelSnapshot is generated as partial class but I cant find other part. bug?

**Comment by bricelam** [comment]
@smitpatel It should be stored as an annotation in the model.

We have a principle to always generate partial classes so that the *could* extend them if they wanted.
