### ISSUE TITLE
Migrations: Support WinRT assemblies in package manager console commands

### ISSUE THREAD

**Issue by boyakoosha** [aspnet/EntityFramework#1058]
UPDATE:
We should address the experience of using Migrations in universal apps. We won't necessarily support code in OnModelCreating() that makes calls that are specific to the platform.
## 

Have followed the steps in https://github.com/aspnet/EntityFramework/wiki/Using-EF7-in-Windows-Phone-&-Store-Applications

But when attempting to add a migration "Add-Migration "init"" I get:
The process has no package identity.

Error trying to open the default application data handle

That's when I switch the CPU build to x86, when it's set to x64 I get:
add-migration : Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Could not load file or assembly 'windows store test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program 
with an incorrect format."
At line:1 char:1
- add-migration 1
- ~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
  - FullyQualifiedErrorId : BadImageFormatException,Add-Migration

Hopefully this helps!

**Comment by bricelam** [comment]
I think this experience is more-or-less as complete as it can be with the current architecture. `Add-Migration` and `Remove-Migration` work. Other commands error pointing you to an alternative. AnyCPU, x86, and x64 are supported. Class libraries can be used if you specify an app as the startup project.

#6128 is about taking it even further, but I think this can be closed now.
