### ISSUE TITLE
Not possible to map Guid to columns declared as BLOB with SQLite

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#1068]
The test class (to be located in the SQLIte Functional Tests project) sums up the issue..
It is perfectly legal to declare a column as blob, and store Guids in this column as byte(16)
In fact there is no datatype called UNIQUEIDENTIFIER in sqlite. 
Have no idea if this is an issue with EF or the SQLite ADO.Net provider also part of this project, ie the sqlite type map or what.

    using System;
    using System.Collections.Generic;
    using System.Data.Common;
    using System.Linq; 
    using System.Text;
    using System.Threading.Tasks;
    using Xunit;

    namespace Microsoft.Data.Entity.SQLite.FunctionalTests
    {
	public class SQLiteGuidDeclaredAsBlobTest
	{
		[Fact]
		public void Can_Read_Guid_Key_Column_Created_As_BLOB_Using_AdoNet()
		{
			using (var connection = new Data.SQLite.SQLiteConnection("Filename=:memory:"))
			{
				using (var command = connection.CreateCommand())
				{
					CreateTestTable(connection, "BLOB");

					command.CommandText = "SELECT ArtistId FROM Artist";

					using (var reader = command.ExecuteReader())
					{
						reader.Read();

						Assert.Equal(new Guid("dc13b11c-e6fb-449f-a892-5e2a47b05350"), reader.GetGuid(0));
					}
				}
			}
		}

		[Theory]
		[InlineData("UNIQUEIDENTIFIER")]
		[InlineData("BLOB")]
		public void Can_Read_Guid_Key_Column_Created_As_BLOB_Using_EF7(string declaredType)
		{
			using (var db = new ChinookContext())
			{
				using (var connection = db.Database.AsRelational().Connection.DbConnection)
				{
					CreateTestTable(connection as Data.SQLite.SQLiteConnection, declaredType);
					var artist = db.Artists.First();
					Assert.Equal(artist.Name, "ABBA");
				}
			}
		}

		//HACK... just to demonstrate the issue:

		//public virtual T ReadValue<T>(int index)
		//{
		//	if (typeof(T).FullName == "System.Guid" && _valueBuffer[index].GetType().FullName == "System.Byte[]")
		//	{
		//		_valueBuffer[index] = new System.Guid(_valueBuffer[index] as System.Byte[]);
		//	}
		//	return (T)_valueBuffer[index];
		//}

		private static void CreateTestTable(Data.SQLite.SQLiteConnection connection, string declaredType)
		{
			connection.Open();
			connection.ExecuteNonQuery(@"
                CREATE TABLE Artist (
                    ArtistId " + declaredType + @",
                    Name TEXT
                )");
			connection.ExecuteNonQuery(@"
                INSERT INTO Artist VALUES (
                    x'1cb113dcfbe69f44a8925e2a47b05350',
                    'ABBA'
                )");
		}

	}

	internal static class DbConnectionExtensions
	{
		public static int ExecuteNonQuery(this DbConnection connection, string commandText)
		{
			using (var command = connection.CreateCommand())
			{
				command.CommandText = commandText;

				return command.ExecuteNonQuery();
			}
		}
	}

	public class ChinookContext : DbContext
	{
		public DbSet<Artist> Artists { get; set; }

		protected override void OnConfiguring(DbContextOptions options)
		{
			options.UseSQLite("Filename=:memory:");
		}
	}

	public class Artist
	{
		public Guid ArtistId { get; set; }
		public string Name { get; set; }
	}	

    }

**Comment by bricelam** [comment]
This appears to be fixed now.
