### ISSUE TITLE
Invalid SQL for FirstOrDefault() with .Include()

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/EntityFramework#1069]
I'm running a query like the following:

    [HttpGet]
    public async Task<ActionResult> Album(int id)
    {
        var album = await context.Albums
            .Include(a => a.Tracks)
            .Include(a => a.Artist)                                
            .FirstOrDefaultAsync(alb => alb.Id == id);

        return View(album);
    } 

and get the following errors:

An unhandled exception occurred while processing the request.

SqlException: The correlation name 'a' is specified multiple times in a FROM clause.
System.Data.SqlClient.SqlCommand.<ExecuteDbDataReaderAsync>b__24(Task`1 result)

AggregateException: One or more errors occurred.
System.Data.SqlClient.SqlCommand.<ExecuteDbDataReaderAsync>b__24(Task`1 result)

AggregateException: One or more errors occurred.
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

AggregateException: One or more errors occurred.
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

AggregateException: One or more errors occurred.
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
It's generating the following incorrect SQL (not the [a] definition for both Album and Artist:

Looks like this query (which is passed to an MVC view to render) generates this invalid SQL captured in the Sql Profiler:

```sql
exec sp_executesql N'SELECT TOP(@p0) [a].[AmazonUrl], [a].[ArtistId], [a].[Description], [a].[Id], [a].[ImageUrl], [a].[Title], [a].[Year], [a].[AmazonUrl], [a].[ArtistName], [a].[Description], [a].[Id], [a].[ImageUrl]
FROM [Albums] AS [a]
INNER JOIN [Artists] AS [a] ON [a].[Id] = [a].[ArtistId]
WHERE [a].[Id] = @p0
ORDER BY [a].[Id]',N'@p0 int',@p0=1
```

Oddly, I'm also running this very same query in an API controller which returns the very same raw result back from, but there I don't get this error. 

        [HttpGet]
        public async Task<Album> Album(int id)
        {
            var album = await context.Albums
                                     .Include(ctx=> ctx.Tracks)
                                     .Include(ctx => ctx.Artist)
                                     .FirstOrDefaultAsync(alb => alb.Id == id);

            return album;
        }

BOth are using .FirstOrDefaultAsync() so and .Include() to materialize the children so I'm not sure why there's a difference here. There are no deeper nested relations or back links that could account for this either.

Using the very simple models that can be found here:
https://github.com/RickStrahl/AlbumViewerVNext/tree/master/src/AlbumViewerBusiness/Models

and I'm on build 11614 of EF at the moment.

**Comment by anpete** [comment]
Hey, @RickStrahl, can you check whether this works now?

**Comment by RickStrahl** [comment]
Works now and has been for a while. Thanks.

**Comment by anpete** [comment]
Thanks @RickStrahl for your help!
