### ISSUE TITLE
nvarchar(max) can't be used with indexed columns

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#1071]
(See [How to create an index for a string property in Entity Framework 7](http://stackoverflow.com/q/26950625/475031))

Similar to how we use `nvarchar(450)` on key columns, we should do something similar for indexed columns. I assume this also applies to `varbinary(max)`.

**Comment by Muchiachio** [comment]
Can a key/foreign key property length be lowered to 128? To follow EF6 of defaulting keys to 128? Or you have a reason to use string length of 450, which is quite big for the string key.

**Comment by ChristineBoersen** [comment]
A workaround for now is during the OnModelCreating event of your Context add the following to manually change the column length to 450 characters versus letting the CLR make them nvarchar(max), you will get an nvarchar(450).

Give that your POCO is named YOUROBJECTNAME and that your property is named YOURFIELDNAME and is defined as a string

            modelBuilder.Entity<YOUROBJECTNAME>(entity =>
            {
                  entity.Property(e => e.YOURFIELDNAME).MaxLength(450);
            });

**Comment by rowanmiller** [comment]
Clearing for triage as this was marked as pri1... but if we are going to do it, we should do it for RTM
