### ISSUE TITLE
Remove SchemaQualifiedName

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1072]
In some parts of the code we use this and in other parts we use schema and table name separately. In some places it makes sense to treat them separately, such as in the code that accesses and manipulates annotations. However, when it comes to code that is reasoning about table names in relational code we should probably consistently use this class or if it doesn't make sense then get rid of it.

**Comment by smitpatel** [comment]
SchemaQualifiedName is used heavily in Sql Generator & Migration classes. In relational context we use "schema.tablename" so it would be useful to have this class. There are some places where it is not consistent (eg. TableExpression class). In metadata extensions, the schema and tablename is stored in different annotations, they are treated separately which can be made exception or changed to make it consistent.
Thoughts?

**Comment by anpete** [comment]
SchemaQualifiedName still handles serializing to/from the dotted string representation (with escaping), which I'm not sure we use anywhere.

**Comment by bricelam** [comment]
Another data point:
Existing EF6 migrations make use of `"schema.Table"` literals, so if our goal is to maximize compatibility, at least part of the stack will need to parse these strings.

**Comment by anpete** [comment]
Yeah, looks like EF7 is that same.

**Comment by ajcvickers** [comment]
Discussed with @bricelam, @anpete, @rowanmiller. Arguments made on both sides, but settled on remove it, don't do any parsing anywhere (including Migrations) and always have schema and table specified separately.

**Comment by bricelam** [comment]
Since this is now a Migrations bug, and I'm about to cause a lot of code churn in that area, this should probably be reassigned to me.

**Comment by bricelam** [comment]
@smitpatel #1569 removed SchemaQualifiedName from Migrations. It's now safe to remove it and any remaining usages.
