### ISSUE TITLE
Migrations: Scaffold cascadeDelete true for required FKs

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#1084]
Currently TODO'd in DatabaseBuilder.BuildForeignKey because of #333

**Comment by rowanmiller** [comment]
Need to do design work for #333 before we know if this is needed

**Comment by divega** [comment]
@ajcvickers and I talked and it is now safe to assume that scaffolding cascade deletes in migrations is part of how we are going to enable the behavior, so this can now be assigned to @bricelam.

**Comment by bricelam** [comment]
All the Migrations code is there. You can even manually add it if you want. The `ModelDiffer` is just [waiting for the metadata](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs#L606).

**Comment by divega** [comment]
Thanks @bricelam. In that case I will close in favor of #333 which is already tracking the general feature.
