### ISSUE TITLE
Reorganize ModelBuilderTest

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#1102]
There are many scenarios that need to be covered for ModelBuilder making the ModelBuilderTest class hard to navigate when looking for coverage gaps, there is also a lot of duplicate tests in BasicModelBuilderTest. Depending on the outcome of #908 these classes need to be reorganized into a collection of suites corresponding to the targeted scenarios and whether they depend on the default set of conventions.

Consider creating a ModelBuilderTests subfolder to group the resulting collection.

**Comment by ajcvickers** [comment]
Clearing milestone. What I didn't realize when we triaged this was that the tests for the non-generic and string-based APIs are currently disabled meaning we have very little coverage for those APIs.

**Comment by divega** [comment]
@smitpatel this is related to #908. Please talk to @AndriySvyryd about how to go about it.
