### ISSUE TITLE
Using AutoMapper or SimpleMapper followed by SaveChanges() fails

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/EntityFramework#1110]
I'm working with code that's updating a complex object that has a one to one and a one to many relationship in an MVC API controller. I capture an an object (same as the entity type) as an input parameter and then use Automapper to map the data from the user supplied data onto either an existing instance loaded from the context or a New and added instance on the context.

The object is mapped property and I get the model changes posted into the Album instance that is to be updated including the child objects.

Here's the code:

        [HttpPost]
        public async Task<Album> Album([FromBody] Album postedAlbum)
        {
            if (!ModelState.IsValid)            
                throw new ApiException("Model binding failed.",500);
            
            int id = postedAlbum.Id;

            Album album = null;
            if (id < 1)
                album = context.Albums.Add(new Album());
            else
            {
                album = await context.Albums
                    .Include(ctx => ctx.Tracks)
                    .Include(ctx => ctx.Artist)
                    .FirstOrDefaultAsync(alb => alb.Id == id);
            }

            var album2 = AutoMapper.Mapper.Map<Album,Album>(postedAlbum, album) as Album;            

            try {
                int result = await context.SaveChangesAsync();
            }
            catch(Exception ex)
            {
                throw new ApiException(ex, 500);
            }

            return album;
        }

When this code runs I get a Null Reference exception. I get the same behavior in the full ASP.NET MusicStore which uses a SimpleMapper() class that simulates similar behavior as AutoMapper using code from the MusicStore project.

Note I've also used my own routines earlier that are essentially doing Reflection based property updates and that code actually works fine.

Model and Context can be found here:
https://github.com/RickStrahl/AlbumViewerVNext/tree/master/src/AlbumViewerBusiness/Models

The full exception is:

```
NullReferenceException: Object reference not set to an instance of an object.
Microsoft.Data.Entity.Metadata.ClrPropertySetter`2.SetClrValue(Object instance, Object value)

Stack Query Cookies Headers Environment
NullReferenceException: Object reference not set to an instance of an object.
Microsoft.Data.Entity.Metadata.ClrPropertySetter`2.SetClrValue(Object instance, Object value)
Microsoft.Data.Entity.ChangeTracking.StateEntry.WritePropertyValue(IPropertyBase propertyBase, Object value)
Microsoft.Data.Entity.ChangeTracking.StateEntry.set_Item(IPropertyBase property, Object value)
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.SetNullForeignKey(StateEntry dependentEntry, IReadOnlyList`1 dependentProperties)
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.ConditionallySetNullForeignKey(StateEntry dependentEntry, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalValues)
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.NavigationCollectionChangedAction(StateEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.<>c__DisplayClass9.<NavigationCollectionChanged>b__10()
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.PerformFixup(Action fixupAction)
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.NavigationCollectionChanged(StateEntry entry, INavigation navigation, ISet`1 added, ISet`1 removed)
Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.<>c__DisplayClass8.<NavigationCollectionChanged>b__9(IEntityStateListener l)
Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.Dispatch(Action`1 action)
Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.NavigationCollectionChanged(StateEntry entry, INavigation navigation, ISet`1 added, ISet`1 removed)
Microsoft.Data.Entity.ChangeTracking.ChangeDetector.DetectNavigationChange(StateEntry entry, INavigation navigation)
Microsoft.Data.Entity.ChangeTracking.ChangeDetector.DetectChanges(StateEntry entry)
Microsoft.Data.Entity.ChangeTracking.ChangeDetector.DetectChanges(StateManager stateManager)
Microsoft.Data.Entity.DbContext.<SaveChangesAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
MusicStoreVNext.MusicStoreApiController.<Album>d__2.MoveNext() in MusicStoreApiController.cs
           int result = await context.SaveChangesAsync();
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.ControllerActionExecutor.<CastToObject>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.ControllerActionExecutor.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.ControllerActionExecutor.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.ControllerActionInvoker.<InvokeActionAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.FilterActionInvoker.<InvokeActionMethodFilter>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNet.Mvc.FilterActionInvoker.<InvokeAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.ControllerActionInvoker.<InvokeAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.MvcRouteHandler.<RouteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Diagnostics.ErrorPageMiddleware.<Invoke>d__1.MoveNext()
```

**Comment by ajcvickers** [comment]
Note for triage: Unassigning since anyone could work on this.

**Comment by rowanmiller** [comment]
@smitpatel work with @ajcvickers  on this one

**Comment by smitpatel** [comment]
@RickStrahl - While investigating this I found that automapper isn't working correctly. For more info check [this](https://github.com/AutoMapper/AutoMapper/issues/656).
Also for the if-else loop which execution path gives error? or both throws the same exception? Because of API changes the code written above needs modifications. And with modifications I am getting different kind of exception in both but not this. Can you have a look at it?

**Comment by smitpatel** [comment]
Closing this for now.
Feel free to open again if you encounter the same exception.

**Comment by JonTheMon** [comment]
I am encountering an issue very similar to the original issue. I'm excluding Automapper and I'm getting the exception below.  To simplify it, all I'm doing is taking my object with a collection, loading it, removing an item out of it, and doing db.SaveChanges().  

I'm trying to take advantage of an identifying relationship (composite key of Id and Foreign Key) so that when the item is removed from the collection, the item is removed as well. 

I've uploaded my simplified version to: https://github.com/JonTheMon/EntityFrameworkExample

>	Microsoft.Data.Entity.Metadata.Internal.ClrPropertySetter`2.SetClrValue(Object instance, Object value)
>	Microsoft.Data.Entity.ChangeTracking.Internal.EntityEntryMetadataServices.WriteValue(Object entity, IPropertyBase propertyBase, Object value)
>	Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.WritePropertyValue(IPropertyBase propertyBase, Object value)
>	Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.set_Item(IPropertyBase property, Object value)
>	Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.SetNullForeignKey(InternalEntityEntry dependentEntry, IReadOnlyList`1 dependentProperties)
>	Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.ConditionallySetNullForeignKey(InternalEntityEntry dependentEntry, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalValues)
>	Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.NavigationCollectionChangedAction(InternalEntityEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
>	Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.<>c__DisplayClass11_0.<NavigationCollectionChanged>b__0()
>	Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.PerformFixup(Action fixupAction)
>	Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, ISet`1 added, ISet`1 removed)
>	Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.<>c__DisplayClass10_0.<NavigationCollectionChanged>b__0(INavigationListener l)
>	Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.Dispatch(Action`1 action)
>	Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, ISet`1 added, ISet`1 removed)
>	Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation, Sidecar snapshot)
>	Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectNavigationChanges(InternalEntityEntry entry, Sidecar snapshot)
>	Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectRelationshipChanges(InternalEntityEntry entry)
>	Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
>	Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
>	Microsoft.Data.Entity.ChangeTracking.ChangeTracker.DetectChanges()
>	EntityFrameworkExample.Models.AppDbContext.SaveChanges() in DbContext.cs
>	
>	19.         ChangeTracker.DetectChanges();
>	
>	EntityFrameworkExample.Controllers.ContactController.<Edit>d__4.MoveNext() in ContactController.cs
>	
>	100.            db.SaveChanges();
>	
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>	Microsoft.AspNet.Mvc.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>	Microsoft.AspNet.Mvc.ControllerActionExecutor.<ExecuteAsync>d__3.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>	Microsoft.AspNet.Mvc.ControllerActionExecutor.<ExecuteAsync>d__2.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>	Microsoft.AspNet.Mvc.Core.ControllerActionInvoker.<InvokeActionAsync>d__7.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>	Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeActionFilterAsync>d__41.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>	Microsoft.AspNet.Mvc.MvcRouteHandler.<InvokeActionAsync>d__3.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>	Microsoft.AspNet.Mvc.MvcRouteHandler.<RouteAsync>d__2.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>	Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__25.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>	Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__10.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>	Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>	Microsoft.AspNet.Diagnostics.ErrorPageMiddleware.<Invoke>d__4.MoveNext()
