### ISSUE TITLE
Remove() and RemoveRange() problems

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/EntityFramework#1111]
I'm doing an update to a one to many graph and need to manually remove entities from the many graph.

```c#
            album = context.Albums.Add(new Album());
            ...
            if (deletedTracks.Count > 0)
            {
                context.Tracks.RemoveRange(deletedTracks);
                //foreach (var dtrack in deletedTracks)
                //    album.Tracks.Remove(dtrack);
            }

            int result = await context.SaveChangesAsync();   
            return album;
```
This works in so far as SaveChanges() will remove the items on disk, but the album instance is not updated.

If I use the commented code instead and remove tracks from the album.Tracks list one at a time, I get a Null Reference runtime error when calling SaveChanges() (see #1110 which is probably the same issue when using mappers).

Model and Context can be found here:
https://github.com/RickStrahl/AlbumViewerVNext/tree/master/src/AlbumViewerBusiness/Models

Full error message:

An unhandled exception occurred while processing the request.

NullReferenceException: Object reference not set to an instance of an object.
Microsoft.Data.Entity.Metadata.ClrPropertySetter`2.SetClrValue(Object instance, Object value)

Stack Query Cookies Headers Environment
NullReferenceException: Object reference not set to an instance of an object.
Microsoft.Data.Entity.Metadata.ClrPropertySetter`2.SetClrValue(Object instance, Object value)
Microsoft.Data.Entity.ChangeTracking.StateEntry.WritePropertyValue(IPropertyBase propertyBase, Object value)
Microsoft.Data.Entity.ChangeTracking.StateEntry.set_Item(IPropertyBase property, Object value)
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.SetNullForeignKey(StateEntry dependentEntry, IReadOnlyList`1 dependentProperties)
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.ConditionallySetNullForeignKey(StateEntry dependentEntry, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalValues)
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.NavigationCollectionChangedAction(StateEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.<>c__DisplayClass9.<NavigationCollectionChanged>b__10()
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.PerformFixup(Action fixupAction)
Microsoft.Data.Entity.ChangeTracking.NavigationFixer.NavigationCollectionChanged(StateEntry entry, INavigation navigation, ISet`1 added, ISet`1 removed)
Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.<>c__DisplayClass8.<NavigationCollectionChanged>b__9(IEntityStateListener l)
Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.Dispatch(Action`1 action)
Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.NavigationCollectionChanged(StateEntry entry, INavigation navigation, ISet`1 added, ISet`1 removed)
Microsoft.Data.Entity.ChangeTracking.ChangeDetector.DetectNavigationChange(StateEntry entry, INavigation navigation)
Microsoft.Data.Entity.ChangeTracking.ChangeDetector.DetectChanges(StateEntry entry)
Microsoft.Data.Entity.ChangeTracking.ChangeDetector.DetectChanges(StateManager stateManager)
Microsoft.Data.Entity.DbContext.<SaveChangesAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
MusicStoreVNext.MusicStoreApiController.<Album>d__2.MoveNext() in MusicStoreApiController.cs
            int result = await context.SaveChangesAsync();   
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.ControllerActionExecutor.<CastToObject>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.ControllerActionExecutor.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.ControllerActionExecutor.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.ControllerActionInvoker.<InvokeActionAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.FilterActionInvoker.<InvokeActionMethodFilter>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNet.Mvc.FilterActionInvoker.<InvokeAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.ControllerActionInvoker.<InvokeAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.MvcRouteHandler.<RouteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Diagnostics.ErrorPageMiddleware.<Invoke>d__1.MoveNext()

**Comment by ajcvickers** [comment]
Note for triage: Unassigning since anyone could work on this.

**Comment by rowanmiller** [comment]
@smitpatel work with @ajcvickers on this one

**Comment by smitpatel** [comment]
@RickStrahl - I tried to reproducing this with some changes as RemoveRange does not exist anymore. But I am not getting any exception. album.Tracks.Remove(dtrack) works correctly for me.
Can you try using latest build and check if you are still getting the exception.

**Comment by smitpatel** [comment]
Repro works fine with API changes.
Feel free to open again if you still encounter the exception.
