### ISSUE TITLE
Make sure that our use of DI is disposing contexts correctly

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1113]
Also make sure that other resources owned by the context or its scope are also disposed--e.g connections. Also see #1112.

**Comment by ajcvickers** [comment]
Note for triage: Unassigning since this doesn't have to be done by me.

**Comment by rowanmiller** [comment]
Please discuss with @ajcvickers

**Comment by divega** [comment]
@mikary will you be able to fix this soon?
