### ISSUE TITLE
Code First: One-to-one FK APIs should introduce shadow properties

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#1124]
Given this:

``` c#
modelBuilder
	.Entity<Person2>(
		e => e.OneToOne(p => p.Address, a => a.Resident)
			.ForeignKey(typeof(Address2), "PersonId"));
```

Where "PersonId" has not been defined, we currently throw ModelItemNotFound; should we just add the shadow key instead?

Should we have an overload of ForeignKey like:
```
ForeignKey<TDependent>(string)
```

**Comment by smitpatel** [comment]
Implemented in #3576
