### ISSUE TITLE
LINQ queries that compare related entities should compare based on their keys

### ISSUE THREAD

**Issue by Eilon** [aspnet/EntityFramework#113]
I chatted with @divega and he suggested I log a bug. He thinks this may have worked in LINQ to SQL, but perhaps not in EF.

I have two related entities, for example, a photo gallery that contains many photos. In one part of my app I want to write this kind of query:
`_db.Photos.Where(p => p.Gallery == gallery)`
But apparently the gallery "instance" comparison doesn't work. I have to compare based on the PK value:
`_db.Photos.Where(p => p.GalleryId == galleryId)`

I'm not sure I'd say this is "hugely" important, but part of me had an expectation that this would work.

**Comment by divega** [comment]
Just to add more details based on the discussion on #3141: In EF6 we did not support comparing an in-memory entity instance against an expression representing an entity in the database but we did have some support for a few patterns for comparing entities in the database, e.g. joins in grouping on an entity would in some cases work and the translation would expand the comparison between entities into a comparison of all the individual columns that were part of the entity. 

In the future in EF7.x we should consider supporting those scenarios as well, but when we do it we should consider translating comparisons between entities into comparisons between their keys.
