### ISSUE TITLE
Logging: Glimpse base wish list

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/EntityFramework#1137]
Here are some requirements for logging:

**Basic Requirements:**
 - Connections:
     - ID, Time, Connection String (Key/Full Details), Duration
     - Association Context (Related Transaction ID, as applicable)
 - Transactions:
     - ID, Time, Type (Normal/DTS), Isolation Level, Duration
     - Association Context (Related Connection/Transaction/Command ID, as applicable)
 - Commands:
     - ID, Time, SQL Statement, Duration, Affected Records, Stack
     - Parameter Name/Values/Types
     - Association Context (Related Connection/Transaction ID, as applicable)
 - Exceptions:
     - Exception Details, Stack
     - Association Context (Related Connection/Transaction/Command ID, as applicable)

**Wish List:**
 - Entity Framework:
     - Query tree that generated the SQL
         - The idea being that we would like to reverse engineer a linq statement which roughly looks like what the user might have written  
         - Note, we have no idea how we would do this and that there are got ya's but the idea is there
         - Model details - which properties are lazy loaded, etc
     - Configuration settings
         - Any and all details about how EF is configured, which providers it used to determine that configuration, etc
     - General events
         - Query compilation - when that happens, if its cached, what did it do, etc 
         - Other interesting things that you guys would know that are important to advanced EF users 

I would love to see this list built out to include other things that I haven't thought of and other use cases.

**Comment by spacecat** [comment]
Is this for SQL Profiler? Because today, I had an issue with Transaction Isolation Level not showing me the right value in an Audit Login event (or not showing me Entity Framework 6 transaction isolation level at all when using a using (var dbContextTransaction = context.Database.BeginTransaction(System.Data.IsolationLevel.Serializable))) for some reason and I stumbled upon this github issue searching for the word "isolation" and thought maybe the problem I'm having and this thread are related?

**Comment by divega** [comment]
@anpete I found this in our backlog and thought it should be assigned to you so you can put a check on what we have done and possibly find other things we could do soon.

**Comment by avanderhoorn** [comment]
As a side note, this issue was created prior to having Diagnostics Source (previously Telemetry Source). The same requirements are still there but on top of Diagnostics Source.

**Comment by anpete** [comment]
@avanderhoorn Can this be closed?
