### ISSUE TITLE
Migrations: Improve functional test coverage

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1141]
Probably by porting existing tests from EF6

**Comment by bricelam** [comment]
Here are some scenarios I want to cover.
- [ ] `CSharpMigrationOperationGenerator` can round-trip operations through the compiler
- [ ] `ModelDiffer` can detect operations
  - [ ] ...and handle entity or property renames
  - [ ] ...and table or column renames
  - [ ] ...and sort correctly
- [ ] `MigrationSqlGenerator` can apply operations to the database

**Comment by roji** [comment]
Just wanted to know the state of migration functional tests before attacking migrations in PostgreSQL... There seem to be some non-inherited migration tests within each provider's testsuite but nothing comprehensive I can actually use. Should I wait a bit, are there plans to work on this?

**Comment by bricelam** [comment]
@roji, So far, there are just unit tests to verify the SQL. You can copy these to use in your own unit tests. I also plan to create some provider-inheritable functional tests. I started in [bricelam:migtests](https://github.com/aspnet/EntityFramework/compare/dev...bricelam:migtests), but they were way too slow! We have some ideas on how to do it faster, but I haven't gotten around to implementing it yet.

**Comment by bricelam** [comment]
I've added some basic functional tests that cover the `HistoryRepository` in #2733

**Comment by bricelam** [comment]
Closing. I feel like our coverage is pretty decent now. We'll rely on app building, exploratory testing, and code coverage analysis for more. Creating more provider-agnostic tests will be done as part of #1807.
