### ISSUE TITLE
Exploratory Testing: Migrations

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1162]
Scenarios of note:
- [ ] Generic `DbContext` types
- [ ] Multiple contexts per database
- [ ] Multi-tenant

**Comment by mikary** [comment]
Ran through Blog/Post sample workflow in VNext and classic console application projects and opened #1345 and #1347.

**Comment by rowanmiller** [comment]
We're happy this has been covered by app building etc.
