### ISSUE TITLE
Exploratory Testing: Shadow state

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1166]

**Comment by divega** [comment]
@mikary moving this to your plate. When chat about what it encompasses whenever you are ready.

**Comment by mikary** [comment]
The interaction between ```FromSql``` and shadow state hasn't been tested yet, this is an area that could use some coverage.

**Comment by rowanmiller** [comment]
The only thing we need to do for RC is verify that query works with the new API pattern we decided on. After that, this can move to the 7.0.0 milestone if there is anything we think needs doing.

**Comment by rowanmiller** [comment]
We are happy that we have covered this
