### ISSUE TITLE
Windows 10 UWP support (formerly UAP, formerly Phone and Store)

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1170]
We're going to temporarily move SQLite (and other providers) out of the working branch while we sure up the core of EF (focusing on ASP.NET 5 and SQL Server). 
This is a parent work item to track re-enabling Phone/Store apps once we move SQLite back in (docs, testing, etc.)

**Comment by bricelam** [comment]
Everything is up-to-date on our end. We're just waiting on some updates to the System.Data.Common package.

**Comment by rowanmiller** [comment]
Re-opening this to track the all up scenario on our end since it's not completely working yet. Marking as blocked since we are waiting on updates from another team.

**Comment by divega** [comment]
@rowanmiller should this stay assigned to you or be assigned to @bricelam or @natemcmaster?

**Comment by rowanmiller** [comment]
Yeah it should be reassigned

**Comment by divega** [comment]
Assigning to @bricelam for now.

**Comment by rowanmiller** [comment]
This is done. We will continue to test with each release
