### ISSUE TITLE
Consider changes to Migrations to allow creation resiliency to be used

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1178]
See Issue #985. This mechanism doesn't currently kick in when ApplyMigrations causes the database to be created. This is because the mechanism is implemented outside of the migration operation, which is in turn because migrations operations cannot execute some arbitrary code as oppose to just generating SQL that can be executed.

**Comment by rowanmiller** [comment]
@lukewaters - This is covered by your current changes?

**Comment by lukewaters** [comment]
I don't think so, we are still executing the same codepath, just in a more conditional manner.

**Comment by rowanmiller** [comment]
Moving to @bricelam as he is going to look at this as part of his migrations work.
