### ISSUE TITLE
ModelBuilder is not dynamically selected by provider in the correct way

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1181]
ModelBuilder is added as a common service in AddEntityFramework but an attempt is made to specialize in AddAzureTableStorage.

If the ModelBuilder needs to be specialized, then it needs to be dynamically selected as part of the provider services such that multiple providers can register different model differs without one hiding another.

Note that the cross-store functional tests are not currently catching this issue.

**Comment by AndriySvyryd** [comment]
Clearing the fields for triage since this needs to be implemented in the provider and only the ATS provider needs it currently.
