### ISSUE TITLE
Implement ChangeTracker.HasChanges

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1198]

**Comment by shawnwildermuth** [comment]
Can we help implement it? It's pretty important.

**Comment by rowanmiller** [comment]
Yeah I think this would make a great contribution. It's only on our backlog because we are swamped getting the 'must have' stuff for the core framework implemented. Provided it comes with unit tests etc. I'd say go for it.

cc @divega @ajcvickers to make sure they agree.

**Comment by divega** [comment]
Sounds great!

**Comment by ajcvickers** [comment]
+1
