### ISSUE TITLE
Implement CurrentValues, OriginalValues, and GetDatabaseValues on EntityEntry

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1200]

**Comment by leo90skk** [comment]
when will this feacture be implemented? I need it for a update function in an update method in a service (N-Tire architecture).

**Comment by rowanmiller** [comment]
Currently planned for 1.1 - see https://blogs.msdn.microsoft.com/dotnet/2016/07/29/entity-framework-core-1-1-plans/ for details.

**Comment by dstep2007** [comment]
I see 1.1 was just released.  Did this make it into the release?

**Comment by smitpatel** [comment]
@dstep2007 - Yes.
