### ISSUE TITLE
Model validation

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#1205]
The first time the model is used we should check it for validity to provide actionable exceptions.
This would include ambiguities found by conventions (#1171 is related).

**Comment by rowanmiller** [comment]
@AndriySvyryd  can you drive design on this one

**Comment by mikary** [comment]
Validation should also check for unbreakable key cycles like the ones described in #1417

**Comment by mikary** [comment]
After further discussion on #1417, it looks like the validation should ensure that there is exactly one value generator per sequence of keys (key chain), and cycles should be fine as long as a generator exists.

**Comment by AndriySvyryd** [comment]
Ambiguities found by conventions will be logged by conventions, see #1171

**Comment by AndriySvyryd** [comment]
Fixed in 7741bfdc7a1372ac92301752333d597c14d8915e
