### ISSUE TITLE
SQLite Add-Migration failing when OneToMany present

### ISSUE THREAD

**Issue by vincentlecours** [aspnet/EntityFramework#1209]
I'm using nightly build 11712 in VS2013 and following instructions from the wiki for both Windows Store/Phone app and traditional .NET apps and can't get the migrations part working on SQLite. Every time I'm executing command "Add-Migration FirstMigration" I'm receiving this error message: "Operation is not valid due to the current state of the object.". From what I understand, either the migration can't access the SQLite DB or it has never tried to open and read it. Tried suggestion from issue #1058 to convert the WinRT path to normal path, without success.

**Comment by bricelam** [comment]
This appears to be fixed now.
