### ISSUE TITLE
Query :: string.Contains could be translated to LIKE '%foo%'

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1210]
We should do that at least in the filters. We do that already for StartsWith and EndsWith.

**Comment by DanielVF** [comment]
Looking at https://github.com/aspnet/EntityFramework/blob/596beb536d61a0d30223fd299480d34f6a5bc8a9/src/EntityFramework.Relational/Query/Methods/ContainsTranslator.cs

It seems like EF7 is doing this already? Or am I wrong?

**Comment by maumar** [comment]
you are correct, closing
