### ISSUE TITLE
Use EF7, Linq Left Join Where Select is error.

### ISSUE THREAD

**Issue by yuezhongxin** [aspnet/EntityFramework#1232]
Hi, Linq left join for different grammar, I use EF6, EF7 were tested, but the test results are completely different, I hope you can help me, because my project is using it, thank you! 

For more details see this blog: [EntityFramework 7 Left Join Where Select 奇怪问题](http://www.cnblogs.com/xishuai/p/ef7-linq-left-join-where-select-error.html)

**Comment by npehrsson** [comment]
When will this be available?

**Comment by divega** [comment]
@maumar just a reminder that we looked at this item and we thought it would be a good idea to tackle it next.

**Comment by anpete** [comment]
Initial work completed.

**Comment by divega** [comment]
Yay!
