### ISSUE TITLE
Use EF7, Linq Contains In is error.

### ISSUE THREAD

**Issue by yuezhongxin** [aspnet/EntityFramework#1243]
Test as follows:

![](http://images.cnitblog.com/blog/435188/201412/071619397642196.png)

Exception Details:

![](http://images.cnitblog.com/blog/435188/201412/071629524365454.png)

For more details see this blog: [EntityFramework 7 Linq Contains In 奇怪问题](http://www.cnblogs.com/xishuai/p/ef7-linq-contains-in-error.html)

**Comment by maumar** [comment]
Bumping priority, since a few customers asked about this, and one of the dupes was triaged as Pri0

**Comment by rowanmiller** [comment]
Confirmed that this now translates, the generated SQL is 

```SQL
SELECT [b].[BlogId], [b].[Url]
FROM [Blog] AS [b]
WHERE [b].[Url] IN ('a', 'b', 'c')
```

**Comment by rowanmiller** [comment]
@maumar just checking there was no other reason this was left open?

**Comment by docseuss** [comment]
I just upgraded to EF7 Core 1.0 and I am trying to migrate some of my API 2.0 / EF 6 code over to the new version and most stuff is migrating OK, however the contains is not throwing an exception but no results are returned when a where clause has a contains in it. Is this still a bug?

My Old EF6 Code
string[] ocmDrugs = _genericDrugs.Concat(_brandDrugs).ToArray();

            List<AgentDTO> agents = (from drugs in db.xref_agt_pt
                                     where ocmDrugs.Contains(drugs.agt_name.ToUpper()) && drugs.status.ToUpper() != "I"
                                     select new AgentDTO
                                     {
                                         PatientID = drugs.pt_id.Trim(),
                                         Name = drugs.agt_name.Trim(),
                                         IsActive = drugs.status.Trim(),
                                         DateOrdered = drugs.date_of_last_dose,
                                         DateEnded = drugs.date_ended
                                     }).Distinct().OrderBy(o => o.DateOrdered).ToList();
            return agents;

My new EF7 Migration of this code
`string[] ocmDrugs = _optionsAccessor.GenericAgents.Concat(_optionsAccessor.BrandAgents).ToArray();

            var results = _context.XrefAgtPt
                .Where(drug => drug.Status.ToUpper() != "I" && ocmDrugs.Contains(drug.AgtName.ToUpper()));

            results.ToList();

            return Json(results);

Now if I take out the  `ocmDrugs.Contains(drug.AgtName.ToUpper())` piece then the code executes and returns results. If I leave it in there the code executes but returns no results. I have checked and yes the list contains elements and really have refactored this LINQ statement a bunch of different ways, but regardless any time I throw a contains into the mix I get nada.

Anyone have any ideas or is this just a bug still?
