### ISSUE TITLE
ChangeTracker ::: NRE when inserting values to a model with multiple One-To-One relationships

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1278]
Consider the following model:

```
    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public House Home { get; set; }
        public House SummerHouse { get; set; }
        public int HomeId { get; set; }
        public int? SummerHouseId { get; set; }
    }

    public class House
    {
        public int? Id { get; set; }
        public string Name { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Person> People { get; set; }

        public DbSet<House> Houses { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<House>().Property(h => h.Id);
            modelBuilder.Entity<Person>().Property(h => h.Id);
            modelBuilder.Entity<Person>().OneToOne(p => p.Home).Required(true).ForeignKey<Person>(h => h.HomeId);
            modelBuilder.Entity<Person>().OneToOne(p => p.SummerHouse).Required(false).ForeignKey<Person>(h => h.SummerHouseId);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "NullableOneToOne", IntegratedSecurity = true }.ToString());
        }
    }
```

and the following code:

```
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var maurycy = new Person { Name = "Maurycy" };
                var maurycysHome = new House { Name = "Maurycy's Home" };
                var maurycysSummerHouse = new House { Name = "Maurycy's Summer House" };

                var radomir = new Person { Name = "Radomir" };
                var radomirsHome = new House { Name = "Radomir's Home" };

                maurycy.Home = maurycysHome;
                maurycy.SummerHouse = maurycysSummerHouse;
                radomir.Home = radomirsHome;

                ctx.People.Add(maurycy, radomir);
                ctx.Houses.Add(maurycysHome, maurycysSummerHouse, radomirsHome);
                ctx.SaveChanges();
            }
```

This throws the following:

Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at Microsoft.Data.Entity.Metadata.ClrPropertySetter`2.SetClrValue(Object inst
ance, Object value)
   at Microsoft.Data.Entity.ChangeTracking.StateEntryMetadataServices.WriteValue
(Object entity, IPropertyBase propertyBase, Object value)
   at Microsoft.Data.Entity.ChangeTracking.StateEntry.WritePropertyValue(IProper
tyBase propertyBase, Object value)
   at Microsoft.Data.Entity.ChangeTracking.StateEntry.set_Item(IPropertyBase pro
perty, Object value)
   at Microsoft.Data.Entity.Identity.ForeignKeyValuePropagator.PropagateValue(St
ateEntry stateEntry, IProperty property)
   at Microsoft.Data.Entity.ChangeTracking.ValueGenerationManager.Generate(State
Entry entry)
   at Microsoft.Data.Entity.ChangeTracking.StateEntry.SetEntityState(EntityState
 entityState)
   at Microsoft.Data.Entity.ChangeTracking.EntityEntry.SetState(EntityState enti
tyState)
   at Microsoft.Data.Entity.DbContext.SetEntityStates[TEntity](TEntity[] entitie
s, EntityState entityState)
   at Microsoft.Data.Entity.DbContext.Add[TEntity](TEntity[] entities)
   at Microsoft.Data.Entity.DbSet`1.Add(TEntity[] entities)
   at NullableOneToOne.Program.Main(String[] args) in D:\Projects\NullableOneToO
ne\NullableOneToOne\Program.cs:line 69

**Comment by mikary** [comment]
This issue does not appear to repro anymore.

Did not throw as written or with the following corrections:
* Moved Requred calls to follow ForeignKey calls
* Made House.Id non-nullable

**Comment by mikary** [comment]
Going to double check with @maumar before closing
