### ISSUE TITLE
Configuring many-to-one relationships in fluent API results in shadow-state FKs even when explicitly configured not to

### ISSUE THREAD

**Issue by lukewaters** [aspnet/EntityFramework#1288]
This is similar to #1284 

Some relationships that can be configured as one-to-many throw when the reverse relationship is configured as many-to-one

This configuration works:
```
builder.Entity<DbProductSubcategory>(b =>
b.OneToMany(subcategory => subcategory.Products, product => product.ProductSubcategory)
.ForeignKey(product => product.ProductSubcategoryID))
```

while this configuration doesn't:
```
builder.Entity<DbProduct>(b => 
b.ManyToOne(product => product.ProductSubcategory, subcategory => subcategory.Products)
.ForeignKey(product => product.ProductSubcategoryID))
```
An exception is thrown saying that ProductSubcategoryIDKey is an invalid column name.

**Comment by mikary** [comment]
Ran the provided sample and it did not throw any exceptions. Checked with @AndriySvyryd and he suggested this was likely resolved by another fix in the last few days.
