### ISSUE TITLE
Perf: Bottleneck on NavigationFixer.InitialFixup

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1334]
Profiling some of the major perf differences between EF6 and EF7 shows that we are spending a lot of time in `Microsoft.Data.Entity.ChangeTracking.NavigationFixer.InitialFixup` for the EF7 tests.

Test | EF6 | EF7 | Time in InitialFixup(..)
------------ | ------------- | ------------- | -------------
Query_Simple_LoadAll | 26 ms |  367 ms | 62%
Query_Simple_Include | 147 ms | 12537 ms | 95%

**Comment by divega** [comment]
@rowanmiller This could have been improved by https://github.com/aspnet/EntityFramework/pull/2734. Is it easy to get new numbers?

**Comment by rowanmiller** [comment]
Yep they run every night, will have numbers tomorrow morning

**Comment by natemcmaster** [comment]
@divega 
![ef-tc-1](https://cloud.githubusercontent.com/assets/2696087/9147267/88ee945c-3d19-11e5-8e86-137f93546f8f.png)

**Comment by natemcmaster** [comment]
...not that total CI time is the most empirically sound evidence, but yeah, it's getting better.

**Comment by divega** [comment]
Thanks for the beautiful chart @natemcmaster! :smile: Nice to see some numbers going in the right direction. BTW, I bet https://github.com/aspnet/EntityFramework/pull/2745 is one of the other dots where the line goes down.

**Comment by divega** [comment]
Also, let's keep this item open. @ajcvickers can close it when he decides he has done enough.

**Comment by rowanmiller** [comment]
@ajcvickers do you have anything else planned for this or can we close it out now?

**Comment by ajcvickers** [comment]
@rowanmiller Still working on it since InitialFixup as used by Add/Attach/Update needs some work.

**Comment by ajcvickers** [comment]
Done everything I was planning on here, so closing this issue.
