### ISSUE TITLE
Flag to allow application data in logging

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1374]
From a security point of view we decided that, by default, both the message action and state passed to ILogger.Write should not contain any application data. That is, data that comes from the data store or may be supplied by an end user of the application. Depending on the application, this data may contain sensitive information (usernames, credit card numbers, etc.). Examples include, results from queries, values stored in entity instances, and constant values used in LINQ expressions.

We'll have a simple flag that can be enabled to allow this information to be included. This is especially useful for logging queries, where it is helpful to have the parameter values logged along with the query.

This work item includes:
- [x] Creating the flag (off by default)
- [ ] Reviewing existing logging to make sure it honors the flag
- [ ] Writing a warning to the log when the flag is enabled (once per context, ServiceProvider, or whatever is easiest)
- [ ] Wherever data is filtered out of a message, include a message in place of the data letting folks know they can enable the flag to get the data (and a warning that it may result in logging sensitive info) 

We should try and add this in a way that makes it easy to use it for future logging that we add.

**Comment by rowanmiller** [comment]
@lukewaters please work with @anpete to get some direction on this one

**Comment by divega** [comment]
@rowanmiller @anpete @ajcvickers need to find an owner for this.

**Comment by rowanmiller** [comment]
Didn't we handle this with a log level that applies across all technologies?

**Comment by anpete** [comment]
This should probably be replaced by a bug to switch from logging to event notification.

**Comment by lukewaters** [comment]
@rowanmiller I did add a Debug log level and a minimum level to logging a couple months ago, the minimum level prevented more detailed level messages from being distributed to registered loggers for security purposes

**Comment by divega** [comment]
@lukewaters Can we assume that the states of check boxes in the check list is up to date? Thanks!

@anpete Yeah probably. I see that as part of what the new owner would need to figure out. Are you volunteering? :smile:

**Comment by anpete** [comment]
Yes I am. :-)

**Comment by lukewaters** [comment]
@divega The flag is in place, and I Added the LogParamenters flag in [RelationalLoggingExtensions](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Extensions/RelationalLoggerExtensions.cs) I think EF also logs a message whenever DbContext is initialized

**Comment by divega** [comment]
Thanks again!

**Comment by divega** [comment]
@anpete all yours!
