### ISSUE TITLE
Disable parallelization of performance microbenchmark execution.

### ISSUE THREAD

**Issue by lukewaters** [aspnet/EntityFramework#1376]
This will ensure that tests are not competing for resources and will make the results more consistent

**Comment by lukewaters** [comment]
adding this attribute to test class should fix this issue
```
[assembly: Xunit.CollectionBehaviorAttribute(DisableTestParallelism = true)]
```

**Comment by rowanmiller** [comment]
Done in ae536e41e3201283707080b3f3c4397389cda568
