### ISSUE TITLE
Attach should not reject changes

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1385]
Issue #742 made changing state from Modified to Unchanged be a reject changes operation, as it was in EF6. However, because Attach uses this directly it means that attaching an object that is Modified now also rejects changes. There are scenarios where this would be correct, but Attach mostly means "the object as it is now is how it is in the database" and hence if the object happens to already be modified with changes then these changes should not be rejected. This was the behavior in EF6.

Here is a full list of state change behaviors in EF6. "Special" behaviors bold.I believe that this bug covers the only one that is still different in EF7. (Other than throwing on Remove for detached objects, which I don't think we want to replicate in EF7.)

Action/Initial state | Unchanged | Modified | Added | Deleted | Detached
-----------------------|----------------|------------|----------|------------|-------------
Set Unchanged | Unchanged | **Unchanged (reject)** | Unchanged | Unchanged | Unchanged
Attach | Unchanged | Unchanged (accept) | Unchanged | Unchanged | Unchanged
Set Added | Added | Added | Added | Added | Added
Add | Added | Added | Added | Added | Added
Set Deleted | Deleted | Deleted | Deleted | Deleted | Deleted
Remove | Deleted | Deleted | **Detached** | Deleted | **Throws**
Set Modified | Modified | Modified | Modified | Modified | Modified
Set Detached | Detached | Detached | Detached | Detached | Detached

**Comment by lukewaters** [comment]
Fixed in #1562
