### ISSUE TITLE
Discussion around API for MVC DI wireup

### ISSUE THREAD

**Issue by ctolkien** [aspnet/EntityFramework#1388]
Firstly, apologies if I've missed some guidance somewhere on making this work.Taken from [this wiki page](https://github.com/aspnet/EntityFramework/wiki/Configuring-a-DbContext), all the examples have a controller taking a direct dependency on a context, not an interface.

Looking at the default wireup for EF services in MVC:

```
// Add EF services to the services container.
services.AddEntityFramework(Configuration)
    .AddSqlServer()
    .AddDbContext<SomeDbContext>();
```

There doesn't seem to be a way to register this context in the DI container as an interface? 

Perhaps something like
```
.AddDbContext<SomeDbContext, IAsThisDbInterface>()
```

**Comment by rowanmiller** [comment]
We should still register as the context type in addition to the other type (to support tooling etc.)

**Comment by divega** [comment]
If we do register both we need to do it in a way that you get the same instance regardless of what type you ask for (simply registering both services won't do that).

**Comment by rowanmiller** [comment]
I don't think we need anything EF specific here, as DI already allows you to register an interface (or base type) to resolve to another service that is already registered in DI.

```
services.AddScoped<IAsThisDbInterface>(servideProvider => servideProvider.GetRequiredService<SomeDbContext>());
```

@divega agree that this can be closed?

**Comment by ctolkien** [comment]
I'm happy with the scenario @rowanmiller  has outlined above as a solution.
