### ISSUE TITLE
Implement PropertyEntry.OriginalValue

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1396]
Issue #1200 is about implementing the methods on EntityEntry that get all current values, original values, etc. But on PropertyEntry there is already a CurrentValue property which is much less hassle to use than dropping down to the low-level StateEntry. It should be easy to implement a similar OriginalValue property which would then make things like concurrency resolution easier.

**Comment by smitpatel** [comment]
finished via e969e53ae5d43655f65921cef05288febe558238
