### ISSUE TITLE
DI config in startup code with options constructor throws InvalidOperationException

### ISSUE THREAD

**Issue by mikary** [aspnet/EntityFramework#1401]
```cs
    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions options)
            : base(options)
        {
        }
    }

    public class Program
    {
        public void Main(string[] args)
        {
            var serviceProvider = new ServiceCollection()
                .AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<MyContext>(options =>
                {
                    options.UseSqlServer("Data Source=(localdb)\\v11.0;Initial Catalog=MyDBFull;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=30");
                })
                .ServiceCollection
                .BuildServiceProvider();

            var context = serviceProvider.GetService<MyContext>();
        }
    }
```

Output:
```
System.InvalidOperationException: Unable to resolve service for type 'ContextOptionsConstructor.MyContext' while attempting to activate 'Microsoft.Data.Entity.DbContextOptions'.
   at Microsoft.Framework.DependencyInjection.TypeActivator.ConstructorMatcher.CreateInstance(IServiceProvider _services)
   at Microsoft.Data.Entity.Infrastructure.DbContextActivator.CreateInstance[TContext](IServiceProvider serviceProvider) in C:\Projects\AspNet\EntityFramework\src\EntityFramework.Core\Infrastructure\DbContextActivator.cs:line 33
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at ContextOptionsConstructor.Program.Main(String[] args) in C:\Projects\turnt-sansa\ConfigurationAndDi\ContextOptionsConstructor\src\ContextOptionsConstructor\Program.cs:line 22
```

**Comment by rowanmiller** [comment]
@mikary - can you confirm that this works in Startup.cs and is only failing when used outside of ASP.NET 5?

**Comment by mikary** [comment]
I was able to reproduce this issue in an ASP.NET 5 web app using Startup.cs and an MVC controller taking a dependency on the context.

**Comment by divega** [comment]
I don't remember precisely but maybe we ended up only registering the generic `DbContextOptions<MyContext>` as a service.

**Comment by rowanmiller** [comment]
Ah, yes @divega is correct... I remember hitting this in the past

**Comment by divega** [comment]
I guess this bugs counts as a vote for adding the non-generic `DbContextOptions` as a service when `AddDbContext<TContext>()` is called. Do you guys think we should do it? Should we do it now? Is it ok if when you have multiple calls to `AddDbContext<TContext>()` the last configuration added wins?

**Comment by ajcvickers** [comment]
Discussed with @divega. Two things:
* Exposing a constructor that takes a `DbContextOptions` is not needed in this case. It would be interesting to hear from Micah whether it seemed to him that it was needed, or whether he was just testing all possibilities.
* I think we should add options as a service typed by as non-generic `DbContextOptions`, and Diego is okay with doing this. This falls down in the case whether there are two contexts and both expose constructors that take the non-generic `DbContextOptions`. In this case one context will get the wrong options. However, because the instance it gets is still of the generic type even though it is typed as non-generic we can actually check in the base constructor that the instance we have is the correct one and throw a helpful message if it isn't. In other words, in the base `DbContext` constructor, check if the `DbContextOptions` instance is a `DbContextOptions<TContext>`. If it is, then check if the `TContext` is our context. If it isn't, then throw.

**Comment by mikary** [comment]
For my testing, I was just trying to cover all of the possibilities.

 From a DI perspective, I don't think the ```DbContextOptions``` adds much. We can already use settings from ```Configuration```, the ```DbContextOptions``` action on ```AddDbContext<TContext>```, or by overriding ```OnConfiguring```.

 For non-DI, there does seem to be some value for an implicit service provider scenario, ex:
```cs
var contextOptions = new DbContextOptions();
contextOptions.UseSqlServer(connectionString);
using (var context = MyContext(contextOptions)
{
    // ...
}
```
At the same time, it seems like it would be about as easy for someone to pass settings in through the constructor and save them off for use in ```OnConfiguring```.

**Comment by rowanmiller** [comment]
Like the suggestion from @ajcvickers / @divega (especially throwing if we detect the wrong generic param on the options). If folks have a basic understanding of DI I think they would expect to need to take the options as a ctor parameter (that felt natural to me when I was app building).

**Comment by smitpatel** [comment]
@mikary - I am not able to repro this. If this is working fine then close it?

**Comment by smitpatel** [comment]
no repro anymore. closing this.
