### ISSUE TITLE
Save original connection string so it can be cloned reliably.

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1406]
In the old stack we cloned the original connection string before using it. Then when we needed to clone the connection string to create a connection to the master database we didn't end up using the connection string with credentials stripped out. This is somewhat less important in EF7 because we don't have database initializers, but it could still be a problem for people using Exists, EnsureCreated, etc., and possibly for Migrations.

**Comment by lukewaters** [comment]
This item can be expanded to include the work involved in adding a Clone method to SqlConnection to allow reliable cloning of a connection with all options.

**Comment by ajcvickers** [comment]
Closing because #1796 has more details.
