### ISSUE TITLE
Code First: Read-only properties are included in model by convention?

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#1407]
Noticed this line in NorthwindQueryFixtureBase:

modelBuilder.Entity<Customer>(e => { e.Ignore(c => c.IsLondon); });

IsLondon is a read-only property, and would not have been mapped in EF6.

**Comment by smitpatel** [comment]
Removed that line and builds successfully. Is this fixed via some update in past?

**Comment by smitpatel** [comment]
Also verified in independent app that readonly properties are not being mapped.

**Comment by smitpatel** [comment]
already fixed in 995e7c7f2cc009e5d026e4ab1ae7aad95bc948ee
