### ISSUE TITLE
Consider blocking inheritance scenarios until we have proper support

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#1423]
#247 covers adding support for some inheritance scenarios and per #743 we made sure we do not allow instances of unmapped derived types to be passed to APIs. However it seems that we should understand better what happens when the application tries to map two or more members of the same inheritance hierarchy in the same model and how whatever behavior we have now would break once we add proper inheritance support. If the break is rather obscure and/or can have severe consequences we should consider blocking the scenario.

**Comment by divega** [comment]
@lukewaters Please start by investigating what the current behavior is. We can then decide what we want to do.

**Comment by lukewaters** [comment]
Closing as work has begun on inheritance starting with aabb95f
