### ISSUE TITLE
Where() on properties of the short type does not generate a sql WHERE clause.

### ISSUE THREAD

**Issue by rmja** [aspnet/EntityFramework#1439]
I have a table `Table1` with the following (relevant) columns: Id, SmallintId, IntId. SmallintId is of type smallint not null in SQL Server, IntId is of type int not null, and the `Table1` POCO model has a SmallintId property of the `short` type and an IntId of the `int` type.

I have the following observations:
The following queries does not produce any sql `WHERE` clause:

    context.Table1.Where(x => x.SmallintId == 17)
    context.Table1.Where(x => x.IntId == 42).Where(x => x.SmallintId == 17)

The following queries does produce a sql `WHERE` clause but *only* for the IntId column:

    context.Table1.Where(x => x.IntId == 42)
    context.Table1.Where(x => x.SmallintId == 17).Where(x => x.IntId == 42)

This issue might be related with #1426.

**Comment by RickyLin** [comment]
Interesting. I tried it out. No where clause was generated if the property was of short type.
There are 2 issues here.
1. the same issue as #1426 
2. "Where() on properties of the short type does not generate a sql WHERE clause"

**Comment by RickyLin** [comment]
@rmja - somehow It seems that Remotion.Linq translated  `x.SmallintId == 17` into `Convert(x.SmallIntId) == 17`, convert `x.SmallIntId` to `int` first, then compare to 17. The EF can't recognize `Convert` expression so no sql statement was generated.
I tried `x.SmallIntId == (short)17`, but the WhereClause was still `Convert(x.SmallIntId) == 17`.

Need further investigation.

**Comment by divega** [comment]
Those converts are added by the compiler because they are implicitly already there: the equality operator is not defined for short so but for int. We need to remove them or ignore them.

**Comment by ilmax** [comment]
@divega it's a difficult task,I worked a little bit on it for EF6 see [here].(https://entityframework.codeplex.com/SourceControl/changeset/3982678d5a359f37e82464aba71ea69452b03ef7) Making the long story short, it happens a lot of times analyzing the expression tree (Linq query) we totally forgot information about the type (e.g short). In those cases we may rely on EF's metadata, but there will remain corner cases where convert elimination will be impossible.
