### ISSUE TITLE
PostgreSQL Provider

### ISSUE THREAD

**Issue by sgentile** [aspnet/EntityFramework#1458]
Any plans to support Postgres ?

**Comment by ErikEJ** [comment]
See Rowans comment here: https://github.com/aspnet/EntityFramework/issues/1340

**Comment by sponnet** [comment]
We are working on an EF7 implementation for PostgreSQL 
https://github.com/npgsql/npgsql/issues/249
If you want to participate in development or testing, please let us know.

**Comment by bricelam** [comment]
@sponnet I was hoping the Npgsql community would be on top of that. :smile:

**Comment by rowanmiller** [comment]
+1 really glad to hear you are working on it already. There is next to no documentation at the moment and things are still churning in the code base... so feel free to reach out if you have questions.

**Comment by borgdylan** [comment]
@sponnet if you want to merge your work into what I had started you are free to send me a PR or point me to to your repo so I could merge it in.

Also if others have a prototype implementation, I am willing to test and give feedback. As a note, I am running Postgres 9.4 i.e the latest stable release.

**Comment by roji** [comment]
Just noticed this... I've been working on an EF7 PostgreSQL/Npgsql provider and while it's still far from complete it's slowly starting to be usable.

I post progress every now and then to https://github.com/npgsql/npgsql/issues/249 (I guess this issue can be closed?)

**Comment by rowanmiller** [comment]
@roji agreed that we can close this as the work is being tracked in your side.
