### ISSUE TITLE
Support multiple calls to UseSqlServer (or other provider)

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1473]
Currently it appears to be "last wins", but it may be better to throw to avoid confusion such as https://github.com/aspnet/EntityFramework/issues/1455

**Comment by rowanmiller** [comment]
@mikary is this done?

**Comment by mikary** [comment]
Decided in design meeting that the desired behavior is "Last Wins"
Going through to verify/update behavior and tests to ensure they are consistent with this decision

**Comment by mikary** [comment]
Confirmed that this is the implemented behavior, test coverage is in the `DbContextOptionsTest`.

Note: If a Connection String is configured and the configuration is updated to use a `DbConnection`, both settings will be applied and an `InvalidOperationException` will be thrown by the `RelationalConnection`. This is the intended behavior.
