### ISSUE TITLE
Enforce "name=xyz" syntax for named connection strings in configuration

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#1480]
Per #1391 we decided to stop using `"ConnectionStringKey" : "xyz"` as a way to specify that the actual connection string is defined in a configuration key `"xyz"`. We started supporting the form `"ConnectionString" : "name=xyz"` instead. But as a consequence of adopting parts of the EF6 implementation we also started supporting the form `"ConnectionString" : "xyz"` (i.e. given any "xyz" string that does not contain an equals sign we assume it is a configuration key that needs to be dereferenced to obtain the actual connection string). 

After discussing with @rowanmiller we decided that we should remove support for the latter since:

1. We want to keep the number of rules customers need to understand to the minimum 
2. We don't really need yet another way of configuring a connection string
3. In the future we may potentially support other kinds of connection strings which may not contain equal signs and which however are not configuration keys, e.g. hypothetically some non-relational store could use a URI as its connection string. When we do so it would be nice if we didn't need to special case such store (or relational, or any particular kind of store) and that we could instead have a single version of this code reading all sorts of connection strings from configuration across all kinds of databases.

**Comment by smitpatel** [comment]
fixed via 44bedde79bb3f81fdfaeec12b350aa81c4dac892
