### ISSUE TITLE
Migrations: Replace usage of BasicModelBuilder with direct calls to core metadata

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#1484]
Currently model snapshots get scaffolded as calls to BasicModelBuilder, but the latter is going away as described in #908.  

Although most scenarios we originally envisioned for BasicModelBuilder can be handled by a "regular" ModelBuilder without the conventions, after discussing with @bricelam and @ajcvickers we agreed that the ModelBuilder API is not the best choice for model snapshots.

Instead we would like to use direct calls to the core metadata API.  

We were considering a JSON representation of the model, described in #1355, but we believe that now should be moved to the backlog.

**Comment by divega** [comment]
@smitpatel please figure out with @bricelam how to best integrate this change with his work on migrations.

**Comment by bricelam** [comment]
@smitpatel I wrote a blog post, [C# Object Notation](http://bricelam.net/2015/02/01/csharp-object-notation.html), on some language features we can use to try and make the format as terse as possible.
