### ISSUE TITLE
SqlServerGearsOfWarQueryTest includes initialization SQL in assert

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1485]
/cc @maumar 

After changing the database initialization to be non-async (See #1483), the first SqlServerGearsOfWarQueryTest that runs now includes the database creation SQL in the SQL log, causing it to fail. The log should only be used for the test query, or the log should be cleared after initialization has happened.

Tests are currently disabled.

**Comment by maumar** [comment]
fixed in 3ae3a838c019ab28e17336557ad17334accfaf40
