### ISSUE TITLE
RelationalDbContextOptions namespace?

### ISSUE THREAD

**Issue by dazinator** [aspnet/EntityFramework#1493]
I'm writing a relational provider, and came across the `RelationalDbContextOptions` class - which is in the EntityFramework.Relational assembly, but it's namespace is `Microsoft.Data.Entity.SqlServer.Extensions`

I am just wondering why it's in a `SqlServer` namespace - shouldn't it be provider agnostic?

**Comment by divega** [comment]
Thanks for letting us know. It is possibly that we missed cleaning things up after refactoring. @mikary can you take a look?
