### ISSUE TITLE
Using an alternate key in ModelBuilder API can fail if PK relationship was discovered by convention

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1495]
This may be related to Issue #1398 since in this case the type of the PK and the alternate key are different, resulting in the same exception as in that bug. However, in this case the root cause seems to be that the PK relationship has already been discovered and configured by convention. This means that the workaround for #1398 does not work here--the exception is thrown regardless of whether the ForeignKey call or the ReferencedKey call is made first.

See GraphUpdateTestBase for repro code--model is big, so not copying it all here.

**Comment by AndriySvyryd** [comment]
Fixed in 10d3f43
