### ISSUE TITLE
Re-enable tests skipped to unblock CI

### ISSUE THREAD

**Issue by pranavkm** [aspnet/EntityFramework#1499]
Revert this changeset: e1fb1deaeda8890ce1567176c68381abc3988161

**Comment by divega** [comment]
@anpete Looks like yesterday's change may have broken something.

**Comment by AndriySvyryd** [comment]
This is caused by different branches (i.e. dev and release) running on the same CI agent and creating different databases.

**Comment by anpete** [comment]
Closing as already re-enabled.
