### ISSUE TITLE
.OneToMany() extension method - wiki details

### ISSUE THREAD

**Issue by dazinator** [aspnet/EntityFramework#1512]
Hello,

This is possibly just that a wiki page needs updating with a newer syntax, not sure.

I am using this page: https://github.com/aspnet/EntityFramework/wiki/Using-EF7-in-Traditional-.NET-Applications, which says to use the fluent api is like so:

```
 protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Blog>()
                .OneToMany(b => b.Posts, p => p.Blog)
                .ForeignKey(p => p.BlogId);
        }
```

However, I can't seem to find those extension methods (OneToMany, ForeignKey etc) anywhere. Is this my mistake or has the fluent API changed?

I am targeting version "7.0.0-beta4-12113"

![image](https://cloud.githubusercontent.com/assets/3176632/5992658/e23d2c2c-aa29-11e4-9238-0c7240260ac1.png)

**Comment by rowanmiller** [comment]
Fixed

**Comment by dazinator** [comment]
Thanks
