### ISSUE TITLE
Generic PropertyEntry should have typed CurrentValues and OriginalValues

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#1538]
In previous versions of EF we came up with a clever conversion-based pattern to flip between generic and non-generic versions of entry types. We now think the conversion mechanism was overkill and we don't want to do the same in EF7, but we can use simple member hiding to obtain `TProperty` typed `CurrentValue` and `OriginalValue` properties. Note that without this there isn't really much of a point on having a generic version of `PropertyEntry`.

**Comment by smitpatel** [comment]
fixed via aff88940320650f9af8f3852124d8da94d0e93d4
