### ISSUE TITLE
Metadata: Remove provider-specific annotation overrides

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#1542]
Now that models are provider-specific, can we remove the provider specific annotations that override relational metadata? This currently includes the following annotations.

* `SqlServer:ColumnDefaultExpression`
* `SqlServer:ColumnDefaultValue`
* `SqlServer:ColumnDefaultValueType`
* `SqlServer:ColumnName`
* `SqlServer:ColumnType`
* `SqlServer:Name`
* `SqlServer:Schema`
* `SqlServer:Sequence:*`
* `SqlServer:TableName`

**Comment by rowanmiller** [comment]
Also need to sort out how ModelBuilder deals with knowing which provider is being targeted.

**Comment by AndriySvyryd** [comment]
We could add information about the target provider to ModelBuilder as a property that then can be queried by the provider-specific extensions

**Comment by bricelam** [comment]
Note, 4b9b9db6b79fa0c0fb05bc1ba417e93bae10f684 can be reverted once this is implemented.

**Comment by ajcvickers** [comment]
Closing; see #1904
