### ISSUE TITLE
Exception thrown when accessing navigation property member after Include()

### ISSUE THREAD

**Issue by rayao** [aspnet/EntityFramework#1543]
EF7 core throws saying that sequence contains more than 1 element. Stack is in EntityQueryModelVisitor.BindMemberExpression, in the closure which calls "ps.Single() as IProperty", apparently ps contains more than 1 element.
 Repro code is as simple as:
            var l5 = ctx.Contacts.Include(o => o.User2).Select(o => new
            {
                M1 = o.ID,
                M2 = o.User2.Name,    // This causes InvalidOperationException, while o.User2 ok.
            }).ToArray();

**Comment by ChrisProlls** [comment]
Same exception here :
list = context.Set<SousFamilleFormation>()
					.Include(sousFamille => sousFamille.FamilleFormation)
					.Where(sousFamille => sousFamille.FamilleFormation.IsActif) // cause exception
					.ToList();

**Comment by gengzu** [comment]
Have same issue... :(

**Comment by anpete** [comment]
Initial work completed. Will treat bugs/improvements separately.
