### ISSUE TITLE
OneToOneBuilder will add a property if Required() is called before ForeignKey()

### ISSUE THREAD

**Issue by rayao** [aspnet/EntityFramework#1555]
I don't know if this is by design, if not, it's a regression, previous version doesn't have this problem.

            modelBuilder.Entity("EF7Test.Contacts").HasOne("EF7Test.Users", "User2").WithOne().
                Required(false).
                ForeignKey("EF7Test.Contacts", "UserSID").ReferencedKey("EF7Test.Users", "SID");

After this a property is forcefully added to entity "Contacts", named "User2SID".
But this works as expected:

            modelBuilder.Entity("EF7Test.Contacts").HasOne("EF7Test.Users", "User2").WithOne().
                ForeignKey("EF7Test.Contacts", "UserSID").ReferencedKey("EF7Test.Users", "SID").
                Required(false);

Maybe we require that Required() must be called last, then it's by design.

**Comment by AndriySvyryd** [comment]
Fixed in #1575
