### ISSUE TITLE
Skip requires OrderBy for DefaultSqlQueryGenerator

### ISSUE THREAD

**Issue by egorpavlikhin** [aspnet/EntityFramework#1607]
https://github.com/aspnet/EntityFramework/blob/bf6360e53f623ffb602bd89a6d678bd85ec8094a/src/EntityFramework.Relational/Query/Sql/DefaultSqlQueryGenerator.cs#L291

Skip and Take should not require OrderBy by default, as only a single product (MS SQL Server) has this limitation. It's simply a wrong place to put that check in.

**Comment by egorpavlikhin** [comment]
It also throws this exception for this query:

    {value(Microsoft.Data.Entity.Query.EntityQueryable`1[Models.DomainPackage]).OrderBy(x => x.Name).OrderBy(Param_0 => Param_0.Name).Skip(0).Take(10)}

**Comment by rowanmiller** [comment]
Triage: We should do OrderBy lifting and default ordering by PK

**Comment by ErikEJ** [comment]
This is how TOP (1) is done in NHibernate: 
ORDER BY newid() OFFSET 0 ROWS FETCH FIRST @p9 ROWS ONLY
