### ISSUE TITLE
Metadata: DRY up helper methods as extensions on the metadata interface type

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#1615]
In K, a nice pattern is to subset the interface and define extension methods for common operations against the narrower interface contract. This has the advantage of keeping the interface small and therefore easier to implement. We should consider whether it makes sense to do this in Metadata.

One example might be the API pairs like GetPrimaryKey and TryGetPrimaryKey on IEntityType. Could the interface have a single method?

**Comment by ajcvickers** [comment]
If we still care about being able to create a compiled model, then things that can be compiled into the model must remain defined on the interface.

**Comment by divega** [comment]
@ajcvickers @anpete @rowanmiller Are there more details in the notes from API reviews about what needs to be done here? Maybe we even have a bug detailing those and this one has become a dupe?

**Comment by anpete** [comment]
Yes, we did all of this as part of API review. This can be closed.
