### ISSUE TITLE
Re-enable .NET Core Tests

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#1617]
LINQ Expressions and Dynamic are broken in the latest .NET Core builds. We've disabled the tests in 033ee73538d63d43fdcd77b505c7e19a014d1ad1, 41079ee6f4488423822b3f62d99142594862b33d & 6c590e7d4f71db016cd854e9169360105e04332f. We should remember to re-enable them when it's fixed. :stuck_out_tongue_winking_eye:

**Comment by rowanmiller** [comment]
Just to help with search, some of the errors you can get as a result of this are:

>Attempt by security transparent method 'Remotion.Linq.Parsing.Structure.NodeTypeProviders.MethodInfoBasedNodeTypeRegistry.CreateFromTypes(System.Collections.Generic.IEnumerable`1<System.Type>)' to access security critical method 'System.Linq.Enumerable.Where<System.Type>(System.Collections.Generic.IEnumerable`1<System.Type>, System.Func`2<System.Type,Boolean>)' failed.

And...

>The best overloaded method match for 'Microsoft.Data.Entity.SqlServer.SqlServerMigrationSqlGenerator.Generate(Microsoft.Data.Entity.SqlServer.Migrations.CreateDatabaseOperation, Microsoft.Data.Entity.Metadata.IModel, Microsoft.Data.Entity.Relational.SqlBatchBuilder)' has some invalid arguments

**Comment by rowanmiller** [comment]
@bricelam do you know if there is a bug tracking this somewhere in another repo?

**Comment by bricelam** [comment]
@rowanmiller not that I know of

**Comment by Jetski5822** [comment]
I would imagine this (https://github.com/aspnet/EntityFramework/commit/24e55a606a6ece80d1859096b9ef0e147f8ac76f) was the change that broke it.

**Comment by rowanmiller** [comment]
Just digging into this a bit more...

Tests first failed CI on dev branch Feb-7, the commit at head of branch was ad98141231c8871ed090b039dd657031854aa5c8 and that commit had built successfully twice before it started failing. So I think we can conclude that it was not an EF change.

**Comment by rowanmiller** [comment]
BTW just to confirm that it wasn't the re-linq upgrade, the relinq upgrade (https://github.com/aspnet/EntityFramework/commit/24e55a606a6ece80d1859096b9ef0e147f8ac76f) came 25 commits after the commit we first saw these failures on.

**Comment by rowanmiller** [comment]
Just to save searching for it in the future... the first CI build to see these failures was 12176

**Comment by Jetski5822** [comment]
@rowanmiller I reverted the relinq dependency to the build I mentioned and my queries are working.

**Comment by rowanmiller** [comment]
@Jetski5822 - interesting... just to confirm, you are running the latest code base from dev with Remotion.Linq 1.15.15 and not seeing the issue on aspnetcore50?

**Comment by Jetski5822** [comment]
@rowanmiller let me try with CoreCLR. Just noticed I was using the latest build today, kre-clr-win-x86.1.0.0-beta4-11134.

**Comment by Jetski5822** [comment]
@rowanmiller Fails on aspnetcore50, works on aspnet50. But kvm builds x86.1.0.0-beta4-11134

**Comment by shhsu** [comment]
Have we start a conversation with CLR team yet?
If not, I can help finding out if Relinq is doing something Core CLR choose not to support or accidentally break

**Comment by rowanmiller** [comment]
@Jetski5822 - That is expected, the failure is only on CoreCLR (our unit tests are still enabled for full .NET)

**Comment by rowanmiller** [comment]
@shhsu - Yep, we have a thread going with CLR folks on getting this one resolved.

**Comment by Jetski5822** [comment]
@rowanmiller so I shouldnt see the error if I upgrade my Remotion.Linq lib for aspnet50?

**Comment by rowanmiller** [comment]
@Jetski5822 - You should see the errors regardless of what version of Remotion.Linq you are using. It looks like an issue in CoreCLR rather than Remotion.Linq.

**Comment by divega** [comment]
The necessary fix has been made on CoreCLR https://github.com/dotnet/coreclr/commit/725d6a91fffdf4603c8a9c74e15cbc83ebf0e3d6. Now we are waiting for aspnet/dnx#1482.
