### ISSUE TITLE
Error Include multiple properties

### ISSUE THREAD

**Issue by kidchenko** [aspnet/EntityFramework#1625]
when using the Include method to eager loading of an entity everything works perfectly, but when using the Include in two properties an error occurs.

**Comment by divega** [comment]
@kiide What version are you using? Can you provide a repro? Model and query can help. A project would be ideal.

**Comment by kiide** [comment]
![image](https://cloud.githubusercontent.com/assets/5432753/6205341/c5dc3ca2-b551-11e4-9931-b3e8e8331f09.png)


![image](https://cloud.githubusercontent.com/assets/5432753/6205331/8b066e04-b551-11e4-892c-2e56c8a8ff0b.png)

![image](https://cloud.githubusercontent.com/assets/5432753/6205334/a0b7d756-b551-11e4-9d4d-1d5a2094ef89.png)

**Comment by kiide** [comment]
I have a class model Produto (Product) that have multiple associations but the entity framework can not load the associations, then I force loading using Incliude method.

**Comment by divega** [comment]
@kiide Thanks. Looks like something that has since then been fixed. @maumar what do you think?

**Comment by maumar** [comment]
This should already be fixed in latest bits

**Comment by maumar** [comment]
This might actually be a different issue. I will take a closer look tomorrow

**Comment by kiide** [comment]
oh, ok great guys! But in this situation, is there anything I can do? I need to load all the associations of my body, I can do a SQL query?

**Comment by maumar** [comment]
I would try our nightly build first, this might unblock you right away, we made a lot of fixes around include area recently

**Comment by Boglen** [comment]
You can try use beta2 from master repo, or beta4 last builds from rev repo

**Comment by kiide** [comment]
Hi guys, give me some days, i will try beta2, beta3 and beta4 and post feedback here!

**Comment by maumar** [comment]
@kiide any update on this?

**Comment by kiide** [comment]
In the docs

**Comment by kiide** [comment]
In my tests

![image](https://cloud.githubusercontent.com/assets/5432753/6841038/976a05d2-d362-11e4-931a-172f0c36c743.png)

but

![image](https://cloud.githubusercontent.com/assets/5432753/6841054/c5d61910-d362-11e4-865c-873c2a247554.png)

and 

![image](https://cloud.githubusercontent.com/assets/5432753/6841123/e25e4b9c-d363-11e4-9653-1409ae158ed3.png)

EF not load all properties. In before beta3 

```if i using .Include(x => x.OtherActor).Include(x => x.OtherDirector).Include(x => x.OtherDirector).``` 

not work.

**Comment by kiide** [comment]
I has using vNext and EF7 in production, but i change EF7 to NHibernate momentarily...

**Comment by maumar** [comment]
Can you also post screenshots or paste contents of your ApplicationContext as well as entities Actor, Director, Movie? Thanks!

**Comment by maumar** [comment]
didn't hear back, closing. Also we did some improvements around include, so the original issue may be already solved. Feel free to reopen if you still see the problem in the latest bits.
