### ISSUE TITLE
Method to get EntityType properties ordered by key members first

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#1634]
There are a few different places in the code where we want to get a list of an entity type's properties with the key members first. These currently include:

* Migrations
  * CreateTable calls
  * Model snapshot
* Reverse engineer

We should have one place to do this. For example, an extension method on `IEntityType`.

**Comment by bricelam** [comment]
See also [this discussion](https://github.com/aspnet/EntityFramework/pull/1601#discussion_r24703128).

**Comment by AndriySvyryd** [comment]
The order should be configurable in the model. The default order would be set by a convention that the providers can replace.

**Comment by mikary** [comment]
Properties are now ordered with properties that are part of the primary key first (in the order specified on the key for composite keys) in PR #1896
