### ISSUE TITLE
Entity is null when primary key value = 0

### ISSUE THREAD

**Issue by anfomin** [aspnet/EntityFramework#1653]
I have entity:
```C#
class Schedule
{
	// Day of week, 0..6
	public byte Day { get; set; }
}
```

I set `Day` property as primary key. When I try to load schedule items:

```C#
var items = context.Schedules.ToArray();
```

Result array contains `null` values for items where `Day = 0`.

**Comment by anpete** [comment]
Take a look at this: https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes:-January-29,-2015#key-value-sentinels

Note for triage: We should do something better when we encounter sentinel nulls in query and possibly update.

**Comment by divega** [comment]
@maumar just a reminder that we looked at this item and we thought it would be a good idea to tackle it next.

**Comment by maumar** [comment]
See https://github.com/aspnet/EntityFramework/issues/2414 for more details, and solution/workaround to this problem, closing
