### ISSUE TITLE
Down() method in migration is generated with wrong order.

### ISSUE THREAD

**Issue by mike-yan** [aspnet/EntityFramework#1654]
public partial class Create_Languages_Table : Migration
    {
        public override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(....)
                .PrimaryKey(x => x.LanguageId, name: "PK_Language");

            migrationBuilder.AddColumn("AspNetUsers", "LanguageId", x => x.Column("int", nullable: true));

            migrationBuilder.AddForeignKey("AspNetUsers", "LanguageId", "Language", principalColumns: "LanguageId", name: "FK_AspNetUsers_Language_LanguageId");
        }

        public override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn("AspNetUsers", "LanguageId");
            migrationBuilder.DropForeignKey("AspNetUsers", "FK_AspNetUsers_Language_LanguageId");
            migrationBuilder.DropTable("Language");
        }
    }

DropForeignKey must be before DropColumn. 
And principalColumns: "LanguageId" must be principalColumn: "LanguageId".

**Comment by rowanmiller** [comment]
I've hit several other places where we try to drop tables/columns before we drop the FK constraint... sounds like we just need ordering in general for the Down operations

**Comment by rowanmiller** [comment]
Another case to consider when you look at this is renaming a PK column, currently we drop the old PK constraint, add the new one, then rename the column

**Comment by bricelam** [comment]
@rowanmiller the crazy dorp-add of everything that touches the renamed object is tracked by [this TODO](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs#L17)--`ModelDiffer` just isn't finished.
