### ISSUE TITLE
InvalidCastException when syncing primary key for MySql

### ISSUE THREAD

**Issue by bartdevriendt** [aspnet/EntityFramework#1655]
I'm working on a MySql provider for EF and I'm having trouble syncing the primary key of model objects with the database.

I tracked down the problem to this:

Microsoft.Data.Entity.Relational.Update.ModificationCommand.PropagateResults uses reader.ReadValue<object> to read the inserted value from the database.  In MySql the LAST_INSERT_ID() function returns a 64-bit int which is converted to ulong in c#.  

Microsoft.Data.Entity.ChangeTracking.Internal.SimpleEntityKeyFactory.Create further on tries to unbox the retrieved value (ulong) to the typedvalue (int) which generates an InvalidCastException on this line:

var typedValue = (TKey)value;

One proposed solution would be to change this to:

var typedValue = Convert.ChangeType(value, typeof(TKey));

Would there be a better way ?

**Comment by ajcvickers** [comment]
Note for triage: see https://github.com/aspnet/EntityFramework/issues/771

**Comment by rowanmiller** [comment]
@anpete - can you drive discussion around this one

**Comment by anpete** [comment]
@rowanmiller Did you mean @AndriySvyryd? This looks like update pipeline.

**Comment by bartdevriendt** [comment]
The proposed solution in my first post isn't enough to get things working.  There's also the clrpropertysettersource class which has this kind of cast.  I'm now trying to add my own implementation to the service collection without luck.

**Comment by divega** [comment]
@anpete @rowanmiller yeah @AndriySvyryd is probably the right person to look at this given that PropagateResults doesn't use IValueReader used by query.

**Comment by ajcvickers** [comment]
This should be working now, assuming the provider is setup correctly. See this thread https://github.com/aspnet/EntityFramework/commit/29cfa8f2194d7e1212a5caa9ecfb05712b3d1584#commitcomment-10950902 and take a look at the SQLite provider which is now checked into the main repro.
