### ISSUE TITLE
RevEng: Consult conventions to see whether Fluent API is necessary 

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework#1668]
Part of #830.

Investigate whether we can update the conventions code so we can directly ask it what it would produce without a given fluent API - so that if it is the same we can skip outputting the fluent API code in OnModelCreating().

**Comment by lajones** [comment]
Examples are: when do we need to output the Key() API? Revisit the current assumptions about when to output the Table(), Column() and ColumnType() APIs.

**Comment by rowanmiller** [comment]
Even if we don't use the conventions, we need to not generate fluent api for stuff that will be taken care of by convention

**Comment by lajones** [comment]
Column() is issued only if the property name we're generating is different from the underlying column name. Planning on leaving that as is.

**Comment by lajones** [comment]
Last part of this was deciding what to do about the relationship code which we currently output.

We decided that we'd like to continue outputting that code as it keeps things simpler (no having to know the ins and outs of when the convention will or will not define it for you) plus it helps educate customers on how those APIs work.

So closing this as nothing more to do.
