### ISSUE TITLE
SqlServer: unexpected sql query for OrderBy with condition

### ISSUE THREAD

**Issue by tstar** [aspnet/EntityFramework#1700]
I have model:
```
public DbSet<Test> Tests { get; set; }

public class Test
{
	public byte Id { get; set; }
	public byte? Weight { get; set; }
}
```
Id - primary key.

I want to sort by column Weight with the null values at the end. For this, I planned to use the following code:
```
var result = Tests.OrderBy(i => i.Weight ?? byte.MaxValue).ToArray();
```
But the result was sorted without my conditions. EF7 sends to the server the following query:
```
SELECT [i].[Id], [i].[Weight]
FROM [dbo].[Test] AS [i]
ORDER BY [i].[Weight]
```
I tried different ways to replace this code:
```
var result = Tests.OrderBy(i => i.Weight == null ? 255 : i.Weight ).ToArray();
var result = Tests.Select(i => new { i.Id, Weight = i.Weight ?? 255 }).OrderBy(i => i.Weight).ToArray();
```
But did not achieve the desired result - sorting with the condition on the server side.

**Comment by lukewaters** [comment]
Fixed in #1749
