### ISSUE TITLE
Decide if AsNoTracking should keep doing identity resolution

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1703]
It currently does, but this may not be desired when streaming large result sets.

**If we change this then the api docs on AsNoTracking need to be updated to reflect the change.**

**Comment by rowanmiller** [comment]
Sub issue of https://github.com/aspnet/EntityFramework/issues/617

**Comment by anpete** [comment]
This was addressed in #f64d269c2a089373200c5903356d2283f42d0bcd

Identity resolution is still performed for no-tracking queries.
