### ISSUE TITLE
Code First: Implement inheritance support

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#1704]
* [x] APIs for configuring base type
* [ ] Base type discovery convention
* [x] Support for referencing inherited entity type members
* [x] Support for ignoring discovered base type
* [x] Support for ignoring inherited properties
* [x] APIs for relational discriminator annotations
* [x] Discriminator introduction convention (readonly by default)
* [x] Relational model validation rule to ensure correct inheritance mapping

**Comment by bricelam** [comment]
@AndriySvyryd Two questions:

1. Will Code First take care uniquifying/collapsing properties in the hierarchy? For example, what would happen to the `Name` properties:

        class Person
        {
        }

        class Student : Person
        {
            public string Name { get; set; }
        }

        class Teacher : Person
        {
            public string Name { get; set; }
        }

2. Do you also intend to also update [CSharpModelGenerator](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/Migrations/CSharpModelGenerator.cs) to serialize inheritance metadata in model snapshots?

**Comment by AndriySvyryd** [comment]
@bricelam 
1. Depends. When using a ModelBuilder with just the core conventions the `EntityType`s for `Student` and `Teacher` each will have a `Name` property, while the one for `Person` will have none.
When also using the relational convention the TPH convention would create a discriminator shadow property and uniquify all the column names that would end up mapped to `Persons` table. In this case it will result in columns `Name` and `Name1` named deterministically.
2. No, that is not part of this issue.

**Comment by bricelam** [comment]
Sounds good. Thanks.

**Comment by AndriySvyryd** [comment]
Discriminator API:
```
// If it's a string we just keep using type name for values
modelBuilder.Entity<Plant>().Discriminator<string>("Type_Of_Entity");
modelBuilder.Entity<Plant>().Discriminator(p => p.TypeOfEntity);

modelBuilder.Entity<Rose>().Discriminator(p => p.Genus).Value("Rose");
modelBuilder.Entity<Daisy>().Discriminator(p => p.Genus).Value("Daisy");

modelBuilder.Entity<Plant>().Discriminator(p => p.Genus);
modelBuilder.Entity<Rose>().Discriminator().Value("Rose");
modelBuilder.Entity<Daisy>().Discriminator().Value("Daisy");

// plus support for typeof() overloads
modelBuilder.Entity<Plant>().Discriminator(p => p.Genus)
    .Value<Rose>(PlantGenus.Rose)
    .Value<Daisy>(PlantGenus.Daisy);
```

**Comment by jnm2** [comment]
EF6 had the ability to use multiple discriminator properties to avoid the use of a dedicated discriminator column. You can set that it up so that if a subclass property is not null, that tells EF that the correct type is the subclass that owns the property. Is this being tracked anywhere?
