### ISSUE TITLE
Inheritance: Implement update pipeline support

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#1705]
- TPH with discriminators

**Comment by cleftheris** [comment]
Hi all, 
Does this mean that with the nightly bits we can use TPH? Any hints on builder.Entity<T> configuration?
Thanks, keep up the good work!

**Comment by rmja** [comment]
@cleftheris see the relational tests in https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.Core.FunctionalTests/InheritanceFixtureBase.cs for information about setting up inheritance.
