### ISSUE TITLE
SqlServer: Generate indexes using WHERE NOT NULL

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#1711]
Per @divega's [comment](https://github.com/aspnet/EntityFramework/pull/1610#discussion_r25408282), this would make it behavior more consistent with other relational databases. We may also have to do work to enable this in the runtime.

**Comment by bricelam** [comment]
Hmm... This is possible on unique **indexes**, but I don't see a way to do it on unique ***constraints***. 
Would it be too inconsistent if we only did it on the indexes?

**Comment by rowanmiller** [comment]
__Triage:__ We won't do this for the reason mentioned above by @bricelam

**Comment by bricelam** [comment]
Re-opening. I think we should always do this on SQL Server for unique indexes.
