### ISSUE TITLE
AnyAsync() leaves reader open

### ISSUE THREAD

**Issue by rmja** [aspnet/EntityFramework#1720]
Consider the following code that I run before saving an entity to the database:

    if (await _db.ItemPages
        .Where(x => x.VendorId == _session.VendorId)
        .SingleOrDefaultAsync(x => x.Id == entity.ItemPageId) == null)
     {
        throw new BusinessRuleViolationException(nameof(ItemPageItem.ItemPageId));
     }

    if (await _db.Items
        .Where(x => x.VendorId == _session.VendorId)
        .SingleOrDefaultAsync(x => x.Id == entity.ItemId) == null)
     {
         throw new BusinessRuleViolationException(nameof(ItemPageItem.ItemId));
     }

    // All is good, insert
    _db.ItemPageItems.Add(entity);
    await _db.SaveChangesAsync();

The above works, but when I start to use AnyAsync instead of SingleOrDefaultAsync, I start to get a SqlException on the SaveChangesAsync() line with the message: "New transaction is not allowed because there are other threads running in the session.". This is the code that fails:

    if (!await _db.ItemPages
        .Where(x => x.VendorId == _session.VendorId)
        .AnyAsync(x => x.Id == entity.ItemPageId))
     {
        throw new BusinessRuleViolationException(nameof(ItemPageItem.ItemPageId));
     }

    if (!await _db.Items
        .Where(x => x.VendorId == _session.VendorId)
        .AnyAsync(x => x.Id == entity.ItemId))
     {
         throw new BusinessRuleViolationException(nameof(ItemPageItem.ItemId));
     }

    // All is good, insert
    _db.ItemPageItems.Add(entity);
    await _db.SaveChangesAsync();

**Comment by divega** [comment]
@rmja what build are you using? (This may am issue we already fixed).

**Comment by rmja** [comment]
@divega 7.0.0-beta3

**Comment by divega** [comment]
@mikary could this one also be related to https://github.com/Reactive-Extensions/Rx.NET/issues/106?

**Comment by mikary** [comment]
This one could be related. The ```AsyncQueryingEnumerable``` only closes the connection on dispose and its entirely possible that it's scheduled on another thread that hasn't started.

I'd have to do more digging to say for sure.

**Comment by divega** [comment]
Thanks. In the meanwhile I will assign it to you. If it still repros after the fix you can reassign it to @maumar.

**Comment by mikary** [comment]
@rmja  I attempted to reproduce this issue on 7.0.0-beta3 based on the information provided, but I was unable to recreate the problem described. Could you produce a stand-alone reproduction of this issue?
