### ISSUE TITLE
Dispose commands

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#1728]
I'm a core contributor for Npgsql, the open-source PostgreSQL ADO.NET driver.

Following up on [this issue on Codeplex](https://entityframework.codeplex.com/workitem/2306), I do hope that EF7 will properly dispose of commands once they're no longer in use. This triggered a memory leak when using EF6 with Npgsql (which we will work around).

Am cross-posting to Codeplex as well.

**Comment by bricelam** [comment]
Related issue: aspnet/DataCommon.SQLite#56

**Comment by rowanmiller** [comment]
If we aren't already, we should do this in EF7

**Comment by rowanmiller** [comment]
@mikary is this done now?

**Comment by mikary** [comment]
This is nearly done. There are still a few issues around ExecuteReader in Update and Query that I expect to finish in PRs in the next few days

**Comment by mikary** [comment]
Finished in #3442 (Disposes now managed by `RelationalCommand` and `RelationalDataReader`)
