### ISSUE TITLE
Disabled Identity test produce Sql exception

### ISSUE THREAD

**Issue by HaoK** [aspnet/EntityFramework#1742]
There was a regression at some point where some identity tests started throwing: 

To reproduce this, reenable these tests: 

https://github.com/aspnet/Identity/blob/dev/test/Shared/UserManagerTestBase.cs#L397

      ---------------- System.Data.SqlClient.SqlException : Incorrect syntax near '<'.
      Must declare the scalar variable "@__CS$".
      Stack Trace:
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Github\Identity\src\Microsoft.AspNet.Identity.EntityFramework\UserStore.cs(489,0): at Microsoft.AspNet.Identity.EntityFramework.UserStore`4.<RemoveClaimsAsync>d__49.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
         C:\Github\Identity\src\Microsoft.AspNet.Identity\UserManager.cs(977,0): at Microsoft.AspNet.Identity.UserManager`1.<RemoveClaimsAsync>d__102.MoveNext()

**Comment by RickyLin** [comment]
I got the same problem. I believe this is related to "Remotion.Linq" "2.0.0-alpha-002"

**Comment by rowanmiller** [comment]
@HaoK do you have a stripped down repro we can use to debug against the EF code base?

**Comment by HaoK** [comment]
No sorry, these were uncovered by CI, some EF changes caused this regression, but the identity tests were just skipped since greater powers wanted a build out...

**Comment by rustd** [comment]
/CC @divega  Do we want to do this in Beta4?

**Comment by divega** [comment]
@rustd I talked to @maumar and he will be looking at this now.

**Comment by maumar** [comment]
culprit is the following query:
```
N'SELECT [uc].[ClaimType], [uc].[ClaimValue], [uc].[Id], [uc].[UserId]
FROM [AspNetUserClaims] AS [uc]
WHERE ([uc].[UserId] = @__CS$<>8__locals1_user_Id_0) AND ([uc].[ClaimValue] = @__claim_Value_1) AND ([uc].[ClaimType] = @__claim_Type_2)
```

**Comment by maumar** [comment]
Problem is that the parameter name we generate for one of the test queries is incorrect - "@__CS$<>8__locals1_user_Id_0". The way we construct those names is by taking FieldInfo and PropertyInfo names from the MemberExpression, and use their Name property. However for this test, the name comes out wacky like this. Code in question is as follows:

```
        public async virtual Task RemoveClaimsAsync(TUser user, IEnumerable<Claim> claims, CancellationToken cancellationToken = default(CancellationToken))
        {
//(...)
            foreach (var claim in claims)
            {
                var matchedClaims = await UserClaims.Where(uc => uc.UserId.Equals(userId) && uc.ClaimValue == claim.Value && uc.ClaimType == claim.Type).ToListAsync(cancellationToken);
//(..)
            }
        }
```

Possible workaround could be to pass the user.Id closure to a local variable and pass this instead. 

This might also be a CLR bug - not sure if those FieldInfo/PropertyInfo names should ever come out like this. 

Alternatively we could compensate in EF by removing the invalid characters and uniquefying  those invalid parameters names.

**Comment by rustd** [comment]
@maumar can you please @HaoK when you fix this so he can fix https://github.com/aspnet/Identity/issues/363

**Comment by divega** [comment]
@maumar thanks for looking. This is very likely a standard compiler generated name for the particular scenario in those Identity methods, in which case EF (or the SQL Server provider for EF) should handle it. Assuming the scenario is not that common we can punt this bug for post Beta4 I believe. Can you send a PR with the workaround on Identity?

**Comment by maumar** [comment]
update: the workaround doesn't work - will try to repro this outside Identity tests and fix in EF

**Comment by maumar** [comment]
Fix to EF has been checked in - 945bbe111f59cca7323bd44508383b173dd5609b

**Comment by maumar** [comment]
@HaoK

**Comment by maumar** [comment]
Query fix has been pushed in

**Comment by HaoK** [comment]
Tests are renabled now and passing
