### ISSUE TITLE
Multi-select with Contains() does not generate SQL

### ISSUE THREAD

**Issue by rmja** [aspnet/EntityFramework#1747]
The following does not generate SQL with the `IN` operator.

    var ids = new int[] {1,2,3};
    _db.Table.Where(x => ids.Contains(x.Id)).ToList();

**Comment by maumar** [comment]
duplicate of https://github.com/aspnet/EntityFramework/issues/1243

**Comment by maumar** [comment]
Fixed in 32cb631986fbd10a1ec5e4aaa7dcaded0eab7270

**Comment by rmja** [comment]
@maumar, one small detail. What is the intended behaviour when the list of ids is empty, say:

    var ids = new int[];
    _db.Table.Where(x => ids.Contains(x.Id)).ToList();

Right now it generates the following invalid SQL:

    SELECT [x].[Id], [x].[SomeOtherColumn]
    FROM [Table] AS [x]
    WHERE [x].[Id] IN ()
    go

I know that I should probably check for the list to be empty before sending it to the database, but it would be nice, if this was handled probably inside EF.

**Comment by maumar** [comment]
EF should cover this case, will fix. Thanks for reporting!

**Comment by maumar** [comment]
Fixed in 5fe084e06ed743d4d8423815829b802bcb9c86f1
