### ISSUE TITLE
Specified cast is not valid on Includes

### ISSUE THREAD

**Issue by 0xdeafcafe** [aspnet/EntityFramework#1748]
When calling this code:

``` csharp
return _db.Trainers
		.Include(t => t.TrainerBlobs)
		.Include(t => t.Image)
		.FirstOrDefault(s => s.Id == id);
```

It throws the following error:
`Additional Information: Specified cast is not valid`

I checked the db, and the data is there and correct, so I don't know what exactly could be causing this to throw. The stacktrace is below:

```
   at Microsoft.Data.Entity.Metadata.ObjectArrayValueReader.ReadValue[T](Int32 index)
   at Microsoft.Data.Entity.Relational.Query.OffsetValueReaderDecorator.ReadValue[T](Int32 index)
   at Microsoft.Data.Entity.ChangeTracking.SimpleEntityKeyFactory`1.Create(IEntityType entityType, IReadOnlyList`1 properties, IValueReader valueReader)
   at Microsoft.Data.Entity.Query.QueryBuffer.IncludeCore(Object entity, INavigation navigation, EntityKey& primaryKey, List`1& bufferedEntities, Func`2& relatedKeyFactory)
   at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedValueReaders, Int32 currentNavigationIndex)
   at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedValueReaders)
   at Microsoft.Data.Entity.Relational.Query.QueryMethodProvider.<>c__DisplayClass11_0`1.<_Include>b__2(T qss)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Relational.Utilities.EnumerableExtensions.<Finally>d__0`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext , QuerySourceScope )
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass36_0`1.<CreateExecutorLambda>b__1(QueryContext qc)
   at Microsoft.Data.Entity.Relational.RelationalDataStore.Query[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryExecutor.ExecuteSingle[T](QueryModel queryModel, Boolean _)
   at Remotion.Linq.Clauses.StreamedData.StreamedSingleValueInfo.ExecuteSingleQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedSingleValueInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at OneOEight.Api.Models.Repositories.TrainerRepository.GetByIdWithIncludes(Guid id) in C:\Users\Alex\Source\Freelance\OneOEight\OneOEight.Api\src\OneOEight.Api\Models\Repositories\TrainerRepository.cs:line 55
   at OneOEight.Api.Areas.V1.Controllers.TrainersController.Get(String id) in C:\Users\Alex\Source\Freelance\OneOEight\OneOEight.Api\src\OneOEight.Api\Areas\V1\TrainersController.cs:line 81
```

**Comment by 0xdeafcafe** [comment]
Should probably throw this in there too. I'm using `7.0.0-beta3`

**Comment by bradleylandis** [comment]
Did you make sure the types in your database match your model?  Usually this comes from having something like int in your model and bigint in your database.  In that case, changing your model to long fixes it.

**Comment by maumar** [comment]
@0xdeafcafe Could you also share the model (and ideally some sample data) used to reproduce this? We fixed some issues around Include in the recent bits, some of them were around incorrect value readers being accessed for some entities (which could result in invalid casts, just like in your case). 

Alternatively you could try one of our latest nightly builds to see if problem still exists.

**Comment by 0xdeafcafe** [comment]
I'm working on this project right now. I'll try and repo this bug (I went though the models setting all Guid's that hold Id's to Nullables, so that might have fixed the casting error) when I finish something.

**Comment by 0xdeafcafe** [comment]
I changed all of the:
``` csharp
public Guid ItemId { get; set; }

public Item Item { get; set; }
```

groups in my models to have Nullable Guid's, then created and applied migrations. That seems to have fixed it.

**Comment by maumar** [comment]
If possible, could you still share the original model? I case the original bug has not been fixed yet.

**Comment by 0xdeafcafe** [comment]
For sure.

user.cs:
``` csharp
public class User
	: Audit, IUser
{
	/// <summary>
	/// Gets or Sets the username of the <see cref="User"/>.
	/// </summary>
	public string Username { get; set; }

	/// <summary>
	/// Gets or Sets the first name of the <see cref="User"/>.
	/// </summary>
	public string FirstName { get; set; }

	/// <summary>
	/// Gets or Sets the last name of the <see cref="User"/>.
	/// </summary>
	public string LastName { get; set; }

	/// <summary>
	/// Gets or Sets the email address of the <see cref="User"/>.
	/// </summary>
	public string EmailAddress { get; set; }

	/// <summary>
	/// Gets or Sets the phone number of the <see cref="User"/>.
	/// </summary>
	public string PhoneNumber { get; set; }

	/// <summary>
	/// Gets or Sets the country code of the <see cref="PhoneNumber"/> of the <see cref="User"/>.
	/// </summary>
	public Nullable<int> PhoneNumberCountryCode { get; set; }

	/// <summary>
	/// Gets or Sets the hash of the password.
	/// Null if <see cref="UserType"/> is set to <see cref="UserType.Facebook"/>.
	/// </summary>
	public string PasswordHash { get; set; }

	/// <summary>
	/// Gets or Sets the salt used when creating the <see cref="PasswordHash"/>.
	/// Null if <see cref="UserType"/> is set to <see cref="UserType.Facebook"/>.
	/// </summary>
	public string PasswordSalt { get; set; }

	/// <summary>
	/// Gets or Sets the number of iterations used when creating the <see cref="PasswordHash"/>.
	/// Null if <see cref="UserType"/> is set to <see cref="UserType.Facebook"/>.
	/// </summary>
	public Nullable<int> PasswordIterations { get; set; }
		
	/// <summary>
	/// Gets or Sets the facebook access token.
	/// Null if <see cref="UserType"/> is set to <see cref="UserType.Generic"/>.
	/// </summary>
	public string FacebookAccessToken { get; set; }

	#region [ Image ]

	/// <summary>
	/// Gets or Sets the Id of the <see cref="Image"/> containg the Profile Picture of this <see cref="User"/>.
	/// </summary>
	public Guid ImageId { get; set; }

	/// <summary>
	/// Gets or Sets the <see cref="Image"/> containg the Profile Picture of this <see cref="User"/>.
	/// </summary>
	public Image Image { get; set; }

	#endregion
}
```

image.cs
``` csharp
public class Image
	: Audit
{
	/// <summary>
	/// Gets or Sets the Id used to locate the image in azure storage.
	/// </summary>
	public Guid AzureStorageId { get; set; }

	/// <summary>
	/// Gets the url path of the <see cref="Image"/>.
	/// </summary>
	/// <returns></returns>
	public string GetImagePath()
	{
		return string.Format("https://oneoeight.blob.core.windows.net/images/{0}", AzureStorageId);
	}

	/// <summary>
	/// Gets or Sets where the <see cref="Image"/> is refrenced from.
	/// </summary>
	public ImageType ImageType { get; set; }
}
```

If I was wrong, and this is actually an issue with something else, I'll update this post with the models as of the error, a copy of my db schema, and data to repo the issue.

**Comment by maumar** [comment]
Thanks a lot! Can you also attach DbContext?

**Comment by maumar** [comment]
@0xdeafcafe I am unable to repro this in beta-3 or current bits, given the information you provided. Could you add some more info? (like you did in #1829). More specifically:
- is dbset Trainers of type User or does it have it's own type (if so, please provide)
- entity that is part of TrainerBlobs navigation
- DbContext (i.e.  relevant mappings and dbset declarations)
- data that was used to fill the database (TSQL format, similar to 1829 works fine)

**Comment by maumar** [comment]
didn't hear back, closing. Also we did some improvements around include, so the original issue may be already solved. Feel free to reopen if you still see the problem in the latest bits.

**Comment by ndenkha** [comment]
Hi guys, I'm having this issue with EF 6.1.3 and it only happens when I include any 3rd Include, i.e. I can get a single or 2 navigation props in any combination fine. I'm running against MySQL 5.7 AWS RDS, and here are my models and tables.

// If I take any one of the includes I get the user object back correctly with only those two navigation props populated, the moment I add any 3rd include I get the error.

Please advise.

var existingUser =
            Users.Include(x => x.Applications)
                .Include(x => x.Roles)
                .Include(x => x.Markets)
                .FirstOrDefault(x => x.Id == user.Id);

public abstract class Trackable : ITrackable
    {
        public DateTime CreatedOn { get; set; }

        public DateTime UpdatedOn { get; set; }
    }

public interface ITrackable
    {
        DateTime CreatedOn { get; set; }

        DateTime UpdatedOn { get; set; }
    }

public class Auditable : Trackable, IAuditable
    {
        public string CreatedBy { get; set; }

        public string UpdatedBy { get; set; }
    }

public interface IAuditable
    {
        string CreatedBy { get; set; }

        string UpdatedBy { get; set; }
    }

public class AppUser : Auditable
    {
        public int Id { get; set; }

        public string Username { get; set; }    // This can be user's domain ID for internal users and any other ID for external users.

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }

        public string Title { get; set; }

        public bool IsActive { get; set; }

        public virtual ICollection<Application> Applications { get; set; }

        public virtual ICollection<Role> Roles { get; set; }
        
        public virtual ICollection<Market> Markets { get; set; }

        public AppUser()
        {
            Applications = new List<Application>();
            Roles = new List<Role>();
            Markets = new List<Market>();
        }
    }

public class Application : Auditable
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool IsDeleted { get; set; }

        public virtual ICollection<Role> Roles { get; set; }

        public virtual ICollection<AppUser> AppUsers { get; set; }

        public Application()
        {
            Roles = new List<Role>();
            AppUsers = new List<AppUser>();
        }
    }

public class Role : Auditable
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int ApplicationId { get; set; }

        // NOTE: commented out as it creates duplicate EDM relationship.
        //public virtual Application Application { get; set; }

        public virtual ICollection<AppUser> AppUsers { get; set; }

        public virtual ICollection<Scope> Scopes { get; set; } 


        public Role()
        {
            //Application = new Application();
            AppUsers = new List<AppUser>();
            Scopes = new List<Scope>();
        }
    }

public class Market
    {
        public short Id { get; set; }

        public string Name { get; set; }

        public string State { get; set; }

        public string Region { get; set; }

        public string Timezone { get; set; }

        public byte TimezoneOrder { get; set; }

        public bool IsActive { get; set; }

        public virtual ICollection<AppUser> AppUsers { get; set; }

        public Market()
        {
            AppUsers = new List<AppUser>();
        }
    }

// Here are the mapping files.
public class ApplicationMap : EntityTypeConfiguration<Application>
    {
        public ApplicationMap()
        {
            ToTable("Application");

            HasKey(x => x.Id);
            Property(x => x.Id).HasColumnName("ApplicationId");

            HasMany(x => x.Roles).WithRequired().HasForeignKey(x => x.ApplicationId);
        }
    }

public class AppUserMap : EntityTypeConfiguration<AppUser>
    {
        public AppUserMap()
        {
            ToTable("AppUser");

            HasKey(x => x.Id);
            Property(x => x.Id).HasColumnName("UserId");

            HasMany(x => x.Applications).WithMany(y => y.AppUsers).Map(z =>
            {
                // NOTE: The left table is AppUser, and right table is Application.
                z.MapLeftKey("UserId");
                z.MapRightKey("ApplicationId");
                z.ToTable("UserApplication");
            });

            HasMany(x => x.Roles).WithMany(y => y.AppUsers).Map(z =>
            {
                // NOTE: The left table is AppUser, and right table is Role.
                z.MapLeftKey("UserId");
                z.MapRightKey("RoleId");
                z.ToTable("UserRole");
            });

            HasMany(x => x.Markets).WithMany(y => y.AppUsers).Map(z =>
            {
                // NOTE: The left table is AppUser, and right table is Market.
                z.MapLeftKey("UserId");
                z.MapRightKey("EnterpriseMarketId");
                z.ToTable("UserMarket");
            });

        }
    }

public class RoleMap : EntityTypeConfiguration<Role>
    {
        public RoleMap()
        {
            ToTable("Role");

            HasKey(x => x.Id);
            Property(x => x.Id).HasColumnName("RoleId");

        }
    }

public class MarketMap : EntityTypeConfiguration<Market>
    {
        public MarketMap()
        {
            ToTable("Market");

            HasKey(x => new {x.Id});
            Property(x => x.Id).HasColumnName("EnterpriseMarketId");
        }
    }

public class ScopeMap : EntityTypeConfiguration<Scope>
    {
        public ScopeMap()
        {
            ToTable("Scope");

            HasKey(x => x.Id);
            Property(x => x.Id).HasColumnName("ScopeId");

        }
    }

// Here are the tables.

create table IF NOT EXISTS Application (
	ApplicationId int not null auto_increment primary key,
	Name varchar(255) not null,
	IsDeleted bool not null default false,
	
	CreatedBy varchar(255) not null,
	CreatedOn Datetime not null,
	UpdatedBy varchar(255) not null,
	UpdatedOn DateTime not null
) ENGINE=INNODB;

create table IF NOT EXISTS AppUser (
	UserId int not null auto_increment primary key,
	Username varchar(255) not null,
	FirstName varchar(255) not null,
	LastName varchar(255) not null,
	Email varchar(255) not null,
	Title varchar(255) null,
	IsActive bool not null default false,
	
	CreatedBy varchar(255) not null,
	CreatedOn Datetime not null,
	UpdatedBy varchar(255) not null,
	UpdatedOn DateTime not null,
	
	UNIQUE KEY unique_record (Username, Email)
	
) ENGINE=INNODB;

create table IF NOT EXISTS Market (
	EnterpriseMarketId smallint not null primary key,
	Name varchar(255) not null,
	State varchar(2) not null,
	Region varchar(255) not null,
	Timezone varchar(25) not null,
	TimezoneOrder tinyint not null,
	IsActive tinyint(1) not null
) ENGINE=INNODB;

create table IF NOT EXISTS Role (
	RoleId int not null auto_increment primary key,
	Name varchar(255) not null,
	ApplicationId int not null,
	
	CreatedBy varchar(255) not null,
	CreatedOn Datetime not null,
	UpdatedBy varchar(255) not null,
	UpdatedOn DateTime not null,
	
	index app_index (ApplicationId),
	foreign key (ApplicationId) references Application(ApplicationId) on delete cascade
) ENGINE=INNODB;

create table IF NOT EXISTS Scope (
	ScopeId int not null auto_increment primary key,
	Name varchar(255) not null,
	RoleId int not null,
	Document JSON,
	
	CreatedBy varchar(255) not null,
	CreatedOn Datetime not null,
	UpdatedBy varchar(255) not null,
	UpdatedOn DateTime not null,
	
	index app_index (RoleId),
	foreign key (RoleId) references Role(RoleId) on delete cascade
) ENGINE=INNODB;

// Association tables

create table IF NOT EXISTS UserApplication (
	ApplicationId int not null,
	UserId int not null,

	index app_index (ApplicationId),
	index user_index (UserId),
	foreign key (ApplicationId) references Application(ApplicationId) on delete cascade,
	foreign key (UserId) references AppUser(UserId) on delete cascade,
	
	primary key (ApplicationId, UserId)
) ENGINE=INNODB;

create table IF NOT EXISTS UserMarket (
	EnterpriseMarketId smallint not null,
	UserId int not null,
	
	index market_index (EnterpriseMarketId),
	index user_index (UserId),
	foreign key (EnterpriseMarketId) references Market(EnterpriseMarketId) on delete cascade,
	foreign key (UserId) references AppUser(UserId) on delete cascade,
	
	primary key (EnterpriseMarketId, UserId)
) ENGINE=INNODB;

create table IF NOT EXISTS UserRole (
	RoleId int not null,
	UserId int not null,
	
	index user_index (UserId),
	index role_index (RoleId),
	foreign key (UserId) references AppUser(UserId) on delete cascade,
	foreign key (RoleId) references Role(RoleId) on delete cascade,
	
	primary key (RoleId, UserId)
) ENGINE=INNODB;
