### ISSUE TITLE
Expression parameters in aggregate functions

### ISSUE THREAD

**Issue by mojtabakaviani** [aspnet/EntityFramework#1783]
In sql server easy can pass expression to aggregate functions such as sum, avg, min, max and etc. for example:
```
select sum(col1 + col2) from table1
```
but in entity framework not support and just calculate aggregate functions over one column.
please add expression parameters in next version of entity framework that support aggregate functions over multiple columns.
```
dbcontext.table1.Sum(t=> new { t.col1 + t.col2 });
```

**Comment by rowanmiller** [comment]
Hey,

The syntax in your Sum call looks invalid. You can't really sum an anonymous type. Is this what you want?

```
dbcontext.table1.Sum(t=> t.col1 + t.col2);
```

That would give you the sum of adding `col1` and `col2` for all rows in the table

~Rowan

**Comment by rowanmiller** [comment]
BTW @anpete is currently making the correct syntax eval on the server (currently client eval)
