### ISSUE TITLE
Create a stand-alone provider test suite

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#1807]
As a spec for provider writers.

**Comment by ErikEJ** [comment]
Hear, hear!

**Comment by dazinator** [comment]
+1 Yes please! :)

**Comment by roji** [comment]
+1, am working on the PostgreSQL provider and integrating with the test suite via a git submodule, it ain't fun.

**Comment by roji** [comment]
Have accidentally noticed EntityFramework.Core.FunctionalTests and EntityFramework.Relational.FunctionalTests in the Nuget feed... Definitely document this in any provider docs you're preparing, and I guess this issue can be closed?

**Comment by rowanmiller** [comment]
@roji publishing the packages is more of an interim solution that what we want to do long term. This item is tracking building something more ideal.

BTW apologies that we didn't make you aware of the packages being available... I should have let you know.

**Comment by roji** [comment]
@rowanmiller no apologies necessary, you guys have a lot in your hands and it didn't affect me that badly.

I'd be interested to hear about your ideas for a better solution here, the current nugets definitely provide what I need...

**Comment by smitpatel** [comment]
We already did in Specification.Tests packages.

**Comment by ajcvickers** [comment]
Triage: we think that what we have now is good enough and there is not enough ROI for doing something more.
