### ISSUE TITLE
SqlServer: Default Value Generator

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#1811]
Presently for PK with single property, we put Default as value generation strategy.
This Default annotation translates to value generation defined on model or to Identity.
Instead of setting Identity hard coded, we should have some way to define what should be the default value generation strategy.

**Comment by ajcvickers** [comment]
The idea here is to have the SQL Server conventions annotate the model with the default strategy to use for the model. This is currently Identity, but we are switching to Sequence, so it would probably make sense to do this switch as part of implementing this issue.
