### ISSUE TITLE
Migrations: Apply with specific migration doesn't resolve short name

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1818]
Need to do `k ef migration apply 000000000000000_CreateIdentitySchema` rather than `k ef migration apply CreateIdentitySchema`

**Comment by bricelam** [comment]
It looks like there's one too many zeros in the template file.

**Comment by rowanmiller** [comment]
Hey, I don't think that is the issue here. I had already regenerated the initial migration using the latest bits.

**Comment by bricelam** [comment]
I can't repro this anymore. I really think it was just the amount of zeros in the timestamp.
