### ISSUE TITLE
Query: Client eval OrderBy combined with Skip/Take gives wrong results

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1851]
In the following code the `OrderByDescending` is client eval'd but the `Take` is still pushed to the database. This means you get the first 4 records from the table sorted by savings, rather than the 4 records with the biggest savings.

If we need to do client eval for an `OrderBy`, `Where`, etc. then we probably need to do the `Take` on the client too... or we could throw because perf is going to be bad sicne you'd have to pull back every record from the table.

```
            var bestDeals = db.Products
                .OrderByDescending(p => CalculateSavings(p.MSRP, p.CurrentPrice))
                .Take(4);

        private decimal CalculateSavings(decimal msrp, decimal current)
        {
            return msrp - current;
        }
```

**Comment by anpete** [comment]
This is just a bug. We need to add RequiresClientOrdering to RelationalQueryModelVisitor and then check it in the result op handler like we do for filtering.
