### ISSUE TITLE
Query: Client eval warnings and disablement

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#1856]
We should log warnings when we are doing client eval of filter/orderby etc...

Additionally, we should consider a big switch to disable client eval completely (and throw).

**Comment by MarcinJuraszek** [comment]
Oh yeah. That's what scares me a lot about EF deciding what part gets translated into SQL and what gets executed on the client. There should be an easy way to

1. determine what's going on
2. force SQL translation for everything in the query
