### ISSUE TITLE
Add support for execution of a raw command on the data store

### ISSUE THREAD

**Issue by mikary** [aspnet/EntityFramework#1863]
Provide a simple mechanism for executing a raw command (SQL statement) that does not return a value

**Comment by mikary** [comment]
@rowanmiller is this a feature we would expect to have parody with ExecuteStoreSql from EF6? If so should we consider moving it into the 7.0.0 milestone?

**Comment by rowanmiller** [comment]
Clearing milestone so that we can address in triage

**Comment by divega** [comment]
We missed creating the async version of ExecuteSqlCommand. Reopening to track that.
