### ISSUE TITLE
Metadata: API Review: Remaining work

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#1881]
Tracking these as I need more detail on the specific changes required. Some of these may also be tracked as part of other bugs/review notes.

- INavigation.PointsToPrincipal: Try and remove this and have navigations represented on ForeignKey.
- IProperty.IsStoreComputed: Can we combine this and UseStoreDefault into an enum? Or some other pattern?

**Comment by ajcvickers** [comment]
Done.
