### ISSUE TITLE
Inheritance EntityType AddProperty does not check base type

### ISSUE THREAD

**Issue by mikary** [aspnet/EntityFramework#1890]
The ```AddProperty``` method in ```EntityType``` ensures that names are not duplicated for properties in the current type, but does not ensure the name is unique per hierarchy. This could be a problem if an ```EntityType``` has a CLR or shadow property with a name that collides with a shadow property on the base type.

**Comment by AndriySvyryd** [comment]
This isn't a problem if we decide that we support property hiding. The property on the most derived type would be used in that case.

**Comment by rowanmiller** [comment]
We should enforce this for the moment and then remove the restriction when we properly support hiding.
