### ISSUE TITLE
Investigate Test Failures on Core CLR

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#1905]
After re-enabling the Core CLR tests, two of them are still failing. We should investigate why and follow up with the appropriate teams.
* `SharedInMemoryEndToEndTest.Can_save_changes_and_query()` in [test/EntityFramework.CrossStore.FunctionalTests/EndToEndTest.cs](https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.CrossStore.FunctionalTests/EndToEndTest.cs#L119)
* `SqlServerEndToEndTest.Can_save_changes()` in [test/EntityFramework.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs](https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs#L127)

**Comment by divega** [comment]
@bricelam just to double-check, you merged a fix for this and it should be closed, right?

**Comment by divega** [comment]
@bricelam Please ignore the previous comment :smile:
