### ISSUE TITLE
Migrations create dbo.DefaultSequence when named schema is specified

### ISSUE THREAD

**Issue by rmja** [aspnet/EntityFramework#1919]
I am using multiple schemas in the database, and I have a `DbContext` for each of them.
In `OnModelCreating()` I have for example the following:

    modelBuilder.ForRelational().Sequence("DefaultSequence", "accounting");

When I run `dnx . ef migration add Initial`, the migration code has (for `Up()`):

    migrationBuilder.CreateSequence("DefaultSequence", "accounting", storeType: "bigint");
    migrationBuilder.CreateSequence("DefaultSequence", storeType: "bigint");

This of cause fails when having independent migrations for each of the schemas, as `dbo.DefaultSequence` can only exist once in the database.
As far as I can tell, the `dbo.DefaultSequence` should not be created when a named schema is specified.

**Comment by bricelam** [comment]
It looks like this is a bug in [the workaround](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs#L36-L39) I have in Migrations for #1568. We could either fix the workaround, or just fix the original issue.

For now, @rmja, you can just remove the second call to `CreateSequence()` in your migration.

**Comment by rmja** [comment]
@brycelam Yes I found that and it works fine, thanks.
