### ISSUE TITLE
Preserve relationship annotations

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#1923]
Annotations set on the relationship using ModelBuilder are stored on the underlying foreign key and when it is recreated they are lost, they should be preserved.

Annotations set on the ForeignKey using Metadata API will not be preserved.

We should also consider adding API for conventions to set annotations on the foreign keys that will not be preserved.

**Comment by rowanmiller** [comment]
Discussed with @AndriySvyryd and this is perhaps not technically correct... but it's also never really hit or visible from using the product. We concluded we could just deal with this in the future if we ever start using things in a way where this becomes an issue.
