### ISSUE TITLE
RevEng: Ignore __MigrationHistory table

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1929]
If this table is in the database we should exclude it from reverse engineer

**Comment by lajones** [comment]
Is it always called __MigrationHistory or is it configurable?

**Comment by rowanmiller** [comment]
I think it's fine just to match on that name... that's what we did in the Power Tools. Obviously for the UI workflow folks can choose if they want that table included or not.

**Comment by lajones** [comment]
Fixed by https://github.com/aspnet/EntityFramework/pull/2089
