### ISSUE TITLE
RevEng: Don't include ModelBuilder.Entity calls for types with no config

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1931]
If there is a type that doesn't need any configuration (i.e. everything is detected by convention) we still include a section in the OnModelCreating method for it. This isn't needed since we include DbSets for all types in the model.

```
modelBuilder.Entity<AspNetUsers>(entity =>
    {
    }
);
```

**Comment by lajones** [comment]
Fixed by fix for https://github.com/aspnet/EntityFramework/pull/2078.
