### ISSUE TITLE
RevEng: Remove explicit generics from relationship calls

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1932]
We currently explicitly specify the generic argument for the first part of the relationship but this isn't needed since it is inferred from the navigation property (i.e. `<Category>` can be removed from the following example).

```
            modelBuilder.Entity<Product>(entity =>
                {
                    entity.Reference<Category>(d => d.Category).InverseCollection(p => p.Product);
                }
            );
```

**Comment by lajones** [comment]
Fixed with commit 1b07c35.
