### ISSUE TITLE
RevEng: Minor improvements to generated entity code

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1939]
Couple of minor improvements:

- Don't generate constructor if there are no collections to initialize
- Don't generate `// Properties` and `// Navigation Properties` comments
- Don't generate `// Generated code` comment in files (also applies to context where there is no need to include connection string in header since it is also in code - which we need to address at some point).

**Comment by lajones** [comment]
Fixed with commit 164c81b.
