### ISSUE TITLE
RevEng: Decide where we store connection string

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1940]
Currently we just write it to code. We are really trying to help folks write secure apps and this is an ant-pattern so we need to work out what to do. This will be complex because the ideal solution is going to be different for different project types.

**Comment by lajones** [comment]
We discussed this and decided we will continue to output the connection string in OnConfiguring(). But in addition we will output a #warning indicating that the connection string may contain a password and with a comment containing a link to a web page which explains what you can do to fix that. Moving to @rowanmiller to decide the wording and the link.

**Comment by rowanmiller** [comment]
Here is my proposed message:

> In order to protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.

**Comment by rowanmiller** [comment]
cc @divega above proposal look ok to you?

**Comment by divega** [comment]
Looks good.

**Comment by rowanmiller** [comment]
@lajones can you make this change in the generated code

**Comment by lajones** [comment]
Fixed by PR #4398. Commit d9b5da1.
