### ISSUE TITLE
Bring back SQLite

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#1953]

**Comment by ErikEJ** [comment]
Yir!

**Comment by crozone** [comment]
Any word on SQLite migrations?

**Comment by ErikEJ** [comment]
@crozone They work, you must invoke programatically on Windows Phone and Store apps. What are you looking for?

**Comment by crozone** [comment]
I'm trying to apply migrations in an ASP.NET 5 application, using `dnx . ef migrations apply` or `Database.AsRelational().ApplyMigrations()` from within the DbContext. 

This appears to require methods within Microsoft.Data.Entity.Sqlite.Migrations.SqliteHistoryRepository which are not yet implemented:

https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Sqlite/Migrations/SqliteHistoryRepository.cs

Is there another way to apply or invoke them?

**Comment by bricelam** [comment]
@crozone Sorry, Migrations had changed a lot so it needs to be re-implemented.
