### ISSUE TITLE
ReaderModificationCommandBatch and affected rows

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#1956]
I'm working on an EF7 provider for PostgreSQL (with Npgsql), it's my very first foray into the EF codebase so I hope I won't be saying too much nonsense.

Looking at `ReaderModificationCommandBatch.Execute()`, I notice that it retrieves the affected rows (in the two ConsumeResultSet* methods). It appears to do this by reading the result of a `SELECT @@ROWCOUNT` appended by `SqlServerSqlGenerator.AppendSelectAffectedCountCommand()`.

PostgreSQL has no equivalent query; affected row counts are sent within the protocol itself, and are currently exposed on the ADO.NET level via the [IDbDataReader.RecordsAffected](https://msdn.microsoft.com/en-us/library/system.data.idatareader.recordsaffected(v=vs.110).aspx) property. In my NpgsqlModificationCommandBatch I can override Execute() and check against that property, but wanted to make sure I'm going down the right path:

* Is there a special reason to use an SqlServer-specific feature (`SELECT @@ROWCOUNT`) rather than the standard ADO.NET API for this? Does this have to do with the fact that RecordsAffected is only supposed to be populated after the reader is closed, and therefore gives the aggregate rows rather than resultset-by-resultset? Note that the PostgreSQL protocol *does* provide affected rows on a resultset-by-resultset basis, so this information can in theory be exposed to the EF provider if absolutely necessary.
* It seems a bit odd for `ReaderModificationCommandBatch`, a generic class within EntityFramework.Relational to encode logic that is so specific to the SqlServer adapter, while at the same time containing other, more generic functionality.
* You should probably consider making `SqlGenerator.AppendSelectAffectedCountCommand` virtual rather than abstract.

Thanks for any advice on this...

**Comment by rowanmiller** [comment]
@AndriySvyryd can you give some input on this one?

**Comment by rowanmiller** [comment]
@AndriySvyryd - ping... can you take a look at this

**Comment by AndriySvyryd** [comment]
Hello roji,

Sorry for late response, I was on vacation.
The reason we use `SELECT @@ROWCOUNT` is that we need to be able to provide enough information for handling optimistic concurrency issues in batches. E.g. if 2 update and 3 delete operations are executed in a single `DbCommand` and only 4 rows were affected ideally we should be able to tell which operation failed without any additional queries.

I haven't worked with PostgreSQL, but won't the following snippet achieve the desired result?
```
GET DIAGNOSTICS row_count = ROW_COUNT;
SELECT row_count;
```

The 'ReaderModificationCommandBatch' implementation expects this behavior because I assumed that most SQL stores either had a way to return the number of rows affected by previous statement or didn't support batches at all.

If that's not the case for PostgreSQL and some other stores we could add a `ModificationCommandBatch` that uses `IDbDataReader.RecordsAffected` and provides limited support for optimistic concurrency handling. Or better yet we could accept a contribution for this.

If there are other places where you had to reimplement functionality from the relational provider because of poor factoring, please let us know.

**Comment by roji** [comment]
@AndriySvyryd thanks for your reply.

Unfortunately, in PostgreSQL `GET DIAGNOSTICS` is only supported in plpgsql, and not in regular SQL. I think that means we can't rely on it (it may be disabled etc.). This seems to be [listed as an unsupported feature](http://www.postgresql.org/docs/9.4/static/unsupported-features-sql-standard.html) of PostgreSQL, feature F121-01

However, the affected rows information is definitely available on a command-by-command basis in the PostgreSQL protocol, in the [CommandComplete](http://www.postgresql.org/docs/9.4/static/protocol-message-formats.html) message - Npgsql's implementation of `IDbDataReader.RecordsAffected` uses that. The only issue is that `IDbDataReader.RecordsAffected` aggregates these values.

It seems that best solution would be to add a non-standard method in Npgsql which would expose the unaggregated numbers. I've opened https://github.com/npgsql/npgsql/issues/585 for this and will implement.

Regarding providing a `ModificationCommandBatch` that only uses `IDbDataReader.RecordsAffected`, I guess I agree with you assumption that if a database provides batching, it's going to provide some way to access each command's affected rows... It's just not necessarily going to do that via an SQL query such as `SELECT @@ROWCOUNT`...

**Comment by AndriySvyryd** [comment]
Ok, so if we make `ReaderModificationCommandBatch.ConsumeResultSet*` and `AggregateEntries` methods protected virtual, make _valueReaderFactory a protected property and make `SqlGenerator.AppendSelectAffectedCountCommand` virtual would that be enough granularity?

**Comment by roji** [comment]
@AndriySvyryd am hard at work at a minimal working provider for a //BUILD demo so I'll get around to this next week...

**Comment by divega** [comment]
@AndriySvyryd should we make this a pri0 given the request from PostgreSQL and SQL CE?

**Comment by AndriySvyryd** [comment]
@divega This isn't a blocking issue, it just makes the implementation less DRY, pri1 is more appropriate

**Comment by ErikEJ** [comment]
Agree, I will just copy and paste quite a lot of code...

**Comment by roji** [comment]
@AndriySvyryd, I'm back working on EF7, sorry for the really long inactivity here. I've studied the command batching classes and I think I understand the situation better now.

First off, in a PostgreSQL implementation the notion of `ResultSetEnds` in `ReaderModificationCommandBatch` is unnecessary, since I won't be finding the affected row count via an SQL query appended to a batch of INSERTs - I'd be extracting that information from the PG protocol instead. Since a lot of the current logic in `ReaderModificationCommandBatch` revolves around that notion, 

Two options come to mind. The current code contains things that are generic and useful for PostgreSQL (AddCommand, CreateStoreCommand, PopulateParameters, some of the code in Execute and others), but also lots of code that seems specific `ResultSetEnds`/`SELECT @@ROWCOUNT` model (ResultSetEnds, ConsumeResultSetWithoutPropagation, the code inside the "using reader" block in the Execute method).

First off, it would be helpful if Execute were split into two methods: everything inside the "using reader" block seems specific to the `SELECT @@ROWCOUNT` model, so I'd simply refactor it out to a protected virtual method. Everything outside the "using reader" block seems pretty generic (except the `Debug.Assert` on the ResultSetEnds, which could be moved inside the "using reader" code. This would be a minimal change that would allow me to override what happens inside "using reader".

A further step would be to refactor the `SELECT @@ROWCOUNT` model-specific code out to a subclass of `ReaderModificationCommandBatch`, say something like `GroupedReaderModificationCommand` - SqlServer would inherit from there, while PostgreSQL would inherit directly from `ReaderModificationCommandBatch`. This gives a more clean separation, but it might complicate the hierarchy somewhat and be more difficult to understand.

Let me know what you think. If you like the general idea I can submit a PR.

**Comment by ErikEJ** [comment]
@roji FWIV - I just wrote my own: https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Update/SqlCeModificationCommandBatch.cs

**Comment by roji** [comment]
Thanks @ErikEJ, I actually looked at your implementation :)

Yeah, I could go down that route but it seems like there's some potential for more reuse and a more productive hierarchy so I thought I'd propose...

**Comment by ErikEJ** [comment]
@roji  Agree. See my comment above from May 14! :smile:

**Comment by AndriySvyryd** [comment]
@roji Refactoring out the result set related logic to a derived class like you describe sounds like a good change, since it wouldn't be needed by providers like yours. Perhaps the new class could be named `ResultSetModificationCommandBatch` to be more specific.

**Comment by roji** [comment]
OK, I've submitted #2448 which refactors the affect row query logic out from `ReaderModificationCommandBatch` and into what I ended calling `AffectedCountModificationCommandBatch`. The main reason behind this name is to clearly link it to `SqlGenerator.AppendSelectAffectedCountCommand`.

Some comments:
* I ended up leaving `Execute` as it is (apart from moving it to the `AffectedCountModificationCommandBatch`, breaking it up into two parts seemed overly complicated.
* `SqlServerModificationCommandBatch` and `SingularModificationCommandBatch` now inherit from `AffectedCountModificationCommandBatch`. Very strictly speaking it should be named `SingularAffectedCountModificationCommandBatch` but I already hate myself for introducing such long names.
* ReaderModificationCommandBatch made use of RelationalLoggerExtensions.LogCommand, which is internal so it's not usable from the NpgsqlModificationCommandBatch. Maybe consider making some of those extensions public for providers?
* A design question I'm not sure about... It seems like it's the ModificationCommandBatch implementation's responsibility to check that the affected rows is correct, and to raise a DbUpdateConcurrencyException otherwise. If that's the case, why does the Execute method return the affected rows at all, can't the caller (BatchExecutor) simply look at the batch's ModificationCommand.Count to infer how many rows where affected? Shouldn't Execute either perform all its updates successfully (checking that internally), or raise an exception if it couldn't?

**Comment by AndriySvyryd** [comment]
@roji 
I've made some comments on the PR.
* The reason `RelationalLoggerExtensions` is internal is to avoid those methods showing up in places not related to EF. We will consider ways of making them public, but meanwhile you could either pull the ivoking code in `Execute*` up or extract the call as a method so your implementation can also use it.
* Yes, there's no good reason to return the count. `ModificationCommandBatch.Execute` and `IBatchExecutor.Execute` should just return void

**Comment by roji** [comment]
Thanks for the review @AndriySvyryd! I'll work on your comments tomorrow.

**Comment by roji** [comment]
@AndriySvyryd, have pushed another commit to the PR dealing with the issues you mentioned. I ended up splitting Execute as I originally thought and pulling up common code back to `ReaderModificationCommandBatch`. This allows providers like Npgsql and SqlCe to override only the reader traversal behavior and to keep the rest.

Let me know if you see anything else.

**Comment by AndriySvyryd** [comment]
@roji `SqlGenerator.AppendSelectAffectedCountCommand` is still abstract, you should change it to virtual. And don't forget to squash those commits.

**Comment by roji** [comment]
Done, sqashed the commits and rebased the PR on the latest dev.
