### ISSUE TITLE
Mono: Use of Scale/Precision in RelationalDecimalTypeMapping

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1965]
Currently our code base compiles on Mono except for the use of DbParameter.Precision/Scale in RelationalDecimalTypeMapping.cs. Obviously compilation isn't a key scenario but it gives insight into what will work at runtime too.

Given this appears to be the only issue (at least in terms of API surface usage) we may want to adjust code.

```
            if (parameter.Direction == ParameterDirection.Output)
            {
                parameter.Scale = _scale;
                parameter.Precision = _precision;
            }
```

**Comment by bricelam** [comment]
On `net45`, we could use the following to enable Mono.

```C#
((IDbDataParameter)parameter).Scale = _scale;
((IDbDataParameter)parameter).Precision = _precision;
```

**Comment by bricelam** [comment]
I've filed [Bug 29167](https://bugzilla.xamarin.com/show_bug.cgi?id=29167) on Mono.

**Comment by rowanmiller** [comment]
@mikary can you do the workaround suggested by Brice
