### ISSUE TITLE
Revist how we read values from DbDataReader (GetFieldValue<T>, GetValue, etc.)

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1977]
To support Mono SqlClient in beta 4 we [made RelationalTypedValueReader.ReadValue<T> not use the generic DbDataReader.GetFieldValue<T>](https://github.com/aspnet/EntityFramework/commit/68d2f94b4696e9a0354c4bf55b598a2fe53b8128). This is ok for SQL Server but we want the generic one for SQLite to help with detecting data types. It's also been suggested that ReadValues may be better to use on SQL Server (and that would work with Mono too).

It seems like we probably need each data store to be able to override how value reading is done.

**Comment by divega** [comment]
We are making further changes in this area at https://github.com/aspnet/EntityFramework/pull/1992 for Mono compatibility.

**Comment by natemcmaster** [comment]
We may be able to use GetFieldValue<T> now. https://github.com/mono/mono/pull/2010
