### ISSUE TITLE
Migrations :: add information how to deal with multiple contexts

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1981]
If project has multiple contexts defined and one tries to perform migration operation the following error pops up:

```
System.InvalidOperationException: More than one DbContext was found. Specify which one to use.
```

However when I display migration tool info it doesn't say how to specify the context. We should probably add this information to the initial message

**Comment by Scalpel78** [comment]
Agreed. How do you specify it?

**Comment by bricelam** [comment]
@Scalpel78 using the `--context` (DNX) or `-Context` (NuGet) parameter
