### ISSUE TITLE
Consider setting read-only before save for SQL Server Identity columns

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1990]
See Issue #703.

Rather than having SQL Server throw, if we mark SQL Server Identity properties as only accepting temporary values, then we will get an exception from our stack when code attempts to set other values rather than waiting for the store to throw.

Also consider that if Identity becomes the default again, then it may be worth changing the update pipeline to make insertion of actual values work, if this is possible to do in a reasonable way.

**Comment by rowanmiller** [comment]
Given you can get the explicit values inserted ([with a bit of extra code](https://github.com/aspnet/EntityFramework/issues/2803#issuecomment-159375915)) I think our current behavior is actually pretty good. @divega @ajcvickers do you agree that this could be closed now?

**Comment by ajcvickers** [comment]
@rowanmiller I'm fine with closing it. The exception SQL Server throws seems fine to me.

**Comment by divega** [comment]
From looking at the code I believe we don't have any usage in the stack of `ReadOnlyBeforeSave`. It also seems that you have to drop down to metadata to use it. Makes me wonder if it is worth keeping it.
