### ISSUE TITLE
Remove Default Sequence from the model if not being used by any property

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#1994]
Presently, convention set Sequence as default value generator for SqlServer. So convention also adds Default Sequence to model.
If the user sets to use identity on model level then the default sequence is removed from the model.
But if the user sets to use identity on individual properties and even if none of the properties is using the default sequence, it still remains. It should be removed in such case.

**Comment by smitpatel** [comment]
With #2175 implemented, above issue doesn't exist anymore.

**Comment by divega** [comment]
@smitpatel what happens if you call UseSequence() on the model and UseIdentity() on all individual properties? Just want to make sure we understand and are ok with the behavior.

**Comment by smitpatel** [comment]
In that case there will be sequence in the model which is not being used by any property. But since user made explicit call to `UseSequence()`, I am not sure if we should be removing it.

**Comment by ajcvickers** [comment]
Agree with @smitpatel that this is an acceptable behavior.

**Comment by divega** [comment]
Agreed that sounds acceptable. @ajcvickers @rowanmiller what do you think?

**Comment by divega** [comment]
ok :)

**Comment by rowanmiller** [comment]
I agree... especially when we rename UseSequence to something that reflects it's the HiLo generator pattern.
