### ISSUE TITLE
Add query specific StartTracking API to StateManager

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#2015]
``` c#
InternalEntityEntry StartTracking(IEntityType entityType, object entity, IValueReader shadowValueReader)
```

The difference with the exiting version is that we only need to pass shadow state, not the entire value reader.

**Comment by ajcvickers** [comment]
Closing for now since code has changed in this area. Might be possible to do an optimization here later   if query can create a ValueBuffer that only contains shadow state data, but we can revisit that later if it comes up as being useful/important.
