### ISSUE TITLE
EntityFramework adds IMemoryCache as transient which breaks it totally

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/EntityFramework#2052]
EF is registering `IMemoryCache` as transient in DI, meaning it's kinda pointless. Other frameworks, e.g. MVC, do a `TryAdd` so they don't replace it. Our default templates add EF services before any others, so this is breaking anything else that relies on `IMemoryCache`, e.g. the `CacheTagHelper`.
  https://github.com/aspnet/EntityFramework/blob/128da35a60e7e54f901ecfaaff6f29678a7ccd43/src/EntityFramework.Core/Extensions/EntityFrameworkServiceCollectionExtensions.cs#L110

**Comment by anpete** [comment]
@DamianEdwards, It's not pointless if the transient instance is a dependency of a singleton component. It also looks like MVC doesn't do TryAdd, but actually AddSingleton: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc/MvcServices.cs#L143

Is it intended that there should only ever be a single memory cache across all frameworks? If so, it seems pretty inflexible as there can now only be a single set of MemoryCacheOptions, and we also need to worry about ensuring cache key uniqueness across frameworks.

**Comment by DamianEdwards** [comment]
ping @lodejard @davidfowl for insight here RE how to use DI for things like this.

ping @pranavkm for comment on MVC not using `TryAdd` and why it still doesn't replace or throw.

Ultimately, it's a single DI container being shared across the app, so registering commonly used types with different lifetimes is problematic. We need to ensure the various frameworks agree on the lifetime of these things. If EF wants its own `MemoryCache` then AFAIK it needs to register it via a different type, but @loudej and @davidfowl can correct me on that.

**Comment by davidfowl** [comment]
Why doesn't ef just new it up for that component? To testability?

**Comment by anpete** [comment]
@davidfowl Yeah, just the usual general DI goodness. To me, transient seems right here as it provides the most flexibility. Consumers are free to re-scope via composition like we do in EF.

**Comment by pranavkm** [comment]
The `TryAdd` was specifically added so previously added services (perhaps user specified ones) don't get overwritten by the framework. I don't think we want to change this.

**Comment by DamianEdwards** [comment]
@pranavkm the point was it seems MVC is *not* calling `TryAdd`, yet EF's registration is winning. Are we reading it wrong?

**Comment by pranavkm** [comment]
Mvc does call TryAdd - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc/MvcServiceCollectionExtensions.cs#L19 and so does EF - https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/Extensions/EntityFrameworkServiceCollectionExtensions.cs#L67. It's just that EF happens to be registered earlier hence their service definition wins.

**Comment by DamianEdwards** [comment]
ah the indirection lead us astray :smile:

**Comment by divega** [comment]
We discussed this with @lodejard, @davidfowl and @anpete. It turns out MemoryCache is in fact designed to have only one instance per application because of how it needs to respond to memory pressure handling GC notifications. 

So we will have to figure out a few changes on the way we use it in EF and presumably we should try to get at least some of the changes in beta5, so that we no longer break other caching. 

Assigning to @anpete with pri0 and the specific milestone. Please get approval to check a fix to release as necessary.
