### ISSUE TITLE
Sql query with enum produces a where clause with the string value instead of the underlying (int) type

### ISSUE THREAD

**Issue by rmja** [aspnet/EntityFramework#2057]
I have the following enum definition:

    public enum Discriminator
    {
        Something = 1
    }

The sql produced when filtering using the enum like this:

    _db.Addresses.Where(x => x.Discriminator == Discriminator.Something).ToList();

is:

    SELECT [x].[Id], [x].[Discriminator]
    FROM [network].[Address] AS [x]
    WHERE [x].[Discriminator] = Something

It should instead be (according to #1381):

    SELECT [x].[Id], [x].[Discriminator]
    FROM [network].[Address] AS [x]
    WHERE [x].[Discriminator] = 1

As a small fix I have changed the `GenerateLiteral()` in `DefaultSqlQueryGenerator.cs` to:

        protected virtual string GenerateLiteral([NotNull] object value)
        {
			if (value is Enum)
			{
				return string.Format(CultureInfo.InvariantCulture, "{0:d}", value);
			}
			else
			{
				return string.Format(CultureInfo.InvariantCulture, "{0}", value);
			}
        }

**Comment by divega** [comment]
@natemcmaster want to give this one a try?

**Comment by natemcmaster** [comment]
@divega Sure. I'll take a wack at it.

**Comment by natemcmaster** [comment]
@rmja Can you provide a repro project? I was unable to get the error.

I created [this sample project](https://gist.github.com/natemcmaster/039c66671b18894c64f7) to reproduce the error and this is the SQL generated:

```sql
@__p_0: 1

SELECT [x].[Id], [x].[Discriminator]
FROM [Address] AS [x]
WHERE [x].[Discriminator] = @__p_0
```

**Comment by rmja** [comment]
Hi @natemcmaster. This bug was previously seen for simple queries like the one I describe in the original post, but since then, it has somehow been fixed. However, when I use the Enum as a discriminator for a polymorphic setup, then the error is still present. I have made a reproducing example here: https://gist.github.com/rmja/691506a58907c07f9ce2

My setup is slightly different, as it uses an ef base that I have modified to allow for discriminators of type object instead of string. Here is the patch:

```
$ git diff --cached
diff --git a/src/EntityFramework.Relational/Metadata/IRelationalEntityTypeExtensions.cs b/src/EntityFramework.Relational/Metadata/IRelationalEntityTypeExtensions.cs
index 80fb2cd..b1cf1de 100644
--- a/src/EntityFramework.Relational/Metadata/IRelationalEntityTypeExtensions.cs
+++ b/src/EntityFramework.Relational/Metadata/IRelationalEntityTypeExtensions.cs
@@ -10,6 +10,6 @@ namespace Microsoft.Data.Entity.Relational.Metadata
         string Table { get; }
         string Schema { get; }
         IProperty DiscriminatorProperty { get; }
-        string DiscriminatorValue { get; } // TODO: should be object
+        object DiscriminatorValue { get; }
     }
 }
diff --git a/src/EntityFramework.Relational/Metadata/ReadOnlyRelationalEntityTypeExtensions.cs b/src/EntityFramework.Relational/Metadata/ReadOnlyRelationalEntityTypeExtensions.cs
index 9f52ac1..00b8604 100644
--- a/src/EntityFramework.Relational/Metadata/ReadOnlyRelationalEntityTypeExtensions.cs
+++ b/src/EntityFramework.Relational/Metadata/ReadOnlyRelationalEntityTypeExtensions.cs
@@ -36,8 +36,8 @@ namespace Microsoft.Data.Entity.Relational.Metadata
                     (string)_entityType.RootType()
                         .GetAnnotation(DiscriminatorPropertyAnnotation).Value);

-        public virtual string DiscriminatorValue
-            => _entityType[DiscriminatorValueAnnotation] as string
+        public virtual object DiscriminatorValue
+            => _entityType[DiscriminatorValueAnnotation]
                ?? _entityType.DisplayName();

         protected virtual IEntityType EntityType => _entityType;
diff --git a/src/EntityFramework.Relational/Metadata/RelationalEntityTypeExtensions.cs b/src/EntityFramework.Relational/Metadata/RelationalEntityTypeExtensions.cs
index 47ac403..6ef84a8 100644
--- a/src/EntityFramework.Relational/Metadata/RelationalEntityTypeExtensions.cs
+++ b/src/EntityFramework.Relational/Metadata/RelationalEntityTypeExtensions.cs
@@ -68,7 +68,7 @@ namespace Microsoft.Data.Entity.Relational.Metadata
             }
         }

-        public new virtual string DiscriminatorValue
+        public new virtual object DiscriminatorValue
         {
             get { return base.DiscriminatorValue; }
             [param: CanBeNull] set { EntityType[DiscriminatorValueAnnotation] = value; }
diff --git a/src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs b/src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
index ec12634..d11a5f2 100644
--- a/src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
+++ b/src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
@@ -860,6 +860,9 @@ namespace Microsoft.Data.Entity.Relational.Query.Sql
         protected virtual string GenerateLiteral([NotNull] object value)
             => string.Format(CultureInfo.InvariantCulture, "{0}", value);

+        //protected virtual string GenerateLiteral(Enum value)
+        //    => string.Format(CultureInfo.InvariantCulture, "{0:d}", value);
+
         protected virtual string GenerateLiteral(int value)
             => value.ToString();
```

The commented lines in the last file "fixes" the problem. Here is the produced invalid SQL:

```
exec sp_executesql N'SELECT [x].[Id], [x].[Discriminator]
FROM [Address] AS [x]
WHERE ([x].[Discriminator] IN (EmployeeAddress, CustomerAddress) AND [x].[Discriminator] = @__p_0)',N'@__p_0 int',@__p_0=1
go
```

I have tried to use, in MyContext.cs in the repro, e.g.:

    customer.Relational().DiscriminatorValue = (int)Discriminator.CustomerAddress;

instead of:

    customer.Relational().DiscriminatorValue = Discriminator.CustomerAddress;

but that leads to invalid cast exception.

Let me know if you need more info.

**Comment by natemcmaster** [comment]
Thanks for posting this very detailed repro. This helps a lot when trying to replicate the errors you see. 

It appears to me the invalid SQL you are seeing is a result of the changes you made to EF. The patch you included takes care of compiler type-checking, but doesn't account for the type-assumptions in query. The SQL generation produces invalid SQL because query generation assumes the discriminator value is a string (for now). Allowing DiscriminatorValue to support `object` will require additional changes to the query pipeline.

This issue has grown into feature request rather than a bug in query. I'd recommend closing this issue and creating a new issue to request DiscriminatorValue as an object, not just a string.

**Comment by rmja** [comment]
@natemcmaster you are right. The error is not the same as the one I original posted, as it is now only visible in the inheritance setup. I will close and make a feature request.
