### ISSUE TITLE
OrderBy() not translating to SQL ORDER BY?

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#2071]
I'm trying to make the `FunctionalTests.QueryTestBase.Take_Distinct()` test pass on PostgreSQL, and am running into some issues - am probably misunderstanding something.

This test runs the query `os.OrderBy(o => o.OrderID).Take(5).Distinct()`. The `SelectExpression` that gets generated from this has `_orderBy` empty, and the SQL that gets generated from that accordingly has no `ORDER BY` clause:

```sql
SELECT DISTINCT "o"."OrderID", "o"."CustomerID", "o"."EmployeeID", "o"."OrderDate" FROM "Orders" AS "o" LIMIT 5
```
(note that in PostgreSQL we have `LIMIT 5`, in SqlServer it's probably `TOP 5`)

Since there is no `ORDER BY` clause, the actual elements returned by this query aren't well-defined, and therefore it seems impossible to assert on them (my test fails)... What am I missing here?

**Comment by rowanmiller** [comment]
@maumar can you help out with this one

**Comment by anpete** [comment]
Bug. Poaching

**Comment by roji** [comment]
Test passes for me, closing.
