### ISSUE TITLE
DbDataReader.GetValues is called multiple times for the same data

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#2080]
One row from a data reader can contain many different blocks of columns, which are then bound to different ValueBuffers at different offsets into the reader. When using the typed buffer factory (which used GetFieldValue) this is not a problem because only the columns needed are read into each buffer, and each buffer is only as big as it needs to be. When using the non-typed buffer factory the GetValues method is used to read all values every time that a ValueBuffer is created, even though only a subset of those values will actually be used. This results in GetValues being called multiple times for the same reader, and the resulting buffers contain values that are never used.

**Comment by anpete** [comment]
This is fixed in the recent query work.

**Comment by divega** [comment]
Just to confirm, do we now call `GetValues()` only once per database query result row?

**Comment by anpete** [comment]
Yes.
