### ISSUE TITLE
Add timeout values to all regex expressions

### ISSUE THREAD

**Issue by blowdart** [aspnet/EntityFramework#2096]
To avoid potential regular expression attacks all regular expressions should have specify time-out values.

**Comment by rowanmiller** [comment]
@mikary we don't think we use regex anywhere... can you verify

**Comment by blowdart** [comment]
I only created this item in repos that do use it, I'm not that mean

src/EntityFramework.SqlServer.Design/Utilities/SqlServerLiteralUtilities.cs 
src/EntityFramework.Relational/Migrations/Infrastructure/MigrationIdGenerator.cs 
src/EntityFramework.Relational.Design/CodeGeneration/CSharpUtilities.cs 
tools/Resources.tt 

I'm not concerned with the one used in test.

**Comment by divega** [comment]
Yes @blowdart you are right, we do use them in a few places. @mikary, when reviewing please focus on cases in which a regex could be used to process untrusted input. Talk to @rowanmiller for our guidance on what APIs should not be used with untrusted input. And you can ask @blowdart if you find any scenario that needs clarification.

**Comment by blowdart** [comment]
Even with untrusted input I'd like people to get into the habit of setting a timeout, so should input change we're still good, hence my blanket request.

**Comment by GSPP** [comment]
Be aware that a GC, or any other load-caused interruption, can cause a 1sec timeout to be exceeded. This change might introduce non-deterministic failures. As I understand the commit these regexes are never run in production (?). Is there really a need to guard here? Maybe the timeout should be very high, like 30sec. That would be a last resort mitigation which I think is fine.
