### ISSUE TITLE
Improve experience for query-specific configuration

### ISSUE THREAD

**Issue by mikary** [aspnet/EntityFramework#2106]
divega
>@mikary @anpete Anyone remembers why ```FromSql()``` returns an ```IQueryable<TEntity>```? Looks like with this design it should also return a ```DbSet<TEntity>``` same as the new operator and that both should work in any order applied to the same query.

anpete
>Agreed. @mikary?

mikary
>Not really, I'm still not convinced that there's a good reason to switch back to a DbSet after FromSql. If we have a compelling reason to compose on FromSql as a DbSet, it's not a breaking change to switch from IQueryable, but until we have a compelling reason, it only seems to enable cases like

>```cs
context.Set<Customer>().FromSql(myQueryString).UseRelationalNullSemantics().AddRange(myCustomers);
```


anpete
>Yes, it removes the strange API ordering restriction and doesn't seem to have any downsides? I guess it could simplify the impl too.


mikary
>I don't like what it does to the API surface for intelisense, it's like having ```Where``` return a DbSet. I don't see FromSql behaving as a query configuration option so much as a part of the query itself that just happens to need to be the first clause so we know how to alias/compose it.


divega
> > I don't like what it does to the API surface for intelisense

> The only possible downside I see in the Intellisense experience is that you would now be able to chain multiple calls to ```FromSql()``` on the same query. It is fair point. Most likely code that did this would be written by mistake. However this not worse than being able to call ```.ToList().ToList()``` as long as we follow consistent rules on how this is interpreted, e.g. we could pick between "last one wins" (my preference) and more than one call results in a run time error.

> > it's like having Where return a DbSet,,,

> Why is that? It is true that ```FromSql()``` and ```UseRelationalNullSemantics()``` are different. ```FromSql()``` applies to query roots (and you can have more than one root in a query) while ```UseRelationalNullSemantics()``` is meant to apply to the whole query regardless of how many roots it has. Associating the call to ```UseRelationalNullSemantics()``` with one of the roots is just a pragmatic compromise (although it is yet another reason for me to prefer the introduction of explicit "relational comparison" operators and a context-level flag over this design). Once you have more than one "query operator" that can only be assigned to the root (as opposed to arbitrary parts of the query), it is really very desirable that they can be called in any order.


mikary
>>The only possible downside I see in the Intellisense experience is that you would now be able to chain multiple calls to FromSql() on the same query. It is fair point. Most likely code that did this would be written by mistake.

> We were also talking about ```AsNoTracking``` being a 'configuration' option of this type. If we return a ```DbSet``` we also make something like this compile:

>```cs
context.Set<Foo>().AsNoTracking().Attach(myFoo);
...
context.SaveChanges();
```

>Which looks like it's attaching an untracked entity, but since it's just a query annotation on the DbSet in a code path that isn't actually being visited, the annotation does nothing.

>My objection here would go away if we had the extension off of a different type without the extra DbSet functionality, for example:

>```cs
public static RootQueryable<TEntity> FromSql<TEntity>([NotNull]this RootQueryable<TEntity> rootQueryable, [NotNull]string sql)
```
> >it is really very desirable that they can be called in any order.

>I'm not convinced that it is desirable. Part of the reason I left the return type as ```IQueryable``` was due to YAGNI. ```FromSql``` was the only extension that we needed rooted to the beginning of the query. Now that we are adding other options, we were commenting that this pattern isn't very good for the other configuration options anyway.

>The original scenario we were discussing with ```FromSql``` was some kind of cross-store situation where each provider has some kind of composable raw command operation, i.e. ```FromSql``` and ```FromRedis``` so we could have something like:

>```cs
context.Set<Foo>().FromSql(sqlCommand).FromRedis(redisCommand).Where(f => f.bar == 5);
```
While there is clearly some utility to being able to do this, it also seems to say "I have a context and I don't know what provider it has, but try this." Given that the concept of composable opaque raw commands is fairly new, and that we are talking about cross-store functionality, I think it would be safer to leave it as is rather than introduce a potential pit of failure.

divega
> (trying to bring the discussion to the present diff to make finding it less annoying)

>>we also make something like this compile: context.Set<Foo>().AsNoTracking().Attach(myFoo);...

>I see. You are right on that.

>>My objection here would go away if we had the extension off of a different type without the extra DbSet functionality

>I agree this would be a way to improve it. Let's file a bug on this issue and discuss more options on how to improve it. We can hold off making changes to FromSql() until we decide.

>Re you other comment I do think it is important to keep this composable and hopefully we will be able to come up with something good. I cannot think how support expressing alternative raw root queries for different providers could become a pit of failure.

anpete
>Right now, AsNoTracking is a real ResultOperator and so it makes sense to exclude it from this discussion.

>How about this:

>```cs
context.Products
    .ConfigureQuery(o => 
        { 
            o.FromSql("blah");
            o.UseRelationalNullSemantics();
        })
     .Where(); // ...
```
>ConfigureQuery can then return IQueryable, and it matches our standard closure/annotation pattern for config.

**Comment by mikary** [comment]
I like the ConfigureQuery / builder pattern, but it does seem like it would get verbose if we wanted to apply a setting for multiple calls on a ```DbSet``` or the entire context.

On the other hand, a consumer could do something like


```cs
public static IQueryable<TEntity> ConfiguredSet<TEntity>(this MyContext context)
{
    return context.Set<TEntity>().ConfigureQuery( o =>
        {
            o.UseRelationalNullSemantics();
        });
}
```

**Comment by anpete** [comment]
Yep, or just a method in the context.

**Comment by divega** [comment]
>> I like the ConfigureQuery / builder pattern, but it does seem like it would get verbose if ...

Is there any scenario in which this isn't more verbose than simple method chaining?

**Comment by mikary** [comment]
I don't think there is a pattern that would be as terse as method chaining with query level granularity. If we wanted a ```DbContext``` level control we could also have something like:
```cs
public virtual OnConfiguringQuery(QueryConfigurationBuilder queryConfigurationBuilder)
{
}
```

Though I'm not sure this is really worth serious consideration

**Comment by rowanmiller** [comment]
**Triage** We'll just put a flag on DbContext `DbContext.Database.UseRelationalNullSemantics(true)`

**Comment by divega** [comment]
Superseded by #2403.
