### ISSUE TITLE
Reuse of EntityFramework.Relational.FunctionalTests.dll

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2114]
I have started writing a relational provider for EF7, and in order to run the test suite, I need the dll above. Maybe you should think about how to make it available to others. Just now, I have to build the dll and add a reference from my test project. Is there a better way (now or later) ? 
Looks like it will soon be the same issue with EF.Core.FunctionalTests.dll

**Comment by rowanmiller** [comment]
**Note for Triage** In today's triage we thought we had an item tracking this but I wasn't able to find it. I think we're all agreed that we should publish the tests as a NuGet package, we should just decided on package name and priority in next triage.

**Comment by ErikEJ** [comment]
Sounds great.. turned out I basically needed most of them, not just the one mentioned in the issue title

**Comment by rowanmiller** [comment]
For the moment we'll just publish to MyGet. In the future we need to come up with a proper test spec.

**Comment by ErikEJ** [comment]
Great, thanks - that will Work fine for now!

**Comment by ErikEJ** [comment]
@bricelam Great, but I also need: EntityFramework.Core.Tests.dll and EntityFramework.Relational.Tests.dll - sorry
