### ISSUE TITLE
EF7 Beta 4 bug with zero value in column

### ISSUE THREAD

**Issue by tstar** [aspnet/EntityFramework#2117]
I have table "Test" with columns: Age (int), Value (int) and data:
Age: 0, Value: 1
Age: 1, Value: 2

Model for Test table:
public class Test
{
	public int Age { get; set; }
	public int Value { get; set; }
}

If I run Test.AsArray or Test.AsList() then in result I have some like:
[0] null
[1] [1, 2]

Also, if I run Test.Where(i => i.Age == 0).FirstOrDefault() then I have null in result too.

If I change int field "Age" to nullable int in my model, then all work well.

In Beta 2 this tests runs well.

I could not run the Beta 5 in the VS 2015 RC to test this error.

**Comment by rowanmiller** [comment]
@tstar can you provide a complete code listing that we can use to reproduce this issue.

**Comment by tstar** [comment]
Hello.
I was able to test this mistake with EntityFramework.SqlServer 7.0.0-beta5-13202. As a result, I got an error: System.InvalidOperationException in EntityFramework.Core.dll: The instance of entity type 'Test' cannot be loaded because it has an invalid (e.g. null or CLR default) primary key.

My table in database:
```
CREATE TABLE [dbo].[Test](
	[Age] [int] NOT NULL,
	[Value] [int] NOT NULL,
 CONSTRAINT [PK_Test] PRIMARY KEY CLUSTERED 
(
	[Age] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```

Data in table:
```
Age	Value
0	111
1	222
```
Code:
```
modelBuilder.Entity<Test> (x => 
{
	x.ForSqlServer().Table("Test", "dbo");
	x.Key(i => i.Age);
});

public DbSet<Test> TestTable { get; set; }

public class Test
{
	public int Age { get; set; }
	public int Value { get; set; }
}

using (var db = new TestContext())
{
	var z = db.TestTable.ToList(); // At this point, an error occurs.
	var zz = z.Count();
}
```
If I change the key value from 0 to 2 in "Age" column, then error does not occur.

**Comment by ajcvickers** [comment]
@tstar To make this work either set the sentinel value that EF is using to indicate and unset property to some value other than zero, e.g. -1, or make the key property nullable so that EF will use null as the unset value. See the scenarios here for examples: https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes:-July-2,-2015

**Comment by tstar** [comment]
Unfortunately, I did not understand that I need to do to read all the data from the table into an array. I can not find the property StoreGeneratedPattern. I tested on version 7.0.0-beta6-13752.

**Comment by tstar** [comment]
We must reopen this issue, because from version 7.0.0-beta7-13905 I had a problem again as described at the beginning of this topic. Now, there is no exception, but I have Null, if the primary key column is set to 0 without any exceptions.

**Comment by rowanmiller** [comment]
@tstar can you open a new issue and include a complete code listing so that we can understand what behavior you are seeing and what you expect.
