### ISSUE TITLE
Investigate failing SQLite tests

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#2121]
I've implemented them in [bricelam:sqlitest2](https://github.com/aspnet/EntityFramework/compare/dev...bricelam:sqlitest2), but they're not passing.

- [x] AsyncFromSqlQueryTest
- [x] AsyncQueryTest
- [x] BuiltInDataTypesTest
- [x] FromSqlQueryTest
- [x] GearsOfWarQueryTest
- [ ] GraphUpdatesTest
- [x] IncludeOneToOneTest
- [x] InheritanceTest
- [x] MappingQueryTest
- [x] MonsterFixupTest
- [x] NullSemanticsQueryTest
- [x] OptimisticConcurrencyTest
- [x] QueryTest
- [x] StoreGeneratedTest
- [x] TransactionTest

**Comment by rowanmiller** [comment]
@maumar can you look at the query tests that are failing

**Comment by bricelam** [comment]
@natemcmaster You could start looking at some of the non-query tests. OptimisticConcurrencyTest & TransactionTest seem like good starting points.

**Comment by ErikEJ** [comment]
@natemcmaster Welcome back!

**Comment by natemcmaster** [comment]
BuiltInDataTypesTest continues to have problems on DNX core, even with #2230. Failures are due to the table not being created correctly.

**Comment by natemcmaster** [comment]
Blocked on a bug in update pipeline. #2238
