### ISSUE TITLE
Model Definition: Implement Default Model Builder Conventions

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#213]
- [x] Entity type conventions
  - [x] Property discovery
    - [x] Support for Ignore on property
  - [x] Navigation/relationship discovery
    - [x] Support for Ignore on entity type
    - [x] Support for Ignore on navigation property
    - [x] ~~Do not discover entity types if no relationships to it can be created~~ (Relationships can always be created to non-shadow entity types)
  - [x] Key properties discovery
- [x] FK conventions
  - [x] Determine the principal in 1-1 deterministically using the entity type/navigation order
  - [x] FK properties discovery
  - [x] ~~New property triggers FK convention~~ (Not needed yet, will revisit after RTM)
- [x] Key conventions
  - [x] New PK triggers FK creation on already discovered relationships
  - [x] ~~New CK triggers FK properties discovery for any referencing FKs~~ (Existing CKs aren't used for relationships by convention)
- [x] Provider-specific conventions
  - [x] ~~MaxLength~~ (The default MaxLength will be determined by the TypeMapper and not stored in the model)
  - [x] ~~FK facet propagation~~ (This will be handled by the RelationalTypeMapper, see #2455)
  - [x] SqlServer Identity
- [x] ~~Internal builder wrappers for conventions~~ (Convention API polish will happen after RTM)

**Comment by divega** [comment]
@smitpatel Please talk to @AndriySvyryd about how to approach the remaining work.
