### ISSUE TITLE
Metadata: Allow unbound navigation properties

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#2140]
For example:

```C#
mb.Entity<Post>().Reference<Blog>("Blog").InverseCollection("Posts");
```

We could then store this in model snapshot and use it to help detect foreign key column renames.

It could also make configuring foreign keys without any navigation properties a little less awkward.

**Comment by rowanmiller** [comment]
@smitpatel please talk to @ajcvickers about this one

**Comment by divega** [comment]
@bricelam @rowanmiller @ajcvickers @AndriySvyryd @smitpatel is this item missing a priority or do we need to investigate it further? @lajones talked about it today because it would allow cleaning up reveng and our provider contract for it.

**Comment by ajcvickers** [comment]
@bricelam @rowanmiller @AndriySvyryd @smitpatel @lajones I suspect that Migrations doesn't need it yet because its not diffing navigation properties, but @bricelam can confirm. This makes it lower priority for Migrations, so the priority may depend on its importance for reverse engineering.

**Comment by divega** [comment]
Unassigning and moving to backlog. We can make migrations smarter and tidy up reverse engineering if we add this later.

**Comment by divega** [comment]
Clearing up the milestone as we mentioned in a recent reverse engineering discussion that we may decide to implement this for RTM.

**Comment by rowanmiller** [comment]
Initially this should be similar to shadow entities where they are non-functional

**Comment by smitpatel** [comment]
Filed #5154 & #5155 for RevEng & Migrations to utilize shadow navigations.
