### ISSUE TITLE
Renable Fluent_api_methods_should_not_return_void

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#2148]
It's being removed because it only ran against BasicModelBuilder, which is being removed. We should consider running it against all builder types and investigating those that return void--currently Ignore returns void.

**Comment by smitpatel** [comment]
Following methods return void
- `ModelBuilder`
  - `Ignore<TEntity>()`
  - `Ignore(Type type)`
- `EntityTypeBuilder<>`
  - `Ignore(Expression<Func<TEntity, object>> propertyExpression)`
- `EntityTypeBuilder`
  - `Ignore(string propertyName)`

**Comment by rowanmiller** [comment]
I think Ignore for entities would return ModelBuilder and for properties would return the EntityTypeBuilder

@anpete @ajcvickers agree?

**Comment by ajcvickers** [comment]
@AndriySvyryd ?

**Comment by AndriySvyryd** [comment]
fine with me
