### ISSUE TITLE
Documentation for Dependency Injection configuration incomplete

### ISSUE THREAD

**Issue by matthewDDennis** [aspnet/EntityFramework#2151]
The current examples in the wiki instruct use to create a constructor
```c#
public TheContext(DbContextOptions options) 
: base(options) 
{}
```
This fails if there are multiple` DbContexts` using different connection strings as either the first or last used connection string is registered in the `DbContextOptions`.
The constructor should be
```c#
public TheContext(DbContextOptions<TheContext> options) 
: base(options) 
{}
```
to have the correct options injected.

**Comment by rowanmiller** [comment]
You no longer need the ctor parameter and our docs are all updated
