### ISSUE TITLE
Adding NuGet reference to EF.Relational with latest daily (beta5-13161) is broken

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2152]
**Platform**
 Windows 81. x64, Visual Studio 2015 RC, NuGet 3.0.60410.213

**Repro**
- Add new C# Desktop Console app, target .NET 4.5. 
- Add NuGet package: EntityFramework.Relational

**Expected**
Required references are added to the project

**Actual**
An error occurs (tested on 2 PCs):
Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache.

**Regression**
beta5-13087 works as expected:
Successfully installed 'EntityFramework.Relational 7.0.0-beta5-13087' to ConsoleApplication1.
Wonder if it is related to: https://github.com/dotnet/corefx/commit/57df1c06dc025aa6bd031603a8497b9c44137d85 
**Package manager log (extracts)**
Attempting to gather dependencies information for package 'EntityFramework.Relational.7.0.0-beta5-13161' with respect to project targeting '.NETFramework, Version=v4.5'
Attempting to resolve dependencies for package 'EntityFramework.Relational.7.0.0-beta5-13161' with DependencyBehavior 'Lowest'
Resolving actions to install package 'EntityFramework.Relational.7.0.0-beta5-13161'
Resolved actions to install package 'EntityFramework.Relational.7.0.0-beta5-13161'
For adding package 'Ix-Async 1.2.3' to project 'ConsoleApplication1' that targets 'net45'.
..
Added reference 'System.Resources.ResourceManager' in the Global Assembly Cache to project 'ConsoleApplication1'
Install failed. Rolling back...
..
System.InvalidOperationException: Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache. ---> System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at VSLangProj.References.Add(String bstrPath)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddGacReference(String name)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddFrameworkReference(String name)
   --- End of inner exception stack trace ---
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__ea.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActions>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()

**Comment by bricelam** [comment]
What version of NuGet are you using?

**Comment by ErikEJ** [comment]
@bricelam The one that comes with VS 2015 RC: 3.0.60410.213

**Comment by htuomola** [comment]
I'm also seeing this now, trying to upgrade EntityFramework.Relational to version from version '7.0.0-beta5-13026' to '7.0.0-beta5-13190'. I'm seeing errors like 
```
Failed to add reference to 'System.Linq'. Please make sure that it is in the Global Assembly Cache.
+ Update-Package EntityFramework.Relational -source "https://www.myget.org/F/aspne ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand
```
I've seen it with a few different assemblies. The project is on .NET 4.5.2 and I've got Nuget version is 2.8.60318.734 (I'm using VS 2013).

**Comment by ErikEJ** [comment]
@bricelam Still seeing this with beta5-13202

**Comment by htuomola** [comment]
I did some testing on this as I had to upgrade my packages (because .InMemory v. -13026 is not anymore on MyGet and it broke my build). The last working build I've found is 7.0.0-beta5-13087. I've tested the following and none of them installs:
- 7.0.0-beta5-13107
- 7.0.0-beta5-13171
- 7.0.0-beta5-13182 
- 7.0.0-beta5-13190

**Comment by ErikEJ** [comment]
So please leave beta5-13087 on myget until this is fixed, thanks

**Comment by bricelam** [comment]
@yishaigalatzer Have you seen any similar reports on your end?

**Comment by bricelam** [comment]
I think @rowanmiller and I just got to the bottom of this--having facade assemblies in the packages framework references. I'll work on getting a fix out soon.

**Comment by ErikEJ** [comment]
Great @bricelam & @rowanmiller - and thanks!

**Comment by julielerman** [comment]
could this have anything to do with why installing EF packges just hangs for a long tme

for example:
PM> install-package entityframework.inmemory -pre
Attempting to gather dependencies information for package 'entityframework.inmemory.7.0.0-beta5-13202' with respect to project targeting '.NETFramework, Version=v4.5.2'
Attempting to resolve dependencies for package 'entityframework.inmemory.7.0.0-beta5-13202' with DependencyBehavior 'Lowest'

Its been stuck on "attempting to resolve" for 15 minutes already.  I had a lot of this all day. Thought it was my internet but now know that my internet is okay.

This is also VS2015 RC with whatever got installed with it on windows 8.1 machine.

**Comment by yishaigalatzer** [comment]
@julielerman this is not related. We think we fixed this bug in nuget, and a major root cause could be related to packages depending on unlisted packages. I might be wrong though, can you please file a bug with all the details on https://github/nuget/home/issues we need your vs version and your packages.config as well

**Comment by julielerman** [comment]
Thanks @yishaigalatzer . It's at https://github.com/aspnet/EntityFramework/issues/2209

I realized after I submitted it that you asked me to put it in nuget issues, not EF.
I have not determined if it's just EF or not but since each test means sitting and waiting for 5 or more minutes to see if anything will happen, I just can't test it any more. So much lost time already. Sorry.

**Comment by rowanmiller** [comment]
The fix for this has now made it onto our nightly feed. You will need to use the workaround for https://github.com/aspnet/EntityFramework/issues/2209 to avoid a hang when installing the package.
