### ISSUE TITLE
AppendSelectAffectedCountCommand - how to implement

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2155]
I am trying to run some (of the built-in) functional tests, and they do INSERTs statements to seed the test database. This requires AppendSelectAffectedCountCommand to return the @@rowcount, but the database engine does not support this. It only allows a batch size of one and a single command per batch, and  DbCommand.ExecuteNonQuery() can return the number of rows affected 

Any suggestions?

**Comment by ErikEJ** [comment]
To further clarify: Only a batch size of one (1) is allowed, and only one (1) SQL command per batch is allowed.

**Comment by ajcvickers** [comment]
@ErikEJ If we implemented what is described in #1956 would this help at all? Or do you absolutely need a batch size of one? If so, @AndriySvyryd can probably tell you what to do to enforce that--I think it is possible, but I don't remember without looking how to do it.

**Comment by ErikEJ** [comment]
@ajcvickers I am not sure I **absolutely** need a Batch Size of 1, having had a closer dive into the code. What I **DO** need is max 1 command per batch (provided I understand the concepts correctly). So one invocation of the provider's DbCommand.ExecuteXxx only allows one (1) SQL statement, you can never use

    SELECT *;SELECT @@IDENTITY

I read #1956 but I think the Postgres provider can return multiple results from a single command, and that is not the case, so I am not sure it will be enough. But then again, I probably lack understanding of Postgres

But "my" DbDataReader also supports RecordsAffected, yes. https://msdn.microsoft.com/en-us/library/system.data.sqlserverce.sqlcedatareader.recordsaffected(v=vs.100).aspx

**Comment by AndriySvyryd** [comment]
You just need to use a ModificationCommandBatch derived from SingularModificationCommandBatch, see https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Sqlite/Update/SqliteModificationCommandBatch.cs

**Comment by ErikEJ** [comment]
@AndriySvyryd Yes, I do that already, but it does not allow me to move on and do INSERTs, as my ADO.NET provider does not allow you to append SELECT @@ROWCOUNT to a statement, in fact it does not have @@ROWCOUNT, only the return value from ExecuteNonQuery and RecordsAffected are available (the SQLite provider supports "SELECT changes()" which is similar to SELECT @@ROWCOUNT I believe)

**Comment by AndriySvyryd** [comment]
Ah, I see. Then #1956 should help with this as it will allow to override only the code that consumes the results. Currently you would need to override Execute and ExecuteAsync from SingularModificationCommandBatch.

**Comment by ErikEJ** [comment]
Thanks, @andriysvyryd - looking forward to that, and will investigate if I can figure oit how to override Execute...

**Comment by ErikEJ** [comment]
Basic scenario with Guid Ids now working, thanks @ajcvickers  @AndriySvyryd !
