### ISSUE TITLE
QuerySqlServerTest has culture-dependent assertion

### ISSUE THREAD

**Issue by MichaelKetting** [aspnet/EntityFramework#2160]
Testcase QuerySqlServerTest.Where_chain is culture sensitive. When run with German system culture, the test fails with:
Expected: __p_0: 1/1/1998 12:00:00 AM\r\n\r\nSELECT [o].[Order···
Actual:   __p_0: 01.01.1998 00:00:00\r\n\r\nSELECT [o].[OrderI···

There's two options for this:0
1)  Either, the diagnostic output written by RelationalLoggerExtensions.LogParameters() should always be formatted in the local system's culture. In this case, the culture should be set and reset in the test fixture. 
2) Or, the logger should always use the same formatting, then a culture, e.g. Invariant, should be chosen and possibly even a specific formatting for Date-types (RFC1123, sortable, etc).

@ajcvickers: Since you did the Logger, do you have a preference for what you'd like to see in a PR?

**Comment by rowanmiller** [comment]
@maumar can you investigate what would make the most sense to do here

**Comment by rowanmiller** [comment]
We should try setting the current culture in the test

**Comment by dougbu** [comment]
@maumar stealing this bug because I fixed it last weekend...

**Comment by divega** [comment]
Hey @dougbu, can you explain the fix?

**Comment by dougbu** [comment]
@divega using the `[ReplaceCulture]` attribute from Microsoft.AspNet.Testing on the offending tests solves the problem.

**Comment by divega** [comment]
Thanks! Talked to @dougbu and it seems this should work in most cases where it can reasonably work, e.g. it won't do magic for async tests on 4.5.1 because the culture is in TLS but it should be good enough.

**Comment by MichaelKetting** [comment]
@dougbu Should this fix already be part of the current dev HEAD?

**Comment by dougbu** [comment]
@MichaelKetting no, not in `dev` yet. See PR #2321.

**Comment by MichaelKetting** [comment]
@dougbu  Good to know. Thanks!

**Comment by dougbu** [comment]
b6118c9

**Comment by ErikEJ** [comment]
Another dependency (on AspNet.Testing) - is that good?
