### ISSUE TITLE
Upgrade of re-linq to 2.0.0-alpha.4

### ISSUE THREAD

**Issue by MichaelKetting** [aspnet/EntityFramework#2162]
Hi @ajcvickers!

Figured this is the most straight forward way to do this: I'll be getting ready with the next drop of re-linq in the next couple of days and am going to send you guys a PR with the breaking changes already fixed (baring unforseen troubles). There's going to be a longer post about them over on our mailing list but the gist is that re-linq now depends on System's ExpressionVisitor instead of our own implementation from way back when (.NET 3.5 times). I would propose to update the namespaces, derived visitors, etc accordingly (namespace "ExpressenTreeVisitors" -> "ExpressionVisitors", etc)

I also removed the ExtensionExpression since it's no longer needed in .NET 4. Unless you guys would like to keep a common base class for Expressions?

Best regards, Michael

**Comment by anpete** [comment]
Hi @MichaelKetting, thanks for the heads-up, and for planning to send the PR!

Those changes sound good. The ExtensionExpression change sounds fine.

**Comment by MichaelKetting** [comment]
Hi @anpete!
Just gotten the PR ready. The mailing list post can be found here: https://groups.google.com/forum/#!topic/re-motion-users/QsXxiUjNJEI but I think the important stuff can be gleaned from the commit messages, too, I just went a tad more explanatory in the breaking changes docs.

The branch is currently based on top of dev. I think I should be able to do a daily rebase in case there's significant activity going on. 

Unrelated: 
Since I basically got to see most of the Expression tree scenery in EntityFramework, I might be sending a couple of refactoring and/or question tickets of things that I noticed your way. Should we do those via the issue tracker; I don't think there's a mailing list, correct?

Oh, and I find the QueryAnnotations-feature intriguing. Will have to study that one more closely :smile:

Best regards, Michael

**Comment by anpete** [comment]
Thanks @MichaelKetting!

The daily rebase would be great because I'm not sure when exactly we can take this as our dependency versions are currently locked. I will follow up on that.

Refactorings/improvements to our use/misuse of re-linq would be appreciated :-) No mailing list, fine just to use issues.

Thanks again.

**Comment by rowanmiller** [comment]
We should be good to take this mid next week - just need to keep dependencies the same while we get ready to branch for the next release.

**Comment by MichaelKetting** [comment]
Good to know. Thanks :smile:

**Comment by MichaelKetting** [comment]
merged in 3d3426145fddf05bc60c403b82c2cbb6fc0a6e52
