### ISSUE TITLE
A way to create alternate keys/unique constraints on ModelBuilder

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#2164]
Currently, the only way to create alternate keys (which translate to unique constraints in Migrations) it to have it play a part in a relationship.
```C#
modelBuilder.Entity<CreditReport>()
    .Reference(r => r.Person)
    .InverseCollection(p => p.CreditReports)
    .ForeignKey(r => r.PersonSSN)
    .PrincipalKey(p => p.SSN);
```
You can also drop down to core metadata.
```C#
var model = modelBuilder.Model;
var person = model.GetEntityType(typeof(Person));
var ssn = person.GetProperty("SSN");
person.AddKey(ssn);
```
Alternatively, you can just specify a unique index.
```C#
modelBuilder.Entity<Person>().Index(t => t.SSN).Unique();
```
I've seen a lot of users asking how to create a unique constraint. We should consider adding first-class API to ModelBuilder for doing this.

See comments on #866 for additional context.

**Comment by rowanmiller** [comment]
@smitpatel  bring a proposed design to team

`Entity<Person>().AlternateKey(p => p.SSN)` is one idea or `UniqueKey` or something else

**Comment by htuomola** [comment]
Now that this is implemented (well, the situation was the same already before when defining Unique constraints), should I be able to lookup entities by alternate key even if they're not saved to DB yet?

Code:
```csharp
public void RetrieveAddedEntityByAlternateKey()
{
	using (var ctx = new SimpleContext())
	{
		var parent = new Parent() { Id = Guid.NewGuid() };
		parent.Name = "John";
		parent.AlternateId = "010101-1234";
		ctx.Parents.Add(parent);

		var existingParent = ctx.Parents.FirstOrDefault(p => p.AlternateId == parent.AlternateId);
		Assert.IsNotNull(existingParent);

		ctx.SaveChanges();
	}
}
```

I remember seeing similar "issue" with EF 6 also but we fixed it by changing the approach.

Model building:
```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder.Entity<Parent>().Table("Parent");
	modelBuilder.Entity<Parent>().Key(r => r.Id);
	modelBuilder.Entity<Parent>().Property(r => r.Id);
	modelBuilder.Entity<Parent>().Property(p => p.AlternateId).MaxLength(32);
	modelBuilder.Entity<Parent>().AlternateKey(p => p.AlternateId);
}
```

Model:
```csharp
public class Parent
{
	public Parent()
	{
		Id = Guid.NewGuid();
	}

	public Guid Id { get; set; }
	public string Name { get; set; }
	public List<Child> Children { get; set; }
	public string AlternateId { get; set; }
}
```

**Comment by bricelam** [comment]
@htuomola Querying `ctx.Parents` will always query the database. For local objects, query `ctx.ChangeTracker.Entries<Parent>()`. (See also #1003) We also had a `Find` method on the set that would first look locally then query the database, but it is not implemented yet. (See #797)

**Comment by htuomola** [comment]
Thanks. I thought that Find was just another (old) way of doing
.FirstOrDefault(). In EF6, I believe Find can be used to lookup entities
only by primary key, so that wouldn't be helpful in this case either. I
think #797 doesn't quite mention this aspect (querying local data) of Find
so I didn't consider the issue so important. I already implemented the
workaround using ChangeTracker but that didn't seem right and that's why
I'm here :).
I do hope users are not forced to query DB and Local data separately. I'd
think that in most cases caller is interested in either entities in DB or
Local ones, of course following transaction separation. Having to query for
both separately seems a bit tedious.
