### ISSUE TITLE
HasTables()/HasTableAsync does not work with Azure SQL Database V12

### ISSUE THREAD

**Issue by Benjiiim** [aspnet/EntityFramework#2179]
The following TSQL command (in CreateHasTablesCommand()) always return 1 with "empty" Azure SQL Database V12 because a database_firewall_rules view is added by default in empty databases (script_deployments and script_deployment_status views are added as well after a migration from old Azure SQL Database version to V12):

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES) SELECT 1 ELSE SELECT 0

As this command is used in the HasTables()/HasTablesAsync() method in the SqlServerDataStoreCreator class to check if the table should be created, tables are never created.

**Comment by ErikEJ** [comment]
@Benjiiim  What is the TABLE_TYPE for those views in INFORMATION_SCHEMA.TABLES?

**Comment by rowanmiller** [comment]
Talk with @anpete  and @ajcvickers

**Comment by Benjiiim** [comment]
@ErikEJ : VIEW
I've workarounded it by adding a " WHERE TABLE_TYPE <> 'VIEW' " but I don't have the big picture.

**Comment by ErikEJ** [comment]
@Benjiiim Had a look at the code, seems like a bug, might do a PR
