### ISSUE TITLE
Generating SQL2012 specific code when using 2008R2

### ISSUE THREAD

**Issue by matthewDDennis** [aspnet/EntityFramework#2180]
I have a query that has Skip() and Take() calls to implement paging.  The code generated is in the form
```sql
SELECT ...FROM [Article] AS [a]
WHERE [a].[PublishingStatusId] = 2
ORDER BY [a].[Updated] DESC OFFSET 0 ROWS FETCH NEXT 25 ROWS ONLY 
```
The OFFSET ...  code is SQL2012+ only.

**Comment by ErikEJ** [comment]
I think that Means that only 2012, 2014 & 2016 are supported. Also consider the use of sequence.

**Comment by matthewDDennis** [comment]
How would Sequences help with Paging?
Is there any documentation on the minimum level/version of Sql Server that will be supported by EF7?
Its not an issue for us as we are moving to 2012 or 2014 next week, but it would be nice to have official requirements.

**Comment by divega** [comment]
I can confirm that the SQL generation we have in place for paging right now will only work with SQL Server 2012 and newer. But we haven't decided if this is going to be the case for RTM. We can probably enable older versions, it is just a matter of priority. Feedback is welcome.

**Comment by rowanmiller** [comment]
**Triage** We want to support 2008 onwards

**Comment by natemcmaster** [comment]
What about sequences? Options:

 - fallback to IDENTITY
 - throw
 - leave as is (let the resulting SQL error bubble up)
 - something else

**Comment by anpete** [comment]
Probably 3.

**Comment by divega** [comment]
Related to #2897. In fact so close that we could choose to close one as a dupe.

cc @rowanmiller

**Comment by rowanmiller** [comment]
I think this one is separate from the test issue. We need a way for folks to be able to run against 2008, at the moment I don't think there is any API surface or internal logic that allows preventing EF from generating OFFSET/FETCH. If it's an explicit API folks need to call, then there is a test component as well to make use of the API.

**Comment by divega** [comment]
Makes sense. This is a known product issue.

**Comment by natemcmaster** [comment]
**Suggestion**
For OFFSET/FETCH, use the ["select as" workaround](http://blog.sqlauthority.com/2013/04/14/sql-server-tricks-for-row-offset-and-paging-in-various-versions-of-sql-server/) to imitate paging on SQL 2008. Allow users to opt-in to backwards-compatibilty by configuration:

```c#
options.UseSqlServer(connStr).WithServerVersion(SqlServer.v2008);
```

Bonus: This could also allow us to handle the quirks of SQL Azure.
```c#
options.UseSqlServer(connStr).WithServerVersion(SqlServer.Azure);
```

**Comment by divega** [comment]
@natemcmaster some time ago we discussed having something like this in the API but for various reasons we decided against pivoting on server version an for having a more granular API to turn on/off specific behaviors (one of the reasons I remember is that SQL Azure DB is a moving target that at any point in time will most likely support a subset of the latest on-premises version of SQL Server), e.g.:

``` C#
options.UseSqlServer(connStr).UseLegacyPaging();
``` 

Re the workaround, at first glance the SQL Server 2008/2005 version looks similar to what EF6 would do. I would suggest you give EF6 a try.

FWIW, the last version of the workaround with the three ORDER BYs looks clever, although I am surprised that it works in SQL Server 2000 as is (as far as I can remember SQL Server did not support parameters/variables in SELECT TOP until 2005). Anyway, supporting anything older than 2008 is not in scope. It just made me wonder if other providers (like the SQL CE one) could use this pattern.

cc @ErikEJ

**Comment by ErikEJ** [comment]
@divega Agree on the Azure strategy, it will always be a moving target, and is almost on par with the on-premise version these days.

Enabling "WithLegacyPaging" or similar will actually enable EF7 to support SQL Server 2005 and later, no matter what your scope may be.

I have tried the SQL Server 2000 paging solution, and it works with SQL CE 3.5 SP2, so it would be very beneficial if we somehow could enable this for SQL CE 3.5 (using hardcoded TOP values, not parameters, however)

**Comment by RickyLin** [comment]
Please solve the pagination issue for SQL Server 2008 ASAP even if a dirty implementation. I asked this in #1326.
Actually I can handle it myself by creating my QuerySqlGenerator based on `DefaultQuerySqlGenerator`, however, it's not easy to replace `SqlServerQuerySqlGenerator` with my QuerySqlGenerator, I have to create my `SqlServerDatabase`, my `SqlServerQueryCompilationContext` as well.

**Comment by natemcmaster** [comment]
@RickyLin stay tuned. We plan on adding a solution for legacy paging.

**Comment by ErikEJ** [comment]
@natemcmaster +1 for the sql 2000 syntax, which will also work with sqlce 3,5!
