### ISSUE TITLE
Many levels of AggregateException (requires update of ix-async)

### ISSUE THREAD

**Issue by jonegerton** [aspnet/EntityFramework#2192]
[As per SO question here](http://stackoverflow.com/q/30233542/592111)

 I made a simple mistake with some linq (used Skip and forgot to include my OrderBy clause).

The exception that was thrown by this included a number of nested aggregate exceptions.

The code that generates (and catches) the exception is:

    int[] newIds;
    try
    {
        newIds = await db.Products
            .Where(p => p.PortalId == portalId)
            .Skip(ids.ProductIds.Count) //Skip the rows already read
            .Take(takeTotal) //get the next block
            .Select(p => p.ProductId)
            .ToArrayAsync();
    }
    catch (AggregateException ex)
    {
        Console.WriteLine(ex.Message);
        newIds = new int[] { };
    }

However the aggregate exception that I got from this was (this is dumped to the immediate window from the catch block shown above):

>System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: A query containing the Skip operator must include at least one OrderBy operation. at Microsoft.Data.Entity.Relational.Query.Sql.DefaultSqlQueryGenerator.GenerateLimitOffset(SelectExpression selectExpression) at Microsoft.Data.Entity.Relational.Query.Sql.DefaultSqlQueryGenerator.VisitSelectExpression(SelectExpression selectExpression) at Microsoft.Data.Entity.Relational.Query.Expressions.SelectExpression.Accept(ExpressionTreeVisitor visitor) at Microsoft.Data.Entity.Relational.Query.Sql.DefaultSqlQueryGenerator.GenerateSql(SelectExpression selectExpression, IDictionary`2 parameterValues) etc etc

The code was originally running in a WebApi controller with a bunch of levels of async-await, so I thought that the AggregateException layers might be a symptom of that, however I've also tested with a console app just running the EF code, and I still get the nested exceptions. I assume that the levels of exception are due to layers of async-await within the EF code itself. 

As the the comments on the SO question, it can be worked around by using `GetBaseException()`, however I mainly wanted to query wether it was intentional that the exception exiting from the EF code would look like this or whether you'd look to wrap it/flatten it for more pleasant public consumption.

**Comment by fujiy** [comment]
@laskoviymishka, do you know why this happens? await should handle that?

**Comment by laskoviymishka** [comment]
@fujiy i researched this a little bit, but not find source of issue :cry:  . I think somewhere incorrect exception handling, but can't find where.

**Comment by fujiy** [comment]
@laskoviymishka you are rethrowing the exception, so it will lose the stack trace.

I spend some time trying to figure out whats happening with no success.

Looking at EnumeratorExceptionInterceptor.MoveNext, if I change this line:

return await _inner.MoveNext(cancellationToken);

To

var t = _inner.MoveNext(cancellationToken);
//var test = t.Result;
return test;

If I create a BreakPoint before returning and call t.Result in Command Window. I can get the result without errors. But uncommenting that line throws a errors.

I  don't know what I am missing.

**Comment by fujiy** [comment]
One more info. Its happens when an exception is thrown at AsyncEnumerator.MoveNext

**Comment by fujiy** [comment]
I think its Ix-Async (Rx.NET) fault:

            var asyncEnumerable = AsyncEnumerable.ToAsyncEnumerable(GetEnumerableWithError());


            try
            {
                var bResult = await asyncEnumerable.ToArray();
            }
            catch (Exception ex)
            {
                //AggregateException
            }


        private IEnumerable<int> GetEnumerableWithError()
        {
            yield return 0;
            yield return 1;
            yield return 2;
            throw new Exception("Some error");
        }

**Comment by fujiy** [comment]
I think I finally found the root cause. I am sending a Pull Request to Rx.NET: https://github.com/Reactive-Extensions/Rx.NET/pull/131

This line is missing a ".InnerException":

https://github.com/Reactive-Extensions/Rx.NET/blob/master/Ix.NET/Source/System.Interactive.Async/TaskExt.cs#L36

The Generate method also wraps the Exception. I don't know why yet, but should be a reason:

https://github.com/Reactive-Extensions/Rx.NET/blob/master/Ix.NET/Source/System.Interactive.Async/AsyncEnumerable.Creation.cs#L204

Changing it to "throw;" fix this test:

var a = AsyncEnumerable.Generate(10, (x) => { throw new Exception("Blah"); }, (x) => { return 1; }, (x) => { return 2; });

            try
            {
                var bResult2 = await a.ToArray();
            }
            catch (Exception ex)
            {
                //AggregateException
            }

**Comment by rowanmiller** [comment]
@fujiy nice work :+1:

**Comment by fujiy** [comment]
Unfortunately Rx.NET project seems inactive

**Comment by divega** [comment]
CC @bartdesmet

**Comment by fujiy** [comment]
Disappointed for not being listed as a contributor in Rx.NET ;)

**Comment by bartdesmet** [comment]
Sorry about that; we're still getting our process for PRs smoothened out over here. When you're visiting the mother ship, I'll pay you a coffee to compensate :-).

**Comment by fujiy** [comment]
Deal :+1:

**Comment by rowanmiller** [comment]
@bartdesmet any plans for an updated release that will include this fix?

**Comment by natemcmaster** [comment]
A fix was added to Ix-Async in https://github.com/Reactive-Extensions/Rx.NET/pull/137 and should be in the next release of Ix-Async.
