### ISSUE TITLE
Switch test projects to use .NET 4.6

### ISSUE THREAD

**Issue by MichaelKetting** [aspnet/EntityFramework#2203]
As suggested by @divega and @bricelam in #2160, the test projects would benefit from switching to .NET 4.6 by enabling the use of .NET 4.6 APIs, e.g. setable CultureInfo.CurrentCulture/CurrentUICulture properties.

**Comment by ErikEJ** [comment]
Concerned if that will break my 4.5 dependent provider?

**Comment by MichaelKetting** [comment]
It should not since this only affects the test projects within the EntityFramework solution. The production projects remain on .NET 4.5.

**Comment by MichaelKetting** [comment]
.NET 4.6 is not fully supported yet: framework dnx46 can't be used at this time.

PR is closed until dnx46 is available. Note to self: also switch from Thread.CurrentCulture to CultureInfo.CurrentCulture when doing the switch.

**Comment by bricelam** [comment]
`dnx46` support is coming in aspnet/dnx#1929

**Comment by natemcmaster** [comment]
Can we reverse this? We can't run our build our test projects against mono (Linux/OSX) if we use `net46`.

**Comment by MichaelKetting** [comment]
The issue originally popped up when it came to using the correct culture in the tests. The actual fix was later done via the ReplaceCulture attribute in XUnit, IRC. No idea if the code actually/still has a requirement for .NET 4.6 to compile.
