### ISSUE TITLE
Adding EF nightly builds with NuGet 3 (VS2015) hangs after resolving dependency message

### ISSUE THREAD

**Issue by julielerman** [aspnet/EntityFramework#2209]
Hang at the following message when installing EF package

>Attempting to resolve dependencies for package 'entityframework.inmemory.7.0.0-beta5-13202' with DependencyBehavior 'Lowest'

This is a NuGet issue (https://github.com/NuGet/Home/issues/605) but we're leaving this issue open to provide workarounds and track the scenario on our end since it affects a lot of users.

## :star2: Workaround :star2: 

Download an updated version of NuGet for VS2015 RC http://nuget.codeplex.com/releases/view/615507.

## Details
Starting with ef.inmemory causes it to hang.
Starting with ef causes it to hang.
Starting with ef.core zips along with install until it hits IX-Async then it errors out.

IX-Async has often been the cause of nuget problems through EF7 releases.

I explicitly installed Ix-Async. Then tried to start my EF install with EF.InMemory but it hung again and my fan went wild again. :) 

I tried installing EF.core again. It ran quickly but then errored at installing system.runtime..I'll see if I can attach a txt file with the output.

I'm on windows 8.1 latest
VS2015RC

New project/solution.
I've had the same problem targetting .net 4.5.2 and .net 4.6.
Project is class library. 
Install-package entityframework.inmemory.

PM> install-package entityframework.inmemory -pre
Attempting to gather dependencies information for package 'entityframework.inmemory.7.0.0-beta5-13202' with respect to project targeting '.NETFramework, Version=v4.6'
Attempting to resolve dependencies for package 'entityframework.inmemory.7.0.0-beta5-13202' with DependencyBehavior 'Lowest'

I've tried many different times thinking that something is wrong with my system. I've let it run for an hour but with later tests I've given up after about  5 minutes. 

I've rebooted my machine before doing this to ensure nothing is lingering to affect the process.

I've tried this with just entityframework -pre
also with entityframework.sqlserver -pre

My battery fan goes crazy while this is going on.

I have to stop it by just closing VS. The cancel button on the console seems to have no effect.

I am not very experienced with using nuget from the commnad line but I did try it and got (a familiar) ix-async version issue. Could that be related to the problem? I would have expected to see this in the console.

D:\testing\ClassLibrary1>
nuget install entityframework.inmemory -pre -source "https://www.myget.org/F/aspnetvnext/api/v2"
Attempting to resolve dependency 'EntityFramework.Core (≥ 7.0.0-beta5-13202)'.
Attempting to resolve dependency 'Ix-Async (≥ 1.2.3)'.
Unable to resolve dependency 'Ix-Async (≥ 1.2.3)'.

**Comment by julielerman** [comment]
can't attach a file so here is the output of attempting to install ef.core from vnext package source with ix-async already installed (from nuget).

Each package is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 3.0.0.0

Type 'get-help NuGet' to see all available NuGet commands.

PM> install-package entityframework.core
install-package : Unable to find package 'entityframework.core'
At line:1 char:1
+ install-package entityframework.core
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM> install-package entityframework.core -pre
Attempting to gather dependencies information for package 'entityframework.core.7.0.0-beta5-13202' with respect to project targeting '.NETFramework, Version=v4.6'
Attempting to resolve dependencies for package 'entityframework.core.7.0.0-beta5-13202' with DependencyBehavior 'Lowest'
Resolving actions to install package 'entityframework.core.7.0.0-beta5-13202'
Resolved actions to install package 'entityframework.core.7.0.0-beta5-13202'
Adding package 'Microsoft.Framework.Caching.Abstractions 1.0.0-beta5-11363' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.Caching.Abstractions 1.0.0-beta5-11363' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.Caching.Abstractions 1.0.0-beta5-11363' to 'packages.config'
Successfully installed 'Microsoft.Framework.Caching.Abstractions 1.0.0-beta5-11363' to ClassLibrary2.
Adding package 'Microsoft.Framework.ConfigurationModel.Abstractions 1.0.0-beta5-11337' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.ConfigurationModel.Abstractions 1.0.0-beta5-11337' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.ConfigurationModel.Abstractions 1.0.0-beta5-11337' to 'packages.config'
Successfully installed 'Microsoft.Framework.ConfigurationModel.Abstractions 1.0.0-beta5-11337' to ClassLibrary2.
Adding package 'Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta5-11367' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta5-11367' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta5-11367' to 'packages.config'
Successfully installed 'Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta5-11367' to ClassLibrary2.
Adding package 'Microsoft.Framework.DependencyInjection 1.0.0-beta5-11367' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.DependencyInjection 1.0.0-beta5-11367' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.DependencyInjection 1.0.0-beta5-11367' to 'packages.config'
Successfully installed 'Microsoft.Framework.DependencyInjection 1.0.0-beta5-11367' to ClassLibrary2.
Adding package 'Microsoft.Framework.Logging.Abstractions 1.0.0-beta5-11361' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.Logging.Abstractions 1.0.0-beta5-11361' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.Logging.Abstractions 1.0.0-beta5-11361' to 'packages.config'
Successfully installed 'Microsoft.Framework.Logging.Abstractions 1.0.0-beta5-11361' to ClassLibrary2.
Adding package 'Microsoft.Framework.Logging 1.0.0-beta5-11361' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.Logging 1.0.0-beta5-11361' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.Logging 1.0.0-beta5-11361' to 'packages.config'
Successfully installed 'Microsoft.Framework.Logging 1.0.0-beta5-11361' to ClassLibrary2.
Adding package 'Microsoft.Framework.OptionsModel 1.0.0-beta5-11337' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.OptionsModel 1.0.0-beta5-11337' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.OptionsModel 1.0.0-beta5-11337' to 'packages.config'
Successfully installed 'Microsoft.Framework.OptionsModel 1.0.0-beta5-11337' to ClassLibrary2.
Adding package 'Microsoft.Framework.Caching.Memory 1.0.0-beta5-11363' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.Caching.Memory 1.0.0-beta5-11363' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Microsoft.Framework.Caching.Memory 1.0.0-beta5-11363' to 'packages.config'
Successfully installed 'Microsoft.Framework.Caching.Memory 1.0.0-beta5-11363' to ClassLibrary2.
Adding package 'Remotion.Linq 2.0.0-alpha-002' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Remotion.Linq 2.0.0-alpha-002' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'Remotion.Linq 2.0.0-alpha-002' to 'packages.config'
Successfully installed 'Remotion.Linq 2.0.0-alpha-002' to ClassLibrary2.
Adding package 'System.Collections.Immutable 1.1.34-rc' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'System.Collections.Immutable 1.1.34-rc' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'System.Collections.Immutable 1.1.34-rc' to 'packages.config'
Successfully installed 'System.Collections.Immutable 1.1.34-rc' to ClassLibrary2.
Adding package 'EntityFramework.Core 7.0.0-beta5-13202' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Added package 'EntityFramework.Core 7.0.0-beta5-13202' to folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Install failed. Rolling back...
Package 'EntityFramework.Core 7.0.0-beta5-13202' does not exist in project 'ClassLibrary2'
Removed package 'System.Collections.Immutable 1.1.34-rc' from 'packages.config'
Removed package 'Remotion.Linq 2.0.0-alpha-002' from 'packages.config'
Removed package 'Microsoft.Framework.Caching.Memory 1.0.0-beta5-11363' from 'packages.config'
Removed package 'Microsoft.Framework.OptionsModel 1.0.0-beta5-11337' from 'packages.config'
Removed package 'Microsoft.Framework.Logging 1.0.0-beta5-11361' from 'packages.config'
Removed package 'Microsoft.Framework.Logging.Abstractions 1.0.0-beta5-11361' from 'packages.config'
Removed package 'Microsoft.Framework.DependencyInjection 1.0.0-beta5-11367' from 'packages.config'
Removed package 'Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta5-11367' from 'packages.config'
Removed package 'Microsoft.Framework.ConfigurationModel.Abstractions 1.0.0-beta5-11337' from 'packages.config'
Removed package 'Microsoft.Framework.Caching.Abstractions 1.0.0-beta5-11363' from 'packages.config'
Removing package 'EntityFramework.Core 7.0.0-beta5-13202' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removed package 'EntityFramework.Core 7.0.0-beta5-13202' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removing package 'System.Collections.Immutable 1.1.34-rc' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removed package 'System.Collections.Immutable 1.1.34-rc' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removing package 'Remotion.Linq 2.0.0-alpha-002' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removed package 'Remotion.Linq 2.0.0-alpha-002' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removing package 'Microsoft.Framework.Caching.Memory 1.0.0-beta5-11363' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removed package 'Microsoft.Framework.Caching.Memory 1.0.0-beta5-11363' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removing package 'Microsoft.Framework.OptionsModel 1.0.0-beta5-11337' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removed package 'Microsoft.Framework.OptionsModel 1.0.0-beta5-11337' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removing package 'Microsoft.Framework.Logging 1.0.0-beta5-11361' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removed package 'Microsoft.Framework.Logging 1.0.0-beta5-11361' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removing package 'Microsoft.Framework.Logging.Abstractions 1.0.0-beta5-11361' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removed package 'Microsoft.Framework.Logging.Abstractions 1.0.0-beta5-11361' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removing package 'Microsoft.Framework.DependencyInjection 1.0.0-beta5-11367' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removed package 'Microsoft.Framework.DependencyInjection 1.0.0-beta5-11367' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removing package 'Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta5-11367' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removed package 'Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta5-11367' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removing package 'Microsoft.Framework.ConfigurationModel.Abstractions 1.0.0-beta5-11337' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removed package 'Microsoft.Framework.ConfigurationModel.Abstractions 1.0.0-beta5-11337' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removing package 'Microsoft.Framework.Caching.Abstractions 1.0.0-beta5-11363' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
Removed package 'Microsoft.Framework.Caching.Abstractions 1.0.0-beta5-11363' from folder 'D:\demos to toss\EF7 Add Test\ClassLibrary2\packages'
install-package : Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache.
At line:1 char:1
+ install-package entityframework.core -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM>

**Comment by julielerman** [comment]
(I just can't let it go...what can I say? :) )

Seem to have gotten 3202 installed. Here's how.
New solution/project (.net 4.6, class library)
Used UI since it's easier to find things when you are not sure what you want. :)

Installed ef.core -pre
It ran through but then complained about system.runtime
Installed system.runtime
tried ef.core again, this time it compalined about system.runtime,extensions
I installed that package
tried efcore again
install success!
There's always an error about System.Collections.Concurrent. @Maartenba recommended just deleting that when I showed him that problem at a conference earlier this week. So I literally just deleted it from references.
Then I installed ef.inmemory
It worked!

My (empty) solution compiles.
HTH

**Comment by ErikEJ** [comment]
@julielerman A fix is underway for this last System.Runtime issue

**Comment by julielerman** [comment]
thanks.
On the other issue that you started where I asked if this was the same problem, I was told to open an issue so am just relaying it all here. (don't ask me the hours invested ...)

Anyway FYI
more! :)
I added another project ..unit test so it needed EF.
I had to go through all of the install problems again to get it in.
EF.core depends on but does not pull in system.runtime, system.runtime.extensions and system.threading. I have to do these one at a time then retry core to find out about each one.

**Comment by rowanmiller** [comment]
@julielerman the ix-async and remotion.linq packages aren't on our nightly feed (since we don't build them) so can you make sure you have nugget.org in your package sources (NuGet will fall back to looking for them in other sources if they aren't in the active one).

As Erik mentioned the System.Runtime issue is known and fixed by https://github.com/aspnet/EntityFramework/pull/2207 (in the code base but hasn't made it onto the nightly build feed just yet).

If things are still hanging with those two items addressed then we likely have a NuGet issue that we need to look into.

**Comment by rowanmiller** [comment]
Added a workaround to the top of this issue. Note that the fix for the System.Runtime issue (https://github.com/aspnet/EntityFramework/pull/2207) has not yet made it to our nightly feed so using the workaround at the time I'm writing this will still fail.

**Comment by rowanmiller** [comment]
Leaving open as many folks are hitting this and it's critical to our experience... marking as blocked since it's a NuGet issue. Will close once we verify it is fixed in nightly NuGet builds.

**Comment by ErikEJ** [comment]
@rowanmiller  Where do we get NuGet updates for VS 2015 RC?

**Comment by rowanmiller** [comment]
Fix for https://github.com/aspnet/EntityFramework/issues/2152 has made it onto the nightly feed, so the workaround listed at the top of this issue will now successfully install the latest nightly builds.

**Comment by ErikEJ** [comment]
@rowanmiller  :clap: Works like a charm with the latest bits, which now includes #2152

**Comment by rowanmiller** [comment]
Simplified the workaround down to the shortest list of package installs that will avoid the hang.

**Comment by ErikEJ** [comment]
Had to downgrade Remotion-Linq, this should not be a problem now with the shorter list of packages

**Comment by ErikEJ** [comment]
@rowanmiller  Still broken, when running 

     Install-Package EntityFramework.Commands -Pre 

after installing the initial packages, VS hangs forever.

Do I need a NuGet daily, or is there a workaround?

**Comment by julielerman** [comment]
Confirming with v 13266. 

With the workaround:
ix-async
ef.core
ef.sqlserver installed fine.

But like Erik, with
ix-async
ef.core
ef.command failed (hung)

**Comment by ErikEJ** [comment]
Maybe something like this https://github.com/aspnet/EntityFramework/commit/44955eb7241b083f1c0c3f01d4579caa2d05531b is missing from the EF.Commands project.json ? @bricelam ?

**Comment by rowanmiller** [comment]
@julielerman @ErikEJ added workaround details to get commands installed. Seems to still be a complexity issue.

**Comment by rowanmiller** [comment]
Updated workaround with details of NuGet 3.0 RC2 that can be downloaded and used with VS2015 RC. I've tested that it resolves the issue.

**Comment by ErikEJ** [comment]
Thanks, Rowan, but I was unable to build at all with RC2!?

**Comment by ErikEJ** [comment]
@julielerman Now completely unblocked with NuGet 3.0 RC2 and latest myget build

**Comment by rowanmiller** [comment]
@ErikEJ sounds like the issues with building with RC2 are fixed now, can you confirm?

**Comment by ErikEJ** [comment]
@rowanmiller Yes, everything builds fine in VS 2015 RC updated with NuGet 3.0 RC2 (still some errors in command line build for some reason, though)

**Comment by jasonwilliams200OK** [comment]
Is this fixed and shipped with beta6 and VS2015 RTM? 
In which case should this be closed as resolved?

**Comment by rowanmiller** [comment]
@jasonwilliams200OK yes, this has shipped. Closing it out now.

**Comment by mmisztal1980** [comment]
PM> install-package entityframework.core -projectname MyLib.UnitTests -pre
Attempting to gather dependencies information for package 'entityframework.core.7.0.0-rc1-final' with respect to project 'Domain\Hive.Domain.UnitTests', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'entityframework.core.7.0.0-rc1-final' with DependencyBehavior 'Lowest'
Resolving actions to install package 'entityframework.core.7.0.0-rc1-final'
Resolved actions to install package 'entityframework.core.7.0.0-rc1-final'
Package 'Ix-Async.1.2.5' already exists in folder 'D:\Checkout\Hive\src\Hive.Core\packages'
Added package 'Ix-Async.1.2.5' to 'packages.config'
Successfully installed 'Ix-Async 1.2.5' to MyLib.UnitTests
Package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-final' already exists in folder 'D:\Checkout\Hive\src\Hive.Core\packages'
Added package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-final' to 'packages.config'
Successfully installed 'Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc1-final' to Hive.Domain.UnitTests
Package 'Microsoft.Extensions.DependencyInjection.1.0.0-rc1-final' already exists in folder 'D:\Checkout\Hive\src\Hive.Core\packages'
Added package 'Microsoft.Extensions.DependencyInjection.1.0.0-rc1-final' to 'packages.config'
Successfully installed 'Microsoft.Extensions.DependencyInjection 1.0.0-rc1-final' to Hive.Domain.UnitTests
Package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-final' already exists in folder 'D:\Checkout\Hive\src\Hive.Core\packages'
Added package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-final' to 'packages.config'
Successfully installed 'Microsoft.Extensions.Logging.Abstractions 1.0.0-rc1-final' to Hive.Domain.UnitTests
Package 'Microsoft.Extensions.Logging.1.0.0-rc1-final' already exists in folder 'D:\Checkout\Hive\src\Hive.Core\packages'
Install failed. Rolling back...
Package 'Microsoft.Extensions.Logging 1.0.0-rc1-final' does not exist in project 'Hive.Domain.UnitTests'
Removed package 'Microsoft.Extensions.Logging.Abstractions 1.0.0-rc1-final' from 'packages.config'
Removed package 'Microsoft.Extensions.DependencyInjection 1.0.0-rc1-final' from 'packages.config'
Removed package 'Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc1-final' from 'packages.config'
Removed package 'Ix-Async 1.2.5' from 'packages.config'
install-package : Failed to add reference to 'System.Collections.Concurrent'. Please make sure that it is in the Global Assembly Cache.
At line:1 char:1
+ install-package entityframework.core -projectname Hive.Domain.UnitTes ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 

@rowanmiller Trying to get EF1 rc1 installed - yields the above exception, any idea how to fix/work around this?

**Comment by ErikEJ** [comment]
@mmisztal1980 Remove all existing references incl packages.config entries, and re-add

**Comment by mmisztal1980** [comment]
@ErikEJ In the target project? or in the entire solution?

**Comment by ErikEJ** [comment]
@mmisztal1980 For each project in the solution...

**Comment by mmisztal1980** [comment]
Done, re-added EF.Core & EF.InMemory to 1st project, that went well, attempted to add EF.Core to 2nd project - it crashed again saying "failed to add reference to 'System.Collections.Concurrent' - again.

Is there anything else I can look at? What's causing this? I thought this was fixed?

Both projects are targeting .NET 4.6 and I'm using VS2015

**Comment by KirillShlenskiy** [comment]
Seeing the same problem. Unable to add EntityFramework.Core to second .NET 4.6 project in the solution.

**Comment by AsValeO** [comment]
The same as previous one.

**Comment by Dresel** [comment]
Had the same issue.

I added

    <package id="Microsoft.Extensions.Logging" version="1.0.0-rc1-final" targetFramework="net451" />

manually to the packages.config, clicked on restore.

After that I could install `EntityFramework.InMemory`.
