### ISSUE TITLE
Versioning of EF Test MyGet packages

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2252]
Great that those test packages are now available for easy comsumprion in for example providers. But there seems to be a issue with the versioning, as both packages have version 1.0.0.  It would be useful if they had the same version number as the "daily" build.

     EntityFramework.Core.FunctionalTests  v1.0.0

**Comment by bricelam** [comment]
Doh, good catch.

**Comment by ErikEJ** [comment]
:clap:
