### ISSUE TITLE
Commands: Design-time scenarios

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#2294]
We should think through all the different scenarios we want to support at design-time. This includes:
* Splitting things (services, config, contexts, models, migrations, etc.) into different projects
* Context constructor and Startup.ConfigureServices patterns (See #639)
* The concept of environments (e.g. Development, Production, etc.)

There are a lot of interacting parts here:
* The project on which the command is invoked
    * Migrations in this assembly
    * Contexts in this assembly
    * Contexts referenced by the migrations
* The startup project
    * Contexts in this assembly
    * Contexts registered in services
* The migrations assembly as configured by the context
    * Migrations in this assembly

A few other related bugs: #732, #2219, #2256, #2293

**Comment by bricelam** [comment]
A few related bugs: #732, #2219, #2256

**Comment by divega** [comment]
I think https://github.com/aspnet/EntityFramework/issues/2357 is also very related.

**Comment by bricelam** [comment]
...and #2553 and #2867... :smile: This is the "fix everything design-time related" bug.

**Comment by divega** [comment]
Good luck! :smile:

**Comment by bricelam** [comment]
See also the [September 17, 2015 Design Meeting Notes](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes-(September-17,-2015)#design-time-services).

**Comment by bricelam** [comment]
Closing; the remaining work is tracked by #639 & #2679.
