### ISSUE TITLE
Implement missing APIs from ChangeTacker/Entry

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#2295]
We do not have all APIs that we historically had available:
* GetModifiedProperties
* Reload
* etc.

**Comment by NullVoxPopuli** [comment]
:+1: I think I need Reload, too

**Comment by shobman** [comment]
+1 for Reload

**Comment by ajcvickers** [comment]
GetModifiedProperties issue resolved with commit above. Reload is being tracked by #1203
