### ISSUE TITLE
Error in TransactionsTest

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2304]
In test Query_uses_explicit_transaction - getting error due to unsupported isolation level: Result Message:	System.ArgumentException : The IsolationLevel value ReadUncommitted is invalid.

https://msdn.microsoft.com/en-us/library/system.data.sqlserverce.sqlcetransaction.isolationlevel(v=vs.100).aspx

What would be the best way to work around this?

**Comment by natemcmaster** [comment]
According to the link you posted, SQL CE should support ReadUncommitted. From where is ArgumentException being thrown?

**Comment by divega** [comment]
@natemcmaster it actually says just Read*Committed*, Serializable and ReadRepeatable. Whether the test needs to use it is another question.

**Comment by natemcmaster** [comment]
@divega Ah, good catch. 

@ErikEJ Either we need to skip the ReadUncommitted assertions for providers that do not support it, or you could just override this test method with your own implementation.

**Comment by ErikEJ** [comment]
@natemcmaster Thanks, but I do not think it is currently possible for me to override the method, or even skip it! Meaning I cannot run any on the TransactionsTests

**Comment by rowanmiller** [comment]
We'll just make these test virtual for the moment, we do want to look at a better design for our acceptance suite in the future.

**Comment by ErikEJ** [comment]
@rowanmiller great, did a PR already!
