### ISSUE TITLE
Cache FromSql based on parameter types instead of values

### ISSUE THREAD

**Issue by mikary** [aspnet/EntityFramework#2315]
The ```CompiledQueryCache``` adds a new entry for each unique set of argument values in the ```FromSql``` call. If we extract the parameters (SQL string and parameters object array) in query compilation and update the cache key to use the ```QueryAnnotation``` parameter types (using these parameters on SQL generation), the caching for ```FromSql``` will be more consistent with other query operations.

**Comment by rowanmiller** [comment]
@mikary any idea how much work this would be. Seems like it would be good to fix now if it's not a huge job.

**Comment by rowanmiller** [comment]
We should investigate the perf impact to help prioritize.

**Comment by mikary** [comment]
As a result of the deep comparison of parameters in the `ShaperCommandContext` `CommandCacheKey` `Equals` method, queries with calls `FromSql` appear to generate a new command on every call. As long as these commands have the same number and `Type`s of parameters, the command should be reusable.

This came up in our discussion on proposed changes for #3704 and #3115
@anpete @divega

**Comment by mikary** [comment]
In further discussion with @divega we noticed that null parameter values to `FromSql` are going to result in cache misses since the Type is lost when the vales are stored in an object array. We discussed a few different options and tradeoffs:

* Current implementation
  * Creates a new cache entry for each parameter value / object reference in param array
  * Always uses `RelationalTypeMapping.NullMapping` for null values
  * Always configures non parameters based on `RelationalTypeMapper` mappings
* Strict `Type` comparison
  * Creates a new cache entry for each parameter `Type` change in param array (i.e. change to null value)
    * Expected to have fewer entries, still can have 2^n permutations
  * Extra overhead of repeated `GetType()` calls / building `Type` info into cache key
* Loose `Type` comparison
  * Cache key with null param array values matches with / defaults to `string` mapping
    * Potentially has incorrect mappings for other `Nullable` types
* Late mapping
  * Cache entry only depends on number of elements in param array
  * Introduces `Dictionary` lookup / `RelationalTypeMapper` method calls to hot path
  * Mappings may be saved after the first non-null parameter value
    * Potentially has incorrect mappings if the parameter type changes (unlikely corner case)
* Untyped parameters
  * Cache entry only depends on number of elements in param array
  * Allow parameter definitions without type metadata, set the values and let ADO interpret the value
    * Similar to older versions of the way parameters are managed
