### ISSUE TITLE
Test issue with Query test: Select_local

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2317]
When running this test against the SQLCE provider, it fails. What is your suggested fix/workaround?

 Do I need to intercept Query generation? In that case, how would I do that (in broad terms) ?

System.Data.SqlServerCe.SqlCeException : A parameter is not allowed in this location.Ensure that the '@' sign is in a valid location or that parameters are valid at all in this SQL statement.

//Result StackTrace:	
//at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
//   at System.Data.SqlServerCe.SqlCeCommand.CompileQueryPlan()
//   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
//   at System.Data.SqlServerCe.SqlCeCommand.ExecuteDbDataReader(CommandBehavior behavior)
//   at System.Data.Common.DbCommand.ExecuteReader()
//   at Microsoft.Data.Entity.Relational.Query.QueryingEnumerable.Enumerator.MoveNext()
//   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
//   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
//   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
//   at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
//   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
//   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
//   at Microsoft.Data.Entity.FunctionalTests.QueryTestBase`1.AssertQuery[TItem](Func`2 query, Boolean assertOrder, Int32 entryCount)
//   at Microsoft.Data.Entity.FunctionalTests.QueryTestBase`1.Select_local()
//   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.QuerySqlCeTest.Select_local() in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\QuerySqlCeTest.cs:line 791
//Result Message:	System.Data.SqlServerCe.SqlCeException : A parameter is not allowed in this location.Ensure that the '@' sign is in a valid location or that parameters are valid at all in this SQL statement.

**Comment by divega** [comment]
@ErikEJ do you know SQL CE simply does not support `SELECT @something` or is it something else? The following thread seems to indicate that there might be a workaround:

http://stackoverflow.com/questions/9482012/why-does-convert-allow-me-to-use-parameterized-query-in-this-case

But you are the expert :smile:

**Comment by ErikEJ** [comment]
@diveaga thanks, I will do some digging, and follow up here. My impression is that the issue may be unability to support SELECT @something

**Comment by ErikEJ** [comment]
@divega - I think I got closer:

                    //Works:
                    //DbParameter param = command.CreateParameter();
                    //param.DbType = DbType.Int32;

                    //Breaks:
                    DbParameter param = command.CreateParameter();

                    //Common
                    param.ParameterName = "@__x_0";
                    param.Value = 10;
                    command.Parameters.Add(param);

So it is the missing setting of DbType that is causing the error, and I can see that the Microsoft.Data.Entity.Relational.Query.CommandBuilder currently does not set any Parameter DbType.

**Comment by ajcvickers** [comment]
@ErikEJ I am working on integrating the type mapping (which includes DbTypes) with query.

**Comment by ErikEJ** [comment]
@ajvickers Sounds great, had an impression something was missing, thanks!

**Comment by ErikEJ** [comment]
Fixed with the latest Typemapper changes

**Comment by divega** [comment]
Great to hear! Thanks.
