### ISSUE TITLE
Build in VS 2015 RC fails with latest source and NuGet 3.0 RC2

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2332]
Running build of EF7 in VS hangs with NuGet 3.0 RC2 installed. Reverting to 3.0 RC fixes the issue.

**Comment by ErikEJ** [comment]
Bad NuGet source config in VS!?

**Comment by bricelam** [comment]
We may need to exclude the project.json files...

**Comment by bricelam** [comment]
Excluding them didn't help. I'll disabled automatic restore in the NuGet.Config
