### ISSUE TITLE
Review autogenerated index names

### ISSUE THREAD

**Issue by HaoK** [aspnet/EntityFramework#2353]
Per @divega "FYI, Brice says that this comes from the entity type. But apparently we are not handling entity type names with generics very well." 

```
CREATE TABLE [dbo].[AspNetRoles] (
    [Id]               INT            IDENTITY (1, 1) NOT NULL,
    [ConcurrencyStamp] NVARCHAR (MAX) NULL,
    [Name]             NVARCHAR (256) NULL,
    [NormalizedName]   NVARCHAR (256) NULL,
    CONSTRAINT [PK_IntRole] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO
CREATE NONCLUSTERED INDEX [IX_IntRole_NormalizedName]
    ON [dbo].[AspNetRoles]([NormalizedName] ASC);
```

Generated from:

            builder.Entity<TRole>(b =>
                {
                    b.Key(r => r.Id);
                    b.Index(“NormalizedName”)

**Comment by smitpatel** [comment]
@HaoK - Which version of EF was showing the issue? There has been some work around this area to handle display names of generic types and indexes might have better autogenerated names now.

**Comment by smitpatel** [comment]
The latest code contains default index name creation as `IX_<entityType>_<properties>` in which generic entity type names are handled already. Closing this. If you are still seeing issues then please provide more detail on model.
