### ISSUE TITLE
NullReferenceException when using ternary expression in select

### ISSUE THREAD

**Issue by DragonMrak** [aspnet/EntityFramework#2364]
Hello,
I have db context like this:
``` C#
public class AppDbContext : DbContext
{
    //some tables skipped
    public DbSet<UnidentifiedActivity> UnidentifiedActivities { get; set; }
}
```
And with the following query:
``` C#
return ctx.UnidentifiedActivities
    .OrderBy(u => u.Read)
    .ThenBy(u => u.Received)
    .Skip(model.Skip)
    .Take(model.Take)
    .Select(u => new 
    { 
        u.id, 
        TitleCss = u.Read ? "read" : null, 
        u.Subject, 
        u.FromName, 
        u.FromAddress, 
        u.Received 
    });
```
I receive NullReferenceException at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.RelationalProjectionExpressionTreeVisitor.VisitExpression(Expression expression)

It doesn't help to change ternary expression to return non-null value, for example TitleCss = u.Read ? "read" : "unread" - still getting the same exception. However it helps to remove ternary expression altogether. Without ternary it works as expected.

**Comment by DragonMrak** [comment]
Almost forgot, I'm using 7.0.0-beta4

**Comment by maumar** [comment]
This no longer repros in the current bits
