### ISSUE TITLE
Perf: Test impact of facets on properties not reflected in query parameters that interact with those properties

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#2368]
Query is now integrated in type mapping such that the default type mappings for the CLR properties of types are used. So for example, we create a datetime2 parameter on SQL Server where needed and avoid the overflow issues with datetime parameters. In all the testing I have done it appears that everything is functional. However, there may be other reasons (such as perf) for taking facets of properties and applying them to parameters. For example, if a string property is mapped to an ANSI column, should a parameter comparing against that column be created differently? This issue is to investigate this and, if necessary, implement any changes.

**Comment by rowanmiller** [comment]
We can just be reactive if issue arise
