### ISSUE TITLE
Invalid SQL generated for multiple joins

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aspnet/EntityFramework#2372]
Here is the simplified version of what I am executing - i removed other tables and left only `Account`

    from a1 in c.Accounts
    from a2 in c.Accounts.Where(a2=>a2.Id == a1.Id)
    from a3 in c.Accounts.Where(a3 => a3.Id == a1.Id)
    where a1.Id == id
    select new { a1, a2, a3 }

The SQL generated is this

    SELECT TOP(1) [a1].[Id], [a2].[Id]
    FROM [account] AS [a1]
    CROSS JOIN [account] AS [a2]
    WHERE ([a2].[Pk] = [a1].[Pk]) AND ([a3].[Pk] = [a1].[Pk]) AND ([a1].[Pk] = @__8__locals1_pkAccount_0)

It is obviously invalid - a3 is included in WHERE clause but nowhere else.

I could have moved `WHERE` clauses to the linq where section but in the real life I would like to do LEFT JOINs like this (which worked fine in EF6)

    from a1 in c.Accounts
    from a2 in c.Accounts.Where(a2=>a2.Id == a1.Id).DefaultIfEmpty()
    from a3 in c.Accounts.Where(a3 => a3.Id == a1.Id).DefaultIfEmpty()
    where a1.Id == id
    select new { a1, a2, a3 }

This fails with an exception
    
    System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.

**Comment by maumar** [comment]
The first example works in current bits, producing the following TSQL

```
SELECT [a1].[Id], [a2].[Id], [a3].[Id]
FROM [Account] AS [a1]
CROSS JOIN [Account] AS [a2]
CROSS JOIN [Account] AS [a3]
WHERE (([a2].[Id] = [a1].[Id]) AND ([a3].[Id] = [a1].[Id])) AND ([a1].[Id] = @__id_0)',N'@__id_0 int',@__id_0=1
```

**Comment by maumar** [comment]
The second example also works, but produces very inefficient queries, basically the joins happen on the client. If you want to produce LEFT JOINs you can follow this pattern (GroupJoin + SelectMany + DefaultIfEmpty) recognized by EF:

```
                var query = from a1 in ctx.Accounts
                            join a2 in ctx.Accounts on a1.Id equals a2.Id into g1
                            from a2 in g1.DefaultIfEmpty()
                            select new { a1, a2, };
```

or in method syntax:

```
                var query = ctx.Accounts
                    .GroupJoin(
                        ctx.Accounts,
                        a1 => a1.Id,
                        a2 => a2.Id,
                        (a1, g1) => new { a1, g1 })
                    .SelectMany(
                        a2 => a2.g1.DefaultIfEmpty(),
                        (g, a2) => new { g.a1, a2 });
```

**Comment by MaximBalaganskiy** [comment]
what if i want to left join with an operator other than equals? is that still possible? and why such a regression? I would say lots of code will have troubles migrating to ef7 because of it.

**Comment by maumar** [comment]
@MaximBalaganskiy unfortunately EF7 only supports joins with equality, so the scenario you are describing is not possible at the moment. Upon initial release, EF7 is not intended to be a recommended upgrade for everyone who is using EF6 at the moment. Consider http://blogs.msdn.com/b/adonet/archive/2014/12/02/ef7-priorities-focus-and-initial-release.aspx for more context on that matter.

**Comment by maumar** [comment]
Filed an issue to introduce those join patterns to EF7:
https://github.com/aspnet/EntityFramework/issues/3263

**Comment by MaximBalaganskiy** [comment]
Wonderful, thanks for that.
