### ISSUE TITLE
i find a query bug

### ISSUE THREAD

**Issue by hiwjcn** [aspnet/EntityFramework#2373]
just a test:

```
int i=0;
List<user> list=db.Set<user>().Where(x=>x.user_email==i.ToString()).ToList();
```

When i pushed F5,i found this expression returns all data in database without exceptions.
and the email field dose not match the expression....

i do not know why......is it a bug?

**Comment by rowanmiller** [comment]
@hiwjcn do you see all data returned in the list, or just loaded from the database and then filtered out in memory?

**Comment by hiwjcn** [comment]
the params of where function is expression not func and where function returns a iqueryable not ienum......
so i think data is fitered in database not memory..

i think ef generate wrong sql....

i use mysql.
if ef work correctly,the sql should be select xxx from user where user_email ='0'
but ef ignore the 'x=>x.user_email==i.tostring()' expression.
so sql turns to be select xxx from user....without where.


forgive my poor english :)

**Comment by hiwjcn** [comment]
@rowanmiller  sorry to borther you,,,,my ef version is 6

**Comment by maumar** [comment]
@hiwjcn simple workaround would be to pass string directly to the predicate, like so:

```
string i='0';
List<user> list=db.Set<user>().Where(x=>x.user_email==i).ToList();
```

**Comment by hiwjcn** [comment]
@maumar  yeah i know how to use ef correctly,,but if ef can't recognize my expression,it should throw a exception not return a wrong data.

**Comment by maumar** [comment]
I'm having hard time reproing this issue in EF6. I tried the following code:

```
    public class User
    {
        public int Id { get; set; }
        public string user_email { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<User> Users { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                var u1 = new User { user_email = "0" };
                var u2 = new User { user_email = "0" };
                var u3 = new User { user_email = "1" };

                ctx.Users.AddRange(new[] { u1, u2, u3 });
                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                ctx.Database.Log = Console.WriteLine;
                int i = 0;
                List<User> list = ctx.Users.Where(x => x.user_email == i.ToString()).ToList();
                Console.WriteLine(list.Count);

            }
        }
    }
```

And it produces the following sql:

```
SELECT
    [Extent1].[Id] AS [Id],
    [Extent1].[user_email] AS [user_email]
    FROM [dbo].[Users] AS [Extent1]
    WHERE [Extent1].[user_email] =  CAST( @p__linq__0 AS nvarchar(max))


-- p__linq__0: '0' (Type = Int32, IsNullable = false)

-- Executing at 6/15/2015 1:58:12 PM -07:00

-- Completed in 3 ms with result: SqlDataReader
```

and produces the expected number of results - 2.

Could you provide a repro that causes the bug?

**Comment by maumar** [comment]
@hiwjcn  actually, i opened a bug in EF6 repository here:
https://entityframework.codeplex.com/workitem/2763#

**Comment by hiwjcn** [comment]
@maumar i posted some bug details on codeplex this morning...did you see that?
