### ISSUE TITLE
Migrations: Improve property layout to help with merge conflicts

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#2377]
See https://github.com/aspnet/EntityFramework/issues/2268#issuecomment-110951321

The way we are splitting up lines combined with every property having a `.Annotation("OriginalValueIndex"...` means that merging can non-trivial when two devs add a property to the same class.

**Comment by bricelam** [comment]
`OriginalValueIndex` (and other irrelevant annotations) were removed from the snapshot in #2186

**Comment by smitpatel** [comment]
We don't have irrelevant annotations included in snapshot now. And each property is written on separate line which makes merge fairly trivial when 2 different properties are added to same class. I tested out a sample and which looks easy to merge.
Closing this for now. We can revisit later if complex case arises.
