### ISSUE TITLE
Always use PRAGMA foreign_keys = ON; in the SQLite provider

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2380]
Otherwise no FK constraints will be enforced by the engine, despite them being present in the model.
https://www.sqlite.org/foreignkeys.html

**Comment by rowanmiller** [comment]
Already tracked by https://github.com/aspnet/Microsoft.Data.Sqlite/issues/62
We may do this in the EF provider or possible in our SQLite implementation of System.Data.Common.

**Comment by ErikEJ** [comment]
@rowanmiller I suggest doing it in the EF provider rather than the ado.net provider, as off is the default behaviour

**Comment by natemcmaster** [comment]
If we don't implement aspnet/Microsoft.Data.Sqlite#62, then I agree with @ErikEJ that we should add this into the EF layer.

**Comment by bricelam** [comment]
In triage, we did decide to do this at the EF (not the ADO.NET) layer.

**Comment by bricelam** [comment]
We should also enable people who want to shoot themselves in the foot turn it off.

**Comment by ErikEJ** [comment]
@bricelam  Of course!
