### ISSUE TITLE
Add test to check exception for Unsupported Data Types

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework#2385]
See #2379. 

SQL CE does not support the data types TimeSpan and DateTimeOffset. We should add a test that when a user creates a model with those types in it and attempts to use it that the expected exception is thrown.

More generally it would be good to have a test which allows any provider to override the expected results so that data types which are expected to pass for that provider pass and data types which are expected to error for that provider error in the expected way.

**Comment by rowanmiller** [comment]
@lajones we discussed in triage and concluded that providers should just include a test for the types they don't support (we already have this for our providers). Do you think there is something specific we need here?

**Comment by lajones** [comment]
Can you point me to the tests you mean when you say "we already have this for our providers"? The BuiltInDataTypes test tests that you can use supported data types but does not test what I mentioned above - that if you attempt to use an unsupported type the "right" kind of exception is thrown. Basically I want to make sure that the experience the customer gets if they include an "unsupported" data type is useful to that customer i.e. throws something or returns an error message that helps them identify what is wrong and how to fix it.

**Comment by ajcvickers** [comment]
@lajones @rowanmiller There currently aren't any tests that check that Strings.UnsupportedType is thrown. It would be trivial to add such a test. I think it only needs to be a unit test, and it only needs to test that the correct exception is thrown for one unsupported type.

**Comment by lajones** [comment]
I think it would be better to have a test that each provider overrides listing all the unsupported types and checking that they throw (just as we test every type that is supported). It would also be useful if we ever need to enumerate for people what types are not supported by the various providers. Anyway - hopefully yes it would be fairly easy either way.

**Comment by ajcvickers** [comment]
@lajones How do we determine the list of unsupported types? Do you mean unsupported "common" types for some definition of "common"? if so, what is that definition? In general there are an unbounded number of unsupported types and an application can try to use any of them. A provider should test that it works with any type that it supports. Any other type that is not recognized should cause an exception to be thrown. Testing that the correct exception is thrown for any type that is not recognized together with testing that any type that is supported works correctly seems to cover the test space. Otherwise we are picking a set of types that we think are somehow more important to test as unsupported than all the other unsupported types, and I don't see that that adds value.

**Comment by lajones** [comment]
@ajcvickers Yes - some definition of "common" TBD. In fact the BuiltInDataTypes test has become a test of "all C# built-in types plus some others that we think of as common". So that seems a good place to start. For instance if a provider chose not to support one of the C# built-in types I feel we should highlight that. There are also tests in that class that we support nullable versions of those types and Enums of certain integer types - to my mind those are valuable too and we should highlight it if a provider does not provide that support.

My own personal view would be that e.g. DateTime should definitely be in the "common" list even though it's not a C# built-in type. TimeSpan and DateTimeOffset (which were the original two that set off this discussion) I'm more on the fence about but on balance would probably include - and so highlight that SQL CE does not support them.

**Comment by ErikEJ** [comment]
FWIW, I already have exactly this type of test added to my implementation of the TypeMapper tests... It is a very simple 2 liner test
