### ISSUE TITLE
SQLite connections not properly closed

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#2397]
SqliteConnection is not being closed correctly.

Repro: repeatedly call this method using a context configured to use Sqlite. It should always return false, but will return true on occasion.

```c#
public bool Test_IsConnectionOpenAfterDispose()
{
	DbConnection connection;
	using(var context = new MyContext())
	{
		context.Hats.Add(new Hat { Color ="red"});
		context.SaveChanges();
		connection = context.Database.AsRelational().Connection.DbConnection;
	}
	
	return connection.State == ConnectionState.Open;
}
```

**Comment by bricelam** [comment]
Possibly due to Reactive-Extensions/Rx.NET#106?

**Comment by divega** [comment]
I believe Reactive-Extensions/Rx.NET#106 only affects async paths though.

**Comment by natemcmaster** [comment]
I believe this was fixed with https://github.com/aspnet/Microsoft.Data.Sqlite/pull/98. I have not been able to reproduce.
