### ISSUE TITLE
Have a way to turn off null semantics at the context level

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#2403]
(just extracting what is actionable from https://github.com/aspnet/EntityFramework/issues/2106)

E.g.:

DbContext.Database.AsRelational().UseDatabaseNullSemantics = true;

Note that this will have an impact on query caching, e.g. at query execution time we should generate different SQL based on the same source LINQ query depending on the state of this flag.

**Comment by ajcvickers** [comment]
@divega Should this be assigned to someone? Or should we triage it again? We have a note in the API review to make sure this gets done and that UseRelationalNullSemantics is then removed.

**Comment by divega** [comment]
@ajcvickers It should have been assigned to @maumar but somehow it got missed. Thanks!

**Comment by maumar** [comment]
I will deal with this as soon as I'm done with my current item

**Comment by maumar** [comment]
fixed in 0a0415e7c04caa1efedbb1d96b7b129ed9e64c3f
