### ISSUE TITLE
RevEng: Command option for adding codegen template into project

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#2415]
We want customers to be able to easily add a package to enable reverse engineering of specific database engine and at any point switch from the default code generation provided by that package to using a template that becomes part of their application and thereon they can customize. 

The idea came up in some brainstorming with @Eilon. He suggested that we could have an option, e.g. `--customize` for the reveng command line that will write the template file (originally stored as a resource in the assemblies of the package) into the project. Once the template is in the project the reverse engineering pipeline would know to use it. 

The templates will be provider specific, but the `--customize` option should work across different reverse engineering packages. We should decide whether the template should need to have a specific name and be put in a specific location in the package. Hopefully there will be a way to specify a custom name in the command line but we should have a default.  

cc @lajones

**Comment by lajones** [comment]
Fixed by https://github.com/aspnet/EntityFramework/pull/2598
Actual command dnx . ef revEng customize <provider_assembly_name>
