### ISSUE TITLE
RelationalTypeMapper: FK facet propagation

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#2455]
If the user specifies a store type for a principal key column that is different from the default creating a foreign key might result in a store error due to type mismatch.
This isn't too bad for explicit FKs, as the user can easily configure the store type, but for shadow state FKs and FKs found by convention it would be harder to figure out and would require more code to fix.
RelationalTypeMapper should get the store type from the principal key if it's not set on the foreign key.

**Comment by ajcvickers** [comment]
@AndriySvyryd Poaching this.
