### ISSUE TITLE
Relational: TPH inheritance mapping pattern

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#247]

**Comment by irperez** [comment]
+1 on the various mapping patterns (TPT, TPH, etc)  Please don't forget a mix of the two in a single graph.  Some objects may be TPT, or where one object via inheritance is mapped to 2 or more tables.

**Comment by kiide** [comment]
+1 for the inheritance support, at least one strategy.

**Comment by ErikEJ** [comment]
Please do NOT support mixing strategies...

**Comment by ilmax** [comment]
Please do not support inheritance OOB, can this be achieved in a separate package so to make pay for play real?

**Comment by kiide** [comment]
Since we do not support inheritance, what better alternative? I was thinking of creating a single class and put all the attributes in it, so work with a single table and a single class, simulating a strategy TPH

**Comment by irperez** [comment]
Without at least TPH, we cannot use EF. For simple applications, the above scenarios may be fine.  But for very complex scenarios especially in a world of medical applications (my company develops medical software for cancer regimens), we would not be able to handle such simple scenarios.

**Comment by rowanmiller** [comment]
@kiide & @irperez - This is just a limitation of the current pre-release versions of EF7. Pre-release are just designed for trying out EF7 so we definitely would not recommend using it to try and write real applications with.

**Comment by kiide** [comment]
Yes i uderstand

**Comment by phillip-haydon** [comment]
As part of EF 7, are you going to fix all the bugs that are currently in 6? Like mapping to the same foreign key for different relationships?

**Comment by rowanmiller** [comment]
Moving into 7.0.0 since we are in the process of enabling at least some scenarios at the moment.

**Comment by issafram** [comment]
For TPH, allow us to pick a custom Discriminator.  There should be no reason to store a string field for each row.  That is my biggest issue with TPH.

**Comment by anpete** [comment]
@issafram In EF7 you can pick any property for the discriminator.

**Comment by issafram** [comment]
@anpete will it support using enums for the discriminator?

**Comment by anpete** [comment]
@issafram Yes.

**Comment by weitzhandler** [comment]
Any workaround even temporary? Can's live with all subclasses being generated as separated tables.

Is there even a list to exclude base classes?

For instance I have TeacherBase and Teacher, and in fact don't want the TeacherBase at all as a table, I only need Teacher to be generated carrying all properties include the base class'.

**Comment by issafram** [comment]
@weitzhandler, did you try the `NotMapped` annotation?

Maybe you are asking for TPC (Table Per Concrete Type), but that can get confusing with foreign keys in other tables.

**Comment by weitzhandler** [comment]
I've opened a separate issue.
https://github.com/aspnet/EntityFramework/issues/2907

**Comment by divega** [comment]
@rowanmiller this item seems to represent the inheritance work as a whole and it is assigned to the 7.0.0 release. Should it have a priority and an owner or should we close it?

**Comment by rowanmiller** [comment]
Yep, changed title to reflect that we are implementing TPH for initial release (we have other issues on the backlog to track enabling other patterns).

Assigning to Andriy since he has the inheritance ball at the moment (for the model building work). We should keep this open until things work well end-to-end.

**Comment by leolana** [comment]
@ErikEJ because do NOT support mixing strategies...

**Comment by jimmymain** [comment]
how is TPC inheritance being tracked?
I have an existing project where each class within the hierarchy is mapped to a particular table.
I will move this model over to version 7 once it's implemented. Is this strategy also being tracked by this [issue](https://github.com/aspnet/EntityFramework/issues/247). The title does not make this clear.

**Comment by rowanmiller** [comment]
@jimmymain #2266 is actually for TPT, I opened #3170 to track TPC (they were originally all tracked by this issue, but then we split it out since we are only implementing TPH for the initial stable release)

**Comment by AndriySvyryd** [comment]
TPH is now fully implemented
