### ISSUE TITLE
Be consistent about Logger creation and management

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#2490]
We need to decide on when to create an ILogger from an ILoggerFactory and be consistent about it. For example, how granular should the ILogger be? What should its lifetime be? How should it be shared across classes, if at all? Exampels--should one be created per query? Per context? Per database?

As part of this we should also review usage of things like RelationalLoggerExtensions

**Comment by anpete** [comment]
Done for runtime.
