### ISSUE TITLE
Consolidate and rationalize SQL generation

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#2493]
Currently different parts of the stack do SQL generation in different ways. This may be fine since, for example, query and update have different mechanisms and requirements. However, we should make sure that we are using common code where it makes sense. If nothing else, code for escaping, etc. should be able to be shared. Related to this is that if a provider needs to customize how things like escaping are done, then the provider should only need to do this in one place.

**Comment by rowanmiller** [comment]
Make sure we API review IUpdateSqlGenerator et al before closing this

**Comment by rowanmiller** [comment]
This should be a very scoped refactoring just to ensure providers don't have to override escaping etc. in multiple places

**Comment by rowanmiller** [comment]
We are happy with what we have now
