### ISSUE TITLE
Create non-internal state entry interface for consuming by SaveChanges

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#2495]
When implementing SaveChanges, providers currently consume InternalEntityEntry objects. We should inside consider creating a simplified interface that is not internal and exposes only those things needed by providers to implement SaveChanges.

**Comment by anpete** [comment]
Are we OK with breaking this interface in the future?

**Comment by ajcvickers** [comment]
@anpete Yes. It falls into the category of being an interface that will almost certainly only be implemented for testing, and even that should be rare. @divega and @rowanmiller both agreed it would be okay to break it in the future.

**Comment by anpete** [comment]
:shipit:
