### ISSUE TITLE
Consolidate and rationalize SQL execution

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#2498]
Do these need to be shared between Update and Migrations?
Should ExecuteCommand use them?

**Comment by mikary** [comment]
Notes from #2758:
 - Cleanup in Query `DefaultQuerySqlGenerator`, renames based on new `RelationalCommandBuilder`
 - Look at removing `RelationalSqlExecutor` and moving `IRelationalConnection` into `SqlStatementExecutor` constructor dependencies
 - Use DI for `ParameterNameGeneratorFactory` in Query

**Comment by mikary** [comment]
completed and passed through API review
