### ISSUE TITLE
Migrations generate wrong order for DropForeignKey and DropPrimaryKey

### ISSUE THREAD

**Issue by andre-artus** [aspnet/EntityFramework#2509]
I changed the name of a column in a small database (on SQL Server 2014) I'm using to test EF7 and used "Add-Migration" to generate the code.

Running "Apply-Migration" I received the following error:

"The constraint 'PK_Address' is being referenced by table 'Meter', foreign key constraint 'FK_Meter_Address_AddressAddressId'"

Looking at the code that was generated I noticed that in the "Up" method the call to "DropPrimaryKey" came before the calls to "DropForeignKey".

    migration.DropPrimaryKey(name: "PK_Address", table: "Address");
    migration.DropForeignKey(name: "FK_Meter_Address_AddressAddressId", table: "Meter");
            
Dropping foreign keys before the primary key worked as expected.

IDE: VS 2015 RC
EF: 7.0.0-beta4
Project types: Console & Class Library
Windows 8.1

Not sure what other information may prove useful.

**Comment by andre-artus** [comment]
I would like to point out that the same is happening in the "Down" method.

**Comment by bricelam** [comment]
:smile: I fixed that *just* as you were filing the issue.

**Comment by andre-artus** [comment]
Was it an open issue already? I did a search in the issues prior to filing, did not see anything that seemed to fit the bill. Thanks for fixing it, where in the code was the issue?

**Comment by bricelam** [comment]
No issue; I found it while adding test coverage. It was an oversight in the [ModelDiffer.Sort()](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs#L24) method.
