### ISSUE TITLE
Decide whether mutable Metadata API should be consistent with readonly interfaces

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#2511]
We now have methods like IEntityType.GetProperties(), IEntityType.GetNavigations() and properties like EntityType.Properties, EntityType.Navigations

**Comment by rowanmiller** [comment]
By design, we discussed this in the API review :smile:

**Comment by rowanmiller** [comment]
Actually, just reviewed decisions and we were going to make the properties methods.

**Comment by rowanmiller** [comment]
The changes have been made, the properties are swapped to methods

**Comment by AndriySvyryd** [comment]
I don't see the changes

**Comment by rowanmiller** [comment]
@AndriySvyryd will be working on this API as part of perf changes
