### ISSUE TITLE
DefaultValuesTest "issue" with SQLCE provider

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2540]
I could only make this test work by implementing below "fix" - is there anything I could do/override to improve?   

                modelBuilder.Entity<KettleChips>()
                    .Property(e => e.BestBuyDate)
                    .StoreGeneratedPattern(StoreGeneratedPattern.Identity)
                    //.DefaultValue(new DateTime(2035, 9, 25));
                    .DefaultValueSql("'2035-09-25 00:00'");

This problem is that the default value date has too high precision with ".DefaultValue(new DateTime(2035, 9, 25))"

     CREATE TABLE [KettleChips] (
         [Id] int NOT NULL IDENTITY,
         [BestBuyDate] datetime NOT NULL DEFAULT '2035-09-25 00:00:00.0000000',
         [Name] nvarchar(4000),
        CONSTRAINT [PK_KettleChips] PRIMARY KEY ([Id])
    )

**Comment by ajcvickers** [comment]
@ErikEJ Is it just that SQL CE needs to be able to override how DateTime objects are written into the SQL? Is it possible to do this with the current code or is there some extensibility point we need to add?

**Comment by ErikEJ** [comment]
Yes, allowing SQLCE to control how the default is created would solve the issue.I have no idea if this can be done currently - but will look closer at the ddl pipeline to see if there is a hook for default values

**Comment by ErikEJ** [comment]
I think I already have the hook: https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/blob/master/src/Provider40/Migrations/SqlCeMigrationSqlGenerator.cs - thanks for making me think! :smile:
