### ISSUE TITLE
Sqlite Migration AutoIncrement wrong cast (string instead of boolean)

### ISSUE THREAD

**Issue by angelsix** [aspnet/EntityFramework#2545]
If you run ef migration add ... on an Sqlite backed model, it generates the cs file and adds:

                columns: table => new
                {
                    Id = table.Column(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
...

Where Annotation is the OperationBuilder<TOperation>'s Annotation function.

That functions parameter is a string, yet the underlying Operation.AddAnnotation wants an object that gets explicitly cast to a boolean in SqliteMigrationSqlGenerator at         public override void ColumnDefinition(string schema, string table, string name, string type, bool nullable, object defaultValue, string defaultExpression, IAnnotatable annotatable, IModel model, SqlBatchBuilder builder)

So this fails to cast. All the fix is needed is to add an overload or change the string parameter in OperationBuilder<TOperation>.Annotation to accept an object or boolean directly.

**Comment by bricelam** [comment]
Oops, looks like this was missed while doing 43e9ae89857859801325fab849d43e179232d3d3

**Comment by angelsix** [comment]
I cannot compile EF as ILogger seems to be missing from EntityFramework.Core so the sooner you can push a nightly build to https://www.myget.org/F/aspnetvnext/ that would be great and I can start using EF7 :)
