### ISSUE TITLE
[Migrations] Implement SqlOperation.SuppressTransaction

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#2558]
It's configured available in the API, but not actually implemented. 

We need this functionality to work to support certain SQLite migrations.

**Comment by bricelam** [comment]
@mikary may or may not already be looking in to this...

**Comment by mikary** [comment]
I did some digging around as a result of my work on #1863 (PR #2520) and noticed that we have two different ways of building commands (`CommandBuilder` and `SqlStatementExecutor`) and different batching systems for Migrations, Modification Commands, and Query. As far as I've seen, only Modification Commands respect the `MaxBatchSize` #2154. We also have a number of SQL generation patterns #2493 and from what I've seen of the factoring there is a lot of duplicated code.

While there isn't a specific issue tracking it, I would like to refactor/unify this code.

**Comment by natemcmaster** [comment]
As we discussed, for SQLite's purposed, it would be better to implement this to end the current transaction and begin a new one after the MigrationOperation executes. This will preserve ordering.

**Comment by mikary** [comment]
Removed transaction suppression in #2758, will need to begin looking at it in light of new consolidated command building.

**Comment by mikary** [comment]
Added transaction suppression in #4917
