### ISSUE TITLE
NuGet Commands: Tab-Expand -Provider Parameter

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#2570]
We should enable tab-expansion on the `Reverse-Engineer -Provider` parameter. Just the list of installed NuGet packages would be a good start. Something like this:

```ps1
Register-TabExpansion 'Reverse-Engineer' @{
    'Provider' = {
        Get-Package | select Id
    }
}
```

**Comment by lajones** [comment]
+1

**Comment by lajones** [comment]
I'll work on this.
