### ISSUE TITLE
Perf tests very slow running single a iteration on dnx451 and dnxcore50

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#2574]
When running tests locally we run a single iteration of the benchmark tests just to verify that they still work. In this mode we don't run the full set of iterations (typically 100) or record the results. Under net451 it takes ~40sec to run a single iteration of all tests in our suite. Under dnx451 or dnxcore50 it takes ~550sec.

Obviously we don't want to add 10min to `build.cmd` so there is currently code in `BenchmarkTestCaseDiscoverer` to skip tests on dnx. We need to investigate why it is slow and then re-enable when resolved.

**Comment by natemcmaster** [comment]
Perhaps related - Mono's perf on running tests is exceptionally bad. I compared just the raw execution time of our tests just to get a sense for how the platforms compare. Mono is 3x to 16x slower. (SqlServer is still running - hours later. I think it is hung on a migration test.)

https://gist.github.com/natemcmaster/e2eaa68a68f00a2693b1

**Comment by rowanmiller** [comment]
Confirmed that this is something in the test runner rather than the execution of the actual test code being slow. The timed test code takes the same amount of time to execute under both net46 and dnx451. The whole test run takes ~7x longer though.

**Comment by rowanmiller** [comment]
Root cause was `GC.GetTotalMemory(forceFullCollection: true)` being slow on DNX (opened https://github.com/aspnet/dnx/issues/2886).

Checked in a workaround on our end since we don't really care about metric collection when we just run a single iteration. The full perf runs against DNX continue to be affected, but it's less of a concern that they have the overhead since they run on a dedicated CI machine.
