### ISSUE TITLE
NotNull vs NotEmpty

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2581]
public virtual Task<IReadOnlyList<string>> ReverseEngineerAsync(
            [NotNull] string runtimeProviderAssemblyName,
            [NotNull] string connectionString,
            [NotNull] string rootNamespace,
            [NotNull] string projectDir,
            CancellationToken cancellationToken = default(CancellationToken))
        {
            *Check.NotNull(runtimeProviderAssemblyName, nameof(runtimeProviderAssemblyName));*
            Check.NotEmpty(connectionString, nameof(connectionString));
            Check.NotEmpty(rootNamespace, nameof(rootNamespace));
            Check.NotEmpty(projectDir, nameof(projectDir));

Why check.NotNull here, and not Check.NotEmpty?

**Comment by lajones** [comment]
Correct. Should be NotEmpty. Maybe a leftover from when we passed around the actual assembly rather than it's name.

**Comment by ErikEJ** [comment]
@lajones I am happy to do a PR - ??

**Comment by lajones** [comment]
@ErikEJ Don't worry. I'm working in that area right now. I'll just include it on my next check-in.

**Comment by lajones** [comment]
Fixed by #2598
