### ISSUE TITLE
Test infrastructure does not support test database schema changes

### ISSUE THREAD

**Issue by mikary** [aspnet/EntityFramework#2615]
When updating test models (in the GearsOfWar model for example) to support test cases, these changes are not detected or applied as a part of the test run, resulting in test failures on the CIs and individual developer instances. This results in test failures until the modified database is manually deleted.

Could be solved in a few different ways, i.e.
- Always drop EF databases before a test run
- Use Migrations in test infrastructure

**Comment by ajcvickers** [comment]
Fixed with database cleaner change.
