### ISSUE TITLE
Reverse Engineer: UWP Projects

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#2646]
The big issue we have to sort out here is how to get Razor into the project to use at design-time. One option is to redistribute it (and any of its dependencies that also won't install on `uwp10` projects) as part of the `EntityFramework7.Relational.Design` package.

**Comment by rowanmiller** [comment]
Discussed and concluded we'll only do this if folks ask for it. Targeting an existing database from UWP seems like a less common scenario (at least until we support targeting non-local storage).

**Comment by ErikEJ** [comment]
An opportunity for a third party Tool, perhaps?

**Comment by rowanmiller** [comment]
@ErikEJ could be, though I'm not sure how often you have an existing local SQLite database that you want to start accessing with EF.

**Comment by ErikEJ** [comment]
Yes, but I have tools already in place that lets you migrate from SQL Server to sqlite, so a possible RAD workflow if you want to resuse your SQL Server based schema could be:
SQL Server => SQLite db => EF7 codegen

**Comment by bricelam** [comment]
Re-opening for triage. After #3687, we're really close to having this. The rest of the work should be relatively cheap. If nothing else, this could be Backlog, up-for-grabs.

**Comment by bricelam** [comment]
This "works" (as much as it can). It could be made better by #6128, but I don't think there's anything else to do here.

**Comment by bricelam** [comment]
The workaround for when it doesn't work is to reverse engineer into a console app and copy the files to the UWP one.
