### ISSUE TITLE
The multi-part identifier "message.Text" could not be bound.

### ISSUE THREAD

**Issue by yongyi781** [aspnet/EntityFramework#2647]
The following query throws the error in the title.

    var query = from message in query
                where message.Text.Contains("hello")
                select message;
    query = query.OrderByDescending(m => m.Id).Take(50).OrderBy(m => m.Id);

Inspecting the SQL shows that the query generates a nested SQL query within a SQL query, and the outer SQL query incorrectly uses the name that is used for the object in the nested SQL instead of the outer query.

(ChatMessages is a table that contains a column named Text)

**Comment by maumar** [comment]
This issue is fixed in the latest bits, 
Beta6 generates the following (wrong) query:

```
SELECT [t0].[Id], [t0].[Text]
FROM (
    SELECT TOP(50) [message].[Id], [message].[Text]
    FROM [Message] AS [message]
    ORDER BY [message].[Id] DESC
) AS [t0]
WHERE [message].[Text] LIKE ('%' + 'hello' + '%')
ORDER BY [t0].[Id]
```

and in current bits we generate:
```
SELECT [t0].[Id], [t0].[Text]
FROM (
    SELECT TOP(50) [message].[Id], [message].[Text]
    FROM [Message] AS [message]
    WHERE [message].[Text] LIKE ('%' + 'hello' + '%')
    ORDER BY [message].[Id] DESC
) AS [t0]
ORDER BY [t0].[Id]
```
