### ISSUE TITLE
Commands: Microsoft.CodeAnalysis.CSharp missing on UWP

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#2661]
Repro:

1. Create new UWP (latest Win10 tooling) project
2. Open "project.json"
2. Add `"EntityFramework7.Commands" : "(latest version number)"` to the dependencies.
4. Verify the package has been installed by running the Nuget package manager console, `Get-Package -ProjectName {name}`
5. `Add-Migration` should be available, but instead it throws `The term 'Add-migration' is not recognized as the name of a cmdlet`

Commands on UWP are installed if the package is added via Nuget GUI or `Install-Package`

(There is probably not much we can do here except offer a workaround for users. This is a bug on UWP tooling.)

#1242

**Comment by natemcmaster** [comment]
**UPDATE**
Latest commands package does not work on UWP with the VS RTM released today.

"entityframework7.commands": "7.0.0-beta7-13800"

```
add-migration : Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Could not load file or assembly 'EntityFramework7.Commands' or one of its dependencies. The system cannot find the file specified."
```

**Comment by bricelam** [comment]
> Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Replacing `bin/Debug/Microsoft.CodeAnalysis.CSharp.dll` with the `net45` version makes it work.
