### ISSUE TITLE
Metadata: Prohibit mixed hierarchies

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#2671]
Assuming that the principal use case for entity type hierarchies is querying from the root CLR type (like using Set\<TEntity\>) then adding shadow entity types in the hierarchy or making its topology different from the corresponding CLR hierarchy doesn't add much value and could make the implementation unnecessarily complex.
Purely shadow hierarchies would still be valid.

**Comment by rowanmiller** [comment]
@AndriySvyryd is this needed now since we throw if we detect shadow entities at runtime for the moment?

**Comment by AndriySvyryd** [comment]
@rowanmiller This would be a fail-early exception that will be thrown from the place the user needs to make the fix.

**Comment by rowanmiller** [comment]
Discussed and it sounds like doing this results in less work to do now
