### ISSUE TITLE
DNX Commands: Make ef a global command (enables --starupProject)

### ISSUE THREAD

**Issue by davidfowl** [aspnet/EntityFramework#2679]
Today users need to run `dnx . ef`, it would be better if they could just run a global command on any project without having to do project modification. To do this properly we'd need to have a way to load a runtime environment to harvest information for loading EF things.

/cc @anurse

**Comment by bricelam** [comment]
Exactly, it executes in the context of your project. I tried going down this path, but things got ugly fast. xUnit.net also tried to do it, but it doesn't work at all since it never loads the "target" project.

**Comment by anurse** [comment]
Yeah, this would probably be best tracked via an issue in DNX to enable global commands to operate in project context.

**Comment by rowanmiller** [comment]
Closing as there is nothing actionable from the EF side at the moment. If the design of global commands changes such that the EF commands could make use of them then we will reconsider.

**Comment by bricelam** [comment]
Re-opening. We need this to properly enable `--startupProject`

**Comment by bricelam** [comment]
Another (easier to implement) option would be to always invoke this on the startup project and have a `--targetProject` option that points to the project with the `DbContext` (actually `Migration`s).

**Comment by totht91** [comment]
I have a workaround for the "migration not working if dbcontext is in another project" 
* Create a Startup.cs class in the class library project's root.
* Add the following content:
```C#
/// <summary>
/// We need a Startup class in this class library,
/// because the ef command line migration tool cannot work,
/// if the DbContext is in a different startup project
/// </summary>
public class Startup
{
    public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
    {
        // link the original startup project's root for the config.json
        var builder = new ConfigurationBuilder()
            .SetBasePath(appEnv.ApplicationBasePath + "/../MyApp.Web") 
            .AddJsonFile("config.json")
            .AddJsonFile($"config.{env.EnvironmentName}.json", optional: true);

        builder.AddEnvironmentVariables();
        Configuration = builder.Build();
    }

    public IConfigurationRoot Configuration { get; set; }

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddEntityFramework()
            .AddSqlServer()
            .AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
    }
}
```
* Add ef commands to the class library's project.json
```json
"commands": {
    "ef": "EntityFramework.Commands"
  }
```
* Run the ef commands from the Class library's root

**Comment by francischeung** [comment]
It looks like --startupProject has been replaced by --targetProject. Is this correct?
If so, is this available in beta8 or should I expect it in RC?

**Comment by bricelam** [comment]
@francischeung Yes, we ended up implementing [my alternative proposal](https://github.com/aspnet/EntityFramework/issues/2679#issuecomment-147862824). It is available in RC 1.

**Comment by justsayno** [comment]
How do you then access the default connection string from the override of OnConfiguring required to set up the data source. IE:

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data:DefaultConnection:ConnectionString");
            base.OnConfiguring(optionsBuilder);
        }
```

With my default connection string being in the MVC app and this code being in the DbContext class library.

**Comment by divega** [comment]
@justsayno the recommended pattern in ASP.NET applications is to configure the DbContext on `Startup.ConfigureServices()`, e.g. like one of the snippets above:

``` C#
public void ConfigureServices(IServiceCollection services)
{
    services.AddEntityFramework()
        .AddSqlServer()
        .AddDbContext<ApplicationDbContext>(options => 
            options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));
}
```
But if for some reason you need to do this in the OnConfiguring() method on the context itself, you are going to need to make the configuration available outside of Startup. The simplest way I know you can do that is by making sure the `Startup.Configuration` property is static, e.g.:

``` C#
public static IConfigurationRoot Configuration { get; set; }
```
Functionally there isn't any significant difference between configuring the DbContext in `Startup` or in `OnConfiguring()`.

**Comment by justsayno** [comment]
@divega Thank you!

**Comment by fe-rod** [comment]
@divega I understand that the recommended pattern is to configure DbContext in the Startup.ConfigureServices method, but that forces me to add a dependency between the web project and the data access layer where the DbContext lives. I prefer the web app to know nothing about the DbContext. Or I might be thinking something wrong.

I think @justsayno was dealing with the same thing. The static option for Configuration would make the dependency the other way around, am I right?

**Comment by bogdandanielb** [comment]
Is there any solution yet to decouple the data persistence from the presentation ?
It seems the Startup.cs is only used in the web project and not in the class library. Basically we should be able to add all EF7 related dependencies in project.json from our class library and do EF setup in the library as well:

```
            services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]))
                .AddDbContext<SkillContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));
```

**Comment by rowanmiller** [comment]
@bogdandanielb you don't have to wire things up in Startup.cs if you don't want to. You can absolutely just define a DbContext in a class library, setup the connection string etc. there (typically by overriding `OnConfiguring`), and then just create instances in whatever app happens to want to consume the context.

**Comment by bogdandanielb** [comment]
@rowanmiller That is correct but I won't be able to benefit from the dependency injection which is set in the ConfigureServices method from Startup.
Thanks for your answer.

**Comment by DevNeeraj** [comment]
@bricelam 

> I have tried many things but still unable to find **RevEng** command under the **ef**.

In a project, i am using

```
 "commands": {
        "web": "Microsoft.AspNet.Server.Kestrel",
        "ef": "EntityFramework.Commands"
    }
```
and
```
 "dependencies": {
        "EntityFramework.Commands": "7.0.0-rc1-final",
        "EntityFramework.Core": "7.0.0-rc1-final",
        "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
        "EntityFramework.MicrosoftSqlServer.Design": "7.0.0-rc1-final",
        "EntityFramework.Relational.Design": "7.0.0-rc1-final",        
}
```

> So how can i enable **RevEng** command in dnx, 
> Help me to out !

**Comment by bricelam** [comment]
@DevNeeraj, it's `dbcontext scaffold`
