### ISSUE TITLE
Failure adding NuGet ref to EF.Relational.FunctionalTests from release branch 

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2680]
Using EntityFramework.Relational.FunctionalTests.7.0.0-beta6-13815 from the MyGet release feed at https://www.myget.org/gallery/aspnetrelease with Visual Studio 2015 RTM on brand new VM.
Getting error when adding to test project targeting .NET 4.6:

    Failed to add reference to 'System.Collections.Concurrent'

(Can add EF.Relational reference to Projects targeting .NET 4.5)

This is blocking me from being able to build a beta 6 release of the SQLCE EF provider (well, I can build the product DLLs, but not run any tests :-1:

**Comment by ErikEJ** [comment]
Possibly related to https://github.com/aspnet/EntityFramework/issues/2457 (but I am using a RTM Azure image)

**Comment by ErikEJ** [comment]
Removing the project reference to the product DLL temporarily solved the issue

**Comment by bricelam** [comment]
Yeah, I saw something similar. I need to dig into it; I think one of our dependencies is violating aspnet/dnx#2031.

**Comment by rowanmiller** [comment]
@ErikEJ anything outstanding from your side here?

**Comment by ErikEJ** [comment]
Yes, as it makes upgrading based on daily builds very cumbersome, error prone and time consuming

**Comment by bricelam** [comment]
Found it. This is an issue with the [Microsoft.Framework.Logging package](https://github.com/aspnet/Logging/blob/release/src/Microsoft.Framework.Logging/project.json#L20).

**Comment by ErikEJ** [comment]
:smile:  Fixed now, thanks a lot!
