### ISSUE TITLE
Migrations revert in the wrong order when going to "0"

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#2695]
Apply-Migration 0 unapplies in the wrong order. It starts with the oldest migration. The first should be last and the last should be first.

**Comment by bricelam** [comment]
Looks like I missed a call to `.OrderByDescending(m => m.Id)` on [line 131 of Migrator.cs](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Migrations/Migrator.cs#L131).
