### ISSUE TITLE
Async query fails on Mono 4.0.x (OS X/Linux)

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#2708]
Async queries will fail on Mono 4.0.x. The Mono implementation of LINQ will throw this error:

>    System.InvalidOperationException : The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IEntityQueryProvider can be used for Entity Framework asynchronous operations.

This will be resolved in a future Mono release. Currently their [4.2.0 branch](https://github.com/mono/mono/tree/mono-4.2.0-pre2-branch) contains the fix, but this is pre-release.

(No changes required in EF. Adding this issue just to track the upgrade of Mono)

**Update**

Preview [packages are available](http://www.mono-project.com/download/).

[Draft release notes for 4.2.0](http://www.mono-project.com/docs/about-mono/releases/4.2.0/)

**Comment by divega** [comment]
This is a bit off-topic, but the exception message seems weird, e.g. is the requirement to implement IAsyncQueryProvider to IEntityQueryProvider?

cc @anpete

**Comment by natemcmaster** [comment]
A preview package for 4.2.0 is available for OS X. See this post: [Mono for El Capitan (OS X 10.11) preview package now available](http://mono.1490590.n4.nabble.com/Mono-for-El-Capitan-OS-X-10-11-preview-package-now-available-td4666401.html).

Note that there are breaking changes on OSX due to El Capitan's new feature that restricts access to `/usr/`. Read the post for details.

**Comment by natemcmaster** [comment]
Mono 4.2.0 has been published. 

[Release notes](http://www.mono-project.com/docs/about-mono/releases/4.2.0/)
Note that [this replaces `System.Linq`](http://www.mono-project.com/docs/about-mono/releases/4.2.0/#linq) with a Microsoft's implementation

**Comment by divega** [comment]
Cool! In the release notes it says System.Data is also replaced with a Microsoft's implementation. Do you know if that means we are getting more compatibility? 

E.g. are `Precision` and `Scale` now in `DbParameter`? Does `GetFieldValue<T>()` works for their SqlClient?

**Comment by natemcmaster** [comment]
The version of `System.Data` in Mono 4.2.0 is compiled from [these files](https://github.com/mono/mono/blob/mono-4.2.0-branch/mcs/class/System.Data/referencesource.sources), which includes Microsoft's [`System.Data.Common.DbParameter`](https://github.com/Microsoft/referencesource/blob/master/System.Data/System/Data/Common/DBParameter.cs).

`GetFieldValue<T>` is still not implemented.

**Comment by natemcmaster** [comment]
...so yes, `SqlParameter` on Mono has `.Precision` and `.Scale`

**Comment by divega** [comment]
Thanks!
