### ISSUE TITLE
NotMappedAttribute still not work for complex type property in beta5

### ISSUE THREAD

**Issue by heavenwing** [aspnet/EntityFramework#2727]
I have below code:
```
class Enterprise
{
    ...
    [NotMapped]
    public EnterpriseReceiptInfo ReceiptInfo { get; set; }
    ...
}
```
EnterpriseReceiptInfo is a complex type, and when ef create database model, it throw a exception to tell me that EnterpriseReceiptInfo must have a Key.
So, I add meta via fluent api in DbContext
```
modelBuilder.Entity<Enterprise>().Ignore(t => t.ReceiptInfo);
```
That is work.

**Comment by rowanmiller** [comment]
@smitpatel Hey mate, this isn't in beta 5, is it. Should it work in current builds?

**Comment by smitpatel** [comment]
NotMappedAttribute is not available in public bits yet. It was added after beta6 release. It should work in latest nightly build.

**Comment by rowanmiller** [comment]
@smitpatel feel free to close if you are confident this scenario now works
