### ISSUE TITLE
RevEng :: reverse engineering a table with column of type float is incorrect - querying the resulting DbSet throws InvalidCastException

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#2740]
Problem is that we reverse engineer column of type "float" to CLR float, however when we query that table, the values of that column are of CLR type double. 

Due to the way we materialize entities (use GetValue(i) on a reader, and cast the result to appropriate type, then assign to a relevant property in the entity), we are getting invalid cast exceptions for this scenario.

Fix would be to correctly reverse engineer "float" columns into properties of CLR type "double".

We should also make sure that there are no other type that exhibit this behavior.

**Comment by lajones** [comment]
See http://entityframework.codeplex.com/SourceControl/latest#src/EntityFramework.SqlServer/Resources/System/Data/SqlClient/System.Data.Resources.SqlClient.SqlProviderServices.ProviderManifest.xml. Looking at EF6 - looks like we used SQL(float) -> CLR(double) and SQL(real) -> CLR(float). 

Note also we are missing rowversion.

**Comment by lajones** [comment]
Fixed by PR https://github.com/aspnet/EntityFramework/pull/2743
