### ISSUE TITLE
Review exception messages to ensure we don't show any instance data

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#2752]

**Comment by mikary** [comment]
- [ ] Review Strings.resx
 - [ ] Commands
 - [ ] Core
 - [ ] InMemory
 - [ ] Microsoft.SqlServer
 - [ ] Microsoft.SqlServer.Design
 - [ ] Relational
 - [ ] Relational.Design
 - [ ] Sqlite
 - [ ] Sqlite.Design
- [ ] Locate raw string messages

**Comment by mikary** [comment]
Exceptions requiring modification
  - ExpressionParameterizationException - passes expression tree that may contain parameter instance data

**Comment by mikary** [comment]
Error messages not in resx file
  - [x] ExpressionPrinter.VisitUnary
  - [x] ExpressionPrinter.UnhandledExpressionType
  - [x] ExpressionPrinter.UnhandledOperation
  - [x] ModificationCommand.AddEntry
  - [x] CommandLogger.Log

**Comment by mikary** [comment]
cc @blowdart here is the issue for reviewing exception messages that I mentioned the other day.

**Comment by mikary** [comment]
Reviewed and removed instance data and connection strings from error messages.

Note: Instance data is referenced in `DbUpdateException` exception object, but not included in the message. Consuming code is expected to intercept these exceptions if the data is not to be accessible.
