### ISSUE TITLE
PropertyAttributeConvention does not apply to non-public properties 

### ISSUE THREAD

**Issue by anfomin** [aspnet/EntityFramework#2766]
Both `PropertyAttributeConvention <T>` and `NavigationAttributeConvention<T>` does not apply to protected and private properties. They use method `Type.GetProperty(name)` to get CLR property which always returns `null` for non-public ones.

**Comment by rowanmiller** [comment]
@smitpatel we don't map privates by default, but we should respect annotations on them once they are included
