### ISSUE TITLE
Decide whether to revert relationship API changes

### ISSUE THREAD

**Issue by rustd** [aspnet/EntityFramework#2775]
These names are very confusing. This is what we have in Identity https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity.EntityFramework/IdentityDbContext.cs#L56

We used to *WithOne() in EF6 which was better

**Comment by rowanmiller** [comment]
Given the direction we have headed with other APIs we should consider reverting back to old API names (or similar to what we had).

**Comment by jarrettv** [comment]
I think the new naming is a step in the right direction. Anything will be better than the confusing primary dependent situation in EF6. :)

**Comment by rowanmiller** [comment]
We discussed and came up with something that closer resembles EF6 but avoids the principal/dependent mess. Here is the work item tracking the changes https://github.com/aspnet/EntityFramework/issues/3071
