### ISSUE TITLE
Relational: Add a validation rule to ensure unique column names

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#2813]
This convention would run after the model is built and set unique column names for all the properties with default mapping that conflict with another column name.

**Comment by rowanmiller** [comment]
@AndriySvyryd are there cases where this errors at the moment? In inheritance it is probably desirable to use the same column if children have the same property name (and the same type). Having to rename explicitly when they are a different type would be fine (possibly error in the validator).

**Comment by AndriySvyryd** [comment]
@rowanmiller This is needed even without inheritance. Consider
```
private class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
}

modelBuilder.Entity<Product>().Property(b => b.Name).HasColumnName("Id");
```
And yes, a validation rule would be needed also to check the explicit configuration.

**Comment by rowanmiller** [comment]
We discussed that scenario in triage and agreed you should have to manually give us a name for Blog.Id too (the model should be invalid)

**Comment by AndriySvyryd** [comment]
Then a validation rule would be enough. We can revisit this if we ever allow mapping several properties to the same column.

**Comment by rowanmiller** [comment]
:+1:
