### ISSUE TITLE
Disable Caching

### ISSUE THREAD

**Issue by leus** [aspnet/EntityFramework#2826]
I'm currently facing an issue (as explained in [this stackoverflow question](http://stackoverflow.com/questions/31953837/cached-results-in-linq-query)) that I suspect may be related to caching.

What is the right way to disable caching for a specific query in EF7?

**Comment by anpete** [comment]
Confirmed a bug in query parameter extraction. Fix on the way.

Thanks for reporting.

**Comment by leus** [comment]
Nice to know. Any hint on how to disable cache (or if that would help)? 

Is there anything I can do to help?
