### ISSUE TITLE
DataAnnotations - Decide when to throw or ignore on various errors

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#2829]
At present we have 2 different behavior in system on how to deal with erroneous DataAnnotations. Sometimes we throw exception and sometimes we log error (presently marked as todo since we don't have logger fully implemented yet).

In following cases we are throwing exception:
- `Timestamp` applied to non-byte array type.
- `Key` applied to multiple properties and key has not been set using fluent API. We do not allow Composite PK with annotation due to ordering.
- `InverseProperty` throws if the inverse property does not exist or of wrong type or self-reference.

In follow cases we are logging error:
- `InverseProperty` attributes present on both navigation and do not points to each other.
- `ForeignKey` on property on both the entityType. Ambiguous to determine the principal end.
- `ForeignKey` is on both navigations or navigation and property and the values do not match.
- `ForeignKey` is on multiple properties (possibly composite FK)
- `ForeignKey` value is invalid property list.
- `Key` in derived type

We should review above and aim for consistency or best user experience while using data annotation.

**Comment by rowanmiller** [comment]
@smitpatel please bring to design meeting (we should use EF6 behavior to help drive decisions)

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes--August-20,-2015#error-handling-in-data-annotations

**Comment by roji** [comment]
Do the notes above refer also to annotation error handling in *providers*, as opposed to the EF7 core? I mean, if an invalid model is given to the provider (in the sense that it includes annotations that aren't supported), shouldn't this trigger exceptions rather than log messages?

**Comment by smitpatel** [comment]
@roji - Above notes referring to data annotation (aka custom attributes) written on entity type/property to configure model.
Data annotations are applied to the model as conventions, which runs at the time of building model. Since there can be errors in user-specified data annotations, conventions should throw/log based on the error. Above notes specify behavior in case of various errors. As of now all attribute conventions are in core (except `Table` and `Column` which are in relational) so providers do not require to do any error handling for data annotations.

For the question of invalid model given to the provider
Data annotation is alternate of fluent API to provide model configuration. All the data annotations can be expressed using fluent API. And they both modify metadata of model. So the same invalid model can be constructed without using data annotations.
Therefore check for invalid model should be done in model validator which runs once the model is fully built. Core contains base `ModelValidator`. There is `RelationalModelValidator` also deriving from core one to apply rules specific to relational only. In the same way provider can implement own model validator (possibly deriving from one of the above) if certain kind of model is invalid for the specific provider. Then its upto provider to trigger exceptions or log messages.
Ref: https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Internal/RelationalModelValidator.cs

**Comment by roji** [comment]
@smitpatel - thanks for the info, I wasn't aware of `ModelValidator`/`RelationalModelValidator`!

And yes, my question was also in general about providers validating models, regardless of whether the models were built using the fluent API or annotations.
