### ISSUE TITLE
Push Migrations use down into RelationalDatabaseCreator

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#2835]
Both the SQLite and SQL Server providers have almost identical code to create the database using Migrations components. We should push this down into the `RelationalDatabaseCreator` class.

**Comment by ErikEJ** [comment]
Would be great if you could take the SQLCE implementation into consideration also: https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/blob/master/src/Provider40/SqlCeDatabaseCreator.cs

**Comment by bricelam** [comment]
Fun Fact: This issue is debt from #556.
