### ISSUE TITLE
RevEng: Keys/AlternateKeys/Indexes

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework#2840]
What code should be generated from a unique constraint which is not the primary key - probably AlternateKey()?

Consider what code should be generated when a foreign key points to such a key in the database.

Should we add fluent API to name the constraint underlying a given foreign key / alternate key / primary key on the database - so that if we regenerated the database using migrations it would use the same names.

Do we need to add a .Index() in order to have access to the Name?

**Comment by smitpatel** [comment]
In model snapshot, keys are declared as follows:
- If primary key then use `Key()`
- If referenced by FK then use `PrincipalKey()` on relationshipbuilder.
- Otherwise use `AlternateKey()`

**Comment by rowanmiller** [comment]
Those rules sound pretty good for reverse engineer too.

**Comment by natemcmaster** [comment]
We need to verify that we are correctly matching the unique index/unique constraint behavior of SQL Server. (See https://technet.microsoft.com/en-us/library/aa224827%28v=sql.80%29.aspx?f=255&MSPPError=-2147217396)

**Comment by lajones** [comment]
Have updated to no longer output HasAlternateKey() fluent API in PR #3519.

**Comment by lajones** [comment]
@rowanmiller @divega @ajcvickers @natemcmaster Re discussion from meeting on 10/21/15.

- Are we saying we want to output the `HasIndex(propertyNames).HasName(indexName).IsUnique(true|false)` into the fluent API in the generated `DbContext`?
- For which indexes do we want to do that? Those whose properties do not match either the primary key or any foreign key on the table? Does it matter if the order of the properties specified in the index is different from the order specified in the PK / FK?
- IIRC we removed the matching `Index` DataAnnotation - so we can't output that if the user wants to use attributes, right?

**Comment by natemcmaster** [comment]
IMHO:

**non-unique indexes**
We should always scaffold `HasIndex()`.

**unique indexes**
Scaffold as `HasIndex().IsUnique()` unless it is already in scaffolded as a key (currently only possible via .PrincipalKey()).

**`[Index]`**
Match our current data annotation conventions. (@smitpatel how do we handle IndexAttribute?)

**Comment by ajcvickers** [comment]
@natemcmaster And index on the dependent properties of a unique (1:1) FK should not need an explicit Index scaffolded either, although this depends on some work that may not have been done yet in the model building API.

Also, we do not support IndexAttribute at all in EF7.

**Comment by natemcmaster** [comment]
@ajcvickers good point. Yes, we wouldn't need it then either. I don't know how complicated that would be to implement. If user-code has a redundant `.HasIndex()`, is this harmful to the runtime Model?

**Comment by ajcvickers** [comment]
It's not harmful to have redundant indexes, no.

Also, the property order does matter. Two indexes over the same properties but in a different order are different indexes.

So basically, if the properties of an index match the properties of a key or FK in the same order, and the explict or implied uniqueness matches, then we should not need to scaffold an explicit index because one will be created by convention.

**Comment by divega** [comment]
> It's not harmful to have redundant indexes, no.

Do we avoid generating redundant indexes on the database? Redundant indexes on the databse affect performance.

**Comment by smitpatel** [comment]
For 2nd question & Arthur's earlier comment look at #700 . Indexes for Key/ForeignKey will have explicit index object in the model so they are not required to scaffold separately.

**Comment by divega** [comment]
Re my previous comment, of course that only matters if you are using scaffolding to take control of the database schema, but I think we should have generating a clean model as a goal.

**Comment by lajones** [comment]
Thinking on this some more. If we want the model to be as "round-trippable" as possible, we will need to specify at least the index's name for all indexes. The name we would otherwise generate through migrations is not likely to be the same as it depends on whatever tool the DBA used to create the index in the first place.

**Comment by rowanmiller** [comment]
Agreed

**Comment by lajones** [comment]
Fixed HasIndex() issue with PR #3579.
