### ISSUE TITLE
Support Enum.HasFlag in LINQ

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/EntityFramework#2852]
Hi,

I'd like to see [`Enum.HasFlag`](https://msdn.microsoft.com/en-us/library/system.enum.hasflag) supported in EF's LINQ provider.
I think this feature is pretty useful. Especially with the support of enums introduced to EF in the recent versions - a great feature indeed.

**Comment by aluanhaddad** [comment]
Yes please.

**Comment by EgoPingvina** [comment]
6 years have passed - there is no answer. We love it.

**Comment by roji** [comment]
@EgoPingvina this was implemented back in 2016 and released with EF Core 1.1.0 (see the milestone above). If you've run into any problems with Enum.HasFlag, can you please open a new issue detailing that problem and including a runnable code sample?
