### ISSUE TITLE
Resolve System.Collections.Immutable version conflicts on CLR

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#2855]
Reverse engineering no longer works on CLR due to [recent changes in DNX](https://github.com/aspnet/dnx/pull/2474).

Reveng uses a version of Roslyn which is complied against System.Collections.Immutable 1.1.36.

EF.Core pulls in System.Collections.Immutable 1.1.37.

 On CLR, we resolved this with binding redirects https://github.com/aspnet/EntityFramework/commit/09412a130e0ff92d802dcc20fe0362f11be91f25 which worked until https://github.com/aspnet/dnx/pull/2474

@davidfowl @anurse @bricelam

**Comment by divega** [comment]
Moreover, the removal of the binding redirects was done to unblock the CI but now it blocks the flow of several devs in EF who run tests from VS. 

The PR https://github.com/aspnet/EntityFramework/pull/2845 mentions an assembly load loop in DNX that needs to be prevented. Is that a bug that can be fixed in DNX? @troydai @davidfowl @anurse

**Comment by ErikEJ** [comment]
Force EF Core to use 1,1,36 ??

**Comment by natemcmaster** [comment]
We should fix this before beta7 release. This completely breaks reverse engineering from the package manager console in Visual Studio.

![image](https://cloud.githubusercontent.com/assets/2696087/9313104/e071b1be-44d5-11e5-8370-03de325d89e8.png)

**Comment by bricelam** [comment]
@ErikEJ I tend to agree that EF should be using the **lowest** version of dependencies it needs--only updating for necessary fixes and features. This would maximize our *compatibility* with other packages. Apps could then use the **highest** compatible versions to maximize for *stability*.

**Comment by natemcmaster** [comment]
Used @ErikEJ's suggestion in #2860. As far my initial testing shows, just using an older version in EF.Core should work just fine (for now). It would be better in the long-run to revisit how reveng uses roslyn and razor to get a more version-insensitive solution.

**Comment by anurse** [comment]
How did this work (even on CLR) before aspnet/dnx#2474? DNX was **ignoring** the binding redirect completely before that change. Or do you mean on non-DNX hosts?

**Comment by bricelam** [comment]
@anurse DNX--both CLR and CoreCLR--was always fine; versions get normalized by the loader. Full .NET (one of EF's many targets) has a far stricter loader and needs this since Roslyn is bound against Immutable Collections 1.1.36 and EF against 1.1.37.

**Comment by anurse** [comment]
:+1: makes sense. I was just confirming that.
