### ISSUE TITLE
Enable migrations in ASP.NET Class library (package) 

### ISSUE THREAD

**Issue by ge6a93** [aspnet/EntityFramework#2867]
Hi,
I'm having DAL (Data Access Layer) class library package in ASP.NET MVC 6 where my entities and DbContext are located and I try to enable migrations  using "dnx . ef migration add MigrationName".
The result it an InvalidOperationException saying: 

System.InvalidOperationException: A type named 'StartupProduction' or 'Startup'
could not be found in assembly 'DAL'.

I wouldn't like to move my DAL structure to the Web application, so is there any workaround about it? Thanks!

**Comment by bricelam** [comment]
Yeah, I'm not sure why Hosting started *throwing* in that case. It used to work. :smile:

**Comment by bricelam** [comment]
This is related to #2357

**Comment by natemcmaster** [comment]
@ge6a93 Workaround: http://ef.readthedocs.org/en/latest/getting-started/osx.html#add-a-startup-class-to-your-project

**Comment by bricelam** [comment]
Closing since this work is tracked by #2294

**Comment by bricelam** [comment]
Re-opening. :blush: It's a distinct enough issue to track on its own.
