### ISSUE TITLE
DateTime.UtcNow support in LINQ queries to the SQL Server provider.

### ISSUE THREAD

**Issue by dcga** [aspnet/EntityFramework#2872]
As suggested in the now closed PR [#2853](https://github.com/aspnet/EntityFramework/pull/2853), DateTime.UtcNow is not supported in the DateTimeNowTranslator  Query Method of the SqlServer provider.

**Comment by rowanmiller** [comment]
@maumar the PR for this change is assigned to you to process

**Comment by maumar** [comment]
fixed in: 3a09a751b394554d7100f13b48d6cd6f4fad6526 e31280222fb95f9cc8122822b115c0310559604d 83be9062af86165b3b033553398bdc9ad64db92d
