### ISSUE TITLE
Throw better exception when trying to use BeginTransaction (or other relational APIs) on a non-relational store

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#2879]
Spinning off from https://github.com/aspnet/EntityFramework/issues/2866

**Comment by hkoestin** [comment]
Still not really happy with "just a better exception".
See https://github.com/aspnet/EntityFramework/issues/2866#issuecomment-133011083

**Comment by rowanmiller** [comment]
This was superseded by https://github.com/aspnet/EntityFramework/issues/2891
