### ISSUE TITLE
DNX Commands: Add --json switch for tool-consumable output

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/EntityFramework#2883]
One of the features that the Visual Studio ASP.NET team would like to support in `beta8` is the ability to [publish support for EF migrations](https://github.com/aspnet/EntityFramework/wiki/Visual-Studio-Publish-Integration).

In previous versions we had a difficult time discovering the contexts correctly for the publish dialog. For DNX projects we have `dnx ef context list`. We would like to use this to simplify the discovery process and to ensure we get the list correct. The issue with this is that the output of `dnx ef context list` is not in a format that is readable by VS. I'm proposing that we add a new switch `--json` to indicate that JSON should be returned instead of text.

@rowanmiller @vijayrkn @mayurid

**Comment by rowanmiller** [comment]
cc @bricelam for his thoughts

**Comment by bricelam** [comment]
Hmm, is there any particular reason you want to use the DNX command as an entry point? It would be better if you could use the API backing that command: `Microsoft.Data.Entity.Commands.ContextTool.GetContextTypes()` in `EntityFramework.Commands.dll`

**Comment by sayedihashimi** [comment]
@bricelam we followed a similar approach (_although a bit more complex_) with unit testing. It will enable us to integrate loosely. The implementation for ef migrations can change and there will be no impact to VS as long as the JSON format doesn't change.

**Comment by bricelam** [comment]
Alright, the approach seems OK to me.

I think JSON is overkill--the most data it could possible return is the list of assembly-qualified type names. I agree that we need to, in general, look at the consumability our our output. Automation workflows shouldn't have to filter out our logging.

**Comment by bricelam** [comment]
I think a `-q|--quite` flag would be idiomatic.

**Comment by sayedihashimi** [comment]
Sure if you pick some other format thats easily consumed thats fine with me. I suggested JSON because of we needed to add more later it would be easy. If we simply return a list of names there is not much opportunity to introduce additional values later.

**Comment by bricelam** [comment]
Yeah, I do see the point. It seems to work well for the `azure` command too...

**Comment by bricelam** [comment]
(Implementation Notes:)
The commands where this matters are
* `ef dbcontext list`
* `ef migrations list`
* `ef migrations script` (Already has `--output` for similar purposes)
* #577 (Backlog)

**Comment by sayedihashimi** [comment]
@bricelam there's an azure command?

**Comment by bricelam** [comment]
The non-DNX, node-based one :wink: [Azure/azure-xplat-cli](https://github.com/Azure/azure-xplat-cli)
