### ISSUE TITLE
Promote transaction API to core (& no-op implementation for in-memory)

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#2891]
Spun off from #2866 

The primary scenario is testing relational data access code against in-memory provider

**Comment by rowanmiller** [comment]
This is limited to:
* Move interfaces to core
* Make anything relational specific an extension method
* Create a null implementation for in-memory

**Comment by Yanal-Yves** [comment]
Hello @mikary, apparently this fix is not part of rc1.

Although I can find this fix in dev branch, I can not find it in the rc1 tag. For example the src/EntityFramework/Storage folder does not contain the IDbContextTransaction interface that has been introduced by this fix (https://github.com/aspnet/EntityFramework/tree/7.0.0-rc1/src/EntityFramework.Core/Storage)

Am I wrong or could you update the milestone of this ticket which is confusing IMHO?

Yanal

**Comment by mikary** [comment]
@Yanal-Yves That is correct, we were originally trying to get this change in for RC1 but it didn't quite make the cut. Just updated the milestone to reflect this.
