### ISSUE TITLE
Perf: Add cold start coverage

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#2894]
Our current performance tests focus mostly on performance of different pieces after warm up. We need more coverage that measures the cold start, e.g. loading EF and the provider, creating the model, etc.

**Comment by rowanmiller** [comment]
Added a set of Initialization tests that measure creation of context, model building, first roundtrip to database, etc. in both cold (first context instance for the AppDomain) and warm (fresh context instance but with another one previously created) scenarios https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.Microbenchmarks/InitializationTests.cs.

There is probably more coverage we could add, but these give us a good start on identifying the areas that need work.
