### ISSUE TITLE
Test: SQL Server 2008 coverage

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#2897]
Our functional tests usually run on recent versions of LocalDB. We want to support older versions of SQL Server including SQL Server 2008 so we should figure out a way (through automation or not) to have good coverage for it.

**Comment by natemcmaster** [comment]
Ran an initial test. Our functional tests make extensive use of SEQUENCE which is not supported in 2008.

**Comment by ErikEJ** [comment]
Also OFFSET and FETCH will cause 2008 to break

**Comment by natemcmaster** [comment]
Current results against SQL Server 2008 SP 1:

299 of 1645 tests in Ef.SqlServer.FunctionalTests fail.

13 fail with
> System.Data.SqlClient.SqlException : Incorrect syntax near 'OFFSET'.

21 fail with
> System.Data.SqlClient.SqlException : Incorrect syntax near 'OFFSET'. Invalid usage of the option NEXT in the FETCH statement.

262 fail with
> System.Data.SqlClient.SqlException : Unknown object type 'SEQUENCE' used in a CREATE, DROP, or ALTER statement.

3 fail with
> System.Data.SqlClient.SqlException : Unknown object type 'SEQUENCE' used in a CREATE, DROP, or ALTER statement. The name "next" is not permitted in this context. Valid expressions are constants, constant expressions, and (in some contexts) variables. Column names are not permitted.

**Comment by rowanmiller** [comment]
Given we have a design principle to optimize for the latest releases and be ok with needing to do additional configuration for older versions of SQL Server we probably need to do additional config on the test model when running on SQL2008.

**Comment by ajcvickers** [comment]
Also there are some tests that just won't work with older versions--for example, anything testing sequences is not going to work. We should have a way of excluding these.

**Comment by anpete** [comment]
Rather than exclude, we should do what @rowanmiller says and figure out how to run them with different config (where it makes sense).

**Comment by natemcmaster** [comment]
Excluding tests is easy. But what about OFFSET? Should we create a SQL2008 query generator that has a workaround?

**Comment by anpete** [comment]
@natemcmaster We are already tracking this. #2180

**Comment by divega** [comment]
Talked to @ajcvickers and we arrived to the conclusion that we have three classes of tests that use SEQUENCE:

1. _Our SQL Server SEQUENCE support tests:_ these will never work with SQL Server 2008 so could be skipped or ignored 
2. _Tests that are using SEQUENCE as an implementation detail but don't care about generated values:_ we can switch to use the default value generation (IDENTITY for SQL Server) without watering down the value of the test
3. _Tests that are using SEQUENCE because we wanted to use specific values we can latter assert against:_ We can hard code key values without decreasing the value of the test.

**Comment by natemcmaster** [comment]
#3086 resolves this issue. 68 tests fall into category 1. Otherwise, the testing required minimal changes to run against 2008.

**Comment by natemcmaster** [comment]
Fixed with #3086

**Comment by divega** [comment]
Thanks!
