### ISSUE TITLE
Broken doc comments

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#2918]
Looks like some got broken after renames:

    /// <summary>
    ///     A <see cref="ReaderModificationCommandBatch" /> for providers which append an SQL query to find out
    ///     how many rows were affected (see <see cref="SqlGenerator.AppendSelectAffectedCountCommand" />).
    /// </summary>
    public abstract class AffectedCountModificationCommandBatch : ReaderModificationCommandBatch

"SqlGenerator" is stale.

**Comment by rowanmiller** [comment]
Fixed this (and others) in RC1
