### ISSUE TITLE
Query: Relational: Correlated client sub-query improvement ideas

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#2927]
For queries that result in separate nested correlated sub-queries, we should try and parameterize the inner queries with the correlation values from the outer query. E.g.

This query:

``` c#
 var orderDetails
    = (from od in context.Set<OrderDetail>()
        select (from o in context.Set<Order>()
            where od.OrderID == o.OrderID
            select o).First())
```

we currently gen:

``` sql
SELECT TOP(2) [od].[OrderID]
FROM [Order Details] AS [od]

SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
FROM [Orders] AS [o]

-- ...
```

but we might be able to gen this:

``` sql
SELECT TOP(2) [od].[OrderID]
FROM [Order Details] AS [od]

SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
FROM [Orders] AS [o]
WHERE @p0 = [o].[OrderID]

-- ...
```

**Comment by tuespetre** [comment]
I think this covers it: https://github.com/aspnet/EntityFramework/pull/7543/files?diff=split#diff-2602188597986ba3e53c5b56162786d2L514

**Comment by smitpatel** [comment]
We may be already doing this.

**Comment by divega** [comment]
@anpete @smitpatel please try to assign resolution and milestone when you close, unless it is too much work to figure out the right values.

**Comment by anpete** [comment]
@maumar Can you add the milestone when this was done (outer parameter introduction).

**Comment by divega** [comment]
The final release milestone is sufficient. E.g. if it was in a 2.0 milestone, 2.0.0 should be enough.
