### ISSUE TITLE
AsyncLock deadlocks - Remove AsyncLock

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#2930]
A few of us have been seeing this in `EntityFramework.SqlServer.FunctionalTests`. The easiest way to repro is:

1. Drop all databases
2. Comment out `[assembly: CollectionBehavior(MaxParallelThreads = 15)]`in `AssemblyInfo.cs`
3. Run the tests

**Comment by rowanmiller** [comment]
Done
