### ISSUE TITLE
SQLite storing Chinese characters problem in beta 6 

### ISSUE THREAD

**Issue by Kagamine** [aspnet/EntityFramework#2936]
<img width="907" alt="qq20150827-1 2x" src="https://cloud.githubusercontent.com/assets/2216750/9516089/ebc3cf38-4cd8-11e5-8bda-816df5b2cfb4.png">

After saving:

<img width="263" alt="qq20150827-2 2x" src="https://cloud.githubusercontent.com/assets/2216750/9516098/f9d7d614-4cd8-11e5-86ee-5c25da5f056b.png">

**Comment by Kagamine** [comment]
How to set the charset into utf8?

**Comment by natemcmaster** [comment]
As of https://github.com/aspnet/Microsoft.Data.Sqlite/pull/89 (merged June 4), UTF-8 should already be the default encoding in the database. Can you add [reproduction steps](https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md#filing-issues) so we can verify if this is an issue in EF or SQLite?

**Comment by Kagamine** [comment]
Okay, Here is the admin controller:

        [AdminRequired]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Admin/Catalog/Edit")]
        public IActionResult CatalogEdit(string id, string newId, string title, int pri)
        {
            var catalog = DB.Catalogs.Where(x => x.Url == id).SingleOrDefault();
            if (catalog == null)
                return TemplatedError(404);
            catalog.Url = newId;
            catalog.Title = title;
            catalog.PRI = pri;
            DB.SaveChanges();
            return Content("true");
        }

I called the CatalogEdit action with typed title "测试"

but the navicat showed me an incorrect string, and it was incorrect also in my site.

<img width="456" alt="qq20150828-1 2x" src="https://cloud.githubusercontent.com/assets/2216750/9526420/d0d55bea-4d1b-11e5-83d1-dbfa92ffb573.png">

Here is Startup.cs:

            services
                .AddEntityFramework()
                .AddSqlite()
                .AddDbContext<BlogContext>(options =>
                    options.UseSqlite("Data source=" + appEnv.ApplicationBasePath + "/" + Configuration["DBFile"] + ";")); // Databse/Yuuko.db

**Comment by Kagamine** [comment]
<img width="1137" alt="qq20150828-2 2x" src="https://cloud.githubusercontent.com/assets/2216750/9526490/27b00924-4d1c-11e5-9ea4-830b9d3dfcbf.png">

But I typed the same string three times, it will show once.

For example, I type "测试测试测试", it will show me "测试".

**Comment by Kagamine** [comment]
<img width="628" alt="qq20150828-3 2x" src="https://cloud.githubusercontent.com/assets/2216750/9526550/855fb5ec-4d1c-11e5-9b54-7a2b74f2179a.png">

After saving:

<img width="182" alt="qq20150828-4 2x" src="https://cloud.githubusercontent.com/assets/2216750/9526559/8ed6f068-4d1c-11e5-81ec-3a89587bae79.png">

**Comment by Kagamine** [comment]
<img width="296" alt="qq20150828-5 2x" src="https://cloud.githubusercontent.com/assets/2216750/9526610/ed38bede-4d1c-11e5-8e5b-83b509064a2c.png">

After saving:

<img width="278" alt="qq20150828-6 2x" src="https://cloud.githubusercontent.com/assets/2216750/9526618/f6d07e32-4d1c-11e5-91ee-f95c92126aaa.png">

**Comment by Kagamine** [comment]
```
  "dependencies": {
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta6",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta6",
    "CodeComb.vNext": "1.0.28",
    "CodeComb.AntiXSS": "1.0.4",
    "CodeComb.Localization": "1.0.1",
    "Microsoft.AspNet.Mvc": "6.0.0-beta6",
    "EntityFramework.Sqlite": "7.0.0-beta6",
    "CodeComb.Marked": "1.0.1",
    "Microsoft.AspNet.Session": "1.0.0-beta6",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta6",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta6"
  },
```

**Comment by Kagamine** [comment]
@natemcmaster

**Comment by natemcmaster** [comment]
Adding to investigations.

**Comment by Kagamine** [comment]
Thanks :)

**Comment by Kagamine** [comment]
There is a same problem that I finded in [https://social.msdn.microsoft.com/Forums/zh-CN/63c6dfe0-edf5-4833-bb3d-7c50953cae87/ef-7-sqllite?forum=295](https://social.msdn.microsoft.com/Forums/zh-CN/63c6dfe0-edf5-4833-bb3d-7c50953cae87/ef-7-sqllite?forum=295),

**Comment by bricelam** [comment]
Could the problem be somewhere between the form submission and passing the value to EF? In other words, is the encoding already scrambled before passing it to EF?

**Comment by natemcmaster** [comment]
Confirmed bug:

```c#
        [Fact]
        public void Can_use_utf_8()
        {
            var testString = "测试测试测试";
            var id = 0;
            using (var context = new ChipsContext(_serviceProvider, "DefaultKettleChips"))
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
                var chineseDijon = context.Add(new KettleChips { Name = testString }).Entity;
                context.SaveChanges();
                id = chineseDijon.Id;
            }

            // ensure we get a new reference, not one from the state manager
            using (var context = new ChipsContext(_serviceProvider, "DefaultKettleChips"))
            {

                var chineseDijon = context.Chips.First(k => k.Id == id);
                Assert.Equal(testString, chineseDijon.Name);
            }
        }
```

```
Test 'Microsoft.Data.Entity.Sqlite.FunctionalTests.DefaultValuesTest.Can_use_utf_8' failed: Assert.Equal() Failure
            ↓ (pos 2)
Expected: 测试测试测试
Actual:   测试
            ↑ (pos 2)

```

**Comment by Kagamine** [comment]
@bricelam It will be stored correctly when I change the provider into sqlserver.

**Comment by Kagamine** [comment]
<img width="819" alt="qq20150828-8 2x" src="https://cloud.githubusercontent.com/assets/2216750/9536138/3d642702-4d5b-11e5-8b62-79c1ce42848d.png">

<img width="653" alt="qq20150828-9 2x" src="https://cloud.githubusercontent.com/assets/2216750/9536154/654063bc-4d5b-11e5-9fa6-7421526e72db.png">

This problem may be an EF problem. It was correctly by using Microsoft.Data.Sqlite without EF.

**Comment by natemcmaster** [comment]
I can confirm what @Kagamine. The string termination bug does not appear to be in the ADO layer.

**Comment by natemcmaster** [comment]
Traced down to a bug in Microsoft.Data.Sqlite parameter binding.
