### ISSUE TITLE
Make FromSqlQuery tests provider-agnostic

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#2941]
While trying to run more tests for PostgreSQL, I ran into the FromSqlQuery functional test suite. FromSqlQueryTestBase contains specific SQL queries such as `SELECT [Region], [PostalCode]...` which won't be supported across providers (square brackets). As another example, PostgreSQL requires table and column names to be quoted to maintain case-sensitivity (so `SELECT * FROM "Customers"` and not `SELECT * FROM Customers`).

Am not sure how I'd refactor this testsuite to be useful across providers, letting providers provide the actual SQL is a possibility but we'd end up with an abstract property per test, almost.

**Comment by natemcmaster** [comment]
Yes, this should be changed.

**Comment by anpete** [comment]
Those ones would probably just work if we removed the delimiters.

**Comment by divega** [comment]
@mikary should this be closed now or are we waiting to hear from @roji if it worked for him?

**Comment by roji** [comment]
Promise to look at this a bit later

**Comment by roji** [comment]
Guys, unfortunately the changes aren't enough to make this PostgreSQL compatible because of the second example I mentioned above: in PG identifier must be quoted in order to preserve uppercase characters, otherwise PG converts everything to lowercase, so `SELECT PostalCode FROM Customers` must become `SELECT "PostalCode" FROM "Customers"`. I realize this wouldn't work with SqlServer, so it seems a more fundamental change in this testsuite is needed...

**Comment by anpete** [comment]
@roji Is this because the Northwind schema objects are created with the quotes?

**Comment by roji** [comment]
That's right. If the identifiers in the database aren't all-lowercase then you have to use double quotes when referencing them.

You could in theory change the Northeind scheme for this but it seems like a pretty huge change. Note that I only have issues with these suite since it defines SQL assertions in the *base* class, which doesn't seem like a good idea given provider variety out there (who knows what provider will come next with some SQL quirk)

**Comment by anpete** [comment]
Agreed, and that is my concern with template-izing only part of the SQL. I.e. The delimiters. Either the SQL needs to be fully portable (may be possible at the moment if we just use " everywhere), or, we allow you to replace the entire SQL statement. I also don't want us to re-invent an ad hoc SQL generation provider model in the test.

Are the quotes the only think blocking you right now?

**Comment by roji** [comment]
@anpete yeah, I think so... sorry that I don't have time to test for other issues right away (can do this tomorrow)

**Comment by anpete** [comment]
@mikary Can you change the base SQL to use " for now?
