### ISSUE TITLE
RevEng: Remove our Razor dependency

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#2947]
After reviewing the outcome of trying to use Razor to generate C# code in our templates and we have come to the conclusion that it is probably not the right thing to do for the long term. There are several reasons for that, among others:

1. Razor is optimized for HTML generation and a template to generate generating C# code can't be very terse.
2. Razor templates (in particular ours) tend to contain a lot of logic which can be powerful, but we don't believe that having it inside the template necessarily provides the best experience. 

We still want to provide extensibility through some templating language in the future but haven't been able to identify a technology that we can take a dependency on with that purpose in the short term. 

We are then going to focus on having a great default experience, e.g. try to get out default generated code as good as possible for EF 7 RTM, while leaving our choice of a template language open.

That implies sacrificing the ability to customize the output code via templates for RTM and it requires either removing the current Razor-based implementation or turning it into an internal implementation detail.

**Comment by rowanmiller** [comment]
Changing to "remove" rather than "internalize" being an option given https://github.com/aspnet/EntityFramework/issues/3340

**Comment by lajones** [comment]
Removed with PR #3393.
