### ISSUE TITLE
"Malformed" SQL generated by MigrationSqlGenerator

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#2950]
This method in EF.Relational.MigrationSqlGenerator

        public virtual IReadOnlyList<RelationalCommand> Generate(
            IReadOnlyList<MigrationOperation> operations,
            IModel model = null)

generates the following "Malformed" SQL

    INSERT INTO [__MigrationHistory] ([MigrationId], [ProductVersion])
    VALUES (N'00000000000000_Empty', N'7.0.0-csproj');;

which may work as is on some database engines, but not on SQL CE.  (Notice the double semicolon at the end)

Changing to

      .AppendLine() 

fixes the issue (for me, anyway) - but I doubt it is the "correct" fix @bricelam

**Comment by bricelam** [comment]
Hmm, there are some TODOs to change the way those get added to the migration script. This could be fixed as part of that.

**Comment by ErikEJ** [comment]
@bricelam Still not working, sorry! Have raised a new issue (since I cannot re-open)
