### ISSUE TITLE
EF7 bug with zero value in primary key column

### ISSUE THREAD

**Issue by tstar** [aspnet/EntityFramework#2951]
I have simple table Test with one column Age (int) with primary key on this column.
```
CREATE TABLE [dbo].[Test](
	[Age] [int] NOT NULL,
	CONSTRAINT [PK_Test] PRIMARY KEY CLUSTERED ([Age] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY])
ON [PRIMARY]
```
My table has 2 values (0, 1).
Also I have model for this table
```
modelBuilder.Entity<Test_Entity>(x =>
{
	x.ToTable("Test", "dbo");
	x.Key(i => i.Age);
});

public DbSet<Test_Entity> Test { get; set; }

public class Test_Entity
{
	public int Age { get; set; }
}

```
I need read all data to array like:
```
var result = Test.ToArray();
```
In result I am waiting something like:
```
[0] | { Age = 0 }
[1] | { Age = 1 }
```
But in fact I have:
```
[0] | null
[1] | { Age = 1 }
```
In Beta 2 this tests runs well. But in Beta 5, 6, 7, 8 I have this error.

My previous report about this problem https://github.com/aspnet/EntityFramework/issues/2117

**Comment by rowanmiller** [comment]
Talk with @ajcvickers about sentinel value behavior for this one

**Comment by anpete** [comment]
@tstar, We will be changing this to throw, which is likely not what you are looking for here. The problem is that your data contains a sentinel value. i.e. A non-nullable value that EF interprets as null. If 0 is actually a valid value in your domain, then either make the Age CLR property nullable (int?), or configure a different sentinel value, E.g. -1.

**Comment by tstar** [comment]
Of course "0" actual and a very important value for us in our system. It can not be Nullable or -1. It should always be "0". I do not understand why in previous EF versions it has not caused problems, but now it has become a problem for us? Because of this, we can not upgrade to the EF7 and without EF7 we can not upgrade to Identity 3 and so on ... In general, everything is very, very sad for us.

**Comment by maumar** [comment]
Sentinel value can be any number that you never going to use as an actual value in your database. E.g. If Age is always at least 0 (and never a negative number) by setting sentinel value to -1, as Andrew suggested, should solve your problem. EF will start treating -1 as a null representation, allowing 0 to be an actual valid value for the key. You don't need to change the values in your database, if that's what you were worried about

**Comment by tstar** [comment]
Thanks you very much. Now I understand what the problem is (in my bad English too). But still I do not see how I can solve it. Column "Age" is int only in this test case. In real system it is tinyint in database and byte in CLR. I can not select any value from 0-255 to set a sentinel value and can not make it nullable. I can not imagine how I can fix this situation without a complete redesign of an existing database. There must be some way to bring the behavior EF7 to have been in the EF6. Is there a global option to disable this feature?

**Comment by ErikEJ** [comment]
And all values between 0 and 255 are in use in your "real system"?

**Comment by tstar** [comment]
The problem is not in the is I use the entire range of numbers or not. EF model is built automatically from the database. EF builder can not know in advance, what number can be used to the sentinel value. I could not even imagine that I would have to face such a problem given the experience with EF6 and other frameworks. I was even afraid to imagine how I can solve the problem with Boolean primary keys that can not be Null. I do not understand why the framework has to make some restrictions on the used data, and the developer should know about them. I am sure that after the release EF7 it will become a common problem.

**Comment by anpete** [comment]
cc @ajcvickers, @divega 

How are new primary keys generated? Do you really want to use boolean PKs?

**Comment by tstar** [comment]
Do you really want to use boolean PKs? - Why not? If I can do it in the database, then why I can not do this in EF7 without magic? Why I can not map simple data from a simple database table in a simple EF7 entity? I do not have to think of something to read data from the database, like in EF6 or Linq2SQL. But if I have to write or update the data in the table with an auto-increment or sequential primary keys, then yes, I have to think about it. I believe that sentinel value mechanism should be disabled by default.

I had hoped that this can be disabled with the help of StoreGeneratedPattern(StoreGeneratedPattern.None), but I can not find it and I can not understand how it can be replaced. But I'm not sure it will help me.

**Comment by anpete** [comment]
> Do you really want to use boolean PKs? - Why not? If I can do it in the database, then why I can not > do this in EF7 without magic?

The short answer is: Because we have finite resources, and given the resources we have, we are trying to build something that provides the most value to the most people.

The reason I asked the question about boolean PKs was to try and determine whether or not your were posing this as a hypothetical, or whether you actually need this for a real world scenario. Helping us to understand why you would like to use EF in a particular way can help us to improve the design in areas such as this.

**Comment by rowanmiller** [comment]
I think even aside from resources, an O/RM does not expose every piece of functionality available in the database. We pick the scenarios that make sense for the application patterns we are trying to enable.

While I can't say I've ever seen a bool PK in a real world app, I do think maybe we need a way to disable the sentinel value for non generated keys (perhaps achieved internally just by setting it something the property will never be, such as `null`). That way we always just try and save whatever you give us and it's up to the developer to ensure they are unique before adding. It would enable this bool scenario but more importantly it would be an easy way to opt out for folks who know they always want to specify values.

**Comment by L4ng3** [comment]
I have this problem as well with an old database that for some reason a table (lets call it x) that has a FK to a user table. I need to insert a row in the table X with userId that is 0 ( zero ). The x table has the userId as a primary key.

It gave me the following error: 

"System.InvalidOperationException: The property 'UserId' on entity type 'XModel' has a temporary value. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property."

After much frustration and totally agree with tstar that EF7 should not force change of databases I found a solution:

public int? UserId { get; set; }

Then it worked. This is however a bit wrong as my column in table X is a PK with NOT NULL but now it is nullable in my ASP.NET Core 3.1 project.

You gave me no choice.

**Comment by OpenSpacesAndPlaces** [comment]
I ran into something similar here with an existing DB - the testing account was using two field PK on several tables where the second was intentionally zero. When you tried update the record, it would at like it was doing in upsert and then fail on duplicate keys.
