### ISSUE TITLE
React to memory cache key change from string to object

### ISSUE THREAD

**Issue by kichalla** [aspnet/EntityFramework#2966]
This is regarding the following commit:
https://github.com/aspnet/Caching/commit/1818306bc3b792cdec7938c717a6d7a854f3934b

Following is one location where you are currently trying to build a key, which you can avoid doing now:
https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/Query/CompiledQueryCache.cs#L166-L170

@divega @anpete

**Comment by divega** [comment]
Thanks for the heads up @kichalla. We will look into this. BTW, I am going to make a comment on the test of your PR.
