### ISSUE TITLE
Update System.Data.SqlClient

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#2977]
Blocked on aspnet/dnx#2387

**Comment by natemcmaster** [comment]
The latest version of SqlClient on coreclr fails on Windows Server 2012 R2.

**Comment by natemcmaster** [comment]
@bricelam the CI boxes will not work with SqlClient 4.0.0-beta-23302 for reasons no one understands. Reverting to an older version.

**Comment by natemcmaster** [comment]
Closed with #3268
