### ISSUE TITLE
StateManager: Review exception thrown when adding entity with sentinel key

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#2985]
When adding an entity with a sentinel key and the key property is ValueGeneratedNever, we throw:

_System.InvalidOperationException : The instance of entity type 'Microsoft.Data.Entity.FunctionalTests.NullKeysTestBase<Microsoft.Data.Entity.InMemory.FunctionalTests.NullKeysInMemoryTest+NullKeysInMemoryFixture>+WithIntKey' cannot be tracked because another instance of this type with the same key is already being tracked. For new entities consider using an IIdentityGenerator to generate unique key values._

This is somewhat confusing.

**Comment by ajcvickers** [comment]
Marking for re-triage. Should probably go to @rowanmiller to write a new message.

**Comment by rowanmiller** [comment]
Superseded by https://github.com/aspnet/EntityFramework/issues/4525 which deals with the same exception message (and is more applicable now that sentinel values are gone).
