### ISSUE TITLE
Allow to override PKs/FKs on relationships that have been already configured

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#2987]
Consider:
```
builder.Entity<Category>().Collection(e => e.Products).InverseReference(e => e.Category)
                    .ForeignKey(e => new [] { e.CategoryId, e.CountryId })
                    .PrincipalKey(e => new [] { e.CategoryId, e.CountryId });

builder.Entity<Category>().Collection(e => e.Products).InverseReference(e => e.Category)
                    .ForeignKey(e => e.CategoryId)
                    .PrincipalKey(e => e.CategoryId);
```

The second configuration will throw currently, because the FK doesn't match the PK specified previously. However doing this might be necessary when configuring a shared model for another provider or another app. This also conflicts with the general guideline of "Last configuration wins".

**Comment by rowanmiller** [comment]
We agree this is incorrect and should work, but reconfiguring a relationship is not a common case so moving to backlog.
