### ISSUE TITLE
Possible null ref in RelationalParameter

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#3002]
```
Value.GetType().IsNullableType()
```

**Comment by csunali** [comment]
This null reference exception occurs with a basic query as below:

```
long? parentId = null;

IQueryable<Item> query = new ApplicationDbContext().Items.Where(i => i.ParentId.Equals(parentId));

List<Item> items = query.ToList();
```

The `ParentId` field is of type `long?`.

I can see that the work to fix this issue has already been done. When do you think we can see it on the developer feeds?

**Comment by mikary** [comment]
The PR associated with this issue was actually closed for rework due to a design/factoring issue. I'll try to get a PR to specifically address this issue out right away.

**Comment by csunali** [comment]
Appreciated.

**Comment by mikary** [comment]
When testing changes based on the reproduction, I discovered that query does not provide Type information when adding parameters resulting in using the default type for null values (which doesn't work in the case of the provided query).

**Comment by mikary** [comment]
Opening related issue #3208
