### ISSUE TITLE
RequiredAttribute on navigation should try to set dependent side

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#3006]
`Required` attribute on navigation property defines the null-ability of foreignkey. Hence it is logical to have `Required` appear on the navigation on dependent side (i.e. dependent to principal navigation). If we encounter `Required` on principal to dependent navigation, we should try inverting relationship and set required.
In case of required being on both navigations, do not invert, set required and log warning.

**Comment by rowanmiller** [comment]
This should have the lowest precedence and just be used as a tie break when we don't have a clear winner based on detecting FKs etc.
