### ISSUE TITLE
Cleanup MonsterFixup tests

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#3007]
MonsterFixupTests do not follow our test fixture conventions. Refactoring will require significant changes to the test structure.

**Comment by ajcvickers** [comment]
Note that the point of these tests are to start with an empty database and then to add and save graphs to the empty database in different ways. In other words, we could change the tests to create an empty database in the fixture and then make sure it is cleared of data before each test runs--the easiest way to do this is to drop and recreate it, which is what the tests do. But changing the tests to create and seed a database once for all the tests would break the tests.

**Comment by anpete** [comment]
Creating a scratch store either in the test or the test class ctor is a good way to do this.

**Comment by natemcmaster** [comment]
Initial work in https://github.com/natemcmaster/EntityFramework/tree/monsterfixup (left over from https://github.com/aspnet/EntityFramework/pull/2931#discussion_r38704441)

**Comment by ajcvickers** [comment]
Closing since efficient cleaning out of the database is now implemented.
