### ISSUE TITLE
Provider writers need test packages on "Nuget.org"

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#3016]
it would be ideal/easier if the https://www.myget.org/gallery/aspnetbeta7take2/ (or future type feed) also included the EF test packages, pointing to betaX packages

**Comment by roji** [comment]
+1, right now there is no EF test package which references beta7.

**Comment by rowanmiller** [comment]
The purpose of https://www.myget.org/gallery/aspnetbeta7take2/ is to just include the packages that are going to be published to NuGet.org so that we can do final verification that there is nothing missing etc.

It sounds like we should consider just publishing the packages to NuGet.org though (probably as unlisted)

**Comment by divega** [comment]
+1 I am starting to think that it would be ok to publish them to nuget.irg and maybe even listing them is OK.

**Comment by roji** [comment]
That would definitely be easiest for me. Any reason not to list them? After all they're public-facing in the sense that they're provider-facing...

**Comment by ErikEJ** [comment]
+1 whether they are listed or not is not important, as long as they are available!

**Comment by ErikEJ** [comment]
Updated the title to reflect the desired goal

**Comment by roji** [comment]
Additional request: if you guys could also release nugets of your unit test suites (EntityFramework.Core.Tests, EntityFramework.Relational.Tests), that would help us a lot. For example, both @ErikEJ and I duplicate MigrationSqlGeneratorTestBase.cs in our unit test suites because a nuget is missing.

**Comment by ErikEJ** [comment]
@roji - now you are pushing it! :smiling_imp:

**Comment by davidfowl** [comment]
Same idea here https://github.com/aspnet/DependencyInjection/issues/270

**Comment by roji** [comment]
@ErikEJ that's how it works, you give pesky developers a little bit and they'll ask for a lot :)

@davidfowl yep. The EF7 team already publish a *functional* test suite, which is extremely useful when working on a database provider. But thers'a also an unpublished unit test suite.

**Comment by bricelam** [comment]
@rowanmiller In terms of build and CI, everything looks good. Assigning to you to ensure they get published as part of the next release.

**Comment by rowanmiller** [comment]
@muratg can you add these packages to the list that gets published for Beta 8
* EntityFramework.Core.FunctionalTests
* EntityFramework.Relational.FunctionalTests
* EntityFramework.Relational.Design.FunctionalTests

**Comment by muratg** [comment]
It looks like this are new packages. I'll add these to the upload list.

@danroth27 FYI

**Comment by ErikEJ** [comment]
Those packages are now available in the beta8 myget feed, thanks for fixing this!

**Comment by muratg** [comment]
@ErikEJ NP, and they will be in nuget.org when we release beta 8 as well.
