### ISSUE TITLE
Projection with Count not generating correct SQL

### ISSUE THREAD

**Issue by davezych** [aspnet/EntityFramework#3029]
I have a few forum style entities with references as such:

    public class Forum
    {
        public int ForumId { get; set; }
        public string Title { get; set; }

        public ICollection<Topic> Topics { get; set; } =  new List<Topic>();
    }

    public class Topic
    {
        public int TopicId { get; set; }
        public string Title { get; set; }

        public int ForumId { get; set; }
        public Forum Forum { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Forum> Forums { get; set; }
        public DbSet<Topic> Topics { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Forum>()
                        .Collection(f => f.Topics)
                        .InverseReference(t => t.Forum)
                        .ForeignKey(t => t.ForumId);
        }
    }

I'm attempting to get a list of `Forum` with the count of the `Topic` for each forum:

    return _context.Forums.Include(f => f.Topics).Select(f => new
            {
                Title = f.Title,
                TopicCount = f.Topics.Count(),
            });

This results in the following SQL:

    SELECT [f].[ForumId], [f].[Title]
    FROM [Forums] AS [f]

and doesn't include a `Count` aggregate or anything, and returns 0 Topics. Is this a bug, or is this type of projection not supported?

**Comment by anpete** [comment]
Hey, which version of EF are you running against.

**Comment by davezych** [comment]
EF7 beta 7. Sorry, I forgot to add that.

**Comment by rowanmiller** [comment]
@anpete did we have collection nav prop translation in Beta 7?

**Comment by anpete** [comment]
We had some, but I'm pretty sure we didn't have collections in the projection like this.

**Comment by davezych** [comment]
@rowanmiller @anpete For what it's worth it doesn't seem to work in the latest beta8 build either.

**Comment by anpete** [comment]
Not sure if it's landed in beta8 but here is a test from dev where we do something similar:

https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs#L346

**Comment by rowanmiller** [comment]
Beta8 is the current code base, @davezych just confirming that you mean you are using the nightly build and it is not working?

**Comment by anpete** [comment]
@rowanmiller Yeah, just wasn't sure if it had landed in the nightly :-)

**Comment by davezych** [comment]
@rowanmiller yea, I forget the exact build number but it was a build from 2 or 3 days ago. 

Sounds like it's in progress. This issue can be closed if you guys don't need it.

**Comment by divega** [comment]
I will leave it to @anpete to decide if this isdue can be closed, but it would actually be great to get confirmation that it is fixed for you. It might be that the fix just hasn't propagated yet to what is in the nightly feeds but it could also be that we are missing some detail about your repro.

**Comment by davezych** [comment]
@divega Sounds good. I'll keep trying the nightly's and let you know if it works. If you think it hit's the nightly, let me know and I'll try it.

**Comment by maumar** [comment]
this is still broken in latest bits

**Comment by davezych** [comment]
Just tried this with `beta8-15840` and receive the following exception:

>An exception of type 'System.InvalidOperationException' occurred in EntityFramework.Core.dll but was not handled in user code

>Additional information: The EF.Property<T> method may only be used within LINQ queries.

**Comment by divega** [comment]
That sounds a lot like #3119 which we I closed because I couldn't repro.

**Comment by davezych** [comment]
@divega I just upgraded to latest rc1 bits (`rc1-15886`) and I get the same `EF.Property<T>` exception as above. I'll see if I can isolate the issue and provide you with some more useful information. Here's what my model looks like now:

    public class Forum
    {
        public Forum()
        {
            Topics = new HashSet<Topic>();
        }

        public int ID { get; set; }
        [Required]
        public string Title { get; set; }

        [InverseProperty("Forum")]
        public virtual ICollection<Topic> Topic { get; set; }
    }

    public class Topic
    {
        public Topic()
        {
        }

        public int ID { get; set; }
        public int ForumID { get; set; }
        [Required]
        public string Title { get; set; }

        [ForeignKey("ForumID")]
        [InverseProperty("Topics")]
        public virtual Forum Forum { get; set; }
    }

    return _context.Forums.Include(f => f.Topics).Select(f => new
        {
            Title = f.Title,
            TopicCount = f.Topics.Count(),
        });

**Comment by davezych** [comment]
@divega @rowanmiller I tested this most of the day and I'm still getting the `The EF.Property<T> method may only be used within LINQ queries` error. I'm using the latest rc1 bits (`rc1-15886`). It seems like the existence of data causes it to break - if the tables are empty it runs without error. This may also be relevant to #3119.

I created a sample application showing the error here: https://github.com/davezych/EF7_3029. There is a seed built in so the tables will have data. If you run the app and navigate to `Home/Index` it should throw the error I'm seeing above.

**Comment by divega** [comment]
@davezych Thanks for all the details and repro code! This is really helpful. @maumar will be investigating this. He may be able provide and ETA for when he will get to it.

**Comment by davezych** [comment]
@maumar any updates on this? I know you're probably way busy, but this seems (to me at least) to be a relatively big bug.

**Comment by maumar** [comment]
@davezych I'm currently working on a bug that also exhibits this behavior and I'm pretty close to pushing the fix (I think, the bug turned out to be multi-faceted). Basically we are translating nav props incorrectly (e.g. Property(forum, "ForumId") rather than Property(topic, "ForumId"). Because what we constructed is not in the model, we think its a client side property access and leave it as us, rather than translating it to get value from the data reader.

**Comment by davezych** [comment]
:+1:

**Comment by maumar** [comment]
fixed in 41ad57ad2f3755c5e35b51d939fab52b489ce738
