### ISSUE TITLE
Feature Request: Scaffolding a database should allow to specify the context name

### ISSUE THREAD

**Issue by abelepereira** [aspnet/EntityFramework#3047]
Currently (beta7) when scaffolding a database the derived DbContext class will pick the database name suffixed with the "Context" word.

For example:
```
dnx ef dbcontext scaffold "Server=myserver;Database=Foo;user id=me;password=pwd" EntityFramework.SqlServer
```

Produces a class named `FooContext`. The command should allow passing the context name as a parameter:
```
dnx ef dbcontext scaffold "Server=myserver;Database=Foo;user id=me;password=pwd" EntityFramework.SqlServer --context-name MyDbContext
```

**Comment by lajones** [comment]
Thanks for the feedback - I've checked in a fix for this with commit 4f133c1. The flag is --context-class-name or -c for short.
