### ISSUE TITLE
Fluent API renames

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#3071]
We still have several API names that do not align with the EF6 equivalent (i.e. `MaxLength` vs. `HasMaxLength`).

We also need to apply the [relationship API naming decisions from a recent design meeting](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes--August-20,-2015#relationship-api-naming).

**Comment by leus** [comment]
Had to use `git blame` when upgrading to find out what `Reference` and `InverseCollection` were now. Is there a "breaking changes" list or wiki page somewhere?

**Comment by ErikEJ** [comment]
@leus There are many "breaking" changes all the time, as this is beta software in motion...

**Comment by leus** [comment]
@ErikEJ of course, that's not the point - I love living on the edge, but sometimes it's a little too difficult to find out these kind of changes. It's not important, just a nice-to-have.
