### ISSUE TITLE
Reverse Engineer: Can we just scaffold string properties for `xml`, `hierarchyid`, `geography`, `geometry`, etc

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#3076]
Some of these datatypes may just work with an implicit conversion to/from string. We need to investigate which ones work (or can work with minimal changes) and then update reverse engineer to scaffold a string property for them.

**Comment by nteague22** [comment]
I do know that stored procedures as of Sql Server 2012 can accept string ADO parameter values when the parameter type is marked as HierarchyId, is there a simple way to override and create a new derivative of SqlOperation that extends these checks?

**Comment by bricelam** [comment]
@nteague22 It may require a few changes, but we should be able to set the parameter type using the [SqlServerTypeMapper](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.SqlServer/Storage/Internal/SqlServerTypeMapper.cs).

**Comment by nteague22** [comment]
Excellent, I really am impressed with the work you guys produce and the team as a whole!  Even in beta, EF7 makes my life easier on running ETL and other data migratory operations

**Comment by wangkanai** [comment]
How is issue going? I still that the https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.MicrosoftSqlServer/Storage/Internal/SqlServerTypeMapper.cs is unchanged.
Hoping to see this feature add by rc1 :)

**Comment by bricelam** [comment]
@wangkanai Have you tried manually adding the properties to your model?

**Comment by wangkanai** [comment]
@bricelam  Do you mean like mapping a object property [System.Data.Spatial] (https://msdn.microsoft.com/en-us/library/system.data.spatial(v=vs.110).aspx) to [Spatial Data Types](https://msdn.microsoft.com/en-us/library/bb964711.aspx) in demo application? **No** :smile:, don't know where to start, still studying your codebase.
Or add [RelationalTypeMapping](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Storage/RelationalTypeMapping.cs) to your [SqlServerTypeMapper.cs](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.MicrosoftSqlServer/Storage/Internal/SqlServerTypeMapper.cs) class?
```
private readonly RelationalTypeMapping _geography = new RelationalTypeMapping("geography");
private readonly RelationalTypeMapping _geometry = new RelationalTypeMapping("geometry");
```
**Did some testing, and it go very deep into the core ** :sweat_smile: skiming guess, its going to take a few 100 manhours base on my skills

**Comment by gitmar** [comment]
Fail to try scaffolding a xml sql datatype and fail to manually add the property in my model. Dont know how to do that.
'Could not find type mapping for column 'dbo.table1.xmlcolumn' with data type 'xml'. Skipping column.'

**Comment by lajones** [comment]
Have checked in a fix for xml columns (@gitmar this should solve your problem above) - commit a8b185f.

**Comment by lajones** [comment]
Support for hierarchyId and spatial types is more complicated and not yet supported by the update and query pipelines. So closing this in favor of #365 (which tracks hierarchyid) and #1100 (which tracks support for spatial types).
