### ISSUE TITLE
ContainsTranslater support for more than strings

### ISSUE THREAD

**Issue by matthewDDennis** [aspnet/EntityFramework#3078]
The `ContainsTranslator` only implements string.Contains(string), not T[].Contains(T).
The later should map to a condition on a `Where' similar to`x in (v1, v2, v3, v4)

Probably need two classes, `StringContainsTranslator` and `ArrayContainsTranslator`.

Currently, attempting a query with `.Where(x => (new int[]{1,2,3]).Contains(x.State))` results in truncated SQL query.  In my case, removed the `.Skip(...).Take(...)` portion of the query and a sql command timeout due to the size of the response - about 1,000,000 rows :(

**Comment by matthewDDennis** [comment]
Similarily,`Where(x => (new int[]{1,2,3}).Any(I => I == x.state))`  should translate to an  `In` clause, or a very verbose `Where` clause

**Comment by matthewDDennis** [comment]
@rowanmiller do you have some guidance on creating/adding translaters.  I think I have it figured out, but want to make sure before digging in.  
Also, so you have a list of expressions/methods the need to be implemented?

**Comment by smitpatel** [comment]
This may be already working.

**Comment by smitpatel** [comment]
Contains is already working. Filed #9149 for Any
