### ISSUE TITLE
Query: Patterns for query-level behavior modifiers

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#3080]
By design, on a query with multiple roots the `AsNoTracking()` method only affects the roots to which it is applied. E.g. given the following query:

``` C#
from p in db.People.AsNoTracking()
from t in db.Things
where p.Id == t.OwnerId
select new { Person = p, Thing = t };
```

Its results will contain instances from both People and Things zipped together, but while _things_ will be tracked by the context _persons_ will not. 

We go a long way to make sure that `AsNoTracking()` doesn't spread to the whole query in a case like that. E.g.: no navigation property fix-up can happen between instances that are tracked and instances that are not, e.g. if Thing declared an Owner property of type Person, it wouldn't be populated in the results of this query. This has to be the case to avoid retuning a graph that would be in an inconsistent or unstable state, i.e. that would result in objects on states different from `Unchanged` to be detected on a call to `DetectChanges()` or similar APIs.

We now have other behavior modifying `IQueryable<T>` operators under consideration, such as the one that opts in relational null semantics and the one that would be used to opt-in client-side evaluation once it is disabled on the context (see #1856). 

For some of these methods it becomes increasingly harder to honor the contract that the method affect individual roots. E.g. what null semantics would be in effect for the equality comparison in the predicate of this query?
``` C#
from p in db.People.UsingRelationalNull()
from t in db.Things
where p.Id == t.OwnerId
select new { Person = p, Thing = t };
```
__Complexity is pushing us to question the value of having these methods affect only query roots they are applied to and to find a pattern that can apply to the whole query.__ 

Most of the options we have discussed so far fall into one of two buckets:

1. Change how the pattern looks like, i.e. remove the extension methods on `IQueryable<T>` and come up with an entirely new pattern. 

2. Keep the pattern the same but adjust the semantics: 

 1. We could enforce at runtime that for queries with multiple roots the method needs to be invoked on the whole query (i.e. queries that apply the method to individual roots would become invalid and would start causing exceptions), e.g.:
   ``` C#
   (from p in db.People
    from t in db.Things
    where p.Id == t.OwnerId
    select new { Person = p, Thing = t }).AsNoTracking();
   ```

 2. Define that by convention the behavior modifiers applied to the root used to boostrap the query will affect the whole query, e.g. for they following query, both people and things would be no tracking (most likely closer to what would happen in EF6):
   ``` C#
   from p in db.People.AsNoTracking()
   from t in db.Things
   where p.Id == t.OwnerId
   select new { Person = p, Thing = t };
   ```
 But the following query would now become an invalid usage case for `AsNoTracking()`:
   ``` C#
   from p in db.People
   from t in db.Things.AsNoTracking()
   where p.Id == t.OwnerId
   select new { Person = p, Thing = t };
   ```
  In fact, we would need to decide whether this should:
    1. Cause an exception (probably better)
    2. Cause `AsNoTracking()` to be ignored

**Comment by ilmax** [comment]
If I can add my voice to this issue, I would love to turn entity tracking off at DbContext level and drop the AsNoTracking method. The rationale behind this move IMO is that we usually (or at least me) separate read from store (CUD) operations. Typically (most of the time) the performance sensitive operations are reads, not the stores, so I would love to turn query tracking completely off on the read context, and leave it on in the store context.

**Comment by divega** [comment]
@ilmax thanks for the feedback!

Retrieving a graph of entities with a DbContext with no-tracking queries and then attaching it to another DbContext so that changes are tracked before you call `SaveChanges()` can become complex. 

It seems that in the scenario it would be simpler to tackle with a single DbContext in which queries are no-tracking by default (hence the majority of queries don't track) but in which you can explicitly ask for specific objects to be retrieved with tracking enabled. 

This is at a high level very similar to what @anpete proposed in our [design meeting on August 6, 2015](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes---August-6,-2015). We decided to enable something like that with the caveat that you need to opt in. I.e. while we are not dropping `AsNoTracking()`, we decided to have a context level property controlling the default behavior for queries. See our  and the bug #134 @anpete just filed for more detils.

**Comment by poke** [comment]
A global property to configure the tracking behavior at context level is definitely a good idea. However, I would like to ask for a way to do this on a entity-level.

In contexts, I often have entities that are there just for read-only purposes. So I disable tracking for them by exposing only `Set<T>().AsNoTracking()` instead of the whole DbSet. As such, a query like the first on in 2.ii. above would fail because `db.Things` might be a non-tracking IQueryable all the time.

Maybe a simple `modelBuilder.Entity<T>().WithTracking(QueryTrackingBehavior.NoTracking)` would work here. That way we get a configuration that applies to everything of type `T` in that context.

**Comment by ilmax** [comment]
@divega I think that detaching and attaching graphs are a widespread scenario IMO, anyway the ability to turn off query tracking at the context level will be a welcome addition!

I like what @poke proposed, in general I would love to "configure graphs" at application startup, and then use the context without any additional tweak most of the time, but this is another story ;)

**Comment by divega** [comment]
@anpete Do I remember correctly that we are done with this one too? I am happy to keep it open if there is any subtle detail we still need to decide on but currently it isn't clear what that would be. Maybe we should do some exploratory testing?

cc @rowanmiller

**Comment by anpete** [comment]
@divega to confirm behavior is good.

**Comment by poke** [comment]
Is there any issue that describes what was done in order to complete this, so we know how to use it?

**Comment by ilmax** [comment]
@rowanmiller any details about this? Is it implemented, or rejected?

**Comment by divega** [comment]
@ilmax The behavior implemented is that for queries that have different roots with different tracking settings, the last one will win.

**Comment by ilmax** [comment]
@divega thank you
