### ISSUE TITLE
Update Pipeline: General review of factoring

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#3084]
During API Review there were a number of questions about whether the Update Pipeline is well factored. One of the folks working on Update Pipeline should spend some time looking at this. Because this is provider API the high order bit is that we make it easy for providers.

**Comment by AndriySvyryd** [comment]
The factoring looks ok now. It will likely change if we add support for TPT, table or entity splitting, but that would be provider breaking changes anyway.
