### ISSUE TITLE
Query: Perf slow on first couple of warm iterations

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#3088]
When running the same query multiple times against the same database we would expect the first (a.k.a cold) query to be slow and then the timing to be consistent for subsequent iterations (provided the ADO.NET components are consistent)

However, given the following code:

```c#
using Microsoft.Data.Entity;
using System;
using System.Diagnostics;
using System.Linq;

namespace FirstPerf
{
    class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < 20; i++)
            {
                using (var context = new OrdersContext())
                {
                    var timer = new Stopwatch();
                    timer.Start();
                    var prod = context.Products.Count();
                    timer.Stop();

                    Console.WriteLine($"Iteration{i}: {timer.ElapsedMilliseconds}ms");
                }
            }
        }
    }

    public class OrdersContext : DbContext
    {
        public DbSet<Product> Products { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var sqlBuilder = optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Perf_Query_Simple;Integrated Security=True;MultipleActiveResultSets=true;");
        }

    }

    public class Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public decimal Retail { get; set; }
    }
}
```

I am consistently seeing results similar to the listing below. As expected the first iteration is slower, but then the next few iterations show intermediate numbers and then fast numbers begin around iteration 4-6.

> Iteration0: 945ms
Iteration1: 37ms
Iteration2: 15ms
Iteration3: 19ms
Iteration4: 17ms
Iteration5: 13ms
Iteration6: 1ms
Iteration7: 1ms
Iteration8: 1ms
Iteration9: 1ms
Iteration10: 1ms
Iteration11: 1ms
Iteration12: 2ms
Iteration13: 2ms
Iteration14: 1ms
Iteration15: 1ms
Iteration16: 2ms
Iteration17: 1ms
Iteration18: 1ms
Iteration19: 2ms

Profiling shows that the variation is accounted for in `DbCommand.ExecuteReader()`. In the following profiled run the speed up happened on iteration 6. Note that the method tree doesn't quite match the above listing as I modified it to help isolate the profile for each iteration.
![iteration3](https://cloud.githubusercontent.com/assets/4741851/9776446/308ae910-570d-11e5-88f0-83da0fb2883b.png)
![iteration6](https://cloud.githubusercontent.com/assets/4741851/9776447/308f87c2-570d-11e5-82fd-7b354d9e7177.png)

This few iterations with intermediate perf does not seem to be consistent with the behavior of SQL Client. The following code uses the same query and connection string that EF uses and measures just the `ExecuteReader` call (which is what showed the difference in profiling).

```c#
using System;
using System.Data.SqlClient;
using System.Diagnostics;

namespace FirstPerf
{
    class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < 20; i++)
            {
                using (var conn = new SqlConnection(@"Server=(localdb)\mssqllocaldb;Database=Perf_Query_Simple;Integrated Security=True;MultipleActiveResultSets=true;"))
                {
                    var timer = new Stopwatch();

                    var cmd = conn.CreateCommand();
                    cmd.CommandText = "SELECT COUNT(*) FROM [Product] AS [p]";
                    conn.Open();

                    timer.Start();
                    var result = cmd.ExecuteReader();
                    timer.Stop();

                    result.Read();
                    var count = result.GetInt32(0);
                    conn.Close();

                    Console.WriteLine($"Iteration{i}: {timer.ElapsedMilliseconds}ms");
                }
            }
        }
    }
}
```

The following are consistent results that I am seeing. First iteration is slower, all subsequent ones are fast.

> Iteration0: 8ms
Iteration1: 0ms
Iteration2: 0ms
Iteration3: 0ms
Iteration4: 0ms
Iteration5: 0ms
Iteration6: 0ms
Iteration7: 0ms
Iteration8: 0ms
Iteration9: 0ms
Iteration10: 0ms
Iteration11: 0ms
Iteration12: 0ms
Iteration13: 0ms
Iteration14: 0ms
Iteration15: 0ms
Iteration16: 0ms
Iteration17: 0ms
Iteration18: 0ms
Iteration19: 0ms

I adjusted the query to something more complex (`SELECT * FROM [Product] AS [p] ORDER BY [Name]`) to ensure that there wasn't a difference getting lost in the 0ms, and the results are consistent with one slow execution and then the rest are fast.

> Iteration0: 16ms
Iteration1: 5ms
Iteration2: 6ms
Iteration3: 5ms
Iteration4: 5ms
Iteration5: 4ms
Iteration6: 5ms
Iteration7: 5ms
Iteration8: 6ms
Iteration9: 6ms
Iteration10: 5ms
Iteration11: 7ms
Iteration12: 6ms
Iteration13: 7ms
Iteration14: 6ms
Iteration15: 4ms
Iteration16: 6ms
Iteration17: 5ms
Iteration18: 4ms
Iteration19: 5ms

**Comment by rowanmiller** [comment]
Here is the test case I was using for profiling to help isolate the profile for each iteration

```c#
using Microsoft.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using Xunit;

namespace EntityFramework.Microbenchmarks.Cache
{
    class WarmupProfile
    {
        [Fact]
        public void Test()
        {
            Run1();
            Run2();
            Run3();
            Run4();
            Run5();
            Run6();
            Run7();
            Run8();
            Run9();
        }

        private void Run1() { RunTest(); }
        private void Run2() { RunTest(); }
        private void Run3() { RunTest(); }
        private void Run4() { RunTest(); }
        private void Run5() { RunTest(); }
        private void Run6() { RunTest(); }
        private void Run7() { RunTest(); }
        private void Run8() { RunTest(); }
        private void Run9() { RunTest(); }

        private void RunTest()
        {
            using (var context = new OrdersContext())
            {
                context.Products.Count();
            }
        }

        private void RunTestSql()
        {
            using (var conn = new SqlConnection(@"Server=(localdb)\mssqllocaldb;Database=Perf_Query_Simple;Integrated Security=True;MultipleActiveResultSets=true;"))
            {
                var cmd = conn.CreateCommand();
                cmd.CommandText = "SELECT COUNT(*) FROM [Product] AS [p]";

                conn.Open();
                var result = cmd.ExecuteReader();
                result.Read();
                var count = result.GetInt32(0);
                conn.Close();
            }
        }
    }

    public class OrdersContext : DbContext
    {
        public DbSet<Product> Products { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var sqlBuilder = optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Perf_Query_Simple;Integrated Security=True;MultipleActiveResultSets=true;");
        }

    }

    public class Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public decimal Retail { get; set; }
    }
}
```

**Comment by whyi** [comment]
Can please you provide with some sample data in Perf_Query_Simple to try your code?

**Comment by rowanmiller** [comment]
You can put any data in the table to see it. The database I was using had 1000 entries (it's the database from the benchmark tests that are checked into our source code).

**Comment by rowanmiller** [comment]
Closing as this seems to be happening in ADO.NET and we have not been able to isolate what is causing it. The overhead is minimal, so it's not worth investing the time to get to the bottom of.

**Comment by whyi** [comment]
adding @lukewaters to keep him in the loop.
