### ISSUE TITLE
Perf: ModelBuilder bottleneck in ConventionDispatcher.OnEntityTypeAdded

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#3097]
Test `EntityFramework.Microbenchmarks.InitializationTests.BuildModel_AdventureWorks` takes around 3x longer than the EF6 equivalent. Over half the CPU time of the timed section of the test is spent in `ConventionDispatcher.OnEntityTypeAdded`

![profile](https://cloud.githubusercontent.com/assets/4741851/9801053/925e9d18-57c5-11e5-8f2c-d15538ba63b5.png)

The call stacks get very deep, but if you drill down through the call stack shown in the profile and then another branch that accounts for another chuck of the time in the test then they both have `RelationshipDiscoveryConvention.Apply` in the stack and adding up the numbers gives ~75% of time spent in that method. Of course, they keep going much deeper than that, so it's more complex than just optimizing the body of that method.

**Comment by davezych** [comment]
I'm having similar performance issues that I have traced back to `ConventionDispatcher.OnEntityTypeAdded`/`RelationshipDiscoveryConvention.Apply`. I have an existing database with entities that were generated using the scaffolder and there are ~400 entities with a lot of relationships defined between them - Some one-to-one's but mostly one-to-manys. With this many relationships the instantiation of the context won't complete - I've let it run for 45 minutes and it pegs the CPU but never completes. 

I can upload a Dottrace snapshot if it would be helpful.

**Comment by rowanmiller** [comment]
@davezych any chance you can share that model? We're always on the look out for decent sized real world models that we can use for benchmarking (things we concoct are never as good as real world scenarios).

I don't think we need the profile just yet as it's pretty easy to identify the bottleneck. This is good data though and we'll get you to retry when we get this resolved.

**Comment by davezych** [comment]
@rowanmiller sorry, I would love to share the model but it's for an internal ERP at my company and too sensitive to share. 

Any time you make progress on this let me know and I'll test it out and provide any useful results/information I can.

Out of curiosity, do you have a rough ETA for this? A week, or month, or...?

**Comment by rowanmiller** [comment]
@davezych totally understand... that is the case for most folks with interesting models :smile: 

I don't have an exact timeline, but this is a pretty significant bottleneck so addressing it will be high priority.

**Comment by rowanmiller** [comment]
@AndriySvyryd this should be your highest priority item :smile:

**Comment by rowanmiller** [comment]
@davezych can you retry on the latest builds? We are now seeing significant improvement in our benchmarks

**Comment by davezych** [comment]
@rowanmiller using the latest beta8 and it's definitely much faster. :+1:

**Comment by rowanmiller** [comment]
@davezych great, thanks
