### ISSUE TITLE
Route all statement execution through ISqlStatementExecutor

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#3110]
From API review: "Everything should be routed thru here. Move logic from here to RelationalCommand."

**Comment by mikary** [comment]
The `SqlStatementExecutor` disposes `DbCommand`s and closes the connection before the `DbDataReader` can be consumed.
- Update pipeline uses a `Consume(DbDataReader)` pattern that could be provided as an `Action<T>` allowing the executor to control the life-cycle of the ADO objects
- Query
 - Requires a streaming / lazy reader, calling `Dispose` and closing connection outside of the executor
 - Reads need to be performed by an `IValueBufferFactory` to ensure proper typed / untyped reads occour
   - In `FromSql` case, requires access to `DbDataReader` before `IValueBufferFactory` can be constructed
