### ISSUE TITLE
Refactor RelationalCommand and its builder

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#3112]
From API review:  Remove RelationalParameter and just have RelationalCommand take a RelationalParameterList. 

Also, if it still matters after the above is done, RelationalCommand should not use a "params" parameter.

**Comment by mikary** [comment]
Removed the `RelationalParameterList` and changed the "params" constructor. I think the new factoring should satisfy the intent of this issue
- [ ] API review required

**Comment by rowanmiller** [comment]
@mikary can this be closed now?

**Comment by mikary** [comment]
Changes are done other than API review changes, I think this issue is fine to close at this point.
