### ISSUE TITLE
Naming nitpicking: rename cross apply to lateral join

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#3118]
CROSS APPLY is an SQL Server-specific syntax, but SQL:1999 has lateral joins. You may want to consider renaming cross apply to lateral join (I'm referring to the expression class, methods...)

**Comment by rowanmiller** [comment]
@anpete @divega thoughts on this one?

**Comment by rowanmiller** [comment]
@roji we would take a PR on this, but it would need to be in before RTM

**Comment by roji** [comment]
Closed via #3276
