### ISSUE TITLE
Where on navigation property throws InvalidOperationException

### ISSUE THREAD

**Issue by marrrcin** [aspnet/EntityFramework#3119]
I'm currently on beta7, I have the following model:
```
 public class Post
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { set; get; }

        public virtual PublishingOptions PublishingOptions { set; get; }
}

public class PublishingOptions
    {
        public bool CommentsAllowed { set; get; }

        public bool VotesAllowed { set; get; }

        public bool SharingAllowed { set; get; }

        public DateTime? LastPublished { set; get; }

        [Key]
        public long Id { set; get; }

        public virtual Post Post { set; get; }

}

```

DbContext:

```
 public class DbContext : IdentityDbContext<BlogUser>
 {
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            var postEntity = modelBuilder.Entity<Post>();
            postEntity.Reference(p => p.PublishingOptions).InverseReference(po => po.Post);
            postEntity.ToTable("Posts");

            var pOpt = modelBuilder.Entity<PublishingOptions>().ToTable("PublishingOptions");
            pOpt.Reference(po => po.Post).InverseReference(post => post.PublishingOptions);


          }

        public DbSet<Post> Posts { get; set; }

        public DbSet<PublishingOptions> PublishingOptions { get; set; }
}
```

As you can see in PublishingOptions, LastPublished is nullable. Now, I try to perform query like this:

```
//Database is instance of DbContext
var query = from p in Database.Posts.Include(p=>p.PublishingOptions)
                where p.PublishingOptions.LastPublished == null
                select p;
```

or 

```
var query = from p in Database.Posts.Include(p=>p.PublishingOptions)
                where p.PublishingOptions.LastPublished != null
                select p;
```

or even

```
var query = from p in Database.Posts.Include(p=>p.PublishingOptions).UseRelationalNullSemantics()
                where p.PublishingOptions.LastPublished == null
                select p;
```
What's even worse, this one does not work too (so it's probably not caused by nullable property):
```
IQueryable<Post> query =
                Database.Posts.Include(p => p.PublishingOptions).Where(p => p.PublishingOptions.CommentsAllowed == true);
```

After every query in my methods, I've called ```return query.ToList();```

The exception I got from every similiar query is:
```
InvalidOperationException: The EF.Property<T> method may only be used within LINQ queries.
w Microsoft.Data.Entity.EF.Property[TProperty](Object entity, String propertyName)

//top of stacktrace:

w Microsoft.Data.Entity.EF.Property[TProperty](Object entity, String propertyName)
w lambda_method(Closure , QueryResultScope )
w System.Linq.Enumerable.<JoinIterator>d__1`4.MoveNext()
w System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
w Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by gabrielgreen** [comment]
I'm getting this too...

**Comment by marrrcin** [comment]
Is this under investigation? Could anyone from the team comment on this?

**Comment by divega** [comment]
@marrrcin Is this the full repro? @gabrielgreen too, are you sure that you are not using the `EF.Property()` method anywhere in your code? 

This seems bizarre, because [we are only throwing that exception from within the body of the method](https://github.com/aspnet/EntityFramework/search?utf8=%E2%9C%93&q=PropertyMethodInvoked) (at least currently). 

Also, would it be possible for you to try more recent bits? Some parts of navigation property translation (which your queries exercise) was only added after beta7.

**Comment by divega** [comment]
Moving to rc1, as there are two reports and this seems like something we need to get to the bottom of.

**Comment by divega** [comment]
I was able to figure out why we would ever see that exception: In [`NavigationRewritingExpressionVisitor`](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/Query/ExpressionVisitors/NavigationRewritingExpressionVisitor.cs#L354) we happen to create expressions that invoke `EF.Property<T>()`. However those are supposed to be either translated in the store query or transformed once more into access to the value buffer if evaluated in memory. 

In theory if we don't do the latter correctly you could end up getting that exception. I haven't been able to repro using either beta7 or our current bits so I am going to assume that we only had a temporary bug that is already fixed. Feel free to reopen the issue if you can still repro this in current or later bits.

**Comment by divega** [comment]
Here is the repro code I used with beta8 bits in case it helps:

``` C#
using System;
using System.Linq;
using System.Data.SqlClient;
using Microsoft.Data.Entity;

namespace Repro3119
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            using (var context = new MyDbContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                (from p in context.Posts.Include(p => p.PublishingOptions)
                    where p.PublishingOptions.LastPublished == null
                    select p).Load();

                (from p in context.Posts.Include(p => p.PublishingOptions)
                    where p.PublishingOptions.LastPublished != null
                    select p).Load();

                (from p in context.Posts.Include(p => p.PublishingOptions)
                    where p.PublishingOptions.LastPublished == null
                    select p).Load();

                context.Posts.Include(p => p.PublishingOptions).Where(p => p.PublishingOptions.CommentsAllowed == true).Load();
            }
        }
    }


    public class Post
    {
        public long Id { set; get; }
        public virtual PublishingOptions PublishingOptions { set; get; }
    }

    public class PublishingOptions
    {
        public long Id { set; get; }
        public bool CommentsAllowed { set; get; }
        public bool VotesAllowed { set; get; }
        public bool SharingAllowed { set; get; }
        public DateTime? LastPublished { set; get; }
        public virtual Post Post { set; get; }

    }

    public class MyDbContext : DbContext
    {

        public DbSet<Post> Posts { get; set; }

        public DbSet<PublishingOptions> PublishingOptions { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                new SqlConnectionStringBuilder
                {
                    DataSource = "(localdb)\\mssqllocaldb",
                    InitialCatalog = "Repro3119"
                }.ToString());
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Post>(
                entity =>
                {
                    entity.HasOne(p => p.PublishingOptions).WithOne(po => po.Post);
                    entity.ToTable("Posts");
                });

            modelBuilder.Entity<PublishingOptions>(
                entity =>
                {
                    entity.ToTable("PublishingOptions");
                    entity.HasOne(po => po.Post).WithOne(post => post.PublishingOptions);
                });
        }
    }
}
```

**Comment by ruicraveiro** [comment]
I didn't deal with this bug on Beta7, but I'm afraid I'm facing it now in Beta8:
The following query is not working:

            var query = DbContext.Employees
                .Include(p => p.Worksheets)
                .Where(p => p.IsActive);
            if (name != null)
                query = query.Where(p => p.Name.Contains(name));
            if (erpNumber != null)
                query = query.Where(p => p.ERPNumber == erpNumber.Value);

            if (requestedPage.RequestMode == EmployeeWithWorksheetRequestMode.DriversWithMissingWorksheet)
                query = query.Where(p => !p.Worksheets.Any(q => 
                        q.EmployeeId == p.Id && q.Year == requestedPage.Year && q.Month == requestedPage.Month));
            return query;

The exception is: InvalidOperationException: The EF.Property<T> method may only be used within LINQ queries.

The workaround I found (still didn't validate if it is efficient) was:
    ....
                query = query.Where(p => DbContext.Worksheets.FirstOrDefault(q => 
                        q.EmployeeId == p.Id && q.Year == requestedPage.Year && q.Month == requestedPage.Month) == null);
            return query;

Now it works, but I think it should be supposed to do the query that way.

Cheers!

**Comment by divega** [comment]
FYI, we are using #3029 (which is still open) to track the issue now.
