### ISSUE TITLE
Migrations: Operations for annotation changes on model and entity type

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#3122]
EF7 allows adding provider-specific traits to various entities - SqlServer has `Clustered` indices for example.

Does the migrations model differ handle alterations in such provider-specific traits, e.g. if an index becomes `Clustered`? I have no idea if this kind of change is actually supported in SqlServer, but I definitely have some examples of PostgreSQL-specific traits that can be altered (e.g. a table's tablespace).

**Comment by bricelam** [comment]
If you provide [an implementation of `MigrationsAnnotationProvider`](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.SqlServer/Migrations/SqlServerMigrationsAnnotationProvider.cs), those annotations will be diffed.

You will run into one issue, however: We don't currently have an `AlterTableOperation` to capture changed annotations on the entity type level.

**Comment by roji** [comment]
That's good news, thanks @bricelam. Do you mean that for anything other than table (e.g. column) I can access the annotations diff? Could you point out how that's done (am not seeing anything like that in MigrationOperation, Annotatable...)

**Comment by bricelam** [comment]
You won't get a diff, but you'll get an alter operation with the new value.

**Comment by roji** [comment]
OK, thanks for the clarification. Getting just the new value is insufficient for at least some cases - the old value may be necessary to generate the alteration SQL etc.

Just want to stress this isn't a critical issue or anything (definitely not RTM), just raising this so it's treated at some point.

**Comment by bricelam** [comment]
Retrieving the old value could be enabled by #1911

**Comment by bricelam** [comment]
Closing since I think the the work for this is already tracked by #1911.

**Comment by bricelam** [comment]
FYI, @roji, @AndriySvyryd is going to add `AlterDatabase` and `AlterTable` operations that will be generated when annotations on the model and entity types are changed.

I'm going to re-open this issue since it's a new feature that just happens will get implemented as part of #6405.

**Comment by bricelam** [comment]
Note: The old annotations are now also available on `AlterColumnOperation`.
