### ISSUE TITLE
Better exception message for circular dependency in FK cycle

### ISSUE THREAD

**Issue by TheMadKow** [aspnet/EntityFramework#3147]
Hi, 
Working with the new dnx-clr-win-x86.1.0.0-Beta7.

I'm getting the following message : 
InvalidOperationException: A circular dependency was detected: 'Schema' {'FutureId'} -> 'Occurrence' {'ID'}, 'Occurrence' {'SchemaID'} -> 'Schema' {'ID'}, 'OccurrenceHistory' {'OccurrenceID'} -> 'Occurrence' {'ID'}.

Where classes architecture is :
- Schema holds all Occurrences under "OccurrenceHistory" enumerable.
- Schema holds Future instance of the occurrence.
- Schema holds Past instance of that occurrence.
(that is, future is the next link in the chain, and past is the previous link in the chain. the history refers to all links whatsoever)

So, i'm not so sure why i get this error, it should work (unless i'm missing something), 
it worked on Beta6 but had some other issues, where it wasn't able to load the Future item with .Include.

Thanks,
Eliran.

**Comment by smitpatel** [comment]
It looks like the relationships are not configured correctly. Can you share your domain classes and modelbuilder configuration?

**Comment by TheMadKow** [comment]
Yeah, Sure... 
I've uploaded the classes to this Dropbox folder : https://www.dropbox.com/sh/sadxtas4m0a2c1h/AAB2hSoCK5c-8hBlYbLN8YPKa?dl=0

Thank you,

**Comment by smitpatel** [comment]
@TheMadKow - thanks for files. I looked into `Schema.cs` & `Occurrence.cs` files. Since `Schema.cs` has 3 navigation properties of type `Occurrence` convention should not be creating relationships between them. Are you configuring the relationship using modelbuilder? If yes, then please share your db context code.

**Comment by TheMadKow** [comment]
@smitpatel , Adding those right now to the drive. 
(Sorry for the delay, different time zones :))

There are two parts : 
* DataBuilderBase (and all related there), which actually handles the build.
* ApplicationContext (the original call-maker).

Also attached all migrations created by "dnx ef" to this point, under "Migrations" subfolder.

This is the relevant part of the builder, regarding Schema and Occurrence :
>
   public class PostitsDataBuilder : DataBuilderBase
    {
        public override void BuildWith(ModelBuilder builder)
        {
            builder.Entity<Schemahistory>(e =>
            {
                HistoryCommonFields(e);
                e.Property(c => c.SchemaID).Required();
            });

            builder.Entity<OccurrenceHistory>(e =>
            {
                HistoryCommonFields(e);
                //e.Property(c => c.OccurrenceID).Required();
            });

            builder.Entity<Schema>(e =>
            {
                e.Key(c => c.ID);
                e.Property(c => c.DepartmentId).Required();
                e.Property(c => c.CreationUTC).Required();
                e.Property(c => c.CreatorId).Required();
                e.Property(c => c.What).Required();
                e.Property(c => c.WhoId).Required();
                e.Ignore(c => c.Last);

                // Indexes 
                e.Index(c => c.CreationUTC);
            });

            builder.Entity<Occurrence>(e =>
            {
                e.Key(c => c.ID);
                //TODO e.Property(c => c.SchemaID).Required();
                e.Property(c => c.InstanceUTC).Required();
                e.Property(c => c.Instance).Required();
                e.Property(c => c.IsSticky).Required();
                e.Ignore(c => c.Last);
            });

            builder.Entity<SchemaTag>(e =>
            {
                e.Key(c => c.ID);
                e.Property(c => c.TagId).Required();
                e.Property(c => c.SchemaId).Required();
            });

        }
    }

**Comment by rowanmiller** [comment]
@smitpatel feel free to clear up Milestone field if you want us to re-evaluate once you investigate

**Comment by smitpatel** [comment]
@TheMadKow - Thanks for the detailed info. From the code of model builder it looks like you are not configuring any relationship explicitly. That means all the relationship will be formed by conventions only based on the navigation properties defined.

Based on description you provided about `Schema.cs` and `Occurrence.cs`, the classes would look like following
````
public class Schema 
{
    // Other properties

    // stores past instance
    public Occurrence Past { get; set; }

    // stores future instance
    public Occurrence Future { get; set; }

    // stores all occurrences
    public List<Occurrence> Occurrences { get; set; }
}

public class Occurrence
{
    // Other properties
}
````
Model generated with above classes is perfectly valid and should not be giving any exceptions. Furthermore the exception message for the error does not represent cycle in foreign keys. Therefore error may not be only in relationships between Schema and Occurrence. It seems that either cycle detection is not working correctly or the error message needs to be improved.

If you can provide a repro project that would be very helpful otherwise can you give some steps to repro the exception. i.e. Are you seeing error when generating migration? or migration is generated successfully (and the ModelSnapshot you provided corresponds to that) but at runtime the exception is thrown? Or you need to modify some property in the model to get the exception?

**Comment by TheMadKow** [comment]
@smitpatel , Hey,
Sorry for not including this info - the error is only at run time, when trying to create a new Schema and attach an occurrence, under "await AppContext.SaveChangesAsync()".

I'm entering partial code again.


        public async Task<IActionResult> Create(CreateUpdatePostit model)
        {
            Logger.LogInformation($"User {AppUser().FullName} requested to CREATE Post-it {model.ID}");
            var assingee = AppContext.Users.FirstOrDefault(x => x.Id == model.WhoId);
            
            if (assingee == null || !ModelState.IsValid)
            {
                @ViewBag.Message = "Create new Post-it";
                @ViewBag.Title = "Create New";
                model.PopulateData(this, DataItems.AppUser | DataItems.Departments);
                return View(model);
            }

            CreateHelper(assingee, model);
            var uRes = await AppContext.SaveChangesAsync();
            return RedirectToAction("ByMe", "Postits", uRes > 0 
                ? new { msg = "Successfully create the Post-it", msgType = "success" } 
                : new { msg = "Failed to create the Post-it", msgType = "fail" });
        }


        private Schema CreateHelper(ApplicationUser user, CreateUpdatePostit model)
        {
            var schema = model.CreateSchema();
            schema.WhoString = user.FullName;

            var cUser = AppUser();
            schema.CreatorId = cUser.Id;
            schema.CreatorName = cUser.FullName;
            schema.CreationUTC = DateTime.UtcNow;
            schema.IsRepeat = schema.When(cUser.Preferences.DateType).IsRepeat;

            schema.Last = HistoryActionType.Created;
            var history = new Schemahistory()
            {
                User = cUser,
                WhenUTC = DateTime.UtcNow,
                What = HistoryActionType.Created.TranslateToHistory(AppContext)
            };

            schema.History.Add(history);
            var occr = OccurrenceBuilder.BuildNext(schema, null, cUser.Preferences.DateType, cUser.Location.TimeZone);
            schema.Occurrences.Add(occr);
            var occrHistory = new OccurrenceHistory()
            {
                User = cUser,
                WhenUTC = DateTime.UtcNow,
                What = HistoryActionType.Opened.TranslateToHistory(AppContext),
            };
            occr.History.Add(occrHistory);

            AppContext.OccurrenceHistory.Add(occrHistory);
            AppContext.Occurrences.Add(occr);
            AppContext.SchemaHistory.Add(history);

            schema.FutureId = occr.ID;
            AppContext.Schemas.Add(schema);
            //TODOoccr.SchemaID = schema.ID;

            schema.Tags = new List<SchemaTag>();
            foreach (var tag in model.TagsLine.SplitCsv())
            {
                var tagitem = AppContext.Tags.FirstOrDefault(x => x.ID.CompareToString(tag));
                var schemaTag = new SchemaTag
                {
                    SchemaId = schema.ID,
                    Schema = schema,
                    Tag = tagitem
                };

                if (tagitem != null)
                {
                    tagitem.LastUsed = DateTime.UtcNow;
                    AppContext.Tags.Update(tagitem);
                }

                schema.Tags.Add(schemaTag);
                AppContext.SchemaTags.Add(schemaTag);
            }

            return schema;
        }

**Comment by smitpatel** [comment]
@TheMadKow  - Since migrations/context creation is working fine, model looks perfectly valid. Error coming at `SaveChangesAsync()` means the cycle is being formed by in entities being added.
I have created a standalone repro for this.
- Schema has list of all occurrences
- Schema has navigation to future occurrence

In the code new Schema & Occurrence are being created. ForeignKey properties for above relationships build a cycle therefore exception will be thrown.

Though exception message is not proper since it does denote the proper info on cycle and should be improved.

**Comment by smitpatel** [comment]
Cleared milestone for re-triage since investigation is done.

**Comment by TheMadKow** [comment]
@smitpatel  Thanks for the kind reply, i'll try to figure this one out, and what i did wrong.

**Comment by rowanmiller** [comment]
We need to improve the message making it clear that it is instance data causing the cycle (not schema/model)

**Comment by smitpatel** [comment]
with ac8336776521b8997d01f3a4b3274792e12ee47d now this exception arises only with instance data and not with schema/model.

**Comment by smitpatel** [comment]
@rowanmiller - Is there anything to be done in this now?

**Comment by rowanmiller** [comment]
@smitpatel looks like the exception message still doesn't make it clear that the cycle is in the data and not in the schema/model. Currently the message is something like:

> A circular dependency was detected: 'Schema' {'FutureId'} -> 'Occurrence' {'ID'}, 'Occurrence' {'SchemaID'} -> 'Schema' {'ID'}, 'OccurrenceHistory' {'OccurrenceID'} -> 'Occurrence' {'ID'}.

I think it should be something like

> Unable to save changes because a circular dependency was detected in the data to be saved: 'Schema' {'FutureId'} -> 'Occurrence' {'ID'}, 'Occurrence' {'SchemaID'} -> 'Schema' {'ID'}, 'OccurrenceHistory' {'OccurrenceID'} -> 'Occurrence' {'ID'}.
