### ISSUE TITLE
Re-enable Shadow Keys

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#3156]
These were disabled by #1621. Both @rowanmiller and I have found them very useful.

**Comment by divega** [comment]
:+1: They can be a pretty decent workaround for the lack of complex type support if you only care about how the object model looks like as opposed to the database schema.

**Comment by AndriySvyryd** [comment]
We should still throw/log a warning for shadow keys created by convention, since it's very easy to unintentionally do when configuring a relationship

**Comment by divega** [comment]
Sounds good.

**Comment by rowanmiller** [comment]
Yeah I don't think we should create them by convention, we should still throw if no key is found

**Comment by smitpatel** [comment]
At present shadow-keys are allowed in the model. `ModelValidator` logs a warning for shadow keys.
I will be making changes to block shadow-keys created by convention.
