### ISSUE TITLE
Query: Test SelectMany_Joined_Take() generates unexpected SQL with SQL CE provider

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#3158]
For the SQL CE provider. the SQL below is generated

    SELECT [c].[CustomerID], [c].[ContactName]
    FROM [Customers] AS [c]

    SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
    FROM [Orders] AS [o]

    SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
    FROM [Orders] AS [o]

    SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
    FROM [Orders] AS [o]

    SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
    FROM [Orders] AS [o]

    SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
    FROM [Orders] AS [o]

    SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
    FROM [Orders] AS [o]

    (and on and on 1000 times!)

In my SqlCeQueryCompilationContext I have: 

    public override bool IsCrossApplySupported => true;

What can I be doing wrong?

**Comment by rowanmiller** [comment]
@anpete any thoughts on this one?

**Comment by anpete** [comment]
Had a quick look and couldn't see anything obvious. Might need to debug it.

**Comment by ErikEJ** [comment]
@anpete  Now get same pattern with Where_query_composition4() !

**Comment by rowanmiller** [comment]
@ErikEJ we have a pretty big backlog of things to investigate, so if you have any time to do further debugging that would be great :smile:

**Comment by rowanmiller** [comment]
@ErikEJ just a general note on this (and a couple of other issues where we need to make things more flexible to support CE). Given how much is on our plate to get RC done, we aren't going to be able to dedicate a lot of time to sorting this out for RC. We will spend the time to unblock things before RTM. Our perspective is that the limitations should be ok for the CE provider for RC - as they don't seem to be super common cases (not that they aren't important, just that we need to prioritize things). That said, if you want to look at working around them, then we'd be happy to take contributions on them.

@anpete if you are able to give a hint at where Erik could get started with this, that would be great.

**Comment by ErikEJ** [comment]
I had a DI bug :sad:
