### ISSUE TITLE
SQLite RevEng: Context is always named ModelContext

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#3164]
By default, it should be named `<database-name>Context`.

**Comment by lajones** [comment]
@bricelam. @natemcmaster and I talked this over. A typical `database-name` for SQLite is just a file path. That's what you get if you put the connection string into SqliteConnectionStringBuilder and ask for DataSource (which is similar to what we do for SqlServer). We could just strip off all directories and just make a CSharp identifier out of the name of the file. Would that work?

**Comment by divega** [comment]
FWIW, works for me: just the file name with no path or extensions + Context.

**Comment by lajones** [comment]
Fix checked in with commit 9d69d87.
