### ISSUE TITLE
[RevEng] Error running "scaffold-dbcontext"

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#3178]
Using SQLCE provider with build: beta8-15719 I get this error when running scaffolding - any idea what could be causing this? (The beta 7 bits on NuGet work fine)

    PM>  Scaffold-DbContext -Connection "Data Source=C:\data\Chinook.sdf" -Provider EntityFramework.SqlServerCompact40 
    Scaffold-DbContext : Exception calling "CreateInstance" with "8" argument    (s): "Type 'System.Management.Automation.SwitchParameter' in assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable."
    At line:1 char:2
    +  Scaffold-DbContext -Connection "Data Source=C:\data\Chinook.sdf" -Provider Enti ...
    +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Scaffold-DbContext], MethodInvocationException
    + FullyQualifiedErrorId : SerializationException,Scaffold-DbContext

**Comment by lajones** [comment]
@ErikEJ  Are you able to do any other command e.g. a migration command? If not it's probably that something's changed about Activator.CreateInstance().

**Comment by ErikEJ** [comment]
@lajones Yes, I am:

     PM> add-migration first
     No DbContext was found. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

**Comment by lajones** [comment]
Hmmm. Not sure. I'll investigate.

**Comment by ErikEJ** [comment]
@lajones  Please let me know if I can provide any more info! The test project is a .NET 4.5 Console app.

**Comment by lajones** [comment]
@ErikEJ - will do. As a workaround does it works from the command line?

**Comment by ErikEJ** [comment]
Does the command line work with a csproj project?

**Comment by lajones** [comment]
@ErikEJ - you'd need to have a project.json to use the command line. But I think I found the problem - I'll post a PR.

**Comment by lajones** [comment]
@ErikEJ - I checked in a fix - so closing. But if you still have problems please re-open.

**Comment by ErikEJ** [comment]
@lajones Excellent - thanks for the quick response! :smile:
