### ISSUE TITLE
Mistyping Error

### ISSUE THREAD

**Issue by HakamFostok** [aspnet/EntityFramework#3179]
The Property "ContextKey" in the "System.Data.Entity.Migrations.DbMigrationsConfiguration" class
has the following documentation

![image](https://cloud.githubusercontent.com/assets/12747172/9994574/9caa3e3e-6086-11e5-9afd-40ba0c6d551b.png)

please note that the "applied to" is repeated statement.
thanks in advanced.
@anpete

**Comment by rowanmiller** [comment]
This was actually in EF6. But rather than moving the issue I just fixed it in http://entityframework.codeplex.com/SourceControl/changeset/89acc0ad9578463a499364d44e1858cc5108b67b.
