### ISSUE TITLE
ConditionalTheory/ConditionalFact tests don't run in TestDriven.NET

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#3192]

**Comment by natemcmaster** [comment]
I believe this is a problem with testdriven.net. These custom attributes work just fine on some classes. Inherited + generics seems to be the problem. TD.net doesn't discover tests on these types of classes.

**Comment by ajcvickers** [comment]
I wonder if the tests are running on the CI? Before this was committed the CI was running 7793. The CI was broken for a while, but when it started again the number of tests running was 7640.

**Comment by natemcmaster** [comment]
Should be. They work locally with dnx.
![image](https://cloud.githubusercontent.com/assets/2696087/10083049/7aa6def0-62b1-11e5-9133-3c294e245ad0.png)

**Comment by natemcmaster** [comment]
...and just to be sure, I removed all Conditional* and the number of tests did not change.

**Comment by rowanmiller** [comment]
We want to have a test runner that works with all of our tests. We should try and make them work with TD.NET or swap to another runner.

**Comment by ErikEJ** [comment]
Why not the VS runner? :smile:
