### ISSUE TITLE
A way to use custom migrations directory?

### ISSUE THREAD

**Issue by Yorie** [aspnet/EntityFramework#3243]
Seems command `dnx ef migrations add` doesn't support custom directories to save migrations to.
So, having multiple database contexts will produce difficulties in generating migrations.
Or am I wrong and it can be done some way?

**Comment by bricelam** [comment]
The tool will mimic the directory and namespace of the previous migration. Simply change them to what you want and code on.

**Comment by Yorie** [comment]
Yeah, this works awesome. Thanks for highlight this feature!

**Comment by bricelam** [comment]
I'm going to re-open this issue since we may have a documentation/user-education issue here.

**Comment by rowanmiller** [comment]
Discussed and decided we should add a param to the command to allow you to specify directory ( we will imply namespace from this).

**Comment by rowanmiller** [comment]
In the meantime, you can just move the migrations since we will follow where the most recent migration is. The parameter would just override this behavior.
