### ISSUE TITLE
RevEng: smallint column with default null constraint generates warning

### ISSUE THREAD

**Issue by StevenBonePgh** [aspnet/EntityFramework#3248]
The command 

    Scaffold-DbContext -Connection "<connection string>" -Provider EntityFramework.SqlServer

Generates the following warning

    For column [dbo][MyTable][NullableInt16] unable to convert default value (NULL) into type System.Nullable`1[System.Int16]. Will not generate code setting a default value for the property [dbo][MyTable][NullableInt16] on entity type [dbo][MyTable].

If [MyTable][NullableInt16] column is defined as [NullableInt16] [smallint] NULL,
and the following constraint exists

    ALTER TABLE [dbo].[MyTable] ADD  CONSTRAINT [DF_MyTable_NullableInt16]  DEFAULT (NULL) FOR [NullableInt16]

**Comment by lajones** [comment]
Fixed with PR #3350
