### ISSUE TITLE
RevEng: varchar column with default null constraint generates warning

### ISSUE THREAD

**Issue by StevenBonePgh** [aspnet/EntityFramework#3249]
The command 

    Scaffold-DbContext -Connection "<connection string>" -Provider EntityFramework.SqlServer

Generates the following warning

    Unable to interpret the string ULL as a SQLServer string literal.
    For column [dbo][MyTable][SomeVarchar] unable to convert default value (NULL) into type System.String. Will not generate code setting a default value for the property [dbo][MyTable][SomeVarchar] on entity type [dbo][MyTable].

If [MyTable][SomeVarchar] column is defined as [NullableInt16] `[SomeVarchar]`(6) NULL,
and the following constraint exists

    ALTER TABLE [dbo].[MyTable] ADD  CONSTRAINT [DF_MyTable_SomeVarchar]  DEFAULT (NULL) FOR [SomeVarchar]

**Comment by lajones** [comment]
Fixed with PR #3350
