### ISSUE TITLE
Query: Navigation property translation

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#325]
i.e. `(b => b.Posts.Count() > 0)`

**Comment by divega** [comment]
Removing milestone to bring back to triage.

**Comment by tingvast** [comment]
What is the current status for this issue?/Tobias

**Comment by robfarmergt** [comment]
Any update on this?

**Comment by rowanmiller** [comment]
Not started yet but we'll be starting on it shortly.

**Comment by lukemurray** [comment]
Are there currently any plans on the implementation? I might be able to lend a hand, I'll have a look at the EF code base.

**Comment by robfarmergt** [comment]
@rowanmiller Any progress on this one?

**Comment by rowanmiller** [comment]
@robfarmergt nothing checked in yet, but @anpete is working on it atm.

**Comment by tingvast** [comment]
Great!

**Comment by a99cl208** [comment]
@rowanmiller Any update on this one? IMO it's actually one of the major missing feature for relationnal data stores.

**Comment by rowanmiller** [comment]
@a99cl208 it's being implemented at the moment. It will most likely work end-to-end in Beta 7.

**Comment by leus** [comment]
Is this still scheduled for beta7? I just stumbled upon it. By the way, neither of these work:

    var q = dbContext.Posts.Include(x => x.Author).Where(x => x.Author.Id == 123);

    var q = dbContext.Posts.Where(x => x.Author.Id == 123);

**Comment by rowanmiller** [comment]
@leus parts of it will be in Beta 7. 

cc @anpete to comment on the two particular lines of code you shared to see if these will work in Beta 7.

**Comment by anpete** [comment]
@rowanmiller @leus Yes, that should work in beta7 - let me know if you hit any issues.

**Comment by leus** [comment]
By the way, guys, just a word to commend the extraordinary work you are doing. I'm having a blast playing with this thing!

**Comment by anpete** [comment]
Initial work completed. Will treat bugs/improvements separately.

**Comment by sbattagl** [comment]
Sounds like this is fixed in EF7? Any chance of moving the fix down to EF6 for those of us not ready to jump on the EF7 bandwagon?

**Comment by divega** [comment]
@sbattagl this issue was originally about functionality that was at the time missing in the EF Core codebase, but that already existed in previous versions of EF such as EF6. 

Given that, I am having a hard time guessing what you want fixed in EF6. Please create a new issue at the EF6 repro, and try to follow the guidelines at https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md#filing-issues.
