### ISSUE TITLE
RevEng: datetime field with default constraint generates warning

### ISSUE THREAD

**Issue by StevenBonePgh** [aspnet/EntityFramework#3250]
The command 

    Scaffold-DbContext -Connection "<connection string>" -Provider EntityFramework.SqlServer

Generates the following warning

    For column [dbo][MyTable][MyDateTime] unable to convert default value ('3000-01-01T00:00:00') into type System.DateTime. Will not generate code setting a default value for the property [dbo][MyTable][MyDateTime] on entity type [dbo][MyTable].

If [MyTable][MyDateTime] column is defined as [MyDateTime] `[datetime]` NOT NULL,
and the following constraint exists

    ALTER TABLE [dbo].[MyDateTime] ADD  CONSTRAINT [DF_MyTable_MyDateTime]  DEFAULT ('3000-01-01T00:00:00') FOR [MyDateTime]

**Comment by rowanmiller** [comment]
@lajones is this fixed now?

**Comment by lajones** [comment]
@rowanmiller No. The ones with the null constraint are fixed. This one still needs work.

**Comment by lajones** [comment]
Fixed by PR #3511.
