### ISSUE TITLE
Consider renaming EntityFramework.SqlServer package and assembly to allow side-by-side loading of EF6 and EF7

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#3270]
This came up in a conversation with @rowanmiller and @bricelam today and we wanted to capture it before we forget: 

We believe that currently the fact that the EntityFramework.SqlServer.dll assembly is named the same between EF6 and EF7 is the only reason both cannot be used side by side. If that proves to be truth, we could consider renaming the assembly (probably in EF7 it would make the most sense, and then the package should probably follow suit). 

Some ideas:

- EntityFramework.MSSqlServer
- EntityFramework.SqlClient

**Comment by ErikEJ** [comment]
EntityFramework.SqlServerR2 ?
EntityFramework.SqlServer2008AndLater ?

**Comment by natemcmaster** [comment]
:+1: for EntityFramework.MSSqlServer

**Comment by rowanmiller** [comment]
**Decision:** `EntityFramework.MicrosoftSqlServer`

We do not like it :panda_face: ... but we have to chose another name to support SxS with EF6 :couple_with_heart:... which we think is important :star2:

**Comment by natemcmaster** [comment]
...=> Announcement repo?

**Comment by ErikEJ** [comment]
@natemcmaster  Brace yourselves!

**Comment by natemcmaster** [comment]
@ErikEJ :see_no_evil:

**Comment by natemcmaster** [comment]
Here it comes #3331....

**Comment by wangkanai** [comment]
You guys change a lot, hope its for the best :smiley:
