### ISSUE TITLE
RevEng: ModelBuilder Approach?

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework#3288]
For the future. Consider taking a ModelBuilder approach to building the relational and codeGen models. Are there any (e.g. error) situations where this won't work?

**Comment by natemcmaster** [comment]
Also worth noting: SQLite.Design constructs a model from metadata using `ModelBuilder` and SQL server only makes call on `Model`. It may be possible to unite the implementations into one "relational" metadata => model process.

**Comment by rowanmiller** [comment]
@lajones @natemcmaster is there any functional benefit in making this change? i.e. would we ever do this work at the expense of other features :smile:

**Comment by rowanmiller** [comment]
BTW I don't just mean benefit from an end user perspective... maintainability etc. would also be a valid reason

**Comment by natemcmaster** [comment]
We did this in our RC1 refactoring of the ScaffoldingModel factory.
