### ISSUE TITLE
C.I. runs fewer tests than TestDriven.NET

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#3301]
C.I. is running approximately 7909.

Test Driven is running approximately 8500.

So potentially the C.I. is not running some of our tests.

(C.I. numbers are not completely up-to-date since it takes a while to catch up to current checked in bits.)

**Comment by natemcmaster** [comment]
[Theory]? When fixing #3192 I noticed bugs in how TD.net counts test cases.

**Comment by rowanmiller** [comment]
Benchmark tests are also skipped on DNX, so that would be a difference (though only ~150 tests). BTW I have a PR going out now to change that since I isolated why they were so slow.
