### ISSUE TITLE
MSSQL - incorrect sql - Where(x => subQuery.Any(y => x.xxx == y.yyy)

### ISSUE THREAD

**Issue by LonDat** [aspnet/EntityFramework#3317]
Hi, I have code:
```C#
var qSrvMail = EntityContext.Current.Query<SrvMailAddress>(); // DbSet<SrvMailAddress>
var qSubMail = EntityContext.Current.Query<KontaktMail>(); // DbSet<KontaktMail>

// PROBLEM => !qSrvMail.Any(m => m.Mail == k.Mail)
string[] mails = qSubMail.Where(k => !qSrvMail.Any(m => m.Mail == k.Mail)).Select(k => k.Mail).Distinct().ToArray();
```

It's generate this SQL:
```SQL
SELECT DISTINCT [k].[Mail]
FROM [KontaktMail] AS [k]
WHERE CASE
    WHEN (
        SELECT CASE
            WHEN EXISTS (
                SELECT 1
                FROM [SrvMailAddress] AS [m]
                WHERE [m].[Mail] = [k].[Mail])
            THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
        END
    ) /* = 1 <<< SOMETHING LIKE THIS MISSING!!! */
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END = 0
```
This SQL statement is broken (`An expression of non-boolean type specified in a context where a condition is expected, near 'THEN'.`)

My environment:
MSSQL 2014 Developer Ed.
EF 7 - dev branch (today synced - 2015/10/3)

EF7 ROCK (is't not ironic :D)
Thx for check, Milan

**Comment by aconstant** [comment]
As stated by @LonDat, the SQL generated is missing a ```= 1``` condition, when using the Any() method.

A workaround is to call ```Count(expression) > 0``` instead of ```Any(expression)```, but that should be less optimized, since it results in a SQL call to : ```Count(*) > 0```

**Comment by trailheadtechnology** [comment]
So is there a fix in the main branch for this?
