### ISSUE TITLE
Reverse Engineer: Simplify provider surface to simple database orientated object model

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#3329]
We decided to stop using `IModel` to try and represent the database schema and instead use a simple, purpose built object model. We also want to refactor things so that in most cases providers only need to implement the surface area to return this model (plus the code fragment for `OnConfiguring` and the context class name) - the rest of the pipeline should be provider agnostic. 

The rest of the surface area will go in a `.Internal` namespace - folks can still use it if needed, but we may change it in future releases.

**Comment by rowanmiller** [comment]
Assigning to @natemcmaster as he has already prototyped something like this.

cc @roji @ErikEJ as an heads up (this will come for RC)

cc @lajones

**Comment by natemcmaster** [comment]
Closed with https://github.com/aspnet/EntityFramework/pull/3439
