### ISSUE TITLE
Cascading delete support

### ISSUE THREAD

**Issue by HaoK** [aspnet/EntityFramework#333]
Identity's EF implementation has historically relied on cascading deletes to do things like deleting a Role when there are still foreign keys referencing it.  This is more or less a tracking bug to ensure that there is some way to enable cascading deletes.

**Comment by esditm** [comment]
I'd like to voice my need for `ON DELETE SET NULL` support.

**Comment by divega** [comment]
Our current thinking is that we will support this through a combination of ON DELETE clauses in DDL and delete orphans on `SaveChanges()`.

Migrations already can express the DDL (see #1084) but we need to [set the right things in metadata] (https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs#L606).

**Comment by ilmax** [comment]
I would like to up-vote what @esditm suggested.

**Comment by ToddThomson** [comment]
I would like to have EF7 support cascadeDelete: true/false in .foreignKey().

Is this something that is planned for RTM?

**Comment by ajcvickers** [comment]
Basic support for RTM done. Reverse engineering tracked by a separate bug.
