### ISSUE TITLE
Be consistent about namespaces

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#3374]
`ModelSource` is in MDE.Infrastructure
`SqlServerModelSource` is in MDE.Internal
`SqliteModelSource` is in MDE.Infrastructure.Internal

**Comment by smitpatel** [comment]
Also namespaces for SQLite Tests are all different.

**Comment by rowanmiller** [comment]
**Triage:** ` SqlServerModelSource` should move to `MDE.Infrastructure.Internal`

**Comment by rowanmiller** [comment]
@smitpatel feel free to just do this if you want (even though it is in the RTM milestone)
