### ISSUE TITLE
Collection navigation properties without setter not detected (they were in EF6)

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#3396]
Not having a setter on a collection navigation is not uncommon if you always initialize it in your domain class. In the following model `Customer.Orders` is not detected as a navigation (it would be in EF6)

```c#
        public class OrdersContext : DbContext
        {
            public DbSet<Customer> Customers { get; set; }
            public DbSet<Order> Orders { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;Trusted_Connection=True;");
            }
        }

        public class Customer
        {
            public int CustomerId { get; set; }
            public List<Order> Orders { get; } = new List<Order>();
        }

        public class Order
        {
            public int OrderId { get; set; }

            public int CustomerId { get; set; }
            public Customer Customer { get; set; }
        }
```

You can see that it is not part of the model by trying to use it in an Include.

```c#
[Fact]
public void Test()
{
    using (var context = new OrdersContext())
    {
        context.Customers.Include(c => c.Orders).ToList();
    }
}
```

> Test 'M:EntityFramework.Microbenchmarks.NavPropTest.Test' failed: The expression '[c].Orders' passed to the Include operator could not be bound.
	System.InvalidOperationException: The expression '[c].Orders' passed to the Include operator could not be bound.
	Query\EntityQueryModelVisitor.cs(309,0): at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<IncludeNavigations>b__43_0(IncludeQueryAnnotation annotation)
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	Query\EntityQueryModelVisitor.cs(282,0): at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
	Query\EntityQueryModelVisitor.cs(158,0): at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
	Storage\Database.cs(34,0): at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	Query\QueryCompiler.cs(132,0): at Microsoft.Data.Entity.Query.QueryCompiler.<>c__DisplayClass16_0`1.<CompileQuery>b__0()
	Query\Internal\CompiledQueryCache.cs(32,0): at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
	Query\QueryCompiler.cs(110,0): at Microsoft.Data.Entity.Query.QueryCompiler.CompileQuery[TResult](Expression query)
	Query\QueryCompiler.cs(67,0): at Microsoft.Data.Entity.Query.QueryCompiler.Execute[TResult](Expression query)
	Query\Internal\EntityQueryProvider.cs(37,0): at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at Remotion.Linq.QueryableBase`1.GetEnumerator()
	Extensions\EntityFrameworkQueryableExtensions.cs(2235,0): at Microsoft.Data.Entity.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetEnumerator()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	C:\Users\rowmil\Documents\GitHub\EntityFramework\test\EntityFramework.Microbenchmarks\NavPropTest.cs(18,0): at EntityFramework.Microbenchmarks.NavPropTest.Test()

**Comment by smitpatel** [comment]
fixed in 3c364f30061f64f419e45e1b8ed90d02af1ce479
