### ISSUE TITLE
Wiki: Building the code guide needs update

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#3403]
(I would be happy to do a PR, but I get errors when cloning the Wiki...)

Since this page is one of the prominent pages in the wiki, it would be nice to see it updated. (Bad docs are worse than missing docs!)

1: VS 2015 is no longer in prerelease, so the text and hyperlink should change
2: dnvm powershell command has been change significantly (see aspnet/Home)
3: Tests cannot (currently) run in the VS Test Explorer, only with TestDriven.NET

**Comment by rowanmiller** [comment]
Done
