### ISSUE TITLE
RevEng: Respect IsStoreGenerated

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#3404]
Looking at the SqlServerMetaDataReader, I cannot see any TODOs for supporting the "IsStoreGenerated" property, and the sys.columns query does not include that information. (But I could be overlooking something)

**Comment by natemcmaster** [comment]
I will be working on this as a part of https://github.com/aspnet/EntityFramework/issues/3329. It may be a few days before the dust settles on this refactoring.

**Comment by natemcmaster** [comment]
(oops, wrong button. Meant to leave open.)

**Comment by lajones** [comment]
+1 on @ErikEJ 's suggestion. In the current code we use this to get the `ValueGeneratedOnAdd()` etc Fluent APIs in the generated code.
