### ISSUE TITLE
Query: ThenInclude throw ArgumentNullException when entity implements the interface

### ISSUE THREAD

**Issue by Boglen** [aspnet/EntityFramework#3409]
public interface ITestEntity1
    {
        int Id { get; set; }

        ICollection<ITestEntity2> EntityChilds { get; set; }
    }

    public interface ITestEntity2
    {
        int Id { get; set; }

        ICollection<ITestEntity2> Childs { get; set; }

        int? TestEntity1Id { get; set; }
        ITestEntity1 ParentRef { get; set; }
        int? TestEntity2Id { get; set; }
        ITestEntity2 Parent { get; set; }
    }

    public class TestEntity11 : ITestEntity1
    {
        public int Id { get; set; }

        public virtual ICollection<ITestEntity2> EntityChilds { get; set; }
    }

    public class TestEntity22 : ITestEntity2
    {
        public int Id { get; set; }

        public virtual ICollection<ITestEntity2> Childs { get; set; }

        public int? TestEntity1Id { get; set; }
        public ITestEntity1 ParentRef { get; set; }
        public int? TestEntity2Id { get; set; }
        public ITestEntity2 Parent { get; set; }
    }

    public class TestContext22 : DbContext
    {
        public DbSet<TestEntity11> Entity1 { get; set; }
        public DbSet<TestEntity22> Entity2 { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity<TestEntity11>(b => {
                b.HasKey(k => k.Id);
                b.HasMany(p => (ICollection<TestEntity22>)p.EntityChilds).WithOne(o => (TestEntity11)o.ParentRef).HasForeignKey(k => k.TestEntity1Id).IsRequired(false);
            });

            modelBuilder.Entity<TestEntity22>(b => {
                b.HasKey(k => k.Id);
                b.HasMany(p => (ICollection<TestEntity22>)p.Childs).WithOne(o => (TestEntity22)o.Parent).HasForeignKey(k => k.TestEntity2Id).IsRequired(false);
            });
        }
}

            using (var context = new TestContext22())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var ent1 = context.Add(new TestEntity11()).Entity;
                context.SaveChanges();

                var ent21 = context.Add(new TestEntity22()).Entity;
                var ent22 = context.Add(new TestEntity22()).Entity;
                var ent23 = context.Add(new TestEntity22()).Entity;

                context.SaveChanges();

                ent21.ParentRef = ent1;
                ent21.Childs = new List<ITestEntity2>() { ent22, ent23 };

                context.SaveChanges();

                //Throw exception
                var getIt = context.Entity1.Include(p => p.EntityChilds).ThenInclude(i => i.Childs).ToList();
            }

**Comment by rowanmiller** [comment]
This is because mapping to interfaces is not supported. This means `public virtual ICollection<ITestEntity2> EntityChilds { get; set; }` is not a valid navigation property and so it is not included in the model - therefore you get an exception when you try to include it.

Enabling this scenario with interfaces is already tracked by https://github.com/aspnet/EntityFramework/issues/757

**Comment by divega** [comment]
I may be missing something but I believe this is just a bug in `Include()`/`ThenInclude()`. 

1. The model is built and seems to be what the user expected (AFAIR we decided at some point that navigation properties that were of a more general types than a known entity type were ok)
2. The data seems to be saved to the database correctly.
3. The following scenarios all seem to work and cause the entities and nav props to be materialized/fixed up correctly:
``` C# 
            using (var context = new TestContext22())
            {
                context.Entity1.Load();
                context.Entity2.Load();
            }
            using (var context = new TestContext22())
            {
                context.Entity1.Include(p => p.EntityChilds).Load();
            }
            using (var context = new TestContext22())
            {
                context.Entity2.Include(p => p.Parent).Load();
            }
            using (var context = new TestContext22())
            {
                context.Entity2.Include(p => p.ParentRef).Load();
            }
            using (var context = new TestContext22())
            {
                context.Entity2.Include(p => p.Childs).Load();
            }
```

**Comment by Boglen** [comment]
In intellisence after i expand Entity1 and Entity2 and then expand context.Entity1.EntityChilds.Childs - all is good. Simple include with public virtual ICollection<ITestEntity2> EntityChilds { get; set; } work fine with interfaces.

**Comment by mikary** [comment]
Ran the original reproduction and the additional cases mentioned by @divega and they are all executing without throwing. There have been several changes to Include since this issue was filed, and it is likely one of these changes also resolved this issue.

**Comment by divega** [comment]
@mikary do we have any test that looks like this scenario? we shouldn't regress it...
