### ISSUE TITLE
RevEng: Scaffolding fails silently on VB projects

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#3417]
It would be helpful to show an error message instead https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/issues/242#issuecomment-147589772

**Comment by rowanmiller** [comment]
We should just be generating C# (or a warning would be fine too).

**Comment by lajones** [comment]
@rowanmiller @ErikEJ - I tried running Scaffold-DbContext against a VB project with build 7.0.0-rc2-16542 and that does _not_ fail. Instead it produces C# code in the VB project successfully. So if we want that functionality we just leave the code as is. However I have created a PR, see #4087, which does throw an error from Scaffold-DbContext if the user attempts to run it from a VB project, which we can use if preferred.

**Comment by rowanmiller** [comment]
Showing an error is better... so lets get your PR in

**Comment by lajones** [comment]
See comments in PR #4087. We decided to leave the code as is - for now it will generate C# code in a VB project.

**Comment by midnait** [comment]
https://github.com/aspnet/EntityFramework/issues/4210

Migrations and Scaffold "translated" to VB.
