### ISSUE TITLE
Provide an IsUnicode API

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#3420]
As pointed out in https://github.com/aspnet/EntityFramework/issues/3362 we have removed this API which forces you to specify a provider specific type in cases where you would not have needed to in EF6. We should add this into EF7.

**Comment by joshmouch** [comment]
I think IsFixedLength() is probably the other one that is agnostic yet can have an easy fallback if not supported by the provider. I use that because I override the entities in Microsoft Identity 2.0, and it uses that quite a bit.

**Comment by bricelam** [comment]
**Note to implementer:** Don't forget to diff the metadata in `MigrationsModelDiffer.Diff(IProperty, IProperty)`.

**Comment by lajones** [comment]
*Note to implementer:* when we do this we'll need to update scaffolding to output `IsUnicode(false)` for `varchar` columns instead of outputting `HasColumnType("varchar(x)")` as we do now. See discussion in #4312.

**Comment by divega** [comment]
Cleaning up milestone so that we can see this in triage.
