### ISSUE TITLE
Build warnings from TelemetrySource in tests

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#3422]
Presumably after 2887b8b95

**Comment by smitpatel** [comment]
fixed by 6e16bdef3a2d4c03ef41c265adbf01b836b69ccd ?

**Comment by anpete** [comment]
@smitpatel No, these are coming out of the tests.

**Comment by divega** [comment]
We can as well choose to directly move up to use the new DiagnosticsSource and remove all the pragma directives for the obsolete TelemetrySource but we need to coordinate that with @JunTaoLuo and @avanderhoorn. 

cc @anpete
