### ISSUE TITLE
Value generation error in case of inheritance

### ISSUE THREAD

**Issue by IonRobu** [aspnet/EntityFramework#3445]
Hello, 

I have two entities: Contract and ContractState, configured as follows:
Contract -> Has many(List[ContractState]).Has one(Contract).With foreign key(Guid ContractId)
ContractState is abstract and has three concrete type inheriting it: ContractStateCease, ContractStateDetach, ContractStateSuspend. OnModelCreating sets it like following:

modelBuilder.Entity<ContractState>()
				.Discriminator()
				.HasValue(typeof(ContractStateCease), "ContractStateCease")
				.HasValue(typeof(ContractStateDetach), "ContractStateDetach")
				.HasValue(typeof(ContractStateSuspend), "ContractStateSuspend");

But i receive error:

InvalidOperationException: The property 'ContractId' on entity type 'ContractState' has value generation on add enabled and it is included in the foreign key {'ContractId'}. Foreign key properties should not have value generation on add enabled unless they are part of a cycle where they are the only properties with value generation on add enabled.

The error appeared in beta8, and worked in beta 7.
I tried:
modelBuilder.Entity<ContractState>()
				.Property(cs => cs.ContractId)
				.ValueGeneratedNever();
but no effect.
Any ideas?

Thanks, Ion

**Comment by rowanmiller** [comment]
@smitpatel can you verify this is fixed after @AndriySvyryd checks in the conventions work.

**Comment by IonRobu** [comment]
Is possible to use another inheritance pattern, at least until the bug is solved? this bug is blocking for me now...

**Comment by AndriySvyryd** [comment]
There are no other inheritance patterns supported by EF7 at this moment. The fix is currently being reviewed and should soon be available in nightly build.

**Comment by IonRobu** [comment]
Thanks, Andriy! I will wait for fix!

**Comment by smitpatel** [comment]
Verified this with latest code that this generates a valid model.

**Comment by IonRobu** [comment]
Hello,

It works now, but I receive another error which seems to be related. I described here: #3584
