### ISSUE TITLE
Add more logging to scaffolding

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#3456]
We only log a small amount of information, and almost exclusively just for console output. We can add more thorough logging for provider writers who are building/testing their own reveng implementations.

Also, revisit the logging we produce on the console to ensure it provides useful information for end-users.

**Comment by natemcmaster** [comment]
- [ ] Index on column that could not be scaffolded (see https://github.com/aspnet/EntityFramework/pull/3509/files#r42923752)

**Comment by lajones** [comment]
Fix checked in with commit 2d14e47. Addresses both the issues above.
