### ISSUE TITLE
Regression? Foreign key properties now based on type name rather than property name

### ISSUE THREAD

**Issue by axefrog** [aspnet/EntityFramework#3503]
I have an entity class with the following properties:

```c#
public virtual ContourTemplate TailContour { get; set; }
public virtual ContourTemplate NoseContour { get; set; }
public virtual ContourTemplate MidContour { get; set; }
```

In beta7, the column names generated were `TailContourId`, `NoseContourId` and `MidContourId`. That's perfect and exactly what it should be. I've had to make some changes and in the process have dumped my old migrations from beta 7 and created new ones with beta 8. The new migrations generated by beta 8 now look like this though:

```c#
ContourTemplateId = table.Column<int>(nullable: false),
ContourTemplateId1 = table.Column<int>(nullable: false),
ContourTemplateId2 = table.Column<int>(nullable: false),
```

This is less than ideal. Why the change?

**Edit**  
I just added `[Column("TailContourId")]` and so forth to each property and it had no effect on the generated migration code.

**Edit**  
Looks like adding `ForeignKey` in place of `Column` does the trick. Original question still stands though.

**Comment by smitpatel** [comment]
Recent refactoring in metadata around relationship building had caused this regression. Submitted PR for fix.

**Comment by smitpatel** [comment]
No repro anymore. Verified in 7.0.0-rc1-16105 packages. 
@axefrog - if you are using nightly then above packages are available on the feed. Else it will be in rc1 release.
