### ISSUE TITLE
Scaffolding: reverse engineer sequences

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#3510]
Scaffolding currently only generates code for identity columns. Detect sequences and add the appropriate annotations to code gen.

**Comment by ajcvickers** [comment]
Note that I don't think we would ever try to reverse engineer to our sequence HiLo pattern for value generation. But if there are sequences in the database, then we should reverse engineer them into the model so they can be manipulated and re-created using Migrations, and so that code can be manually set to use them for value generation if that is what they are intended to be used for.

**Comment by roji** [comment]
Note that this is critical for PostgreSQL reverse engineering - only sequences are supported (no alternative identity strategy)

**Comment by natemcmaster** [comment]
To be clear, the intention is to reverse engineer a `ModelBuilder.HasSequence()` and not reverse engineer sequence-based value generation for properties (at least in SQL Server.)

@roji in PostgreSQL, can sequences be reused across multiple columns and tables? Or are they restricted to one table/column as the implementation detail for `serial`?

**Comment by roji** [comment]
See discussion in #3966.

@natemcmaster, sequences can indeed be reused across multiple columns and tables. However, when a column is created with type `serial` a sequence is implicitly created for that column. This does not prevent it from being used for other columns/tables, but the implicitly-created name does contain the table and column, "restricting" it to that column.

**Comment by roji** [comment]
FYI I just realized that if the hack detailed in #3966 is kept, then it's no longer especially important for PostgreSQL to reverse-engineer sequences: PG serial columns are simply reverse engineered with ValueGenerated.OnAdd, which is probably sufficient.

**Comment by roji** [comment]
Have done this for PostgreSQL too.
