### ISSUE TITLE
Scaffolding: cleanup issues in property/type name generation

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#3532]
Name generation has a minor bug (see below). We should also add more testing for these scenarios (e.g. automate testing against AdventureWorks).

Column names are not checked for validity in their current type. i.e. a table named "EmailAddress" with a column named "EmailAddress" will produce invalid C#. "

> error CS0542: 'EmailAddress': member names cannot be the same as their enclosing type

~~We can also improve existing code to use Microsoft.CodeAnalysis.CSharp instead of CSharpUtilities.~~

**Comment by lajones** [comment]
We decided not to depend on `Roslyn` (and hence `Microsoft.CodeAnalysis.CSharp`) in #3602.

**Comment by lajones** [comment]
Fix checked in with 90e5555.
