### ISSUE TITLE
Optimize .NET Native directives

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#3561]
The current runtime directives in our library are not optimized. Runtime-metadata data is included for **all** EF types, most of which do not need to be reflection enabled. Optimizing the library to include only those types needing metadata will reduce compilation time and resulting .NET Native binary.

**Comment by rowanmiller** [comment]
@natemcmaster is this critical? It seems like things will become more fragile if we have a list of things we need (that will break all the time). If there is no major downside, then it seems like we should just leave it with everything.

**Comment by natemcmaster** [comment]
Not critical. I think we can consider this a `pr1` or backlog item. The primary reason for optimizing is to reduce the binary and (potentially) improve compile time.

**Comment by rowanmiller** [comment]
Closing as this would just makes things more brittle. If we find a good reason to do it in the future then we can reconsider.

**Comment by natemcmaster** [comment]
More info to consider: adding EF.Sqlite RC1 to an empty UWP project increases the appx package (release mode w/ .net native) from 1 MB to about 56 MB, and increases compilation time from about 30 seconds to >5 minutes.

**Comment by ErikEJ** [comment]
WAT :question:

**Comment by natemcmaster** [comment]
This is due to the excessive metadata included due to [ImplyGen.cs](https://github.com/aspnet/EntityFramework/blob/94cd412e9319d35aac3f2600d9d42d6132e0cbb6/src/EntityFramework.Core/Utilities/ImplyGen.cs). This was necesary to make query work in RC1. Hopefully our new approach for #3801 will reduce this.

**Comment by divega** [comment]
Reopening as Nate needs to do a bit more analysis on how much unnecessary reflection metadata from the EF assemblies is contributing to the size of the binaries and the compilation time.

We should have an automated test suite running on .NET Native to makes sure we are not missing any required reflection metadata.

**Comment by rowanmiller** [comment]
Yep... agreed that is a compelling reason to address this :smile:

**Comment by natemcmaster** [comment]
With changes in 9aab7992d1825ebc903ca321d420dcb5cabb2e65, we've made significant improvement.

*Baseline: Blank UWP Project (default template):*
**Build time**: 20.0s
**Appx size (x86)**: 2.42 MB

*Baseline + added a reference to `EntityFramework.Sqlite`:*
**Build time:** 45.9s
**Appx size (x86)**: 10.1 MB

*Build time is the average of 3 build runs on a clean solution, excluding restore and deploy times

**Comment by divega** [comment]
Nice!

**Comment by natemcmaster** [comment]
Closing now that we have addressed the compiler crashes and excessive metadata inclusion. See https://github.com/aspnet/EntityFramework/pull/4197. Optimizing further could make EF brittle as it can be hard to keep rdxml in sync with code.
