### ISSUE TITLE
Properties marked as HasAlternateKey will not be updated on DB.

### ISSUE THREAD

**Issue by ivanrusso** [aspnet/EntityFramework#3563]
On a Model we have two properties marked as AlternateKey. This generates a new Unique Constraint on the Database.

`entityBuilder.HasKey(p => p.Id);`
`entityBuilder.HasAlternateKey(p => p.Abbrev);`
`entityBuilder.HasAlternateKey(p => p.Name);`

When a value of a key property changes, then the change tracker returns the EntityEntry with the given changes. But calling SaveChanges the propety is not included in the Update Statement.

**Comment by rowanmiller** [comment]
We don't support mutating key values (at least not yet) so this should throw

**Comment by ivanrusso** [comment]
For primary keys this is a good approach but not for unique keys.
What can we do to generate a unique key on the Database and allow to update this key?
Is the only Workarround to generate a unique key constraint on the Database with Custom Migration Script and execute an Alter Table command?

**Comment by rowanmiller** [comment]
@ivanrusso you can create a unique index on the properties to enforce that they are unique (`builder.Entity<Blog>().Index(...)`) but you won't be able to use these as the target of a foreign key. At this stage in EF7, if a set of unique properties are used as the target of a relationship then the values can not be mutated after they are saved.
