### ISSUE TITLE
Exploratory testing: UWP app end to end

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#3593]
We should try to actually publish a UWP app that uses EntityFramework.Sqlite and test on devices.

**Comment by rowanmiller** [comment]
I have done this for RC1 (Unicorn Clicker is [now available in the app store](https://www.microsoft.com/en-us/store/apps/unicorn-clicker/9nblggh5jzrk)). I will continue to upgrade this to the latest release as part of our testing for each upcoming release.

The only issues I hit were the binary size and build perf issues that we have already addressed for RC2.

@divega @natemcmaster @bricelam any objections to closing this out now.

**Comment by bricelam** [comment]
Sounds good to me, so long as we make updating Unicorn Clicker part of our release criteria.

**Comment by divega** [comment]
:+1:
