### ISSUE TITLE
Queries with shadow properties fail on .NET Native

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#3604]
Any query that uses `EF.Property(e, "SomeProperty")` fails on UWP, .NET Native with this error:

`System.InvalidOperationException: The EF.Property<T> method may only be used within LINQ queries.`

**Comment by divega** [comment]
That exception is of course in the body of the method. It is supposed to never be invoked :smile: 

Seems like a symptom of the query being evaluated in-memory outside of the control of EF, which is concerning. Have you checked that the SQL of other queries is what expect?

**Comment by natemcmaster** [comment]
The SQL never generates. It dies before this point. My untested guess is that the problem is in [EntityQueryModelVisitor.BindMethodCallExpression](https://github.com/aspnet/EntityFramework/blob/5450ca9d07cc722ec5a0f2dfac8f3a4619657202/src/EntityFramework.Core/Query/EntityQueryModelVisitor.cs#L1145-L1147). .Net Native has a concept of a "inspection-only" runtime type that may be tripping up our "ReferenceEquals" comparison here.

**Comment by divega** [comment]
For the SQL I was referring to what happens with other queries, but you can disregard that. @anpete had a theory (which maybe related to what you are saying): that the logic that tries to match that method call in the expression (so that we can rewrite it) is failing to produce a match.

**Comment by anpete** [comment]
@natemcmaster It would probably be OK to switch to matching the Property method via name and declaring type as strings.

**Comment by natemcmaster** [comment]
**Status update:** I presume the root cause is [comparison with `EntityQueryModelVisitor.PropertyMethodInfo`](https://github.com/aspnet/EntityFramework/blob/0b96c132f41442a10064156798d18d2526c3c0a7/src/EntityFramework.Core/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs#L154-L157) is not working correctly. (The instance of `MethodInfo` returned from `MethodInfo.GetGenericMethodDefinition()` is not reference equivalent to `TypeInfo.GetDeclaredMethod()` on .NET Native runtime but is on CLR.) Unfortunately, I could not find a different method of comparison that solves this bug. I tried string comparison on method/type names and `.Equals()` instead of `ReferenceEquals`....still haven't found a solution.

**Comment by anpete** [comment]
I think string comparison on the method name, declaring type, namespace is fine. Do you mean you tried that and it doesn't work for some reason?

**Comment by natemcmaster** [comment]
Yeah, I tried string comparison. Didn't work.

**Comment by anpete** [comment]
Why?

**Comment by natemcmaster** [comment]
Still working on it. Our query debugging tools don't work on .NET Native. The .NET Native runtime and the VS debugger still do not play nice. I can't even get a breakpoint in the right place to examine. (The debugger team is looking in this.) 

I suspect, however, that it's the type system in the .NET Native runtime (`System.Private.*`) allows for two, different *runtime* method definitions to exist that represent the same *compile-time* method. And there is no way to equate them at runtime...so far as I can tell...

**Comment by anpete** [comment]
Would something like this work?
```c#
if (node.Method.IsGenericMethod
    && node.Method.Name == "Property"
    && node.Method.DeclaringType.FullName == "Microsoft.Data.Entity.EF")
// ...
```

**Comment by natemcmaster** [comment]
Yeah, I bet that would. I’ll try it.
