### ISSUE TITLE
Projection with multiple aggregates only running last one

### ISSUE THREAD

**Issue by davezych** [aspnet/EntityFramework#3616]
If you have a projection with multiple aggregates (I've only tried with combinations of `Sum` and `Count`) only the last one seems to get run, and each property gets the results from that last query. 

dnx: `1.0.0-rc1-16048`
EF: `7.0.0-rc1-16147`

Repro:

    public partial class MyContext : DbContext
    {
        public MyContext()
        {

        }
        
        public DbSet<Forum> Forums { get; set; }
        public DbSet<Topic> Topics { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                @"Server=(localdb)\mssqllocaldb;Database=EF7.AspNet5;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }
    }
    
    public class Forum
    {
        public Forum()
        {
            Topics = new HashSet<Topic>();
        }

        public int Id { get; set; }
        public string Title { get; set; }

        public ICollection<Topic> Topics { get; set; }
    }

    public class Topic
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int ForumId { get; set; }
        public int Counter { get; set; }

        [ForeignKey(nameof(ForumId))]
        [InverseProperty("Topics")]
        public Forum Forum { get; set; }
    }

Query:

    var forums = _context.Forums.Include(f => f.Topics).Select(f => new
            {
                f.Id,
                Counter = f.Topics.Sum(t => t.Counter),
                TopicCount = f.Topics.Count(),
            }).ToList();

Sample data:

    var forum = new Forum();
    forum.Title = "SAMPLE";

    var topic = new Topic();
    topic.Title = "SAMPLE";
    topic.Forum = forum;
    topic.Counter = 10;

    forum.Topics.Add(topic);

    var topic2 = new Topic();
    topic2.Title = "SAMPLE2";
    topic2.Forum = forum;
    topic2.Counter = 9;

    forum.Topics.Add(topic2);

    context.Forums.Add(forum);

    context.SaveChanges();

Running the above query with this sample data results in:

    Id: 1
    Counter: 2
    TopicCount: 2

When we should get a `Counter` of `19`. This is the resulting SQL query:

    SELECT (
         SELECT COUNT(*)
         FROM [Topic] AS [t]
         WHERE [f].[Id] = [t].[ForumId]
    ), [f].[Id]
    FROM [Forum] AS [f]

**Comment by davezych** [comment]
I also updated a sample MVC repo with an example of this issue: https://github.com/davezych/EF7_3029/tree/SumCount

**Comment by GunterGlad** [comment]
I also have the same issue. A fix would be appreciated.

**Comment by GunterGlad** [comment]
I can provide some samples if you want.

**Comment by maumar** [comment]
@GunterGlad please do provide samples (you can paste them in the comments).

**Comment by GunterGlad** [comment]
Here is my expression:
var list3 = context.Customers.Select(x => new
         {
            Name = x.Name,
            PaymentTotal = x.Payments.Sum(p => p.PaymentAmount),
            PaymentTotalPlus = x.Payments.Sum(p => p.PaymentAmount + 5)
         }).ToList();

public class AppDBContext: DbContext, { 
public DbSet<Customer> Customers { get; set; }
public DbSet<Payment> Payments { get; set; }
}

Here are my classes:
public class Customer 
{
public string Name { get; set; }
public virtual ICollection<Payment> Payments { get; set; }
}

public class Payment 
{
#region Customer
public int CustomerID { get; set; }
public virtual Customer Customer { get; set; }
#endregion Customer

  public decimal PaymentAmount { get; set; }
}

**Comment by maumar** [comment]
Fixed in e697bd49359b50e4a385f199c0e4aabff769aca2

**Comment by realavaloro** [comment]
I am having the same issue. Example:
```
var test = await _context.Transports
                .Include(t => t.Boxes)
                .Where(t => t.Id == 123)
                .Select(s => new
                {
                    Weight = (from b in b.Boxes
                              join p in _context.Packages on c.Id equals p.BoxId
                              select p).Sum(p => p.Weight),
                    Volume = (from c in s.Boxes
                              join p in _context.Packages on c.Id equals p.BoxId
                              select p).Sum(p => p.Volume)
                })
                .ToListAsync();
```
would return a list of objects where Weight would be always the same value as Volume because the Weight aggregate is never executed in database. Same thing as described above.

I can see it was fixed in November 2015, however I am testing it with `"EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final"` and it still has this problem.

Isn't this fix part of the final RC1? If not, how should I apply the fix? Thank you

**Comment by maumar** [comment]
@realavaloro the fix is not part of the RC1, we took a snapshot on the 18th. Also there is no easy way to update the packages to the nightly ones - you would have to move the entire project to the nightly packages and might have some stability problems at the moment. The best course of action is apply the workaround for now (produce two queries, each having just one aggregate). 

We don't have the dates for RC2 just yet, but you can follow https://github.com/aspnet/Home/wiki/Roadmap
Dates will appear there, when they are known. It should happen soon.

**Comment by realavaloro** [comment]
@maumar  Thank you. The workaround will be enough for now then.
