### ISSUE TITLE
Invalid SQL when projection includes a comparison to a Nullable type

### ISSUE THREAD

**Issue by jeffogata** [aspnet/EntityFramework#3618]
int? selectedId = null;

    var results = await DbContext.Departments
        .Select(x => new {Selected = x.Id == selectedId})
        .ToListAsync();

generates this SQL:

    exec sp_executesql N'SELECT [x].[Id] = @__selectedId_0
    FROM [Department] AS [x]',N'@__selectedId_0 int',@__selectedId_0=NULL

This looks to be similar to https://github.com/aspnet/EntityFramework/issues/2450 (apologies if it is a duplicate).

**Comment by smitpatel** [comment]
could be similar to #3703
