### ISSUE TITLE
Perf: Address model building benchmarks that are slower than EF6

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#3640]
Building the AdventureWorks model is currently slightly slower than EF6. We have several improvements under way that should make it faster than EF6, but using this issue to track ensuring the overall scenario is sped up.

**Comment by rowanmiller** [comment]
One improvement to consider: https://github.com/aspnet/EntityFramework/issues/3587

**Comment by rowanmiller** [comment]
One related improvement already underway https://github.com/aspnet/EntityFramework/issues/3476

**Comment by AndriySvyryd** [comment]
The planned perf improvements have been implemented. Should this be closed?

**Comment by divega** [comment]
Fine by me. How much did it improve? :smile:

**Comment by AndriySvyryd** [comment]
I believe that before any improvements EF7 was about 40% slower than EF6, now it's about 15% faster in InitializationTests.BuildModel_AdventureWorks scenario
