### ISSUE TITLE
Topological Sort of CommandBatch gives incorrect ordering

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#3648]
When we assign new dependent entity to principal end navigation for required fk, the old dependent entity gets deleted and new entity is added to database. Though commands are sorted in a way that we add new entity first and then delete the old entity. For one-to-one FK the fk property should be unique. Therefore the order in which sql sent to database throws exception. This is not happening at present because of #700 

Following is the test failure out codebase. Trying to generate standalone repro if possible.

Test
`GraphUpdatesWithSequenceSqlServerTest.Save_required_non_PK_one_to_one_changed_by_reference(changeMechanism = ChangeMechanism.Principal, useExistingEntities = false)`
Sql sent to database
```` SQL
exec sp_executesql N'SET NOCOUNT OFF;
INSERT INTO [RequiredNonPkSingle1] ([Id], [RootId])
VALUES (@p0, @p1);
SELECT @@ROWCOUNT;
DELETE FROM [RequiredNonPkSingle2]
WHERE [Id] = @p2;
SELECT @@ROWCOUNT;
INSERT INTO [Root] ([Id], [AlternateId])
VALUES (@p3, @p4);
SELECT @@ROWCOUNT;
',N'@p0 int,@p1 int,@p2 int,@p3 int,@p4 uniqueidentifier',@p0=181,@p1=1,@p2=31,@p3=180,@p4='D52E97D8-367E-4EDE-1CD5-08D2E4AE65A2'

exec sp_executesql N'SET NOCOUNT OFF;
DELETE FROM [RequiredNonPkSingle1]
WHERE [Id] = @p5;
SELECT @@ROWCOUNT;
INSERT INTO [RequiredNonPkSingle2] ([Id], [BackId])
VALUES (@p6, @p7);
SELECT @@ROWCOUNT;
',N'@p5 int,@p6 int,@p7 int',@p5=30,@p6=182,@p7=181
````

**Comment by divega** [comment]
Are these two operations correlated in any way from the perspective of the topological sort? Otherwise should we just do deletes before inserts? I ask because we went over the same change in previous versions of EF and it helped in other scenarios as well.

**Comment by smitpatel** [comment]
the delete & insert operation on `[RequiredNonPkSingle]` are pointing to same `[root]` so unique index constraint on fk property is violated.

**Comment by divega** [comment]
But there isn't any dependency between the two operations, correct?

**Comment by smitpatel** [comment]
At present our topological sort looks at foreign key based dependencies only. Hence for delete child precedes parent & for insert parent precedes child. Though in this case there is no foreign key dependency between 2 operations (delete and insert on same table). Due to both operations are having foreign key dependencies with other operations they both end up in different batches. Sorting deletes before insert would not solve it if they both are in different batches.
Based on unique index (or alternate key) constraints, we should also have dependency between operations.
