### ISSUE TITLE
Query: [Nav Prop Translation] .OrderBy on column in optionally joined table makes the join required

### ISSUE THREAD

**Issue by jparish9** [aspnet/EntityFramework#3660]
Windows 10, VS 2015, IIS Express, SQL Server Express 2014, EF 7.0.0-beta8, ASP.NET 6.0.0-beta8

Using .OrderBy to order by a column in a table that has been joined through a nullable join column filters out results where the join column is null.

Models:
```c#
public class Blog {
   public int BlogId { get; set; }
   public int? AuthorId { get; set; }
   public Author Author { get; set; }
}
```

```c#
public class Author {
   public int AuthorId { get; set; }
   public string Name { get; set; }
}
```

This query is filtering out `Blog`s where `AuthorId` is null:
```c#
_dbContext.Blogs.OrderBy(b => b.Author.Name).ToList();
```

The generated SQL shows an `inner join` to `Author`, even though `AuthorId` is nullable:
```sql
SELECT [b].[BlogId], [b].[AuthorId]
FROM [Blog] AS [b]
INNER JOIN [Author] AS [b.Author] ON [b].[AuthorId] = [b.Author].[AuthorId]
ORDER BY [b.Author].[Name]
```

Note that `.Include` handles the nullable join correctly with a `left join`, e.g.:
```c#
_dbContext.Blogs.Include(b => b.Author).ToList();
```
generates:
```sql
SELECT [b].[BlogId], [b].[AuthorId], [a].[AuthorId], [a].[Name]
FROM [Blog] AS [b]
LEFT JOIN [Author] AS [a] ON [b].[AuthorId] = [a].[AuthorId]
```

Combining `.Include` and `.OrderBy` results in two joins, one of them `inner`, also filtering out `Blog`s with null `AuthorId`s:
```c#
_dbContext.Blogs.Include(b => b.Author).OrderBy(b => b.Author.Name).ToList();
```
generates:
```sql
SELECT [b].[BlogId], [b].[AuthorId], [a].[AuthorId], [a].[Name]
FROM [Blog] AS [b]
INNER JOIN [Author] AS [b.Author] ON [b].[AuthorId] = [b.Author].[AuthorId]
LEFT JOIN [Author] AS [a] ON [b].[AuthorId] = [a].[AuthorId]
ORDER BY [b.Author].[Name]
```

**Comment by maumar** [comment]
Related to https://github.com/aspnet/EntityFramework/issues/3186

Currently all navigation properties are expanded using inner joins

**Comment by maumar** [comment]
Initial support for optional navigation translation to LOJ has been added in c4e44471b6f41f96d37b1acfbbb4cc97cd11ee89

There are still some issues remaining, e.g. Include not working with optional navigations, and queries being client-evaluated more often
