### ISSUE TITLE
Subqueries with parameters skip parameterization

### ISSUE THREAD

**Issue by jeremyZX** [aspnet/EntityFramework#3668]
This may be related to #3317.

If I create a query that I use as a subquery of another query, e.g.:

```c#
var petsOfType = _dbContext.PetOwners.Where(x => x.Pet.Type == petType)

var owners = _dbContext.People
    .Where(x => petsOfType.Where(d => d.PersonId == x.PersonId).Count() > 0)
    .ToList()
```

The parameters to the subquery are cached along with the query itself, which leads to wrong results from the database when the parameters change.  The results are correct for the first execution only.

The executed queries reflect the lack of parameterization and hint at the entire query being cached.

From SQL Profiler, first execution, petType = "dog":

```sql
SELECT [x].[PersonId], [x].[Name], [x].[PetPetId]
FROM [Person] AS [x]
WHERE (
	SELECT COUNT(*)
	FROM [PetOwner] AS [x]
	INNER JOIN [Pet] AS [x.Pet] ON [x].[PetId] = [x.Pet].[PetId]
	WHERE ([x.Pet].[Type] = 'dog') AND ([x].[PersonId] = [x].[PersonId])
) > 0
```

From SQL Profiler, second execution, petType = "cat":

```sql
SELECT [x].[PersonId], [x].[Name], [x].[PetPetId]
FROM [Person] AS [x]
WHERE (
	SELECT COUNT(*)
	FROM [PetOwner] AS [x]
	INNER JOIN [Pet] AS [x.Pet] ON [x].[PetId] = [x.Pet].[PetId]
	WHERE ([x.Pet].[Type] = 'dog') AND ([x].[PersonId] = [x].[PersonId])
) > 0
```

**Comment by divega** [comment]
@jeremyZX what version of the bits are you using? 

@anpete this maybe an issue in the area you are working on at the moment.

**Comment by jeremyZX** [comment]
Beta 8.

**Comment by anpete** [comment]
@rowanmiller Moving to rc2 as I have a fix already.
