### ISSUE TITLE
Grouping with Where on a navigation prop fails

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/EntityFramework#3674]
Version: "7.0.0-rc1-*

Query:

    from o in nwind.Orders
    where o.Shipper.CompanyName == "Speedy Express"
    group o by o.OrderDate;

Message:

    Expression of type '...' cannot be used for parameter of type '...' of method '...'

Full sample: https://github.com/AlekseyMartynov/ef7-bugs/tree/group-navigation-where

**Comment by mikary** [comment]
Verified that this query throws an `ArgumentException` in `EntityFramework.MicrosoftSqlServer 7.0.0-rc1-final`, but the exception is not thrown in current dev.

The returned results appear to be incorrect due to a related issue (#5179) with navigations.

**Comment by rowanmiller** [comment]
@mikary can you verify now that #5179 is fixed

**Comment by mikary** [comment]
Verified and added test coverage to prevent future regressions.
