### ISSUE TITLE
"Sequence contains more than one element" when grouping by a nested (nav) prop

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/EntityFramework#3675]
Version: 7.0.0-rc1-*

Query:

    from p in nwind.Products
    group p by p.Category.CategoryName;

Full sample: https://github.com/AlekseyMartynov/ef7-bugs/tree/group-nested-prop

**Comment by PrashanthIBM** [comment]
Seems similar to  #3639

**Comment by PrashanthIBM** [comment]
Hi Aleksey,

Seems like  navigation property usage is still not supported.

Are you able to use set operators like UNION, INTERSECT, EXCEPT, CONCAT .... in rc1 ?

Thanks and Regards,
Prashanth

**Comment by AlekseyMartynov** [comment]
@PrashanthIBM 

> Seems like navigation property usage is still not supported

Simple cases (`OrderBy`, `Where`) work fine in RC1. A lot of issues with grouping though. 

> Are you able to use set operators like UNION, INTERSECT, EXCEPT, CONCAT .... in rc1 ?

No, they fail too.

**Comment by PrashanthIBM** [comment]
@AlekseyMartynov you mean to say navigation property with order by will work in RC1 ?

Will the below query work :  
var query = context.ORDERSS.Where(o => o.SHIPCOUNTRY == "Mexico").Select(o => o.Customer.CUSTOMERID);

Thanks and Regards,
Prashanth.

**Comment by AlekseyMartynov** [comment]
@PrashanthIBM 

Yes, the query (adapted to Northwind context) works fine:

    nwind.Orders
        .Where(o => o.ShipCountry == "Mexico")
        .Select(o => o.Customer.CustomerID)
        .ToArray();

**Comment by mikary** [comment]
Verified that this query throws an `InvalidOperationException` in EntityFramework.MicrosoftSqlServer 7.0.0-rc1-final, but the exception is not thrown in current dev.

The returned results appear to be incorrect due to a related issue (#5179) with navigations.

**Comment by mikary** [comment]
The test: `QueryNavigationsTestBase.GroupBy_on_nav_prop` added in #5141 for issue #3626 has the same shape as the query. Closing as resolved / duplicate
