### ISSUE TITLE
Usage of the "let" keyword breaks grouping

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/EntityFramework#3676]
Version: 7.0.0-rc1-*

Query:

    from p in nwind.Products
    let cat = p.CategoryID
    group p by cat;
    // group p by p.CategoryID; // - also fails when 'let' is present

Message:

    Expression of type '...' cannot be used for parameter of type '...' of method '...'

Full sample: https://github.com/AlekseyMartynov/ef7-bugs/tree/group-with-let

**Comment by mikary** [comment]
Verified that this query throws an `ArgumentException` in `EntityFramework.MicrosoftSqlServer 7.0.0-rc1-final`, but the exception is not thrown in current dev.

The returned results appear to be incorrect due to a related issue (#5179) with navigations.

**Comment by mikary** [comment]
Retested now that related issue has been resolved. The initial query completes successfully; however, a `NullReferenceException` is thrown in `LinqOperatorProvider.GetEnumerator` when enumerating the elements within the `IGrouping<TKey, TElement>`

```cs
[ConditionalFact]
public virtual void Let_group_by_nav_prop()
{
    AssertQuery<OrderDetail, IGrouping<string, OrderDetail>>(
        ods => from od in ods
                let customer = od.Order.CustomerID
                group od by customer
                into odg
                select odg,
        asserter: (l2oItems, efItems) =>
        {
            foreach (var pair in
                from l2oItem in l2oItems
                join efItem in efItems on l2oItem.Key equals efItem.Key
                select new { l2oItem, efItem })
            {
                Assert.Equal(
                    pair.l2oItem.Select(i => i.OrderID).OrderBy(i => i),
                    pair.efItem.Select(i => i.OrderID).OrderBy(i => i));
            }
        });
}
```
