### ISSUE TITLE
NuGet Commands: Remove EF.Commands.dll from bin on UWP

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#3682]
Currently, the commands package copies the net451 version of EntityFramework.Commands.dll to the output directory on UWP in order to work.

The problem is that .NET Native will try and compile *all* the assemblies in the output directory. We should look into a solution that doesn't leave this assembly in the output directory when compiling with .NET Native.

**Comment by natemcmaster** [comment]
Also, we should ensure that libraries is moved when EF commands are in a UWP class library.

Cref https://github.com/aspnet/EntityFramework/issues/5069#issuecomment-216654757
