### ISSUE TITLE
Query: [Nav Prop Translation] Using select in LINQ with nested properties (navigation) create inner join.

### ISSUE THREAD

**Issue by jerry2007** [aspnet/EntityFramework#3718]
When I use fluent Api in that way, that I select nested property (1..n relation) it do select with inner joins. (I would like left join)

When I use Include before select in fluent Api it throws exception Target Invocation, Null parameter source.

Can you give some tips or could you help me to solve this problém please?

**Comment by divega** [comment]
Could you provide code showing what you are trying to achieve?

**Comment by jerry2007** [comment]
db.Fakturace_ZalohovaFakturaPrijata.Select(p => new
                                    {
                                        ID = p.ID,
                                        Stredisko = p.Stredisko.Kod,
                                    })
                                    .Skip(0)
                                    .Take(20)
                                    .ToList();


this code do select but with inner join on Table 'Ciselniky_Stredko'. It will generate this Sql script:

SELECT [p].[ID], [p.Stredisko].[Kod]
FROM [Fakturace_ZalohovaFakturaPrijata] AS [p]
INNER JOIN [Ciselniky_Stredisko] AS [p.Stredisko] ON [p].[Stredisko_ID] = [p.Stredisko].[ID]
ORDER BY [p].[ID] DESC
OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY


Without select it select all colums in db with left join:
db.Fakturace_ZalohovaFakturaPrijata
.Include(p => p.Cinnost)
                                    .Skip(0)
                                    .Take(20)
                                    .ToList();

But when do this, it will throw exception:
db.Fakturace_ZalohovaFakturaPrijata
.Include(p => p.Cinnost)
                                    .Select(p=>new
                                    {
                                        p.ID,
                                        p.Cinnost.Kod
                                    })
                                    .Skip(0)
                                    .Take(20)
                                    .ToList();

An exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll but was not handled in user code

Additional information: Cíl vyvolání způsobil výjimku.

Value cannot be NULL. Name of parametr: provider: (Hodnota nemůže být NULL.
Název parametru: provider)

StackTrace (inner Exception)
   v Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   v Microsoft.Data.Entity.Query.EntityQueryable`1..ctor(IEntityQueryProvider provider)
   v Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor._CreateEntityQueryable[TResult](IEntityQueryProvider entityQueryProvider)

StackTrace
   v System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   v System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   v System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   v System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   v Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.CreateEntityQueryable(IEntityType targetEntityType)
   v Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.CreateJoinsForNavigations(QuerySourceReferenceExpression outerQuerySourceReferenceExpression, IEnumerable`1 navigations)
   v Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.<>c__DisplayClass12_0.<VisitMember>b__0(IEnumerable`1 ps, IQuerySource qs)
   v Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   v Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindNavigationPathMemberExpression[TResult](MemberExpression memberExpression, Func`3 memberBinder)
   v Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   v System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   v Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   v Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func`2 transformation)
   v Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   v Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel)
   v Microsoft.Data.Entity.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
   v Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   v Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   v Microsoft.Data.Entity.Query.QueryCompiler.<>c__DisplayClass16_0`1.<CompileQuery>b__0()
   v Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   v Microsoft.Data.Entity.Query.QueryCompiler.CompileQuery[TResult](Expression query)
   v Microsoft.Data.Entity.Query.QueryCompiler.Execute[TResult](Expression query)
   v Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   v Remotion.Linq.QueryableBase`1.GetEnumerator()
   v System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   v System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   v S5Wrapper.S5WrapperSelectQuery`1.ToList() v t:\CSWWeb\REST-API-S5\S5Wrapper\src\S5Wrapper\S5WrapperSelectQuery.cs:řádek 68
   v ApiS5.Controllers.Test1Controller.getdata() v T:\CSWWeb\REST-API-S5\ApiS5\src\ApiS5\Controllers\Test1Controller.cs:řádek 28

**Comment by Anderman** [comment]
Hi @jerry2007, you can use markup language to format code. see [Syntax highlighting](https://guides.github.com/features/mastering-markdown/)

**Comment by GunterGlad** [comment]
Also would like this please.

**Comment by maumar** [comment]
Related to https://github.com/aspnet/EntityFramework/issues/3186

**Comment by maumar** [comment]
Fixed in c4e44471b6f41f96d37b1acfbbb4cc97cd11ee89
