### ISSUE TITLE
Better exception message when DbContext does not have default ctor

### ISSUE THREAD

**Issue by Sohra** [aspnet/EntityFramework#3752]
Tested on Full .NET, in a unit test project, with EntityFramework.Commands v7.0.0-rc2-16292.

The DbContext class lives in a shared project (i.e. the glorified linked files project type) that is referenced by the unit test project, acting as the startup project.

Calling Add-Migration and providing only a name gives error:
No DbContext was found. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

Explicitly specifying the full name (includes namespace) of the DbContext with the -Context parameter and I get an error in the form:
No DbContext named 'MyNameSpace.MyDbContext' was found.

I thought at first the shared project might be causing problems, so I repeated the test in a new console project, exact same problem.  It's a public, non-abstract and non-generic class that was functioning perfectly fine in beta6 or 7 (I forget which now).

**Comment by bricelam** [comment]
Does passing your unit test project as the `-StartupProject` when invoking the command allow it to work?

**Comment by Sohra** [comment]
No, I already had the unit test project set as startup project (right click context menu).  Explicitly specifying the -StartupProject parameter (or the other -Project one, or both together) makes no difference.

Likewise in the Console project (just like the example on ef.readthedocs.org/en/latest/getting-started/full-dotnet.html shows) it has the same problem, so that suggests to me being a unit test project has nothing to do with it.

Although unrelated, I am noticing Add-Migrations doesn't like building under x64 at the moment either.

**Comment by bricelam** [comment]
Try running with `-Verbose` to get more information about what it's doing.

The 64-bit issue is tracked by #1074.

**Comment by bricelam** [comment]
What does your Startup class look like?

**Comment by Sohra** [comment]
ahh, thanks for that reference for the 64bit issue.

I don't have a startup class for a unit test project or console application - I thought those were only really required for ASP.NET projects that are hosted in IIS?

The only additional detail I really get with verbose, is a stack trace, which probably doesn't tell you anything you couldn't already have known from the error message:
Finding DbContext classes...
Microsoft.Data.Entity.Design.OperationException: No DbContext named 'wired.net.MP4Amp.Models.EntityFrameworkDbContext' was found.
   at Microsoft.Data.Entity.Design.DbContextOperations.FindContextType(String name)
   at Microsoft.Data.Entity.Design.DbContextOperations.CreateContext(String contextType)
   at Microsoft.Data.Entity.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.Data.Entity.Design.OperationExecutor.<AddMigrationImpl>d__7.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.Execute(Action action)

**Comment by bricelam** [comment]
Yeah, I deleted my comment about the `Startup` class. It didn't make any sense. :wink:

**Comment by bricelam** [comment]
Could you share your `DbContext` class?

**Comment by Sohra** [comment]
Just ignore all the comments and RC1 debugging regions, its a copy paste and I've been following this project since beta3 (:  I've omitted overrides for Commit and Rollback for brevity, but left OnConfiguring fully intact in all its verbosity.

```c#
namespace wired.net.MP4Amp.Models
{
    public class EntityFrameworkDbContext : DbContext
    {
        readonly Action<DbContextOptionsBuilder> mConfigureContext;

        public EntityFrameworkDbContext(Action<DbContextOptionsBuilder> _configureContext)
        {
            if (_configureContext == null)
                throw new ArgumentNullException(nameof(_configureContext));

            mConfigureContext = _configureContext;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder _options)
        {
            mConfigureContext(_options);
        }

        protected override void OnModelCreating(ModelBuilder _builder)
        {
            #region RC1 Debugging
            var clrType = typeof(CPlaylistEntry<CMediaFile>);
            var allClrProperties = System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperties(clrType)
                                                                                .Where(pi => IsCandidateProperty(pi))
                                                                                .Select(pi => pi.Name);
            var clrProperties = new System.Collections.Generic.HashSet<string>();
            clrProperties.UnionWith(allClrProperties);
            //clrProperties.ExceptWith(entityType.GetProperties().Select(p => p.Name));
            //clrProperties.ExceptWith(entityType.GetNavigations().Select(p => p.Name));
            foreach (var clrProperty in clrProperties)
            {
                var actualProperty = System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperty(clrType, clrProperty);
                if (actualProperty == null)
                {
                    throw new InvalidOperationException();
                }
            }
            #endregion RC1 Debugging

            var mediaFile = _builder.Entity<CMediaFile>();
            //mediaFile.Metadata.Relational()
            //mediaFile.Metadata.Sqlite()
            mediaFile.ToTable("MediaFiles");
            //Better to use SqliteTable???
            //mediaFile.ToSqliteTable("MediaFiles");
            mediaFile.HasKey(e => e.Uri);
            mediaFile.HasIndex(e => e.Uri);
            mediaFile.Property(e => e.Title).HasMaxLength(256).IsRequired();
            mediaFile.Property(e => e.Album).HasMaxLength(256);  //Allow this to be unspecified
            mediaFile.Property(e => e.Artist).HasMaxLength(256).IsRequired();
            mediaFile.Property(e => e.Number).IsRequired();
            mediaFile.Property(e => e.Year).IsRequired();
            mediaFile.Property(e => e.Genre).HasMaxLength(256).IsRequired();
            mediaFile.Property(e => e.Rating).IsRequired();
            mediaFile.Property(e => e.Uri).HasMaxLength(256).IsRequired();
            mediaFile.Property(e => e.DurationInMilliseconds).IsRequired();

            var pseudoMediaFile = _builder.Entity<CPseudoMediaFile>();
            pseudoMediaFile.ToTable("PseudoMediaFiles");
            //pseudoMediaFile.ToSqliteTable("PseudoMediaFiles");
            //NOTE: Now that TPH is supported in the prereleases, this no longer works, nor does HasAlternateKey
            //      Attempt to disable it by setting base type to null
            pseudoMediaFile.HasBaseType((string)null);
            pseudoMediaFile.HasKey(e => new { e.Uri, e.Number });
            pseudoMediaFile.HasIndex(e => e.Uri);
            pseudoMediaFile.Property(e => e.Title).HasMaxLength(256).IsRequired();
            pseudoMediaFile.Property(e => e.Album).HasMaxLength(256);  //Allow this to be unspecified
            pseudoMediaFile.Property(e => e.Artist).HasMaxLength(256).IsRequired();
            pseudoMediaFile.Property(e => e.Number).IsRequired();
            pseudoMediaFile.Property(e => e.Year).IsRequired();
            pseudoMediaFile.Property(e => e.Genre).HasMaxLength(256).IsRequired();
            pseudoMediaFile.Property(e => e.Rating).IsRequired();
            pseudoMediaFile.Property(e => e.Uri).HasMaxLength(256).IsRequired();
            pseudoMediaFile.Property(e => e.DurationInMilliseconds).IsRequired();
            //Unique to Pseudo
            pseudoMediaFile.Property(e => e.TrackNumber).IsRequired();
            pseudoMediaFile.Property(e => e.OffsetMilliseconds).IsRequired();

            var mediaFilePlaylistEntry = _builder.Entity<CPlaylistEntry<CMediaFile>>();
            mediaFilePlaylistEntry.ToTable("MediaFileEntries");
            //mediaFilePlaylistEntry.ToSqliteTable("MediaFileEntries");
            //Workaround for EF not supporting Entity as a Key
            //Suggestion here: http://data.uservoice.com/forums/72025-entity-framework-feature-suggestions/suggestions/8102202-support-another-entity-as-a-key
            //If attempt to set Entity as Key, SaveChanges throws: The 'MediaFile' on entity type 'CPlaylistEntry<CMediaFile>' does not have a value set and no value generator is available for properties of type 'CMediaFile'. Either set a value for the property before adding the entity or configure a value generator for properties of type 'CMediaFile'.
            //Although it is actually set, its value is an object (IMediaFile) and not a basic value type that I think is required
            //mediaFilePlaylistEntry.Key(e => e.MediaFile);
            //Trying to setup key as a nested property throws: The properties expression 'e => e.MediaFile.Uri' is not valid. The expression should represent a property access: 't => t.MyProperty'. When specifying multiple properties use an anonymous type: 't => new { t.MyProperty1, t.MyProperty2 }'.
            //mediaFilePlaylistEntry.Key(e => e.MediaFile.Uri);
            //Using a Shadow Property so as not to pollute our CLR type . . . (set this up in the Foreign Key below all in one go, it get's the data type)
            //Explicit declare the shadow state property since the foreign key below throws saying Uri can't exist on the type as its not marked as shadow state
            mediaFilePlaylistEntry.Property<string>("Uri");
            //Declare this as the key for the entity
            mediaFilePlaylistEntry.HasKey("Uri");
            //Should be tags collection, but EF7 can't handle complex types yet, so TagsCsv introduced to do the appropriate serialisation and deserialisation
            //Could make this a shadow property, but it means I'll have to override SaveChanges, DetectChanges to pick up any modified, and recalculate TagsCsv
            //each commit.  Might be easier to just leave this property in place in the meantime.
            mediaFilePlaylistEntry.Property(e => e.TagsCsv).IsRequired();
            //Workaround for EF not supporting Entity as a Key
            //mediaFilePlaylistEntry.Reference(e => e.MediaFile).InverseReference()
            mediaFilePlaylistEntry.HasOne(e => e.MediaFile)
                                  .WithOne()
                                  .HasForeignKey(typeof(CPlaylistEntry<CMediaFile>), "Uri");  //Want this to be e.MediaFile.Uri, but it can't go a level down, so using a shadow state property instead
            //This will actually create Key shadow property if not already defined on the type
            //Means I don't need to define it earlier, but do I need to define it as a primary key?
            //or is that a given?  Or can I continue to declare the navigation property as primary key
            //as it should be?  There's also questions about writing this, and loading navigation property
            //when reading entity from the database.  A bunch of things need to be tested.  All this
            //to get rid of the Key property messing up my CLR type, and yet it's still a workaround since
            //EF7 can't use an entity as a key
            //mediaFilePlaylistEntry.Reference(e => e.MediaFile)
            //                      .InverseReference()
            //                      .ForeignKey(typeof(CPlaylistEntry<CMediaFile>), "Key");  //Want this to be e.MediaFile.Uri, so I can remove e.Key from the class
            //Unit test project ought to do it
            //Contrary to the comment on the ForeignKey(type, params string[] foreignKeyPropertyNames) about auto creating shadow, the above throws:
            //The property 'Uri' cannot exist on entity type 'wired.net.MP4Amp.Models.CPlaylistEntry<wired.net.MP4Amp.Models.CMediaFile>'
            //because the property is not marked as shadow state and no corresponding CLR property exists on the underlying type.

            var pseudoMediaFilePlaylistEntry = _builder.Entity<CPlaylistEntry<CPseudoMediaFile>>();
            pseudoMediaFilePlaylistEntry.ToTable("PseudoMediaFileEntries");
            //pseudoMediaFilePlaylistEntry.ToSqliteTable("PseudoMediaFileEntries");
            //Workaround for EF not supporting Entity as a Key
            //pseudoMediaFilePlaylistEntry.Key(e => e.MediaFile);
            //pseudoMediaFilePlaylistEntry.Key(e => new { e.MediaFile.Uri, e.MediaFile.Number });
            //Explicit declare the shadow state properties as Foreign Key fails to implicitly do it like the comment says it should
            pseudoMediaFilePlaylistEntry.Property<string>("Uri");
            pseudoMediaFilePlaylistEntry.Property<uint>("Chapter");
            pseudoMediaFilePlaylistEntry.HasKey("Uri", "Chapter");
            //Should be tags collection, but EF7 can't handle complex types yet, so TagsCsv introduced to do the appropriate serialisation and deserialisation
            pseudoMediaFilePlaylistEntry.Property(e => e.TagsCsv).IsRequired();
            //Workaround for EF not supporting Entity as a Key
            //pseudoMediaFilePlaylistEntry.Reference(e => e.MediaFile).InverseReference();
            pseudoMediaFilePlaylistEntry.HasOne(e => e.MediaFile)
                                        .WithOne()
                                        .HasForeignKey(typeof(CPlaylistEntry<CPseudoMediaFile>), "Uri", "Chapter");
        }

        #region RC1 Debugging
        public static bool IsStatic(System.Reflection.PropertyInfo property)
            => (property.GetMethod ?? property.SetMethod).IsStatic;

        public static bool IsCandidateProperty(System.Reflection.PropertyInfo propertyInfo)
           => !IsStatic(propertyInfo)
               && propertyInfo.GetIndexParameters().Length == 0
               && propertyInfo.CanRead;

        #endregion

        public IPlaylistRepository PlaylistEntries { get; }

    }
}
```

**Comment by bricelam** [comment]
Ah, you don't have a default constructor. Add one, or add a class like the following to your project.
```C#
class EntityFrameworkDbContextFactory : IDbContextFactory<EntityFrameworkDbContext>
{
    public EntityFrameworkDbContext Create()
        => new EntityFrameworkDbContext(
            options => options.UseSqlServer("" + new SqlConnectionStringBuilder
                {
                    DataSource = @"(localdb)\MSSQLLocalDB",
                    InitalCatalog = "TheTestDatabase",
                    MultipleActiveResultSets = true
                }));
}
```
This will tell the migrations Commands how to instantiate your DbContext.

**Comment by bricelam** [comment]
We should probably change the commands find the `DbContext` and write an error saying that it doesn't have a default constructor. They currently just ignore types that don't have a default constructor.

**Comment by Sohra** [comment]
silly me!  I must have stripped that out accidentally.  Sorry for the false alarm.  I'll test this resolves all issues later today and close.  Thanks Brice

**Comment by bricelam** [comment]
Don't close (or apologize)! The error message you got wasn't helpful; that's a bug. :wink:

**Comment by Sohra** [comment]
I know its a different error, but with the same code when I call EnsureCreated() I get:
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=The property 'wired.net.MP4Amp.Models.IPlaylistEntry.MediaFile' on entity type 'wired.net.MP4Amp.Models.CPlaylistEntry<wired.net.MP4Amp.Models.CMediaFile>'
  has not been added to the model or ignored.
  Source=EntityFramework.Core
  StackTrace:
       at Microsoft.Data.Entity.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
       at Microsoft.Data.Entity.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
       at Microsoft.Data.Entity.ModelBuilder.Validate()
       at Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
       at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
       at Microsoft.Data.Entity.Infrastructure.DatabaseFacade.EnsureCreated()
       at wired.net.MP4Amp.App..ctor()
       at wired.net.MP4Amp.Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p)
  InnerException: 

Not sure if you prefer me to list this separately, as its obviously a different issue, or leave it in here?  I specify this property in a relationship using HasOne, so I think this has added it to the model...

**Comment by smitpatel** [comment]
@Sohra - It is different issue and related to model building, Can you file a new issue for it? Also please provide your domain classes and `OnModelConfiguring` code.

**Comment by Sohra** [comment]
@smitpatel Sorry for the delay in this.  I've logged #3790 with the requested information.

**Comment by bricelam** [comment]
Moving to `7.0.0-rc2` since it's closely related to #3061
