### ISSUE TITLE
Including Many-To-Many Relation in Select

### ISSUE THREAD

**Issue by chbach** [aspnet/EntityFramework#3758]
Hi, 

I have a many to many relationship between my models `NewsEntry` and `Tag` via the "pivot" model `Taggings`. On the index view of my NewsEntry page I don't want to include all columns of `NewsEntry` in my query result. However, it somehow throws an error when selecting the `Taggings` relation. Here is the working version including all fields: 

```c#
var query = Db.NewsEntries.Include(e => e.Taggings);
```

Producing the following query: 
```sql
SELECT "t"."NewsEntryId", "t"."TagId"
FROM "Tagging" AS "t"
INNER JOIN (
    SELECT DISTINCT "t0".*
    FROM (
        SELECT "e"."Id", "e"."Abstract", "e"."Date", "e"."Image", "e"."Querystring", "e"."Text", "e"."Title", "e"."URL"
        FROM "NewsEntry" AS "e"
        ORDER BY "e"."Date" DESC, "e"."Id"
        LIMIT 12 OFFSET 0
    ) AS "t0"
) AS "e" ON "t"."NewsEntryId" = "e"."Id"
```

Then I tried to map the result to a smaller version of the object like this: 

```c#
var entries = query.Select(e => new NewsEntry { 
    Id = e.Id,
    Title = e.Title,
    URL = e.URL,
    Taggings = e.Taggings,
    Date = e.Date
});
```

Producing the following error: 

```txt
ArgumentException: Argument types do not match
System.Linq.Expressions.Expression.Bind (System.Reflection.MemberInfo member, System.Linq.Expressions.Expression expression) <0x5aeac80 + 0x000bf> in <filename unknown>, line 0
```

If I don't include the taggings in the select, everything works as expected.

I found out that e.Taggings somehow still only includes `int` values (after converting it to a list) and hasn't been populated with the Tagging objects. My guess is the query returns just a row containing the TagId and EF later automagically populates the relation, so I would have to select the TagId. But my model does not contain a field for TagId. Is there some way around it or do I have to select all columns for now?

Thanks for your help, 

Christoph

**Comment by maumar** [comment]
@chbach could you provide full code listing of the entities used as well as DBContext? We have made some bug fixes in this area recently and with functional repro I could quickly check whether this issue has been addressed already

**Comment by chbach** [comment]
Thanks for your quick reply. Here are the classes:

Models: 

```c#
public class NewsEntry
{
    public int Id { get; set; }
    public String Title { get; set; }
    public String Abstract { get; set; }
    public DateTime Date { get; set; }
    public String Text { get; set; }
    public String URL { get; set; }
    public byte[] Image { get; set; }
    public String Querystring { get; set; }
    public virtual ICollection<Tagging> Taggings { get; set; }        
}

public class Tag
{
    public int Id { get; set; }
    public String Name { get; set; }
    public String Keywords { get; set; }
    public virtual ICollection<Tagging> Taggings { get; set; }
}

public class Tagging
{
	public int NewsEntryId { get; set; }
	public virtual NewsEntry NewsEntry { get; set; }
	
	public int TagId { get; set; }
	public virtual Tag Tag { get; set; }
}
```

DbContext: 

```c#
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
{
    public DbSet<NewsEntry> NewsEntries { get; set; }
    public DbSet<Tag> Tags { get; set; }
    public DbSet<Tagging> Taggings { get; set; }
    
    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.Entity<Tagging>().HasKey(x => new { x.NewsEntryId, x.TagId });           
    }
}
```

**Comment by maumar** [comment]
Update: this is still an issue in latest bits. Will investigate.

**Comment by divega** [comment]
@maumar Wouldn't the query with `Include()` also issue two queries and glue them together on the client in this case?

**Comment by maumar** [comment]
@divega good point, somehow it slipped my mind
@chbach please ignore the second paragraph of my previous comment

**Comment by chbach** [comment]
Just to make my case clear, I want to perform the select on the database since I don't want to transfer the Image BLOB from the database to the webserver in the query, because I don't need the content of this column in that particular case. So a client-side solution doesn't really help. 

Nonetheless thanks for your investigation so far.

**Comment by maumar** [comment]
Fixed in aef1c6308365a0e456e7b3c1d2995cdd6eeef751

**Comment by maumar** [comment]
Note that this fixes the exception - the scenario will now work, however it will still produce N+1 queries, where N is a number of entities in the parent collection. I will open a separate issue to handle projection from the Include

**Comment by maumar** [comment]
Opened issue #3878 to track this
