### ISSUE TITLE
Better Exception Message when provider services are not added to ServiceProvider

### ISSUE THREAD

**Issue by angelsix** [aspnet/EntityFramework#3759]
I am setting up unit tests so for the Entity Framework I use "EntityFramework.InMemory": "7.0.0-beta8".

Then the services in the test environment are:

services.AddEntityFramework()
    .AddSqlServer()
    .AddDbContext<StorageContext>();

The StorageContext has the OnConfiguring which gets run successfully and does:

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
      optionsBuilder.UseInMemoryDatabase();
}

However when I then get the StorageContext from the services (or any other way) it throws with the error:

Exception thrown: 'System.InvalidOperationException' in EntityFramework.Core.dll

Additional information: No database providers are configured. Configure a database provider by overriding OnConfiguring in your DbContext class or in the AddDbContext method when setting up services.

Yet it is configured as I called the UseInMemoryDatabase().

If I add optionsBuilder.UseSqlServer("connectionStringHere") instead of UseInMemoryDatabase() it works by using the actual database, so it seems its purely the UseInMemoryDatabase() with the issue.

**Comment by divega** [comment]
Try calling `AddInMemoryDatabase()` after `AddEntityFramework()`. 

I think that should fix it, but the exception you got could have been more helpful.

**Comment by angelsix** [comment]
Thanks that fixed it. Yes I think if the module could detect the missing AddEntityFramework and report a more helpful message that would help others that miss that bit out too.

**Comment by divega** [comment]
Reopening to consider exception improvement.

**Comment by ajcvickers** [comment]
@rowanmiller Reviewed the messages when we made updates to the D.I. behavior recently, so closing this.
