### ISSUE TITLE
Handle provider specific metadata in reverse engineer

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#3766]
The generic Microsoft.Data.Entity.Scaffolding.Metadata.ColumnModel contains an SqlServer-specific Identity field, and IndexModel contains Clustered. There should be a better way to represent provider-specific column metadata...

**Comment by natemcmaster** [comment]
@roji Are there Postgres-specific fields you need? Our original intention was to make SQL Server specific concepts optional. `RelationalScaffoldingModelFactory` ignores the `bool?` flag when null. e.g. SQLite does not have these concepts either, so the `SqliteDatabaseModelFactory` leaves the Identity and Clustered flags null.

**Comment by roji** [comment]
Ideally yes... For example, PostgreSQL allows you to specify [which "method" you want to use on an index](http://www.postgresql.org/docs/current/static/indexes-types.html)  (e.g. btree). I've already exposed this in EF7 `NpgsqlIndexAnnotations`, which gets picked up by the migrations. The same needs to happen when scaffolding - I should be able to get the index method from the database and generate it in the code...

**Comment by rowanmiller** [comment]
@natemcmaster is working on this atm

**Comment by natemcmaster** [comment]
In our most recent design meeting, we had what I felt was an even split between solving this with annotations or inheritance. In making this design change, we want to ensure we don't paint ourselves into a corner for #3438. Eventually we want to use EF to materialize the database model, not ADO.NET.

Consequently, here are the two ways to solve this:
 - Inheritance #3783. EF would either need a generic DbContext or need better handling of inheritance
 - Annotations #3831. EF would need a way to materialize annotations.

As this is a provider-writer API untouched by most users, @roji  @ErikEJ do you care to weigh in?

**Comment by ErikEJ** [comment]
@natemcmaster I assume you mean #3831 by "this design change" ? For my part, this simply means more code in the provider, as SQL CE features/data types are a subset of SQL Server's. 

For the SQL CE provider, only IsIdentity is relevant/supported, not datatime precision or clustered indexes

**Comment by roji** [comment]
Sorry for not commenting earlier, this slipped through.

Am not 100% clear on overall design, but since the scaffolding model classes (e.g. ColumnModel) seem to simply be a way to communicate between a given provider's DataModelFactory and the same provider's ScaffoldingModelFactory, inheritance seem to be a more natural, less difficult way of extending the model. I think I might be missing something though (can't see why introducing inheritance here would require a generic DbContext...). Annotations would also work OK.
