### ISSUE TITLE
Automate runtime directive generation on UWP

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#3801]
Extend the UWP build process to add project-specific runtime directives. This ideally runs post-CSC pre-ILC. This addresses impossible problem of *statically* generating directives for all possible `Snapshot<T1...T30>` types (minimum 2.35x10^32 are possible).

See https://github.com/aspnet/EntityFramework/pull/3777#issuecomment-157545631.

**Comment by rowanmiller** [comment]
@natemcmaster if we don't do this now are we just limited to not using certain query methods, or are there other issues we've run into?

**Comment by natemcmaster** [comment]
@rowanmiller Users could still (in theory) provide their own runtime directives for all of the `Snapshot<T>` types needed for their project. Without these, anything that uses change tracking will fail. This means all queries, update pipeline, etc.

**Comment by rowanmiller** [comment]
Right, so this all regressed after RC1 because of the changes we made? And we can't handle these new types with the existing approach we have?

**Comment by natemcmaster** [comment]
Yes to both questions. RC2 does not work on UWP and won't until we fix this (or until .NET Native itself changes.)

**Comment by divega** [comment]
@rowanmiller I think this one belongs un RC2.

**Comment by rowanmiller** [comment]
Agreed

**Comment by natemcmaster** [comment]
Let's discuss how this might work from a user-perspective. 

I've got [an initial prototype](https://github.com/natemcmaster/EntityFramework/tree/757e88ef89e33c04014e9ae9449a8767eba3b46d) so that the Getting Started in UWP guide works in RC2.

It adds new PowerShell command, ```Scaffold-Directives```. This command creates a file containing all runtime directives. For example, in the EFGettingStarted project from the docs, it makes [`Properties\EntityFramework.g.rd.xml`](https://gist.github.com/natemcmaster/fa49b7978de5b467fd5c).

```xml
<!--This file was automatically generated and may be overwritten. Do not edit this file manually.-->
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Library>
    <TypeInstantiation Name="System.Collections.Generic.IEnumerable" Arguments="EFGetStarted.UWP.Blog" Dynamic="Required All" />
    <TypeInstantiation Name="Microsoft.Data.Entity.Metadata.Internal.ClrPropertySetter" Arguments="EFGetStarted.UWP.Blog, System.String" Dynamic="Required All" />
    <TypeInstantiation Name="Microsoft.Data.Entity.ChangeTracking.Internal.Snapshot" Arguments="System.Int32, System.String" Dynamic="Required All" />

...etc...
```

**Pros:** only runs once, not on every build. Does not hide the magic. Users could edit the file if they want more control

**Cons:** poor discoverability. Not automatically synced with code.

One alternative: we plugin automatically to MSBuild.

Thoughts?

**Comment by ErikEJ** [comment]
I like the idea of the developer being in control.

If you do not plugin with MS Build, you need a way to at least inform the developer, that the file is not present but required. Maybe display a readme.txt when the EF.Sqlite package is installed in a UWP project?

**Comment by divega** [comment]
One idea @natemcmaster and I have discussed is the possibility of having an MSBuild task that does this automatically but is smart enough to no-op if there haven't been any changes in the EF model or the EF assemblies since last time the directives file was generated. This would probably involve computing a hash of the relevant parts of the model and persisting that hash to the file. It would only be beneficial if generating the directives file becomes very slow compared to the total compilation time (and compared to the time it would take to compute such hash).

**Comment by galich** [comment]
let me share my experience that I've got with EF, UWP and .NETNative - TLDR; it fails badly.

the project is not large, UWP app, few screens, few libraries (like JSON.NET and MoonSharp) that could add some dynamic/reflection based code. Nothing fancy. Everything works. But we need database and we gave a try to NuGet package "7.0.0-rc2-16583", made just 4 small entities, probably twice as much of code as you can find in UWP sample app.

The machine is Surface 2 Pro 8GB RAM. At build time it peaked around 4-4.5GB for .NET Native tools and after 10 minutes it crashes with "out of memory" message. Judging by the size of <project>.reflectionlog.csv I can see that with EF it is above 90MB, without EF it is less than 8MB.

This makes me believe that EF got too much of runtime directives and metadata to preserve. While the crash belongs to .NET Native (please point me at the right place so I can report this issue to .NET Native guys), it was EF that caused this issue.

Feel free to get in touch, I can reveal a bit more and assist if you need on a private channel like sergey.galich@outlook.com (can't speak of this app in public). And let me know if I'm spamming in the wrong issue and you would like me to create new one.

**Comment by natemcmaster** [comment]
@galich thanks for the information. The problems you are experiencing are exactly what this a solution to this issue should address. Our nightly builds don't yet have any fixes to these problems, but should soon. Stay posted to this issue for updates.

**Comment by galich** [comment]
@natemcmaster thanks, i'll keep trying nightlies to see when the issue will go away and report here
