### ISSUE TITLE
Commands: Look for ConfigureServices in Program

### ISSUE THREAD

**Issue by dneimke** [aspnet/EntityFramework#3802]
I created a Console project and configured it to read the connection string during Startup and the app ran fine as expected.  However, when I tried to use migrations using EF.Commands, I got an error saying that no database providers were configured.

To work around that I ended up creating a DbContextFactory which the Commands read and things worked fine.

https://github.com/dneimke/coffeestore/blob/develop/src/EF7Demo.CoffeeStore/Model/DbContextFactory.cs

I was surprised that I had to create the Factory as I do not need to do this for an ASP Web Application.  Is this a different behavior for apps other than ASP.NET Web Application and was I right to create the Factory to work around this?

**Comment by rowanmiller** [comment]
We have some special logic for ASP.NET 5 apps to run the code from startup and then resolve your context from DI. 

cc @bricelam who was looking at some improvements so that we could do the same outside of ASP.NET 5... not sure where we got to with those? Note there is a [ConfigureServices in Program](https://github.com/dneimke/coffeestore/blob/develop/src/EF7Demo.CoffeeStore/Program.cs#L104).

**Comment by dneimke** [comment]
Thanks.  Yeah I know that there is ConfigureServices in Program but I still couldn't get the EF Commands to work with just ConfigureServices in Program.

It wasn't until I added the Factory that I could generate Migrations

**Comment by bricelam** [comment]
The behavior is the same, but the `ConfigureServices` method still needs to be in a class called `Startup`. Looking inside `Program` came up during the design meeting, but we decided to stick with just `Startup` everywhere for now.

**Comment by dneimke** [comment]
Ahh... got it.  Thx

**Comment by dneimke** [comment]
I moved all of that code into a Startup.cs and now I no longer need the Factory.  Thanks for the help!

**Comment by bricelam** [comment]
I've updated the title of this bug to reflect your original expectations so we can discuss it as a team again.

**Comment by bricelam** [comment]
We decided to look search for `Program` and `App` in addition to `Startup`.

**Comment by dneimke** [comment]
That's awesome, thanks guys!
