### ISSUE TITLE
EF 7 LINQ query with .Select() including collection throws ArgumentNullException when .Take() is used

### ISSUE THREAD

**Issue by jemiller0** [aspnet/EntityFramework#3804]
I found that the query below throws an ArgumentNullException when used with EF 7 RC 1. It works in EF 6. If you comment out the .Take(100), the query works. Also, it doesn't matter if there are any rows in the database. Initially, I was using .FirstOrDefault() which has the same problem, but, I found that the problem even occurs if you use .Any(). 

```c#
using Microsoft.Data.Entity;
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var bc = new BlogContext())
            {
                bc.Database.EnsureCreated();
                for (int i = 0; i < 5; i++)
                {
                    var b = new Blog { };
                    bc.Blogs.Add(b);
                    var p = new Post { Blog = b };
                    bc.Posts.Add(p);
                }
                bc.SaveChanges();
                bc.Blogs
                    .Take(100)
                    //.Select(b2 => b2.Posts.Any())
                    .Select(b2 => b2.Posts.FirstOrDefault().Content)
                    .ToArray();
            }
        }
    }

    public class BlogContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Blogs;Trusted_Connection=True;");
    }

    public class Blog
    {
        public int? Id { get; set; }
        public ICollection<Post> Posts { get; set; }
    }

    public class Post
    {
        public int? Id { get; set; }
        public string Content { get; set; }
        public int? BlogId { get; set; }
        public Blog Blog { get; set; }
    }
}
```

**Comment by rowanmiller** [comment]
Appears to be the same code as https://github.com/aspnet/EntityFramework/issues/3807 but one reports bad SQL and the other an exception

**Comment by jemiller0** [comment]
Yes, the code is almost the same. Basically, if you have a Take(), it fails with an exception. If you comment that out, it works, however, the generated SQL looks wrong. It works, but, it would be very inefficient if the table had a large number or rows since it isn’t filtering and is querying for the entire table (the subqueries).

Jon

**Comment by rowanmiller** [comment]
Ok I see now that your comments mention that commenting out the Take makes it work. We were just skimming you repro code and the Take is commented out - so we assumed you saw the error with the code listing provided. I updated the listing to be the code that reproduces the issue.

**Comment by jemiller0** [comment]
OK, thanks.

**Comment by creeve** [comment]
I found that calling .Take() before .Select() throws a TargetInvocationException, while calling Take after Select works seemingly correctly.  The ordering of these wasn't a problem in EF 6.  I don't know why my exception is different from jemiller0's because it seems like I encountered the exact same problem.

I'm also on EF 7 RC 1.

**Comment by ro3y** [comment]
Hello,

I am working on large scale project with my team and we have started using EF7. We have encountered the same bug as creeve TargetInvocationException. I was wondering is there any quick fix or should we go back to EF6?

**Comment by ErikEJ** [comment]
@ro3y consider waiting for rc2

**Comment by robertledinski** [comment]
Just found some workaround. First use select, then .AsQuerayable().Skip().Take().ToList(). That should do the trick. Works for me.

**Comment by kbekkenutte** [comment]
Same problem here, @robertledinski workaround indeed does the trick. Note that the issue can also be reproduced when using simple navigation properties. My reproduction:
`    public class Foo {
        public int Id { get; set; }
        public Bar Bar { get; set; }
    }
    public class Bar {
        public int Id { get; set; }
        public string Test { get; set; }
    }
    public class AppContext : DbContext    {
        public DbSet<Foo> Foo { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder o) => o.UseSqlServer("...");
    }

    void Test()
    {
        using (var c = new AppContext())
        {
            var r = c.Foo
                .Take(1) // this will cause an exception
                .Skip(1) // this will also cause an exception
                .Select(x => x.Bar.Test) // when selecting a property of a relation that is not part of the foreign key
                //.Select(x => x.Bar.Id) // but not if selecting the primary key instead
                .ToList();
        }
    }`

**Comment by mikary** [comment]
Verified that this issue reproduces in `EntityFramework.MicrosoftSqlServer 7.0.0-RC1-final` but it does not throw the exception in the current dev branch.
