### ISSUE TITLE
One-to-one relationship with navigation properties on both ends throws StackOverflowException

### ISSUE THREAD

**Issue by jparish9** [aspnet/EntityFramework#3806]
Windows 10, VS 2015, IIS Express, SQL Server Express 2014, EF 7.0.0-rc1-final, ASP.NET 6.0.0-rc1-final

After upgrading to RC1, I am seeing a StackOverflowException with the following one-to-one relationship setup.  This setup was working fine in beta8.

Models:
```c#
    public class Blog
    {
        public int BlogId { get; set; }

        public string Title { get; set; }

        public virtual BlogMetadata BlogMetadata { get; set; }
    }
```

```c#
    public class BlogMetadata
    {
        [Key, ForeignKey("Blog")]
        public int BlogId { get; set; }

        public string Metadata { get; set; }

        public virtual Blog Blog { get; set; }
    }
```

FK setup:
```c#
   modelBuilder.Entity<Blog>().HasOne(b => b.BlogMetadata).WithOne();
```

The FK setup line throws `StackOverflowException` after upgrading to RC1 (but not in beta8).

The `StackOverflowException` is not thrown if I remove the navigation property
`public virtual Blog Blog {get; set;}` from `BlogMetadata`.

**Comment by smitpatel** [comment]
@jparish9 - Thank you for reporting this bug. It does appear in RC1 bits due to relationship building convention calling each other while trying to create 2 relationships.
There will be 2 relationships. One is configured explicitly and the other one will use `Blog` navigation property and `BlogId` foreign key property (FKAttribute).
Though the issue has been fixed in some other changes after RC1.
Work-around would be to configure the other relationship explicitly.
If you add this code in `OnModelCreating` then it will work
```C#
modelBuilder.Entity<BlogMetadata>().HasOne(e => e.Blog).WithOne();
modelBuilder.Entity<Blog>().HasOne(b => b.BlogMetadata).WithOne();
```

**Comment by jparish9** [comment]
@smitpatel Thank you for the workaround, it seems to work and is good enough for now.

Models w/annotations:
```c#
    public class Blog
    {
        public int BlogId { get; set; }

        public string Title { get; set; }

        [ForeignKey("BlogId")]
        public virtual BlogMetadata BlogMetadata { get; set; }
    }
```
```c#
public class BlogMetadata
    {
        [Key]
        public int BlogId { get; set; }

        public string Metadata { get; set; }

        public virtual Blog Blog { get; set; }
    }
```
FK configuration:
```c#
            modelBuilder.Entity<BlogMetadata>().HasOne(e => e.Blog).WithOne();
            modelBuilder.Entity<Blog>().HasOne(b => b.BlogMetadata).WithOne();
```
Now the 1-1 relationship is correctly configured.  (Without the `[ForeignKey("BlogId")]` annotation, it does not throw `StackOverflowException`, but an extra column `BlogMetadataBlogId` is created in `Blog`.)

Thank you for the quick response!

**Comment by rowanmiller** [comment]
If you don't want two separate relationships, then this is the config you want:

```c#
modelBuilder.Entity<Blog>()
    .HasOne(b => b.BlogMetadata)
    .WithOne(m => m.Blog)
    .HasForeignKey<BlogMetadata>(m => m.BlogId);
```

**Comment by smitpatel** [comment]
This works fine in latest codebase. Slightly different variation of this is covered by #3832
