### ISSUE TITLE
Allow reusing column names for multiple properties

### ISSUE THREAD

**Issue by poke** [aspnet/EntityFramework#3821]
With RC1, I can no longer reuse column names for multiple properties. This was introduced with change e6e9449d20712b24583cd3bb162abdf61c9d2948.

I have two very similar entities which only differ by some properties, so I have a common base type which I use throughout my application to work with those two types more efficiently. Each of the entities has two different id properties.

For one of those entities, both id properties come from unique columns from the database. However, for the other entity, there is only one id column, so I want to fill both properties from the same column.

This previously worked just fine:

```
entity.HasKey(item => item.Id);
entity.Property(item => item.Id).HasColumnName("ID");
entity.Property(item => item.InternalId).HasColumnName("ID");
```

But since upgrading to RC1, EF7 complains that I can only use a column name once. Is there any way to allow this, or alternatively to just disable the validation for this type?

**Comment by rowanmiller** [comment]
Agreed that we could enable this (albeit that you'd need to know what you are doing as the update pipeline may not work - such as when you assign different values to each property). We aren't going to relax it right now, so moving to backlog for post-RTM.

**Comment by poke** [comment]
Do you have any suggestion for a quick fix / workaround in the meantime? This is currently blocking me from updating to RC1.

**Comment by rowanmiller** [comment]
Override the property from the base type and just have it get/set the property from the derived type?

**Comment by poke** [comment]
Yeah, I should have have thought about that myself… This is working for my purposes for now, thanks :)

**Comment by bricelam** [comment]
@AndriySvyryd Is this possible now?

**Comment by AndriySvyryd** [comment]
@bricelam Yes, should work.
