### ISSUE TITLE
Improve exception message when we can't map a property

### ISSUE THREAD

**Issue by poke** [aspnet/EntityFramework#3822]
My entity includes a property that only has a getter, e.g. something like this:

    public string FullName
    {
        get { return FirstName + " " + LastName; }
    }

Previously, this was automatically ignored by EF when building the model. But now, I receive the following error:

> No backing field could be discovered for property 'Example.User.FullName' and the property does not have a setter. Either use a backing field name that can be matched by convention, annotate the property with a backing field, or define a property setter.

I had to add an explicit `entity.Ignore(x => x.FullName)` to the model builder, in order to fix this. But before RC1, this was just working fine without having to explcitly ignore properties. When and why was this changed?

**Comment by rowanmiller** [comment]
This was an intentional change we made. We now include all properties in the model since folks would often not realize that things were being excluded. We should change that error message though to tell you that you can use `Ignore(...)` or `[NotMapped]` to exclude it.

**Comment by poke** [comment]
Ah, I see, thanks for the information.

I would welcome if there was also a way to disable automatic discovery for entities completely. So that you need to mention all properties explicitly in the model builder in order to get them mapped. Similarly how you can switch from opt-out to opt-in with Json.Net which requires you to annotate all members you actually want to serialize.

**Comment by rowanmiller** [comment]
@AndriySvyryd is property discovery implemented as a convention? i.e. is it something you would be able to remove once we have a public convention surface?

**Comment by AndriySvyryd** [comment]
Yed
