### ISSUE TITLE
Table alias collision in generated SQL with subquery (MSSQL)

### ISSUE THREAD

**Issue by jparish9** [aspnet/EntityFramework#3826]
Windows 10, VS 2015, IIS Express, SQL Server Express 2014, EF 7.0.0-rc1-final, ASP.NET 6.0.0-rc1-final

I am seeing incorrect SQL generated with subqueries when the tables involved begin with the same letter.

 Models:
```c#
public class Blog
{
        public int BlogId { get; set; }

        public string Title { get; set; }

        public ICollection<BlogPost> BlogPosts { get; set; }
}
```
```c#
public class BlogPost
{
        public int BlogPostId { get; set; }

        public int BlogId { get; set; }

        public Blog Blog { get; set; }

        public string PostText { get; set; }
}
```
FK setup:
```c#
    modelBuilder.Entity<Blog>().HasMany(b => b.BlogPosts).WithOne(p => p.Blog);
```

Query:
```c#
   _dbContext.Blogs.Where(b => b.BlogPosts.Count == 0).ToList();
```

Generated SQL:
```sql
SELECT [b].[BlogId], [b].[Title]
FROM [Blog] AS [b]
WHERE (
    SELECT COUNT(*)
    FROM [BlogPost] AS [b]
    WHERE [b].[BlogId] = [b].[BlogId]
) = 0
```

With test data of 2 blogs, 2 posts for blog 1 and 0 for blog 2, this query incorrectly returns 0 results (should return one result, namely blog 2).  If `BlogPost` in the subquery is aliased to something other than [b] it works fine, e.g.:

```sql
SELECT [b].[BlogId], [b].[Title]
FROM [Blog] AS [b]
WHERE (
    SELECT COUNT(*)
    FROM [BlogPost] AS [bp]
    WHERE [bp].[BlogId] = [b].[BlogId]
) = 0
```

**Comment by smitpatel** [comment]
The issue here is,
For generated subquery, when we create table alias, we use first character of the entity in lower case. If that clashes with user defined alias then error happens. Simple workaround for now would be to use different character like this:
``` _dbContext.Blogs.Where(p => p.BlogPosts.Count == 0).ToList();```
