### ISSUE TITLE
Relative directory passed to Scaffold-DbContext for OutputDirectory parameter creates a project directory called "."

### ISSUE THREAD

**Issue by esmith-blackrat** [aspnet/EntityFramework#3830]
**Relevant Assemblies**
EF 7.0.0-rc1-final
EntityFramework.Commands.7.0.0-rc1-final
EntityFramework.MicrosoftSqlServer.Design.7.0.0-rc1-final

Visual Studio 2015, .NET 4.6 Console Application

When running `Scaffold-DbContext` from the Package Manager Console, if you pass a directory in the style of ".\Models" to argument `-OutputDirectory`, a project folder is added called "." with the child directory "Models".

As a user, I assumed the `-OutputDirectory` parameter expected (or at least would work with) this type of path as it does with other PowerShell cmdlets.

As a side note, if you delete the "." folder from within Visual Studio, it deletes as much as it can from the project folder on the file system, which is unfortunate.

**Comment by lajones** [comment]
Fixed with PR #3959.
