### ISSUE TITLE
Reverse Enginer: Support type aliases (user-defined data types)

### ISSUE THREAD

**Issue by jonnybee** [aspnet/EntityFramework#3843]
I tried to reverse engineer the AdventureWorks 2008 database and got errors on custom datatype is SQL Server during reverse enginneer. 

"Could not find type mapping for column 'Person.AddressType.Name' with data type 'Name'. Skipping column."

Moved the following to #3941 ~~Reverse engineering also failed to create default value on Decimal datatype: 
"For column Purchasing.ShipMethod.ShipBase unable to convert default value ((0.00)) into type System.Decimal. Will not generate code setting a default value for the property ShipBase on entity type ShipMethod."~~ 

This did work in EF6 and should also work in EF7!

**Comment by rowanmiller** [comment]
@lajones - if a custom type is just an alias for a built-in type (i.e. it's a "user-defined data type" on SQL Server) then we should be able to scaffold it right? We just use the type mapper to get the CLR type for the property based on the underlying built-in type... and then specify the user-defined data type using the Fluent API.

```SQL
CREATE TYPE [dbo].[Name] FROM [varchar](max) NOT NULL
```

**Comment by lajones** [comment]
@rowanmiller @natemcmaster  - re aliased data types - if they are well-known and only ever mean the same thing on different instances of SQL Server (e.g. `Name` always means `varchar(max)`) then it would be easy to hard-code them into the type mapper. But if we need to run a query to look up the underlying data types for aliased data-types on that particular instance then I would need to look into how that metadata works.

Re the decimal value - that's a bug - that looks like a perfectly well-defined decimal default value to me. I should investigate why the code is not picking it up.

**Comment by jonnybee** [comment]
These types are typically defined in a database / domain  specific manner as User Defined Data Types, 

Example from AdventureWorks: 

- AccountNumber 	: NVARCHAR(15)
- Flag			: BIT, NOT NULL
- Name			: NVARCHAR(50)
- OrderNumber	: NVARCHAR(25)
- Phone			: NVRACHAR(25) 

In my opinion EF should be able to map these directly to the actual type - not as an alias in the type mapping.

**Comment by jonnybee** [comment]
@lajones 
The issue with default value is locale/globalization.

This fails: 

    Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("nb-NO");
    Convert.ChangeType("0.00", typeof(Decimal));

You must use the overload that specifies an IFormatProvider to make sure that the proper format is used. 

In many cultures the decimal separator is "," and not "."

**Comment by lajones** [comment]
@jonnybee Cool. Thanks for debugging.
@rowanmiller Do we support UDTs at runtime?

**Comment by rowanmiller** [comment]
@lajones - Need to distinguish between "User-Defined Types" and "User-Defined Data Types". The former we do not support, but the latter should just work since they are only aliases for built-in types that we already support. I think we just need to pull back some extra metadata to find out what they underlying type is.

**Comment by lajones** [comment]
@rowanmiller Yep - that was what I thought - but my reading of "should be able to map these directly to the actual type" from @jonnybee above is that he wants User-Defined Types - so sorry Johnny I don't think we'll be generating properties with e.g. fluent API saying `entity.Property(e => e.SomeColumn).HasColumnType("user_defined_type")` any time soon. However User-Defined Data Types producing e.g. `entity.Property(e => e.SomeColumn).HasColumnType("underlying_system_type")` might work. I'll look into what would be necessary. Have assigned it to me.

**Comment by jonnybee** [comment]
No. I do not expect to have mapping to the custom type but rather the actual underlying system type.

**Comment by lajones** [comment]
OK. Then just User-Defined Data Types. Will look into it.

**Comment by rowanmiller** [comment]
@lajones @jonnybee it actually does work already. Obviously there is no way to specify the user-defined data types in the model and have EF create them for you. You can however specify them if you are mapping to an existing database... or it actually even works if EF is creating the schema for you and you already have the type defined in your database (or you modify your migration to create it for you using the `Sql` method).

I.e. this works

```c#
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Infrastructure;
using Microsoft.Data.Entity.Storage;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                db.Database.EnsureDeleted();
                var creator = db.GetService<IRelationalDatabaseCreator>();
                creator.Create();
                db.Database.ExecuteSqlCommand("CREATE TYPE [dbo].[Name] FROM [nvarchar](max) NOT NULL");
                creator.CreateTables();

                db.People.Add(new Person { Name = "Bob" });
                db.SaveChanges();
            }
        }
    }

    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Person> People { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=People;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>().Property(p => p.Name).HasColumnType("Name");
        }
    }
}
```

**Comment by rowanmiller** [comment]
BTW from the code listing above, here is the SQL issued from `CreateTables()`

```SQL
CREATE TABLE [Person] (
    [Id] int NOT NULL IDENTITY,
    [Name] Name,
    CONSTRAINT [PK_Person] PRIMARY KEY ([Id])
);
```

**Comment by rowanmiller** [comment]
Since there are really two distinct issues being discussed here, I'm making this one about the datatypes and opened https://github.com/aspnet/EntityFramework/issues/3941 to deal with the default value issue

**Comment by lajones** [comment]
@rowanmiller Interesting. So if the above code `...HasColumnType("Name")` works, would you like Scaffolding to generate such code, or to generate as if the data type were the underlying system type?

**Comment by jonnybee** [comment]
@rowanmiller And how should scaffolding handle other constraints such as nullable/not nullable, length and precision on a UDDT?

**Comment by rowanmiller** [comment]
length/precision/etc. are all implied by the data type. Given the scaffolded code would explicitly map to the user-defined data type I don't think there is any need to specify those as well (since they are just hints that are used to help the database pick a type and are ignored when you specify an explicit data type).

At least in SQL Server, it looks like nullability is handled the same as any other column and is separate from the data type you select - so that would be the same as all other columns.

**Comment by rowanmiller** [comment]
@lajones we should generate the code that maps to the user-defined data type.

**Comment by lajones** [comment]
Checked in with commit 701f32e.

**Comment by josetonyin** [comment]
One more comment -  If you Try to map  Property to  boolean  and  database  column has  Custom BITTYPE(int) type.  The read  part is giving exception -  Invalid cast.
CREATE TYPE [dbo].[Name] FROM [nvarchar](max) NOT NULL
CREATE TYPE [dbo].[BITTYPE] FROM int NOT NULL

CREATE TABLE [dbo].[Person](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [dbo].[Name] NULL,
	[IsValid] [dbo].[BITTYPE] NULL,
 CONSTRAINT [PK_Person1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

**Comment by lajones** [comment]
@josetonyin That seems like a different issue to me - so please raise another one. Please include the full definition of the TABLE including the columns, the model you are mapping to that, the query you are performing and the stack trace you see as a result. Thanks.
