### ISSUE TITLE
"ArgumentNullException: Value cannot be null. Parameter name: provider" error occurs when accessing certain navigation properties after Skip()

### ISSUE THREAD

**Issue by cda-1** [aspnet/EntityFramework#3844]
### Minimal repro steps
Create these two entities.

    public class Property
    {
        public int Id { get; set; }

        [Required]
        public int EmployeeId { get; set; }
        public Employee Employee { get; set; }
    }
    public class Employee
    {
        public int Id { get; set; }

        [StringLength(256)]
        public string FirstName { get; set; }
    }

This will work:

    var testNav = await AppContext.Properties
        .Select(p => p.Employee.FirstName)
        .ToListAsync();

But this will not work (see exception below):

    var testNav = await AppContext.Properties
        .Skip(20)
        .Select(p => p.Employee.FirstName)
        .ToListAsync();

You can select the p.Employee.Id after the skip, but not p.Employee.FirstName. Both work without the skip.

### Expected result
You should be able to use .Select() after .Skip() and access navigation properties. It works fine in EF6 (although EF6 requires an OrderBy before the Skip). Using OrderBy before skip does not fix the issue in EF7.

### Actual result
    System.ArgumentNullException: Value cannot be null.
    Parameter name: provider
        at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
        at Microsoft.Data.Entity.Query.Internal.EntityQueryable`1..ctor(IAsyncQueryProvider provider)
        at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor._CreateEntityQueryable[TResult](IAsyncQueryProvider entityQueryProvider)

**Comment by mikary** [comment]
Same issue as #3962
Addressed in #4128
