### ISSUE TITLE
EF tests timeout

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#3857]
Creating this issue to track ongoing work to track slow DB creation/deletion for SQL Server tests which causes CI tests to fail.

Might be fixed with https://github.com/aspnet/EntityFramework/pull/3852

**Comment by natemcmaster** [comment]
ade3ca17a216dbd02b5455e4fd60c55c0d85e96e fixed the problem for EF tests on CI. 

:watch: will close if universe tests pass.

**Comment by AndriySvyryd** [comment]
Looks like some Identity tests still timeout

**Comment by natemcmaster** [comment]
Last 4 runs of testing on CI have passed. We can re-open this if the issue re-surfaces.
