### ISSUE TITLE
Can we avoid some of the overhead from OUTPUT INTO changes

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#3893]
There is a significant perf impact for no batching case

**Comment by rowanmiller** [comment]
Yeah I think we need to make it opt-in... here is the impact from on adding and saving a single row (from our benchmarks).

![results](https://cloud.githubusercontent.com/assets/4741851/11488374/e1e7fc54-977a-11e5-9447-888b36ab7410.png)

**Comment by AndriySvyryd** [comment]
We can also make it faster.

**Comment by rowanmiller** [comment]
Yep, that looks good :smile: 

![results](https://cloud.githubusercontent.com/assets/4741851/11547438/a9c6a4b2-9908-11e5-9436-af3af4f8f1ff.png)
