### ISSUE TITLE
Removing derived type does not update list of directly derived type in the base type

### ISSUE THREAD

**Issue by ESPNSTI** [aspnet/EntityFramework#3894]
See https://github.com/aspnet/EntityFramework/issues/3555

I don't have a code sample yet, but I have some more information.
I reproduced this using EF7 RC1 final, .Net Framework 4.6 in VS2015.

The null reference happens in this section of Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder.Remove:

```csharp
            foreach (var directlyDerivedType in entityType.GetDirectlyDerivedTypes().ToList())
            {
                var removed = Entity(directlyDerivedType.Name, ConfigurationSource.Convention)
                    .HasBaseType(entityType.BaseType, configurationSource);
                Debug.Assert(removed != null);
            }
```
"Entity(directlyDerivedType.Name, ConfigurationSource.Convention)" ends up returning null because "IsIgnored(name, configurationSource)" in the "Entity" method is true.

In the case that I encountered, these are the variable values in this section:

entityType - System.Xml.Linq.XNode
directlyDerivedType.Name - System.Xml.Linq.XDocument
entityType.BaseType - null
configurationSource - DataAnnotation

---

It appears that while the code has changed, the problem still exists in the Dev branch (as of commit 26276266), in this case, "directlyDerivedType.Builder" returns null.
```csharp
            foreach (var directlyDerivedType in entityType.GetDirectlyDerivedTypes().ToList())
            {
                var derivedEntityTypeBuilder = directlyDerivedType.Builder
                    .HasBaseType(entityType.BaseType, configurationSource);
                Debug.Assert(derivedEntityTypeBuilder != null);
            }
```

---

For a workaround, I ended up adding the following to my code.
I did not need this in Beta8.

```csharp
            modelBuilder.Ignore<Version>();
            modelBuilder.Ignore<XAttribute>();
            modelBuilder.Ignore<XElement>();
            modelBuilder.Ignore<XName>();
            modelBuilder.Ignore<XNamespace>();
            modelBuilder.Ignore<XNode>();
            modelBuilder.Ignore<XDocument>();
```
It appears that the types listed above come from entity properties in my model that are ignored using this method:
```csharp
            modelBuilder.Entity<T>(
                c =>
                {
                    c.Ignore( x => x.Prop);
                } );
```

**Comment by AndriySvyryd** [comment]
@ESPNSTI could you provide a complete repro? A NRE in that piece of code indicates that there's a bug in a different place, but it would be hard to find without a repro.

**Comment by ESPNSTI** [comment]
Sure, here is a test project that will reproduce it:
https://onedrive.live.com/redir?resid=5E5FB20A43816C86!138&authkey=!AMK11ZHwTeqqpGI&ithint=file%2czip

**Comment by smitpatel** [comment]
Issue here is - while removing entity type, we do not remove it from the `BaseType._directlyDerivedTypes`. Therefore if the derived type is removed before, then removing base type throws NRE since `Builder` for derived type is set to null while removing it.

**Comment by smitpatel** [comment]
This also throws exception while removing derived type since when foreign keys are removed, relationship discovery convention will run and add new foreign key which disallows removing entity type.

**Comment by AndriySvyryd** [comment]
The entity type should be ignored before it is removed, so the convention shouldn't discover any relationship involving it. Perhaps there's an `IsIgnored` call missing somewhere.

**Comment by smitpatel** [comment]
There are `IsIgnored` calls about the target type and navigation but we do not check if the entity type which is running the convention is ignored or not. Should I put check for that? Or after `Ignore` is called we remove the entity type from _directlyderivedtypes?

**Comment by AndriySvyryd** [comment]
Yes, if the current type is ignored no conventions should run on it. We should also call HasBaseType(null) which will remove the type from _directlyderivedtypes before removing anything else.
