### ISSUE TITLE
Add DbSet<T>.Local (or similar)

### ISSUE THREAD

**Issue by joshmouch** [aspnet/EntityFramework#3915]
You used to be able to do the following to a DbSet<T>:

````
context.EntityDbSet.Local.FirstOrDefault(searchLocalQuery)
````

But it doesn't look like you can anymore (unless I'm missing an extension assembly).

Short of this, a backup is to do the following:

````
context.ChangeTracker.Entries<YourEntity>().Any(e => e.Entity.Id == id)
````

However, that only works if you have the context.  Is there a way to get the context if you just have a DbSet<T>?

**Comment by rowanmiller** [comment]
We thought we already had a backlog item to support .Local... but it doesn't look like we do, so turning this into an enhancement to track it.

In the meantime, you can write something like this. It gives you most of what local did, the main difference is that it won't refresh the list if you query for more data. It will sync changes to the list back into the change tracker though.

```c#
public static class Extensions
{
    public static ObservableCollection<TEntity> GetLocal<TEntity>(this DbSet<TEntity> set)
        where TEntity : class
    {
        var context = set.GetService<DbContext>();
        var data = context.ChangeTracker.Entries<TEntity>().Select(e => e.Entity);
        var collection = new ObservableCollection<TEntity>(data);

        collection.CollectionChanged += (s, e) =>
        {
            if (e.NewItems != null)
            {
                context.AddRange(e.NewItems.Cast<TEntity>());
            }

            if (e.OldItems != null)
            {
                context.RemoveRange(e.OldItems.Cast<TEntity>());
            }
        };

        return collection;
    }
}
```
