### ISSUE TITLE
Reverse Engineer: Always use DefaultValueSql for default values

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#3958]
Discussing https://github.com/aspnet/EntityFramework/issues/3941 it becomes clear that there is no fool-proof way to detect whether a default expression in SQL is a constant or an expression. Given that there is no real advantage to using the constant in the model, we should just always treat it as an expression.

**Comment by lajones** [comment]
Checked in with commit 8079adf.
