### ISSUE TITLE
Self Referencing Entity

### ISSUE THREAD

**Issue by stevejgordon** [aspnet/EntityFramework#3978]
I'm not sure if this is a bug or just me doing something wrong but if I create a simple entity that can optionally have children of the same type, or a parent of the same type I'm unable to setup the model to produce the correct database.

I have a set of terms which can have child terms under them to build a taxonomy. When I create the migration it produces and additional column for what should be the FK to the parent term. I originally tried with annotations and later with fluent with the same issue.

This is the Term entity
```
    public class Term
    {
        public int Id { get; set; }
        public int CategoryId{ get; set; }
        public string Name { get; set; }
        public int? ParentId { get; set; }
        public Term Parent { get; set; }
        public ICollection<Term> Children { get; set; }
    }
```

Fluent model builder

```
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<Term>()
                .HasKey(t => new { t.Id, t.CategoryId });

            builder.Entity<Term>()
                .HasOne(x => x.Parent)
                .WithMany(x => x.Children)
                .HasForeignKey(x => x.ParentId)
                .IsRequired(false);
        }
```

This is what a snippet of the migration looks like but the issue for me is the non nullable ParentId1
```
columns: table => new
                {
                    Id = table.Column<int>(nullable: false),
                    CategoryId = table.Column<int>(nullable: false),
                    Name = table.Column<string>(nullable: true),
                    ParentId = table.Column<int>(nullable: true),
                    ParentId1 = table.Column<int>(nullable: false)
                },
```

I've added a repo with the code to reproduce this to https://github.com/stevejgordon/EF7SelfRefTest

**Comment by smitpatel** [comment]
The entity `Term` has a composite primary key defined explicitly. When you explicitly configure relationship to use `ParentId` as foreign key property, the number of foreign key properties is not equal to number of primary key property of referenced entity (`Term`), therefore EF will create a shadow property `ParentId1` which will be referenced by this foreign key. Hence migration will have extra column `ParentId1` and alternate key defined on it.

If you do not want to have shadow property then you need to specify which property to be used as principal key property for the relationship. You need to write something similar to following code:
````C#
builder.Entity<Term>()
    .HasOne(x => x.Parent)
    .WithMany(x => x.Children)
    .HasForeignKey(x => x.ParentId)
    .HasPrincipalKey(x => x.Id)      // or whichever property you want to use as principal key property
    .IsRequired(false);
````

**Comment by stevejgordon** [comment]
Many thanks @smitpatel. Can't believe I didn't catch onto that. Have tested it out and it works perfectly. I appreciate the assistance.

**Comment by rowanmiller** [comment]
@smitpatel this should throw in validation rather than proceeding with a shadow FK
