### ISSUE TITLE
Identifier generation strategy in reverse engineering

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#3987]
I can see logic in CSharpUtilities that's responsible for generating a C# identifier out of a database column. In PostgreSQL it seems that the standard case is "snake case" (employee_name). It seems right for the reverse engineering process to convert this to camel case (EmployeeName).

So I was wondering if this is something that Npgsql should do in its own version of CSharpUtilities, or whether the universal CSharpUtilities should detect snake case and perform this task (I'm guessing there are instances where SqlServer or other databases contain snake case).

**Comment by natemcmaster** [comment]
This is a good question. The identifier generation needs to be revisited. 

**Currently** [`RelationalScaffoldingModelFactory.GetEntityName`](https://github.com/aspnet/EntityFramework/blob/083fc56455bfd7fb919f30c284cab272b1272c2e/src/EntityFramework.Relational.Design/RelationalScaffoldingModelFactory.cs#L83) handles generating the names. This can be overridden. This does 2 things: (1) ensures unique names for each entity type and (2) ensures these identifiers are CSharp-safe.

**Future** we will move the csharpification of identifiers into the code-gen step (i.e. RelationalScaffoldingModelFactory will no longer need to return CSharp-safe identifiers.) We haven't designed code-gen API yet.

**Comment by rowanmiller** [comment]
**Triage:** We should just handle snake case in our CSharpUtilities. @roji do you want to send a PR for this?

**Comment by roji** [comment]
@rowanmiller sure I'll submit a PR soon.

**Comment by roji** [comment]
Note this probably means that single uncapitalized words are uppercased. If so there's no more need to detect C# reserved words and prefix them with underscore, since `volatile` becomes Volatile anyway

**Comment by natemcmaster** [comment]
Yup, this was one of the intentions of [my comments above](https://github.com/aspnet/EntityFramework/issues/3987#issuecomment-162962760). `IScaffoldingModelFactory.Create` shouldn't be concerned with the targeted code-gen language.

**Comment by rowanmiller** [comment]
@lajones regardless of extension points, we should update EF to handle snake case

**Comment by lajones** [comment]
Fix checked in with a065b93.

**Comment by lajones** [comment]
See comments in #5360. Need to add <space> as a word separator.

**Comment by lajones** [comment]
Blocked pending discussion between @divega, @rowanmiller and me to decide final design.

**Comment by lajones** [comment]
Had discussion on 5/24/16 with @rowanmiller, @divega, @ajcvickers and @bricelam. Approach will be:

1. Split DB identifier into words. Word separation happens a) if there is any non-letter & non-digit character, or b) if there is a change of case from lower to upper (where intervening digit characters don't change the change of case i.e. Blog123ID results in 2 words: "Blog123" and "ID")
2. If the first letter of the word is a letter then upper-case it. Lower-case all other letters in the word.
3. Put the words back together to form the candidate identifier.

The candidate identifier will then be used to produce the final identifier by a) making sure it's a valid identifier for the output language (currently C#) and b) making sure it doesn't clash with existing identifiers as per normal.

**Comment by lajones** [comment]
Fix (as designed above) checked in with f2f90ca.
