### ISSUE TITLE
DbContext.X.Where().Include(x => x.Y) may load Y as added entity

### ISSUE THREAD

**Issue by LonDat** [aspnet/EntityFramework#4020]
Hi,
I have 2 classes (X and Y) with **INotifyPropertyChanged**
Somethink like:
```C#
public class X : INotifyPropertyChanged
{
    public Y YRef { 
            get { return ...; } 
            set { ... = value; NotifyPropertyChange(...); } // NotifyPropertyChange is important!
    }
    // some PK + properties

}
public class Y : INotifyPropertyChanged
{
    // some PK + properties
}
```
When I execute:
```C#
dbContext.Xs.Where<X>(x => x.ID == 1).Include(x => x.YRef).ToArray();
```
everything is OK...I have 2 entries in unmodified state...BUT:
```C#
dbContext.Xs.Single<X>(x => x.ID == 1); // it's cache instance in entry
dbContext.Xs.Where<X>(x => x.ID == 1).Include(x => x.YRef).ToArray();
```
Instance (type Y) in YRef property has Added state.

I mean, that YRef call PropertyChanged and StateManager start tracking entity...and because entry is Detached...state is set to Added.

Is it understandable? Thx.
PS: sry...my English is not perfect :)

**Comment by divega** [comment]
@ajcvickers did you see this? Seems interesting.

**Comment by LonDat** [comment]
Any news/progress? :)
