### ISSUE TITLE
Reveng: entity class properties in the same order of table fields

### ISSUE THREAD

**Issue by alfberga** [aspnet/EntityFramework#4062]
In reverse engineer please consider  to generate (eventually optional) the entity class with (field) properties listed not in alphabetic order but  in the same order of the fields in related table.

**Comment by rowanmiller** [comment]
Triage: We should just do this, it doesn't need to be optional though.

**Comment by ahmad-moussawi** [comment]
The same for code first approach would be nice, so the columns in the database should be in the same order as the model classes

**Comment by rowanmiller** [comment]
@ahmad-moussawi there has been a lot of discussion around that (and it's what we tried to do in EF6) but it causes a bunch of issues because reflection can give the properties in a different order on different architectures. While theoretically this doesn't really change the model... it can have subtle impacts on conventions etc. which ends up with different models on different architectures and it is super hard to debug why the differences occur.

**Comment by ahmad-moussawi** [comment]
@rowanmiller thanks for the clarification, so it would be useful if we can set it by annotation attributes (I don't know if this was already implemented but at least I didn't find it in the docs) especially for the `Id` column, where am expecting to be always the first column.

Maybe  `[Order("First")]` or `[Order("Last")]` or maybe also something like `[Order(0)]` for the 1st one, `[Order("n-1")]` for the 2nd from the end

**Comment by rowanmiller** [comment]
@ahmad-moussawi see https://github.com/aspnet/EntityFramework/issues/2272 for some ideas we have on providing a hint to migrations to the order columns would be in - which would often give you the order you defined things in the class (or at least close to it).

**Comment by lajones** [comment]
Note to providers: this is now implemented. And you probably won't need to do anything. But if you override `RelationalScaffoldingModelFactory.VisitColumn()` and you don't call `base.VisitColumn()` then you will need to make sure the same `ColumnOrdinal` annotation is added yourself.

**Comment by ktrkumarbablu** [comment]
Can anyone has resolve this issue.I tried find the solution but completely unsuccessful...
Please look this issue..

**Comment by icecream520** [comment]
also has problem

**Comment by bricelam** [comment]
@icecream520 Can you submit a new issue with additional details about what you're seeing?
