### ISSUE TITLE
Reverse Engineer from database doesn't handle Tablename == enclosed Fieldname

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/EntityFramework#4063]
Given (the poorly designed but stuck with it) table design

CREATE TABLE InvoiceType
(
id int,
InvoiceType char(1),
);

EF 6 tooling would call the Field "InvoiceType1" and set [ColumnName("InvoiceType")] when reverse engineering.

Given this design pattern is in quite a few tables in my database I am stuck with altering the code gen manually which is very painful and also adding column mapping attributes.

Since the mapping code is not runtime code I see no major drawbacks to adding back this functionality.

**Comment by ErikEJ** [comment]
Looks like this was already fixed post RC1: https://github.com/aspnet/EntityFramework/commit/90e5555fb17505b9872ac2d1f3fe7c1a45e86fa1

**Comment by mikes-gh** [comment]
Ah great I am running rc1 so that explains it.  Please close.

**Comment by lajones** [comment]
@miles-gh Yep, this was working back in one of the beta's. Then the bug got re-introduced when we redesigned the part of the reverse-engineer code that reads the DB metadata. But as ErikEJ mentioned above we've already fixed it for RC2. So closing.
