### ISSUE TITLE
TPH: Validate shared columns and constraints

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#4074]
It is possible to share columns, foreign keys, and indexes across a hierarchy. For example:
```C#
class Animal {
    public int Id { get; set; }
}

class Cat : Animal {
    public string Breed { get; set; }
}

class Dog: Animal {
    public string Breed { get; set; }
}
```
We should validate (or combine) the configuration on each of the properties. Because conflicts:
```C#
modelBuilder.Entity<Cat>().Property(c => c.Breed).HasMaxLength(30);
modelBuilder.Entity<Dog>().Property(d => d.Breed).HasMaxLength(15);
```

**Comment by divega** [comment]
It the current behavior last one wins?

**Comment by bricelam** [comment]
The only place it currently matters is Migrations. I just did `Distinct((x, y) => x.Name == y.Name)`, so one (undefined) of them will win.

**Comment by bricelam** [comment]
:trollface: It's almost like we should maintain a separate model for SSpace with some sort of mapping between the two...

**Comment by divega** [comment]
:see_no_evil:

**Comment by rowanmiller** [comment]
Triage: For the moment we will throw if the two columns are not configured in the same way. We can relax this in the future.
