### ISSUE TITLE
InvalidCastException when filtering a projected list

### ISSUE THREAD

**Issue by alaatm** [aspnet/EntityFramework#4094]
Using version **7.0.0-rc2-16556** which is the latest on myget as of this writing.

Consider the below 2 entities:

    public class Expense
    {
        public Guid Id { get; set; }
        public Guid CategoryId { get; set; }
        public Category Category { get; set; }
        public decimal Amount { get; set; }
    }

    public class Category
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Expense> ExpenseList { get; set; }
    }

When entities have a PK field of type `Guid` such as above, the below code throws `InvalidCastException` when `ToList()` runs. The same code executes without any exceptions when the PK field is of type `int` although the executed result is wrong as it returns empty list where it should return a list with 1 item in it *(See linked repro)*.

    var q = from c in db.Categories
            select new
            {
                Id = c.Id,
                Name = c.Name,
                TotalTransactions = c.ExpenseList.Count(),
                TotalAmount = c.ExpenseList.Sum(e => e.Amount)
            };

    var filter = q.Where(p => p.TotalTransactions > 2);
    var result = filter.ToList(); // Throws InvalidCastException when Id is Guid but no exceptions are thrown when Id is int.

I have included a repro here: http://1drv.ms/1P5iSGA - *Filename: EF7Issues.rar*
This tests both cases where PK field is `int` in repro1.cs and when PK field is `Guid` in repro2.cs.

*Note*: Both cases throw `InvalidCastException` in **7.0.0-rc1-final**.

**Comment by smitpatel** [comment]
related to #4908 
The incorrect ordering of columns and materializer makes the comparison on fk property during client eval to use the count value instead of actual Id. Therefore for int PK its incorrect result and for Guid its cast exception.
