### ISSUE TITLE
Unable to add EntityFramework.Relational NuGet package to PCL

### ISSUE THREAD

**Issue by hameedfs** [aspnet/EntityFramework#4102]
I am unable to add EntityFramework.Relational NuGet package to a PCL project targeting .Net 4.6 & UWP. I get an error message that says the package is not compatible with ".NETPlatform,Version=v5.0". My requirement is to create a DbContext class that can be used in Windows 10 app (to access SQLite) as well as in the server side (to access SQL Server).

**Comment by hameedfs** [comment]
Until the fix is available, is there a temporary workaround for adding EF7 to PCL?

**Comment by rowanmiller** [comment]
Clearing for re-triage... not sure why we assigned this one to me :smile:

**Comment by bricelam** [comment]
I think we're waiting on updated Win10 Tools that can understand the [.NET Platform Standard](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md)...

**Comment by bricelam** [comment]
I've verified that this now works using an internal build of Visual Studio 2015 Update 2 RC.
