### ISSUE TITLE
EntityFramework.Commands don't support dotnet5.4 framework

### ISSUE THREAD

**Issue by OlegKi** [aspnet/EntityFramework#4143]
The `project.json` of `EntityFramework.Commands` contains `"netcore50"` framework (see [the lines](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/project.json#L61-L65)), but no `"dotnet5.4"`, which should exist now (see [the announcement](https://github.com/aspnet/Announcements/issues/98)).

It seems to me that **one have to copy the dependencies from existing `"dnxcore50"` property to  `"dotnet5.4"` and probably to fix some version numbers**.

Additionally one should consider to include `"dnx451"` in all `project.json` files of `EntityFramework` as the copy of `"net451"` for better compatibility. Alternatively one should delete `"dnx451"` from the `project.json` of `EntityFramework.Commands` and probably other `project.json` files of `EntityFramework`

**Comment by NickolasAcosta** [comment]
+1

**Comment by LostBalloon1** [comment]
+1
No updates regarding this?

**Comment by rowanmiller** [comment]
We're catching up on the backlog of new issues after the majority of folks have been out for holidays... we should get to everything (including this one) this week.

**Comment by bricelam** [comment]
Resolved by #4283
