### ISSUE TITLE
Query: Translate bitwise operations

### ISSUE THREAD

**Issue by leroyd** [aspnet/EntityFramework#4255]
When I use flags into a model, bitwise operators could not be translate to sql with following code :
```
    public class MyModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Week Days { get; set; }
    }

    [Flags]
    public enum Week
    {
        Monday = 1,
        Tuesday = 2,
        Wednesday = 4,
        Thursday = 8,
        Friday = 16,
        Saturday = 32,
        Sunday = 64
    }
```
Where clause exemple :
```
MyModels.Where(m => (m.Days & Week.Wednesday) > 0)
```
Debug message show :
```
Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression '((Convert([m.Days) & 4) > 0)' could not be translated and will be evaluated locally.
```
The issue cause bad performance because the request return all lines of the table before filtering.

For EF 6, same code works and the code has been translate to SQL.
```
SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Days] AS [Days]
    FROM [dbo].[MyModels] AS [Extent1]
    WHERE  CAST( ( CAST( [Extent1].[Days] AS int)) & (4) AS int) > 0
```

**Comment by RejectKid** [comment]
is there someone I could talk with about this?  I pulled the project and at first DNXCore wasn't DLing correctly as it needs.  So I tried to DL it through many other means like the DNVM, though I'm still getting 21k build errors still.  I'm guessing relating to the DNXCore version.   is there a guide on how to get the proj set up anywhere? or if someone could help me out a bit.  sorry for being a scrub
