### ISSUE TITLE
SQL2008 query bug with Include and skip

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#4260]
Changes made in 804458aa576723d8732f65605effde5b7fb7145a cause IncludeSqlServerTest.Include_with_skip to start to fail on SQL Server 2008:

```
System.InvalidOperationException : Sequence contains no matching element
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.
```

Full stack trace on our CI server

cc @anpete

**Comment by anpete** [comment]
This doesn't look like a regression. The new test exposes an existing bug in the interaction between Include and RowNumberPaging.
