### ISSUE TITLE
Only discover properties with public getter and public/private/etc. setter

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#4314]

**Comment by rowanmiller** [comment]
My understanding from our discussion was that we would go back to the EF6 rules - i.e. only pull in properties with a getter and setter where at least one of them is public. The exception being collection navigations - where a setter is not required.

@divega @ajcvickers was that your understanding too?

**Comment by AndriySvyryd** [comment]
I thought we decided that we will keep discovering private properties.

**Comment by ajcvickers** [comment]
I also think we decided to keep discovering private properties, but I might be remembering wrong. We've had so many different discussions! Fundamentally, the biggest problem is mapping read-only properties, so we should stop doing that. Also, probably mapping private _navigation_ properties doesn't make much sense.

**Comment by rowanmiller** [comment]
Yeah I'm pretty sure we decided to "go back to the same rules we had in EF6". The reasons being that we know they worked well in most cases and we now have an easy way to bring private properties into the model (using the string overload of Property), which was hard in EF6.

**Comment by ajcvickers** [comment]
I can go with that. :-)

**Comment by ajcvickers** [comment]
So, EF6 rules, except that we never exclude a property because the type of the property "can't be mapped".

**Comment by rowanmiller** [comment]
**Triage:** Decision is that we map properties with a getter and a setter when the getter is public (the setter does not have to be public). The one exception is that collection navigation properties do not need to have a setter at all. This is slightly simplified from the EF6 rules. The one deviation from the EF6 rules is that we don't just silently ignore properties that we can't find a type mapping for - we continue to throw saying that the property can't be mapped.
