### ISSUE TITLE
OnModelCreating : ValueGenerated.OnAddOrUpdate results in ValueGeneratedOnAdd()

### ISSUE THREAD

**Issue by adrien-constant** [aspnet/EntityFramework#4328]
I am using EF version 7.0.0-rc2-16649 and dnx  1.0.0-rc2-16357

I use the following code in my context OnModelCreating() method, in order to automatically update the "DateMod" column on all entities which have the property :
```
foreach (var entityType in builder.Model.GetEntityTypes())
{
    var dateModProp = entityType.FindProperty("DateMod");
    if (dateModProp != null)
    {
        dateModProp.ValueGenerated = ValueGenerated.OnAddOrUpdate;
        builder.Entity(entityType.ClrType).Property(typeof(DateTime), "DateMod").HasDefaultValueSql("getutcdate()");
    }
}
```
I then updated an entity, and DateMod did not change.
After looking in the model snapshot generated code, I can see :
```
 b.Property<DateTime>("DateMod")
  .ValueGeneratedOnAdd()
  .HasAnnotation("Relational:GeneratedValueSql", "getutcdate()");
```
I think the method **ValueGeneratedOnAddOrUpdate()** should be called instead.

**Comment by ErikEJ** [comment]
Have you seen this? http://ef.readthedocs.org/en/latest/modeling/generated-properties.html#value-generated-on-add-or-update

**Comment by aconstant** [comment]
Yes, and I also do the same with a "DateCrea" (creation date) property, with ValueGeneated.OnAdd, and it works (SQL Server 2016 CTP 3).

I think it may be a bug, because the generated code in the snapshot class is ValueGeneratedOnAdd(), while it seems logic that it should be ValueGeneratedOnAddOrUpdate() in my case.

**Comment by rowanmiller** [comment]
@aconstant the most important piece of information from the link @ErikEJ provided is...

> How the value is generated for added and updated entities will depend on the database provider being used. Database providers may automatically setup value generation for some property types, while others will require you to manually setup how the value is generated.

> For example, when using SQL Server, byte[] properties that are set as generated on add or update and marked as concurrency tokens, will be setup with the rowversion data type - so that values will be generated in the database. However, if you specify that a DateTime property is generated on add or update, then you must setup a way for the values to be generated (such as a database trigger).

So you'll need to setup some way to have the values generated when the row is updated (In SQL Server DefaultValue only get used for INSERT statements)

**Comment by aconstant** [comment]
Thanks for the clarification. 

So, it means when ValueGeneratedOnAddOrUpdate is not supported with the specified database provider, the code generation tool fallbacks to ValueGeneratedOnAdd ?

**Comment by rowanmiller** [comment]
@aconstant the snapshot should contain the correct setting - so this is definitely a bug if we are writing the wrong thing. ValueGeneratedOnAddOrUpdate is supported by SQL Server - I was just pointing out that even when we fix this bug, you still need to let the database know how values are generated on Update.

**Comment by aconstant** [comment]
Ok, I though the bug was related. The model snapshot generated code bug occurred with this version :

    "EntityFramework.Commands": "7.0.0-rc2-16649",
    "EntityFramework.Core": "7.0.0-rc2-16649",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc2-16649",
    "EntityFramework.Relational": "7.0.0-rc2-16649",

Now I'm on nightly builds (16751), so I can't use migrations any more, I don't know if it was fixed.

**Comment by smitpatel** [comment]
As @rowanmiller  said
> In SQL Server DefaultValue only get used for INSERT statements

Therefore when `HasDefaultValueSql()` is called, EF sets the property to be `ValueGeneratedOnAdd` which will overwrite value generatation set before the `HasDefaultValueSql()` call. Easy work-around would be change the order in which they are called.
Simplified version of the loop would be:
````
foreach (var entityType in builder.Model.GetEntityTypes())
{
    var dateModProp = entityType.FindProperty("DateMod");
    if (dateModProp != null)
    {
        builder.Entity(entityType.ClrType).Property(typeof(DateTime), "DateMod")
            .HasDefaultValueSql("getutcdate()")
            .ValueGeneratedOnAddOrUpdate();
    }
}
````

**Comment by smitpatel** [comment]
@rowanmiller - Is there anything to be done in this?

**Comment by rowanmiller** [comment]
Clearing milestone for triage... I wonder if setting the default value should not override `ValueGeneratedOnAddOrUpdate` if it is set (i.e. only move to `ValueGeneratedOnAdd` if it is set to no value generation).

**Comment by rowanmiller** [comment]
@smitpatel this seems to be a bug in HasDefaultValue/Sql, it should only set value generated pattern if it hasn't already been explicitly set (talk to @ajcvickers as he wrote original code that did this)
