### ISSUE TITLE
IConcurrencyDetector should probably be moved to internal namespace

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#4365]
When we added the async guard for query execution in https://github.com/aspnet/EntityFramework/commit/eece19ded562ba8aa85f2173d3280a23fc4e3727 we introduced a public interface in our main namespace:

``` C#
namespace Microsoft.Data.Entity 
{ 
    public interface IConcurrencyDetector 
    { 
        void EnterCriticalSection(); 

        void ExitCriticalSection(); 
    } 
} 
```

Unless I am missing something this should probably go an internal namespace to avoid exposing the type to Intellisense for 99% of EF Core users.

cc @mikary

**Comment by mikary** [comment]
The `IConcurrencyDetector` is only not in an internal namespace because it's consumed by non-internal types in query (`QueryContext` and `RelationalQueryContext`). Should we also consider moving these into internal or is there an expectation for this to be a provider extensibility point? @anpete

**Comment by divega** [comment]
Then maybe it should be in `Infraestructure` or something similar (I think it is neither Query nor Update specific, correct?), just not in our main namespace.

**Comment by mikary** [comment]
Correct, `Infrastructure` seems reasonable since it's not specific to a feature area and not really useful to most EF users.

**Comment by rowanmiller** [comment]
Is the interface actually used by provider writers? If it's just a constructor parameter for a type that providers may inherit from then it's fine for it to be "internal"

**Comment by mikary** [comment]
This isn't an interface that a provider would need to use beyond the constructor parameter. Moving to internal sounds good to me.
