### ISSUE TITLE
Rebrand to EF Core v1

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#4376]
For more context on the rename, see http://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx.

There are several folks working on the various parts of this. This is just a high level item to track everything that needs to happen in the EF repos.

## Rename/reversion packages

Packages will move to v1.0.0, this (in addition to wanting a clear distinction between EF6.x and EF Core packages) means we will rename the packages too.

We are moving to a naming strategy that aligns with other packages from Microsoft (ASP.NET and .NET Framework). Our core package will be Microsoft.EntityFrameworkCore. Our providers will be Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.SQLite, and Microsoft.EntityFrameworkCore.InMemory.

**Suggested naming of third party providers**

Our initial suggestion to third party provider writer would be to use the following naming for packages - which is consistent with the names we are adopting. Totally open to feedback/discussion on this one though (cc @ErikEJ @roji).

```
<Optional project/company name>.EntityFrameworkCore.<Database engine name>
```

For example:
* `Npgsql.EntityFrameworkCore.PostgreSQL`
* `EntityFrameworkCore.SqlServerCompact40`

## Update namespaces

Our packages have been somewhat unique in that the namespace does not align with the package name. We will take this opportunity to change that - and adopt `Microsoft.EntityFrameworkCore` instead of `Microsoft.Data.Entity`.

## Update branding on [docs.efproject.net](http://docs.efproject.net)

**Comment by ErikEJ** [comment]
And update github Wiki pages, readme etc.

**Comment by davidroth** [comment]
@rowanmiller 

Since EF is a well known abbreviation, have you already though about using `EFCore` instead?

Ex:
`using Microsoft.EFCore.ChangeTracking;`
`using Microsoft.EFCore.ChangeTracking.Internal;`
`using Microsoft.EFCore.Extensions.Internal;`

is much shorter an clearer than:
`using Microsoft.EntityFrameworkCore.ChangeTracking;`
`using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;`
`using Microsoft.EntityFrameworkCore.Extensions.Internal;`

**Comment by YehudahA** [comment]
What will be the future?
EF will remain as a "CORE"? Why?

If in two years I will use EF with a WPF project, I will use EntityFrameworkCore 3.x ? Why?!

**Comment by rowanmiller** [comment]
@davidroth we did consider EFCore instead... whether it is cleaner or not is somewhat subjective and acronyms in namespaces are generally considered bad practice.

**Comment by rowanmiller** [comment]
@YehudahA 

> EF will remain as a "CORE"? Why?

Yes, there will be EF 6.x and EF Core x.x. Because they are two different technologies. They have a lot in common - hence the shared "Entity Framework" branding - but EF Core is not v7 of the original stack... it is something new.

For a more detailed explanation see the post announcing the changes - http://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx. You could also take a read of a blog post we published a little over a year ago that talks about the options we had, and why we originally chose EF7 - http://blogs.msdn.com/b/adonet/archive/2014/10/27/ef7-v1-or-v7.aspx. We have received a LOT of feedback that calling it v7 is confusing - hence the change to a new name.

**Comment by YehudahA** [comment]
What "CORE" mean in context of EF?

@davidroth, AspNet namespaces also change to AspNetCore? I'm not sure.

**Comment by rowanmiller** [comment]
@YehudahA it's a name being used to identify a set of technologies that follow the same set of "runs everywhere, lighter weight, modularized, etc." principles. It's not something that we chose on the EF team (though I like it).

**Comment by rowanmiller** [comment]
I've done an initial pass of the Wiki pages. Our Wiki needs a more involved cleanup though, as much content has been moved to our proper docs site.

**Comment by cincuranet** [comment]
> Npgsql.EntityFrameworkCore.PostgreSQL
EntityFrameworkCore.SqlServerCompact40

Is there some story for naming in case v2 changes the provider model? Doing `EntityFrameworkCore2.SqlServerCompact40` does not seem smart.

**Comment by rowanmiller** [comment]
@cincuranet for our provider packages we will use the same version as the core packages, so Microsoft.EntityFrameworkCore.SqlServer 2.0 will be compatible with Microsoft.EntityFrameworkCore 2.0 etc.

**Comment by roji** [comment]
@rowanmiller am back to life and will slowly start working on Npgsql/EF Core again.

To follow up on @cincuranet's question, do you guys have more specific guidelines as to how to manage provider versions vis-à-vis core versions? In other words, I understand that the SqlServer provider compatible with EF Core 2.0.0 should have 2 as its major version (this makes sense). How about the minor version (should there be Microsoft.EntityFrameworkCore.SqlServer 2.1.0 once Microsoft.EntityFrameworkCore 2.1.0 comes out)? Patch version?

**Comment by gdoron** [comment]
I agree with @davidroth that `EFCore` is neater than `EntityFrameworkCore` and everyone is using that acronym and it's well known for every EF(...) user what it's.
