### ISSUE TITLE
Fix non-Windows dotnet build

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#4402]
The transition to dotnet CLI broke our Linux and OSX build/test support. Use this issue to track overall progress on restoring non-Windows build/test

- [ ] Linux
- [ ] OSX

**Comment by ErikEJ** [comment]
And the AppVeyor build seems to be well broken also...

**Comment by natemcmaster** [comment]
Blocking issues:
https://github.com/NuGet/Home/issues/1959
https://bugzilla.xamarin.com/show_bug.cgi?id=35947

**Comment by victorhurdugaci** [comment]
Do you need mono 4.2? We usually use 4.0.5

**Comment by natemcmaster** [comment]
Short answer: yes and no.
Longer answer: our testing is currently configured to work on Mono 4.0.x, but it skips a huge number of tests that fail due to features that were not added until 4.2.x. So tests on 4.0.x should pass, but 4.2.x is preferred.
