### ISSUE TITLE
Additional FK and Inconsistent ReferentialAction

### ISSUE THREAD

**Issue by cp79shark** [aspnet/EntityFramework#4404]
It's late in Germany, so please be gentle. :) 

7.0.0-rc1-final  (I haven't had a chance to get any of the nightlies, trying to stay with what's published via official nuget/dnvm channels)
1.0.0-rc1-update1 clr     x86          win

Starting to investigate moving to EF7 from EF6, pretty complex graph and as it's in RC, noticing some weird issues. I'll post other issues separately. This one is pretty simple to show using a small model instead of my actual large model.

Given the following Context and Model

    public class TestContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlServer(@"server=devlan-sql;database=TestEF7;Trusted_Connection=Yes;");
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Container>(e =>
            {
                e.HasOne(p => p.ContentOne)
                    .WithOne(p => p.Container)
                    .HasForeignKey<Container>(p => p.ContentOneId)
                    .IsRequired();

                e.HasOne(p => p.ContentTwo)
                    .WithOne(p => p.Container)
                    .HasForeignKey<Container>(p => p.ContentTwoId)
                    .IsRequired();

                e.HasOne(p => p.ContentThree)
                    .WithOne(p => p.Container)
                    .HasForeignKey<Container>(p => p.ContentThreeId)
                    .IsRequired();
            });

            builder.Entity<Content>(e =>
            {
                e.Property(p => p.Data).IsRequired();

                e.HasOne(p => p.Container)
                    .WithOne()
                    .HasForeignKey<Content>(p => p.ContainerId)
                    .IsRequired();
            });
        }
    }

    public class Container
    {
        public int Id { get; set; }
        public int ContentOneId { get; set; }
        public Content ContentOne { get; set; }
        public int ContentTwoId { get; set; }
        public Content ContentTwo { get; set; }
        public int ContentThreeId { get; set; }
        public Content ContentThree { get; set; }
    }

    public class Content
    {
        public int Id { get; set; }
        public string Data { get; set; }

        public int ContainerId { get; set; }
        public Container Container { get; set; }
    }

The migration generator seems to get confused and I get columns jumbled and/or renamed. ContentThreeId1 was added and is nullable. It, of course, does not exist in the Container model.

Additionally, note that the LAST (in this case ContentThree) Navigation Property of this type has its RefentialAction set to Restrict instead of Cascade. If I remove ContentThree from the model, then ContentTwo is the property that gets an additional Column (ContentTwoId1) and its referential action is Restrict.

            migrationBuilder.CreateTable(
                name: "Container",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    ContentOneId = table.Column<int>(nullable: false),
                    ContentThreeId = table.Column<int>(nullable: false),
                    ContentThreeId1 = table.Column<int>(nullable: true),
                    ContentTwoId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Container", x => x.Id);
                });
            migrationBuilder.CreateTable(
                name: "Content",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    ContainerId = table.Column<int>(nullable: false),
                    Data = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Content", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Content_Container_ContainerId",
                        column: x => x.ContainerId,
                        principalTable: "Container",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });
            migrationBuilder.AddForeignKey(
                name: "FK_Container_Content_ContentOneId",
                table: "Container",
                column: "ContentOneId",
                principalTable: "Content",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
            migrationBuilder.AddForeignKey(
                name: "FK_Container_Content_ContentThreeId1",
                table: "Container",
                column: "ContentThreeId1",
                principalTable: "Content",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
            migrationBuilder.AddForeignKey(
                name: "FK_Container_Content_ContentTwoId",
                table: "Container",
                column: "ContentTwoId",
                principalTable: "Content",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

If I do not specify a property in the WithOne() call, then the migration is built correctly. I do that for now in my actual model builder, but am curious why it's confused for something, at least on its face since WithOne([null]) is supposed to indicate no nav property on the other end?? yet I have one, makes sense to be able to declare. Thanks!

**Comment by smitpatel** [comment]
You are using `Container` navigation property on `Content` class in all the relationships. One navigation can be part of only one relationship. Hence every time you configure a new relationship using the same navigation, it will remove that navigation from any other relationship using it.

**Comment by cp79shark** [comment]
Understood, but I am still a little confused on the output. Why does it feel it needs to add an additional Column to use as the FK (when it's explicitly defined) and alter the ``ReferentialAction`` to something not specified? If this is something that shouldn't be done, maybe an exception should be thrown? I guess when I get some time I can dig into the source, but there is quite a bit of it. :)

If this is a non-issue, then I'm okay with it being closed, but still curious about the behavior. Thanks.

**Comment by smitpatel** [comment]
Reason for extra column would be, at some stage EF is replacing the foreign key for `ContentThree` navigation. While replacing the FK it tries to find the matching property. By some reason it is not able to use `ContentThreeId` (may be being used by another FK already). Hence EF will create a shadow property in the model named `ContentThreeId1`. Since it is shadow property & relationship is being generated by conventions, there is no `IsRequired()` set. Therefore the shadow property becomes nullable type and ReferentialAction is set to Restrict.
It may not be supposed to behave that way. I will look into it later.

**Comment by smitpatel** [comment]
With recent improvements in relationship building, the final model generated out of above code will have following relationships
In `Container`
Navigation `ContentOne` with shadow fk `ContentOneId1`
Navigation `ContentTwo` with shadow fk `ContentTwoId1`
Navigation `ContentThree` with shadow fk `ContentThreeId1`
In `Content`
Navigation `Container` with fk `ContainerId`

This is the result of the way relationships are configured. There is nothing actionable here.
@rowanmiller
