### ISSUE TITLE
Cleanup TFMs

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#4413]
We have inserted some TFM hacks to get around the mismatch of DNX (VS) and dotnet (CLI). 

e.g. Relational.Design shouldn't need "netcore50". See https://github.com/aspnet/EntityFramework/commit/18a850127f2d2a3a850cffaed868d3dbf1d6a3b5#commitcomment-15711979

**Comment by natemcmaster** [comment]
cc @victorhurdugaci

**Comment by victorhurdugaci** [comment]
:+1:

**Comment by bricelam** [comment]
I think this is more-or-less done.
