### ISSUE TITLE
Make the 'foreign key column gets indexed' a IForeignKeyConvention

### ISSUE THREAD

**Issue by BradBarnich** [aspnet/EntityFramework#4416]
I am porting a large schema to EF7. We have tables where it would be impractical to have a reverse index for every foreign key property. We know this is not a best practice, but we also don't delete from the primary table.

Having as a convention, we could easily remove it from the ConventionSet during model creation. We are already doing this for the `CascadeDeleteConvention`.

Currently had to do this: https://github.com/BradBarnich/EntityFramework/commit/46ca0d3641c6c309013d8c8f92919fc0c1fc65ad

Is there another workaround?

**Comment by mejje** [comment]
My EF7 model haven't created any automatic FK indices, I actually thought it was a deprecated feature since I haven't disabled anything but cascade delete as well. I'll try to find out why that happens.

**Comment by rowanmiller** [comment]
@smitpatel @AndriySvyryd where in the stack do we currently introduce indexes on FKs?

**Comment by smitpatel** [comment]
Here
https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs#L1016

**Comment by AndriySvyryd** [comment]
It can be move to a convention fairly easily

**Comment by rowanmiller** [comment]
Decided that we should handle this as part of https://github.com/aspnet/EntityFramework/issues/214. There may be other things that should be moved to a convention, and we may want to combine and/or split existing conventions too.

**Comment by AndriySvyryd** [comment]
This was fixed in ab9e75fba7abb64d6aff19e9387365f24d0ba818
