### ISSUE TITLE
Redesign SqlServerTypeMapper to provide better round-trip mappings?

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework#4425]
See #4348. When trying to update scaffolding to make better use of the `SqlServerTypeMapper` code it was difficult to re-use because the mappings conflate the ideas of synonyms (which result in identical SQL Server data types in the database) with the idea of CLR-types which, by default, map to the same SQL Server data type e.g. see the mapping of `image` to `_varbinary`.

It also conflates in the idea of a max length qualification. And when it's available (see #3420) will also conflate in the idea of whether a column is a Unicode column as well. For scaffolding purposes (going from SQL Server metadata to generated code) it would be good for this code to provide an API which can be passed a set of attributes (say an unqualified SQL Server data type, e.g. "varchar", and the max length, e.g. 30) and return that the full column type is "varchar(30)" but that in order to implement that we need the fluent API `.HasMaxLength(30).IsUnicode(false)` i.e. we don't, and must not, specify `HasColumnType()`. Other data types would need different combinations of those APIs.

Migrations (going from code to generated SQL Server metadata) need to know e.g. that the default SQL Server data type for a string column is `nvarchar(max)`. But scaffolding needs to know that too in order that it _not_ to generate fluent API if that is what would be assumed by default anyway.

We aim for scaffolding to generate code from which migrations would generate the same SQL Server metadata i.e. to make it "round-trippable". `SQLServerTypeMapper` seems like a good place to centralize this but looks like it needs a redesign to make that work. We would also need to figure out how much code that is useful to scaffolding could also be used for more general purposes.

**Comment by divega** [comment]
@ajcvickers I had this assigned to me I believe with the purpose of giving it some thought. Re-reading it today I am not sure how much of it is still necessary. While I tend to agree that it could be worth to centralize the knowledge of how CLR types + facets map to database types for a specific database provider, I believe having logic that is runtime specific and design time specific in separate places is a reasonable compromise. 

Could you please take a look at this and provide your thoughts on whether we should have this in the backlog, do something about it before RTM or close it?

**Comment by divega** [comment]
> For scaffolding purposes (going from SQL Server metadata to generated code) it would be good for this code to provide an API which can be passed a set of attributes (say an unqualified SQL Server data type, e.g. "varchar", and the max length, e.g. 30) and return that the full column type is "varchar(30)" but that in order to implement that we need the fluent API  .HasMaxLength(30).IsUnicode(false)  i.e. we don't, and must not, specify  HasColumnType() . Other data types would need different combinations of those APIs.

@lajones I am not sure I completely understand this paragraph. In what format is the type information obtained currently for scaffolding?
