### ISSUE TITLE
Recent test change exposes SQL CE limitation

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#4455]
The changes to the test model in fix 
https://github.com/aspnet/EntityFramework/commit/788aee079f6aec2b077113f18cec82322da09336 has exposed an issue with the SQL Server Compact provider. 
The changes prevent any tests in InheritanceRelationshipsQuerySqlCeTest from passing 
see: https://github.com/ErikEJ/EntityFramework.SqlServerCompact/issues/299

I am posting the issue in this repo for advice.
The new seeding causes the following statement, which is not supported by SQL Server Compact to be generated:

    INSERT INTO [ReferencedEntity]\r\nDEFAULT VALUES;

I think it was also an issue before this fix, but just not covered by any of my tests. In fact I cannot really see usage of "DEFAULT VALUES" covered by any functional tests at all.

This is the definition of [ReferencedEntity]:

     -- Script Date: 02-02-2016 14:30  - ErikEJ.SqlCeScripting version 3.5.2.58
    CREATE TABLE [ReferencedEntity] (
      [Id] int IDENTITY (1,1) NOT NULL
    );
    GO
    ALTER TABLE [ReferencedEntity] ADD CONSTRAINT [PK_ReferencedEntity] PRIMARY KEY ([Id]);
    GO
 
The "real" issue here is that SQL Server Compact is not designed to work with a table with just a single IDENTITY column

**Comment by ErikEJ** [comment]
See this discussion for an example of the issue: http://stackoverflow.com/questions/2558646/how-to-insert-into-a-table-with-just-one-identity-column-sql-server-ce

Adding an additional property to the "ReferenceEntity" table would unblock the test run.

**Comment by divega** [comment]
Very interesting limitation... or maybe not so much :smile: At first glance I don't think we have a strong reason to have multiple tests that create tables with a single column that is identity. We could have only one of those. Looping in @smitpatel who made those changes.

**Comment by smitpatel** [comment]
The only reason there is only 1 property is another was not required so I did not add it. Should I add another property?

**Comment by ErikEJ** [comment]
@smitpatel Yes, that would be great!

**Comment by ajcvickers** [comment]
@smitpatel @divega Historically we have always just added another property to all classes because of this CE limitation.

**Comment by smitpatel** [comment]
@ErikEJ - Sorry for breaking you. I was not aware about Sql CE limitation. Checked in fix. :)

**Comment by ErikEJ** [comment]
@smitpatel No worries, and thanks for the quick fix. To be perfectly honest, I had also blissfully forgotten about this quirky SQL CE limitation, until I saw the table schema
