### ISSUE TITLE
Investigate failing ChangeTrackingInMemoryTests

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#4457]
Tests failing
`Entity_range_does_not_revert_when_attached_dbContext` & `Entity_range_does_not_revert_when_attached_dbSet`
Above tests fail for only for InMemory provider with dnx test runner on coreclr environment. For other providers or testing platforms it passes.
So far issue identified - something is wrong with the combination of `OrderBy(...).Take(2).Skip(1)` which gives 0 results while there should be 1.

**Comment by bricelam** [comment]
This wasn't fixed by moving off of DNX. We need to investigate further and possibly file a bug on [dotnet/corefx](https://github.com/dotnet/corefx).

**Comment by smitpatel** [comment]
filed dotnet/corefx#6819

**Comment by smitpatel** [comment]
Issue resolved in corefx. Just need to wait till it propagates and re-enable the tests.
