### ISSUE TITLE
Measure and improve state manager/fixup perf

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#446]
Currently fixup code (and other related state manager code) scans the entire model and the entire list of tracked entities multiple times when doing fixup. The perf implications of this need to be measured and then optimizations added. These optimizations will probably include additional indexes in the state manager and additional structure in the model. When adding such things memory use must be balanced against additional perf through indexes, etc.

**Comment by rowanmiller** [comment]
We now have tests that measure this. Opened https://github.com/aspnet/EntityFramework/issues/1334 to deal with the current bottleneck. May open more issues once this is resolved and new measurements are taken.
