### ISSUE TITLE
[Question/Issue] Adding entities with and without keys in the same context. The instance of entity type 'XXXX' cannot be tracked because another instance of this type with the same key is already being tracked.

### ISSUE THREAD

**Issue by danielcirket** [aspnet/EntityFramework#4488]
So, I have a DbSet<T> for which at runtime/startup I want to seed some initial/test data if it doesn't exist.

However i'm running into some issues when adding the first entry with a set key (will be a default value of -1), then trying to add the next item with no Id set to be generated, I get an exception thrown for the key already existing in the dbset.

For the entity type I'm using this as a base class:

```C#
public abstract class Entity
{
    public virtual int? Id { get; set; }
    public virtual DateTime CreatedDate { get; set; }
    public virtual int CreatedById { get; set; }
    public virtual DateTimeLastModifiedDate { get; set; }
    public virtual int LastModifiedById { get; set; }
    public virtual bool IsDeleted { get; set; }
}
```

With the entity as:

```C#
public class Country : Entity
{
   public string Name { get; set; }
}
```

(I have tried this with different combinations of the Id property having the UseSqlServerIdentityColumn() and ValueGeneratedOnAdd() and with both removed (Adding them seemed to make no difference, but wanted to try as many options as possible in case I was missing something).

```C#
public static void AddEntityDefaults<T>(this EntityTypeBuilder<T> source) where T : Entity    
{
    source.HasKey(x => x.Id);
    source.Property(x => x.Id).UseSqlServerIdentityColumn();
    source.Property(x => x.Id).ValueGeneratedOnAdd();
    source.Property(x => x.CreatedDate).HasDefaultValue(DateTime.Now).ValueGeneratedOnAdd();
    source.Property(x => x.LastModifiedDate).HasDefaultValue(DateTime.Now).ValueGeneratedOnAddOrUpdate();
    source.Property(x => x.IsDeleted)
        .HasDefaultValue(false)
        .IsRequired();
}
```

And for the 'seeding' I'm using this (Which works perfectly for a single entity OR a number of entities where the Id is null for all items). I have tried wrapping this in a transaction, and running an SQL command to enable then disable identity insert, saving the entity with the Id set before adding the additional items and simply adding them one at a time then saving.

This works for adding a single with the Id set to -1:

```C#
private static void InitialiseCountries(this DataContext source)
{
    if (source.Countries.Any())
        return;

    using (var transaction = source.Database.BeginTransaction())
    {
        source.Database.ExecuteSqlCommand("SET IDENTITY_INSERT Country ON");

        source.Countries.Add(new Country { Id = -1, Name = "Unknown", CreatedById = -1 });
        source.SaveChanges();

        source.Database.ExecuteSqlCommand("SET IDENTITY_INSERT Country OFF");
        transaction.CommitTransaction();
    }
}
```

This works for adding multiple items where the Id is still null (I could use add range for this, but changed it to below to make sure it wasn't me calling add multiple times that was causing the issue):

```C#
private static void InitialiseCountries(this DataContext source)
 {
     if (source.Countries.Any())
        return;

    source.Countries.Add(new Country { Name = "Unknown", CreatedById = -1 });
    source.Countries.Add(new Country { Name = "Test", CreatedById = -1 });
    source.Countries.Add(new Country { Name = "Test2", CreatedById = -1 });
    source.Countries.Add(new Country { Name = "Test3", CreatedById = -1 });
    source.SaveChanges();
}
```

But this gives me the exception (As mentioned above, tried SaveChanges() before and after the 2nd item is added, and before and after the 2nd ExecuteSqlCommand which makes no difference):

```C#
private static void InitialiseCountries(this DataContext source)
{
    if (source.Countries.Any())
        return;

    using (var transaction = source.Database.BeginTransaction())
    {
        source.Database.ExecuteSqlCommand("SET IDENTITY_INSERT Country ON");

        source.Counties.Add(new Country { Id = -1, Name = "Unknown", CreatedById = -1 });
        source.SaveChanges();

        source.Database.ExecuteSqlCommand("SET IDENTITY_INSERT Country OFF");
                
        source.Counties.Add(new Country { Name = "Test", CreatedById = -1 }); // <-- The exception happens here.
        source.SaveChanges();
        
        transaction.CommitTransaction();
    }
}
```

The exception:

```
An exception of type 'System.InvalidOperationException' occurred in EntityFramework.Core.dll but was not handled in user code

Additional information: The instance of entity type 'My.Namespace.Entities.Country ' cannot be tracked because another instance of this type with the same key is already being tracked. For new entities consider using an IIdentityGenerator to generate unique key values.
```

_I'm expecting that this may be something I'm doing incorrectly or should potentially use a different approach, however I've never used EF before this version, so have no prior experience to go on and my Google-foo has failed on this occasion._

**Comment by ajcvickers** [comment]
Note for triage: I think this is because if an explicit value of -1 is used for a primary key value, and then in the same context instance no key value is provided, then EF will generate a temporary value, but that value will also be -1, and hence there will be a collision.

**Comment by danielcirket** [comment]
Thank you for the quick reply Arthur, so based on that I've managed to get this working by changing the order of the adds.

So from this:

```C#
private static void InitialiseCountries(this DataContext source)
{
    if (source.Countries.Any())
        return;

    using (var transaction = source.Database.BeginTransaction())
    {
        source.Database.ExecuteSqlCommand("SET IDENTITY_INSERT Country ON");

        source.Counties.Add(new Country { Id = -1, Name = "Unknown", CreatedById = -1 });
        source.SaveChanges();

        source.Database.ExecuteSqlCommand("SET IDENTITY_INSERT Country OFF");

        source.Counties.Add(new Country { Name = "Test", CreatedById = -1 }); // <-- The exception happens here.
        source.SaveChanges();

        transaction.Commit();
    }
}
```

to this:

```C#
private static void InitialiseCountries(this DataContext source)
{
    if (source.Countries.Any())
        return;

    using (var transaction = source.Database.BeginTransaction())
    {
        source.Counties.Add(new Country { Name = "Test", CreatedById = -1 }); 
        source.SaveChanges();

        source.Database.ExecuteSqlCommand("SET IDENTITY_INSERT Country ON");
        source.Counties.Add(new Country { Id = -1, Name = "Unknown", CreatedById = -1 });
        source.SaveChanges();
        source.Database.ExecuteSqlCommand("SET IDENTITY_INSERT Country OFF");

        transaction.Commit();
    }
}
```

Which works fine given my use cases so far.

**Comment by danielcirket** [comment]
Just to note:

Core\ChangeTracking\ValueGenerationManager.cs seems to be where the temporary id value is generated and is simply decremented each time. (Line 25): 

```C#
public virtual void Generate(InternalEntityEntry entry)
```

would it be worth checking to see if the temp value is already used and re-decrement if required as in my case above, not sure if there would be any/how much negative impact on this, especially seeing that I have a work around above?

**Comment by rowanmiller** [comment]
We think moving to min int number will avoid almost every case where you would hit conflicts. Assigning to @ajcvickers to make this change.

**Comment by danielcirket** [comment]
Done a quick PR for this: PR #4503 if that helps.

**Comment by danielcirket** [comment]
PR #4504

**Comment by danielcirket** [comment]
I thought that, I had trouble even building the project, so wasn't expecting anything from it either.
