### ISSUE TITLE
Full .NET xunit is not running ConditionalTheory and ConditionalFact tests

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#4495]
When we transitioned to dotnet cli, we started using `xunit.console.exe` to run full .NET tests. Currently, this is not finding tests marked with `[ConditionalTheory]` or `[ConditionalFact]`.

Example: Microsoft.EntityFrameworkCore.Commands.FunctionalTests should have 109 tests, but only 98 are discovered. The [tests](https://github.com/aspnet/EntityFramework/files/118126/tests.txt) should in include `OperationExecutorTest`, but they are not discovered.

Related: https://github.com/aspnet/Testing/issues/203 (EF implements its own discoverers, but problably requires the same fix Testing needs.)

**Comment by bricelam** [comment]
Hmm, this could be due to not using the full assembly name in `[XunitTestCaseDiscoverer]`. The DNX CLR host was more lenient about things like this.

**Comment by natemcmaster** [comment]
What would the full assembly name be? Currently it is set to `"Microsoft.EntityFrameworkCore.FunctionalTests"`. Could this be due to strong naming or versions?

**Comment by natemcmaster** [comment]
It appears there is nothing wrong with EF's implementation. This is a KoreBuild and xunit issue. See https://github.com/xunit/xunit/issues/669

**Comment by rowanmiller** [comment]
Passing `-noappdomain` to ` xunit.console.exe` should workaround this... the benchmark tests use a custom discoverer as well and they require this to run

**Comment by natemcmaster** [comment]
I tried the `-noappdomain` solution but for some reason it ignores `ITestCondition`. This means our SQL 2008 tests run all the 2014 tests too and vice versa...I think switching to to `net451
