### ISSUE TITLE
Reconsider ValueGeneratedOnAddOrUpdate + HasDefaultValueSql = Computed Column

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#4501]
Consider the following model where I want a `LastModified` column to be generated by the database. The best way to do this is a default value to handle inserts and a trigger for updates. I'd have to do the trigger outside of EF, but I can setup the default value in my model.

```c#
public class MyContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>()
            .Property(b => b.LastModified)
            .HasDefaultValueSql("GETDATE()")
            .ValueGeneratedOnAddOrUpdate();
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public DateTime LastModified { get; set; }
    }
```

The issue is that DDL assumes that ValueGeneratedOnAddOrUpdate with a default value means I want a computed column. Which I don't... since that would give the current time whenever I select the entity... but I have no way to stop if being a computed column.

```SQL
CREATE TABLE [Blog] (
    [BlogId] int NOT NULL IDENTITY,
    [Modified] AS GETDATE(),
    CONSTRAINT [PK_Blog] PRIMARY KEY ([BlogId])
);
```

**Comment by ajcvickers** [comment]
This is probably because we collapse HasDefaultValueSql and HasComputedColumnSql into one piece of metadata: GeneratedValueSql. If we stop doing this, then Migrations can behave differently.

**Comment by gdoron** [comment]
Exactly what I was trying to do now.
BTW, shouldn't be an EF way of defining a trigger for updates?
Something like:    

    HasValueSqlOnUpdate(string code)

With a lot of effort which probably doesn't worth it, it can even have an overload with `Expression<Func<TEntity, object>>` or something like that.
But the string overload should be relatively quite simple to implement.

What do you think @rowanmiller @ajcvickers?
I might even implement it myself and contribute the code if you think it's a good idea.

**Comment by rowanmiller** [comment]
@gdoron yes I think that could be really useful - I doubt we'd get it into 1.0.0 release but I think it would provide a lot of value.

**Comment by ericwj** [comment]
For Guid columns all that is needed is to say `property.ValueGeneratedOnAdd()`. No need to specify a default value nor any SQL here. They get to be `UNIQUEIDENTIFIER NOT NULL` without `IDENTITY` specification or a default and the GuidValueGenerator produces a value.

That is even true if I don't configure the `Guid Id` property at all - I expected there to be an IDENTITY specification by convention but there isn't - not in 7.0.0-rc1-final at least.

Perhaps it'd be easy to (also) add a value generation strategy for DateTime/DateTimeOffset the same as exists for Guid? Today (on 7.0.0-rc1-final) neither ValueGeneratedOnAdd nor ValueGeneratedOnAddOrUpdate do anything at all for DateTimeOffset columns. Would such a value generation strategy be present, it'd work to generate values for the common Created/Updated columns people seem to want this feature for, for table storage and other non-relational providers too - very convenient.

I'm not quite sure it'd be easy to add this, or whether there'd be interactions between other conventions, but it might be easier to add than patching the SQL and uncollapsing HasDefaultValueSql and HasComputedColumnSql as @ajcvickers mentioned.

**Comment by rowanmiller** [comment]
@ericwj I think this is a decent idea... I'm not sure that "ValueGeneratedXyz" always means "set the current date/time" for `datetime` columns, so it may want to be a different method that sets up a few pieces.
