### ISSUE TITLE
Query: Include collection and order by subquery throws 'Variable names must be unique within a query batch or stored procedure.'

### ISSUE THREAD

**Issue by Tasteful** [aspnet/EntityFramework#4521]
An query that includes a collection and sorting on a subquery throws exception that the parameter name exists multiple times.

Example
```
context.Set<Customer>()
    .Include(c => c.Orders)
    .Where(c => c.CustomerID == customerId)
    .OrderBy(c => context.Set<Order>().Where(oo => oo.CustomerID == customerId).Select(oo => oo.OrderDate).FirstOrDefault())
    .FirstOrDefault();
```
will generate
```
exec sp_executesql N'SELECT TOP(1) [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
FROM [Customers] AS [c]
WHERE [c].[CustomerID] = @__customerId_0
ORDER BY (
    SELECT TOP(1) [oo].[OrderDate]
    FROM [Orders] AS [oo]
    WHERE [oo].[CustomerID] = @__customerId_1
), [c].[CustomerID]',N'@__customerId_0 nvarchar(4000),@__customerId_1 nvarchar(4000)',@__customerId_0=N'ALFKI',@__customerId_1=N'ALFKI'
go
exec sp_executesql N'SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
FROM [Orders] AS [o]
INNER JOIN (
    SELECT DISTINCT TOP(1) (
        SELECT TOP(1) [oo].[OrderDate]
        FROM [Orders] AS [oo]
        WHERE [oo].[CustomerID] = @__customerId_1
    ), [c].[CustomerID]
    FROM [Customers] AS [c]
    WHERE [c].[CustomerID] = @__customerId_0
) AS [c] ON [o].[CustomerID] = [c].[CustomerID]
ORDER BY (
    SELECT TOP(1) [oo].[OrderDate]
    FROM [Orders] AS [oo]
    WHERE [oo].[CustomerID] = @__customerId_1
), [c].[CustomerID]',N'@__customerId_1 nvarchar(4000),@__customerId_0 nvarchar(4000),@__customerId_1 nvarchar(4000)',@__customerId_1=N'ALFKI',@__customerId_0=N'ALFKI',@__customerId_1=N'ALFKI'
go
```
that contains the parameter `@__customerId_1` multiple times

My dev-branch have stopped to working with the latest dotnet changes but added testcase that was failing in RC1-final version. 

Testcase exists here https://github.com/aspnet/EntityFramework/compare/dev...Tasteful:dev-subqueryorderby

Is this bug fixed?

**Comment by Tasteful** [comment]
After more investigation the second part of the SQL should probably be generated like this, in the first one the order is not inserted on correct place.
```
exec sp_executesql N'SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
FROM [Orders] AS [o]
INNER JOIN (
    SELECT DISTINCT TOP(1) (
        SELECT TOP(1) [oo].[OrderDate]
        FROM [Orders] AS [oo]
        WHERE [oo].[CustomerID] = @__customerId_1
    ) AS [__orderby_1], [c].[CustomerID]
    FROM [Customers] AS [c]
    WHERE [c].[CustomerID] = @__customerId_0
	ORDER BY [__orderby_1]
) AS [c] ON [o].[CustomerID] = [c].[CustomerID]
ORDER BY [c].[CustomerID]',N'@__customerId_1 nvarchar(4000),@__customerId_0 nvarchar(4000)',@__customerId_1=N'ALFKI',@__customerId_0=N'ALFKI'
go
```

**Comment by Tasteful** [comment]
This changes seems to work and generate correct SQL https://github.com/Tasteful/EntityFramework/commit/47bc7ad779ce53decfd04f02b28f84f7a4b4af42

This is tested for `RC1-final` and i'm not able to test with the `RC2` due to broken build.

**Comment by smitpatel** [comment]
blocked on #5038 
Scenario without parameters is broken itself atm.

**Comment by Tasteful** [comment]
@smitpatel @maumar This issue can be closed after merged PR. Will not close it because of what I think is wrong milestone.

**Comment by smitpatel** [comment]
PR closes the issues if used with special words which GitHub recognizes. I think fix or close words with issue number works. 😄 
This issue is about repeated variable name. Considering underlying non-parametric query is working correctly now, we should verify that variable names are generated correctly. And if it working correctly now then test coverage should close this issue.

**Comment by Tasteful** [comment]
@rowanmiller @smitpatel This issue is fixed and the commit exists in release-branch. The milestone on this bug is set to `1.1.0` but should be `1.0.0`.
