### ISSUE TITLE
Possible bug? LINQ Query to EFCore not returning results when FK referance is null.

### ISSUE THREAD

**Issue by Eaglef90** [aspnet/EntityFramework#4523]
I think I found a bug in EF Core. I have two rows of test data and am able to pull back the first row with no problems but can't get the second row to return. Digging around and testing shows that this is probably due to the AppovedByID column being null in the row that is not being returned. I have looked but can't figure out how to modify my LINQ query so it will return all rows even if the child table can't be linked in due to a null value. In testing this seems to work fine in EF6 but when I run it against EF core it does not work.

Here is the query:
```
public JsonResult ChangeOrders()
        {
            var ChangeOrdersList = _DbContext.ChangeOrders
                                             .Include(co => co.ApprovalStatus)
                                             .Include(co => co.ApprovedBy)
                                             .Include(co => co.AssignedTo)
                                             .Include(co => co.CreatedBy)
                                             .Include(co => co.CurrentStatus)
                                             .Include(co => co.Impact)
                                             .Include(co => co.Priority)
                                             .Include(co => co.ChangeType)
                                             .Select(co => new ChangeOrderListVM()
                                             {
                                                 ApprovalStatus = co.ApprovalStatus.Name,
                                                 ApprovedBy = (co.ApprovedByUserID.HasValue) ? string.Concat(co.ApprovedBy.FirstName, ' ', co.ApprovedBy.LastName) : "",
                                                 AssignedTo = string.Concat(co.AssignedTo.FirstName, ' ', co.AssignedTo.LastName),
                                                 CreatedBy = string.Concat(co.CreatedBy.FirstName, ' ', co.CreatedBy.LastName),
                                                 CurrentStatus = co.CurrentStatus.Name,
                                                 DateApproved = co.DateApproved,
                                                 DateCompleated = co.DateCompleated,
                                                 DateCreated = co.DateCreated,
                                                 DateStarted = co.DateStarted,
                                                 EstimatedEndDate = co.EstimatedEndDate,
                                                 EstimatedStartDate = co.EstimatedStartDate,
                                                 ID = co.ID,
                                                 Impact = co.Impact.Name,
                                                 Name = co.Name,
                                                 Priority = co.Priority.Name,
                                                 Reason = co.ReasonForChange,
                                                 Type = co.ChangeType.Name
                                             }).ToList();

            return Json(ChangeOrdersList);
        }
```

The Parent Entity:```

    public class ChangeOrder
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        public short? ApprovedByUserID { get; set; }
        public byte ApprovalStatusID { get; set; }
        public short AssignedToUserID { get; set; }
        public short CreatedByUserID { get; set; }
        public byte CurrentStatusID { get; set; }
        public DateTime? DateApproved { get; set; }
        public DateTime? DateCompleated { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime? DateStarted { get; set; }
        public DateTime EstimatedStartDate { get; set; }
        public DateTime EstimatedEndDate { get; set; }
        public byte ImpactID { get; set; }
        public byte PriorityID { get; set; }
        public byte TypeID { get; set; }
        
        [Required]
        public string Name { get; set; }

        [Required]
        public string ReasonForChange { get; set; }        

        [ForeignKey("ApprovalStatusID")]
        public ChangeApprovalStatus ApprovalStatus { get; set; }

        [ForeignKey("ApprovedByUserID")]
        public User ApprovedBy { get; set; }

        [ForeignKey("AssignedToUserID")]
        public User AssignedTo { get; set; }

        [ForeignKey("CreatedByUserID")]
        public User CreatedBy { get; set; }

        [ForeignKey("CurrentStatusID")]
        public ChangeStatus CurrentStatus { get; set; }

        [ForeignKey("ImpactID")]
        public ChangeImpact Impact { get; set; }

        [ForeignKey("PriorityID")]
        public ChangePriority Priority { get; set; }

        [ForeignKey("TypeID")]
        public ChangeType ChangeType { get; set; }
    }
```

The Child Entity:```

    public class User
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public short ID { get; set; }

        [Required]
        public string ADUserName { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Phone { get; set; }

        [Required]
        public DateTime LastUpdated { get; set; }
    }
```

Thinking the problem was because ApprovedBy in the ViewModel was not being filled I tried changing that assignment code to

`ApprovedBy = (co.ApprovedByUserID.HasValue) ? string.Concat(co.ApprovedBy.FirstName, ' ', co.ApprovedBy.LastName) : "",`

but that gives me an error of

>incorrect syntax near the keyword 'is'

It's perfectly possible I am just being stupid and screwing something up but I don't know what it is and based off this working in EF6 as well as the odd error message I am thinking it is a bug.

**Comment by Eaglef90** [comment]
Does anyone know a work around for this? Kind of annoying to not have a way toll pull the all the data back simply because a single, nullable, FK does not contain a value.

**Comment by maumar** [comment]
@Eaglef90 two things you can try:

```
ApprovedBy = co.ApprovedByUserID != null ? string.Concat(co.ApprovedBy.FirstName, ' ', co.ApprovedBy.LastName) : "",
```

might work better than HasValue

alternatively you can split the query into two, one would return everything except ApprovedBy, and the second query would return ChangeOrders and ApprovedBy, and then you can filter the result on the client circumventing the bug.

```

var query1 = _DbContext.ChangeOrders
                                             .Select(co => new ChangeOrderListVM()
                                             {
                                                 ApprovalStatus = co.ApprovalStatus.Name,
                                                 ApprovedBy = "",
                                                 AssignedTo = string.Concat(co.AssignedTo.FirstName, ' ', co.AssignedTo.LastName),
                                                 CreatedBy = string.Concat(co.CreatedBy.FirstName, ' ', co.CreatedBy.LastName),
                                                 CurrentStatus = co.CurrentStatus.Name,
                                                 DateApproved = co.DateApproved,
                                                 DateCompleated = co.DateCompleated,
                                                 DateCreated = co.DateCreated,
                                                 DateStarted = co.DateStarted,
                                                 EstimatedEndDate = co.EstimatedEndDate,
                                                 EstimatedStartDate = co.EstimatedStartDate,
                                                 ID = co.ID,
                                                 Impact = co.Impact.Name,
                                                 Name = co.Name,
                                                 Priority = co.Priority.Name,
                                                 Reason = co.ReasonForChange,
                                                 Type = co.ChangeType.Name
                                             }).ToList();


var query2 = _DbContext.ChangeOrders
                          .Include(co => co.ApprovedBy)
                          .ToList()
                          .Select(co => new { Id = co.Id, ApprovedBy = (co.ApprovedByUserID.HasValue) ? string.Concat(co.ApprovedBy.FirstName, ' ', co.ApprovedBy.LastName) : "", });

// paste correct ApprovedBy from query2 into query1 on the client

```

**Comment by maumar** [comment]
The issue probably got fixed in https://github.com/aspnet/EntityFramework/pull/4141, but will double check.

**Comment by rowanmiller** [comment]
@maumar ping

**Comment by maumar** [comment]
verified that it works in current bits, closing
