### ISSUE TITLE
Windows 10 UWP app with SQLite fails certification kit and store submission

### ISSUE THREAD

**Issue by intui** [aspnet/EntityFramework#4572]
Hi,
we are writing an universal windows 10 app with SQLite as database. I followed the getting started tutorial on http://ef.readthedocs.org/en/latest/platforms/uwp/getting-started.html but the certification kit as well as the result of submitting the app package to the store fails with the following error messages:
Supported API test FAILED
Error Found: The supported APIs test detected the following errors:
API __acrt_iob_func in ucrtbased.dll is not supported for this application type. sqlite3.dll calls this API.
◦API __stdio_common_vfprintf in ucrtbased.dll is not supported for this application type. sqlite3.dll calls this API.
... and some more like these
what am I doing wrong here? 
Any help or a link to a detailed how-to guide would be greatly appreciated.
Thanks, Wido

**Comment by natemcmaster** [comment]
I couldn't reproduce. I ran the Cert Kit  on EFGetStarted.UWP from our docs and it passes everything except the "Branding" test. @intui Are you using the latest UWP tooling ([VS 2015 Update 1](https://www.visualstudio.com/en-us/news/vs2015-update1-vs.aspx))?

**Comment by intui** [comment]
Thanks for pointing me to the right direction. Updating the tooling did it.
