### ISSUE TITLE
Wrong latin SQL encoding in migrations

### ISSUE THREAD

**Issue by tedeschia** [aspnet/EntityFramework#4574]
When I add a migration with SQL command and latin characters, I get them replaced by "?" when updating database.

Let's see an example:

    public partial class TestEncodingMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"some text with latin chars : á é í ñ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }

And this is the script I get from that migration:

    PM> dnx ef migrations script <some prev migration> -c MyDbContext
    
    some text with latin chars: ? ? ? ?
    ;
    
    GO
    
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20160216162901_TestEncodingMigration', N'7.0.0-rc1-16348');

As you can see, all latin characters have been replaced by "?"

**Comment by bricelam** [comment]
Does this happen when you write to a file using the `--output` option?

**Comment by tedeschia** [comment]
Yes, I just tested it now and it happens. I've got:
`some text with accent: � � � �`

**Comment by bricelam** [comment]
Another random thought: Does changing the active code page do anything?
```cmd
chcp 65001
dnx ef migrations script
```

**Comment by tedeschia** [comment]
now I've got
`ï¿½ ï¿½ ï¿½ ï¿½` in Package Manager and  `� � � �` in file output

**Comment by tedeschia** [comment]
[here](http://stackoverflow.com/questions/35438673/ef-core-migrations-wrong-latin-sql-encoding/35446203#35446203) is a workaround meanwhile it's being solved

**Comment by natemcmaster** [comment]
I'm unable to reproduce this with the latest dotnet-ef tooling (RC2) on Windows or OSX. @tedeschia are you still able to reproduce the error when using [dotnet-cli](https://github.com/dotnet/cli) and the latest dotnet-ef package (1.0.0-rc2-20075)?

**Comment by natemcmaster** [comment]
Finally reproduced this, but using the powershell commands, not dnx. The fix in https://github.com/aspnet/EntityFramework/pull/4763 should ensure all files created are UTF8.
