### ISSUE TITLE
CLI Commands: Support .NET Framework-only projects

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#4577]
Currently, in order to use the .NET Core CLI EF commands, your project must target a .NET Core-compatible framework. We could remove this requirement by starting a new net451 process to execute the commands in this case.

~~Currently **blocked** on dotnet/cli#2126~~

### Known Issues

- [ ] Cannot use dotnet-ef on net451 class library project https://github.com/dotnet/cli/issues/2919
```
No executable found matching command "Microsoft.EntityFrameworkCore.Tools.Cli"
```
- [ ] dotnet-ef cannot load the startup assembly. See below https://github.com/aspnet/EntityFramework/issues/4577#issuecomment-217496222

```
System.IO.FileNotFoundException: Could not load file or assembly 'StartupProj' or one of its dependencies. The system cannot find the file specified. File name: 'StartupProj'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint,
```

**Comment by divega** [comment]
> your project must target a .NET Core-compatible framework

Does that mean they run fine in .NET 4.6 or not?

**Comment by bricelam** [comment]
No, the user's assembly needs to be compiled  against the .NET Core contracts.

**Comment by ErikEJ** [comment]
But all the commands work in the PMC, I assume?

**Comment by rowanmiller** [comment]
@ErikEJ correct. PMC will light up for xproj in RC2

**Comment by bricelam** [comment]
Yes, if you want to target only .NET 4.5.1, using the *.csproj + NuGet commands will work as usual.

**Comment by rowanmiller** [comment]
For folks using VS, the primary way to invoke these commands is Package Manager Console (which will be enabled in RC2). That means for the developer workflow, this would only be needed for someone developing against Full .NET and wanting to use the command line tools. This seems like it will be a small set of folks.

One thing we didn't consider in triage though is that this could be very useful for build/deployment integration.

**Comment by rowanmiller** [comment]
Discussed and decided that our general purpose CLI that runs on assemblies (https://github.com/aspnet/EntityFramework/issues/646) rather than our .NET CLI specific commands is the thing that will be best suited to build/deployment/etc. Given that, closing this out but we can reconsider if we see customers wanting this in real applications.

**Comment by bricelam** [comment]
Re-opening. It looks like this will happen as part of dotnet/cli#2020

**Comment by rowanmiller** [comment]
Blocked on design decision about how this works in CLI

**Comment by divega** [comment]
Talked to @bricelam and while this is something we still hope will be fixed by changes to the CLI in RC2. However if that doesn't happen and we need to workaround the limitation we will only do it for RTM, so moving to RTM milestone.

**Comment by scttstrck** [comment]
I have a project which is a windows service where I run asp.net core on kestrel in a thread. As such it only targets framework net451. I found when trying to move to rc2 that "dotnet ef" is missing, so I can't do migrations.

Would this issue be the reason why "dotnet ef" is not found / working?

If so, I would guess, that I could work around this by adding the framework netstandardapp1.5, as long as I can get the project to somehow build on netstandardapp1.5 framework?

Changing 
```"frameworks": {
    "net451": {}
  },```
to
```"frameworks": {
    "net451": {},
    "netstandardapp1.5": {
      "dependencies": {
        "NETStandard.Library": "1.5.0-*"
      },
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ]
    }
  },```
and running "dotnet restore" allows me to run "dotnet ef", however a "dotnet ef migrations -v add test" fails and the output shows:
```Running C:\Program Files\dotnet\bin\dotnet.exe build C:\Dev\move-to-rc2\src\move-to-rc2\project.json -f netstandardapp1.5
Process ID: 10880
Build failed.```

**Comment by natemcmaster** [comment]
@scttstrck 

> Would this issue be the reason why "dotnet ef" is not found / working?

Yes, this is the issue tracking on-going work to make dotnet-ef work on net451.

**Comment by natemcmaster** [comment]
Blocked on https://github.com/dotnet/cli/issues/2505 and https://github.com/dotnet/cli/issues/2566

**Comment by natemcmaster** [comment]
Initial support has been added with changes in #5142. We are still waiting for https://github.com/dotnet/cli/pull/2586 to become available in CLI.

**Comment by natemcmaster** [comment]
Known issue: if a user is trying to use dotnet-ef on a net451 project where "buildOptions" > "emitEntryPoint": false, dotnet-ef cannot execute. It tries to dispatch to a command inside `bin/Debug/net451/win7-x64/Microsoft.EntityframeworkCore.Tools.Cli.exe`, but for class libraries, the command is in `bin/Debug/net451/Microsoft.EntityframeworkCore.Tools.Cli.exe`.

**Comment by natemcmaster** [comment]
Blocked: https://github.com/dotnet/cli/issues/2919

**Comment by natemcmaster** [comment]
Second issue: dotnet-ef cannot load the startup assembly in desktop .NET when executing on a different project. This was a design oversight on our part. Here is the issue:

### In PowerShell
```
LibProj/
    LibProj.csproj
    TestContext.cs
    - Dependency on Ms.EfCore.Sqlite
WebApp/
    WebApp.csproj
    Startup.cs (provides connection string)
    - References LibProj
    - Dependency on Ms.EfCore.Tools
```
`Add-Migration Init -Project LibProj -StartupProject WebApp`
The powershell will load **`WebApp.dll`**, using the app domain base path as `WebApp/bin/Debug/`. Because WebApp references LibProj, all assemblies need to run migrations are in  `WebApp/bin/Debug/` and can be reflected on.

### In dotnet-cli
```
LibProj/
    project.json 
    TestContext.cs
    - Dependency on Ms.EfCore.Sqlite
    - targets "net451"
WebApp/
    project.json 
    Startup.cs (provides connection string)
    - References LibProj
    - Dependency on Ms.EfCore.Tools
    -     - targets "net451"
```
`C:\LibProj\ > dotnet ef migrations add --startup-project ../WebApp`
The CLI invokes `LibProj/bin/Debug/net451/Microsoft.EntityFrameworkCore.Tools.Cli.exe` which means the app domain base directory does not include **WebApp.dll**. When we try to load WebApp.Startup, .NET can't find the right assembly *becauase it isn't availalbe in this app domain*. Instead, Microsoft.EntityFrameworkCore.Tools.Cli needs to setup a new app domain pointed at `WebApp/bin/Debug/net451` in order to load Startup.

**Comment by natemcmaster** [comment]
Base support for CLI commands on desktop is added for RC2. Remaining issues are tracked else where. 

See #5311 and https://github.com/dotnet/cli/issues/2645
