### ISSUE TITLE
Should [DesignTimeProviderServices] be in M.EFCore.dll?

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#4579]
It's currently in Relational, but for the same reasons as `[DbContext]`, it feels like it should be in the core assembly.

cc @lajones

**Comment by lajones** [comment]
I've no objection. If we had a "provider functionality but for all providers, not just relational ones" nupkg to me it would be better there. But since we don't have that `EFCore` is fine. But what were the reasons for `[DbContext]`?

**Comment by bricelam** [comment]
The main reason behind putting `[DbContext]` there was that, even though it is currently only used by relational providers, it is a general enough concept that could be expanded to other classes of providers.

**Comment by lajones** [comment]
Yep - agreed - it's pretty much the same situation.

**Comment by lajones** [comment]
Fixed with 8b40798.

**Comment by lajones** [comment]
Note for providers: the namespace and name of the attribute didn't change - just which package it is stored in - from `Microsoft.EntityFrameworkCore.Relational` to `Microsoft.EntityFrameworkCore`.
