### ISSUE TITLE
Cannot add Microsoft.EFCore.Relational.Design.FunctionalTest package to test project

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#4613]
With build 16898 I can no longer add the above package to a Classic .NET 4.6 test project - see an error about NuGet 3.4... What to do? (Nuget 3.4 does not seem to be available)

**Comment by bricelam** [comment]
I wonder if [Visual Studio 2015 Update 2 CTP](https://www.visualstudio.com/en-us/downloads/update2-prereleases) includes it...

**Comment by ErikEJ** [comment]
Let me give it a try!

**Comment by bricelam** [comment]
Is this fixed? I just tried it with an internal build of Update 2 RC, and it worked. I don't actually see anything in the dependency closure that would require NuGet 3.4...

**Comment by bricelam** [comment]
Closing. If it still doesn't work, the answer is to wait for a public release of NuGet 3.4

**Comment by ErikEJ** [comment]
@bricelam Yes, Update 2 contains NuGet 3.4, but now I am blocked getting new packages for other reasons https://github.com/aspnet/EntityFramework/issues/4708
