### ISSUE TITLE
Include doesn't work with Skip/Take

### ISSUE THREAD

**Issue by cbmek** [aspnet/EntityFramework#4615]
When i do simple include (for one-to-many relation) it works ok:

`_context.MyCollection.Include(m => m.OtherItem).ToList()'`

But when I also add Skip/Take to it, the Include is dropped, and reference property is null.

`_context.MyCollection.Include(m => m.OtherItem).Skip(10).Take(20).ToList()'`

It always worked ok, so what am I doing wrong with EF7?

Edit: I've also checked SQL query in debug mode, and it just don't use any JOINs after adding Skip/Take.

**Comment by cbmek** [comment]
I just found out that it didn't do Include (INNER JOIN) not because of skip/take only but also because of Select. So it seams that this order don't do inner join:

`_context.MyCollection.Include(m => m.OtherItem).Skip(10).Take(20).Select(...)`

but this one works ok:

`_context.MyCollection.Include(m => m.OtherItem).Select(...).Skip(10).Take(20)`

**Comment by divega** [comment]
Reopening so that we can take a look. @maumar does this sound like a dupe?

**Comment by divega** [comment]
Looks somewhat similar to #3804. Cc @anpete

**Comment by anpete** [comment]
Verified fixed.

**Comment by thefenix1** [comment]
I still see this problem. Which version this is fixed in? I'm using rc1 and include is NOT working for me when using skip and take

Thanks!

**Comment by smitpatel** [comment]
@thefenix1 - It is fixed in RTM release which is available on nuget.
