### ISSUE TITLE
Remove rdxml scaffolding

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#4618]
Remove the rdxml scaffolding to simplify our code and reduce maintenance load.

Triage: this is a TODO task to do *after* ~~RC2.~~ updated tooling releases.

**Comment by bricelam** [comment]
I wonder if we should also try and block native compilation if the updated Win10 Tools aren't installed.

**Comment by rowanmiller** [comment]
I think we should do this in RC2 (not after) since updated tooling will be available.

**Comment by rowanmiller** [comment]
@natemcmaster you can go ahead and do this now. We are already broken on the current UWP tooling.
