### ISSUE TITLE
SelectMany with long property

### ISSUE THREAD

**Issue by carlcamilleri** [aspnet/EntityFramework#4640]
Given the below (simplified) model:

```C#
 public partial class SizeDimensions
    {
        public SizeDimensions()
        {
        }

        public long Id { get; set; }
}

public partial class SiteProducts
{
   public virtual ICollection<SizeDimensions> SizeDimensions { get; set; }
}
```

The below query compiles:
```C#
  //select parents
   var q = 	from p in dbContext.Products
				join sp in dbContext.SiteProducts
				on p.Id equals sp.ProdId
                where p.Id = 1
				select sp;

	//get children	
	var q2 = q.SelectMany(e => e.SizeDimensions);
	
```

However, executing q2.ToList() returns the following error:
Property 'Int64 Id' is not defined for type 'SizeDimensions'

I have tried to change SizeDimensions.Id from long explicitly to Int64 but the same error occurs

I know that I can use INCLUDE statement but the target is to eventually Project only a few of the columns of the child entity (in this case, SizeDimensions)

**Comment by maumar** [comment]
Fixed in 7d27bf6527391cd46dbb09210f7e40f7998e549e
