### ISSUE TITLE
.OfType<>() breaks query

### ISSUE THREAD

**Issue by BogeyCode** [aspnet/EntityFramework#4655]
Hi,

I'm using EntityFramework.SQLite 7.0.0-rc1. I have two simple DTOs:

    public class Bond
    {
        [Key]
        public virtual string ISIN { get; set; }
        public virtual ICollection<Cashflow> Cashflows { get; set; }
    }

    public class Cashflow
    {
        [Key]
        public virtual Guid ID { get; set; }
        public virtual DateTime Time { get; set; }
        public virtual double Amount { get; set; }
    }

and a pretty plain Context

    public class Context : DbContext
    {
        public DbSet<Bond> Securities { get; set; }
        
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionSB = new SqliteConnectionStringBuilder { DataSource = @"C:\test.db" };
            var connectionString = connectionSB.ToString();
            var connection = new SqliteConnection(connectionString);
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlite(connection);
        }

    }

`

I'm doing three similar queries with this dbSet; two of these work, one of them throws an exception:

    using (var context = new Context())
            {
                var thisWorks = context.Securities.OfType<Bond>().Include(b => b.Cashflows).ToArray().SelectMany(b => b.Cashflows).ToArray();
                var thisAlsoWorks = context.Securities.Where(b => b.Cashflows.Count() > 0).ToArray();

                var thisThrows = context.Securities.OfType<Bond>().Where(b => b.Cashflows.Count() > 0).ToArray();
            }

Especially query "thisAlsoWorks" and "thisThrows" are almost identical, only that the latter uses an .OfType<Bond>() in between.

The exception thrown is a TargetInvocationException in EntityFramework.Core.dll; inner exception (loosely translated as my VS is not in English) Value must not be NULL. Parameter name: provider.

Stacktrace:
    Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor._CreateEntityQueryable[TResult](IAsyncQueryProvider entityQueryProvider)

Is this in any way intended behaviour, or bugged?

In my above example, using OfType<Bond>() is pretty useless of course because that's the dbSet's type anyway; but this can become problematic if dbSet is of some base type and you're trying to work with a property specific to a more derived type (which is how I encountered this issue in the first place).

**Comment by maumar** [comment]
this works in current bits, closing
