### ISSUE TITLE
Enable OSX on Travis

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/EntityFramework#4662]
Is that intentional? cc @bricelam

**Comment by divega** [comment]
Cc @natemcmaster

**Comment by natemcmaster** [comment]
It is intentional. Last I checked it doesn't work because dotnet restore can't find runtime packages for OSX Mavericks. https://github.com/aspnet/EntityFramework/blob/dev/.travis.yml#L5 and discussion on https://github.com/dotnet/corefx/pull/4729

**Comment by victorhurdugaci** [comment]
We can upgrade to a newer OSX if that would solve the problem

**Comment by natemcmaster** [comment]
Didn't know you could do that on Travis.  Try OSX Yosemite or newer

**Comment by natemcmaster** [comment]
@victorhurdugaci unless you know something I can't find, it seems we are stuck with OSX 10.9 on Travis. https://docs.travis-ci.com/user/osx-ci-environment/

**Comment by victorhurdugaci** [comment]
Oh... I thought they have newer ones. I'm curious, is it a particular package that doesn't support Mavericks? All our builds seem to work fine on travis

**Comment by natemcmaster** [comment]
I believe almost all CoreCLR packages don't support osx 10.9. See https://travis-ci.org/aspnet/Microsoft.Data.Sqlite/jobs/111531582#L2820. Dotnet-restore fails with `(pkg) provides a compile-time reference assembly for (pkg) on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.9-x64.` We disabled travis on https://github.com/aspnet/Microsoft.Data.Sqlite too for the same reason.

**Comment by natemcmaster** [comment]
Aha. The secret is `osx_image` https://docs.travis-ci.com/user/languages/objective-c

**Comment by natemcmaster** [comment]
Re-marking for triage.
Currently Travis's agents are underpowered and our build on OSX takes too long. All travis builds on OSX agents fail. We test internally on OSX so the Travis CI is redundant anyways.

**Comment by bricelam** [comment]
Hmm... Is this the reason we've been waiting for to split the repository?

**Comment by rowanmiller** [comment]
@natemcmaster how much do we need to reduce? If it's just a minute, then we could split out benchmarks pretty easy... if it's more then it may be more work.

**Comment by natemcmaster** [comment]
The build times out at 50 minutes. On the last run, this happened in the middle of InMemory functional tests. Pulling out microbenchmarks may save a little time on compilation, but these tests don't even run within the 50 minute window.

**Comment by natemcmaster** [comment]
Just noting some ideas for how to improve build time:

 - cache nuget packages (has it's own issues. See https://github.com/aspnet/Universe/issues/394)
 - only build for coreclr. Skip compiling for net451. (Should cut build time in half.)
 - Parallelize test assemblies.
