### ISSUE TITLE
Include will remove the where clause already there.

### ISSUE THREAD

**Issue by sumtec** [aspnet/EntityFramework#4698]
Hi,

For something like:
``` csharp
var query = 
    from item in (
        from user in _db.User
        where user.UserName == 'something ignored'
        select user
   ).Include(x => x.Company)
   where item.Company.Name == "only this will be filtered"
   select item;
```

It actually ignores the where clause inside and becomes:
``` csharp
var query = from item in _db.User.Include(x => x.Company)
                   where item.Company.Name == "only this will be filtered"
                   select item;
```

It seems like, when calling the Include, it will go straight to the bottom of the source's expression tree and take the DbSet there and ignore everything already in the expression tree.

The reason I make such kind of weird query is that I am trying to provide functions to filter different things like BeforeDate, AfterDate, WithName, etc. All of them have the similar form of (IQueryable<T>, U) -> IQueryable<T>. With this, I can provide flexible search by combining all those things together as users' wish.

Now, it seems like it doesn't like this. However, I think it's quite easy to make it possible. The only thing to do is to rebuild the expression tree and put those expression node back like this:

``` csharp
var query = 
    from item in (
        from user in _db.User.Include(x => x.Company) // <-- move to here
        where user.UserName == 'something ignored' // <-- but not forgetting the else.
        select user
   ) //<-- move the Include call from here
   where item.Company.Name == "only this will be filtered"
   select item;
```

Yes, there is a way to walk around. However, we have to take the Include call out and design a registration pattern to provide the root source of the query. It's not straight forward. And I can't see why we have to do it that way if the Include() call doesn't drop the where (or maybe also the select) clause.

Regards,
Frank

**Comment by maumar** [comment]
This no longer repros in current bits. Must have been fixed by one of the improvements to Include or Navigation Property handling.

This is the SQL that we now generate:

```
                SELECT [user].[Id], [user].[CompanyId], [user].[UserName], [c].[Id], [c].[Name]
                FROM [Users] AS [user]
                INNER JOIN [Company] AS [user.Company] ON [user].[CompanyId] = [user.Company].[Id]
                INNER JOIN [Company] AS [c] ON [user].[CompanyId] = [c].[Id]
                WHERE ([user].[UserName] = N'something ignored') AND ([user.Company].[Name] = N'only this will be filtered')
```
