### ISSUE TITLE
ExpressionEqualityComparer.GetHashCode missing ExpressionType.Invoke

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#4705]
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode throws if the node is an expression is `ExpressionType.Invoke`

**Comment by natemcmaster** [comment]
Also missing `ExpressionType.Default`

**Comment by Villason** [comment]
Any workaround for this bug? This totally breaks my Web App.

**Comment by divega** [comment]
@Villason if there is a workaround is going to depend on  how the query looks like.

**Comment by mikary** [comment]
Fixed in #5477
