### ISSUE TITLE
cannot add EFCore.Relational build 20093 to .NET 4.5.1 class library

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#4708]
On VS 2015 Update 1 getting this:

Added package 'Microsoft.Extensions.Options.1.0.0-rc2-20093' to folder 'C:\Code\EF7SQLCE\packages'
Install failed. Rolling back...
Package 'Microsoft.Extensions.Options.1.0.0-rc2-20093 : Microsoft.Extensions.DependencyInjection.Abstractions [1.0.0-rc2-20093, ), Microsoft.Extensions.Primitives [1.0.0-rc2-20093, )' does not exist in project 'EntityFramework.SqlServerCompact40'
Removed package 'Microsoft.Extensions.Caching.Abstractions.1.0.0-rc2-20093 : Microsoft.Extensions.Primitives [1.0.0-rc2-20093, )' from 'packages.config'

**Comment by bricelam** [comment]
Ugg. :frowning: Yet another issue just like aspnet/Logging#376 @Eilon Can we add a rule to our package verification thingy for this?

**Comment by ErikEJ** [comment]
Nice turnaround time there, @bricelam :smile:

**Comment by Eilon** [comment]
@bricelam it's fairly easy to add rules to it. Source code is here if you want to take a crack at it: https://github.com/aspnet/DnxTools/tree/dev/src/NuGetPackageVerifier

Question is: do you feel like this is likely to break again in the future? If so, we should add the rule. But if this is likely a one-time thing that we'll clear up and likely never see again, the value of course might not be high enough.

**Comment by ErikEJ** [comment]
@Eilon Sadly, this has already happended before...

**Comment by Eilon** [comment]
@ErikEJ indeed, I'm just wondering if this is a one-time cleanup or if it's something that'll keep reappearing. Adding tests has its own cost that has to be balanced. (Everything is slower, tests can be flakey or have their own bugs, etc.)

**Comment by bricelam** [comment]
> Do you feel like this is likely to break again in the future?

Yes, it happens at least once a release.
