### ISSUE TITLE
Investigate possible perf issues in reverse engineering

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#4735]
The SqlServer reverse engineering E2E tests tests occasionally fail with this error:

```
System.Data.SqlClient.SqlException : A transport-level error has occurred when
 receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
```

Could be 

1. Network issues
2. Server dropped connection
3. Server too busy

If its #3, it could be that we have perf issues in SqlServerDatabaseModelFactory.

**Comment by rowanmiller** [comment]
We have done sanity testing that reverse engineer perf is ok with decent size databases. This is likely just a test issue.
