### ISSUE TITLE
CLI commands puts SQLite files in the nuget folder containing dotnet-ef

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#4765]
A relative path in the SQLite connection string + dotnet-ef  = the root for the relative path is the folder containing dotnet-ef.dll. This is because Microsoft.Data.Sqlite relies on AppContext.BaseDirectory, [which is Package.Current.InstalledLocation.Path](https://github.com/dotnet/corefx/blob/master/src/System.AppContext/src/System/AppContext.cs#L28).

![image](https://cloud.githubusercontent.com/assets/2696087/13689873/f2bce890-e6e0-11e5-8779-b67d9149f83a.png)

To reproduce:
```c#
    public class TestContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Filename=./test.db");
        }
    }
```
```
dotnet ef migrations add First
dotnet ef database update
```

**Comment by bricelam** [comment]
Makes sense; that's the application's base directory. We'll need to use some sort of override mechanism that `M.D.Sqlite` can use. Is there a .NET Core equivalent to `AppDomain.SetData()`?

**Comment by bricelam** [comment]
Ironically, if we just let SQLite use the current directory, it would be correct. :smile:
