### ISSUE TITLE
Migrations :: exception thrown when trying to add migration using regular dotnet project (csproj)

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#4796]
Exception is as follows:

Add-Migration : Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Type 'Microsoft.EntityFrameworkCore.Design.OperationException' in assembly 
'Microsoft.EntityFrameworkCore.Commands, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' is not marked as serializable."
At line:1 char:1
+ Add-Migration Mig01 -Verbose

**Comment by bricelam** [comment]
[This code](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Commands/Design/OperationExecutor.cs#L40-L50) needs to be lazy so exceptions can be passed properly to the result handler.

**Comment by bricelam** [comment]
@maumar It should work if you ensure that your startup project references your migrations project (or you set your startup project to your migrations project before executing).
