### ISSUE TITLE
Latest RC2 packages do not install in latest UWP builds

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#4802]
The errors are currently in our dependencies, so there is likely nothing to do on our side other than test and report issues to the appropriate teams. I've reported the current issue with the `System.AppContext` package to .NET Core folks.

> System.AppContext 4.1.0-rc2-23826 provides a compile-time reference assembly for System.AppContext on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.
At line:1 char:1
install-package Microsoft.EntityFrameworkCore.Sqlite -pre
~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [Install-Package], Exception
FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by ericstj** [comment]
Yeah, we know latest is broken.  UWP should only be using the stable meta-package until that work is done.

**Comment by rowanmiller** [comment]
Figured as much, just opened this to track making sure everything works on our side once things stabilize - the last few releases we've had to do additional work in our packages once everything under us is working.

**Comment by natemcmaster** [comment]
> UWP should only be using the stable meta-package until that work is done.

EF doesn't even work against the stable meta-package either. @ericstj What version of Ms.NETCore.UWP should we ensure works for RC2?

**Comment by natemcmaster** [comment]
No updated yet. Still blocked on packaging issues in .NET Core (using rc2 build 23931).

**Comment by natemcmaster** [comment]
Can install EF.SQLite now, but UWP is still broken. Blocked on https://github.com/dotnet/corefx/issues/7582

**Comment by natemcmaster** [comment]
Are we intentionally leaving out runtime assemblies for UWP in RC2 from these BCL libraries? Or is this nuget installer error?

Using rc2-23931, the following BCL nupkgs are missing runtime assemblies for UWP, which causes installing EF to fail against UWP 5.1.0

```csv
System.AppContext
System.Collections
System.Diagnostics.Debug
System.Diagnostics.Tracing
System.Globalization
System.IO
System.IO.FileSystem
System.Reflection
System.Reflection.Emit.ILGeneration
System.Reflection.Extensions
System.Reflection.Primitives
System.Resources.ResourceManager
System.Runtime
System.Runtime.Extensions
System.Runtime.Handles
System.Runtime.InteropServices
System.Text.Encoding
System.Threading.Tasks
```

**Comment by ericstj** [comment]
That's happening because you're upgrading all those packages which have been split between ref/lib without bringing in the lineup that pulls in the lib packages.  I'd expect the latest 5.2.0 rc3 UWP meta-package to work.

**Comment by ericstj** [comment]
Alternatively, just bringing in the MS.NETCore.Platforms latest may solve the problem, but I believe you'll hit a couple other issues in the RC2 packages for UWP that have only been fixed in the RC3 branch (eg: AppContext, Linq.Expressions).

**Comment by natemcmaster** [comment]
>  I believe you'll hit a couple other issues in the RC2 packages for UWP that have only been fixed in the RC3 branch (eg: AppContext, Linq.Expressions).

So, then for the sake of our RC2 release, we should make sure we pull in stable packages in UWP 5.1.0. I believe this implies we will need to cross-compile, as we did for RC1.

**Comment by ericstj** [comment]
I think that's still the safest thing to do.  As before you don't actually need to cross compile but just have a separate dependency set but if you're using project.json > pack you have to cross compile.

**Comment by natemcmaster** [comment]
> you'll hit a couple other issues in the RC2 packages for UWP that have only been fixed in the RC3 branch (eg: AppContext, Linq.Expressions).

What would it take to get these in RC2?

**Comment by Eilon** [comment]
@natemcmaster I think at this point I'd do the cross compilation, because we know it will work.

**Comment by natemcmaster** [comment]
> we know it will work.

I'm not so sure it will. It did for RC1, but I've not yet been able to craft the right project.json's to make dotnet-restore, dotnet-pack, UWP, and EF happy together.

**Comment by natemcmaster** [comment]
I'm beginning to fear we may not be able to get this working for RC2 :skull:. I found the magic project.json a user needs to get packages to install AND to get build working.

Nota bene: order matters
```
Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5.1.0
Install-Package System.Reflection.Emit.ILGeneration -Version 4.0.0
Install-Package Microsoft.NETCore.Platforms -Pre
Install-Package Microsoft.Win32.Primitives -Pre
Install-Package System.Diagnostics.Tools -Pre
Install-Package System.Globalization.Calendars -Pre
Install-Package System.Net.Sockets -Pre
Install-Package System.Threading.Timer -Pre
Install-Package Microsoft.EntityFrameworeCore.Sqlite -Pre
```

Result json:
```json
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-rc2-20507",
    "Microsoft.NETCore.Platforms": "1.0.1-rc2-23931",
    "Microsoft.NETCore.UniversalWindowsPLatform": "5.1.0",
    "Microsoft.Win32.Primitives": "4.0.1-rc2-23931",
    "System.Diagnostics.Tools": "4.0.1-rc2-23931",
    "System.Globalization.Calendars": "4.0.1-rc2-23931",
    "System.Net.Sockets": "4.1.0-rc2-23931",
    "System.Reflection.Emit.ILGeneration": "4.0.0",
    "System.Threading.Timer": "4.0.1-rc2-23931"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

:warning: Here's the kicker. After all that, the app will build and run and then crash on launch with this bug: https://github.com/dotnet/corefx/issues/7582 which was closed with "will fix in RC3".

**Comment by ericstj** [comment]
Why are you updating the following?
    "Microsoft.NETCore.Platforms": "1.0.1-rc2-23931",
    "System.Threading.Timer": "4.0.1-rc2-23931"
    "Microsoft.Win32.Primitives": "4.0.1-rc2-23931",
    "System.Diagnostics.Tools": "4.0.1-rc2-23931",
    "System.Globalization.Calendars": "4.0.1-rc2-23931",
    "System.Net.Sockets": "4.1.0-rc2-23931",

**Comment by natemcmaster** [comment]
Platforms: https://github.com/aspnet/EntityFramework/issues/4802#issuecomment-207077106

The others:
![image](https://cloud.githubusercontent.com/assets/2696087/14394568/bc5a9574-fd81-11e5-8457-cc293c845b7d.png)

**Comment by ericstj** [comment]
That previous comment was about trying to use the *latest* packages in UWP.  I thought we had switched gears to use stable dependencies for UWP.

I would have expected you to do something like the following, like was done in RC1:
dependencyGroup TFM=uap10.0
  ...stable dependencies...
dependencyGroup TFM=netstandardX.Y
  ...rc2 dependencies...

**Comment by natemcmaster** [comment]
Yes good point. I should have been more clear. Allow me to clarify. 

Approach 1: get EF working with RC2 .NET Core. I think it's clear at this point that approach isn't going to work. My comment here https://github.com/aspnet/EntityFramework/issues/4802#issuecomment-207550659 was regarding that first approach. 

Approach 2: cross-compile to lower dependencies for UWP. My comment https://github.com/aspnet/EntityFramework/issues/4802#issuecomment-207535796 was regarding cross-compiling to stable packages.

Going forward: I'm working on approach 2 now. Status: cross-compiling isn't working (yet).

**Comment by natemcmaster** [comment]
Cross compiling to fix this issue. See PR #5021

**Comment by natemcmaster** [comment]
Fixed https://github.com/aspnet/EntityFramework/pull/5021

**Comment by divega** [comment]
🎉

**Comment by Eilon** [comment]
Mark as Done?

**Comment by natemcmaster** [comment]
Marked.
