### ISSUE TITLE
React to changes in IHostingEnvironment

### ISSUE THREAD

**Issue by pranavkm** [aspnet/EntityFramework#4803]
I checked in a change to unblock the build https://github.com/aspnet/EntityFramework/commit/1eef28b7e93ffb02e354d6e37a4a6cdd370a8551. Using this work item to track follow up work

**Comment by mmalolepszy** [comment]
I think the `ContentRootPath` property of `HostingEnvironment` should be initialized in `StartupInvoker` the same way as `ApplicationBasePath` property of `ApplicationEnvironment`, just like it's done [here](https://github.com/mmalolepszy/EntityFramework/blob/IHostingEnvironment_Changes/src/Microsoft.EntityFrameworkCore.Commands/Design/Internal/StartupInvoker.cs#L100-L104).

Without initializing it you get `ArgumentNullException` in `Startup` while using `SetBasePath` method of `ConfigurationBuilder` class ([example](https://github.com/mmalolepszy/webcrud/blob/master/src/WebCRUD.vNext/Startup.cs#L29-L33)).

**Comment by bricelam** [comment]
:+1:

**Comment by divega** [comment]
It seems https://github.com/aspnet/EntityFramework/commit/1eef28b7e93ffb02e354d6e37a4a6cdd370a8551 added some non-virtual properties and is causing failures in APIConsistencyTest. We should address that too.

**Comment by bricelam** [comment]
That would have been the perfect PR, @mmalolepszy.
