### ISSUE TITLE
Changes in derived related entities are not detected

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#4817]
The derived related entities are tracked as base related entities, so changes to properties that only exist on the derived type are not detected.

Add this test to `InheritanceRelationshipsQueryTestBase`:
```
[Fact]
public virtual void Changes_in_derived_related_entities_are_detected()
{
    using (var context = CreateContext())
    {
        context.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.TrackAll;

        var derivedEntity = context.BaseEntities.Include(e => e.BaseCollectionOnBase)
            .Single(e => e.Name == "Derived1(4)") as DerivedInheritanceRelationshipEntity;

        var firstRelatedEntity = derivedEntity.BaseCollectionOnBase.Cast<DerivedCollectionOnBase>().First();

        Assert.Equal(0, firstRelatedEntity.DerivedProperty);
                
        var firstRelatedEntityEntry = context.ChangeTracker.Entries<DerivedCollectionOnBase>()
            .Single(e => e.Entity == firstRelatedEntity);

        firstRelatedEntity.DerivedProperty = 1;
        context.ChangeTracker.DetectChanges();

        Assert.Equal(EntityState.Modified, firstRelatedEntityEntry.State);
        Assert.Equal(0, firstRelatedEntityEntry.Property(e => e.DerivedProperty).OriginalValue);
        Assert.Equal(1, firstRelatedEntityEntry.Property(e => e.DerivedProperty).CurrentValue);
    }
}
```

Also add `DerivedProperty` to `DerivedCollectionOnBase`

**Comment by sandord** [comment]
I'm hitting this exact issue in EF Core 3.1 today.

What caught my eye is that after updating a property of the derived type with a different value, its value in `CurrentValues` equals the one in `OriginalValues`, which is obviously wrong.

**Comment by ajcvickers** [comment]
@sandord This is a very old issue. If you're seeing this on EF Core 3.1 or 5.0 RC1, then please file a _new issue_ and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by sandord** [comment]
@ajcvickers Thanks for your reply. Luckily, I managed to figure out what was causing the issue.

I was doing this:

    var customer = await dbContext.Customers.GetRequired(customerId);

where `GetRequired()` is an extension method that had another `await` inside it, which obviously isn't very efficient anyway.

If you think this is still worth an issue, I'll post one.

**Comment by sandord** [comment]
> @ajcvickers Thanks for your reply. Luckily, I managed to figure out what was causing the issue.
> 
> I was doing this:
> 
> ```
> var customer = await dbContext.Customers.GetRequired(customerId);
> ```
> 
> where `GetRequired()` is an extension method that had another `await` inside it, which obviously isn't very efficient anyway.
> 
> If you think this is still worth an issue, I'll post one.

It turned out that I was wrong there, everything's fine. I found an intermittent `SaveChanges` call 🤦
