### ISSUE TITLE
Make the repo build without the src folder

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/EntityFramework#4837]
On the CI we want to run tests without src. Tests will get recompiled but the product will be restored from packages.

This repo fails because: 

```
[Building EntityFramework] build-test
[11:29:04][build-test] Can't find file ..\..\src\Microsoft.EntityFrameworkCore.Commands\tools\OperationHandlers.cs
```

Once you fix this, please update `KOREBUILD_NOSRC_EXCLUDE` on the CI

cc @bricelam

**Comment by natemcmaster** [comment]
> Tests will get recompiled

Could you just compile tests once and distribute binaries? We do this successfully on efci
