### ISSUE TITLE
Extracting subquery to a variable causes local evaluation

### ISSUE THREAD

**Issue by jdaley** [aspnet/EntityFramework#4857]
Sorry for the contrived query, it's a simplified example that still reproduces the problem.

If I run this code, it works fine:

    var ids = new List<int>() { 3, 4, 5 };

    var query =
        from a2 in context.Assets
        where (
            from a1 in context.Assets
            where ids.Contains(a1.Id)
            select a1.Id
        ).Contains(a2.Id)
        select a2;

The generated SQL looks good:

    SELECT [a2].[Id], [a2].[Name]
    FROM [Asset] AS [a2]
    WHERE [a2].[Id] IN (
        SELECT [a1].[Id]
        FROM [Asset] AS [a1]
        WHERE [a1].[Id] IN (3, 4, 5)
    )

But if I modify that code to pull the subquery out into a variable...

    var ids = new List<int>() { 3, 4, 5 };

    var subquery =
        from a1 in context.Assets
        where ids.Contains(a1.Id)
        select a1.Id;

    var query =
        from a2 in context.Assets
        where subquery.Contains(a2.Id)
        select a2;

Then EF decides that it "could not be translated and will be evaluated locally":

    Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression '{value(System.Collections.Generic.List`1[System.Int32]) => Contains([a1].Id)}' could not be translated and will be evaluated locally.
    Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression 'Contains([a1].Id)' could not be translated and will be evaluated locally.
    Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression 'Contains([a2].Id)' could not be translated and will be evaluated locally.
    Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression '{from Asset a1 in value(Microsoft.Data.Entity.Query.Internal.EntityQueryable`1[Entities.Asset]) where {value(System.Collections.Generic.List`1[System.Int32]) => Contains([a1].Id)} select [a1].Id => Contains([a2].Id)}' could not be translated and will be evaluated locally.
    Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression '{value(System.Collections.Generic.List`1[System.Int32]) => Contains([a1].Id)}' could not be translated and will be evaluated locally.
    Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression 'Contains([a1].Id)' could not be translated and will be evaluated locally.
    Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression 'Contains([a2].Id)' could not be translated and will be evaluated locally.

And it repeatedly executes the following query, over and over:

    Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory: Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
    SELECT [a1].[Id]
    FROM [Asset] AS [a1]
    Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory: Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
    SELECT [a1].[Id]
    FROM [Asset] AS [a1]
    Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory: Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
    SELECT [a1].[Id]
    FROM [Asset] AS [a1]
    Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory: Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
    SELECT [a1].[Id]
    FROM [Asset] AS [a1]
    Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory: Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
    SELECT [a1].[Id]
    FROM [Asset] AS [a1]

    etc...

The number of times it executes matches the number of rows in the `Asset` table.

Generally speaking, I would have expected any EF IQueryable variable used within a query to be automatically "inlined", if that makes sense, and produce the same SQL as if it had been written as a single LINQ statement?

7.0.0-rc1-final. Windows 10, VS 2015 LocalDB

**Comment by anpete** [comment]
Verified no longer repros.
