### ISSUE TITLE
Commands: React to dotnet/cli#1877

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#4881]
Right now, I think we assume in a few places that the assembly name matches the directory or project name, but after dotnet/cli#1877, they might be different.

**Comment by divega** [comment]
Talked to @bricelam and this won't be a ship blocker for RC2. Currently there are assumptions in multiple places about the assembly (not only in EF Commands or even EF) and that is something we can address for RTM.

**Comment by natemcmaster** [comment]
This was finished as a part of https://github.com/aspnet/EntityFramework/pull/5142
