### ISSUE TITLE
Shadow FK created by replicating the property type from principal key are non-nullable

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#4895]
I tried applying `[ForeignKey(name)]` on a reference navigation property that didn't have a corresponding FK property in the CLR type to pick a column name that was different from the one that the convention would produce. 

This had the unexpected side effect that it made the FK non-nullable (which in turns activated cascade deletes, caused queries with `Include()` on that navigation property to translate to INNER JOINs, etc). 

None of these things happened if the name I specified in the attribute matched what the convention would pick.

I haven't dug into the implementation but I wonder if this affects more than just the nullability of the property, and if the relationship builder should produce nullable FKs by default. 

**Repro**

``` C#
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace ForeignKeyName
{
    public class Tests
    {
        [Fact]
        private static void FKAttribute_should_not_change_nullability_if_it_renames_property()
        {
            using (var context = new BloggingContext())
            {
                var et = context.Model.FindEntityType(typeof(Post));
                var fk = et.FindProperty("AuthorId");
                Assert.True(fk.IsNullable); // fails
            }
        }

        [Fact]
        private static void FKAttribute_should_not_change_nullability_if_it_does_not_rename_property()
        {
            using (var context = new BloggingContext())
            {
                var et = context.Model.FindEntityType(typeof(Post));
                var fk = et.FindProperty("ModifiedById");
                Assert.True(fk.IsNullable); // passes
            }
        }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase();
        }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Body { get; set; }
        [ForeignKey("AuthorId")] // does not match by convention name
        public User PostedBy { get; set; }
        [ForeignKey("ModifiedById")] // matches by convention name
        public User ModifiedBy { get; set; }
    }

    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
```

**Comment by smitpatel** [comment]
Small observation: If the property name matches by convention then `ForeignKeyPropertyDiscoveryConvention` will also set the fk properties.

**Comment by smitpatel** [comment]
Same test results with following models too.
Seems issue arises when fk properties set by some source matches with what convention would find. Not long ago we started matching shadow properties for fk. (See #4591 )
````c#
public class BloggingContext : DbContext
{
	public DbSet<Post> Posts { get; set; }

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseInMemoryDatabase();
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Post>(b =>
			{
				b.HasOne(e => e.PostedBy).WithMany().HasForeignKey("AuthorId");
				b.HasOne(e => e.ModifiedBy).WithMany().HasForeignKey("ModifiedById");
			});
	}
}

public class Post
{
	public int PostId { get; set; }
	public string Body { get; set; }
	public User PostedBy { get; set; }
	public User ModifiedBy { get; set; }
}

public class User
{
	public int Id { get; set; }
	public string Name { get; set; }
}
````

**Comment by smitpatel** [comment]
Found the issue
When we create shadow property by replicating type from the principal key properties, we use the same type hence the property is non-nullable.
If the property name matches with conventional name then the convention will create property which will use nullable type, hence we use the same property instead of creating one by replicating type. Therefore it works.

**Comment by smitpatel** [comment]
@AndriySvyryd - Should we just use nullable type while copying from principal key? :smile:

**Comment by AndriySvyryd** [comment]
@smitpatel Yes, by default FKs are not required and thus should create nullable shadow properties
