### ISSUE TITLE
Investigate test regression in SQL Client on Linux

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#4915]
Possible regression in SqlClient? Started getting failures on Linux after upgrading version of SqlClient. Needs investigation.

```
Microsoft.EntityFrameworkCore.SqlServer.Tests.SqlServerConnectionTest.Creates_SQL_Server_connection_string [FAIL]
System.NotSupportedException : The keyword 'integrated security' is not supported on this platform.
Stack Trace:
     at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
     at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
     at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
     at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
     at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
     at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
     at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
     at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
     at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
     at Microsoft.EntityFrameworkCore.SqlServer.Tests.SqlServerConnectionTest.Creates_SQL_Server_connection_string()
```

**Comment by ErikEJ** [comment]
Is integrated security supported on Linux?

**Comment by natemcmaster** [comment]
No, it isn't. Our test never sets `integrated security = true`, but the test fails anyways.

**Comment by ErikEJ** [comment]
But the test set Trusted_Connection, which is an alias for integrated security: https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.connectionstring(v=vs.110).aspx

**Comment by natemcmaster** [comment]
@ErikEJ thanks for investigating. Yup, that's the source of the issue. Looks like this test was changed by @ajcvickers in https://github.com/aspnet/EntityFramework/commit/6c1c83949e184db648d7b80a4cc36d17a6d3f91c

**Comment by ErikEJ** [comment]
It looks like sqlclient silently ignored the invalid connection string before the update

**Comment by BeelzeBu** [comment]
I have the same issue on OSX, the same code on windows works fine. Is there any sqlclient version the is working?

**Comment by natemcmaster** [comment]
Triage: this is blocking build on x-plat.
cc @cesarbs

**Comment by ErikEJ** [comment]
@natemcmaster Why not change the connection string to use SQL authentication?

**Comment by ajcvickers** [comment]
@natemcmaster @divega I didn't intentionally change the behavior here. Can we just switch the connection string back to what it was?

**Comment by divega** [comment]
@ajcvickers will give this a try.

**Comment by ajcvickers** [comment]
@natemcmaster I can't see how the change I made changed the connection string at all. It had Trusted_Connection=True before as well.

I think what is actually happening is that the new build of SQLClient is validating this when before it was not. Therefore I'll still go ahead and remove it.

**Comment by natemcmaster** [comment]
@ajcvickers I suspected it was something simple like this and just haven't had time to find it myself. 

@saurabh500 did the string builder behavior intentionally change to throw earlier on platforms where integrated security isn't supported?

**Comment by saurabh500** [comment]
cc @corivera Was this your change which affected this?

**Comment by corivera** [comment]
@saurabh500 Yes, before we were only throwing an exception when checking for WindowsIndentity in Connection Pooling code.

**Comment by corivera** [comment]
@BeelzeBu The code checks if the parameter is being set at all
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnectionString.cs#L198

I'll open an issue to only fail when setting the parameter to true

**Comment by ajcvickers** [comment]
I have checked in a fix for this, but it seems our Linux C.I. is broken for other reasons, so I don't know if it has fixed the issue or not. I am marking as blocked for now.

**Comment by natemcmaster** [comment]
I just ran locally on Linux. Test passes. with your fixes @ajcvickers

**Comment by kmjungersen** [comment]
Hello,

I'm still having this issue on OS X with Version : 1.0.1.  My solution will build successfully on both Windows and OS X, but when running ```dotnet ef database update``` the operation fails on OS X but works fine on Windows.  Per the suggestion by @BeelzeBu above, I tried removing ```Trusted_Connection=False``` from my connection string, but then I receive a different error:

```A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)```

My connection string is supposed to create a SQLite DB instance, and that's exactly what happens on Windows, so I'm not sure why the error message references connecting to SQL Server.

I'm not sure if this is relevant or not, but I've started separating my datacontext into a separate class library isolated from the main web app.  So I'm actually running ```dotnet ef --startup-project <path_to_web_project> database update``` per the [recommendations regarding this in the EF docs](https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#targeting-class-library-projects-is-not-supported).

This is vexing because I'm only having the issue on OS X and not Windows.  This might be the wrong place to report this, however this thread was where I originally came because of the original reported issue of ```The keyword 'integrated security' is not supported on this platform.``` and this is clearly platform-specific.  Any ideas on what to do here?

**Comment by natemcmaster** [comment]
@kmjungersen this thread was for a different issue than the one you are experiencing. Can you please open a new issue with your problem? Also, please try to include all the info to completely repro the issue, such as a stand alone project or the relevant code samples. We won't be able to give you much useful guidance with fragments of information.

Thanks,
~Nate
