### ISSUE TITLE
DateTime substraction and TimeSpan comparison cause "New transaction is not allowed because there are other threads running in the session"

### ISSUE THREAD

**Issue by lutsykigor** [aspnet/EntityFramework#4926]
Hi,

Just experienced problem with EF7 7.0.0-rc1-final, when tried to execute next query:

await context.Claimers.Where(c => c.Shares.Any(s => (DateTime.Now - s.Day).TotalDays < 90)).CountAsync()

I know that in EF7 there are no more DbFunctions and I can use datetime comparison as with in-memory collections, but this does not work.

I get "New transaction is not allowed because there are other threads running in the session" when use "MultipleActiveResultSets=true" in connection string, and "There is already an open DataReader associated with this Command which must be closed first" without, at the next call within context.

It is no metter I am using async way or syncronous, result is the same. What is interesting - is that it returns correct count, and then next call throws exception.

It is easy to fix this, rewriting code as following:
var dateTime = DateTime.Now.AddDays(-90);
var claimersCount = await context.Claimers.Where(c => c.Shares.Any(s => s.Day > dateTime)).CountAsync(); 

But I think I may point you to resolving that problem.

Anyway thanks for nice product.
Cheers

**Comment by rowanmiller** [comment]
@mikary can you verify that this is fixed

**Comment by mikary** [comment]
@lutsykigor I attempted to reproduce the issue you described on `EntityFramework.MicrosoftSqlServer 7.0.0-rc1-final` but I did not observe the exception being thrown. The problem may be resolved by upgrading to the latest version (`Microsoft.EntityFrameworkCore.SqlServer 1.0.0-rc2-final`).

Here is the code I used to attempt to reproduce the issue:
```cs
class Program
{
    static void Main(string[] args)
    {
        using (var context = new MyContext(mars: false))
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var now = DateTime.Now;

            for (var index = 0; index < 300; index++)
            {
                var claimer = new Claimer();
                var share = new Share { Claimer = claimer, Day = now - TimeSpan.FromDays(index) };

                context.AddRange(claimer, share);
            }

            context.SaveChanges();
        }

        using (var context = new MyContext(mars: false))
        {
            var count1 = context.Claimers.Where(c => c.Shares.Any(s => (DateTime.Now - s.Day).TotalDays < 90)).Count();
            var count2 = context.Claimers.Where(c => c.Shares.Any(s => (DateTime.Now - s.Day).TotalDays < 90)).Count();

            var total = context.Claimers.Count();

            Console.WriteLine("Count: {0}, {1} Total: {2}", count1, count2, total);
        }

        using (var context = new MyContext(mars: true))
        {
            var count1 = context.Claimers.Where(c => c.Shares.Any(s => (DateTime.Now - s.Day).TotalDays < 90)).Count();
            var count2 = context.Claimers.Where(c => c.Shares.Any(s => (DateTime.Now - s.Day).TotalDays < 90)).Count();

            var total = context.Claimers.Count();

            Console.WriteLine("Mars Count: {0}, {1} Total: {2}", count1, count2, total);
        }

        Console.WriteLine("Done");
        Console.ReadLine();
    }
}

public class MyContext : DbContext
{
    private readonly string _connectionString;

    public MyContext(bool mars)
    {
        _connectionString = mars
            ? "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=DateTimeSubtractTimeSpan;Integrated Security=True;MultipleActiveResultSets=true"
            : "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=DateTimeSubtractTimeSpan;Integrated Security=True";
    }

    public DbSet<Claimer> Claimers { get; set; }
    public DbSet<Share> Shares { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(_connectionString);
    }
}

public class Claimer
{
    public int Id { get; set; }
    public List<Share> Shares { get; set; }
}

public class Share
{
    public int Id { get; set; }
    public Claimer Claimer { get; set; }
    public DateTime Day { get; set; }
}
```

I also attempted some `async` variations as well as multi-threaded access of the same context (not a supported scenario), but I did not observe the described exceptions being thrown.

**Comment by lutsykigor** [comment]
I can confirm that this issue is fixed at RC2, thanks guys for fixing it.
