### ISSUE TITLE
FromSql() with "SELECT *" relies on returned column order

### ISSUE THREAD

**Issue by rmja** [aspnet/EntityFramework#4940]
I get invalid cast exception when selecting from a function using FromSql() where the order in which the columns are returned is not strictly the same as the order EF expects.

Consider the following example where ToListAsync() is right after FromSql() without any other filtering, etc.:
```
await _db.Bases.FromSql("SELECT * FROM someFunctionReturningBases(@p0)", aParameter)
.ToListAsync();
```
The generated SQL is directly:
```
SELECT * FROM someFunctionReturningBases(@p0)
```

However, if instead the query was:
```
await _db.Bases.FromSql("SELECT * FROM someFunctionReturningBases(@p0)", aParameter)
.Where(x => x is DerivedA or x is DerivedB) // Any condition will do
.ToListAsync();
```
then the columns are explicitly named in the SQL:
```
      SELECT [x].[Id], ..., [x].[Created],
      FROM (
          SELECT * FROM someFunctionReturningBases(@p0)
      ) AS [x]
      WHERE [x].[Discriminator] IN (1, 2, 3)
```
The order of the returned columns are now as expected by EF, and the invalid cast exception thrown by the result reader is no longer thrown.

(As a side note, it would be nice if the `Where(x => x is DerivedA or x is DerivedB)` was translated into SQL query so filtering on the discriminator was `WHERE [x].[Discriminator] IN (1, 2)` instead of `WHERE [x].[Discriminator] IN (1, 2, 3)`.)

rc1

**Comment by divega** [comment]
@rmja thanks for reporting this. We have code that is supposed to deal with arbitrary column order when `FromSql() ` is used without composition and the user SQL is sent to the server as is,  but I guess we must have a bug there. I suspect this might be the case with Inheritance but otherwise it would be helpful if you could provide a full listing of the model (and database) so we can repro on our side.

**Comment by rmja** [comment]
@divega sure, here you go https://github.com/rmja/EntityFrameworkIssue4940

**Comment by rmja** [comment]
@divega can you reproduce the behavior?

**Comment by divega** [comment]
@rmja haven't tried it yet, but this is now assigned. @mikary can you take a look?

**Comment by mikary** [comment]
@rmja @divega I just ran this against current dev and I encountered #4998 when running the query that was supposed to work properly. The provided repro did not throw any exceptions, so it was probably resolved by other fixes we have had since RC1.

**Comment by rmja** [comment]
@mikary I can confirm that it works on the latest dev bits, sorry for net checking that first.
