### ISSUE TITLE
Update pipeline: Add tests for Sargability of non-Unicode string keys

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#4949]
(Tracking this separately from query which is covered in #4686 since we have a fix for that one)

Update and delete operations on tables that have non-Unicode keys can have the same performance issues as query, since we always use the key to lookup the right row to update or delete.

I haven't tried this with parameters or measure the difference but running a couple of simple experiments with literals show that quite different plans are produced whether the unicodeness matches or not, e.g. for a modified Northwind Customers table:

``` SQL
CREATE TABLE "Customers" (
	"CustomerID" char (5) NOT NULL ,
	"CompanyName" nvarchar (40) NOT NULL ,
	"ContactName" nvarchar (30) NULL ,
	"ContactTitle" nvarchar (30) NULL ,
	"Address" nvarchar (60) NULL ,
	"City" nvarchar (15) NULL ,
	"Region" nvarchar (15) NULL ,
	"PostalCode" nvarchar (10) NULL ,
	"Country" nvarchar (15) NULL ,
	"Phone" nvarchar (24) NULL ,
	"Fax" nvarchar (24) NULL ,
	CONSTRAINT "PK_Customers" PRIMARY KEY  CLUSTERED 
	(
		"CustomerID"
	)
)
```

The following two queries have quite different costs:

``` SQL
update customers set ContactName = 'Maria Anders' where CustomerID = N'BOLID'

-- Table 'Customers'. Scan count 1, logical reads 6, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.

update customers set ContactName = 'Maria Anders' where CustomerID = 'BOLID'

-- Table 'Customers'. Scan count 0, logical reads 2, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.

```

**Comment by smitpatel** [comment]
After analyzing update pipeline, we are not using literals anywhere in the updates. All the values are passed as parameter. And while adding parameters, we use the underlying property hence Unicode-behavior is maintained from the property.
There are no tests verifying this at the moment. Due to #4952 we cannot test the behavior at present. Once that issue is fixed we can add extra property with non-default facets in `SqlServerEndToEndTest` and verify this scenario.

**Comment by divega** [comment]
Thanks. That is great news!

**Comment by smitpatel** [comment]
#4952 is fixed now so this is unblocked.
@ajcvickers - While fixing #4134 , did you add any test for update pipeline?

**Comment by ajcvickers** [comment]
@smitpatel Yep.

**Comment by smitpatel** [comment]
Should we close this then? 😄

**Comment by ajcvickers** [comment]
Yep. :-)
