### ISSUE TITLE
Test: Verify unicode behaviour of parameters

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#4952]
with f416dd9a71a5a6a69715b4ba40a37e6f9da751ef
we have added test `Non_unicode_parameter_is_used_for_non_unicode_column()` though our current testing framework (or may be logging too) does not allow us to see the type of parameter used.

**Comment by divega** [comment]
As far as I remember in EF6 we decided to log all parameter facets that were not set to their default values. Should we do something similar in EF Core?

**Comment by rowanmiller** [comment]
@smitpatel can you talk to @divega and @anpete about some ideas on how to do this

**Comment by ajcvickers** [comment]
@smitpatel I'm going to look at this since I need it for the parameter stuff I am working on.
