### ISSUE TITLE
EntityFramework.SQLite with UWP

### ISSUE THREAD

**Issue by Brian-Ding** [aspnet/EntityFramework#4971]
The tutorial [here](https://docs.efproject.net/en/latest/platforms/uwp/getting-started.html) talks about how to create a fresh new database in UWP.
but I would like to use a SQLite database file (x.db3) that I already had in UWP, the process in that link seems not working, any help plz?

**Comment by bricelam** [comment]
> not working

We're going to need a bit more info than this. :smile: What specific errors are you seeing?

**Comment by Brian-Ding** [comment]
![1](https://cloud.githubusercontent.com/assets/11363173/14269961/2c49577a-fb1c-11e5-894b-bcf2a68ec5d7.png)
instead of "Blogging.db", i tried both "myDatabase.db3" giving me an error of "cant find xxx table" or "ms-appx:\\\myDatabase.db3", which shows an error of cant open the database

any thoughts on that?

**Comment by natemcmaster** [comment]
@Brian-Ding The connection string you showed is the correct format.
```c#
// in your dbcontext
optionsBuilder.UseSqlite("Filename=myDatabase.db3");
```

Are you initializing your tables? For example:
```c#
// in your app initialization
// if you are using migrations
db.Database.Migrate();

// if NOT using migrations
db.Database.EnsureCreated(); 
// this will create db file and tables only on the first time the app launches. For second and after, you'll need to use migrations to alter existing tables
```
See the ["Create your database" step](https://docs.efproject.net/en/latest/platforms/uwp/getting-started.html#create-your-database).

**Comment by Brian-Ding** [comment]
@natemcmaster The problem is, I would like to use an existing database, which I generated somewhere else, already has several tables and data in it. The "migration" makes the app running, but seems to create a new database file, which is not as I desired.

**Comment by natemcmaster** [comment]
Are you sure your app is connected correctly to the existing database? SQLite will automatically map relative paths into ApplicationData.Current.LocalFolder, i.e. `"Filename=myDatabase.db3"` is really `"Filename={ApplicationData.Current.LocalFolder}/myDatabase.db3"`. If the file is not there, sqlite creates it when it opens the connection. It could be SQLite created an empty db file for you.

**Comment by Brian-Ding** [comment]
![image](https://cloud.githubusercontent.com/assets/11363173/14289652/62fb7ff6-fb8e-11e5-93f2-eef2e6edb697.png)
![image](https://cloud.githubusercontent.com/assets/11363173/14289665/6c5b5a80-fb8e-11e5-9887-90baca27e144.png)

**Comment by Brian-Ding** [comment]
@natemcmaster plz check the screen shots, is there any problem with where I place the database file?

**Comment by Brian-Ding** [comment]
I keep getting the error "no such table", but I am 100% sure that the table exists

do I still need to 
`db.Database.Migrate();
db.Database.EnsureCreated(); 
`

even working with an existing database?

**Comment by natemcmaster** [comment]
Aha, I think I know what is wrong. Are you copying the db file from InstalledLocation to LocalData? By default, your file is not in LocalFolder, but in `Package.Current.InstalledLocation.Path`.

Example: https://github.com/natemcmaster/EntityFramework.PlatformTesting/blob/master/test/UWP.SQLite/UnitTestApp.xaml.cs#L30-38

**Comment by rowanmiller** [comment]
Just another thought...

`EnsureCreated()` won't add tables to an existing database, it either creates the whole thing if it doesn't exist, or does nothing. If you want to add tables to an existing database you need to use migrations.

Not sure if that is the issue or not... just wanted to throw it out.

**Comment by ErikEJ** [comment]
Make sure to copy the file from your installed content: http://erikej.blogspot.dk/2012/08/getting-started-with-sqlite-in-windows.html

**Comment by Brian-Ding** [comment]
@natemcmaster Thank you and all your guys for your help, I will try it when I get back home tonight

**Comment by Brian-Ding** [comment]
Thank you guys for all your great help!! After I copy the database file to localfolder, I finally got the data! Problem solved!

**Comment by natemcmaster** [comment]
@Brian-Ding we're glad to help.
