### ISSUE TITLE
Perf: Model building 4x perf regression

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#4986]
A 4x perf regression has shown up in the [EF Core benchmark that builds the AdventureWorks model](https://github.com/aspnet/EntityFramework/blob/f416dd9a71a5a6a69715b4ba40a37e6f9da751ef/test/Microsoft.EntityFrameworkCore.Microbenchmarks/InitializationTests.cs#L41).

We should fix that :smile: 

![perf](https://cloud.githubusercontent.com/assets/4741851/14293962/b7f30f4e-fb23-11e5-85f1-a2af568d6bc1.png)

**Comment by rowanmiller** [comment]
The most significant regression shows up between builds 609 and 610 of our CI, which isolates it to https://github.com/aspnet/EntityFramework/commit/89c6844d3b5dbb4066ab6856275a40f8f014a442 (Allow inverting non-unique relationships). It looks like there may have been another smaller regression since then as well, but it was during the time our CI was out due to moving to .NET CLI.

**Comment by rowanmiller** [comment]
Putting in RC2 milestone while we dig into this, we may or may not try to take any changes for RC2 based on what we find, risk of fix, etc.

**Comment by AndriySvyryd** [comment]
We are running the `RelationshipDiscoveryConvention` much more often now. Most of the times it runs it doesn't actually do anything, so we could speed up the model building by preemptively detecting those cases and don't do redundant work, however this might introduce subtle bugs so we should do this carefully, with time to properly test it.
