### ISSUE TITLE
CLI Commands: Work with netcoreapp1.0

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#4989]
I'm not sure if the TFM `netcoreapp1.0` has landed everywhere yet, but when it does, we'll need to update our CLI commands to work with it. See [this code](https://github.com/aspnet/EntityFramework/blob/dev/src/dotnet-ef/ReflectionOperationExecutor.cs#L217-L233).

**Comment by natemcmaster** [comment]
Fixed with https://github.com/aspnet/EntityFramework/commit/979148720aadeab7e377efbd7c5faadc12a2a48d
