### ISSUE TITLE
Query ExpressionEqualityComparer throws on Is

### ISSUE THREAD

**Issue by mikary** [aspnet/EntityFramework#4998]
`ExpressionEqualityComparer.GetHashCode` throws a `NotImplementedException.` for expressions with expression type `ExpressionType.TypeIs` (`TypeBinaryExpression`)

```cs
        [Fact]
        public virtual void NotImplementedException_on_is()
        {
            using (var context = CreateContext())
            {
                var birds = context.Set<Animal>().Where(a => a is Bird).ToList();
            }
        }
```

**Comment by divega** [comment]
@mikary how common is the scenario for which you can hit this? Do you think it us something we should prioritize for RC2?

**Comment by anpete** [comment]
@divega Very easy and low risk fix if we decide to take it.

**Comment by rmja** [comment]
+1 This would be really useful! And it would be awesome if it was evaluated server side as mentioned here: https://github.com/aspnet/EntityFramework/issues/4940

**Comment by mikary** [comment]
@rmja The fix for this issue is pretty small, so I opened #5007 to track the client evaluation since those changes will not be related to this fix.

**Comment by divega** [comment]
@mikary let's try to get the fix in for RC2.
