### ISSUE TITLE
Performance issue when querying using async operations.

### ISSUE THREAD

**Issue by Carpi68** [aspnet/EntityFramework#5029]
I'm opening this issue because I didn't see anything already filed here on github.
I'm working with EF7 rc1 and see the same performance drop as described here for EF6: http://stackoverflow.com/questions/28543293/entity-framework-async-operation-takes-ten-times-as-long-to-complete.
I see a tremendous increase of the execution time as soon as I'm using ToListAsync or ToDictionaryAsync. Any help would be highly appreciated.

**Comment by anpete** [comment]
@divega @rowanmiller I think we have addressed the low-hanging fruit here with our recent changes. Any objections to moving this post RTM?

**Comment by rowanmiller** [comment]
I'm fine with that. At least for tracking queries it looks like the async slow down is significantly less than it was in EF6.

**Comment by rowanmiller** [comment]
Latest fixes have gone into 1.1.0
