### ISSUE TITLE
Include() ThenInclude() throws “Sequence contains more than one matching element” exception

### ISSUE THREAD

**Issue by kall2sollies** [aspnet/EntityFramework#5033]
I have a model which involves parent-child relations on 3 levels :

 - `Corporations` have `companies`
 - `Companies` belong to a `corporation` and have `factories`
 - `Factories` belong to a `company`

Since these 3 entities share a lot in common, they all inherit from an abstract `BaseOrganization` entity.

When I try to list all the factories, including their mother companies, and then including their mother corporations, I have these two different scenarios :

 - **Without including**  `BaseOrganization` into the context, code-first creates **three tables (TPC)**. `Include()` and `ThenInclude()` work fine, and I can list factories and traverse relations as expected.
 - **Including** `BaseOrganization` into the context, code-first creates **one table (TPH)** with a discriminator field. `Include()` and `ThenInclude()` throw a `Sequence contains more than one matching element` exception.

This issue (without the inheritance pattern) was already adressed here ( https://github.com/aspnet/EntityFramework/issues/1460).

So I think there is an issue with multi-level relations Include when these relations involve same base types AND when the tables are generated along the Table Per Hierarchy strategy.

Below is the full reproduction code :

		using System;
		using System.Collections.Generic;
		using System.Linq;
		using Microsoft.Data.Entity;

		namespace MultiLevelTest
		{
			// All places share name and Id
			public abstract class BaseOrganization
			{
				public int Id { get; set; }
				public string Name { get; set; }
			}

			// a corporation (eg : Airbus Group)
			public class Corporation : BaseOrganization
			{
				public virtual ICollection<Company> Companies { get; set; } = new List<Company>();
			}

			// a company (eg : Airbus, Airbus Helicopters, Arianespace)
			public class Company : BaseOrganization
			{
				public virtual Corporation Corporation { get; set; }
				public virtual ICollection<Factory> Factories { get; set; } = new List<Factory>();
			}

			// a factory of a company (Airbus Toulouse, Airbus US...)
			public class Factory : BaseOrganization
			{
				public virtual Company Company { get; set; }
			}

			// setup DbContext
			public class MyContext : DbContext
			{
                // if this line is commented, then code first creates 3 tables instead of one, and everything works fine.
				public DbSet<BaseOrganization> BaseOrganizationCollection { get; set; }
				public DbSet<Corporation> Corporations { get; set; }
				public DbSet<Company> Companies { get; set; }
				public DbSet<Factory> Factories { get; set; }

				protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
				{
					optionsBuilder.UseSqlServer(
						@"Server=(localdb)\mssqllocaldb;Database=MultiLevelTest;Trusted_Connection=True;MultipleActiveResultSets=true");
				}

				protected override void OnModelCreating(ModelBuilder modelBuilder)
				{
					base.OnModelCreating(modelBuilder);

					modelBuilder.Entity<Corporation>().HasMany(c => c.Companies).WithOne(c => c.Corporation);
					modelBuilder.Entity<Company>().HasMany(c => c.Factories).WithOne(c => c.Company);
					modelBuilder.Entity<Factory>().HasOne(f => f.Company);
				}
			}

			public class Program
			{
				public static void Main(string[] args)
				{
					using (var ctx = new MyContext())
					{
						ctx.Database.EnsureDeleted();
						ctx.Database.EnsureCreated();

						// Add a corporation with companies then factories (this works fine)
						if (!ctx.Corporations.Any()) CreateOrganizationGraph(ctx);

						// Get all the factories without including anything (this is still working fine)
						var simpleFactories = ctx.Factories.ToList();
						foreach(var f in simpleFactories) Console.WriteLine(f.Name);

						// Get all the factories including their mother company, then their mother corporation
						var fullFactories = ctx.Factories
							.Include(f => f.Company)
							.ThenInclude(c => c.Corporation)
							.ToList();
						foreach (var f in fullFactories) Console.WriteLine($"{f.Company.Corporation.Name} > {f.Company.Name} > {f.Name}");
					}
				}

				public static void CreateOrganizationGraph(MyContext ctx)
				{
					var airbusCorp = new Corporation()
					{
						Name = "Airbus Group",
						Companies = new List<Company>()
								{
									new Company
									{
										Name = "Airbus",
										Factories = new List<Factory>()
										{
											new Factory {Name = "Airbus Toulouse (FR)"},
											new Factory {Name = "Airbus Hambourg (DE)"}
										}
									},
									new Company
									{
										Name = "Airbus Helicopters",
										Factories = new List<Factory>()
										{
											new Factory {Name = "Eurocopter Marignane (FR)"},
											new Factory {Name = "Eurocopter Deutschland (DE)"}
										}
									}
								}
					};

					ctx.Corporations.Add(airbusCorp);
					ctx.SaveChanges();

				}
			}
		}

**Comment by kall2sollies** [comment]
Has anyone had the opportunity to reproduce, and state if that is an actual bug, or an improper approach on my own ?

**Comment by maumar** [comment]
@kall2sollies I ran the scenario on our current bits and it seems to be working. I guess it must have been addressed in one of the Include improvements that we did after RC1 was released. Repro produces the following output:

```
Airbus Toulouse (FR)
Airbus Hambourg (DE)
Eurocopter Marignane (FR)
Eurocopter Deutschland (DE)
Airbus Group > Airbus > Airbus Toulouse (FR)
Airbus Group > Airbus > Airbus Hambourg (DE)
Airbus Group > Airbus Helicopters > Eurocopter Marignane (FR)
Airbus Group > Airbus Helicopters > Eurocopter Deutschland (DE)
```

**Comment by kall2sollies** [comment]
Hello,

It must be as you say, since my code was run against rc1, and also ef7rc1.

So the next release will probably solve that.

Thanks for the reply.

Calendau GUQUET
Via mon iPhone

**Comment by kall2sollies** [comment]
I am unable to migrate my test project to RC2 (ou RC3) builds of EF.
Here's what I did:

- Added rererence to the beta nuget channel (https://www.myget.org/F/aspnetvnext/api/v3/index.json)
- Changed package names to reflect the new naming and version reset

Here's my project.json file:

	{
	  "version": "1.0.0-*",
	  "description": "LinqKitIssue Console Application",
	  "authors": [ "cguquet" ],
	  "tags": [ "" ],
	  "projectUrl": "",
	  "licenseUrl": "",

	  "compilationOptions": {
		"emitEntryPoint": true
	  },

	  "dependencies": {
		"LinqKit": "1.1.3.1",
		"Microsoft.EntityFrameworkCore": "1.0.0-rc2-*",
		"Microsoft.EntityFrameworkCore.Commands": "1.0.0-rc2-*",
		"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-*",
		"Microsoft.Extensions.Caching.Abstractions": "1.0.0-rc2-*"
	  },

	  "commands": {
		"LinqKitIssue": "LinqKitIssue"
	  },

	  "frameworks": {
		"dnx451": { }
	  }
	}

It results in having unresolved dependencies, because they are not compatible with DNX version 4.5.1.

I have tried to change the framework to everything possible or impossible (net451, dnx46, net46, dnx462, net462) but the result would always be the same. Here's the output of dnu list:

	Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16609

	Listing dependencies for LinqKitIssue (D:\Documents\Visual Studio 2015\Projects\LinqKitIssue\src\LinqKitIssue\project.json)

	[Target framework DNX,Version=v4.6.2 (dnx462)]

	Framework references:
	  fx/Microsoft.CSharp
	  fx/mscorlib
	  fx/System
	  fx/System.ComponentModel.DataAnnotations
	  fx/System.Core
	  fx/System.Data
	  fx/System.Transactions

	Package references:
	  EntityFramework 6.1.3
	  Ix-Async 1.2.5
	* LinqKit 1.1.3.1
	  Microsoft.AspNetCore.Hosting.Abstractions 1.0.0-rc2-20466
	  Microsoft.AspNetCore.Hosting.Server.Abstractions 1.0.0-rc2-20466
	  Microsoft.AspNetCore.Http.Abstractions 1.0.0-rc2-20466
	  Microsoft.AspNetCore.Http.Features 1.0.0-rc2-20466
	* Microsoft.EntityFrameworkCore 1.0.0-rc2-20466
	* Microsoft.EntityFrameworkCore.Commands 1.0.0-rc2-20466
	  Microsoft.EntityFrameworkCore.Relational 1.0.0-rc2-20466
	  Microsoft.EntityFrameworkCore.Relational.Design 1.0.0-rc2-20466
	* Microsoft.EntityFrameworkCore.SqlServer 1.0.0-rc2-20466
	* Microsoft.Extensions.Caching.Abstractions 1.0.0-rc2-20466 - Unresolved
	  Microsoft.Extensions.Caching.Memory 1.0.0-rc2-20466
	  Microsoft.Extensions.Configuration.Abstractions 1.0.0-rc2-20466 - Unresolved
	  Microsoft.Extensions.DependencyInjection 1.0.0-rc2-20466 - Unresolved
	  Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc2-20466 - Unresolved
	  Microsoft.Extensions.FileProviders.Abstractions 1.0.0-rc2-20466 - Unresolved
	  Microsoft.Extensions.Logging 1.0.0-rc2-20466 - Unresolved
	  Microsoft.Extensions.Logging.Abstractions 1.0.0-rc2-20466 - Unresolved
	  Microsoft.Extensions.Options 1.0.0-rc2-20466 - Unresolved
	  Microsoft.Extensions.PlatformAbstractions 1.0.0-rc2-20466
	  Microsoft.Extensions.Primitives 1.0.0-rc2-20466 - Unresolved
	  Remotion.Linq 2.0.2
	  System.Diagnostics.DiagnosticSource 4.0.0-rc2-23931
	  System.Text.Encodings.Web 4.0.0-rc2-23931 - Unresolved

**Comment by maumar** [comment]
@kall2sollies Visual Studio is missing the tooling support for RC2 stuff, you can try using .NET cli  which is the replacement for dnx, and a command line. Here is the link to the project, which contains some getting started instructions:
http://dotnet.github.io/getting-started/

**Comment by kall2sollies** [comment]
Among all the things I thought I could try, it has been the only one I didn't, because I thought it was a lightweight version of the runtime, and not the future runtime itself, so ok tomorrow I'll go for it, thanks!

**Comment by kall2sollies** [comment]
Ok I have installed the redist installer and can now run the .Net CLI with dotnet commands (.NET Command Line Tools (1.0.0-beta-001598).
No problem scaffolding a new projet with the `dotnet new` command, but I am still unable to build or run this simple project mentioned above.

Below is my current project.json file. Current framework moniker is set to `net46`, but I also tried `net461`, `netcore50` (as in default CLI hello world project, but it still fails because it either cannot resolve dependencies (when targetting net46), or tells dependencies are not compatible with netcore50 (especially LinqKit, which brings EF6 with).

  {
    "version": "1.0.0-*",
    "description": "LinqKitIssue Console Application",
    "authors": [ "cguquet" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "compilationOptions": {
      "emitEntryPoint": true
    },

    "dependencies": {
      "NETStandard.Library": "1.0.0-rc2-23811",
      "LinqKit": "1.1.3.1",
      "Microsoft.EntityFrameworkCore": "1.0.0-rc3-20637",
      "Microsoft.EntityFrameworkCore.Commands": "1.0.0-rc3-20637",
      "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc3-20637",
      "Microsoft.Extensions.Caching.Abstractions": "1.0.0-rc3-20637"
    },

    "commands": {
      "LinqKitIssue": "LinqKitIssue"
    },

    "frameworks": {
      "net46": { }
    }
  }
