### ISSUE TITLE
DateTime.Parse is evaluated on client

### ISSUE THREAD

**Issue by mauricew** [aspnet/EntityFramework#5035]
In a SQL Server 2014 table with a smalldatetime column, any sort of comparison on said column returns this error:
`SqlException: Conversion failed when converting character string to smalldatetime data type.`

The setup is basic:
```
class Entity {
    [Column(TypeName="smalldatetime")]
    public DateTime Date { get; set; }
}
...
static void main(string[] args) {
    dbContext.Entity.Where(x => x.Date > DateTime.Parse("1/1/2015")).ToList(); // crashes
}
```

I noticed via Profiler that smalldatetime parameters are done the same way as datetime2, which has a precision of up to 7 decimal points of a second. The code for this is _DateTimeFormatConst_ in **RelationalSqlGenerationHelper**. However, in T-SQL a smalldatetime can only be parsed with a precision of one second (rounded to nearest minute as the type can support) So '2015-01-01T00:00:00.0000000' wouldn't work but '2015-01-01T00:00:00' would.

As I'm sure others still use this type for whatever reason that may be needed, can there be an additional format akin to something like `yyyy-MM-dd HH:mm:ss` and an overload to _GenerateLiteralValue_ that supports smalldatetime?

**Comment by smitpatel** [comment]
I tried running above query with latest dev,
It passes successfully. Since we do not know how to translate `DateTime.Parse()` to T-Sql, the where clause is evaluated on client.
I also tried passing the `DateTime.Parse("1/1/2015"))` as a variable which gets converted to parameter.
Query - 
````
var time = DateTime.Parse("1/1/2015");
var query = context.Entities.Where(x => x.Date > time).ToList();
````
Which generated following query
````
exec sp_executesql N'SELECT [x].[Id], [x].[Date]
FROM [Entities] AS [x]
WHERE [x].[Date] > @__time_0',N'@__time_0 datetime2(7)',@__time_0='2015-01-01 00:00:00'
````
Which also does not throw any exception.
Can you provide of full repro code for the issue and tell us which version of EF you are using?

**Comment by mauricew** [comment]
I'm using EF RC1, I just did a test using .NET Core (1.0.0-rc1-update1) and it works successfully, but in Mono 4.2.3 it does not work.

Just to make a record of it, here is a more thorough example of what I did with anonymized variables. It has 2 includes and one join.

````
IEnumerable<SomeViewModel> Result = db.Schedule_Current
    .Include(x => x.IncludeModel1)
    .Include(x => x.IncludeModel2)
    .Join(db.JoinTable1,
        z => new { z.Date, z.SomeInt },
        y => new { y.Date, y.SomeInt },
        (one, two) => new { One = one, Two = two }
    ).Where(x =>
        x.One.Date >= searchDateStart && x.One.Date <= searchDateEnd &&
        x.One.IncludeModel2.SomeString == "abc"
    ).Select(x => new SomeViewModel {
        Name = x.One.IncludeModel1.Name
        StartDate = x.One.Date
    });

foreach(var item in Result) {
    Console.WriteLine(item.ToString());
}

````

x.One.Date is a smalldatetime in this example

**Comment by divega** [comment]
@smitpatel 

> Since we do not know how to translate  DateTime.Parse()  to T-Sql, the where clause is evaluated on client.
> I also tried passing the  DateTime.Parse("1/1/2015"))  as a variable which gets converted to parameter.

Talked to @anpete and we both expected DateTime.Parse() inline in the query to be funcletized (i.e. partially evaluated and included in the query) instead of triggering client side evaluation. Maybe there is something in this case that we missed or that we have regressed?
