### ISSUE TITLE
Functional Tests: Move Specification tests to source

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#5055]
EF has following test projects which are being published to nuget.org
-	Microsoft.EntityFrameworkCore.Relational.FunctionalTests
-	Microsoft.EntityFrameworkCore.FunctionalTests
-	Microsoft.EntityFrameworkCore.Relational.Design.FunctionalTests

These tests depend on dotnet-test-xunit. These tests should be split into Facts which rely on xunit (which will be published to nuget.org) and runnable component (which does not get published).

**Comment by ErikEJ** [comment]
@smitpatel How will this impact my use of these test libraries? Most of my test suite inherit from these libraries...

**Comment by divega** [comment]
@ErikEJ I believe impact is mostly going to be a rename of the package. 

cc @roji who I believe is using this as well.
