### ISSUE TITLE
Make notification change tracking opt-in

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#5075]
Currently we dynamically decide what kind of change tracking to use based on the entity types and even instances used:
* Does not implement INotifyPropertyChanged or INotifyPropertyChanging: use snapshots with change detection
* Implements INotifyPropertyChanged but not INotifyPropertyChanging: use snapshots with change notification
* Implements both INotifyPropertyChanged and INotifyPropertyChanging: use only change notification (with lazy snapshots where original values are needed)

In addition, if an entity instance has a non-notifying collection navigation property instance, then it will still need snapshot change tracking.

Also note:
* These choices will only work correctly if the entity type correctly implements the interfaces for _all_ mapped properties and navigations.
* Entity types may implement these interfaces for reasons other than EF change tracking. In fact, it may be much more likely that entity types implement these interfaces for other reasons--e.g. data binding. In such cases it may be fine to only implement the interfaces for certain properties.

I propose that we change to an opt-in mechanism to switch on notification based change tracking. The options would be:
* Snapshot with change detection (default)
* Snapshot with notifications (I assert that my entity types correctly implement INotifyPropertyChanged for all mapped properties and navigations and the collection navigation properties are all notifying collections.)
* Full notifications (I assert that my entity types correctly implement both INotifyPropertyChanging and INotifyPropertyChanged for all mapped properties and navigations and the collection navigation properties are all notifying collections.)

The APi would allow this setting to be configured for the entire model and for each entity type.

**Comment by rowanmiller** [comment]
:+1:

**Comment by davidroth** [comment]
@ajcvickers  :+1: for the new API.

I guess the third option (correctly implementing _INotifyPropertyChanged_+ _INotifyPropertyChanging_) will show the best performance / lowest memory usage?

@rowanmiller  Are there any benchmarks for these different configurations?
