### ISSUE TITLE
Code first migration. Index name issue

### ISSUE THREAD

**Issue by Loat** [aspnet/EntityFramework#5083]
I have found some issue with index names. I have table declared like this:

![image](https://cloud.githubusercontent.com/assets/6999100/14555162/a0525682-02f9-11e6-8fbe-e097f0898bb0.png)

And code first migration generated code with index name like "IX_ClassName_ColumnName" but i think it should be like "IX_Table_ColumnName"

![image](https://cloud.githubusercontent.com/assets/6999100/14555150/821eb336-02f9-11e6-8979-8cca2aaf0832.png)

**Comment by smitpatel** [comment]
Already fixed in 4eaa473c04b525d83abd0a8378cc993e035eb9a6
