### ISSUE TITLE
Usability: Mention ServiceLifetime in DbContext disposed exception

### ISSUE THREAD

**Issue by mikary** [aspnet/EntityFramework#5087]
Users are likely to encounter this exception when they are using a DbContext that has been registered in DI as a Scoped service when they expect it to be Transient. This would be a good opportunity to provide a message describing how to register the DbContext with a different ServiceLifetime.

**Comment by divega** [comment]
I think it might also be relevant that should only ever encounter this exception if they explicitly dispose the context instance, which is something they can avoid if using DI.
