### ISSUE TITLE
Nit - Spelling on Error Message for missing Microsoft.EntityFramework.Commands

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/EntityFramework#5125]
https://github.com/aspnet/EntityFramework/blob/72af85c13f09654dea9e8cc91a8a70d71c7f1451/src/dotnet-ef/ReflectionOperationExecutor.cs#L85

Microsoft.EntityFramework.Commands -> Microsoft.EntityFrameworkCore.Commands

**Comment by rowanmiller** [comment]
These strings should all be moved to a resources file too

**Comment by natemcmaster** [comment]
Fixed a while ago.
