### ISSUE TITLE
EF 7 Wont Save Changes on Entity With Many-to-Many Relationships

### ISSUE THREAD

**Issue by ElvisHalil** [aspnet/EntityFramework#5133]
I'm not sure if I'm doing something completely wrong (if so, PLEASE let me know!), but I am trying to add to a entity (Devices) which has some relationships using Code First (EF Core).  Here is the model in question:

    [Table("Devices")]
    public class Device
    {
        public int ID { get; set; }

        public string SerialNumber { get; set; }

        public int DeviceModelID { get; set; }

        public virtual DeviceModel DeviceModel { get; set; }

        public ICollection<UnitDevice> UnitDevice { get; set; }

        public ICollection<DeviceTest> DeviceTest { get; set; }
    }

It has a 1 to Many relationship from Device to DeviceModel.  DeviceModel is seeded data and that part seems to be OK, no real issues there.  My issue is when I try to add a Device and call SaveChanges I get an error regarding UnitDevice and DeviceTest, duplicate records.  Both UnitDevice and DeviceTest are Many-Many relationships that have 2 composite P-keys.  Here are their models for more context:

DeviceTest:

    [Table("DeviceTests")]
    public class DeviceTest
    {
        public Guid TestID { get; set; }

        public int DeviceID { get; set; }

        public TestResult Test { get; set; }

        public Device Device { get; set; }
    }

UnitDevice:

    [Table("UnitDevices")]
    public class UnitDevice
    {
        public Guid SessionZoneID { get; set; }

        public int DeviceID { get; set; }

        public ZonesInSession ZonesInSession { get; set; }

        public Device Device { get; set; }
    }

My issue arises when the following code executes:

                foreach(var device in devices)
                {
                    if (_deviceRepository.FindBy(x => x.ID == device.ID).FirstOrDefault() == null)
                    {
                        _deviceRepository.Add(device);
                        _deviceRepository.Save();
                    }
                }

Devices is a in memory List of Device (model can be seen at the top).  In some cases it will throw an error on the save.  One particular example I will provide has the following data in device:

DeviceModel = null
DeviceModelID = 5
DeviceTest = null
ID = 0
SerialNumber = "GIZ0011"
UnitDevice = null

Once this device goes through the .Add(device) the ID is changed to:

ID = -5

The rest of the attributes stay the same, the ID isn't really a concern as I imagine that is just the way EF is 'Adding' and it resolves to the correct ID once it's been saved.  As you can see I am not referencing any UnitDevice objects or DeviceTest objects, they are both null.  Now I am confused as to why when calling SaveChanges on this particular device it throws the following error:

```
Violation of PRIMARY KEY constraint 'PK_DeviceTest'. Cannot insert duplicate key in object 'dbo.DeviceTests'. The duplicate key value is (69, 480006d2-fc98-4b9f-a561-e84e37ee3df3).
Violation of PRIMARY KEY constraint 'PK_UnitDevice'. Cannot insert duplicate key in object 'dbo.UnitDevices'. The duplicate key value is (f3a0811b-926b-4d8d-8adf-7c3b2c9b3071, 67).
The statement has been terminated.
The statement has been terminated.
```

I am not adding either of those records to either table and have no idea where these values are even coming from.  The Device with SerialNumber "GIZ0011" does NOT exist in the Devices table, and all I want to do is Insert it there, but it seems there is something preventing that and I'm not sure if it's my fault or a EF 7 bug. 

Please help as I'm losing my mind here.  Thanks all!

**Comment by ElvisHalil** [comment]
Just some more context from the Database itself, the Device Table at the time of posting this looks like this:

```
ID	DeviceModelID	SerialNumber
61	          1	        21
62	          7	        G2H003
63	          9	        0000
64	         10	        0000
65	         14	        TJ003780
67	          2	        21
68	          5	        GIZ0008
69	          6	        GSCS034
70	         14	        TJ002624
```

**Comment by ElvisHalil** [comment]
Please note that the errors are pointing to 2 different devices, not the device I'm trying to Save... No Idea what the issue is here but I'm having a hard time figuring it out myself.  Any help would be greatly appreciated.

**Comment by ElvisHalil** [comment]
Another thing I'd like to mention here is that if I run through the same data set another time, the device does get saved but nothing at all changes... Confusing, not sure if EF 7 bug, or me.

**Comment by ElvisHalil** [comment]
Hi, thanks for assigning this.  Just want to add some more details I've discovered.  The error is pointing to the previous set of data that was added successfully.  My application iterates through data files and processed them then adds them to the DB.  In this case the DBset for the device repository had items in it from the previous set of data that was processed.  My app will add the device(s) and after that add the UnitDevice.  Once that UnitDevice is added and saved into the db with the unitdevicerepository, the devicerepository DBset items are updated with the new UnitDevice link.  This seems to be the issue, as when I move to the next set of data the errors show up because of that and point to the previous IDs that have already been processed.  

Is there a way to clear the DBset?  Any input would help me at this point.  Thanks.

**Comment by ElvisHalil** [comment]
I have discovered the problem and it is with change tracking.  

The next block of code that executes is this:

```
foreach (var unitDevice in unitDevices)
                {
                    if (_unitDeviceRepository.FindBy(x => x.SessionZoneID == unitDevice.SessionZoneID && x.DeviceID == unitDevice.DeviceID || x.Device.ID == unitDevice.Device.ID).FirstOrDefault() == null)
                    {
                        _unitDeviceRepository.Add(unitDevice);
                        _unitDeviceRepository.Save();
                    }
                }
```

UnitDevice here in memory is similar to device where I don't link objects together, rather I link the ID's.  A exception here is if the Device isn't yet in the DB and since it's auto incremented int it needs to be added before I get an ID.  In this case UnitDevice has a relation in memory to the Device object that was added just before this next block of code executes.  Once the UnitDevices are added to the DB, the devices are updated in the background and EF tracks these changes.  Next time around (on the next set of data) when it hits the devicerepository and tries to save changes it is actually trying to add to the UnitDevice table (also into the DeviceTest table) as the previous device objects have changed.  

This may be expected behavior and I am just not used to it.  Because of the way I'm doing this I have decided to turn off change tracking for now.  That has resolved my issue.

My Context class is called TempDBContext and I have added a constructor with the following setting:
```
        public TempDBContext()
        {
            this.ChangeTracker.AutoDetectChangesEnabled = false;
        }

```

**Comment by ajcvickers** [comment]
@ElvisHalil I'm not sure exactly what is going on, but it sounds like you are creating a single context instance and using it over and over. It is usually much better to create a short-lived context instance just for a single unit-of-work. From what you have said, it seems like each call to SaveChanges probably defines a unit-of-work in your case, and so the context should be disposed and thrown away after that--however, I'm making assumptions here without knowing exactly what you need to do. The reason that there are no methods to clear entities out of a context (or DbSet) is that any time you would need to do this it indicates that instead you should dispose your context.

**Comment by ElvisHalil** [comment]
@ajcvickers You are correct!  I was iterating through files within that class where all my units of work are being initialized in the constructor.  I have now moved the iteration piece outside of the class and am disposing my repositories in the constructor (if not null) and re-initializing them.  This now works with track changes turned on.  

Thank you!

**Comment by ElvisHalil** [comment]
@ajcvickers You pointed me to the right direction.  It turns out I was using the wrong lifestyle for my DI containers.  They were set to singleton which completely makes sense with my issue.  I have now configured it properly to scoped and there is no longer errors from DB tracking referencing old data.  

Thank you!
