### ISSUE TITLE
Consider moving SqlDataReaderExtension and SqlServerTableSelectionSetExtensions to internal namespace

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#5135]
Relative to other types in `Microsoft.EntityFrameworkCore.SqlServer.Design` they seem to be more implementation detail than public surface that we want to expose to anyone.

**Comment by lajones** [comment]
Discussed this in a team meeting today and decided to put all the classes in the `M.EFCore.SqlServer.Design` assembly into `.Internal` namespaces to indicate that, although other provider-writers can take dependencies on some of those classes, we still feel free to make breaking changes to them. Same for the `M.EFCore.Sqlite.Design` assembly.

**Comment by lajones** [comment]
Fixed as discussed above with PR #5209.
