### ISSUE TITLE
Migrations PowerShell commands can't work for both EF6 and EF Core projects that are part of the same solution

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#5145]
The PowerShell versions of the migrations commands are global to the solution and have the same names in EF6 and EF Core but their implementations are version specific. Only one version of them can be active per solution. This can be very inconvenient while incrementally migrating existing projects to EF Core if at any point projects targeting different versions of EF are part of the same solution.

Possible workarounds customers could use are:
- Uninstall and reinstall the EF packages as needed
- Split the solution (more permanent)

In a quick brainstorming we came up with a few ideas (we haven't validated feasibility):
- Release commands that are compatible with both EF6 and EF Core
- Provide an easy way to unload or swap the active PS module

**Comment by bricelam** [comment]
If we change the PowerShell module name (and GUID), you could workaround this by fully-qualifying the commands.

E.g.

    EntityFramework\Update-Database
    EntityFrameworkCore\Update-Database

**Comment by natemcmaster** [comment]
I like that idea, but what happens if user executes "Update-Database" w/o the full-qualified name? Which module wins?

**Comment by bricelam** [comment]
I believe PMC will ask prompt you for which one

**Comment by rowanmiller** [comment]
And that would only happen if there is a conflict (i.e. both modules installed)?

**Comment by natemcmaster** [comment]
I just tried this. If two modules define a function with the same name, PowerShell invokes the one from the most recently imported module. :-/

**Comment by divega** [comment]
Would it be possible to detect the situation in which there is a chance you are using the wrong version of the scripts and show a helpful error telling the you to qualify it?

**Comment by natemcmaster** [comment]
We should rename the EF core PS module, but something more advanced, such as detection which version of EF the project is using and invoking the right version of the command is going to be tricky. I can't think of a clean solution that works for all cases.

**Comment by bricelam** [comment]
Personally, I think as long as people aren't blocked it's good enough. If they try to use the wrong commands, they'll just get "No context found" errors. Maybe we can add something to that message about EF Core.

**Comment by rowanmiller** [comment]
> Personally, I think as long as people aren't blocked it's good enough.

👍 folks know they are trying to use two versions of EF in the same project and I think some guidance on how to do this is fine.

**Comment by divega** [comment]
Had a chat with @natemcmaster and I am reopening just to check what errors you get after the change if you apply the EF Core commands to a project using EF6, and to evaluate adding some text to those errors that can help you disambiguate.

Also created https://entityframework.codeplex.com/workitem/2927 to do this on the EF6 side.
