### ISSUE TITLE
RevEng : Use unbounded navigations in scaffolded model

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#5154]
Since updated navigation are supported in design time model now, RevEng should use them to have navigations in scaffolded model.

**Comment by divega** [comment]
A bit off-topic, but any thoughts on whether we should actually commit to the term "shadow navigation" in our ubiquitous language? 

In my mind things are shadow only if at runtime their original and current values are tracked in shadow state, e.g. shadow entities don't currently exist but they may exist in the future. However these navigation properties don't have their own state so to me they are just metadata-only navigation properties or unbound navigation properties.

I am ok with embracing the term even if it doesn't feel completely accurate :smile:

**Comment by smitpatel** [comment]
Updated title & issue. I did not think in that detail about the term "shadow" but not using it for navigations seems more reasonable.

**Comment by divega** [comment]
@smitpatel I wasn't really pushing back. I would just like to hear what people in the team think we should call them.

**Comment by ajcvickers** [comment]
@divega No reason why they couldn't have state in the future. Would be relatively easy to implement, although I'm not sure that the value would be high.

I haven't looked at the code yet, but presumably they can already or will at some point be useable in query to do things like Include.

**Comment by lajones** [comment]
Note: see #5146 for the fix that allowed navigation properties to point to entities which do not yet have a backing CLR type (which is what we have when constructing the `IModel` during RevEng).

**Comment by lajones** [comment]
Fix checked in with 767b3dd.
