### ISSUE TITLE
Need external dependencies to support .NET Standard in order to remove the requirement for imports in project.json 

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#5176]
Two of EF Core's dependencies, Remotion.Linq and Ix-Async currently use pre-existing portable targets to support multiple platforms. Until these packages add support for .NET Standard, libraries or applications using EF Core will need to specify additional import attributes in project.json. 

```
    Package Ix-Async 1.2.5 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). 
    Package Ix-Async 1.2.5 supports:
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
    Package Remotion.Linq 2.0.2 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). 
    Package Remotion.Linq 2.0.2 supports:
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
```

These two issues track the necessary changes in our dependencies:

Reactive-Extensions/Rx.NET#174
https://www.re-motion.org/jira/browse/RMLNQ-98

Cc: @natemcmaster @rowanmiller

**Comment by stannynuytkens** [comment]
Hi what is the supposed workaround?

**Comment by natemcmaster** [comment]
Use "imports" in project.json.
```json
"frameworks": {
    "netcoreapp1.0": {
       "imports": "portable-net451+win8"
    }
}
```

**Comment by stannynuytkens** [comment]
Hi, still getting EntityFramework.Core 7.0.0-rc1-final is not compatible with .NETPlatform,Version=v5.0.

**Comment by davidfowl** [comment]
@stannynuytkens can you provide more details? That looks you have a bad `project.json`

**Comment by stannynuytkens** [comment]
{
  "supports": {
    "net46.app": {},
    "dnxcore50.app": {}
  },
  "dependencies": {
    "Microsoft.NETCore": "5.0.0",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.0"
  },
  "frameworks": {
    "dotnet": {
      "imports": "portable-net451+win8"
    }
  }
}

**Comment by stannynuytkens** [comment]
Just trying to add EntityFramework.Core to a 4.6.1 Portable class library for use in a .net core app.

**Comment by stannynuytkens** [comment]
Full output:

Restoring packages for 'BitBite.Data'.
Restoring packages for C:\Users\nuytk\Documents\Visual Studio 2015\Projects\BitBite\BitBite.Data\project.json...
Detected package downgrade: System.Reflection from 4.1.0-beta-23225 to 4.0.10 
 BitBite.Data (>= 1.0.0) -> EntityFramework.Core (>= 7.0.0-rc1-final) -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 1.0.0-rc1-final) -> System.Reflection (>= 4.1.0-beta-23225) 
 BitBite.Data (>= 1.0.0) -> EntityFramework.Core (>= 7.0.0-rc1-final) -> System.Reflection (>= 4.0.10)
Detected package downgrade: System.Reflection from 4.1.0-beta-23225 to 4.0.10 
 BitBite.Data (>= 1.0.0) -> EntityFramework.Core (>= 7.0.0-rc1-final) -> Microsoft.Extensions.Logging.Abstractions (>= 1.0.0-rc1-final) -> System.Reflection (>= 4.1.0-beta-23225) 
 BitBite.Data (>= 1.0.0) -> EntityFramework.Core (>= 7.0.0-rc1-final) -> System.Reflection (>= 4.0.10)
Version conflict detected for System.Collections. 
 BitBite.Data (>= 1.0.0) -> EntityFramework.Core (>= 7.0.0-rc1-final) -> System.Collections (>= 4.0.11-beta-23516) 
 BitBite.Data (>= 1.0.0) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-x86 (>= 1.0.0) -> System.Collections (= 4.0.10).
EntityFramework.Core 7.0.0-rc1-final is not compatible with .NETPlatform,Version=v5.0.
Some packages are not compatible with .NETPlatform,Version=v5.0.
Ix-Async 1.2.5 is not compatible with DNXCore,Version=v5.0.
Remotion.Linq 2.0.1 is not compatible with DNXCore,Version=v5.0.
Some packages are not compatible with DNXCore,Version=v5.0.
Ix-Async 1.2.5 is not compatible with DNXCore,Version=v5.0 (win7-x86).
Remotion.Linq 2.0.1 is not compatible with DNXCore,Version=v5.0 (win7-x86).
Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86).
Ix-Async 1.2.5 is not compatible with DNXCore,Version=v5.0 (win7-x64).
Remotion.Linq 2.0.1 is not compatible with DNXCore,Version=v5.0 (win7-x64).
Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64).
Package restore failed for 'BitBite.Data'.
Package restore failed. Rolling back package changes for 'BitBite.Data'.
========== Finished ==========

**Comment by davidfowl** [comment]
Yea, the `project.json` isn't right. You can't use the `dotnet` TFM (it's pretty much deprecated at this point). What are you trying to do? Write a portable class library that uses EF Core?

**Comment by stannynuytkens** [comment]
Hi David, yeah that's about exactly what I'm trying to do. =)

**Comment by davidfowl** [comment]
First thing you need to do is install update 2 and change the portable class library to a .NET Standard class library by right clicking and using the project properties. Also make sure you have the latest version of the NuGet client

**Comment by stannynuytkens** [comment]
Thank you David, will do.

**Comment by natemcmaster** [comment]
@stannynuytkens this conversation has deviated from the original issue. Can you open a new issue on http://github.com/aspnet/home?

**Comment by onovotny** [comment]
We have an unofficial build of Ix-Async here that has netstandard support. Work is in progress to make it official.

https://github.com/Reactive-Extensions/Rx.NET/issues/148#issuecomment-219506305

**Comment by natemcmaster** [comment]
@onovotny good news. 

> Work is in progress to make it official.

I assume this is why the assemblies aren't strong-named yet?

**Comment by onovotny** [comment]
Bingo. We could do an OSS sign but the Rx.NET repo only has the public keys checked in. There are two things we need -- the full SNK and Authenicode. The Authenticode signing will be moving to the .NET Foundation, not sure how this affects the strong name, or are those separate?

**Comment by natemcmaster** [comment]
@onovotny IIUC strong name and authenticode are separate. e.g. EF nightly builds on myget.org/gallery/aspnetcidev have been built with strong-named signing but haven't been code-signed yet.

Side note: I'm testing the builds on http://myget.org/gallery/rxnet. Where should I file issues? Do you have a fork?

**Comment by natemcmaster** [comment]
Merged #5689, which means using EF Core 1.0 won't require "imports" in .NET Core apps.

Thanks to @MichaelKetting @shiftkey @onovotny @bartdesmet for their work to update Ix-Async and Re-linq to support .NET Standard.

**Comment by onovotny** [comment]
Quick question -- where are you currently pulling the Ix bits from? FWIW, the latest version on the myget feed is OSS signed with the SNK and has the granular dependencies applied.

**Comment by natemcmaster** [comment]
@onovotny we mirrored System.Interactive.Async to our CI build feeds for now. http://myget.org/feed/aspnetcidev/package/nuget/System.Interactive.Async. When the updated version lands on NuGet.org, we will use that instead.

**Comment by wpostma** [comment]
So this is closed, but a project.json containing only  dnxcore are still not compatible with EntityFrameworkCore.MicrosoftSqlServer?  I still need this workaround:

```
"frameworks": {    "netstandard1.6": {
      "imports": [ "dnxcore50", "portable-net451+win8" ]
    }
```

When will this workaround go away?

**Comment by divega** [comment]
`EntityFrameworkCore.MicrosoftSqlServer` is an old package from when this issue existed. If you are using 1.0.0 RTM you should use `Microsoft.EntityFrameworkCore.SqlServer` instead.

**Comment by wpostma** [comment]
What's odd then is that the VS IDE still picks up and suggests adding "EntityFrameworkCore.MicrosoftSqlServer" to my project.json when it can't find references to things like DbContext.

**Comment by divega** [comment]
@wpostma I am not sure how the suggestion mechanism work internally but I ran an experiment in my machine and it seems to remember packages that you have used in previous VS sessions. So I think this may be a good time to remove pre-RTM packages from other projects, local NuGet cache, etc.
