### ISSUE TITLE
SerializationException during test runs on CI machines

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#5184]
Tests on CI occasionally fail with this error message. The error goes away on repeated test runs.

> System.Runtime.Serialization.SerializationException : Type 'Microsoft.EntityFrameworkCore.Specification.Tests.TestSqlLoggerFactory+SqlLoggerData' in assembly 'Microsoft.EntityFrameworkCore.Relational.Specification.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' is not marked as serializable.

**Comment by rowanmiller** [comment]
We should make this test class serializable as we suspect there is an underlying error causing this condition.
