### ISSUE TITLE
CLI Commands: usability improvements

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#5188]
Some ideas for improving the usability of dotnet ef.

- [ ] `dotnet ef database update` doesn't list the migrations being applied/reverted
- [ ] Don't require building to get output of `--help`. We can show help dialog without dispatching to inside-man.
- [x] Support `--json` on all subcommands
- [ ] Allow top-level arguments in any order. E.g. currently `dotnet ef dbcontext list --no-build` throws, but `dotnet ef --no-build dbcontext list` works. ~~Part of this is just the way that [Microsoft.Extensions.CommandLineUtils](https://github.com/aspnet/Common/tree/dev/src/Microsoft.Extensions.CommandLineUtils) works.~~ https://github.com/aspnet/Common/pull/131. We still can't completely do this with the way we invoke ef.exe from dotnet-ef.dll.
- [x] ~~Depending on the outcome of https://github.com/dotnet/cli/issues/2514, we may be able to remove "inside-man" dispatch for RTM.~~ NVM. We've pivoted away from ProjectDependencyCommandFactory to our own thing.
- [x] ~~Depending on the resolution to https://github.com/dotnet/cli/issues/2645, we may need to change Ms.EfCore.Tools to also target class libraries. (Support this by cross-compiling the library to netstandard1.5)~~ tracked here: https://github.com/aspnet/EntityFramework/issues/5320
- [x] ~~Help dialog should show options top-level args (`--framework`) even when listing args for subcommands.~~ Fixed in CommandLineUtils.

**Comment by natemcmaster** [comment]
We should do this but it can be post RTM.

**Comment by VanKichline** [comment]
Note that new preview 2 web application templates use 'dotnet bundle' command, so asking for 'dotnet help ef' runs the bundler/minifier and may modify the contents of the project.

**Comment by natemcmaster** [comment]
@VanKichline you can workaround with the `--no-build` parameter. e.g.:
```sh
dotnet ef --no-build --help
dotnet ef --no-build migrations list 
# etc...
```

**Comment by bricelam** [comment]
Closing. Filed remaining work as #6592 and #6593.
