### ISSUE TITLE
Guidance on applying migrations during KUDU deploy

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#5207]
We've had a few folks ask about this. It should be possible with CLI commands, but folks have reported errors trying to do so. We should get it working and then document how to do it.

**Comment by justinyoo** [comment]
I've left an issue on KUDU as well - not sure it's EF issue or KUDU issue:

https://github.com/projectkudu/kudu/issues/1977

**Comment by justinyoo** [comment]
@rowanmiller  If I can make a spare time today, I'll deploy a test web app and let you know.

**Comment by rowanmiller** [comment]
@justinyoo sounds good, I appreciate you spending your time to help on this

**Comment by justinyoo** [comment]
@rowanmiller Hmmm... I deployed a new test ASP.NET Core web app into new Azure Web App and run DB migration directly on KUDU. This time I couldn't reproduce the issue. I should deploy my **real** app to see the error. I'll get back to you next week.

**Comment by rowanmiller** [comment]
Moved over to docs repo since this is primarily about writing guidance around how to do this - https://github.com/aspnet/EntityFramework.Docs/issues/180. Doing so may spawn product issues/improvements back in this repo.
