### ISSUE TITLE
Test fixture base class uses SqlServer-specific code

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#5216]
InheritanceRelationalFixture sets ColumnType to nvarchar, which is SqlServer-specific and should happen in a provider-independent project.

https://github.com/aspnet/EntityFramework/blob/fb465491355f09f7f0fafdd2013043acb670d87e/src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/InheritanceRelationalFixture.cs#L22

**Comment by rowanmiller** [comment]
@roji feel free to send a PR with some refactoring to allow this to be done in the provider tests

**Comment by roji** [comment]
OK @rowanmiller, will do

**Comment by roji** [comment]
@AndriySvyryd I've tried to get around the specification of nvarchar by replacing `.HasColumnType("nvarchar(100)")` with `.HasMaxLength(100);` in InheritanceRelationalFixture, and oddly this generates the error "Column 'Animal.Species' is not the same length or scale as referencing column 'Animal.EagleId' in foreign key 'FK_Animal_Animal_EagleId'. Columns participating in a foreign key relationship must be defined with the same length and scale.". The same error happens if I don't configure the properties at all.

I know #2455 is still open and am not sure about things here, but it seems problematic to have to specify the full column type here, any input?

**Comment by smitpatel** [comment]
@roji - 🐛 filed #5379
The same error happens for no configuration since, one of them is PK and its length will be limited for it and then it becomes same issue as the former.
You can override `OnModelCreating` method in derived classes like `InheritanceSqlServerFixture` and set provider-specific types there.

**Comment by roji** [comment]
Thanks!
