### ISSUE TITLE
CLI : dotnet ef or dotnet Microsoft.EntityFrameworkCore.Tools.Cli

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#5227]
dotnet ef command output contains following
Entity Framework .NET Core CLI Commands 1.0.0-rc3-20747
Usage: **Microsoft.EntityFrameworkCore.Tools.Cli** [options] [command]
Should it be "ef" instead?

**Comment by smitpatel** [comment]
I guess yes. 😞 
````
PM> dotnet Microsoft.EntityFrameworkCore.Tools.Cli
[1m[31mNo executable found matching command "dotnet-Microsoft.EntityFrameworkCore.Tools.Cli"[39m[22m
````

**Comment by natemcmaster** [comment]
We should update the help text to say "dotnet ef". The command is `dotnet ef`. Microsoft.EntityFrameworkCore.Tools.Cli is an internal implementation detail.
