### ISSUE TITLE
missing "using System;" in context class

### ISSUE THREAD

**Issue by tdjastrzebski** [aspnet/EntityFramework#5238]
version: 1.0.0-rc1-final

SQL Server DB has a table with uniqueidentifier (Guid) column which has a default value "00000000-0000-0000-0000-000000000000".

Proper Fluent API gets generated:
`entity.Property(e => e.PrintFormatListId).HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));`
but lack of "using System;" in the file header causes compiler error CS0246: The type or namespace name 'Guid' could not be found,

**Comment by lajones** [comment]
Fxied with commit 4e27d5a.
