### ISSUE TITLE
Specified cast is not valid in Microsoft.EntityFrameworkCore.Relational

### ISSUE THREAD

**Issue by gmartinezsan** [aspnet/EntityFramework#5250]
Is this a real bug or something I'm missing?. I'm getting this exception:

```
failed: System.InvalidCastException : Specified cast is not valid.
	at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
	at lambda_method(Closure , QueryContext )
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at System.Linq.Queryable.Any[TSource](IQueryable`1 source)
	FunctionalTests.cs(53,0): at MySql.Data.Entity.Tests.FunctionalTests.CanConnectWithConnectionOnConfiguring()
```

This same test was working with RC1.

DbContext class definition

```c#
   private class UseConnectionInOnConfiguring : TestsContext
    {
      private MySqlConnection _connection;

      public UseConnectionInOnConfiguring(MySqlConnection connection)
      {
        _connection = connection;
      }      

      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
        optionsBuilder.UseMySQL(_connection);
      }

      public override void Dispose()
      {
        _connection.Dispose();
        base.Dispose();
      }
    }
```

Thanks in advance!

**Comment by anpete** [comment]
@gmartinezsan Can you please share the code for the test, along with the log produced (LogLevel.Debug) when running the query?

**Comment by anpete** [comment]
@gmartinezsan GetResult is attempting to cast the value in the ValueBuffer to a bool. This is failing so it is likely that the underlying value in the buffer is not a bool.

**Comment by gmartinezsan** [comment]
Yeah, I checked and the value is a "0". Is this a bug then ?

**Comment by gmartinezsan** [comment]
[log.txt](https://github.com/aspnet/EntityFramework/files/247594/log.txt)

Here is the code of the unit test:

  public void CanConnectWithConnectionOnConfiguring()
    {
      var serviceCollection = new ServiceCollection();
      serviceCollection.AddEntityFrameworkMySQL()
        .AddDbContext<ConnectionStringInOnConfiguringTestContext>();

     var serviceProvider = serviceCollection.BuildServiceProvider();  

      using (var context = serviceProvider.GetRequiredService<ConnectionStringInOnConfiguringTestContext>())
      {
        context.Database.EnsureCreated();
        Assert.True(context.Posts.Any());
        context.Database.EnsureDeleted();
      }
    }

I attached the log file. 
The details exception is at the bottom of the file.

Thanks in advance.

**Comment by anpete** [comment]
@gmartinezsan Do you have an implementation of RelationalDatabaseProviderServices in the MySql provider? If so, can you share it?

**Comment by gmartinezsan** [comment]
Sure.. here it is

public class MySQLDatabaseProviderServices : RelationalDatabaseProviderServices
  {
    public MySQLDatabaseProviderServices(IServiceProvider serviceProvider) : base(serviceProvider)
    {
    }

    public override string InvariantName
    {
      get { return GetType().GetTypeInfo().Assembly.GetName().Name; }
    }

    public override IDatabaseCreator Creator
    {
      get {
        return GetService<MySQLDatabaseCreator>(); }
    }

    public override IRelationalConnection RelationalConnection
    {
      get { return GetService<MySQLServerConnection>(); }
    }

    public override ISqlGenerationHelper SqlGenerationHelper
    {
      get { return GetService<MySQLSqlGenerationHelper>(); }
    }

    public override IRelationalDatabaseCreator RelationalDatabaseCreator
    {
      get { return GetService<RelationalDatabaseCreator>(); }
    }

    public override IRelationalAnnotationProvider AnnotationProvider
    {
      get { return GetService<MySQLAnnotationProvider>();  }
    }

    public override IMigrationsAnnotationProvider MigrationsAnnotationProvider
    {
      get { return GetService<MySQLMigrationsAnnotationProvider>();  }
    }

    public override IHistoryRepository HistoryRepository
    {
      get { return GetService<MySQLHistoryRepository>(); }
    }

    public override IMigrationsSqlGenerator MigrationsSqlGenerator
    {
      get { return GetService<MySQLMigrationsSqlGenerator>(); }
    }

    public override IUpdateSqlGenerator UpdateSqlGenerator
    {
      get { return GetService<MySQLUpdateSqlGenerator>(); }
    }


    public override IValueGeneratorCache ValueGeneratorCache
    {
      get { return GetService<MySQLValueGeneratorCache>(); }
    }

    public override IModelSource ModelSource => GetService<MySQLModelSource>();

    public override IQueryContextFactory QueryContextFactory => GetService<RelationalQueryContextFactory>();

    public override IRelationalTypeMapper TypeMapper
    {
      get { return GetService<MySQLTypeMapper>(); }
    }

    public override IModificationCommandBatchFactory ModificationCommandBatchFactory
    {
      get { return GetService<MySQLModificationCommandBatchFactory>(); }
    }


    public override IMethodCallTranslator CompositeMethodCallTranslator
    {
      get { return GetService<MySQLCompositeMethodCallTranslator>(); }
    }

    public override IMemberTranslator CompositeMemberTranslator
    {
      get { return GetService<MySQLCompositeMemberTranslator>(); }
    }

    public override IRelationalValueBufferFactoryFactory ValueBufferFactoryFactory
    {
      get { return GetService<UntypedRelationalValueBufferFactoryFactory>(); }
    }

    public override IQuerySqlGeneratorFactory QuerySqlGeneratorFactory
    {
      get { return GetService<MySQLQueryGeneratorFactory>(); }
    }
  }

**Comment by anpete** [comment]
@gmartinezsan Thanks. Can you try removing the override of ValueBufferFactoryFactory?

**Comment by gmartinezsan** [comment]
Done it. Now the exception is on MS.EntityFramework.Core

System.FormatException occurred
  HResult=-2146233033
  Message=String was not recognized as a valid Boolean.
  Source=mscorlib
  StackTrace:
       at System.Boolean.Parse(String value)
       at System.String.System.IConvertible.ToBoolean(IFormatProvider provider)
       at System.Convert.ToBoolean(Object value)
       at MySql.Data.MySqlClient.MySqlDataReader.GetBoolean(Int32 i) in D:\Repository\GIT\cnet\6.10\6.10_EF_Core - RC2\Source\MySql.Data\datareader.cs:line 276
       at lambda_method(Closure , DbDataReader )
       at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
       at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
       at lambda_method(Closure , QueryContext )
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
       at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
       at System.Linq.Queryable.Any[TSource](IQueryable`1 source)
       at MySql.Data.Entity.Tests.FunctionalTests.CanConnectWithConnectionOnConfiguring() in D:\Repository\GIT\cnet\6.10\6.10_EF_Core - RC2\Tests\MySql.EntityFramework7.Basic.Tests\FunctionalTests.cs:line 71
  InnerException:

**Comment by ErikEJ** [comment]
It looks like the erroris in MySql.. MySql.Data.MySqlClient.MySqlDataReader.GetBoolean

**Comment by gmartinezsan** [comment]
Looks like it is.. thanks ErikEJ!

**Comment by PrashanthIBM** [comment]
@gmartinezsan  : Was the issue resolved on this layer MySql.Data.MySqlClient ?
