### ISSUE TITLE
Migrations: Incorrect discriminator value generated if a derived class is referenced from an entity

### ISSUE THREAD

**Issue by rmja** [aspnet/EntityFramework#5258]
Consider the following example:
```
    public abstract class Vehicle
    {
        public int Id { get; set; }
    }

    public class Car : Vehicle
    {
        public int CarparkId { get; set; }
    }

    public class Carpark
    {
        public int Id { get; set; }
        public ICollection<Car> Cars { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Vehicle> Vehicles { get; set; }
        public DbSet<Carpark> Carparks { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=localhost;Database=MyDatabase;Trusted_Connection=True;MultipleActiveResultSets=true");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Vehicle>().HasDiscriminator<int>("Discriminator")
                .HasValue<Car>(1);
        }
    }
```

The `Carpark` references the derived type `Car`. This causes the following model snapshot to be generated:

```
modelBuilder.Entity("CustomAnnotationsRepro.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Discriminator");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator<int>("Discriminator").HasValue("Vehicle");
                });
```
The `.HasValue("Vehicle")` should not be included and the code cannot compilse as `"Vehicle"` cannot be converted to int.

Latest rc2 bits

**Comment by rmja** [comment]
The problems seems to be [on this line](https://github.com/aspnet/EntityFramework/blob/5fce4e24440fde8936d1c3806f0d8b0080da42a4/src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalEntityTypeBuilderAnnotations.cs#L94)

`DiscriminatorProperty.ClrType == discriminatorType` Evaluates to false, as `typeof(int) != typeof(Vehicle)`, and so the discriminator value annotation is set to the name of the property. What is the reasoning behind this?

**Comment by rmja** [comment]
I guess the fallback to use the name of the type as discriminator value should only be used if the type of the discriminator is string and the clr type is not abstract?

**Comment by rowanmiller** [comment]
Workaround for the moment is probably to set an `int` value (even thought its not needed) for `Vehicle`
