### ISSUE TITLE
Take Working Incorrectly When Used WIth OrderByDescending

### ISSUE THREAD

**Issue by StrangeWill** [aspnet/EntityFramework#5262]
Given the following query:

    this.Context.Media
      .OrderByDescending(m => m.Created)
      .Skip(0)
      .Take(60)
      .Include(m => m.Files);
  
I'm getting 3 files for one piece of media, and 0 for another. There should be 3 for each (there are only two pieces of media).

However if I do this:

    this.Context.Media
      .OrderBy(m => m.Created)
      .Skip(0)
      .Take(60)
      .Include(m => m.Files);
    
Works fine (aside from the files being in the wrong order). Generated SQL looks fine, it matches in both ways aside from "DESC" being removed when doing "OrderBy".

Additionally applying "OrderByDescending" *after* Skip/Take appears to fix the issue, not sure if this is intentional.

**Comment by anpete** [comment]
@StrangeWill Which version of EF Core are you running?

**Comment by StrangeWill** [comment]
@anpete Terribly sorry about that... that's an obvious should-be-here thing.

EntityFramework.Core 7.0.0-rc1-final

**Comment by anpete** [comment]
Confirming this is fixed in RC2.
