### ISSUE TITLE
Consider removing IX-async dependency

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#5266]
We currently are getting value from IX-async in two ways:

- Shared `IAsyncEnumerable<T>` interfaces
- In-memory implementation of async LINQ operators

A few new data points may affect the initial decision on taking this dependency:

- The .NET languages team is working on standard version the interfaces and language support for them (see https://github.com/ljw1004/roslyn/blob/features/async-return/docs/specs/feature%20-%20async%20iterators.md). We definitely will want to swap to that when it is ready 
- We have found performance issues in the LINQ operator implementation of IX-async which we solved by implementing our own version of some of the operators

The proposal is to define our own interface in an internal namespace, so that we can swap to the standard interfaces and implementations when they are available but in the meanwhile enable developers that are ok with opting in to possible breaking changes to code against our interfaces.

If there is enough demand for it, we can always create a bridge to IX-async.

The cost of removing the dependency would be mostly the cost of finishing the implementation of all LINQ operators.

**Comment by anpete** [comment]
@divega I remember now that we discussed the quick option, too - Copy the relevant IX code into EF (internal) so that we can do the migration piecemeal.

**Comment by divega** [comment]
If the main goal was to avoid committing to the `IAsyncEnumerable<T>` interface in IX-async while we wait for the BCL version, another option would be to make the dependency purely internal, e.g. making sure all the ways you can access the underlying `IAsyncEnumerable<T>` from a query are internal: `AsAsyncEnumerable()` and `IAsyncEnumerableAccessor<T>` should be defined in internal namespaces and ideally we wouldn't implement `IAsyncEnumerable<T>` directly in our public types.

This of course does not help with relieving the weight of having the dependency.

**Comment by rowanmiller** [comment]
We'll remove IX-Async from public surface and then handle this post RTM

**Comment by anpete** [comment]
@divega @rowanmiller I noticed a few other non-internal APIs where the interface shows up. They are all provider APIs, so it seems OK.

**Comment by divega** [comment]
I guess will have to live with that for now. I don't know how we could get away with not having a representation for async collections at this level.

**Comment by rowanmiller** [comment]
Agreed, we can be sensible about when we actually remove the dependency and coordinate with providers.
