### ISSUE TITLE
Empty GUID is overriden with a new GUID

### ISSUE THREAD

**Issue by chris02031** [aspnet/EntityFramework#5269]
When trying to insert GUID.Empty as a value explicitly the EF framework seems to replace this with a new random GUID.

In the query parameters list it appears as a '?'.

EDIT: The column IS a key, but it is not database generated / seed.

**Comment by ajcvickers** [comment]
@chris02031 Can you please post your entity classes and any code you have in OnModelCreating?

**Comment by chris02031** [comment]
My original post was wrong. The column is in fact a key, but not DB generated.

```
 public class Owner
    {
        [Key]
        public Guid OwnerID { get; set; }

        public string CompanyName { get; set; }
        public string CompanyEmail { get; set; }

        public virtual Currency DefaultCurrency { get; set; }

        [ForeignKey("DefaultCurrency")]
        public int? DefaultCurrencyID { get; set; }

        public virtual IList<TradeUser> Users { get; set; }
        public virtual IList<ChannelAccount> ChannelAccounts { get; set; }
        public virtual IList<Product> Products { get; set; }
        public virtual IList<Payment> Transactions { get; set; }
        public virtual IList<Purchase> Purchases { get; set; }
        public virtual IList<Sale> Sales { get; set; }
        public virtual IList<Supplier> Suppliers { get; set; }
        public virtual IList<Customer> Customers { get; set; }
        public virtual IList<ListingGroup> Listings { get; set; }
        public virtual IList<ShippingManifest> ShipmentManifests { get; set; }

    }
```

```
protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            var m = builder;

            m.Entity<Payment>(e =>
            {
                e.Property(f => f.LocalTransactionID).HasMaxLength(18);
                e.HasIndex(f => f.LocalTransactionID).HasName("IX_Transaction_LocalID");
            });

            m.Entity<FinanceAccount>(e =>
            {
                e.Property(f => f.RowVersion).ValueGeneratedOnAddOrUpdate().IsConcurrencyToken();
            });

            m.Entity<ProductSuppliers>(e =>
            {
                e.HasKey(f => new { f.ProductID, f.SupplierID });
                e.HasOne(f => f.Product).WithMany(f => f.Suppliers).HasForeignKey(f => f.ProductID);
                e.HasOne(f => f.Supplier).WithMany(f => f.Products).HasForeignKey(f => f.SupplierID);
            });

            m.Entity<Product>(e =>
            {
                e.HasMany(f => f.Components).WithOne(f => f.Product).HasForeignKey(f => f.ProductID);
            });

            m.Entity<ProductComponent>(e =>
            {
                e.HasKey(f => new { f.ProductID, f.ChildID });
                e.HasOne(f => f.Product).WithMany(f => f.Components).HasForeignKey(f => f.ProductID);
                e.HasOne(f => f.Child).WithMany(f => f.PartOf).HasForeignKey(f => f.ChildID);
            });


            foreach (var relationship in m.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }
        }
```

This creates a random GUID as the key where EF6 used the literal empty GUID.

```
var owner = new Owner { OwnerID = Guid.Empty, CompanyEmail = "owner@email.com", CompanyName = "Owner", DefaultCurrencyID = gbp.CurrencyID };
            _DB.Owners.Add(owner);
```

**Comment by ajcvickers** [comment]
@chris02031 EF creates the GUID key as database-generated by convention. This is the same as EF6. However, EF needs to have a key for the entity before it is saved to the database, so if the key given to the entity is Guid.Empty, then EF creates a temporary GUID key for this. This temporary key is replaced by the database-generated key when the entity is saved.

You can set the key value to anything other than Guid.Empty before adding the entity and this key value will then be saved to the database.

I'm going to close this as by-design, but feel free to re-open if necessary.

**Comment by mrcoymeeks** [comment]
Apologize for commenting on a closed issue, but I want to get some clarification around the designed behavior.

I'm currently porting over to EF Core and I have a closure tree representation in the database, with a composite key, parentId, descendantId, and tenantId.  The root of the tree is always Guid.Empty so all nodes are related to Guid.Empty.

When I attempt to insert Guid.Empty into this table as the parentId, I get InvalidOperationException: temporary value.

Am I reading it correctly that it is not possible to insert an empty guid into a PK column in EF?

**Comment by ajcvickers** [comment]
@mrcoymeeks If you need GUIDs to be automatically when inserting new entities, then yes. Otherwise, just disable value generation on the primary key. See discussion here: #13123

**Comment by mrcoymeeks** [comment]
@ajcvickers Thanks for the link!
