### ISSUE TITLE
Wrap 'open DataReader' exception with something that says to enable MARS

### ISSUE THREAD

**Issue by kirthik** [aspnet/EntityFramework#529]
**DECISION:** We will wrap the exception in something that says to use MARS.

If MARS is not enabled in connection string, browser shows the following error. Error message should suggest user to enable MARS to get past the error

`An unhandled exception occurred while processing the request.
InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
Remotion.Linq.Clauses.ResultOperatorBase.InvokeExecuteMethod(MethodInfo method, Object input)
DataStoreException: An error occured while running a data store operation. See InnerException for details.
Microsoft.Data.Entity.Query.EntityQueryExecutor.ExecuteCollection[T](QueryModel queryModel)`

**Comment by sayedihashimi** [comment]
I spoke to @kirthik about this about a week ago regarding if the Visual Studio web publish dialog should do something. Below are my comments.

>Let’s take a step back for a second, in ASP.NET 5 the publish dialog does not currently accept a connection string. When running a website in Azure if you create a site in the publish dialog with a linked DB there is a connection string added to an env var that makes it available to the app at runtime. The result when creating the site+db in VS is the same as when you do that same thing in the portal.
>
>That said at some point VS will have a connection string update feature. The design is TBD but we are currently thinking to write a ```config.override.json``` file that is imported via runtime. When running in Azure websites if we write the file (_which we may not for azure websites, tbd_) that value would be ignored since there is an env var with the exact same name for the linked db. Even if we added MARS=true in ```config.override.json``` it wouldn’t matter because the Azure env var will win.
>
>To summarize; the bug is not currently a bug since we don’t update connection strings and when we do handle connection strings there is nothing we can do for azure websites since the env var for the linked DB will trump anything that VS can do.
>
>If you don’t think it makes sense to enable MARS=true for all of Azure then I would recommend you explore other options. One thing that I can think of is having an appSetting for MARS and having that appSetting to default to true in VS templates.

**Comment by anpete** [comment]
Closing as we no longer require MARS.
