### ISSUE TITLE
dotnet ef database drop does not provide any feed back when y/Y is keyed

### ISSUE THREAD

**Issue by pranavkm** [aspnet/EntityFramework#5316]
It seems like the command is hung when the key is pressed. It would be nice to get some form of response that says it's busy deleting the db.

**Comment by pranavkm** [comment]
Would be also nice to have it ask for "yes" followed `Enter ↵` to prevent accidental key strokes from dropping the db.

**Comment by laskoviymishka** [comment]
@pranavkm Agree with regards to `Enter ↵`, but it better to stay with `Y/n` as this follows common rules for such CLI. 
In a fact it would be really nice to see some fun inside of this confirm.
Like this, but with unicorn (EF logo):
![like this, but with unicorn](https://t.alipayobjects.com/images/T1zJheXmjzXXXXXXXX.png)

**Comment by natemcmaster** [comment]
We can add more logging so its clear the process is not hung, but unfortunately our interaction with the console is heavily limited by `dotnet run`. See https://github.com/dotnet/cli/issues/1985
