### ISSUE TITLE
dotnet ef database drop always ask if it wants to drop the database regardless of the existence of the db

### ISSUE THREAD

**Issue by pranavkm** [aspnet/EntityFramework#5317]
The command always prompts for `Are you sure you want to drop the database ...` without verifying if it exists. Running it twice makes it appear as if it hasn't done any work the first time around.

**Comment by laskoviymishka** [comment]
What behavior is expected?

**Comment by pranavkm** [comment]
It'd be nice if it says it doesn't exist (`Cannot drop TestDatabase. Are you sure it exists?`) or something along these lines.

**Comment by rowanmiller** [comment]
We don't preemptively check if the database exists, but `EnsureDeleted` does return a `bool` letting us know if there was a database to drop or not... so we could log the result.

**Comment by laskoviymishka** [comment]
@rowanmiller It's a good point, can i grab this issue and made PR for this?

**Comment by rowanmiller** [comment]
@laskoviymishka go for it, we moved it out of 1.0.0 purely for scheduling reasons, more than happy to take the change if it looks good. Take a look at [this recent PR](https://github.com/aspnet/EntityFramework/pull/5388) for guidance on how to store strings etc.

**Comment by laskoviymishka** [comment]
@rowanmiller yeah - everything to a resources. Thx!
