### ISSUE TITLE
Modify InvokeDotnetEf in EntityFramework.psm1 to use .Path instead of .Source to discover dotnet location

### ISSUE THREAD

**Issue by pranavkm** [aspnet/EntityFramework#5327]
According to https://msdn.microsoft.com/en-us/library/system.management.automation.applicationinfo_members(v=vs.85).aspx, the `.Source` property on `ApplicationInfo` returned by `Get-Command` was added in Powershell 5.0. `.Path` returns the same value and works in powershell 3.0.

Line of code to change: https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFramework.psm1#L643

**Comment by pranavkm** [comment]
To perform EF migrations in the package manager console until this is fixed, install powershell 5.0.

**Comment by divega** [comment]
@rowanmiller I talked to @natemcmaster and we think we should take a fix for this now.

**Comment by divega** [comment]
FWIW the rationale for taking this now is that:

1. The PMC commands are the tooling option that works for the greatest set of scenarios in RC2
2. I believe the user gets a very unhelpful exception 
3. PowerShell 5.0 requires extra downloads for Windows 7, 8, 8.1 and the corresponding server SKUs.

**Comment by rowanmiller** [comment]
Sounds fine to me... should be a low risk fix

**Comment by natemcmaster** [comment]
To be clear, this only affects users on *.xproj. PMC commands for csproj are unaffected by this.

**Comment by rowanmiller** [comment]
Spoke with @danroth27, this does not meet the bar to reset RC2 builds. Moving to RTM.

**Comment by ErikEJ** [comment]
So Windows 10 or manual changes to the psm1 file will be required in rc2?

**Comment by natemcmaster** [comment]
Or upgrade to Powershell 5. https://www.microsoft.com/en-us/download/details.aspx?id=50395

**Comment by rowanmiller** [comment]
Upgrading PS would be our guidance over modifying the scripts

**Comment by ErikEJ** [comment]
Of course!

**Comment by divega** [comment]
Download link for PowerShell 5.0: https://www.microsoft.com/en-us/download/details.aspx?id=50395
