### ISSUE TITLE
Implement new architecture of dotnet-ef and PowerShell commands for ASP.NET Core/.NET Core

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#5334]
Some things to consider:
 * Do we continue to just shell to dotnet-ef from PowerShell commands? If so, how do we get better output (#4771).
 * Can we use AppDomains for xproj (#4773)

**Comment by rowanmiller** [comment]
Since GitHub doesn't support multiple assignees 😄... assigning to @bricelam to catch up with @natemcmaster and other when he is back in the office to discuss where have landed and where we go from here.

**Comment by natemcmaster** [comment]
Remarking for triage: this can wait until after RTM.

**Comment by natemcmaster** [comment]
Additional things to consider:

- [ ] Can we change the appdomain interfaces now that everything runs through ef.exe? https://github.com/aspnet/EntityFramework/pull/6288#discussion_r74467607
