### ISSUE TITLE
Working on a project with SQL and Visual Studio 2015

### ISSUE THREAD

**Issue by subzero1001** [aspnet/EntityFramework#5354]
Hello guys, I need help!!!
I'm currently working on a project where I have to create an **Application using SQL in Visual Studio 2015 ( UWP) . 
The problem is , that Microsoft hasn't published any guide or tutorials for VS 2015 and SQL, as far as I know. There are some guides for previous Visual Studio but I always get to a point where **something is missing** or not the same .
I manage somehow  to connect the SQL database to my Project ( still don't know if it is the correct way) but my biggest problem  is , that **i can't find any C # code to connect the SQL table** to my application . Even when I find some code , it is not working because some libraries are missing or it is not well explained ( such as System.Data.SqlClient ).
I read that I can use SQLite with Entity Framework , but I'm not sure.I'm been working on this 2 weeks and still haven't find anything !The deadline is in 2 weeks. Please help :/

**Comment by jcob-ross** [comment]
https://ef.readthedocs.io/en/latest/platforms/uwp/getting-started.html

hope it helps
