### ISSUE TITLE
PostgreSQL-specific types ignored in query's where clause

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#5365]
I'm trying to run some BuiltInDataTypes functional tests on PostgreSQL-specific types. These types have been properly mapped in my NpgsqlTypeMapper, and indeed most of the tests pass quite well (it's a real pleasure to see this work).

There's one important issue though, with Can_query_using_any_mapped_data_type which places the types in a where clause. Looking at the generated SQL, I can see that with regular types the where clause is good (`WHERE ("e"."Int" = 999) AND ("e"."Bool" = $1)`). However, PostgreSQL types get dropped completely: ` WHERE "e"."Int" = 999`. Examples of CLR types which cause this are PhysicalAddress, TimeSpan and some others.

Have I messed things up in NpgsqlTypeMapper, or does the EFCore query generator somehow not accept non-standard types yet?

(~~this may be somehow related to #3617~~ probably not actually)

**Comment by divega** [comment]
Indeed that sounds like query doesn't recognize the type and therefore switches to client side evaluation. Not sure what you would need to extend to enable SQL translation. @anpete, @maumar or @smitpatel might be able to help.
