### ISSUE TITLE
The default HistoryRepository implementation does not respect a provider implementation of ISqlGenerationHelper 

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#5368]
Meaning that for example the StatementTerminator is hardcoded with semicolon in the default HistoryRepository implementation...

**Comment by rowanmiller** [comment]
@ErikEJ you should be able to override the `HistoryRepository` for RTM. We agree this should be fixed though, but we're going to have to deal with it post-1.0.0. We would of course take a PR if you wanted to go down that route 😄 .

**Comment by ErikEJ** [comment]
Sure, I will consider a PR when I am able to build again...
