### ISSUE TITLE
RC2 SqlServer fails with simple update on table with RowVersion field

### ISSUE THREAD

**Issue by b-butcher** [aspnet/EntityFramework#5393]
A single-table update fails when updating an existing record that contains RowVersion field.  The issue is that "@inserted1" is re-used as a variable name.

Here is the trace:

SET NOCOUNT ON;
DECLARE @toInsert1 TABLE ([ActionType] nvarchar(6), [Key1Value] nvarchar(100), [Key2Value] nvarchar(100), [Key3Value] nvarchar(100), [TableName] nvarchar(100), [UserId] nvarchar(40), [_Position] [int]);
INSERT INTO @toInsert1
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, 0);

DECLARE @inserted1 TABLE ([Id] bigint, [ActionDate] datetimeoffset, [ActionType] nvarchar(6), [Key1Value] nvarchar(100), [Key2Value] nvarchar(100), [Key3Value] nvarchar(100), [TableName] nvarchar(100), [UserId] nvarchar(40), [_Position] [int]);
MERGE [Audit].[RowChange] USING @toInsert1 AS i ON 1=0
WHEN NOT MATCHED THEN
INSERT ([ActionType], [Key1Value], [Key2Value], [Key3Value], [TableName], [UserId])
VALUES (i.[ActionType], i.[Key1Value], i.[Key2Value], i.[Key3Value], i.[TableName], i.[UserId])
OUTPUT INSERTED.[Id], INSERTED.[ActionDate], INSERTED.[ActionType], INSERTED.[Key1Value], INSERTED.[Key2Value], INSERTED.[Key3Value], INSERTED.[TableName], INSERTED.[UserId], i._Position
INTO @inserted1;

SELECT [Id], [ActionDate] FROM @inserted1
ORDER BY _Position;
DECLARE @inserted1 TABLE ([RowVersion] varbinary(8));
UPDATE [ClientSetup].[Client] SET [Name] = @p7, [Status] = @p9
OUTPUT INSERTED.[RowVersion]
INTO @inserted1
WHERE [Id] = @p6 AND [RowVersion] = @p8;
SELECT [RowVersion] FROM @inserted1;
Microsoft.EntityFrameworkCore.DbContext:Error: An exception occurred in the database while saving changes.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The variable name '@inserted1' has already been declared. Variable names must be unique within a query batch or stored procedure.

**Comment by divega** [comment]
cc @AndriySvyryd

**Comment by AndriySvyryd** [comment]
@b-butcher Could you provide a small repro project?

**Comment by AndriySvyryd** [comment]
@qpler-bot You can use the "RC3" nightly builds from https://www.myget.org/F/aspnetvnext/api/v3/index.json, see https://github.com/aspnet/Home/wiki/NuGet-feeds. Beware that VS tooling will likely not work with these packages.

**Comment by AndriySvyryd** [comment]
@qpler-bot An RC2 workaround would be to disable update batching by calling
```
optionsBuilder.UseSqlServer("Connection string", b => b.MaxBatchSize(1));
```

**Comment by AndriySvyryd** [comment]
@qpler-bot Yes, the change might take a few days to get pushed, as currently there are some unrelated failures that are blocking the package publishing
