### ISSUE TITLE
Update scaffolding to use ScaffoldingTypeMapper

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#5410]
This follows the changes made for #4425 which provides more information from the type mapper to scaffolding on what to scaffold for a given property. However, the implementation assumes that IsUnicode has been implemented and so this cannot be done until that issue is fixed--see #3420.

**Comment by rowanmiller** [comment]
When this is done, verify that decimal columns have scale/precision included in column type

**Comment by bricelam** [comment]
This work was also mentioned as part of #1671

**Comment by AndriySvyryd** [comment]
The type for decimal properties should always be specified, even if same as default, due to #6944

**Comment by ajcvickers** [comment]
@lajones Can you elaborate on why this is flagged as a breaking change?

**Comment by lajones** [comment]
@ajcvickers This is part of the overall type mapping work. Though I haven't mapped out the exact API on how that will work yet, I don't think we'll manage to get through all of that without changing any of the type-mapping API. I don't know that it will specifically affect the `ScaffoldingTypeMapper` yet - we'll see.

**Comment by ajcvickers** [comment]
@lajones So you are saying that using the ScaffoldingTypeMapper will affect the reverse engineering API such that it will be breaking for providers? Or that #7434 will do that, and this is part of the work needed for #7434?

**Comment by lajones** [comment]
@ajcvickers The latter. I'm saying #7434 may affect the APIs on `ScaffoldingTypeMapper`.

**Comment by ajcvickers** [comment]
@lajones Then I think it's okay to have only #7434 marked as breaking.

**Comment by ajcvickers** [comment]
Moving this out of preview2 since it doesn't need to be done.

**Comment by smitpatel** [comment]
Poaching this as it needs for #7004

**Comment by smitpatel** [comment]
Fixed in #8626 & #8660 
There are some inaccuracies in how it is used filed #8697

**Comment by smitpatel** [comment]
Commits 263c102e74898ccf117d8eccabff81b34235f725 & 58c8f8100b98beb3ed003c10c7f1ef59141ff050
