### ISSUE TITLE
Unable to run sqlite functional tests with latest dev

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#5422]
VS 2015 Update 2 on Win 8.1 - latest source from dev - run with TestDriven  - all SQLite functional tests fail - I think they all pass when running via the "build" command.

Test 'Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.BuiltInDataTypesSqliteTest.Can_insert_and_read_back_all_mapped_data_types_set_to_null' failed:
	System.AggregateException : One or more errors occurred.
---- System.EntryPointNotFoundException : Unable to find an entry point named 'sqlite3_open_v2' in DLL 'sqlite3'.
---- The following constructor parameters did not have matching fixture data: BuiltInDataTypesSqliteFixture fixture
	
	----- Inner Stack Trace #1 (System.EntryPointNotFoundException) -----
	at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
	at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
	at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
	at Microsoft.Data.Sqlite.SqliteConnection.Open()
	SqliteTestStore.cs(74,0): at Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.SqliteTestStore.CreateAndOpenConnection(Boolean sharedCache)
	SqliteTestStore.cs(65,0): at Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.SqliteTestStore.CreateTransient(Boolean sharedCache)
	SqliteTestStore.cs(36,0): at Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.SqliteTestStore.CreateScratch(Boolean sharedCache)
	BuiltInDataTypesSqliteFixture.cs(17,0): at Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.BuiltInDataTypesSqliteFixture..ctor()
	----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----

**Comment by natemcmaster** [comment]
Confirmed issue. Our csproj generation isn't getting the right version of sqlite3.dll into the build output folder so running tests. You can workaround by manually copying sqlite3.dll from the nuget cache to the bin/debug/ folder. I believe TestDriven.NET runs in x86 only, so make sure to grab the win7-x86 version. 

cc @bricelam

**Comment by natemcmaster** [comment]
Remarking for triage: this doesn't need to happen for RTM. This is a EF dev issue, but doesn't affect product.

**Comment by rowanmiller** [comment]
I think our main concern was having the test coverage to ensure we have the right quality for RTM. Are these tests getting run on CI or somewhere?

**Comment by ErikEJ** [comment]
@rowanmiller They run when doing command line build on the local dev machine, just not when run using TestDriven

**Comment by divega** [comment]
Is there any chance that the new SQLite package could help fix the issue?

**Comment by natemcmaster** [comment]
I've opened a PR with a fix. #5668
