### ISSUE TITLE
RC2 ForEachAsync does not work anymore

### ISSUE THREAD

**Issue by bragma** [aspnet/EntityFramework#5440]
Hi,
I've just updated to RC2 and some of my tests are failing. It seems that this sample code using ForEachAsync is not working anymore:

```
await _dbContext.Stuff.Where(s => s.OtherId== otherId).ForEachAsync(s =>
{
	s.OtherId = defaultId;
});
```

The exception message is "New transaction is not allowed because there are other threads running in the session." when executing "SaveChangesAsync()"

My workaround at the moment is to materialize the results in a list and then use a foreach:

```
var listOfStuff = await _dbContext.Stuff.Where(s => s.OtherId== otherId).ToListAsync();
foreach(var s in listOfStuff)
{
	s.OtherId = defaultId;
}
```

Am I doing something wrong with ForEachAsync?
Thanks!

**Comment by divega** [comment]
@bragma I am surprised you get this exception since there is no call to `SaveChangesAsync()` in the code snippet. Is `s.OtherId = defaultId` really the only thing that is happening inside the `ForEachAsync()` loop?

On the other hand, if you are actually trying to save inside the loop, you are hitting a known limitation of SQL Server/SqlClient: you cannot create a transaction on a connection while you are still consuming results of a query in the same connection. But in that case, I am surprised you were not hitting this in RC1 as well.

**Comment by bragma** [comment]
@divega you are right, the snippet was just a part of a slightly larger method and I only hinted to the following SaveChangesAsync (but outside the loop). Still, no other changes were happening in the ForEachAsync(). I've run the test in the past dozen of times and never had the problem, while it showed immediately when moving to RC2. Here is the complete code:

```
public async Task DeleteGroup(Group group)
{
	// Get default group for association
	var defaultGroupId = await GetAssociationDefaultGroupId(group.FriendId);

	// Set all associate's group id to default if they were set to the group we want to delete
	await _dbContext.Associates.Where(a => a.GroupId == group.GroupId).ForEachAsync(a =>
	{
		a.GroupId = defaultGroupId;
	});

	_dbContext.Groups.Remove(group);
	await _dbContext.SaveChangesAsync();
}
```

Associate.GroupId is a foreign key. This code worked fine in RC1, i.e. it never caused its tests to fail.

**Comment by divega** [comment]
@bragma thanks for the additional details. If your code really looks like that I am afraid we could be failing to finish consuming and disposing the query results in `ForEachAsync()`.

cc @anpete

**Comment by divega** [comment]
@bragma BTW, in case it is relevant, what is in `GetAssociationDefaultGroupId()`?

**Comment by bragma** [comment]
@divega I've updated my previous post with the missing method. I don't think its relevant, btw.

**Comment by anpete** [comment]
@bragma Are you able to re-test this against a nightly build? You can use this feed: https://www.myget.org/F/aspnetvnext/api/v3/index.json

**Comment by bragma** [comment]
@anpete sure, I'll try to do it as soon as I get some breath from my job :)

**Comment by bragma** [comment]
@anpete sorry for the long delay, today I had some time to test against build "1.0.0-rc3-21267" and everything went well. My tests passed, I can mark this as fixed.

**Comment by anpete** [comment]
@bragma Thanks for the update!

**Comment by divega** [comment]
@anpete are we ready to close this one then?
