### ISSUE TITLE
Uwp ToListAsync() throws Exception with Message "The semaphore has been disposed."

### ISSUE THREAD

**Issue by cykone** [aspnet/EntityFramework#5444]
Hi,
I am using EF RC2 with an UWP App, after the update from EF RC1 the following Code lines:
`var iq= ctx.Projects.Include(p => p.Address).ThenInclude(a => a.GeoLocation);`
`return await iq.ToListAsync();`

throw an exception with the message="The semaphore has been disposed".

The same query works fine with synchronious ToList()

=> SingleOrDefaultAsync is also not working as expected.

**Comment by anpete** [comment]
@cykone Can you provide the stack trace?

**Comment by cykone** [comment]
at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.AsyncDisposer.Dispose()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor 1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129 1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter 1.GetResult()
   at Persistence.EntityFramework.Repositories.ProjectRepositoryEf.<>c__DisplayClass6_0 1.<<GetAllOrderedByAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by anpete** [comment]
@cykone I was able to repro this if I disposed the DbContext before the async query had completed. Can you verify whether or not this is happening in your case?

**Comment by flotie** [comment]
@anpete We call the ToListAsync() inside an using statement. 

`using(var ctx = this.contextfactory.Create())`
`{`
`var iq= ctx.Projects.Include(p => p.Address).ThenInclude(a => a.GeoLocation); `
`return await iq.ToListAsync(); `
`}`

**Comment by aflx** [comment]
Hi, I have the same problem, after upgrading to the latest build today.

doesn't work:
```
public Task<Project> GetProjectByIdAsync(int id)
{
	Task<Project> project = null;

	using (MyContext context = new MyContext())
	{
		project = context.Projects
		   .Include(p => p.Tasks)
			   .ThenInclude(t => t.TaskType)
			.Include(p => p.Tasks)
				.ThenInclude(t => t.Note)
		   .SingleOrDefaultAsync(p => p.Id == id);
	
	}

	return project;
}
```

workaround:
```
public async Task<Project> GetProjectByIdAsync(int id)
{
	Project project = null;

	using (MyContext context = new MyContext())
	{
		project = await context.Projects
		   .Include(p => p.Tasks)
			   .ThenInclude(t => t.TaskType)
			.Include(p => p.Tasks)
				.ThenInclude(t => t.Note)
		   .SingleOrDefaultAsync(p => p.Id == id);
	
	}

	return project;
}
```

**Comment by cykone** [comment]
@aflx thank you.

**Comment by gdoron** [comment]
@anpete @rowanmiller  just got hit by this one (constantly on one specific query) on 1.0.0 after working **for months** on this release.
Can you please shed some light why is this happening and how to avoid it in a non 1.1.0 release?

It looks very random that it drove me mad. 😢

**Comment by gdoron** [comment]
@anpete @rowanmiller  Also, worth mentioning, I'm running on full .NET Framework and not UWP.
So I hope the fix isn't just for UWP.

**Comment by rowanmiller** [comment]
@aflx the code you shared is by-design. Because you are storing the task that represents the query and not executing it right away, the context is disposed by the time you run the query. You either need to execute the query within the using statement (like you do in the second listing), or increase the scope of the context so that it is not disposed when you run the query.

**Comment by gdoron** [comment]
Just following up, I found a bug in my code involving threads and query running outside the scope of the context, disregard all my comments.
Sorry.

**Comment by rowanmiller** [comment]
@gdoron thanks for confirming!
