### ISSUE TITLE
Private properties not included in the model. Migration from RC1 to RC2

### ISSUE THREAD

**Issue by soycabanillas** [aspnet/EntityFramework#5446]
After migrating my project from RC1 to RC2, I've found some differences, most notably the one described on the title.
So on RC1, I had the next code

    [JsonConverter(typeof(StringEnumConverter))]
    public TEnum Subtype { get; set; }
    private string _subtypeText;
    [MaxLength(40)]
    private string SubtypeText => Subtype.ToString();

and the property SubtypeText got into the model, but not on RC2. The same happens with the next code:

    private string Serialized { get; set; }

The current documentation talks only about public properties being included in the model, but I'm almost sure the docs where different for the RC1 version.

Any discussion over it that I didn't found?

**Comment by smitpatel** [comment]
See #4314

**Comment by soycabanillas** [comment]
So now, I have to use "BackingFields" in order to model these properties, right?
Is it planned to create a MappedAttribute to help on this? I know is not the best idea to mix data access attributes with the model, but far simpler than my current solution (doesn't work by the way due the generics):

            var entityTypes = modelBuilder.Model.GetEntityTypes();
            foreach (var entityType in entityTypes)
            {
                foreach (var foreignKey in entityType.GetForeignKeys())
                {
                    foreignKey.DeleteBehavior = DeleteBehavior.Restrict;
                }
                var entityToModel = modelBuilder.Entity(entityType.ClrType);
                if (typeof(Entity.EntityBase).IsAssignableFrom(entityType.ClrType))
                {
                    entityToModel.HasAlternateKey(nameof(Entity.EntityBase.BGuid));
                }
                if (typeof(Entity.EntityBaseGeneric<>).GetGenericTypeDefinition().IsAssignableFrom(entityType.ClrType))
                {
                    entityToModel.Property<string>(nameof(Entity.EntityBaseGeneric<Entity.Enumerations.CUserEnum>.Subtype)).HasAnnotation("BackingField", "_subtypeText");
                }
            }

**Comment by rowanmiller** [comment]
Note for triage: I thought that mentioning the property by name would be enough to bring it in, but we create a shadow property.

**Comment by rowanmiller** [comment]
Calling the string overload should include the CLR property if one matches (even if the property is private).

**Comment by rowanmiller** [comment]
Here is a repro on RC2, `isShadow` is true when you run it.

```c#
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Repro.RC2
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new BloggingContext())
            {
                var isShadow = db.Model.GetEntityTypes().Single()
                    .GetProperties()
                    .Single(p => p.Name == "Test")
                    .IsShadowProperty;
            }
        }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=Test;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>().Property<int>("Test");

        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        private int Test { get; set; }
    }

}
```

**Comment by AndriySvyryd** [comment]
Fixed post RC2
