### ISSUE TITLE
Migration error with default double value

### ISSUE THREAD

**Issue by AR1ES** [aspnet/EntityFramework#5455]
When you have a double property that has a default double value, then `ef database update` command throws 
`Cannot set default value '0' of type 'System.Int32' on property 'XXX' of type 'System.Double' in entity type 'YYY'.`

Fluent configuration:
`mb.Property(p => p.Uptime).HasDefaultValue<double>(0.0).IsRequired();`

Created migration file:
```
migrationBuilder.AlterColumn<double>(
    name: "Uptime",
    table: "ServersStatusRate",
    nullable: false,
    defaultValue: 0);
```

Snapshot file:
```
b.Property<double>("Uptime")
     .ValueGeneratedOnAdd()
     .HasDefaultValue(0);
```

**Comment by ErikEJ** [comment]
Are you on RC2?

**Comment by AR1ES** [comment]
Yes. It is RC2 project.
On RC1 it worked correctly.

**Comment by geoffmmorgan** [comment]
Seeing this as well with shorts
`Cannot set default value '10' of type 'System.Int32' on property 'SortOrder' of type 'System.Int16' in entity type 'CurriculumMapItem'`

but I can fix with doing an explicit cast
entity.Property(e => e.SortOrder).HasDefaultValue((short)10);

**Comment by AndriySvyryd** [comment]
@geoffmmorgan The behavior you are seeing is by design, we currently don't perform value conversion in this code, even if it's safe
