### ISSUE TITLE
Release Build -> Yields M.E.PlatformAbstractions complications

### ISSUE THREAD

**Issue by mvermef** [aspnet/EntityFramework#5483]
Posting this here since it is the only library right now that I am using in conjunction with Template10 for Sqlite support.   It appears that the Microsoft.EntityFrameworkCore.Tools are part of the problem with M.E.PlatformAbstractions, since they are the only tool that apparently references that library

1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'sysctl!libc' in assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.

1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'uname!libc' in assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.

1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'RtlGetVersion!ntdll' in assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.

---project.lock.json --
"Microsoft.EntityFrameworkCore.Tools/1.0.0-preview1-final": {
        "type": "package",
        "dependencies": {
          "Microsoft.EntityFrameworkCore.Tools.Core": "1.0.0-rc2-final",
          "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc2-final",
          "System.Collections.NonGeneric": "4.0.0",
          "System.IO": "4.0.10",
          "System.IO.FileSystem": "4.0.0"
        },
        "compile": {
          "lib/netcore50/Microsoft.EntityFrameworkCore.Tools.dll": {}
        },
        "runtime": {
          "lib/netcore50/Microsoft.EntityFrameworkCore.Tools.dll": {}
        }
      },

**Comment by davidfowl** [comment]
The WACK strikes again...

/cc @ericstj @anurse

**Comment by rowanmiller** [comment]
@natemcmaster this may already be fixed by some of your work for RTM?

**Comment by mvermef** [comment]
what do I need to fork to get the latest code to test out?

**Comment by natemcmaster** [comment]
Actually, this issue should have landed on https://github.com/aspnet/PlatformAbstractions. The work around is to remove Microsoft.EntityFrameworkCore.Tools from your project before you build.

Leaving open as I am working on removing as many dependencies from our tooling package as possible.

**Comment by natemcmaster** [comment]
Just checked. There is already an issue open for this. https://github.com/aspnet/PlatformAbstractions/issues/34

**Comment by mvermef** [comment]
got it... just commented out the tools and it does build thanks for the temporary workaround.
