### ISSUE TITLE
"Process is terminated due to StackOverflowException" on Mac - works perfectly on Windows, how can I see further details?

### ISSUE THREAD

**Issue by mleader1** [aspnet/EntityFramework#5490]
Hi,

I'm trying out ASP.NET RC2 + EF Core, i created a simple Web Api app connecting to our existing database with the following setting:

1. WebApi:  simple ASP.NET Core 1.0 (RC2)   and on default port 5000
    Test Url:    /sites/{id:long}
    Data Layer testing code:   very simple  ( sudo code:    ` dbContext.Sites.FirstOrDefault(site=>site.Id == id)` 

2. As obviously as you can see it's a crazy simple Get request,  it works without any problem on Windows

However today I downloaded my testing repository code to my Mac, issues happened:

1.  compile and run without any problem
2.  Web server kestrel 5000 opened without any problem, web page opened without issue
3.  When visiting  /sites/2   ==> which worked on Windows, now it immediately failed with the following error:

![image](https://cloud.githubusercontent.com/assets/5477158/15504582/9220ba9a-21b7-11e6-9185-6b3c2ce64139.png)

**The only line of code in the Controller is  just calling the Get method usign the DbContext**
Obviously the code worked in Windows environment, so it's highly unlikely any bug in the testing code (no mention it's very simple)

One thing worth mentioning is that the database I connect to is a shadow copy of our production database that has over 100 tables in it. And the first kick start of the Asp.Net testing app takes about 20 seconds to boot up (not sure whether it is related to the entities scaffolded but it took just blink of a second without referencing the ef entities which I separated in another project)

Another thing to mention is that the database sits in Azure SQL v12.

I will now try to connect to a simple demo database and check whether that works, but regardless I think it's an issue worth reporting so here it goes...

**Comment by mleader1** [comment]
hi,

a further update here:  I've tried hooking up with another existing database with <20 data tables, it works without any issues on MacOSX

So I guess it's something weird happening with the database has a level of complexity... Since it works in Windows environment I'll stick onto this till next stable release of EF Core.

However if anyone can shed some lights of this issue above or **a way to dig more logging information** that'll be highly appreciated - you know geeks always seek for answers... 

Cheers

**Comment by rowanmiller** [comment]
@mleader1 we think this may be an exception occurring during model building. Could you just try accessing the `.Model` property on your context and see if you get the same exception when you do.

**Comment by mleader1** [comment]
hi @rowanmiller   yes you are absolutely right,the same exception threw when even just 1 line code assigning the .Model property to a local variable in the dbContext.

Are there any upcoming release for a fix?

**Comment by rowanmiller** [comment]
We think this is probably already fixed in our working code base. Any chance you could retry with out latest nightly build from https://www.myget.org/Gallery/aspnetcidev

**Comment by mleader1** [comment]
hi @rowanmiller   great thx - I confirm it works with the latest nightly build.  will have a further look with more complicated queries on Monday.  cheers!

**Comment by rowanmiller** [comment]
Great, thanks for confirming.
