### ISSUE TITLE
Local variable null check incorrectly translates to SQL

### ISSUE THREAD

**Issue by jacob-robertson** [aspnet/EntityFramework#5499]
I have a simple filter being passed into a `.Where()` call that is improperly using the equal operator (=) instead of `IS` to check for null values.

    var g = Guid.Parse('XXXX');
    var guitars = context.Guitars
                         .Include(g => g.Model)
                         .Where(g => guitarId == null || g.Id == guitarId);

Where `guitarId` is equal to some non-null value, translates to

    WHERE (@__guitarId_0 = NULL) OR ([g].[Id] = @__guitarId_1)

When `guitarId` is `null`, I get

    WHERE (@__guitarId_0 = NULL) OR [g].[Id] IS NULL

The first is incorrect but returns data.  The second always returns an empty data-set.  I would expect something like the following

    WHERE (@__guitarId_0 IS NULL) OR [g].[Id] IS NULL

The obvious workaround is to conditionally add the filter expression, but this does seem to be an issue with SQL translation in general.  I'm also curious as to why, in the first example the two references to `guitarId` are given two separate SQL parameters.  Shouldn't there just be one?  I've attached a working example.
                    
[EFTester.zip](https://github.com/aspnet/EntityFramework/files/280198/EFTester.zip)

**Comment by c1rus** [comment]
This works before rc2 :/

**Comment by gdoron** [comment]
Which build can we use if we can't wait for RTM on this?
I'm quite surprised that not even one test failed because of this...

**Comment by maumar** [comment]
@gdoron the fix is not checked in yet

**Comment by maumar** [comment]
fixed in 3e797a8ae3d09aeb6e580596dfc6f2c46c3b898a

**Comment by maumar** [comment]
@gdoron just checked in the fix so should be available in tomorrow's nightly build, unless we get some infra issues with the build system

**Comment by prasannapattam** [comment]
Where can I get the nightly build for this fix?

**Comment by gdoron** [comment]
Add the MyGet feed

**Comment by smitpatel** [comment]
More info on feeds : https://github.com/aspnet/Home/wiki/NuGet-feeds
