### ISSUE TITLE
Query :: force client evaluation on First() inside a query

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#5544]
We are currently translating First and FirstOrDefault calls into SQL whenever we can, however we should consider forcing client eval on First, so that we can mimic L2O behavior of throwing if there are no elements in the collection. We should continue translating FirstOrDefault

**Comment by rowanmiller** [comment]
> First, so that we can mimic L2O behavior of throwing if there is more than one element in the collection. 

Do you mean throwing if there is **no elements** in the collection?

**Comment by maumar** [comment]
right :)

**Comment by rowanmiller** [comment]
@maumar can you share some details of what happens now (i.e. wrong results, poor exception message, etc.)

**Comment by maumar** [comment]
it behaves just like FirstOrDefault, i.e. it never throws.

**Comment by maumar** [comment]
Clearing for re-triage. This could be a perf regression/breaking change for people who are already using it.

**Comment by divega** [comment]
**EF Team Triage:** we will switch to client eval. `FirstOrDefault()` is the only one of these operators that we can translate to SQL correctly.

**Comment by maumar** [comment]
Fixed in d698b57b561a7c27ff513b131937ad2d8c39de89
