### ISSUE TITLE
Scaffold-DbContext is not working

### ISSUE THREAD

**Issue by rchamila** [aspnet/EntityFramework#5549]
Im trying to generate the EF context for MS SQL database using the Scaffold-Context command in EFCore. But I'm getting following error each time I execute the command in Package manager console.

Command I used :
Scaffold-DbContext "'Server=DomainName\Server;Database=xxxxx;Trusted_Connection=True;'" Microsoft.EntityFrameworkCore.SqlServer

Error I got :
**The term 'Scaffold-DbContext' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:19
+ Scaffold-DbContext <<<<  "'Server=DomainName\Server;Database=xxxxx;Trusted_Connection=True;'" Microsoft.EntityFrameworkCore.SqlServer
    + CategoryInfo          : ObjectNotFound: (Scaffold-DbContext:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException**

 
EF Core version: 1.0.0-rc2-final
Operating system: Windows 7
Visual Studio version: VS2015

I've attached the project.json file for your reference
[project.txt](https://github.com/aspnet/EntityFramework/files/286107/project.txt)

Could you please check and let me know what is the issue with this?

**Comment by vedranzg** [comment]
also have the same problem..

ASP.Net Core Web App (.Net Core)
EF Core version: 1.0.0-rc2-final
Operating system: Windows 10
Visual Studio version: VS2015

**Comment by smitpatel** [comment]
I created new .NET Core console app and copied project.json as it was provided by @rchamila . I ran `dotnet restore --infer-runtimes` and then `Scaffold-DbContext` works.
If the term is not recognized then there is some issue in the tools installation. Try restoring packages again. You may need to delete the directory `%USERPROFILE%\.nuget\packages\.tools\Microsoft.EntityFrameworkCore.Tools` if tools were previously restored incorrectly.

**Comment by vedranzg** [comment]
Great, this is helpful and now Scaffold-DbContext works. Thanks a lot for your help

**Comment by rchamila** [comment]
Hi @smitpatel , I did the same thing as you suggested for a new console app, but still I'm getting same error. Steps I've followed.

1. Delete the directory under %USERPROFILE%\.nuget\packages\.tools\Microsoft.EntityFrameworkCore.Tools
2. Created new console app and copied the project.json
3. Ran dotnet restore --infer-runtime [By the way what is the use of this command?]
4. Ran Scaffold-DbContext but got the same eror.

Not sure whats wrong. Could you please assist?

Thanks

**Comment by smitpatel** [comment]
@rchamila - Can you share your `project.json` and output of `dotnet restore --infer-runtimes`

**Comment by rchamila** [comment]
Hi @smitpatel please find the attached files.
[output.txt](https://github.com/aspnet/EntityFramework/files/288720/output.txt)
[project.txt](https://github.com/aspnet/EntityFramework/files/288721/project.txt)

**Comment by smitpatel** [comment]
With that `project.json`, I hit the error, that Tools cannot target class library so I added following in project.json to make it console app.
```
"buildOptions": { 
  "emitEntryPoint": true 
}, 
```
After that it did work fine.
Looking at your feeds, you wouldn't need anything other than nuget feed. Could be case of inconsistent packages. I cannot think of any other reason why it would fail otherwise. You can give a try with having only nuget.org as feed. I will look into it more.

**Comment by rchamila** [comment]
I've tried adding the missing console app settings and removing our internal nuget feeds. But still the same. Anyway I'll try to play around and see how it goes. Thanks for the help

**Comment by smitpatel** [comment]
Here it is: A sample Console App which runs EF Commands in powershell and CLI both. https://github.com/smitpatel/EFCommands

**Comment by rchamila** [comment]
Thanks still no luck. I've installed following packages. Do I need to have anything else?

Install-Package Microsoft.EntityFrameworkCore.SqlServer –Pre
Install-Package Microsoft.EntityFrameworkCore.Tools –Pre
Install-Package Microsoft.EntityFrameworkCore.SqlServer.Design –Pre

**Comment by smitpatel** [comment]
With that and updating the imports auto-restore in VS works fine and Scaffold-DbContext work.
Can you try running the project this project on your machine? https://github.com/smitpatel/EFCommands
If that does not work then its some issue with package restored.

**Comment by rchamila** [comment]
Hi @smitpatel , I've used EFCommands project and followed following steps. But no luck yet

1. Changed the PMC directory to src\EFCommands 
2. Ran dotnet ef
3. Ran dotnet restore --infer-runtimes
4. Ran Scaffold-DbContext

I'm not sure whats wrong here. :(

**Comment by rchamila** [comment]
Hi @smitpatel , Just wanted let you know that I've used following command and finally it worked. :)

dotnet ef dbcontext scaffold -c PaymentsContext -o Model "Data Source=xxxxxx;Initial Catalog=xxxxxx;Integrated Security=True" Microsoft.EntityFrameworkCore.SqlServer --force

**Comment by smitpatel** [comment]
That is good to know 😄 
It is hard to know what is wrong, once you are in inconsistent state of tools installed.
If you can run dotnet ef command then in PMC for that project you should be able to have `Scaffold-DbContext` (& other ef commands) too. You can also verify that tools are restored properly in nuget packages by trying to run dotnet ef in some other project.

**Comment by rchamila** [comment]
Yeah in my case donet ef is working but Scaffold-DbContext doesn't work. Anyway thanks for the assistance.

**Comment by Scandal-UK** [comment]
I had this but installing Powershell 5 (and rebooting) got it to work properly.  Apparently this is a temporary requirement (see the EF docs for upgrading from RC1 to RC2).

**Comment by rchamila** [comment]
@Scandal-UK  spot on. It did the trick :). Thanks for sharing

**Comment by DanJ210** [comment]
Would this still be a solution for Windows 10? I would thing PowerShell 5 would be installed but I have all of these dependencies needed and I'm getting the same issue as in this thread.

**Comment by smitpatel** [comment]
@DanJ210 - Please file a new issue with details of your project, exception you are seeing & EF Core package versions. This is a very old issue. While it may be same error message, the root cause can be totally different based on project system/package version.

**Comment by MuhammadAsifAdnan** [comment]
Restarting vs fixed the issue for me.

**Comment by chileshemartin** [comment]
Performing a repair with visual studio installer fixed it for me.
