### ISSUE TITLE
Separate Sequence Test from other RevEng tests

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework#5593]
### Steps to reproduce
In f873682 I put `[SqlServerCondition(SqlServerCondition.SupportsSequences)]` on the 2 tests `SqlServerE2ETests.E2ETest_UseAttributesInsteadOfFluentApi` and `SqlServerE2ETests.E2ETest_AllFluentApi`. To repro simply remove those attributes and run those tests on a box where the version of SQL Server is 2008. 

### The issue
This was a temporary measure to prevent CI failures. Long term the correct solution is to pull out the part of the test that depends on a `CREATE SEQUENCE` statement (see `E2E.sql`) into a separate test, remove that attribute from the 2 old tests and have only the new test depend on `[SqlServerCondition(SqlServerCondition.SupportsSequences)]`.

**Comment by rowanmiller** [comment]
We should discuss the correct solution for this before implementing

**Comment by lajones** [comment]
Had the discussion with @rowanmiller. Proceeding as planned.
