### ISSUE TITLE
Commands: Better ConfigureDesignTimeServices entry point

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#5617]
Currently, if you want to configure design-time services (e.g. `MigrationsCodeGenerator`, `DbContextWriter`, `EntityTypeWriter`, etc.) you add a method named `ConfigureDesignTimeServices` to your `Startup`/`Program`/`App` class.

Instead, we should have a more structured approach similar to `IDbContextFactory<>`. We'll add an `IDesignTimeServices` interface. If there is an implementation of this interface in your startup assembly, we'll find it at design-time and use it to configure the design-time services.

**Comment by divega** [comment]
Reopening to take through patch release approval. 

@bricelam can you please put together a short paragraph explaining why we take this in 1.0.2? 

cc @Eilon

**Comment by bricelam** [comment]
Here is the commit of we'd like to take in the 1.0.2 patch: 85929c2f9691695ad34d4c8571b6e907c7b33001

**Comment by Eilon** [comment]
This patch is **approved**, please ensure it is merged into the correct branch and building as part of the patch train.
