### ISSUE TITLE
RC2 one-to-many An item with the same key...

### ISSUE THREAD

**Issue by liba23** [aspnet/EntityFramework#5624]
### Steps to reproduce
I have three entity models. The relationship is one-to-many. Entity2 has many Entities1 and Entities3

```C#
public class Entity1
{
    public int Id {get;set;}
    public string Property1 {get;set;}
...
...
    public string PropertyN {get;set;}
    public int Entity2Id {get;set}
    public virtual Entity2 Entity2{get;set;}
}

public class Entity2
{
    public int Id {get;set;}
    public string Property1 {get;set;}
...
...
    public string PropertyN {get;set;}
    public virtual ICollection Entities1 {get;set;}
    public virtual ICollection Entities2 {get;set;}
}

public class Entity3
{
    public int Id {get;set;}
    public string Property1 {get;set;}
...
...
    public string PropertyN {get;set;}
    public int Entity2Id {get;set}
    public virtual Entity2 Entity2{get;set;}
}
```
I have a list of Entities2 and I am trying to save it to a database.

```C#
List<Entity2> Entity2List ...
_context.Set<Entity2>().AddRange(Entity2List);
_context.SaveChanges();
```
### The issue
When _context.SaveChanges() is beeing performed, I get the following exception.
Exception message: An item with the same key has already been added.

Stack trace:
"   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\r\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.CreateStoreCommand()\r\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)\r\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)\r\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)\r\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()\r\n   at CheckBase.DataAccess.Repositories.Save() in D:\\Projects\\CheckBase\\src\\CheckBase.DataAccess\\Repositories.cs:line 54\r\n   at CheckBase.Application.DataHandler.SaveImportedVcfToDatabase(Guid taskId, Protocol protocol, List`1 sampleData, Int32 hgBuild) in D:\\Projects\\CheckBase\\src\\CheckBase.Application\\DataHandler.cs:line 181\r\n   at CheckBase.Application.Files.FileManager.<>c__DisplayClass25_0.<StartImportVcfData>b__0() in D:\\Projects\\CheckBase\\src\\CheckBase.Application\\Files\\FileManager.cs:line 337"

If I limit the list to approx. 450 items, it works.

**I have tried the same code on EF Core RC1 and it worked fine without any limitaiton.**

Am I doing something wrong?

### Further technical details

EF Core version:
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
"Microsoft.EntityFrameworkCore.Relational.Design": "1.0.0-rc2-final",
"Microsoft.EntityFrameworkCore": "1.0.0-rc2-final"

Operating system: Windows 10
Visual Studio version: VS2015 Community

**Comment by ajcvickers** [comment]
@liba23 I used your entities with the following code to try to reproduce the issue, but there was no exception. Can you post a complete repro or make the required changes to the code below to reproduce the issue.

```C#
public void Superbe()
{
    using (var context = new InsertContext())
    {
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        var entity1List = new List<Entity1>();
        var entity2List = new List<Entity2>();

        for (int i = 0; i < 2000; i++)
        {
            entity1List.Add(new Entity1 { Property1 = "Blah", PropertyN = "Blan" });
        }

        for (int i = 0; i < 2000; i++)
        {
            entity2List.Add(
                new Entity2
                {
                    Property1 = "Blah",
                    PropertyN = "Blan",
                    Entities1 = entity1List.ToList(),
                    Entities2 = entity2List.ToList()
                });
        }

        context.Set<Entity2>().AddRange(entity2List);

        context.SaveChanges();

    }
}

private class InsertContext : DbContext
{
    public DbSet<Entity1> Entity1s { get; set; }
    public DbSet<Entity2> Entity2s { get; set; }
    public DbSet<Entity3> Entity3s { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(SqlServerTestStore.CreateConnectionString("Superbe"));
}
```

**Comment by DotGoodies** [comment]
@ajcvickers, I have a very similar issue, but in my case I only update existing records. The table has parent and children tables but neither the data nor the relationships are changed by my updates.

There are 2 thing worth noting:
* If I limit the number of rows updated (there are ~13K rows in total), it works:
``` c#
foreach(var item in database.MyTable.Take(200))
{
  //Update fields
}
database.SaveChanges();
```

* Is I turn off tracking and then register each record in a change tracker, it works. Not surprisingly incredibly slowly.

``` c#
foreach(var item in database.MyTable.AsNoTracking())
{
 //Update fields
 database.MyTable.Update(item);
}
database.SaveChanges();
```

Exception looks as follows:
```
System.ArgumentException was unhandled
  HResult=-2147024809
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.CreateStoreCommand()
       at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
       at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
       at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
       at AnalogueDatabase.Program.Main(String[] args)
```

Do you think we need a separated issue for this?

## These are my EF packages
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview1-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0-rc2-final",

**Comment by ajcvickers** [comment]
@DotGoodies If you could post code that reproduces the issue that would be great.

**Comment by liba23** [comment]
I can't send you entire project, but I can separate it into new project. I'll do it over the weekend.

**Comment by AndriySvyryd** [comment]
I haven't been able to repro this either, so closing until we get a complete repro project.

**Comment by liba23** [comment]
[testrc25.zip](https://github.com/aspnet/EntityFramework/files/323187/testrc25.zip)

The project is attached. On the home screen is a link to a page Test. In the action method, list of Entity1, 2, 3 is saved to a database. This code produces the error described above.

**Comment by rowanmiller** [comment]
@AndriySvyryd reopened now that we have a repro

**Comment by liba23** [comment]
It looks it works again in the final release. Is it possible the problem was only in RC2?

**Comment by rowanmiller** [comment]
@liba23 yes, very much possible. I'll close this one out, but feel free to reply if you see it again.

**Comment by alexzaytsev-newsroomly** [comment]
I found the same issue with EF core 2.0, however i am using an external Pomelo.MySql provider (although there is no provider specific code on the stack)

**Comment by AndriySvyryd** [comment]
@alexzaytsev-newsroomly That's not the same code that was throwing in the original comment. Could you open a new issue and provide a small repro?
