### ISSUE TITLE
Move WarningsConfigurationBuilder to Infrastructure

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#5633]
In general we only put types in the root namespace that a developer would need to type out. `WarningsConfigurationBuilder` is "returned" in a nested closure lambda in `DbContextOptionsBuilder.ConfigureWarnings`, so I think it can go to infra.

**Comment by rowanmiller** [comment]
cc @anpete @divega @ajcvickers to see if we all agree as we'll want to get this change into RTM if we do.

**Comment by divega** [comment]
:+1:

**Comment by ajcvickers** [comment]
+1
