### ISSUE TITLE
Invalid SQL statement produced from null-coalescing a nullable boolean

### ISSUE THREAD

**Issue by nfiles** [aspnet/EntityFramework#5652]
##### Database:
```
CREATE TABLE dbo.Items (
    Id int NOT NULL PRIMARY KEY,
    Enabled bit NULL,
    Value nvarchar(max) NOT NULL
);
```

##### Entity:
```
public class Items
{
    [Key]
    public int Id { get; set; }
    public string Value { get; set; }
    public bool? Enabled { get; set; }
}
```

##### Query:
```
var items = _context.Items.Where(i => i.Enabled ?? false).ToList();
```

##### Generated SQL
```
SELECT [i].[Id], [i].[Enabled], [i].[Value]
FROM [Items] AS [i]
WHERE COALESCE([i].[Enabled], 0)
```

##### Exception message (from SQL)
```
An expression of non-boolean type specified in a context where a condition is expected
```

### The issue

Using the null-coalescing operator with a nullable boolean (`bool?`) in a `Where` clause produces invalid SQL. I would expect this LINQ statement to produce something like this:
`WHERE (COALESCE([i].[Enabled], 0) = 1`

Is there a format that EF Core expects for a query like this?

### Further technical details
EF Core version: EntityFramework 7.0.0-rc1-final
Operating system: Windows 8
Visual Studio version: VS 2015

**Comment by smitpatel** [comment]
Looking into this. Still repro in latest.
