### ISSUE TITLE
Investigate removal of relational LiteralExpression

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#5669]
Looks like we could just use ConstantExpression here.

**Comment by divega** [comment]
@anpete isn't this something we should consider doing now before anyone takes a dependency on `LiteralExpression`?

**Comment by anpete** [comment]
@divega Couldn't we just obsolete it?

**Comment by divega** [comment]
Yes, but if happened to be trivial to remove it before we release I think we can make the case.

**Comment by divega** [comment]
@smitpatel can you investigate if it would be trivial to remove `LiteralExpression`.
