### ISSUE TITLE
[Win 8.1 x86] New ASP.NET Core Web Application, Ctrl-F5 and try register a new user - we get The server was not found or was not accessible.

### ISSUE THREAD

**Issue by balachir** [aspnet/EntityFramework#5713]
**INSTALL STEPS:**
Win8.1 x86 ENU + Dev14 U3 RC + DotNetCoreRTWTooling
DotNetCoreRTWTooling build: DotNetCore.1.0.0.RC3-25-VS2015Tools.Preview2.exe

**REPRO STEPS:**
1. File > New Project > ASP.NET Core Web Application->Web application ("Individual Accounts")
2. Ctrl-F5
3. Try to register a new user

See additional info below

 **ACTUAL:**
![image](https://cloud.githubusercontent.com/assets/8246794/15950853/8a73c974-2e67-11e6-960c-9b071ab77f5b.png)

**EXPECTED**
![image](https://cloud.githubusercontent.com/assets/8246794/15950952/8e7a9c18-2e68-11e6-9b0a-e42c844eb576.png)

**SOME ADDITIONAL INFO**
1. LocalDb is properly installed on this machine.
2. Waiting a minute and try Ctrl-F5 and register again does not seem to help
3. If I create a new MVC 5 application and try to register a new user, that works fine. 
4. In same VS session as (4) above, if I now create a new ASP.NET Core application and try to register a user that works fine
5. If I restart the machine and try creating a new ASP.NET Core application and try to register a user, I can reproduce the issue again
6. I can reproduce this issue with .NET Core RC2 tooling as well

**Comment by natemcmaster** [comment]
Could this be a bug in Localdb? When I tried to install dev14 u3 RC, I got this 

![image](https://cloud.githubusercontent.com/assets/2696087/15981305/53261168-2f28-11e6-827f-364a2ba060d3.png)

**Comment by divega** [comment]
Indeed, executing the following command in the command prompt proves it:

``` 
>sqllocaldb s mssqllocaldb
Start of LocalDB instance "mssqllocaldb" failed because of the following error:
Error occurred during LocalDB instance startup: SQL Server process failed to start.
``` 

@balachir I didn't want to make changes in the repro VM you gave me but here are a coupe of things I would have tried as possible workarounds:

- Delete the automatic LocalDB instance with `sqllocalddb d mssqllocaldb` to if recovers after that. 
- Repair the application "Microsoft SQL Server 2015 Express LocalDB" in ARP

**Comment by divega** [comment]
From the application event log:
```
Log Name:      Application
Source:        SQLLocalDB 12.0
Date:          6/10/2016 9:51:24 PM
Event ID:      528
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ***
Description:
Windows API call WaitForMultipleObjects returned error code: 575. Windows system error message is: {Application Error}
The application was unable to start correctly (0x%lx). Click OK to close the application.
Reported at line: 3728. 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="SQLLocalDB 12.0" />
    <EventID Qualifiers="51653">528</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-06-11T04:51:24.000000000Z" />
    <EventRecordID>3801</EventRecordID>
    <Channel>Application</Channel>
    <Computer>***</Computer>
    <Security />
  </System>
  <EventData>
    <Data>WaitForMultipleObjects</Data>
    <Data>575</Data>
    <Data>{Application Error}
The application was unable to start correctly (0x%lx). Click OK to close the application.
</Data>
    <Data>3728</Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by divega** [comment]
@natemcmaster what OS and bitness did you have issues with? Do you get the same errors?

**Comment by divega** [comment]
Closing as I am pretty sure this is external. @balachir let's follow up offline.

**Comment by natemcmaster** [comment]
@Divega I was on Win 10 x64. Reinstalling localdb fix it for me

**Comment by balachir** [comment]
Yeah, I did a search online using the description from the application event log error and found other reports of this issue as well. eg: See [this post](http://stackoverflow.com/questions/13287252/cannot-start-localdb) on StackOverflow

Here is the workaround that fixed the problem for me
![image](https://cloud.githubusercontent.com/assets/8246794/16081772/c77e0572-32c3-11e6-9ac3-9b67baf8c1bd.png)
