### ISSUE TITLE
Nit -  reveng generated DbContext violates SA1201: A property should not follow a method

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/EntityFramework#5721]
### Steps to reproduce
Run reveng on existing database

### The issue
It all works.  Its just the emitted DbContext class violates SA1201
To be specific the virtual DbSet properties come after the OnModelCreating method.

```
warning SA1201: A property should not follow a method
```

### Further technical details

RC2
win7 x64
Visual Studio 2015 update 2

### The resolution

Emit OnModelCreating after DbSet properties.

**Comment by lajones** [comment]
@rowanmiller There are actually multiple StyleCop rules we fail: multiple elements should have xml comments, `using`s should be inside `namespace`, properties should be separated by a blank line, references to members in the constructor should be prefixed by `this.` etc. Some of these could be fixed, but for e.g. the xml comments it would be difficult to produce anything meaningful and using `this` would be against our current R# rules.

Note 1: the `Program.cs` and `AssemblyInfo.cs` files produced by the project template also fail several StyleCop rules.
Note 2: for EF6 we did e.g. put the properties before the methods and the `using`s inside the `namespace` but e.g. did not put blank lines between the properties nor add xml comments nor use `this`.

Do you want an exhaustive list of all the StyleCop rules we fail and suggestions, do you want to just fix SA1201, or ...?

**Comment by rowanmiller** [comment]
Agreed that in general we should favor readable code that resembles what we think folks write over being SA compliant. But in this case, I do think the methods should come after the properties. In all our samples etc. that is how we layout the members of the derived context.

**Comment by rowanmiller** [comment]
cc @ajcvickers  @bricelam @anpete to check that we are in agreement

**Comment by ajcvickers** [comment]
@rowanmiller Agreed. Even though it was filed that way, this bug wasn't triaged to fix because of the StyleCop issue. It is about generating code that is idiomatic of how DbContext classes are written. Rowan has good examples in the docs. In particular, DbSet properties go after constructors and before methods.

**Comment by lajones** [comment]
@ajcvickers @rowanmiller Moving properties before methods and after constructors seems agreed. Any thoughts on `using`s? At the moment we do at the top of the file, before the namespace. To be consistent with EF6 (and StyleCop) we'd have to do within the namespace just before the class declaration. Let me know - I'd like to agree on a format and just make the change once.

Note to self: will need to change docs for reverse-engineering as well.

**Comment by rowanmiller** [comment]
I think usings should stay at the top of the file. Putting them inside the namespace is to prevent some edge cases issues and in general isn't something that folks do.

**Comment by ajcvickers** [comment]
Agree with @rowanmiller

**Comment by lajones** [comment]
OK - so for this issue I'll just change where the properties are then.

**Comment by lajones** [comment]
Fix checked in with commit 54fce03.
