### ISSUE TITLE
Microsoft.EntityFrameworkCore.Tools.Core version is "1.0.0-rc3-*"

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#5746]
@rowanmiller just found that this package is not versioned as "1.0.0-preview2-*" although it is part of the tooling. 

@natemcmaster @bricelam is this intentional for a reason we are missing?

BTW, we actually already shipped the package with that name as "1.0.0-rc2-final" so just changing the version to "preview2" would be going back in time.

**Comment by natemcmaster** [comment]
This was just something we missed when we split the versions. We plan to remove this package as a part of https://github.com/aspnet/EntityFramework/issues/5334. As the rc2 version is out, we probably shouldn't go back in time by naming it preview2.

**Comment by rowanmiller** [comment]
If we ship it in this next release it is RTM'd though, so we can't just abandon it when we get to #5334

**Comment by natemcmaster** [comment]
Can we pick another prerelease label that comes after rc2?

**Comment by divega** [comment]
Can we rename the package so that we can stamp it as priview2 without it being going back in time? What is the package supposed to contain at a high level, i.e. is there a better name for it than "core"?

**Comment by natemcmaster** [comment]
I supposed we could rename the package too. The package contains components shared between the powershell cmdlets and dotnet cli commands.

**Comment by divega** [comment]
Ok, and what is the general plan for https://github.com/aspnet/EntityFramework/issues/5334? Is it going to be merged into some other package?

**Comment by divega** [comment]
@natemcmaster @rowanmiller @bricelam did you get a chance to talk about this?

**Comment by natemcmaster** [comment]
The general plan for #5334 is that the code currently in .Tools.Core will be lifted into .Design. We talked in person and decided the simplest solution is to rename .Tools.Core to .Design.Core and label it preview2.
