### ISSUE TITLE
Several types in provider assemblies should be "internal"

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#5761]
In general we have made the provider implementations of core services "internal" - since no one should really need to interact with them.

Here are the ones I've found that violate this principle:
* InMemoryTransaction
* InMemoryTransactionManager
* SqliteDatabaseProviderServices 
* SqliteQuerySqlGenerator
* SqliteQuerySqlGeneratorFactory
* ISqlServerExpressionVisitor

There are also a number of query ones that are covered by https://github.com/aspnet/EntityFramework/pull/5759

cc @divega

**Comment by rowanmiller** [comment]
BTW I did a scan back over the projects to check for others that I've missed (I couldn't find any)

**Comment by rowanmiller** [comment]
cc @anpete just to confirm there isn't a specific reason that the query ones shouldn't be "internal"

**Comment by anpete** [comment]
@rowanmiller  Wouldn't these be the primary way a user would extend/tweak a provider? E.g. Subclass a provider SQL generator to tweak something.

**Comment by rowanmiller** [comment]
Spoke with @anpete and we agreed these should be "Internal" for the moment, though we do plan to make them a public extension point later when we have a better handle on how folks would use them.
