### ISSUE TITLE
Upgrade to re-linq 2.1.1 and Ix-Async 3.0.0

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#5766]
Re-linq 2.1.0-rc-001 is build against CoreFX RC2. We will need to upgrade EF to 2.1.1 for the "RTM" release of CoreFX ~~when it is available.~~

The same applies to System.Interactive.Async 3.0.0-beta-00397. We need to upgrade to 3.0.0 when it is available.

- [x] Remotion.Linq 2.1.1
- [x] System.Interactive.Async 3.0.0

**Comment by Eilon** [comment]
Yay!!!
