### ISSUE TITLE
SQL Server Migrations: Rebuild columns after altering HasComputedColumnSql

### ISSUE THREAD

**Issue by maksir** [aspnet/EntityFramework#5789]
### Steps to reproduce
I have a class
```C#
public class User : IdentityUser<int>
{
	public string Name { get; set; }
	public string DisplayName { get; set; }
}
```
and DbContext
```C#
AppDbContext : IdentityDbContext<User, Role, int>
{
    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.Entity<User>().Property(p => p.DisplayName).HasComputedColumnSql("[Name]");
    }
}
```

execute

    dotnet ef migrations add User_DisplayName
    dotnet ef database update
    All done.

Modify `OnModelCreating()`  like this:
```C#
builder.Entity<User>().Property(p => p.DisplayName)
    .HasComputedColumnSql("[Name] + ' (' + [Email] + ')'");
```
execute again

    dotnet ef migrations add User_DisplayName_fix
    dotnet ef database update

### The issue

    Error Number:156,State:1,Class:15
    Incorrect syntax near the keyword 'AS'.'

### Further technical details
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview1-final",
Operating system: Win 10
Visual Studio version: 2015
MS SQL 2012

### Cause of the error
In this file `src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs`
lines number 60 and 400 generating script:
```SQL
alter table User alter column DisplayName as [Name] + ' (' + [Email] + ')'
```
This is wrong. 
T-SQL does not support argument 'AS' for command 'Alter column'.

For computed column, need 2 commands.

1. drop computed column
2. create new computed column with same name

**Comment by rowanmiller** [comment]
If you are changing a column from non-computed to computed you are also dropping all the existing data from the column. Perhaps our model differ should reason about this and generate a DropColumnOperation and AddColumnOperation rather than the alter in this case.

**Comment by bricelam** [comment]
> If you are changing a column from non-computed to computed...

This is not what the code above is doing. It just changes the computed expression--the column was previously computed too.

As far as I can tell, Oracle supports altering computed columns just like any other column. I think we should treat this issue as specific to SQL Server and rebuild the column in its Migrations SQL generator.
