### ISSUE TITLE
Migrations: SQL Server Filtered Indexes

### ISSUE THREAD

**Issue by MarcoLoetscher** [aspnet/EntityFramework#5817]
For indexes on SQL Server, it should be possible to set a filter might as string or lamda expression:
`modelBuilder.Entity<Blog>().HasIndex(b => b.Url, "[Url] IS NOT NULL AND [IsActive] = 1");`
or
`modelBuilder.Entity<Blog>().HasIndex(b => b.Url, b => b.Url != null && b.IsActive == 1);`

**Comment by AndriySvyryd** [comment]
Fixed in 2e0498a by @laskoviymishka
