### ISSUE TITLE
Optional Foreign Key Isn't Updated in Child Record When Record Is Added

### ISSUE THREAD

**Issue by chrisjmccrum** [aspnet/EntityFramework#5833]
Attached project. Unfortunately I dont have MS SQL so the startup and package reference Npgsql (PostgreSQL).  It should be fairly trivial to change it on your end to sql to test tho.
[webapp.zip](https://github.com/aspnet/EntityFramework/files/327031/webapp.zip)

### The issue
I'm trying to understand how to update one record and add a related entity to that record for the first time, and then update the original record with the foreign key from the newly create related record. When you run the project it will automatically:

1. Create a Tenant (TenantID) -  TenantName: ABC Company
2. Create a Person (TenantID, PersonID) -  FirstName: Chris
3. Create a Client (TenantID, ClientID) -  Comments: "Sample Comment"

The client has no last name or address at this point.  When I call my controller I then want to add a last name to person and Address (TenantID, AddressID). This also works.  What doesn't happen tho is that the app doesn't automatically fill in the Client Address ID Foreign Key.

```
            int tenantID = 1;
            var client = _db.tbl_Client
                .Include(t => t.tbl_Person)
                .Include(t => t.tbl_Address)
                .Where(p => p.TenantID == tenantID &&
                            p.ClientID == id).First();

            client.Comments = "Revised Sample Comment";
            client.tbl_Person.LastName = "Jack";
            client.tbl_Address = new tbl_Address() {
                AddressLine1 = "123 Sesame St",
                City = "New York",
                State = "NY",
                TenantID = tenantID
            };

            _db.SaveChanges();
```

### Further technical details

EF Core version: 1.0.0-rc2-final
Operating system: MacOS 10.11.5
Visual Studio version: Visual Studio Code 1.2.1

**Comment by ajcvickers** [comment]
I was able to reproduce this with RC2, but it is fixed with current bits.
