### ISSUE TITLE
Clearer documentation : IsRequired vs Ignore

### ISSUE THREAD

**Issue by Ponant** [aspnet/EntityFramework#5855]
Documentation in https://docs.efproject.net/en/latest/modeling/included-types.html
and https://docs.efproject.net/en/latest/modeling/included-properties.html
does not explain the difference between Ignore and IsRequired(false). It seems from intellisense that IsRequired is about setting the value to null or not, which is not clear in the documentation.

### Advice
Change the examples provided to isolate the case of type vs property and go through IsRequired vs Ignore vs NotMapped.

**Comment by rowanmiller** [comment]
`NotMapped`/`Ignore` are about excluding types from the model. `IsRequired` is unrelated to this concept and is about whether the column can store nulls or not - https://docs.efproject.net/en/latest/modeling/required-optional.html.

The uses of these are pretty clear in the docs (including the API docs that show in IntelliSense). We generally don't have docs to specifically compare/contrast unrelated things.

**Comment by Ponant** [comment]
The confusion occurs here in the docs https://docs.efproject.net/en/latest/modeling/included-types.html :

```
class MyContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AuditEntry>()
                .Property(a => a.Username)
                .IsRequired();
        }
```
The doc highlights 

`modelBuilder.Entity< AuditEntry >() 
`
as being the reason why AuditEntry is discovered, but the reader may conclude that it is the presence of IsRequired which makes AuditEntry discovered.

**Comment by rowanmiller** [comment]
Ah, good point. I'll trim it down to just the call to `Entity<>`

**Comment by Ponant** [comment]
Probably people who know about that would find this trivial, but it was not obvious at all to me. For instance I thought I absolutely needed DbSet in this business, but it is more tricky (hence the use of "discovered" wording in the doc perhaps). Here is a way to show the subtleties, for instance (notice the absence of DbSet among other things):

```
public class AppDbContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {           

        //This will create the Table BTable
        modelBuilder.Entity<BTable>();

        //This will create the Table CTable with the property CNotRequired possibly null
        modelBuilder.Entity<CTable>()
        .Property(p => p.CNotRequired)
        .IsRequired(false);

        //This will create the Table CTable but without the property CIgnore
        modelBuilder.Entity<CTable>().Ignore(p => p.CIgnore);
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) //Seems to run only once
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFCoreBase-v1;Trusted_Connection=True;");
    }
}
```
```
public class BTable
{
    public int Id { get; set; }
    public string B1 { get; set; }
}

public class CTable
{
    public int Id { get; set; }
    public string C1 { get; set; }
    public string CNotRequired { get; set; }
    public string CIgnore { get; set; }
}

```
```
add-migration init

update-database
```
Output will be the tables
![btable](https://cloud.githubusercontent.com/assets/19961806/16351228/620b723a-3a64-11e6-8c9d-3f4a125a5d13.PNG)
![ctable](https://cloud.githubusercontent.com/assets/19961806/16351229/620c0e3e-3a64-11e6-846d-cecf03117903.PNG)

**Comment by rowanmiller** [comment]
Adjusted docs to be clearer in https://github.com/aspnet/EntityFramework.Docs/commit/1c52eeb17f5281757e91bf0d3ac34ffb591befa5

**Comment by Ponant** [comment]
Thanks
