### ISSUE TITLE
Sort order is lost while grouping items and there is some duplicated items

### ISSUE THREAD

**Issue by zegroumf** [aspnet/EntityFramework#5869]
### The issue
I'm trying to extract some grouped data from the database with the inner data of each groups sorted. The groups have also to be sorted

The query is very basic as :
```
context.Books.OrderBy(b => b.Number)
.ThenBy(b => b.Name)
.Join(context.Collections, b => b.CollectionId, c => c.Id, (b, c) =>
	new
	{
		Id                = b.Id,
		Name              = b.Name,
		Number            = b.Number,
		CollectionName    = c.Name,
	})
.GroupBy(bbv => bbv.CollectionName)
.OrderBy(group => group.Key);
```
I'm basically sorted the books, grouping them and then sorting the groups.

In EF CORE, the order of the items is incorrect when the grouping is performed and there is some duplicated entries
I'm ending with something like:

```
Collection 0 
    Book 0
    Book 95
    Book 85
    ...
    Book 5
    Book 0
    Book 95
    Book 90
```

Using LINQ-to-object or LINQ-to-SQL, the books order is kept and there is no duplicated items. The LINQ-to-object implementation is available in the repro application. The LINQ-to-SQL has been tested using LinqPad 5.

Please look at the attached repro app. It displays both the EF CORE invalid result and the expected one.

### Further technical details

EF Core version: 1.0.0-rc2-final
Operating system: Windows 10 (586)
Visual Studio version:2015

[EF Core issue.zip](https://github.com/aspnet/EntityFramework/files/333608/EF.Core.issue.zip)

**Comment by gdoron** [comment]
Seems like you can use this instead:

	context.Books
	.Join(context.Collections, b => b.CollectionId, c => c.Id, (b, c) =>
	    new
	    {
	        Id                = b.Id,
	        Name              = b.Name,
	        Number            = b.Number,
	        CollectionName    = c.Name,
	    })
	.OrderBy(b => b.CollectionName)
	.ThenBy(b => b.Number)
	.ThenBy(b => b.Name)
	.GroupBy(bbv => bbv.CollectionName);
	
It's even more readable IMHO.

**Comment by anpete** [comment]
@zegroumf I think this may have been fixed as I'm unable to repro. If you have time to confirm against a nightly, that would be great.
