### ISSUE TITLE
Group by multiple properties Extension methods error.

### ISSUE THREAD

**Issue by jotab123** [aspnet/EntityFramework#5887]
Hi!
I think I found and error working on group by queries with multiple properties using Linq.Dynamic.Core library https://github.com/StefH/System.Linq.Dynamic.Core that I believe is an EntityFramework Core error because the output is correct in memory List query but not in sql server database query.

Full example project: https://github.com/jotab123/GroupByError

**Model**
```
    [Table("Element")]
    public class Element
    {
        [Key]
        public int Id { get; set; }
        public double Attribute1 { get; set; }
        public double Attribute2 { get; set; }
    }
```
**Test**
```
 //List test.
var resultList1 = ElementsList.GroupBy(el => new { el.Attribute1, el.Attribute2 });     //CORRECT
var resultList2 = ElementsList.AsQueryable().GroupBy("new(Attribute1, Attribute2)");    //CORRECT

 //Database tests.
var resultDb1 = db.Element.GroupBy(el => new { el.Attribute1, el.Attribute2 });         //CORRECT
var resultDb2 = db.Element.GroupBy("new(Attribute1, Attribute2)");                      //WRONG
```

EF Core version: 1.0 Final Release
Operating system: Windows 10
Visual Studio version: VS 2015

Other details about my project setup:
System.Linq.Dynamic.Core

**Comment by rowanmiller** [comment]
Can you elaborate on what "wrong" means. Do you see an exception, incorrect results, unexpected SQL, etc.?

**Comment by jotab123** [comment]
Last query returns incorrect results. resultList1, resultList2 and resultDb1 return 4 groups, resultDb2 returns 10 groups. I'm in contact with Stef Heyenrath, main developer of Linq Dynamic Core library, about this problem. He tried it in Entity Framework 6.1.3 and works fine.

More info in this thread: [https://github.com/StefH/System.Linq.Dynamic.Core/issues/31](url)

**Comment by smitpatel** [comment]
Same cause as #4581

**Comment by smitpatel** [comment]
@jotab123 - #6271 fixed this. Feel free to re-open if you still see the issue after fix.
