### ISSUE TITLE
Generating Migrations loses using / namespace for custom types

### ISSUE THREAD

**Issue by akuseru** [aspnet/EntityFramework#5912]
### Steps to reproduce

when creating a model add a custom type. In my case i am using `NpgsqlTypes.NpgsqlDateTime` 

``` c#
using NpgsqlTypes;

// ---- OR ---

public NpgsqlTypes.NpgsqlDateTime Posted{get;set;}

```

(I have models with both methods atm for testing.)
### The issue

I expect the command `dotnet ef migrations add [migration name]` to maintain the type definitions. either by adding a `using NpgsqlTypes;` or by keeping the type as `NpgsqlTypes.NpgsqlDateTime`

instead the following is generated:

``` c#
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using project.Data;

namespace project.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20160630040622_addNews")]
    partial class addNews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
                 modelBuilder
                        .HasAnnotation("ProductVersion", "1.0.0-rtm-21431");
//------- snip ----
modelBuilder.Entity("project.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorId");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<int>("Comments");

                    b.Property<NpgsqlDateTime>("Posted");

                    b.Property<string>("SeoUrl");

                    b.Property<string>("Title");

                    b.Property<bool>("Visible");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SeoUrl");

                    b.ToTable("News");
                });
/// ---- snip ---
        }
    }
}

```

Exception message:
Stack trace:

```
/Users/adam/git/project/Data/Migrations/ApplicationDbContextModelSnapshot.cs(79,32): error CS0246: The type or namespace name 'NpgsqlDateTime' could not be found (are you missing a using directive or an assembly reference?)
/Users/adam/git/project/Data/Migrations/ApplicationDbContextModelSnapshot.cs(152,32): error CS0246: The type or namespace name 'NpgsqlDate' could not be found (are you missing a using directive or an assembly reference?)
/Users/adam/git/project/Data/Migrations/ApplicationDbContextModelSnapshot.cs(162,32): error CS0246: The type or namespace name 'NpgsqlDate' could not be found (are you missing a using directive or an assembly reference?)
/Users/adam/git/project/Data/Migrations/20160630040622_addNews.cs(20,43): error CS0246: The type or namespace name 'NpgsqlDateTime' could not be found (are you missing a using directive or an assembly reference?)
Compilation failed.
/Users/adam/git/project/Data/Migrations/20160630040622_addNews.Designer.cs(80,32): error CS0246: The type or namespace name 'NpgsqlDateTime' could not be found (are you missing a using directive or an assembly reference?)
    0 Warning(s)
    7 Error(s)
/Users/adam/git/project/Data/Migrations/20160630040622_addNews.Designer.cs(153,32): error CS0246: The type or namespace name 'NpgsqlDate' could not be found (are you missing a using directive or an assembly reference?)
Time elapsed 00:00:03.2841875
/Users/adam/git/project/Data/Migrations/20160630040622_addNews.Designer.cs(163,32): error CS0246: The type or namespace name 'NpgsqlDate' could not be found (are you missing a using directive or an assembly reference?)
Build failed on 'project'.
```
### Further technical details

EF Core version: 1.0.0
Operating system: 
Visual Studio version: VS code 1.2.1

Other details about my project setup:

```
"Npgsql": "3.1.5",
"Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.0",
```

**Comment by natemcmaster** [comment]
Can you use `System.DateTime` instead of `NpgsqlDateTime`? If I understand correctly, the Postgres provider will map this an appropriate storage type.

cc @roji @npgsql

**Comment by akuseru** [comment]
I believe that I could, However there are still other types in the `NpgsqlTypes` that I would like to use, NpgsqlDate & NpgsqlPoint for instance. While I could simplify those down to more native types I already have existing data in those types that I would like to use.

Thanks!

**Comment by ajcvickers** [comment]
Note for triage: We used to have code to do this for spatial types in the old stack. I think we should do the same thing here. We can't put model types in the snapshot because they will change as the model changes, but these types should be okay--we just need to handle them in the code that generates the using statements.

**Comment by bricelam** [comment]
Interesting. I believe we have code to this this in the `Migration` class generator. We must have missed it in the snapshot.

**Comment by bricelam** [comment]
We cover namespaces for annotation enum values, but it looks like we're missing namespaces for the following:

* AddColumnOperation.ClrType
* AddColumnOperation.OldColumn.ClrType
* AlterColumnOperation.ClrType
* AlterColumnOperation.OldColumn.ClrType
* CreateTableOperation.AddColumnOperation.ClrType
* CreateTableOperation.AddColumnOperation.OldColumn.ClrType
* IProperty.ClrType

**Comment by Kagamine** [comment]
@ajcvickers This issue still occurred in Pomelo.EntityFrameworkCore.MySql When working with `JsonObject`

The generated script:

![image](https://cloud.githubusercontent.com/assets/2216750/21495339/b88092a6-cc51-11e6-9734-043aed70c1ad.png)

Model:

![image](https://cloud.githubusercontent.com/assets/2216750/21495333/b0b83010-cc51-11e6-9841-4e8a7b02e7cf.png)

It seems that EF Core cannot add the generic type's namespace yet.

**Comment by divega** [comment]
@Kagamine I am having a hard time trying to imagine how this class gets mapped, but if you can provide a repro that works (besides the namespaces not being generated in migrations) it would be great if you could create a new issue for it and we will investigate.

**Comment by ajcvickers** [comment]
@divega It probably makes senses to look at the generic parameters regardless of whether the JsonObject stuff actually works right now. Re-opening to triage.

**Comment by ajcvickers** [comment]
Decided to create a new issue (#7352) for this instead so we don't lose release information for where this one was fixed.

**Comment by divega** [comment]
@ajcvickers makes sense. Thanks.
