### ISSUE TITLE
Weird test failure with GroupBy/Min

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#592]

**Comment by natemcmaster** [comment]
`GroupBy_Sum_Min_Max_Avg` has started failing again on CI. It fails consistently on Mono.

**Comment by anpete** [comment]
Could be another IX-Async bug. @divega was taking a look. Might need to do some dedicated investigation.

**Comment by divega** [comment]
@natemcmaster is it right to assume that the test yields different wrong Avg results every time or by do you mean it really always returns the same? Just trying to figure out what you mean by "consistent" in this context :smile:

**Comment by natemcmaster** [comment]
By consistent I meant every run on Mono fails. On Windows and CoreCLR, the tests appear to pass most of the time. On CI they pass about 98% of the time.
![image](https://cloud.githubusercontent.com/assets/2696087/11153933/07184764-89f1-11e5-9bbb-f8ad63c7a663.png)

**Comment by divega** [comment]
Thanks!

**Comment by anpete** [comment]
Fixed.
