### ISSUE TITLE
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Error: An exception occurred in the database while iterating the results of a query.

### ISSUE THREAD

**Issue by TerraVenil** [aspnet/EntityFramework#5958]
### Steps to reproduce
Startup configuration
`var connection = @"Server=(localdb)\mssqllocaldb;Database=Northwind;Trusted_Connection=True;";
            services.AddDbContext<OrderContext>(options => options.UseSqlServer(connection));`

I have a very simple query in my Api
```
[HttpGet]
public IActionResult Get()
{
	IEnumerable<Order> orders = _orderContext.Orders;

	var result = orders
		.Where(x => x.OrderDate < new DateTime(1996, 7, 12) && x.OrderDate > new DateTime(1996, 7, 4))
		.OrderBy(x => x.ShippedDate)
		.GroupBy(x => x.ShipName);

	return Ok(result);
}       
```

### The issue
I expected to load all orders from database and apply filtering on the Web Api side.
```
Stack trace:
```
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Debug: TRACKED: True
(QueryContext queryContext) => IEnumerable<Order> _ShapedQuery(
    queryContext: queryContext, 
    shaperCommandContext: SelectExpression: 
        SELECT [o].[OrderID], [o].[OrderDate], [o].[ShipName], [o].[ShippedDate]
        FROM [Orders] AS [o]
    , 
    shaper: UnbufferedEntityShaper<Order>
)

'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\USER_NAME\.nuget\packages\System.Data.SqlClient\4.1.0\runtimes\win\lib\netstandard1.3\System.Data.SqlClient.dll'. Cannot find or open the PDB file.
Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection:Debug: Opening connection to database 'Northwind' on server '(localdb)\mssqllocaldb'.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Text.Encoding.CodePages.dll'. Cannot find or open the PDB file.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\Microsoft.Win32.Primitives.dll'. Cannot find or open the PDB file.
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [o].[OrderID], [o].[OrderDate], [o].[ShipName], [o].[ShippedDate]
FROM [Orders] AS [o]
Exception thrown: 'System.NullReferenceException' in Microsoft.EntityFrameworkCore.Relational.dll
Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection:Debug: Closing connection to database 'Northwind' on server '(localdb)\mssqllocaldb'.
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Error: An exception occurred in the database while iterating the results of a query.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
Exception thrown: 'System.NullReferenceException' in Microsoft.EntityFrameworkCore.dll
Exception thrown: 'System.NullReferenceException' in Newtonsoft.Json.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.ni.dll

Additional strange line of debug information
```
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Warning: The LINQ expression 'GroupBy([x].ShipName, [x])' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
```
### Further technical details

"Microsoft.EntityFrameworkCore": "1.0.0",
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0"

Operating system:
Windows 7
Visual Studio version: VS 2015 Update 3

**Comment by rowanmiller** [comment]
Possibly due to `ShipName` being null. Any chance you could try it on our current code base, we think it may be fixed - https://www.myget.org/Gallery/aspnetcidev.

**Comment by TerraVenil** [comment]
Nope, it's not related to null value for `ShipName` anyway it should not throw an exception :)
For example, if you are using query like that
```
IQuerable<Order> orders = _orderContext.Orders;

var result = orders
        .Where(x => x.OrderDate < new DateTime(1996, 7, 12) && x.OrderDate > new DateTime(1996, 7, 4))
        .OrderBy(x => x.ShippedDate)
        .GroupBy(x => x.ShipName);

    return Ok(result);
```

it works perfect! So I think it's problem between difference `IEnumerable<T>` and `IQuerable<T>` interfaces.

**Comment by anpete** [comment]
Verified fixed in dev.

**Comment by ellsworthpcx** [comment]
Any suggestions for when this will release or a workaround? I hit this bug about two hours ago...

**Comment by rowanmiller** [comment]
@ellsworthpcx don't have dates for 1.1.0 release as yet, but you could swap to nightly builds if you want https://www.myget.org/Gallery/aspnetcidev
