### ISSUE TITLE
EF Core 1.0 RTM not filtering properly on fields of type char

### ISSUE THREAD

**Issue by iberodev** [aspnet/EntityFramework#5975]
### Steps to reproduce

I have created a Github project for this issue
https://github.com/iberodev/EntityFramework5975
### The issue

Suppose I have a Port entity

```
public class Port
{
    public string Code { get; set; }
    public string Name { get; set; }
}

public class PortMap
{
    public PortMap(EntityTypeBuilder<Port> entityBuilder)
    {
        entityBuilder.HasKey(p => p.Code);

        entityBuilder.Property(p => p.Code)
            .HasColumnType("char(5)");

        entityBuilder.Property(p => p.Name)
            .HasMaxLength(65);
    }
}

```

and the field Code has a `char(5)` type.

and the following data:
Code    Name
AUCNB   Canberra
AUMLB   Melbourne
AUSYD   Sydney
NZAKL   Auckland
NZTRG   Tauranga

if I use Entity to retrieve rows based on a filter (eg: the word `NZ` to retrieve only ports whose code starts with `NZ`), the SQL query Entity generates does not return any results from database.

```
public IEnumerable<Port> GetPortsFilteredInDatabase(string filter = "NZ")
{
    var query = _context.Ports.Where(p => p.Code.StartsWith(filter));
    return query.ToList(); //this list will be empty
}

public IEnumerable<Port> GetPortsFilteredInMemory(string filter = "NZ")
{
    var allPorts = _context.Ports.ToList();
    var query = allPorts.Where(p => p.Code.StartsWith(filter));
    return query.ToList(); //this list is correct
}
```

> Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[@__filter_0='?' (Size = 5)], CommandType='Text', CommandTimeout='30']
> SELECT [p].[Code], [p].[Name]
> FROM [Ports] AS [p]
> WHERE [p].[Code] LIKE @__filter_0 + '%'

Notice the question mark instead the `NZ` text when generating the SQL statement. Is that normal?

This was working fine in EF Core RC2.

Also notice that if instead CHAR(5), my code column is NVARCHAR(5) everything works well.
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10
Visual Studio version: VS2015 update 3

**Comment by iberodev** [comment]
If my filter, instead `NZ`, is `NZAKL` (same lenght as the char(5)) then it returns properly one result. So the question mark in the logs I guess it does not mean what I thought, but still there is an issue here.

**Comment by rowanmiller** [comment]
You could try this as a workaround... `.Where(p => p.Code.StartsWith(filter.Trim()));`

**Comment by divega** [comment]
At least on SQL Server, when we create string parameters we should use the variable length flavors of the types e.g. `NVARCHAR(x)` and `VARCHAR(x)` and not `NCHAR(x)` and `CHAR(x)`, otherwise padding will be added.

**Comment by divega** [comment]
Note that this is likely to impact many databases and providers, but I am not sure there is common implementation code where we could fix it. We can add tests to help providers do the same.
