### ISSUE TITLE
Group by related object is not performing as expected

### ISSUE THREAD

**Issue by shaulbehr** [aspnet/EntityFramework#6078]
I'm simplifying here, but this is the idea:

```
// Invoice has a FK to Customer through CustomerId
var largeInvoices = db.Invoices.Where(i => i.Amount > minAmt);

var groupedByCustomer = 
    largeInvoices.GroupBy(i => i.Customer)
        .Select(g => new { Customer = g.Key, Invoices = g.OrderBy(i => i.Date) })
        .ToList();
```
I would expect one item in the resulting list per customer.  But the actual behavior has multiple records for the same Customer.  I haven't worked out any pattern; the grouping seems to be arbitrary.
When I change the code to this, it works:
```
var groupedByCustomer = 
    largeInvoices.GroupBy(i => i.CustomerId)
        .Select(g => new { Customer = g.Select(i => i.Customer).FirstOrDefault(), Invoices = g.OrderBy(i => i.Date) })
        .ToList();
```
But of course, that's pretty ugly.  Plus I put a sniffer on the DB and found it was doing a select n+1, first querying only the Invoice table, then loading each Customer in turn.

**Comment by smitpatel** [comment]
@shaulbehr - I am not able to reproduce this. Can you provide repro code?

**Comment by shaulbehr** [comment]
I also can't now.  Looks like it was some kind of corner case.  If I repro again I'll post here with more detail.
