### ISSUE TITLE
Be consistent in the exception types thrown by core metadata

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#611]
For very similar cases in core metadata we sometimes throw ArgumentException, sometimes throw InvalidOperationException, and sometimes throw ModelItemNotFoundException. We should decide what the general categories of errors are here and then be consistent in what we throw.

**Comment by AndriySvyryd** [comment]
ModelItemNotFoundException is removed
I propose to throw ArgumentException if the condition is only on the arguments, not any other state, otherwise throw InvalidOperationException
