### ISSUE TITLE
Model Building: StackOverflowException when two properties share the same foreign key

### ISSUE THREAD

**Issue by ntsekouras** [aspnet/EntityFramework#6115]
```
public class FileRecord : RelativeEntity
    {
        public Guid DmsId { get; set; }
        public int EntityId { get; set; }
        public string MimeType { get; set; }
        public FileRecordEntity Entity { get; set; }

        [ForeignKey("EntityId")]
        public virtual Decision Decision { get; set; }
        [ForeignKey("EntityId")]
        public virtual Invitation Invitation { get; set; }
    }
```

Can i have two properties with the same foreign key?

EF Core version: 1.0.0
Operating system: Win10 64
Visual Studio version: VS2015

**Comment by ajcvickers** [comment]
@ntsekouras Yes. Are you seeing an error? If so, please provider error, stack trace, and full repro code.

**Comment by rowanmiller** [comment]
Closing as we have answered the question. If you see an error, reply with details and we will reopen.

**Comment by xrkolovos** [comment]
We get a big exception "dotnet has stopped working"

dotnet : Process is terminated due to StackOverflowException.
At line:1 char:1
+ dotnet ef migrations add filerecordsTest
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Process is term...rflowException.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by xrkolovos** [comment]
The other 2 classes are like this

```
public class Invitation : AuditedEntity
{
    ...
    public List<FileRecord> FileRecords { get; set; }
}
```

We also set up fluent API like this
```
/*          FileRecorts           */
modelBuilder.Entity<FileRecord>()
	.HasOne(r => r.Decision)
	.WithMany(c => c.FileRecords)
	.OnDelete(DeleteBehavior.Restrict);
modelBuilder.Entity<FileRecord>()
	.HasOne(r => r.Invitation)
	.WithMany(c => c.FileRecords)
	.OnDelete(DeleteBehavior.Restrict);
```

**Comment by smitpatel** [comment]
StackOverflow in latest codebase too. Setting `EntityId` as foreign key for one relationship removes the other one and when convention re-discover the other relationship, it will try to use `EntityId` and same thing repeats.

**Comment by ntsekouras** [comment]
Is there a workaround for v1.0 of efcore?

**Comment by AndriySvyryd** [comment]
@ntsekouras You would need to remove the annotations, configure one of the relationships using Fluent API and the other one using Model API:

```C#
modelBuilder.Entity<FileRecord>().HasOne(f => f.Decision).WithMany().HasForeignKey(f => f.EntityId);
modelBuilder.Entity<FileRecord>().Ignore(f => f.Invitation);

var fileRecordEntityType = modelBuilder.Entity<FileRecord>().Metadata;
var invitationEntityType = modelBuilder.Entity<Invitation>().Metadata;
fileRecordEntityType.AddForeignKey(
    new[] { entityType.FindProperty("EntityId") },
    invitationEntityType.FindPrimaryKey(),
    invitationEntityType)
    .HasDependentToPrincipal(typeof(FileRecord).GetTypeInfo().GetDeclaredProperty("Invitation"));
```
