### ISSUE TITLE
Migrations: Script-Migration doesn't revert -From migration

### ISSUE THREAD

**Issue by pamerio** [aspnet/EntityFramework#6126]
In the previous version of EF core one could use Update-Database with the option -Script to generate an SQL Script instead of updating the DB. That way I could generate the script to downgrade a bad migration.
Now the option -script has gone and I'm not sure how to get the same result. 
I tried Script-Migration -From Migration2 -To Migration1 (where Migration2 is newer than Migration1) but no success.
Any hints...?

Thanks

Paolo

**Comment by bricelam** [comment]
It looks like there is a bug (#6228) preventing migrations names form being used with `Script-Migration`. Does it work if you use the full migration ID?

    Script-Migration -From 20160809114400_Migration2 -To 20160809112200_Migration1

**Comment by bricelam** [comment]
It looks like there is another issue here--the `-From` migration isn't reverted. Thus, if you do two consecutive migrations, the revert script is empty.

**Comment by bricelam** [comment]
As a workaround, it looks like you can enter an arbitrary string that is ordinary greater than the desired migration e.g. `20160809114400_zzz`
