### ISSUE TITLE
Commands: Use MSBuild to get project metadata

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#6139]
dotnet-ef uses this to understand the project model. We will need to implement an alternative way of understanding the project system without using API from Microsoft.DotNet.ProjectModel.

Things we need to be able to find from the project model API:

- target framework(s)
- class library or console application
- folder containing compiled output folder
- filename of compiled assembly/executable
- default namespace
- nuget dependencies
- any other project references

**Comment by davidfowl** [comment]
What's the goal?

**Comment by natemcmaster** [comment]
cc @piotrpMSFT

**Comment by davidfowl** [comment]
You'll need the msbuild workspace to work with .NET Core projects so we can use it in our command line tooling.

/cc @DustinCampbell @davkean @jaredpar

**Comment by natemcmaster** [comment]
I've pushed an initial version to the [feature/msbuild](https://github.com/aspnet/EntityFramework/tree/feature/msbuild) branch. This only kinda works if you build and locally install the feature/msbuild branch from the dotnet/cli repo. We'll need to wait for CLI and msbuild-splat churn to settle before we can make much more progress on this.
