### ISSUE TITLE
Better support for no tracking queries

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#617]
Tracking objects for changes introduces overhead, but not all queries require returned objects to be tracked for changes, i.e. not always I am retrieving objects in to memory with the goal of making changes to them and saving them back to the database, so this is an opportunity for optimization. Note that for no tracking queries:

- Results may not fit in memory
- I am only interested in the data, so returning duplicate objects may be ok

In the past, which EF queries would be tracked or not followed some rules, e.g.:

- Projections of non-entity objects were never tracked
- Results of entity types were tracked unless explicitly noted at the query level, e.g. with AsNoTracking()

Other O/RMs take different approaches, e.g.:

1. A context/session-level flag can be used to turn off tracking
2. A separate "stateless" context/session type can be used for no tracking queries

When discussing a design for this we should strive for simple and predictable rules but we should also consider compatibility.

**Comment by divega** [comment]
@rowanmiller @anpete Based on the description of the issue I am not sure we still have a reason to keep it open in the backlog. Perhaps we need to clarify what we mean by "better" or create a new issue that is more specific?

**Comment by anpete** [comment]
This work has been done.

**Comment by divega** [comment]
Thanks.
