### ISSUE TITLE
Relational: Table splitting support

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#619]
This work item represents the mapping capability to slice a single table vertically into multiple objects.

**Comment by strangeattr** [comment]
I'm sorry, I can't find the vote button here but I'd like to vote this up.

I'd also like to add to the feature specification: it should be possible to use a table as a part of more than one entity.

E.g. GUIDS are used as primary keys for all the tables and there is a field that every entity has, so there is a table of 2 columns: the GUID and the common field and a record with equal GUID is created in it for every record created in another table.

**Comment by smitpatel** [comment]
@AndriySvyryd

**Comment by AndriySvyryd** [comment]
Fixed in f5af64f38dc55cb857a5598765c2eb0678ae62a9, 644dec8482805ef4ebf2d6faf4d05a25294bb574

**Comment by wcc-neal** [comment]
The two commits above (f5af64f and 644dec8) only add table splitting. They don't add entity splitting, so this feature request is not complete
