### ISSUE TITLE
NotImplementedException for GroupJoin

### ISSUE THREAD

**Issue by flipchart** [aspnet/EntityFramework#6198]
### Steps to reproduce
See gist https://gist.github.com/flipchart/67e5687ec70ed2673d50803b78f05319

### The issue
	{System.NotImplementedException: The method or operation is not implemented.
	   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.AsyncQueryableAdapter`1.get_Provider()
	   at System.Linq.Queryable.GroupJoin[TOuter,TInner,TKey,TResult](IQueryable`1 outer, IEnumerable`1 inner, Expression`1 outerKeySelector, Expression`1 innerKeySelector, Expression`1 resultSelector)
	   at ConsoleApp1.Program.<>c__DisplayClass1_0.<ExecuteAsync>b__0(<>f__AnonymousType0`2 x) in C:\Bitbucket\ConsoleApp2\src\ConsoleApp1\Program.cs:line 48}

### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10
Visual Studio version: VS2015 (14.0.25424.00 Update 3)

**Comment by anpete** [comment]
@flipchart Thanks for reporting. To workaround you can put a ToList at the end of the first subquery:
```c#
Windows = windows.Where(y => y.House.Id == x.Id).ToList(),
```

**Comment by flipchart** [comment]
Thanks for the workaround. I can confirm that it resolves the exception. However, it does generate two separate SQL statements to gather the data, unlike EF6 which created a single statement (both with the `.ToList()` and without it). I would probably bet that executing it as two separate statements is the way to go, but would want them as a part of the same batch to save round trips. 

Furthermore, it appears to duplicate the SQL calls for each record in the DB. See profile below where there are 14 records in both the `Houses` and `Windows` tables, and note that it duplicates the 

	SELECT [y].[Id], [y].[HouseId], [y.House].[Id]
	FROM [Windows] AS [y]
	LEFT JOIN [Houses] AS [y.House] ON [y].[HouseId] = [y.House].[Id]
	ORDER BY [y].[HouseId]

statement 14 times:

![groupjoin sql profile](https://cloud.githubusercontent.com/assets/1951912/17404584/88a704be-5a5c-11e6-895d-483844cef000.png)

**Comment by anpete** [comment]
@flipchart The reason for multiple queries is that each sub-query in the outer projection is a separate, lazy IEnumerable, that only executes when it is accessed. We have made a change (available in our nightlies) so that the inner queries are properly correlated with the outer row, which fixes the problem where we were returning too much data in the inner queries. We don't currently support query batching as it would require buffering - Our queries are always streaming.

**Comment by anpete** [comment]
Fixed in 9b5f5e3bb
