### ISSUE TITLE
Query :: repeated joins between Includes and nav props

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#6206]
When we apply Include and also access navigation property on the entity that was included, we generate JOINs for to the same table twice. We could potentially be smart about it and only do it once. 

e.g. 

``` cs
ctx.As.Include(a => a.B).Where(a => a.B.Name == "Foo")
```

**Comment by divega** [comment]
@maumar @anpete I see we have some possible overlap or duplication between this bug, #4900, #3816 and #3419. 

Could you please figure out if we can consolidate into a smaller set of orthogonal bugs without loosing information?

**Comment by smitpatel** [comment]
@maumar - Can you do a quick check if this is fixed after new include compiler ?

**Comment by maumar** [comment]
Yes, that is indeed fixed, closing
