### ISSUE TITLE
ArgumentException using same query source for multiple separate queries

### ISSUE THREAD

**Issue by flipchart** [aspnet/EntityFramework#6209]
### Steps to reproduce
Repro gist: https://gist.github.com/flipchart/a0983761f04077381acdfad1965fb6a6

### The issue
	System.ArgumentException: An item with the same key has already been added. Key: join WorkflowRecord _ in {from WorkflowRecord x in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Rublock.Data.DataModel.Workflows.WorkflowRecord]) join WorkflowRecord x.Parent in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Rublock.Data.DataModel.Workflows.WorkflowRecord]) on IIF(([x] != null), Property([x], "ParentId"), null) equals Convert(Property([x.Parent], "Id")) into IEnumerable`1 x.Parent_group from WorkflowRecord x.Parent in {[x.Parent_group] => DefaultIfEmpty()} join AccountRecord x.Owner in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Rublock.Data.DataModel.Accounts.AccountRecord]) on IIF(([x] != null), Property([x], "OwnerId"), null) equals Convert(Property([x.Owner], "Id")) into IEnumerable`1 x.Owner_group from AccountRecord x.Owner in {[x.Owner_group] => DefaultIfEmpty()} where (((IIF(([x.Owner] != null), [x.Owner].Username, null) == __query_Username_0) AndAlso (IIF(([x.Parent] != null), Convert([x.Parent].Id), null) == Convert(__query_WorkflowId_1))) AndAlso ([x].Id == __query_StepId_2)) select [x]} on [x].WorkflowServiceId equals {from WorkflowServiceRecord subQuery in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Rublock.Data.DataModel.Services.WorkflowServiceRecord]) where (Convert(Property([subQuery], "Id")) == Property([_], "ServiceId")) select [subQuery].Id => FirstOrDefault()}
	   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
	   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
	   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.RegisterSubQueryVisitor(IQuerySource querySource, RelationalQueryModelVisitor queryModelVisitor)

### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10
Visual Studio version: VS2015 14.0.25424.00 Update 3

**Comment by maumar** [comment]
verified that this is a legitimate bug

**Comment by maumar** [comment]
We think this is fixed now.

**Comment by maumar** [comment]
This is indeed fixed in the current bits. Currently we produce the following query:

```sql
SELECT [x].[FingerId]
FROM [PersonDefinitionFingerRecord] AS [x]
INNER JOIN (
    SELECT [x1].*
    FROM [PersonRecord] AS [x1]
    WHERE [x1].[Name] = N'Foo'
) AS [t] ON [x].[PersonDefinitionId] = (
    SELECT TOP(1) [subQuery0].[Id]
    FROM [PersonDefinitionRecord] AS [subQuery0]
    WHERE [subQuery0].[Id] = [t].[PersonDefinitionId]
)
WHERE [x].[Discriminator] = N'PersonDefinitionLeftFingerRecord'
```
