### ISSUE TITLE
New Solution Based on Core and Receiving Warning about Both EF6 and Core

### ISSUE THREAD

**Issue by pettechbytes** [aspnet/EntityFramework#6211]
### Steps to reproduce
Create a new solution using Visual Studio 2015 (Update 3) using the default template for Core, ASP.NET, include Identity.  Next, add a project for Repositories (DbContexts) and add the following package:

```
"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.0",
      "type": "build"
    }
``` 

### The issue
When I attempt to call Add-Migration BlahBlah from the Package Manager Console, I receive the following error:

```
Both Entity Framework Core and Entity Framework 6.x commands are installed. The Entity Framework Core version is executing. You can fully qualify the command to select which one to execute, 'EntityFramework\Add-Migration' for EF6.x and 'EntityFrameworkCore\Add-Migration' for EF Core.
```

In my opinion, this message shouldn't appear because I didn't install EF6.

**Comment by divega** [comment]
@natemcmaster can you try to repro with the instructions above and otherwise ask for more details?

**Comment by natemcmaster** [comment]
@pettechbytes none of packages you shared above contain EF 6.x or EF Core package manager console commands. These commands are installed through "EntityFramework" (EF 6.x) and "Microsoft.EntityFrameworkCore.Tools" (EF Core). Can you share the full project.json?

A couple things could be happening. (1) A previously open solution failed to unregister PMC commands when it was closed. (2) You have another project in the solution that has installed the commands. PMC commands are solution-global. (3) You have a pre-release version of EF Core commands installed. Between RC2 and RTM, we renamed the module, which could cause the error. Do any of these scenarios describe your project setup?

**Comment by natemcmaster** [comment]
I'm going to close this for now as I still don't have enough information to reproduce the problem, but feel free to continue to discuss. If we get the info to reproduce the issue, we can reopen for further investigation.

**Comment by pettechbytes** [comment]
Yes, thanks for closing this.  I meant to come back and comment that after refreshing my packages and reloading Visual Studio, the message disappeared.
