### ISSUE TITLE
Explicit loading support

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#625]
Explicitly triggering the loading of associated data through a navigation can be handy especially when loading across aggregate bondaries or when working with stores that are not natively [aggregate oriented](http://martinfowler.com/bliki/AggregateOrientedDatabase.html). In previous versions of EF we had such methods as Load() and LoadAsync() on reference and collection property entries. We also had handy Query() methods that returned the query we would use to load the data so that filters could be composed over them before executing them. We should have the equivalent functionality in EF7.

**Comment by mjrousos** [comment]
+1; I've recently been porting some old EF6 code which used lazy loading and while I'm ok with not using lazy loading in the new world, some of the models are too large to entirely eagerly load. Instead, I have to explicitly load related objects as they're needed. Having first-class support for this with APIs like Load() and LoadAsync() would make porting easier.

**Comment by nocommonsense** [comment]
+1 for this

**Comment by arielcloud** [comment]
The docs [here](https://ef.readthedocs.io/en/latest/querying/related-data.html#explicit-loading) reference this issue.
if u close this it means the issue solved? if so - can u fix the docs? thanks!

**Comment by rowanmiller** [comment]
@arielcloud it's fixed in our working code base, but not in the current stable release. We will update the docs when this is released in 1.1.

**Comment by RickStrahl** [comment]
Looking at this it occurs to me that it would be nice to have a model attribute that would allow you to specify that related entities or collections should always be included. This would greatly mitigate the need for lazy or even explicit loading in many situations. 

It'd be nice if you could just say:

```csharp
public class album
{
    ...
    [Include]
    public Artist Artist {get; set;}

    [Include]
    public Track[] Tracks {get; set; }
}
````

**Comment by divega** [comment]
@RickStrahl I think that is covered by #1985, but please let us know if you have additional feedback.

**Comment by RickStrahl** [comment]
Thank you. Yup that looks like it would work. 

These options will make life a lot easier for generic code in base repositories.
