### ISSUE TITLE
Add direct dependency of UWP metapackage for uap10.0

### ISSUE THREAD

**Issue by alpaix** [aspnet/EntityFramework#6255]
### Scenario
Installing EFCore in Universal Windows App fails when using default `Blank App` template. The error NuGet displays is not actionable:
<pre>
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
</pre>

The only way to resolve this error is upgrading `Microsoft.NETCore.UniversalWindowsPlatform` metapackage to 5.2.2 from "default" 5.1.0. Unfortunately user won't be given any guidance on that workaround.

### Suggested Solution
Consider adding direct UWP dependency to EFCore nupkg:
```xml
      <group targetFramework="UAP,Version=v10.0">
        <dependency id="Microsoft.NETCore.UniversalWindowsPlatform" version="5.2.2" />
        <dependency id="Remotion.Linq" version="2.1.1" />
      </group>
```
With this declaration installing EFCore with 5.1.0 would reveal "downgrade" warnings:
<pre>
Restoring packages for 'App6'.
Restoring packages for c:\users\alpanov\documents\visual studio 15\Projects\App6\App6\project.json...
Installing Microsoft.EntityFrameworkCore 1.0.1-uap-1.
Detected package downgrade: Microsoft.NETCore.UniversalWindowsPlatform from 5.2.2 to 5.1.0 
 App6 (>= 1.0.0) -> Microsoft.EntityFrameworkCore (>= 1.0.1-uap-1) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) 
 App6 (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.1.0)
</pre>
This would help a user understand what blocks the package installation.

Apart from that nuget.org and VS Package Manager UI would show framework dependency information (see the right bottom lines):

![image](https://cloud.githubusercontent.com/assets/8239356/17451849/c39ce45e-5b1e-11e6-8350-51308610381c.png)

**Comment by natemcmaster** [comment]
For EF Triage: @alpaix and I discussed this offline before he opened the issue. Although I haven't verified this will work, it appears this requires no code change, just nuspec updates. This could be a good candidate for 1.0.1

**Comment by divega** [comment]
@natemcmaster in triage we think we should not do this in 1.0.1 but in 1.1.0. We can discuss in person if you want to provide more details.

**Comment by natemcmaster** [comment]
@divega depending on when we release 1.1.0, we may not really need this much. VS is expected to update templates soon to use the 5.2.x versions.

**Comment by bricelam** [comment]
Closing this. The next version of the templates will ship with a dependency on `5.2.2` anyway.
