### ISSUE TITLE
Expose way to get simple, human-readable, representation of the model for debugging

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#6304]
There are some internal APIs called ToDebugString that allow a model to be dumped out in a form like this:
```
Model 1.1.0-csproj
  Game
    Properties: 
      Id (<Id>k__BackingField, int) Required PK ReadOnlyAfterSave RequiresValueGenerator ValueGenerated.OnAdd 0 0 0 -1 0
    Navigations: 
      Items (<Items>k__BackingField, ICollection<Item>) Collection ToDependent Item Inverse: Game 1 -1 1 -1 -1
      Levels (<Levels>k__BackingField, ICollection<Level>) Collection ToDependent Level Inverse: Game 2 -1 2 -1 -1
    Keys: 
      Id PK
  Item
    Properties: 
      Id (<Id>k__BackingField, int) Required PK ReadOnlyAfterSave RequiresValueGenerator ValueGenerated.OnAdd 0 0 0 -1 0
      GameId (<GameId>k__BackingField, int) Required FK Index 1 1 1 -1 1
      LevelId (<LevelId>k__BackingField, int) Required FK Index 2 2 2 -1 -1
    Navigations: 
      Game (<Game>k__BackingField, Game) ToPrincipal Game Inverse: Items 3 -1 3 -1 -1
      Level (<Level>k__BackingField, Level) ToPrincipal Level Inverse: Items 4 -1 4 -1 -1
    Keys: 
      Id PK
    Foreign keys: 
      GameId -> Game.Id ToDependent: Items ToPrincipal: Game
      GameId, LevelId -> Level.GameId, Level.Id ToDependent: Items ToPrincipal: Level
  Level
    Properties: 
      GameId (<GameId>k__BackingField, int) Required PK FK Index ReadOnlyAfterSave 0 0 0 -1 0
      Id (<Id>k__BackingField, int) Required PK ReadOnlyAfterSave 1 1 1 -1 -1
    Navigations: 
      Game (<Game>k__BackingField, Game) ToPrincipal Game Inverse: Levels 2 -1 2 -1 -1
      Items (<Items>k__BackingField, ICollection<Item>) Collection ToDependent Item Inverse: Level 3 -1 3 -1 -1
    Keys: 
      GameId, Id PK
    Foreign keys: 
      GameId -> Game.Id ToDependent: Levels ToPrincipal: Game
```

This is indented to be a relatively terse and not necessarily complete form useful for debugging the model. It is not intended as a serialization format.

We should consider if something like this should be made public, and if so what form it should take.

**Comment by divega** [comment]
**Triage:** We think this can be useful and @ajcvickers is going to investigate if this can be shown in the debugger automatically without introducing much overhead.

**Comment by ajcvickers** [comment]
My goal was to have the human readable format available to anybody using the debugger, but in such a way that it is only created on-demand, since creating the view for a very large model can be quite expensive resulting in latency in the debugger and memory usage. I was not able to find anything that would do this using VS attributes, etc., without installing third-party stuff. However, I did come up with this: create a level of indirection in code:
```C#
// Note that Model is internal
public class Model
{
    ...
    public virtual DebugView<Model> DebugView
        => new DebugView<Model>(this, m => m.ToDebugString());
}

// Internal
public class DebugView<T>
{
    private readonly T _metadata;
    private readonly Func<T, string> _toDebugString;
    private string _view;

    public DebugView(T metadata, Func<T, string> toDebugString)
    {
        _metadata = metadata;
        _toDebugString = toDebugString;
    }

    public virtual string View => _view ?? (_view = _toDebugString(_metadata));
}
```
So now when I expand Model in the debugger I get this:
![image](https://cloud.githubusercontent.com/assets/1430078/17817854/82e110fc-65f5-11e6-9353-865b738dbd3c.png)

Note that the debug view of the model has not yet been created, so there is minimal additional overhead. But if I want to see the debug view, then I just expand out the property, at which point the view will be created.
![image](https://cloud.githubusercontent.com/assets/1430078/17817886/a1e22586-65f5-11e6-97a4-957b132253e2.png)
![image](https://cloud.githubusercontent.com/assets/1430078/17817909/b6d9860a-65f5-11e6-9abf-d25b4cbfb27e.png)
Stepping over a piece of code that causes the model to be updated causes the view to be re-created:
![image](https://cloud.githubusercontent.com/assets/1430078/17817950/ebc8350a-65f5-11e6-8ffe-55ae1d207d63.png)
