### ISSUE TITLE
Consider auto-initializing collection navigation properties when materializing entities and in other scenarios

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#638]
Change #637 fixes all known cases in which we currently throw NullReferenceException from our stack due to uninitialized navigation collections. E.g. it stops trying to iterate over the contents of collections when the collections themselves are null and it auto-initializes the collections when we need to add items to them. 

This issue is about initializing collections more consistently so customers don't need to initialize the collections everywhere to avoid NullReferenceExceptions from being thrown from application code. There are several places in which doing this could make sense:

1. Materialization
2. Simple creation, e.g. db.Set<TEntity>().Create<TDerivedEntity>()
3. Attachment, i.e. any time we start tracking entities

Creation of navigation properties happens on a best effort basis, e.g. we have convention that looks for specific types, specific constructors and specific patterns on the parent class, e.g. collection setters. We should decided what to do when we can't figure out the right type, constructor and setting mechanism, and whether we can factor this as a service.

**Comment by rowanmiller** [comment]
Decided we should just do 1 from the initial list (reactivated https://github.com/aspnet/EntityFramework/issues/451 to track this).
2 doesn't apply (DbSet.Create doesn't exist)
We're not sure 3 is a good idea
