### ISSUE TITLE
Commands: Add IDbContextFactory

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#639]
Both the Scaffolding and Migrations tools need to construct `DbContext` objects at design-time. We need to figure out which constructors we'll be able to support and how we'll build up the service provider and options to use.

This loosely correlates to the the interactions between the `DbContextInfo`, `IDbContextFactory<TContext>` & `DbConfiguration` classes in EF6.

**Comment by bricelam** [comment]
Partially blocked on https://github.com/aspnet/Hosting/issues/85

**Comment by bricelam** [comment]
Related StackOverflow question: [How do you configure the DbContext when creating Migrations in Entity Framework 7?](http://stackoverflow.com/q/29110241/475031)

**Comment by glen-84** [comment]
Will this allow you to do something like:

`services.Configure<ApplicationDbContext>(c => c.Set<Tag>());`

... and have the Tag set be visible to the migration commands?

**Comment by bricelam** [comment]
(Additional notes)

There are a lot of interacting parts here:
* The project on which the command is invoked
    * Migrations in this assembly
    * Contexts in this assembly
    * Contexts referenced by the migrations
* The startup project
    * Contexts in this assembly
    * Contexts registered services
* The migrations assembly as configured by the context
    * Migrations in this assembly

**Comment by bricelam** [comment]
See also the [September 17, 2015 Design Meeting Notes](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes-(September-17,-2015)#design-time-services).
