### ISSUE TITLE
Cascade behaviour not as I expected

### ISSUE THREAD

**Issue by mikebrind** [aspnet/EntityFramework#6398]
### Steps to reproduce

Here's a model with an optional relationship between `Property` and `Tenant`:

``` csharp
public class LettingsContext : DbContext
{
    public DbSet<Property> Properties { get; set; }
    public DbSet<Tenant> Tenants { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Lettings;Trusted_Connection=True;MultipleActiveResultSets=true");
    }
}

public class Tenant
{
    public int TenantId { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public int? PropertyId { get; set; }
    public Property Property { get; set; }
}

public class Property
{
    public int PropertyId { get; set; }
    public string Address { get; set; }
    public List<Tenant> Tenants { get; set; }
}
```
### The issue

When I create a migration, I would expect to see the `ReferentialAction` set to `SetNull` for the `onDelete` parameter of the `PropertyId` foreign key in the Tenants table, but it is defined as `Restrict`:

``` csharp
migrationBuilder.CreateTable(
    name: "Tenants",
    columns: table => new
    {
        TenantId = table.Column<int>(nullable: false)
            .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
        Email = table.Column<string>(nullable: true),
        Name = table.Column<string>(nullable: true),
        PropertyId = table.Column<int>(nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Tenants", x => x.TenantId);
        table.ForeignKey(
            name: "FK_Tenants_Properties_PropertyId",
            column: x => x.PropertyId,
            principalTable: "Properties",
            principalColumn: "PropertyId",
            onDelete: ReferentialAction.Restrict);
    });
```

Which then translates to `NO ACTION` for SQL Server:

``` sql
CONSTRAINT [FK_Tenants_Properties_PropertyId] 
FOREIGN KEY ([PropertyId]) 
REFERENCES [Properties] ([PropertyId]) 
ON DELETE NO ACTION
```

My expectation is based on the docs here: [https://ef.readthedocs.io/en/latest/modeling/relationships.html#cascade-delete](https://ef.readthedocs.io/en/latest/modeling/relationships.html#cascade-delete). Why doesn't this work as I expect? Is some additional configuration required? Or have I misunderstood something?

```
Exception message:
Stack trace:
```
### Further technical details

EF Core version: 1.0
Microsoft.EntityFrameworkCore.Tools version: 1.0.0-preview2-final

**Comment by ajcvickers** [comment]
@mikebrind The documentation is not correct. We had originally intended to do this, but the problem is that it causes errors in so many cases when using SQL Server. See this PR: #3311

**Comment by mikebrind** [comment]
So the behaviour, and possible solutions, are the same as for EF6?

**Comment by ajcvickers** [comment]
Sorry, I thought the docs said this, but I don't see it. EF Core supports the SetNull behavior:
```C#
modelBuilder.Entity<Tenant>()
    .HasOne(p => p.Property)
    .WithMany(b => b.Tenants);
    .OnDelete(DeleteBehavior.SetNull);
```
It just isn't on by default. It should work fine with your posted code. If you are using SQL Server and have other relationships, then SQL Server might start complaining about cycles. In those cases the workaround is the same as for EF6--switch it off in the database and always make sure all related entities are loaded so that the cascade behavior is all done client-side.

**Comment by mikebrind** [comment]
I was beginning to question my sanity. The PR you referenced appeared to show that it had been included, but I was expecting it to show that it had been removed (or canned or something other than included) based on your earlier comment. Consequently, it made no sense to me at all.

Thanks for the update.

**Comment by ajcvickers** [comment]
Re-opening as there is a documentation bug.

**Comment by divega** [comment]
@rowanmiller this is a docs bug.

**Comment by Ponant** [comment]
It might be a good idea to include intellisense describing what the enum ReferentialAction does, too.

**Comment by rowanmiller** [comment]
PR for docs is out https://github.com/aspnet/EntityFramework.Docs/pull/308

**Comment by rowanmiller** [comment]
Fixed n https://github.com/aspnet/EntityFramework.Docs/commit/fdddb6ab55ae31ac82f5333add30bbfbea5717b0
