### ISSUE TITLE
Support for DateAdd

### ISSUE THREAD

**Issue by johnkwaters** [aspnet/EntityFramework#6402]
### Steps to reproduce

I am trying to write a query where I want to return records where a child entity in a detail record has a data that is 10 years later than a field in it's parent. Instead of doing that, EF loops sending a bunch of additional queries.
### The issue

p is the main object, p.StatusChanges the child:

``` c#
qry = qry.Where(p => 
    p.ProjectStatusId == cid &&
    p.IsUnderLitigation && p.LitigationEndDate != null && 
    p.StatusChanges.Any(psc => psc.ToStatusId == cid && 
        psc.ModifiedOn <= p.LitigationEndDate.Value.AddYears(-10))));
```
### Further technical details

If I comment out the 

``` c#
    p.StatusChanges.Any(psc => psc.ToStatusId == cid && 
        psc.ModifiedOn <= p.LitigationEndDate.Value.AddYears(-10))
```

I get the correct query

``` SQL
SELECT [p].[Id], [p].[AjeraClientType], [p].[AlertText], [p].[BillingContactId], [p].[BillingSpecialInstructions], [p].[CPR], [p].[CTR], [p].[ClientId], [p].[ConsolidatedDate], [p].[Description], [p].[ECPR], [p].[ECTR], [p].[EFLocation], [p].[EmailInvoice], [p].[EstimatedFee], [p].[HasAlert], [p].[HasMarketingMaterials], [p].[HasNonBarcodedContractDocs], [p].[HasProjectSummary], [p].[HasRequiredNotes], [p].[IsDestroyedDateUnknown], [p].[IsPaperFileCreated], [p].[IsPaperFileMissing], [p].[IsPurgedDateUnknown], [p].[IsReoccurring], [p].[IsThinned], [p].[IsUnderLitigation], [p].[LastPaperFileMissingDate], [p].[Latitude], [p].[LitigationEndDate], [p].[LitigationStartDate], [p].[Longitude], [p].[MarketingFolderLocation], [p].[MarketingProjectNumber], [p].[ProjectBudget], [p].[ProjectHomeOfficeId], [p].[ProjectStatusId], [p].[PurchaseOrder], [p].[SpecialInstructions], [p].[SubmissionDate], [p].[Year], [p0].[Id], [p0].[ColorARGB], [p0].[Name], [c].[Id], [c].[Name], [c].[PreviousName]
FROM [Project] AS [p]
INNER JOIN [ProjectStatus] AS [p0] ON [p].[ProjectStatusId] = [p0].[Id]
INNER JOIN [Client] AS [c] ON [p].[ClientId] = [c].[Id]
WHERE (EXISTS (
    SELECT 1
    FROM [Folder] AS [f]
    WHERE ([f].[OfficeId] = @__q_OfficeId_Value_0) AND ([p].[Id] = [f].[ProjectId])) OR EXISTS (
    SELECT 1
    FROM [EFolder] AS [ef]
    WHERE ([ef].[OfficeId] = @__q_OfficeId_Value_1) AND ([p].[Id] = [ef].[ProjectId]))) AND ((([p].[ProjectStatusId] = 3000) AND (([p].[IsUnderLitigation] = 0) AND EXISTS (
    SELECT 1
    FROM [ProjectStatusChange] AS [psc]
    WHERE (([psc].[ToStatusId] = 3000) AND ([psc].[ModifiedOn] <= @__cutoff_2)) AND ([p].[Id] = [psc].[ProjectId])))) OR (([p].[IsUnderLitigation] = 1) AND [p].[LitigationEndDate] IS NOT NULL))
ORDER BY [p].[Id] DESC
OFFSET @__p_3 ROWS FETCH NEXT @__p_4 ROWS ONLY
```

If I uncomment it I get this 

``` SQL
SELECT [p].[Id], [p].[AjeraClientType], [p].[AlertText], [p].[BillingContactId], [p].[BillingSpecialInstructions], [p].[CPR], [p].[CTR], [p].[ClientId], [p].[ConsolidatedDate], [p].[Description], [p].[ECPR], [p].[ECTR], [p].[EFLocation], [p].[EmailInvoice], [p].[EstimatedFee], [p].[HasAlert], [p].[HasMarketingMaterials], [p].[HasNonBarcodedContractDocs], [p].[HasProjectSummary], [p].[HasRequiredNotes], [p].[IsDestroyedDateUnknown], [p].[IsPaperFileCreated], [p].[IsPaperFileMissing], [p].[IsPurgedDateUnknown], [p].[IsReoccurring], [p].[IsThinned], [p].[IsUnderLitigation], [p].[LastPaperFileMissingDate], [p].[Latitude], [p].[LitigationEndDate], [p].[LitigationStartDate], [p].[Longitude], [p].[MarketingFolderLocation], [p].[MarketingProjectNumber], [p].[ProjectBudget], [p].[ProjectHomeOfficeId], [p].[ProjectStatusId], [p].[PurchaseOrder], [p].[SpecialInstructions], [p].[SubmissionDate], [p].[Year]
FROM [Project] AS [p]
WHERE EXISTS (
    SELECT 1
    FROM [Folder] AS [f]
    WHERE ([f].[OfficeId] = @__q_OfficeId_Value_0) AND ([p].[Id] = [f].[ProjectId])) OR EXISTS (
    SELECT 1
    FROM [EFolder] AS [ef]
    WHERE ([ef].[OfficeId] = @__q_OfficeId_Value_1) AND ([p].[Id] = [ef].[ProjectId]))
```

Followed by a long series of these:

``` SQL
SELECT [psc1].[ProjectId]
FROM [ProjectStatusChange] AS [psc1]
WHERE ([psc1].[ToStatusId] = 3000) AND ([psc1].[ModifiedOn] <= @__cutoff_2)

SELECT [psc1].[ProjectId]
FROM [ProjectStatusChange] AS [psc1]
WHERE ([psc1].[ToStatusId] = 3000) AND ([psc1].[ModifiedOn] <= @__cutoff_2)

SELECT [psc1].[ProjectId]
FROM [ProjectStatusChange] AS [psc1]
WHERE ([psc1].[ToStatusId] = 3000) AND ([psc1].[ModifiedOn] <= @__cutoff_2)

SELECT [psc1].[ProjectId]
FROM [ProjectStatusChange] AS [psc1]
WHERE ([psc1].[ToStatusId] = 3000) AND ([psc1].[ModifiedOn] <= @__cutoff_2)
```

...

**Comment by ErikEJ** [comment]
Where does the paging in the first query come from?

**Comment by johnkwaters** [comment]
There is a generic helper method that adds sorting and paging to all queries.

        public async Task<IEnumerable<ProjectLite>> SearchAsync(ProjectQuery q)
        {
            var qry = MakeProjectQuery(q, MakeBaseProjectQuery());
            AddDefaultSort(q, defaultAsc: false);
            qry = QueryHelper<DbProject>.ApplySortingPaging(qry, q);
            var res = await qry.ToListAsync();
            return Mapper.Map<IEnumerable<ProjectLite>>(res);
        }

See class here

    public static class QueryHelper<T>
    {
        public static IQueryable<T> ApplySortingPaging(IQueryable<T> qry, QueryBase q)
        {
            if (q.SortDescriptors != null && q.SortDescriptors.Any())
            {
                foreach (var sd in q.SortDescriptors)
                {
                    qry = sd.Ascending ? qry.OrderByProperty(sd.FieldName) : qry.OrderByPropertyDescending(sd.FieldName);
                }                
            }
            if (q.PageNo == 0 && q.PageSize == 0)
            {
                return qry;
            }
            return qry.Skip(q.PageNo * q.PageSize).Take(q.PageSize);
        }
    }

    public static class SortingHelper
    {
        private static readonly MethodInfo OrderByMethod =
            typeof(Queryable).GetMethods().Single(method =>
           method.Name == "OrderBy" && method.GetParameters().Length == 2);

        private static readonly MethodInfo OrderByDescendingMethod =
            typeof(Queryable).GetMethods().Single(method =>
           method.Name == "OrderByDescending" && method.GetParameters().Length == 2);

        public static bool PropertyExists<T>(string propertyName)
        {
            return typeof(T).GetProperty(propertyName, BindingFlags.IgnoreCase |
                BindingFlags.Public | BindingFlags.Instance) != null;
        }

        public static MemberExpression NestedExpressionProperty(Expression expression, string propertyName)
        {
            var parts = propertyName.Split('.');
            var partsL = parts.Length;

            return (partsL > 1)
                ?
                Expression.Property(
                    NestedExpressionProperty(
                        expression,
                        parts.Take(partsL - 1)
                            .Aggregate((a, i) => a + "." + i)
                    ),
                    parts[partsL - 1])
                :
                Expression.Property(expression, propertyName);
        }

        public static IQueryable<T> OrderByProperty<T>(
           this IQueryable<T> source, string propertyName)
        {
            var paramterExpression = Expression.Parameter(typeof(T));
            Expression orderByProperty = NestedExpressionProperty(paramterExpression, propertyName);
            var lambda = Expression.Lambda(orderByProperty, paramterExpression);
            var genericMethod =
              OrderByMethod.MakeGenericMethod(typeof(T), orderByProperty.Type);
            var ret = genericMethod.Invoke(null, new object[] { source, lambda });
            return (IQueryable<T>)ret;
        }

        public static IQueryable<T> OrderByPropertyDescending<T>(
            this IQueryable<T> source, string propertyName)
        {

            var paramterExpression = Expression.Parameter(typeof(T));
            Expression orderByProperty = NestedExpressionProperty(paramterExpression, propertyName);
            var lambda = Expression.Lambda(orderByProperty, paramterExpression);
            var genericMethod =
              OrderByDescendingMethod.MakeGenericMethod(typeof(T), orderByProperty.Type);
            var ret = genericMethod.Invoke(null, new object[] { source, lambda });
            return (IQueryable<T>)ret;
        }
    }

**Comment by mj1856** [comment]
Shouldn't you be using `EntityFunctions.AddYears` for this?

**Comment by johnkwaters** [comment]
Sounds great - where is that in EF core?

Sent from my iPhone



Sent from my iPhone
On Aug 27, 2016, at 3:13 PM, Matt Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Shouldn't you be using EntityFunctions.AddYears for this?

**Comment by johnkwaters** [comment]
I worked around it for now by creating a view that does the heaving lifting, but I sure miss those EntityFunctions!
