### ISSUE TITLE
Memory-optimized table support for Sql Server

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#6405]
Provide fluent API:
``` C#
modelBuilder.Entity<Product>().ForSqlServerIsMemoryOptimized();
```

For on-premise SQL Server a file in a memory-optimized filegroup needs to be added to the database. We will dynamically create it in the migration if it doesn't exist.

The default durability is `SCHEMA_AND_DATA` we will _not_ provide an API to change it to `SCHEMA_ONLY`. Likewise we won't have API to set `MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT` to false. Both can be accomplished by editing the migration.

A convention will set indexes to be nonclustered on memory-optimized tables. But the computed columns will will be up to the user to remove.

See https://msdn.microsoft.com/en-us/library/dn133165.aspx for more info on memory-optimized tables. And https://msdn.microsoft.com/en-us/library/dn246937.aspx for detailed description of limitations of memory-optimized tables.

**Comment by AndriySvyryd** [comment]
@bricelam, @ajcvickers, @anpete, @divega This is what the SQL to 'seamlessly' create the necessary database file and filegroup would look like:
``` SQL
IF SERVERPROPERTY('EngineEdition') <> 5 
	BEGIN
	IF NOT EXISTS (SELECT * FROM [MemoryOptimizedContext].sys.filegroups FG JOIN [MemoryOptimizedContext].sys.database_files F ON FG.data_space_id = F.data_space_id WHERE FG.type = 'FX' AND F.type = 2)
		BEGIN
		DECLARE @path NVARCHAR(MAX), @filename NVARCHAR(MAX), @folder NVARCHAR(MAX), @new_path NVARCHAR(MAX), @fg_name NVARCHAR(MAX)
		SELECT TOP(1) @path = physical_name FROM [MemoryOptimizedContext].sys.database_files WHERE charindex('\', physical_name) > 0 ORDER BY file_id
		SELECT TOP(1) @fg_name = name FROM [MemoryOptimizedContext].sys.filegroups WHERE type = 'FX'
		SET @filename = right(@path, charindex('\', reverse(@path)) - 1)
		SET @folder = left(@path, len(@path) - len(@filename))
		SET @filename = left(@filename, len(@filename) - charindex('.', reverse(@filename)))

		if @fg_name IS NULL
			BEGIN
			SET @fg_name = @filename + '_FG'
			EXEC(N'ALTER DATABASE [MemoryOptimizedContext]
				ADD FILEGROUP [' + @fg_name + '] CONTAINS MEMORY_OPTIMIZED_DATA;')
			END
	
		SET @filename = @filename + '_MOD'
		SET @new_path = @folder + @filename
		EXEC(N'ALTER DATABASE [MemoryOptimizedContext]
			ADD FILE (NAME=''' + @filename + ''', filename=''' + @new_path + ''')
			TO FILEGROUP [' + @fg_name + ']')
		END
	END
```

**Comment by divega** [comment]
cc @jodebrui un case he can think of anything else we could do with the filegroup.

**Comment by ErikEJ** [comment]
Should it not be: 

   IF SERVERPROPERTY('IsXTPSupported')  = 1

**Comment by AndriySvyryd** [comment]
@ErikEJ we don't want to run this on SQL Azure, but it's a good suggestion, so I'll add it to the condition

**Comment by jodebrui** [comment]
Looks good. For reference, I created a similar script, that adds a filegroup if it's not there (in SQL Server) and configures recommended DB settings:
https://github.com/Microsoft/sql-server-samples/blob/master/samples/features/in-memory/t-sql-scripts/enable-in-memory-oltp.sql

What is your plan for recommended settings? I always recommend:
- MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = ON
- DB compat level at least 130 (for SQL2016 and Azure DB)

**Comment by AndriySvyryd** [comment]
@jodebrui Added `MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = ON`. At the moment the are no plans to check the compat level, unless we get user feedback

**Comment by jodebrui** [comment]
Sounds good. Thanks.
Yeah, with compat level you usually want to be careful, so may not want to change it automatically.
