### ISSUE TITLE
Breaking change in 1.0.1 - causing the SQL CE provider to break

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#6420]
### Steps to reproduce
Get the latest build of 1.0.1-rtm from myget feed and use in EFCore.SqlCe provider
Build, expecting the build to pass (no breaking changes)
### The issue
The build breaks, as the FindProperty method on MigrationsSqlBuilder is no longer available, but replaced with FindProperties

https://github.com/aspnet/EntityFramework/commit/82fdf18aeed4d061cb70535a4aab9310d5520ada

### Further technical details

EF Core version: 1.0.1-rtm-201608241155
Operating system: Windows 10
Visual Studio version: VS 2015 Update 3

**Comment by divega** [comment]
Thanks @ErikEJ for the heads up on this one.

**Comment by bricelam** [comment]
I double-checked, and this is the only non-Internal API we've changed in 1.0.1.

**Comment by divega** [comment]
We ended up finding a few additional binary compatibility breaks in types in internal namespaces. We have a fix for all of them in https://github.com/aspnet/EntityFramework/pull/6430. 

@ErikEJ thanks a lot of reporting this.

**Comment by divega** [comment]
Closing as fixed. CC @bricelam in case there was something else left to do.
