### ISSUE TITLE
LINQ expressions using ICollection navigation property evaluates locally

### ISSUE THREAD

**Issue by skimmilk** [aspnet/EntityFramework#6439]
### Steps to reproduce
Take a look at [this solution](https://github.com/skimmilk/TrivialQueryFail) to find the full code.

In short, the following expression cannot be compiled to SQL

``` C#
                var fail = (from p in context.Parents
                            where p.ParentId > 10 && p.ParentId < 50
                            select p.Children.ToList()).ToList();
``` 

### The issue
The above expression produces this warning:
> The LINQ expression '(Property([p], "ParentId") == Property([c], "ParentId"))' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.

### Further technical details

EF Core version: 1.0.0, Sqlite provider
Operating system: Windows 10
Visual Studio version: VS2015

**Comment by maumar** [comment]
This has been fixed in https://github.com/aspnet/EntityFramework/issues/5738

Currently we produce the following:

```sql
SELECT [p].[ParentId]
FROM [Parents] AS [p]
WHERE ([p].[ParentId] > 10) AND ([p].[ParentId] < 50)
```

and then for each Parent that meets the predicate:

```sql
SELECT [c].[ChildId], [c].[ParentId]
FROM [Children] AS [c]
WHERE @_outer_ParentId = [c].[ParentId]
```

Basically, we still produce N+1 queries, but only fetch the right data. Issue regarding N+1 queries is tracked here: https://github.com/aspnet/EntityFramework/issues/4007
