### ISSUE TITLE
Query: support conditional expressions

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#649]
E.g. db.Products.Select(p => new {p.Name, IsExpensive = p.Price >  100});

**Comment by divega** [comment]
Assigning to @maumar since he is already working on a few issue that we think are related.

**Comment by smitpatel** [comment]
We have support for conditional expressions in where clause already. #4141 adds support in projection.

**Comment by anpete** [comment]
@smitpatel This one is projection, too.
