### ISSUE TITLE
Initial Migration:  cannot scaffold literals of type 'System.Collections.Immutable.ImmutableSortedDictionary`

### ISSUE THREAD

**Issue by byatis** [aspnet/EntityFramework#6520]
Hi! 

I've mostly ported quite complicated EF6 project to EF 1.0 Core. Have to use alpha1 though, because I need CurrentValues. I can't create my initial migration though.  I have no idea what this error means, or where I should start looking. The project is so large I can't copy all the code here either, just let me know which place to look at and I try to get you the code.

### Steps to reproduce
C:\devel\project\dotnet ef migrations add "Initial-Migration" --context MyDataContext

Project MyProject (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
System.InvalidOperationException: The current CSharpHelper cannot scaffold literals of type 'System.Collections.Immutable.ImmutableSortedDictionary`2[System.Reflection.PropertyInfo,System.Type]'. Configure your services to use one that can.
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotation(IAnnotation annotation, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityTypeAnnotations(IEntityType entityType, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityType(String builderName, IEntityType entityType, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityTypes(String builderName, IReadOnlyList`1 entityTypes, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String builderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetMod
el)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String environment, Action`1 reporter)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
The current CSharpHelper cannot scaffold literals of type 'System.Collections.Immutable.ImmutableSortedDictionary`2[System.Reflection.PropertyInfo,System.Type]'. Configure your services to use one that can.

### Further technical details

EF Core version: 1.1.0-alpha1-22125
Operating system: Windows 7
Visual Studio version: VS 2015

**Comment by rowanmiller** [comment]
@AndriySvyryd could this be an `ImmutableSortedDictionary` annotation that is being added during model building?

**Comment by rowanmiller** [comment]
@AndriySvyryd can you sync with @bricelam on this one

**Comment by AndriySvyryd** [comment]
@byatis Could you share the minimal model that you get this error with?

**Comment by byatis** [comment]
Hi!

Sorry it took while to answer, it took some time to strip the code of all the nonsense.
Here is the simplified model with this error. 

It could be my misconfiguration since I've used to annotations, and had to convert these to fluent API, but at least the error could be more informative :)
[MyDataContext.zip](https://github.com/aspnet/EntityFramework/files/471536/MyDataContext.zip)

**Comment by AndriySvyryd** [comment]
@byatis Thanks. Though I don't get the error. Can you ensure that you are also using the latest version of Microsoft.EntityFrameworkCore.Tools ? It should be something like 1.0.0-preview3-21859
If that's the case please also post your project.json

**Comment by byatis** [comment]
@AndriySvyryd I was using old tooling, but updating to 21859 ( which wanted to upgrade Design  to  "Microsoft.EntityFrameworkCore.Design": "1.0.0-preview3-22135") causes another crash. Project builds fine, but trying to add migration results in:
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Th
e system cannot find the file specified.
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

Something is still using older Design.Core I think...
Here's my project json
[project.zip](https://github.com/aspnet/EntityFramework/files/473947/project.zip)

Where can I found what is the latest build versions for Tooling and Design? Thanks for help.

**Comment by AndriySvyryd** [comment]
@byatis This is probably because NuGet doesn't resolve prerelease dependencies in the expected way. Since EntityFrameworkCore and AspNetCore share many dependencies you'd need to use the prerelease versions for all of them. Generally specifying `1.1.0-*` for runtime packages and `1.0.0-*` for design and tooling should get you the correct set of packages. If it still fails try resetting the NuGet cache: `nuget locals all -clear`

[project.json.txt](https://github.com/aspnet/EntityFramework/files/475495/project.json.txt)

**Comment by byatis** [comment]
@AndriySvyryd  Sorry if I'm causing you a headache, but still can't add migrations. Nuget command didn't help either.

Even if I do a completely new project using project json you posted and don't add the context to it yet:

c:\Users\me\Documents\Visual Studio 2015\Projects\EFBugTest\src\newtest>dotnet new
Created new C# project in c:\Users\niemite\Documents\Visual Studio 2015\Projects\EFBugTest\src\newtest.

c:\Users\me\Documents\Visual Studio 2015\Projects\EFBugTest\src\newtest>cp "..\..\..\..\..\..\Downloads\project.json.txt" project.json
'cp' is not recognized as an internal or external command,
operable program or batch file.

c:\Users\me\Documents\Visual Studio 2015\Projects\EFBugTest\src\newtest>copy "..\..\..\..\..\..\Downloads\project.json (1).txt" project.json
Overwrite project.json? (Yes/No/All): Y
        1 file(s) copied.

c:\Users\me\Documents\Visual Studio 2015\Projects\EFBugTest\src\newtest>copy ..\EFBugTest\Nuget.config .
        1 file(s) copied.
c:\Users\me\Documents\Visual Studio 2015\Projects\EFBugTest\src\newtest>dotnet restore

c:\Users\me\Documents\Visual Studio 2015\Projects\EFBugTest\src\newtest>dotnet ef migrations add "Initial"
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Th
e system cannot find the file specified.
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

**Comment by AndriySvyryd** [comment]
@bricelam Could you take a look?

**Comment by bricelam** [comment]
lol TBH, probably not any time soon... :smile:

**Comment by AndriySvyryd** [comment]
@byatis This might be a bug in our tooling. While we investigate you could avoid using migrations by placing some database initialization code in Startup.cs:
```C#
if (env.IsDevelopment())
{
    using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>()
        .CreateScope())
    {
        using (var context = serviceScope.ServiceProvider.GetService<MyDataContext>())
        {
            //context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }
    }
}
```

**Comment by AndriySvyryd** [comment]
@byatis I got it. You need to change `Microsoft.EntityFrameworkCore.Tools` to `Microsoft.EntityFrameworkCore.Tools.DotNet`
[project.json.txt](https://github.com/aspnet/EntityFramework/files/478439/project.json.txt)

**Comment by byatis** [comment]
@AndriySvyryd Thanks you very much  Didn't know there were different way of getting the tools. That did the trick and I'm now finally able to compile and run with migrations. Have yet another problems though, but let's keep them for another day :D
