### ISSUE TITLE
LINQ with Take generates incorrect SQL

### ISSUE THREAD

**Issue by Feasoron** [aspnet/EntityFramework#6530]
### Steps to reproduce

If I run a query like 

```
 varobj = context.Lightbox.Take(50)
             .Include(l => l.LightboxImages)
            .ThenInclude(i => i.Image)
```

which is to say, take the top 50 lightboxes, including the images that have a many-to-many relationship with lightboxes.
### The issue

This frequently times out. It turns out that this is because it is generating incorrect SQL (as seen in the .NET Core debug output). The SQL it generates (with the columns pulled out for brevity) is

```
SELECT TOP(50) *
FROM [tblLightbox] AS [l]
ORDER BY [l].[LightboxId]

SELECT *
FROM [tblLightboxImages] AS [t]
LEFT JOIN [tblLBDImages] AS [t0] ON [t].[ImageId] = [t0].[ImageId]
WHERE EXISTS (
    SELECT TOP(50) 1
    FROM [tblLightbox] AS [l]
    WHERE [t].[LightboxId] = [l].[LightboxId])
ORDER BY [t].[LightboxId]
```

The `where exists` clause is incorrect. This will return every image that has a many-to-many with at least one lightbox. The SQL should look more like this: 

```
SELECT *
FROM [tblLightboxImages] AS [t]
LEFT JOIN [tblLBDImages] AS [t0] ON [t].[ImageId] = [t0].[ImageId]
WHERE [t].[LightboxId] in (
    SELECT TOP(50) [l].[LightboxId]
    FROM [tblLightbox] AS [l])
```

This will return only the images that have a lightbox ID in those top 50 lightboxes. It maps to entities properly, but with an image table with a large number of rows this query is too slow and times out.
### Further technical details

EF Core version: 1.0.0
Operating system:  WIndows 10 Anniversary, 
Visual Studio version: (e.g. VS 2013 or n/a) VS 2015

Other details about my project setup:
SQL Server 2016

**Comment by kunnis** [comment]
``WHERE [t].[LightboxId] in (...`` won't handle when working with a composite key.  I believe a ``INNER JOIN`` should work in all cases

> SELECT *
> FROM [tblLightboxImages] AS [t]
> LEFT JOIN [tblLBDImages] AS [t0] ON [t].[ImageId] = [t0].[ImageId]
> INNER JOIN (
>     SELECT TOP(50) Col1, Col2, Col3
>     FROM [tblLightbox] AS [l]
>     WHERE [t].[LightboxId] = [l].[LightboxId]) [q] ON [q].[Col1] = [t].[Col1] AND [q].[Col2] = [t].[Col2] AND [q].[Col3] = [t].[Col3]
> ORDER BY [t].[LightboxId]

**Comment by kunnis** [comment]
A bit of research shows this is in src\Microsoft.EntityFrameworkCore.Relational\Query\ExpressionVisitors\Internal\IncludeExpressionVisitor.cs  at Line 348.  The code condtionally selects when it thinks it can safely use an ``EXISTS``, and uses an exist when it can, and falls back to ``INNER JOIN`` if it can't.  Is there a reason there's a preference for generating an exists statement vs an inner join?  I'd think always using ``INNER JOIN`` would be clearer to someone reading the output vs a ``WHERE EXISTS`` with extra items added to the where clause.  I also think eliminating the ``EXISTS`` branch of code will make the code simpler.

**Comment by smitpatel** [comment]
@kunnis - Read discussion on #4903 for reasons to prefer Where Exists.

**Comment by divega** [comment]
> 'd think always using INNER JOIN would be clearer to someone reading the output vs a WHERE EXISTS with extra items added to the where clause. I also think eliminating the EXISTS branch of code will make the code simpler

This may be worth rediscussing. We have found new data since we made the call.

**Comment by caleblloyd** [comment]
I also think it's worth re-discussing.  The WHERE EXISTS implementation does not limit the query results and pulls all results from the database.  It's also much slower in some cases.

**Comment by kunnis** [comment]
@caleblloyd Outside of the issue with skip/take, which is what started this whole conversation, can you describe where it's slower?  Or was the skip/take issue causing the slowness you're discussing?

**Comment by caleblloyd** [comment]
@kunnis there's the issue of Take(int) dumping the entire data set.  There's also this query optimization issue:

    db.Blogs.Take(10).Include(m => m.Posts).OrderByDescending(m => m.BlogId).ToList()

WHERE/EXISTS approach takes 0.1010 seconds to run:

	SELECT `p`.`PostId`, `p`.`BlogId`, `p`.`Content`, `p`.`Title`
	FROM `Posts` AS `p`
	WHERE EXISTS (
	    SELECT 1
	    FROM (
		SELECT `b0`.`BlogId`, `b0`.`Title`
		FROM `Blogs` AS `b0`
		LIMIT @__p_0
	    ) AS `t`
	    WHERE `p`.`BlogId` = `t`.`BlogId`)
	ORDER BY `p`.`BlogId` DESC

JOIN approach takes 0.0005 seconds to run:

	SELECT `p`.`PostId`, `p`.`BlogId`, `p`.`Content`, `p`.`Title`
	FROM `Posts` AS `p`
	INNER JOIN (
	    SELECT DISTINCT `t`.`BlogId`
	    FROM (
		SELECT `b0`.`BlogId`, `b0`.`Title`
		FROM `Blogs` AS `b0`
		LIMIT @__p_0
	    ) AS `t`
	) AS `t0` ON `p`.`BlogId` = `t0`.`BlogId`
	ORDER BY `t0`.`BlogId` DESC

100ms of latency for joining a few items is no joke.  This is on MySQL, so SQL Server / SQLite may optimize differently.  But this makes 2 issues with WHERE/EXISTS.

I've removed the WHERE/EXISTS approach from the [MySQL driver](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/56) I contribute to, hoping EF will remove it upstream.

**Comment by maumar** [comment]
alternatively, we could recognize this case and fallback to join, but keep EXISTS for cases where it's safe to use it

**Comment by kunnis** [comment]
@caleblloyd   The two SQL statements you included are not the same.  They will return different result sets. That is what this whole issue is about.  The MSSQL code has the same issue.  EF does not handling the ``Take()`` with ``Include()`` correctly.   Weather ``INNER JOIN`` or ``EXISTS`` is used to fix this issue is a different question.  The code that creates the ``INNER JOIN`` is correct, but the code that creates the ``EXISTS`` is incorrect.  It seems like MySql patched out the EXISTS branch to get around this bug.

The deeper question is: "Is ``EXIST`` more specific then ``INNER JOIN`` when doing the same logical operation?"  If the the ``EXISTS`` query is more specific in a way you can't match with ``INNER JOIN`` Then we should use ``EXISTS`` when we can.  If the two are logically the same, then we should ditch the exists branch, and just use ``INNER JOIN`` all the time, and make that code a bit simpler.

**Comment by kunnis** [comment]
Here is an alternate general purpose solution.  I believe it would remove the need for the inner join branch of code.

    SELECT *
    FROM [tblLightboxImages] AS [t]
    LEFT JOIN [tblLBDImages] AS [t0] ON [t].[ImageId] = [t0].[ImageId]
    WHERE EXISTS (
        SELECT 1 FROM
        (
            SELECT TOP(50) Pk1, Pk2, Pk3
            FROM [tblLightbox] AS [l])
            ORDER BY [l].[LightboxId]
        ) q WHERE t.Pk1 = q.Pk1 AND t.Pk2 = q.Pk2 and t.Pk3 = q.Pk3
    ORDER BY [t].[LightboxId]

**Comment by divega** [comment]
Reopening to go through proper approval process.

**Comment by Eilon** [comment]
This patch is **approved**, please ensure it is merged into the correct branch and building as part of the patch train.
