### ISSUE TITLE
Enable tools to work with 1.0 runtime

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#6549]
When the tools packages (listed below) RTM, We'll need to ensure they work with the 1.0.0 runtime in addition to the 1.1.0 runtime.

* Microsoft.EntityFrameworkCore.Design
* Microsoft.EntityFrameworkCore.Tools.*

We'll especially need to investigate what to do with the `Microsoft.EntityFrameworkCore.Design` package. The original assumption was that this assembly would version alongside the runtime. We'll either need to make sure the `1.0.0` version plays nicely with the `1.1.0` runtime, or release **both** a `1.0.0` and `1.1.0` version when the tools RTM.

**Comment by bricelam** [comment]
Having a single version is not going to work. We added new migration operations which require referencing MS.EFCore.Relational 1.1.0.

So I guess we need to decide when to rev the number:

1. With each version of the runtime
2. When we need new features from the runtime

**Comment by rowanmiller** [comment]
Long term I think we want to get the runtime/tooling package versions back in lock step (so option 1). So I think that approach would be fine for now too.

**Comment by bricelam** [comment]
Ok, then we need to retroactively create a version of Microsoft.EntityFrameworkCore.Design that works with 1.0.1 and RTM it with the tools (or with the next preview).

Microsoft.EntityFrameworkCore.Design should not move to the tools repo. This solves the Reverse Engineering tests issue.

**Comment by bricelam** [comment]
Also, we should start versioning Microsoft.EntityFrameworkCore.Design with the runtime from here on out.

**Comment by bricelam** [comment]
This plan fits the original architecture.

**Comment by rowanmiller** [comment]
Done

**Comment by bricelam** [comment]
The plan is to release a 1.0.0-compatible version of `Microsoft.EntityFramework.Design` from `dev` branch of the [aspnet/EntityFramework.Tools](https://github.com/aspnet/EntityFramework.Tools) repo, and a 1.1.0-compatible version from the `dev` branch this repo.

After the tools RTM, we can transition the code back to the next `rel/1.0.x` branch on this repo.

**Comment by bricelam** [comment]
Re-opening since our build infrastructure didn't support this.

**Comment by bricelam** [comment]
The current plan is to:

1. Make Tools work with Design 1.0.0-preview2 (#6743)
2. Release Design with 1.0.2 (#6742)
3. Remove the work for step 1
4. Release Tools 1.0.0

**Comment by bricelam** [comment]
That plan won't work. 1.0.0-preview2 doesn't contain the types we need. We have to go back to the original plan of releasing a 1.0.1 version with the next release of the tools.
