### ISSUE TITLE
What's the best way to get the POCO model ignored properties configured by Fluent API?

### ISSUE THREAD

**Issue by xyting** [aspnet/EntityFramework#6568]
I want EFCore to auto record the change history so that I can undo and redo from the change history.

The repo is [Love.Net.EF.AutoHistory](https://github.com/lovedotnet/Love.Net.EF.AutoHistory)

So I add some extension methods to ``DbContext`` like [DbContextAutoHistoryExtensions](https://github.com/lovedotnet/Love.Net.EF.AutoHistory/blob/master/src/Love.Net.EF.AutoHistory/DbContextAutoHistoryExtensions.cs#L20-L55), but if the POCO model have some properties had been configured ignored using `Fluent API` like [this](https://github.com/xyting/RigoFunc.DAL/blob/master/src/Host/Models/AgendaContext.cs#L8),  the following code will throw exception

```C#
private static object Original(this EntityEntry entry) {
            var type = entry.Entity.GetType();
            var entity = Activator.CreateInstance(type, true);

            var properties = type.GetTypeInfo().GetProperties();
            foreach (var property in properties) {
                var nav = entry.Metadata.FindNavigation(property);
                if(nav != null) {
                    continue;
                }

                var original = entry.Property(property.Name).OriginalValue;
                property.SetValue(entity, original);
            }
            return entity;
        }
```

so I change the  code like following (add try...catch)

```C#
private static object Original(this EntityEntry entry) {
            var type = entry.Entity.GetType();
            var entity = Activator.CreateInstance(type, true);

            var properties = type.GetTypeInfo().GetProperties();
            foreach (var property in properties) {
                var nav = entry.Metadata.FindNavigation(property);
                if(nav != null) {
                    continue;
                }

                try {
                    // following code will throw exception if the property had been ignored.
                    var original = entry.Property(property.Name).OriginalValue;
                    property.SetValue(entity, original);
                }
                catch {
                    // what's the best way to get the ignored properties?
                    continue;
                }
            }

            return entity;
        }
```

My question is what's the best way to get the POCO mode ignored properties

**Comment by ajcvickers** [comment]
@xyting I'm not sure exactly what you are trying to do, but if you want to get just the mapped properties for the entity type then it is probably best to use the EF metadata to do this. For example:
```C#
var properties = entry.Metadata.GetProperties();
foreach (var property in properties)
{
    var propertyEntry = entry.Property(property.Name);
    var original = propertyEntry.OriginalValue;
    propertyEntry.CurrentValue = original;
}
```
This will not include navigations, so you won't need to skip them, and will include shadow properties, which your code would not do.

Note that in version 1.1, not released yet, but available in nightly builds, you can more easily get property entries directly. For example:
```C#
foreach (var propertyEntry in entry.Properties)
{
    var original = propertyEntry.OriginalValue;
    propertyEntry.CurrentValue = original;
}
```

**Comment by xyting** [comment]
@ajcvickers Thanks your valuable answer!
