### ISSUE TITLE
KoreBuild needs to support running xUnit.net tests on regular NET45

### ISSUE THREAD

**Issue by Eilon** [aspnet/EntityFramework#659]
KoreBuild needs to support running xUnit.net tests on regular NET45. If there a csproj in the test folder, build it and run tests from it.

* Just do this for EF repos for now

**Comment by rowanmiller** [comment]
We get coverage from running locally, it's not worth the investment to do this.

**Comment by bricelam** [comment]
@rynowak hit a similar need to run tests on netcore50 for eventing. Mitigated it by just sharing source files with the tests.
