### ISSUE TITLE
Shadow property naming not working as documented

### ISSUE THREAD

**Issue by mikebrind** [aspnet/EntityFramework#6655]
### Steps to reproduce
Create the model as detailed in the documentation on shadow properties here: https://ef.readthedocs.io/en/latest/modeling/shadow-properties.html#conventions
```csharp
class MyContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }

    public List<Post> Posts { get; set; }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public Blog Blog { get; set; }
}
```
Then add a migration.
### The issue
The database column and therefore the shadow property for the foreign key in the Posts table is named 'BlogId' instead of BlogBlogId contrary to the documentation:

```
migrationBuilder.CreateTable(
    name: "Posts",
    columns: table => new
    {
        PostId = table.Column<int>(nullable: false)
            .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
        BlogId = table.Column<int>(nullable: true),
        Content = table.Column<string>(nullable: true),
        Title = table.Column<string>(nullable: true)
    },
```
Is the bug in the documentation or the framework?

**Comment by smitpatel** [comment]
@mikebrind - Which version of EF are you using?
In #6317 , the behavior was changed. If the PK property name has navigation/entitytype name as prefix then prefix would be removed. Hence shadow property is created with name `BlogId` dropping prefix `Blog` from navigation name. Though this change is in dev branch and not released to public yet. And documentation refers to public bits therefore there is difference.

For Triage: This could be a breaking change.

**Comment by mikebrind** [comment]
1.0.0:
```json
"dependencies": {
    "Microsoft.Extensions.Configuration": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    }
  },
```

**Comment by rowanmiller** [comment]
@smitpatel to verify if we changed the naming between 1.0 and 1.1

**Comment by smitpatel** [comment]
@rowanmiller - RTM generates `BlogId` so documentation error.
