### ISSUE TITLE
SQLite Migrations: Ignore schema

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#6679]
Asked by @VorSiechtIP (or a user with the same name) [on StackOverflow](http://stackoverflow.com/q/39854342/475031):

I have a shared model that will be used to create both SqlServer and SQLite databases.  I added the Table attribute onto each one of my model classes and supplied a schema:

``` C#
[Table("Sites", Schema = Common)]
```

When I migrate the SQLite database using `context.Database.Migrate()`, I get a NotSupportedException error.  I know that SQLite doesn't support schemas, so I was wondering if there was an easy way to ignore the schema attribute during migrate?

**Comment by bricelam** [comment]
I suspect the reason this is happening is because the migration was generated with the SQL Server provider active. This would scaffold the schema name into the migration. If SQLite was active, these would not be scaffolded.

This was the original design: Strip schemas out when generating the migration, but throw if the user tries to explicitly specify one since they're note supported on SQLite. This, however, makes creating provider-agnostic migrations unnecessarily difficult and we should consider just ignoring them in the Migrations SQL generator too.

**Comment by Allann** [comment]
Get the same error if the OnModelCreating (in a DbContext) is called with the line:

`modelBuilder.HasDefaultSchema("Maintenance");`

As a suggestion, could this not be:

`modelBuilder.ForSqlServerHasDefaultSchema("Maintenance");`

that way it is configured only for SqlServer and is ignored in other provider types.

As it currently stands, it is implied the the command works for ALL provider types.

**Comment by bricelam** [comment]
In addition to ignoring schemas in Migrations (and `EnsureCreated()`), we decided to warn during model building if a schema is specified. We'll also warn when a sequence is specified since they are also not supported by SQLite.
