### ISSUE TITLE
Commands: Show full log

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#6697]
We discussed #6643 in a design meeting and decided on a different approach.

Instead of using `IReportedLogState`, we will whitelist the event IDs we want reported when `--verbose` isn't specified. If needed, we'll allow providers to add to the whitelist, but this is probably YAGNI.

Specifying `--verbose` will ignore the whitelist and report all events `Debug` and higher. (Or just all events depending how noisy it is.)

**Comment by bricelam** [comment]
I started implementing this, and it is rapidly growing into something far more complex than where we started. Reverse Engineer has a significant amount of provider-specific messages that we would want to show on the default verbosity. We don't have a good way letting the providers tell us which messages they want us to show (this is what drove us to use a well-known category in the first place). Having operation-specific whitelists also adds additional complexity.

I'm coming to the conclusion that we should just show all the log messages in the tools. Logging is general-purpose and we've set the levels according to what we believe consumers are generally interested in. Our tools, like Kestrel, should be just another consumer. Specifying `--verbose` will merely lower the level of messages we show (from `Information` to `Trace`).

This has the added benefit of making warnings more visible to users. Currently, they only see things like model building warnings if they happen to be using Kestrel or explicitly turn on logging. This will expand that audience to anyone using Migrations.

If we find any of the levels inappropriate for the tools, we should question whether the level is appropriate in general. If we think it is generally right, but not right for the tools, we can fix up the level  in the tools.

**Comment by anpete** [comment]
@bricelam It looks like RE is logging warnings at the Warning level. Don't we just want to always output anything at that level? I.e. Logging at Information usually means LogLevel >= LogLevel.Information.

**Comment by bricelam** [comment]
Yep. And I'm saying we should also output anything at Information level too--no more filtering of log messages.

**Comment by anpete** [comment]
I'm fine with that. I think we are still able to do ad-hoc filtering by eventId if we choose. E.g. SQL comes out at Information by default, but we could choose to only display it in verbose mode in the tool.

**Comment by bricelam** [comment]
+1

**Comment by rowanmiller** [comment]
👍
