### ISSUE TITLE
Clean API of IRelationalCommand and related classes

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#6700]
* Methods on `IRelationalCommand` should not have parameters with default values, in particular `manageConnection` can be removed completely since assuming it's `true` always will not affect actual behavior due to how these methods are called.
 * `RelationalCommandBuilderFactory` should use a public type for the `ISensitiveDataLogger` category

**Comment by rowanmiller** [comment]
@AndriySvyryd does this need to be done now (for 1.1)?

**Comment by AndriySvyryd** [comment]
It doesn't __need__ to be done at all, but if we are going to do it for 1.1 we should do it before preview. It shouldn't take more than 30 minutes.

**Comment by rowanmiller** [comment]
Putting on the backlog, but as with all cleanup tasks... feel free to do it now if you want 😄
