### ISSUE TITLE
Query: Null semantics issue after improved nav. translation

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#6702]
Tests disabled:

Complex_navigations_with_predicate_projected_into_anonymous_type
Select_Where_Navigation_Scalar_Equals_Navigation_Scalar
Select_Where_Navigation_Equals_Navigation
Select_Where_Navigation_Scalar_Equals_Navigation_Scalar_Projected

**Comment by maumar** [comment]
Fixed in 6d3881496943d4835af5599013e5f07f6bebb665
