### ISSUE TITLE
Revisit public/abstract aspects of query context factories

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#6713]
While investigating #6642 it was noticed that RelationalQueryContextFactory is an internal class. This means providers should not be using it as a base class, which in turn means that #6642 does not apply.

However, should it actually be public? It is only useful to make it public if it is useful for providers to use as a base class. Neither SQL Server or SQLite need this. Also, it contains very little code and so would likely add little value as a base class.

The non-relational QueryContextFactory is abstract and public. This implies all providers should provide their own implementation, which for relational providers may be RelationalQueryContextFactory. However,  QueryContext itself is not abstract, so maybe QueryContextFactory should not be abstract and the default implementation should return a QueryContext?

**Comment by rowanmiller** [comment]
We're OK with this being internal, we don't think providers will need to override this

**Comment by ajcvickers** [comment]
Re-opening this based on API review. Also consider:
* Dependencies of public, non-D.I. types on internal services (IStateManager, IChangeDetector)
* Some of these were changed to LazyRefs, which is also internal
* How these play with QueryBuffer, which is internal
* Can QueryCompilationContext and related classes be made internal?

**Comment by rowanmiller** [comment]
For 1.1 we will just verify that we didn't break providers (already tracked as part of sign-off). For 1.2 we should rationalize what is internal etc.

**Comment by ajcvickers** [comment]
@anpete Can you take a quick look at this and make a decision as to whether we will ever change anything here, or whether it is okay the way it is. If the former, we should try to do it for 2.0 because of the breaking nature. If the latter, we'll just close.

**Comment by ajcvickers** [comment]
Make RelationalQueryContextFactory public.

**Comment by divega** [comment]
@anpete just double-checking: is this issue completely addressed by https://github.com/aspnet/EntityFramework/issues/8406?
