### ISSUE TITLE
API review for 1.1

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#6714]
We should review APIs, paying special attention to any breaking changes. In particular, one thing we should look at are base classes used by provider-specific service implementations. See #6622 for details.

**Comment by rowanmiller** [comment]
Done for preview1, will do an incremental review for 1.1 RTM

**Comment by rowanmiller** [comment]
Done. There were only two API changes between Preview1 and RTM. The changes were in the lower level query components and I synced with relevant folks to make sure they were good.
