### ISSUE TITLE
Revert 57b7656 once we pick up dotnet/core-setup#423 fix

### ISSUE THREAD

**Issue by dougbu** [aspnet/EntityFramework#6727]
Similar to aspnet/Mvc#5376 cleanup of the same workaround in MVC.

**Comment by dougbu** [comment]
@pranavkm should this issue be closed now? Or does some work remain after you pushed 62de4bd?

**Comment by pranavkm** [comment]
Reverted in https://github.com/aspnet/EntityFramework/commit/62de4bd41dfba3d94eda0a2211864078341cb3fd

**Comment by bricelam** [comment]
Thanks, @pranavkm!
