### ISSUE TITLE
Port Include() performance improvement to 1.0.2

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#6760]
We made a fix in d0134932eb0032024ef6fa70ee83fe2f55c01e42 that significantly improves the performance of certain queries with `Include()`. 

We should check if it meets the risk bar for a patch release.

**Comment by gdoron** [comment]
In general, I think the releases should be more often and release as soon as possible.
I'm not sure why, but sometimes, there are very small changes, that **surely won't break anything** with great impact, but they are merged to a branch that is going to be release in 4 months!

An example (from the MVC repo) @dougbu: https://github.com/aspnet/Mvc/commit/cbc88fc2d425f76ff80604a02cf79ced76cf27cb
https://github.com/aspnet/Mvc/issues/4989

Please bear in mind there are real applications out there, which crucially need those fixed merged, and 4 months or even more to wait is sometimes unacceptable, depending on the severity. 

Thanks for considering it @divega !

**Comment by rowanmiller** [comment]
@anpete can you evaluate the risk on this one

**Comment by anpete** [comment]
@rowanmiller Low risk. I think we can take it.

**Comment by rowanmiller** [comment]
Cool, can you port the fix into 1.0.2

**Comment by anpete** [comment]
Merged

**Comment by gdoron** [comment]
Thanks 👍 👍 👍

**Comment by divega** [comment]
Reopening to take through patch release approval. @anpete could you please write a risk assessment for the change? I will send you samples :smile:

cc @Eilon

**Comment by Eilon** [comment]
This patch is **approved**, please ensure it is merged into the correct branch and building as part of the patch train.

**Comment by divega** [comment]
This is already in all the right branches.

**Comment by gdoron** [comment]
@Eilon @divega Can you share a ~ release date of 1.0.2? 
We just got hit hard by the bug I mentioned earlier of MVC and ValidationSummary. 😢

(Safari for some reason doesn't respect form validations ([for 9 years!](https://bugs.webkit.org/show_bug.cgi?id=28649)) and a very important customer of ours submitted an invalid form and MVC couldn't show him the errors because the required field was in a collection)

**Comment by Eilon** [comment]
@gdoron hopefully soon 😄 We're nearly done writing the code, but we have to do verification of the bits first. We have a package feed with nightly builds at https://dotnet.myget.org/gallery/aspnetcore-patch, but the builds for this release aren't there yet (we're working on it right now).

**Comment by gdoron** [comment]
@Eilon, for some reason, we can't use the nightly builds.
When we try to update our references it always breaks and won't compile, it's extremely frustrating 😢 .
@smitpatel was very kind and [tried helping us out,](https://github.com/aspnet/EntityFramework/issues/6634#issuecomment-250548293) but it didn't work for us.

Can you please assign someone to take a look? I can give him an access to our private GitHub repository (Yes, we are desperate...) so it won't be a trial and error.

p.s. It's for a very good cause, ASP.NET Core is not just [saving kittens](https://github.com/aspnet/Home/pull/1754#issuecomment-248365498) 😸 but helping people with disabilities at [yooocan.com](https://yooocan.com) 💪.
Checkout this **amazing story** we got two days ago for Halloween: https://yooocan.com/Story/329/Having-Wheels-Has-Its-Perks.

**Comment by Eilon** [comment]
@gdoron well if you do manage to get nightly builds working, we have some builds on this feed: https://dotnet.myget.org/gallery/aspnetcore-patch

As far as dates, we're nearly done with the code, but the actual release involves a number of teams coordinating lots of builds so we can't guarantee any particular dates.

BTW very cool project you're working on!
