### ISSUE TITLE
Breaking changes to relational command methods may affect Npgsql provider

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#6783]
### Steps to reproduce
1. Create a .NET Framework console app
2. Execute `install-package Microsoft.Entityframeworkcore.Relational -pre` form a feed with recent 1.1.0 preview1 bits 
3. Execute `install-package Npgsql.EntityFrameworkCore.PostgreSQL` from the NuGet feed. 
4. Add some code that uses the Npgsql provider and build, e.g.:
 ``` C#
using Microsoft.EntityFrameworkCore;

namespace ConsoleApplication86
{
    class Program
    {
        static void Main(string[] args)
        {

        }
    }

    public class MyContext: DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql("");
        }
    }
}
``` 
5. go to the bin\debug or release folder in a developer command prompt and execute `ngen install ConsoleApplication86.exe`

### The issue
The relevant output looks like this:
- ``Warning: System.MissingMethodException: Method not found: 'System.Object Microsoft.EntityFrameworkCore.Storage.IRelationalCommand.ExecuteScalar(Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.Object>, Boolean)'. while resolving 0xa0000a8 - Microsoft.EntityFrameworkCore.Storage.IRelationalCommand.ExecuteScalar.``
- ``Warning: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Object> Microsoft.EntityFrameworkCore.Storage.IRelationalCommand.ExecuteScalarAsync(Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.Object>, Boolean, System.Threading.CancellationToken)'. while resolving 0xa0001da - Microsoft.EntityFrameworkCore.Storage.IRelationalCommand.ExecuteScalarAsync.``
- ``Method not found: 'System.Object Microsoft.EntityFrameworkCore.Storage.IRelationalCommand.ExecuteScalar(Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.Object>, Boolean)'. while compiling method NpgsqlDatabaseCreator.HasTables``
- ``Method not found: 'System.Threading.Tasks.Task`1<System.Object> Microsoft.EntityFrameworkCore.Storage.IRelationalCommand.ExecuteScalarAsync(Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.Object>, Boolean, System.Threading.CancellationToken)'. while compiling method <HasTablesAsync>d__8.MoveNext``

These methods were removed in dbdfe1482da93830d5f7e71d7b3701fb5bd94aec. 

The output is the same for .NET Framework 4.5.1 and 4.6 but I don't know how to do something similar for .NET Core.

### Further technical details

EF Core version: 1.1.0-alpha1-22431
Npgsql.EntityFrameworkCore.PostgreSQL version: 1.0.2
Operating system: Windows 10
Visual Studio version: VS 2015 Update 3

**Comment by AndriySvyryd** [comment]
Fixed in https://github.com/aspnet/EntityFramework/commit/cbc617e4bc1875ea5687334f2b6561fad1ff29c4
