### ISSUE TITLE
Strange FK exception depending on property names

### ISSUE THREAD

**Issue by HappyNomad** [aspnet/EntityFramework#6792]
I'm mapping a complex domain model and encountered the exception, "The property 'ID' cannot be part of a foreign key on 'T' because it is contained in a key defined on a base entity type."  Looks like the throwing of this exception was introduced in #2837.

At first I thought this was due to either a limitation of TPH mapping in general, or the current EF core implementation specifically.  But now I think it's a bug in EF Core.  It was difficult to reproduce in isolation since it obscurely depends on property names, too.

Trying to create a database using this context and model will reproduce the issue:

```
public class BloggingContext : DbContext
{
    public BloggingContext( DbContextOptions<BloggingContext> options )
        : base( options ) { }

    public DbSet<L> Ls { get; set; }
    public DbSet<PBase> PBases { get; set; }
    public DbSet<P> Ps { get; set; }
    public DbSet<Q> Qs { get; set; }
    public DbSet<T> Ts { get; set; }
}

public class L
{
    public int ID { get; set; }
    public IList<T> Ts { get; set; }
}

public abstract class PBase
{
    public int ID { get; set; }
}

public class P : PBase
{
}

public class Q : PBase
{
}

public class T : P
{
    public P P { get; set; }
    public Q F { get; set; }
}
```

A workaround for this example is to rename the context's "Ls" DbSet property to "Zs".  Unfortunately, I've already come across a case in my real domain model where this simple hack doesn't help.  That is, it removes the exception for one class but that, in turn, causes the same exception to occur for another class.  Removing one of the properties but not the other doesn't remove the exception, either.

**Comment by HappyNomad** [comment]
I tested said portion of my domain model in isolation and it worked!  This is really confusing since the exception message said otherwise.  Looks like the majority of exception messages coming back from EF Core when I feed it my large domain model are misleading.  I'm trying to feed it smaller portions of my domain model, so it doesn't throw back this garbage, but apparently I haven't yet gotten small enough.

**Comment by HappyNomad** [comment]
I've updated my original comment with a model that reproduces the issue in isolation.  It was difficult to whittle down this small model since reproducing the issue depends on class and property names.

**Comment by HappyNomad** [comment]
I updated my original comment to include the context used to reproduce the issue.  I also found a workaround for the example.

**Comment by HappyNomad** [comment]
Okay, so now I understand the default behavior is as stated [here](https://msdn.microsoft.com/en-us/data/jj713564(v=vs.113).aspx): "In a one-to-one relationship, the primary key acts additionally as a foreign key and there is no separate foreign key column for either table.".

But then why not do the correction automatically similar to how [this](https://docs.efproject.net/en/latest/modeling/relationships.html#no-foreign-key-property) happens automatically, instead of throwing the exception and requiring extra code?

Anyway, please explain why the exact same exception is thrown even for this model where T has *no* properties.  Is it a bug too?

	public class BloggingContext : DbContext
	{
		public BloggingContext( DbContextOptions<BloggingContext> options )
			: base( options ) { }

		public DbSet<A> As { get; set; }
	}

	public class A
	{
		public int ID { get; set; }
		public L L1 { get; set; }
		public IList<PBase> L2 { get; set; }
	}

	public class L
	{
		public int ID { get; set; }
		public IList<T> Ts { get; set; }
	}

	public class T : P { }

	public class P : PBase { }

	public class Q : PBase { }

	public abstract class PBase
	{
		public int ID { get; set; }
		public string Stuff { get; set; }
	}

This example has a similar strange workaround: flip the L1 and L2 names and then the exception disappears.

**Comment by AndriySvyryd** [comment]
Fixed in 66c4c79

**Comment by HappyNomad** [comment]
Thanks for the fix here and on #6814.  I see both are on the feature/1.2.0 branch.  I'm now using the MyGet - ASP.NET Core "dev" branch feed with this version configured:

        "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0-preview2-*"

So I can't benefit from these changes until after the 1.1.0 release at which time I'll be able to update my version to 1.2.0-preview1-*, right?  I'd just like to verify that I understand this correctly, so I don't wait unnecessarily.  I looked at the [aspnetcore-feature-work feed](https://dotnet.myget.org/gallery/aspnetcore-feature-work) but don't see EF-Core (not sure I should use that feed even if it were there, though).

**Comment by AndriySvyryd** [comment]
@HappyNomad Correct. Hopefully you won't need to wait long.

**Comment by divega** [comment]
> I looked at the "aspnetcore-feature-work" feed but don't see EF-Core (not sure I should use that feed even if it were there, though).

@pranavkm @Eilon any idea why the build output of our feature/1.2.0 branch is not landing in the aspnetcore-feature-work feed? I was under the impression it was automatic :smile:

**Comment by pranavkm** [comment]
@divega unfortunatelty it's not automagic. You have to tell the build to push the packages. Here's what Razor does to push - https://github.com/aspnet/Razor/blob/feature/razor-pages/makefile.shade.

**Comment by divega** [comment]
cc @anpete about what you asked, see @pranavkm's comment above. Feel free to fix it, or we can wait until we marge feature/1.2.0 into dev.

**Comment by Eilon** [comment]
You are free to merge 1.2.0 changes into dev - the branch is open.

**Comment by HappyNomad** [comment]
> But then why not do the correction automatically similar to how [this](https://docs.microsoft.com/en-us/ef/core/modeling/relationships#no-foreign-key-property) happens automatically, instead of throwing the exception and requiring extra code?

@AndriySvyryd To clarify, did you implement this suggestion?  I'm using version `1.2.0-preview*` and it seems to be working that way.  The model builds fine even without the `OnModelCreating` workaround you suggested.

Also to clarify, you suggested the workaround:

	modelbuilder.Entity<T>().Property<int>("PId");
	modelbuilder.Entity<T>().HasOne(t => t.P).WithOne().HasForeignKey<T>("PId");

But I believe it should instead be:

	modelbuilder.Entity<P>().Property<int>("PId");
	modelbuilder.Entity<T>().HasOne(t => t.P).WithOne().HasForeignKey<P>("PId");

Right?  And I believe the first line can be omitted.

**Comment by AndriySvyryd** [comment]
@HappyNomad Yes, the fix is to choose FK properties that are compatible with the base type if you haven't specified any explicitly, so no extra configuration would be needed.

**Comment by AndriySvyryd** [comment]
Both workarounds are valid, it depends on what type you want to be the dependent one.

**Comment by HappyNomad** [comment]
@AndriySvyryd I looked at the generated model and it's reversing the principle/dependent roles from what I need.  My model classes consistently lack navigation properties that point from dependent to principle, so your fix's default feels counter-intuitive.  How can I leverage my model's consistent approach to navigation, or maybe add some attributes to my model classes' properties (something like [`[Part]`](https://github.com/aspnet/EntityFramework/issues/1985#issuecomment-258117532)), so that your fix generates as I need, without the extra configuration?

**Comment by AndriySvyryd** [comment]
@HappyNomad We actually tried to use the proposed heuristic in addition to others before the 1.0.0 release, but it became harder to explain and understand how EF chooses the dependent side, while it didn't improve the success rate that much, as many users have different expectations.
Unfortunately there's currently no public way of doing what you want, but it should be handled by Custom Conventions (#214)
