### ISSUE TITLE
Model Definition: Ability to override IS NOT NULL clauses of an index

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/EntityFramework#6794]
> This is for SQL Server and I am using EF Core 1.0.1. 

Assume that I have the below entity:

``` csharp
public class Person
{
    public string Name { get; set; }
    public string Lastname { get; set; }
    public DateTime? DeletedOn { get; set; }
}
```

Inside `OnModelCreating`, I also have this to create a multi-column unique index:

``` csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Person>().HasIndex(x => new { x.Name, x.Lastname, x.DeletedOn }).IsUnique();
}
```

This causes EF Core to generate something similar to below:

``` csharp
CREATE UNIQUE NONCLUSTERED INDEX [IX_People_Name_Lastname_DeletedOn] ON [dbo].[People]
(
    [Name] ASC,
    [Lastname] ASC,
    [DeletedOn] ASC
)
WHERE ([Name] IS NOT NULL AND [Lastname] IS NOT NULL AND [DeletedOn] IS NOT NULL)
```

However, I want not to allow `DeletedOn` column to be null for this index. So, I am try to make EF Core to generate the below index creation script for me:

``` csharp
CREATE UNIQUE NONCLUSTERED INDEX [IX_People_Name_Lastname_DeletedOn] ON [dbo].[People]
(
    [Name] ASC,
    [Lastname] ASC,
    [DeletedOn] ASC
)
WHERE ([Name] IS NOT NULL AND [Lastname] IS NOT NULL)
```

**QUESTION: Is this possible to do this with EF Core fluent API?**

I dug a bit into the fluent API and was able to find some things related to `HasAnnotation` API but was not able to understand enough to achieve this.

**Comment by rowanmiller** [comment]
This is not possible. Assigning to 1.2 to look at providing this functionality.

**Comment by AndriySvyryd** [comment]
Fixed in 428a328

**Comment by Davilink** [comment]
#1 Is it possible to have some example how to use it ?

#2 Is it possible that this can be back port to EF Core 1.0.5 ? Because i have that exact same issue, but i can't use EF Core 2.0, because i need to migrate my project to dotnet Core 2.0, and for the current moment is impossible. We have so much breaking change with the new mechanism of the Identity implementation.

**Comment by ajcvickers** [comment]
@Davilink I filed https://github.com/aspnet/EntityFramework.Docs/issues/610 for the docs. We will not be porting this fix to the 1.x versions of EF Core--the bar is very high to get patch changes into those releases, and this issue does not meet that bar.

**Comment by Davilink** [comment]
@ajcvickers Thx for the quick response.
