### ISSUE TITLE
Logger event IDs can be ambiguous

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#6802]
If each named logger is only associated with a single space of event IDs (i.e. a single enum), then event IDs can be used to identify messages. However, we sometimes share loggers between pieces of code which then log events using different event ID spaces.

For example, SqlServerScaffoldingModelFactory uses the logger from RelationalScaffoldingModelFactory. This means that event IDs from two spaces (SqlServerDesignEventId and RelationalDesignEventId) get written to the same logger, making the IDs ambiguous. We share loggers in other places, so I suspect there are other cases of this lurking in the codebase.

**Comment by bricelam** [comment]
@ajcvickers Should this one be assigned to you?

**Comment by ajcvickers** [comment]
Yep, at least until after we decide what to do. :-)
