### ISSUE TITLE
Query: Convert.ToString(string) is evaluated on client for .NET Core

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#6803]
Test

``` C#
AssertQuery<Order>(
    os => os.Where(o => o.CustomerID == "ALFKI")
        .Where(o => Convert.ToString(Convert.ToString(o.OrderID % 1)) != 10),
    entryCount: 6);
```

The 2nd where clause is evaluated on client 

```
The LINQ expression '(ToString(ToString(([o].OrderID % 1))) != "10")' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
```

This is because the outer method call has method `String ToString(System.Object)` for which are not able to translate. This happens only in .NET Core.

**Comment by smitpatel** [comment]
External issue filed on Roslyn - https://github.com/dotnet/roslyn/issues/14567

**Comment by smitpatel** [comment]
This will be fixed when .NET core 1.2 is released.

**Comment by smitpatel** [comment]
enable the tests once we upgrade to .Net core app 2.0

**Comment by ajcvickers** [comment]
@smitpatel to re-open Rosyln bug and find out if it is fixed in 2.0 and if so, why we aren't seeing this work.

**Comment by smitpatel** [comment]
We have correct runtime but the test is in Specs lib which targets netstandard1.3 still hence the expression tree does not find new overload (even though it is present at runtime). Since we are going to cross compile on net standard, this test (only ToString(string) part) should be made conditional on netstandard2.0 when we cross compile to that tfm.

Blocked on https://github.com/aspnet/Coherence/issues/166

**Comment by smitpatel** [comment]
@bricelam

**Comment by bricelam** [comment]
Unblocked after #8353
