### ISSUE TITLE
Exception says base and derived classes have same properties, but they don't

### ISSUE THREAD

**Issue by HappyNomad** [aspnet/EntityFramework#6814]
This issue can be reproduced by trying to create a database using this context and model:

	public class BloggingContext : DbContext
	{
		public BloggingContext( DbContextOptions<BloggingContext> options )
			: base( options ) { }

		public DbSet<A> As { get; set; }
	}

	public class A
	{
		public int ID { get; set; }
		public L M3 { get; set; }
		public IList<PBase> Ls { get; set; }
		public MT M2 { get; set; }
		public M M1 { get; set; }
	}

	public class C : OT { }

	public class MT
	{
		public int ID { get; set; }
		public IList<ST> STs { get; set; }
		public IList<OGT> OGs { get; set; }
	}

	public class M
	{
		public int ID { get; set; }
		public IList<S> Ss { get; set; }
	}

	public class ST : P
	{
		public C DC { get; set; }
	}

	public class OGT : P
	{
		public IList<OT> Os { get; set; }
	}

	public class S
	{
		public int ID { get; set; }
		public ST Type { get; set; }
	}

	public class OT : P { }

	public class L
	{
		public int ID { get; set; }
		public IList<T> Ts { get; set; }
	}

	public class T : P
	{
		public P P { get; set; }
		public Q F { get; set; }
	}

	public class P : PBase { }

	public class Q : PBase { }

	public abstract class PBase
	{
		public int ID { get; set; }
		public string Stuff { get; set; }
	}

The exception text says, "The type 'OT' cannot have base type 'P' because both types include the properties: ID, Stuff."

**Comment by HappyNomad** [comment]
@rowanmiller Thanks for acknowledging this as a bug.  Another likely incorrect exception that occurs upon feeding EF-Core my domain model is described in #6792.  I've edited my comment there to now include a context and model that reproduces the issue.

**Comment by AndriySvyryd** [comment]
Fixed in b689f18
