### ISSUE TITLE
Generate unique FK constraint names

### ISSUE THREAD

**Issue by HappyNomad** [aspnet/EntityFramework#6815]
I discovered this issue while looking for a workaround to #6814.  It can be reproduced using the context and model posted there, with this modification of swapping the names of A's M1 and M2 properties.  This produces an `SqlException` with the text, "Cannot create, drop, enable, or disable more than one constraint, column, index, or trigger named 'FK_PBase_MT_MTID' in this context. Duplicate names are not allowed."

**Comment by rowanmiller** [comment]
We think this is fixed in 1.1. Could you retry it on Preview 1 and see if it is resolved?

**Comment by rowanmiller** [comment]
BTW here info on trying out 1.1 Preview 1 https://blogs.msdn.microsoft.com/dotnet/2016/10/25/announcing-entity-framework-core-1-1-preview-1/

**Comment by HappyNomad** [comment]
Okay, I tried and this bug appears to be resolved.

**Comment by rowanmiller** [comment]
Thanks!
