### ISSUE TITLE
ExecutionStrategy ctor argument - maxRetryCount has incorrect documentation

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#6828]
Documentation says:

```
The maximum delay in milliseconds between retries.
```

but the argument is TimeSpan.

We should change the message to:

```
The maximum delay between retries.
```

**Comment by AndriySvyryd** [comment]
There are 5 places where this needs to be changed.

**Comment by smitpatel** [comment]
Can I poach this? :trollface:

**Comment by smitpatel** [comment]
@AndriySvyryd - Suggested doc comment here?
`The maximum delay between retries.` ? or do we want to include timespan too?

**Comment by AndriySvyryd** [comment]
Timespan is implied, so the first suggestion should be ok.
