### ISSUE TITLE
Script-Migration should have a parameter for the output location - like Add-Migration has

### ISSUE THREAD

**Issue by vmsgsp** [aspnet/EntityFramework#6890]
Script-Migration should have a parameter to specify the location where the SQL output file shall be written to. 

Something similar to Add-Migration 

`-OutputDir <String>
        The directory (and sub-namespace) to use. If omitted, "Migrations" is used. Relative paths are relative to project directory.`

**Comment by bricelam** [comment]
`dotnet migrations script` has `--output`. Having parity in the PowerShell command would be good.

We used to open it in VS as an unsaved file, but stopped doing that with the new architecture.
