### ISSUE TITLE
PERF: Implement DbContext pooling for high scale scenarios

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#6923]
- [x] Add overload of AddDbContext that enables pooling
- [x] OnConfiguring is never run. Configuration is external only.
- [x] Add state reset (context behavior flags, internal StateManager state)
- [x] Add Dispose event redirection.
- [ ] Logging
- [x] Pool cleanup

**Comment by bryan07** [comment]
As OnConfiguring is never run, how is it possible to configure many different connectionstring at runtime using DbContext Pooling?

**Comment by ajcvickers** [comment]
@bryan07 DbContext pooling uses the same context instances with the same configuration and hence has the limitation that you cannot change that configuration. This means that right now the connection string cannot be changed. It may be possible to do this once #8427 and/or #8494 are implemented, but I don't think we have thought deeply about whether this will play well with pooling.
