### ISSUE TITLE
Breaking changes in 1.1 affecting SapientGuardian MySQL provider

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#6926]
Here is some information about missing methods from pushing the SapientGuardian.EntityFrameworkCore.MySql v7.1.11 provider through NGen (similar to how I did for #6783):

```
Warning: System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.Internal.ContainsTranslator..ctor()'. while resolving 0xa000023 - Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.Internal.ContainsTranslator..ctor.
Warning: System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.Internal.EndsWithTranslator..ctor()'. while resolving 0xa000037 - Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.Internal.EndsWithTranslator..ctor.
Warning: System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.Internal.StartsWithTranslator..ctor()'. while resolving 0xa00003a - Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.Internal.StartsWithTranslator..ctor.
Method not found: 'Void Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.Internal.ContainsTranslator..ctor()'. while compiling method MySqlContainsTranslator..ctor
Method not found: 'Void Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.Internal.EndsWithTranslator..ctor()'. while compiling method MySQLCompositeMethodCallTranslator..ctor
```

The cause is that we removed the parameterless constructors from string method translators in 5e1c562ae40c16ef49b90731fd015eccce0c1d44. 

Creating this issue so that we can decide in triage whether we want to fix this for the same reason we reverted the removal of `EntityTypeExtensions.DisplayName()` (see https://github.com/aspnet/EntityFramework/issues/6914#issuecomment-257962521) or whether we want to apply the default bar for internal types.

**Comment by sweetwxh** [comment]
I'm using the official provider for mysql, and have the same issue. Almost all operation throws MissingMethodException. It's fine on previous version of efcore. I also updated Microsoft.EntityFrameworkCore.Relational to 1.1.0, but doesn't make any sense.

Below is one of the operation's exception:
`
Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory..ctor(Microsoft.EntityFrameworkCore.Infrastructure.ISensitiveDataLogger`1<Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory>, System.Diagnostics.DiagnosticSource, Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.
`

**Comment by rowanmiller** [comment]
@sweetwxh can you open an new issue and include a code listing we can run to see the error.

**Comment by mguinness** [comment]
@sweetwxh were you able to get this working?  I upgraded a project to 1.1 yesterday and got "Method not found" with the official MySQL provider.  It's not clear to me what the fix is, which package update is necessary to overcome this problem?

**Comment by rowanmiller** [comment]
@mguinness I've passed this info on to the MySQL team, but you may also want to report it directly so that they can track how many folks are hitting it https://bugs.mysql.com/.

**Comment by tobiashoeft** [comment]
Any news? :(

**Comment by mguinness** [comment]
@tobiashoeft Avoid MySql.Data.EntityFrameworkCore for now and use SapientGuardian.EntityFrameworkCore.MySql or Pomelo.EntityFrameworkCore.MySql instead.

**Comment by avikenjale** [comment]
Basically this issue is getting when I tried to implement method 'OnModelCreating' and using new feature .HasField for MySql database. 
I go with normal implementation of mySql model without using new feature, it works.

**Comment by avikenjale** [comment]
I am using `Pomelo.EntityFrameworkCore.MySql`, as native MySQL library has some another issues like Data Annotations  **TableAttribute**, **ColumnAttribute**

**Comment by geminiyellow** [comment]
same error

```
Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory..ctor(Microsoft.EntityFrameworkCore.Infrastructure.ISensitiveDataLogger`1<Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory>, System.Diagnostics.DiagnosticSource, Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.
```

`MySql.Data.EntityFrameworkCore` still die.

**Comment by mguinness** [comment]
@geminiyellow See if [Unable to run Migrations with EFCore 1.1.0 in MySQL](https://bugs.mysql.com/bug.php?id=84051) resolves your issue.

**Comment by JanWerder** [comment]
@mguinness Your solution solves the problem at hand, but it seems like the beta still has a problem with the Transaction Commit. But thanks anyways! 👍

**Comment by mguinness** [comment]
@JanWerder Try using the [Pomelo](https://docs.microsoft.com/en-us/ef/core/providers/pomelo/) provider instead, they're about to release [1.1.1](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/208) version.

**Comment by JanWerder** [comment]
@mguinness That works great! Thank you! 😄
