### ISSUE TITLE
Expecting  client eval warnings on Last and LastOrDefault query extensions

### ISSUE THREAD

**Issue by julielerman** [aspnet/EntityFramework#6929]
### Steps to reproduce
A simple Last or LastOrDefault query.

db.MyEntities.LastOrDefault();

I'm using the SQL Server provider.
Provider is configured to throw on client eval.

### The issue
Actual query against database is not filtered:

I was seeing this in the ILoggerProvider logging and then verified in SQL Profiler:

SELECT [s].[Id], [s].[Name]
FROM [Samurais] AS [s]

 Therefore I can only assume the full set is returned and the Last evaluation is happening in memory.

 I can see that the [throw on client eval] config is working because an Average method does cause an exception to throw.

No exception thrown for Last or LastOrDefault, 

### system
EF Core version: 1.1.0-preview1-final
Operating system: windows 10
Visual Studio version: VS2015

**Comment by divega** [comment]
We should also double-check if/when we can translate `Last`.

**Comment by maumar** [comment]
If the query has order by, we could reverse it (asc->desc, desc->asc) and use First/FirstOrDefault instead

**Comment by julielerman** [comment]
yeah ...translating last would be very subjective, TOP 1 is also subjective I suppose since it's possible (in linq and in TSQL) to use it without an order by. Would be easier to blame the database if it just had a BOTTOM expression ;)
