### ISSUE TITLE
Add announcement of the rename of "Microsoft.EntityFrameworkCore.Tools" -> "Microsoft.EntityFrameworkCore.Tools.DotNet"

### ISSUE THREAD

**Issue by Bartmax** [aspnet/EntityFramework#6936]
The only place where this is documented right now is on the announcement blog and trying using the previous "Microsoft.EntityFrameworkCore.Tools" doesn't give an error. You will only notice when trying to execute `dotnet ef` i think making an announcement will save people lot of time.

**Comment by rowanmiller** [comment]
Good point. Done - https://github.com/aspnet/Announcements/issues/208.
