### ISSUE TITLE
Logging: Use template based format string to log structured DbCommand log data

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#6946]
At present EF logging of Db Command uses `DbCommandLogData` object with custom formatter which would generate a plain string message for logger to log. This blocks structured logging since logger would get only `DbCommandLogData` object instead of different parts of log messages (for querying). During #6096, we overcame this gap by implementing `IEnumerable<KeyValuePair<string,object>>` in #6201 which means that `DbCommandLogData` can be queried.

Current logging framework allows generation of structured log using template based string. The template string contains placeholders to fill the values of arguments and provides ability to query the log data without requiring any additional code. (See https://github.com/aspnet/EntityFramework/pull/6201#issuecomment-236076125
and example in MVC at https://github.com/aspnet/Mvc/blob/a78f77afde003c4a3fcf5dd7b6dc13dd9c85f825/src/Microsoft.AspNetCore.Mvc.Razor/Internal/MvcRazorLoggerExtensions.cs#L23)

This saves us trouble of creating custom formatter and extra type to store the state of DbCommandLog.
`DbCommandLogData` which is marked as obsolete at present would be removed when logging is implemented this way.

**Comment by julielerman** [comment]
Guys -- this is the "kludge" I was talking about on Wednesday that I was confused about when you said it was implemented in 1.1. 
This is how I'm currently using & explaining it with 1.1:
![image](https://cloud.githubusercontent.com/assets/5007120/22151014/238c4cb6-deea-11e6-9223-53acaeed5c3b.png)

Am I missing something?

**Comment by ErikEJ** [comment]
@julielerman I am doing this instead (based on sample code from Rowan) https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Extensions/Logging/DbSimpleLogger.cs

**Comment by rowanmiller** [comment]
Our logging is overly complex to work with at the moment, and we have an item on the list to address this in 2.0 (#218). Honestly, either way is fine with 1.x. `DbCommandLogData` is marked as obsolete... but we won't be removing it until 2.0 - at which point there will be a much cleaner way to do this.

**Comment by smitpatel** [comment]
Removing milestone for this. Since we are re-addressing logging, should we merge this issue with #218
