### ISSUE TITLE
Update SQL Server execution strategy

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#6970]
1205, 41301 and 41839 should be considered transient.
41301, 41302, 41305, 41325 and 41839 should be retried much more aggressively, with all retries happening within 100ms from the first failure.
See https://msdn.microsoft.com/en-us/library/mt668435.aspx#Conflict%20Detection%20and%20Retry%20Logic for more information

**Comment by divega** [comment]
Clearing up milestone to take this through proper triage.
