### ISSUE TITLE
Integrate Api Check 

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#6996]
Api Check can be integrated into our build to help avoid unintentional breaking changes between releases. The tool and the process to add exceptions is described at https://github.com/aspnet/BuildTools/wiki/Api-Check. 

An example of a baseline Initial baselines have been checked in at https://github.com/aspnet/EntityFramework/tree/javiercn/breaking-changes (although they may need updating).

cc @javiercn

**Comment by divega** [comment]
Last time we talked about checking in a modified baseline every time we make changes instead of checking in the list of exceptions. 

The problem with that approach is that Api-Check generates a JSON representation of the whole public surface, therefore any time we make any breaking **or non-breaking** change (e.g. any time we add any new public API) to the public surface we would have a huge file to diff. 

The exceptions file on the other hand only requires changes when there is an intentional breaking change, which should be less often and a much smaller file.

Clearing up milestone to re-discuss.

**Comment by divega** [comment]
@smitpatel talk to @javiercn

**Comment by Eilon** [comment]
Any update on this? We should get this integrated to we can keep an eye on breaking changes... We'll certainly have some breaking changes for 2.0 but we want to make sure they're all intentional, which this tool will help catch.

**Comment by divega** [comment]
@Eilon yes, we are making progress. @smitpatel already started on it and now needs to talk to @javiercn about some issues.

**Comment by smitpatel** [comment]
@divega @Eilon - Does this tool need to run on Specification tests?

**Comment by divega** [comment]
@smitpatel I think the answer is no. My reasoning is that we are not committed to avoid breaking changes in the spec test but rather to communicate them to provider writers as needed.

**Comment by Eilon** [comment]
Yeah I agree with this.
