### ISSUE TITLE
Document exceptions

### ISSUE THREAD

**Issue by denisz1** [aspnet/EntityFramework#7012]
MS SDKs typically document which exceptions are thrown.

This is crucial information. We cannot properly handle our error paths without knowing what is going wrong (and catching an `Exception` tells us nothing).

Many EF Core methods lack complete documentation, because they do not mention exceptions thrown. [MSDN was good at this](http://msdn.microsoft.com/en-us/library/system.data.entity.dbcontext.savechanges(v=vs.113).aspx#Anchor_1), but the new docs site seems incomplete.

**These are the [worst culprits](http://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.dbcontext#Microsoft_EntityFrameworkCore_DbContext_SaveChanges):**

    DbContext.SaveChanges
    DbContext.SaveChangesAsync

We cannot rely on the source, because that can change at any time. You need to **officially document** this.

It's not hard, PLEASE consider this a priority.

*(In the meantime, please at least let us know about those two methods.)*

**Comment by rowanmiller** [comment]
Note to self - look for custom exception types that we have defined
