### ISSUE TITLE
PMC Tools: Add unifying binding redirects on UWP

### ISSUE THREAD

**Issue by sgmon** [aspnet/EntityFramework#7045]
### Steps to reproduce
1. Create a UWP application targeting Windows 10 Anniversary edition.
2. Follow steps provided at https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started except for using the later Microsoft.EntityFrameworkCore.Tools v1.1.0-preview4-final and not needing to create the XAML page.
3.  In class Post add property         [NotMapped] public int NotMappedProperty { get; set; }
4. Run "Add-Migration MyFirstMigration". 
5. The repo zipped project has been attached.

### The issue
1. The NotMappedProperty ends up in the database schema even though the NotMappedAttribute has been applied. This can be verified by looking into the generated migration class.
2. Using the App.config has no affect on this though it was applicable for preview2 of tooling.
3. In my main project other attributes like InverseProperty are also not being considered by Add-Migration.

### Further technical details
EF Core version: "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
Operating system: Windows 10 Anniversary Edition
Visual Studio version: VS 2015 Update 3

Other details about my project setup: none
[EFCoreV11AddMigrationRepo.zip](https://github.com/aspnet/EntityFramework/files/598857/EFCoreV11AddMigrationRepo.zip)

**Comment by bricelam** [comment]
Nuts. It looks like we're still going to need a few binding redirects (despite #6916) for unification.

**Comment by rowanmiller** [comment]
@bricelam can you provide the required redirects here so that folks can get unblocked on 1.1

**Comment by bricelam** [comment]
### Workaround
Create two files with the following contents.
* `%USERPROFILE%\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\net451\ef.exe.config`
* `%USERPROFILE%\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\net451\ef.x86.exe.config`
```XML
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.ComponentModel.Annotations" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
        <bindingRedirect oldVersion="4.1.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
