### ISSUE TITLE
Design: Public API to instantiate DbContext classes

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#7050]
Scaffolding is now using `DbContextOperations.CreateContext()` to instantiate contexts at design-time; however, this is an internal API.

Model visualization may require the same functionality.

We should consider adding public API with this functionality.

cc @prafullbhosale

**Comment by bricelam** [comment]
If we do, we should add it to 1.0.3 as well.

**Comment by bricelam** [comment]
@Eilon @ajcvickers Do we want to try and get this into 2.0.0-preview1 too? The work for `Program.BuildWebHost` (#8164) has broken the internal APIs Scaffolding was using...

**Comment by bricelam** [comment]
(and possibly 1.0.4 & 1.1.2)

**Comment by ajcvickers** [comment]
@bricelam Without this, what is broken?  When you say "Scaffolding" I'm not sure which "Scaffolding" that is--reverse engineering, or asp.net scaffolding?

Why would we put it in 1.0.4/1.1.2? What is broken there that this would fix?

**Comment by bricelam** [comment]
The Scaffoding repo. Anything they use a DbContext for is broken.

I'll add back an overload to maintain compatibility in 2.0.0-preview1.

**Comment by ajcvickers** [comment]
@bricelam What's the priority of this for 2.0?

**Comment by bricelam** [comment]
We should do it so Scaffolding doesn't have to rely on internal API. Shouldn't be much work.
