### ISSUE TITLE
.NET Framework compatibility issue

### ISSUE THREAD

**Issue by krs500** [aspnet/EntityFramework#7078]
### Steps to reproduce
When I try to install the `Microsoft.EntityFrameworkCore` NuGet package in my .NET Framework 4.6.2 project, it pulls the whole .NET Standard, which consists of more than 50 additional packages:
![image](https://cloud.githubusercontent.com/assets/1933456/20467526/325959b4-af92-11e6-98d0-210747060ae5.png)

### The issue
This is obviously wrong, and `Microsoft.EntityFrameworkCore` should not pull the `NETStandard.Library` when targeting a full .NET Framework.

### Further technical details

EF Core version: 1.1.0
Operating system: Windows 10 Pro
Visual Studio version: 2015 Update 3

**Comment by rowanmiller** [comment]
Currently this is by-design (and not really specific to EF). The packages add up to ~1.5mb in the deployed app size (the dlls are super slim on full .NET). That said... it is annoying to have all those extra binaries/references/etc. so there is some work underway in upcoming versions to try and improve this.

**Comment by geirsagberg** [comment]
EF Core 1.1.0 depending on NETStandard 1.6.1 for full .NET framework causes a really nasty issue related to https://github.com/dotnet/corefx/issues/11100 for our part.

Specifically, any library depending on the NuGet package System.Net.Http 4.3.0 is incompatible with the full .NET framework 4.6.x.

Please consider reverting this change at least until that issue is fixed; As of today we have only two options:

1. Roll back to EF Core 1.0.2 and lose the improvements in 1.1.0,
2. Use 1.1.0 with the horrible workarounds for assembly redirection described in https://github.com/dotnet/corefx/issues/11100

**Comment by divega** [comment]
Reopening so that we can talk about this in triage.

**Comment by divega** [comment]
Adding @pranavkm and @Eilon 

We would like to understand when the fix for https://github.com/dotnet/corefx/issues/11100 is happening as well if there is anything we could do in 1.1.1 version of EF Core and is dependencies to help.

**Comment by Eilon** [comment]
We can't remove/change references in a patch release. But I expect in 2.0 that this issue will be resolved.

**Comment by divega** [comment]
@Eilon as discussed we would like to ask if dotnet/corefx#11100 can be addressed in a patch release before we consider more impactful workarounds (e.g. changing dependencies of EF Core for the .NET Framework targets). 

What would be the best way to drive towards a resolution? Would the "blocking-partner" label help? 

Also the impact of these issues on applications using `Microsoft.Extensions` libraries (but not EF Core) has also been reported at https://github.com/aspnet/Home/issues/1889. 

And BTW dotnet/sdk#514 also seems related and describes other possible incompatibilities between `NETStandard.Library` and .NET Framework.

**Comment by divega** [comment]
Other issues related under aspnet:
- https://github.com/aspnet/Security/issues/1046 
- https://github.com/aspnet/JavaScriptServices/issues/487

**Comment by divega** [comment]
Clearing up milestone to discuss this next week given some new information.

**Comment by Eilon** [comment]
@anurse does this get fixed by us doing https://github.com/aspnet/Coherence-Signed/issues/389 / https://github.com/aspnet/Coherence-Signed/issues/400 ?

**Comment by anurse** [comment]
No, it wouldn't be affected. In fact, the fix involves introducing **more** package references to replace framework references.

**Comment by Eilon** [comment]
Moving to `External` milestone per yesterday's discussion.

**Comment by Eilon** [comment]
@bricelam given that https://github.com/dotnet/corefx/issues/11100 is closed, can we double check the scenario here, and if we're satisfied, close this issue?

**Comment by bricelam** [comment]
It looks fixed to me.

**Comment by Eilon** [comment]
Great!
