### ISSUE TITLE
DbSetInitializer does not check if type is not added to model

### ISSUE THREAD

**Issue by jamesrich0855** [aspnet/EntityFramework#7094]
I am using GetKpiMeasures() to return an IQueryable collection for a grid. The query string returns the correct data with no nulls when run in SQL Server. However the FromSql() call fails.

Any ideas about what the problem is here please?

### Steps to reproduce

        public IQueryable<KpiMeasure> GetKpiMeasures()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("Select Distinct kpim.Id, IsNull(kpin.Description, '') As Name, ");
            sb.Append("Coalesce(NullIf(kpif.FormulaText, ''), NullIf(kpiagg.Description, '') + '(' + NullIf(m.Description, '') + ')', '') As Formula, ");
            sb.Append("IsNull(kpis.Description, '') As Site, IsNull(am.Description, '') As AssocMeasure, kpim.IsVariableKpi, kpim.IsActive ");
            sb.Append("From Kpis.Measurelist ml ");
            sb.Append("Inner Join Kpis.KpiMeasure kpim on ml.KpiMeasureId = kpim.Id ");
            sb.Append("Inner Join Kpis.Measure m on ml.MeasureId = m.id ");
            sb.Append("Inner Join Kpis.Kpi kpi on kpim.Id = kpi.KpiMeasureId ");
            sb.Append("Inner Join Kpis.KpiName kpin on kpi.KpiNameId = kpin.Id ");
            sb.Append("Left Join Kpis.Measure am on kpim.AssociatedMeasureId = am.Id ");
            sb.Append("Left Join Kpis.Formula kpif on kpim.FormulaId = kpif.Id ");
            sb.Append("Left Join Maintenance.AggregatorFunction kpiagg on kpim.AggregatorFunctionId = kpiagg.Id ");
            sb.Append("Left Join Maintenance.Site kpis on kpim.SiteId = kpis.Id ");
            sb.Append("Where kpim.IsActive = 1 ");
            sb.Append("Order By Name");
            string query = sb.ToString();

            var temp = _context.KpiMeasureLists.FromSql(query);

            var kpiMeasures = temp.Select(t => KpiMeasure.Create(t.Id, t.Name, t.Formula, t.Site, t.AssocMeasure, t.IsVariableKpi, t.IsActive));

            return kpiMeasures;
        }

    public class KpiMeasureList
    {
        public KpiMeasureList() { }
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Formula { get; set; }
        public string Site { get; set; }
        public string AssocMeasure { get; set; }
        public bool? IsVariableKpi { get; set; }
        public bool? IsActive { get; set; }
    }
### The issue
Fails at line "var temp = _context.KpiMeasureLists.FromSql(query);" in GetKpiMeasures().
temp has type IQuerable<KpiMeasureList>, but is empty with internal errors
KpiMeasureLists is defined as public DbSet<KpiMeasureList> KpiMeasureLists { get; set; } in the context

Exception message:Value cannot be null. Parameter name: entityType
Stack trace:
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.SqlServerMetadataExtensions.SqlServer(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
   at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)

### Further technical details

EF Core version: 1.0.0-preview2-final
Operating system: Windows 10 64bit
Visual Studio version: VS 2015

Other details about my project setup:

**Comment by smitpatel** [comment]
Generated query:
```
SELECT [t].[Id], [t].[Name], [t].[Formula], [t].[Site], [t].[AssocMeasure], [t].[IsVariableKpi], [t].[IsActive]
      FROM (
          Select Distinct kpim.Id, IsNull(kpin.Description, '') As Name, Coalesce(NullIf(kpif.FormulaText, ''), NullIf(kpiagg.Description, '') + '(' + NullIf(m.Description, '') + ')', '') As Formula, IsNull(kpis.Description, '') As Site, IsNull(am.Description, '') As AssocMeasure, kpim.IsVariableKpi, kpim.IsActive From Kpis.Measurelist ml Inner Join Kpis.KpiMeasure kpim on ml.KpiMeasureId = kpim.Id Inner Join Kpis.Measure m on ml.MeasureId = m.id Inner Join Kpis.Kpi kpi on kpim.Id = kpi.KpiMeasureId Inner Join Kpis.KpiName kpin on kpi.KpiNameId = kpin.Id Left Join Kpis.Measure am on kpim.AssociatedMeasureId = am.Id Left Join Kpis.Formula kpif on kpim.FormulaId = kpif.Id Left Join Maintenance.AggregatorFunction kpiagg on kpim.AggregatorFunctionId = kpiagg.Id Left Join Maintenance.Site kpis on kpim.SiteId = kpis.Id Where kpim.IsActive = 1 Order By Name
      ) AS [t]
```
@jamesrich0855 - Can you share your full DbContext class? I am not able to repro based on information provided above.

**Comment by jamesrich0855** [comment]
[KpiContext.zip](https://github.com/aspnet/EntityFramework/files/607789/KpiContext.zip)

**Comment by jamesrich0855** [comment]
smitpatel,

Thanks for the reply. I have uploaded the DBContext file.

I have also upgraded to version 1.1.0. This did not fix the problem.
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.NETCore.App": "1.1.0",

I ran the generated query you supplied on SQL Server and got this error:
Msg 1033, Level 15, State 1, Line 4
The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.
Removing the Order By clause made the query run in SQL Server. I'll modify the application and let you know how it goes.

**Comment by smitpatel** [comment]
@jamesrich0855 - EntityType `KpiMeasureList` is ignored in `OnModelCreating`. At present `FromSql` does not support composing into types not included in model. The tracking issue is #1862 
Since `KpiMeasureList` is ignored, the above query will not work. It should throw exception earlier when trying to create DbSet but there is bug in DbSetInitializer therefore you got exception in query.
As for the generated query, it is invalid query for SqlServer. We do not try to parse or reason about the user provided query in `FromSql`. Instead we just wrap it in subquery if it is compostable and send appropriate query to server. Since there is subquery above issue can arise. Which we really cannot detect easily. And it is easy for user to change the query string in `FromSql`.

**Comment by divega** [comment]
@jamesrich0855 @smitpatel Regarding the query with ORDER BY not being composable, an easy workaround that SQL Server supports is to add TOP 100%, e.g.

``` SQL
SELECT TOP (100) PERCENT [t].[Id], [t].[Name], [t].[Formula], [t].[Site], [t].[AssocMeasure], [t].[IsVariableKpi], [t].[IsActive]
      FROM (
          Select Distinct kpim.Id, IsNull(kpin.Description, '') As Name, Coalesce(NullIf(kpif.FormulaText, ''), NullIf(kpiagg.Description, '') + '(' + NullIf(m.Description, '') + ')', '') As Formula, IsNull(kpis.Description, '') As Site, IsNull(am.Description, '') As AssocMeasure, kpim.IsVariableKpi, kpim.IsActive From Kpis.Measurelist ml Inner Join Kpis.KpiMeasure kpim on ml.KpiMeasureId = kpim.Id Inner Join Kpis.Measure m on ml.MeasureId = m.id Inner Join Kpis.Kpi kpi on kpim.Id = kpi.KpiMeasureId Inner Join Kpis.KpiName kpin on kpi.KpiNameId = kpin.Id Left Join Kpis.Measure am on kpim.AssociatedMeasureId = am.Id Left Join Kpis.Formula kpif on kpim.FormulaId = kpif.Id Left Join Maintenance.AggregatorFunction kpiagg on kpim.AggregatorFunctionId = kpiagg.Id Left Join Maintenance.Site kpis on kpim.SiteId = kpis.Id Where kpim.IsActive = 1 Order By Name
      ) AS [t]
```

This avoid the error but will not guarantee that the order is preserved after composing the query further, so you might just as well move the ORDER BY clause outside of the SQL query and add it back as a LINQ `OrderBy()` call at the of your query composition.

**Comment by jamesrich0855** [comment]
OK, that is what is going on.
The original query was OK until wrapped in a subquery. I did not think to check the generated query.
If the DISTINCT is removed from the query, duplicate records are returned. I was unable to remove these using a LINQ query as Distinct had no effect and GroupBy does not work yet.
KpiMeasureList is a "dummy" table in the DbContext as a work around. Looks like I will need to return the full list with LINQ and remove the duplicates myself. Not ideal, but the full list is about 150 records, so acceptable for now.

Thanks divega, your comment arrived as I was typing. I will try your solution.

**Comment by divega** [comment]
@jamesrich0855 FYI, I edited the SQL in my comment (I had added the TOP 100% to the wrong query).

**Comment by jamesrich0855** [comment]
divega,

Thanks again, I should have read your reply more carefully. That fixes the SQL, but the problem is the dummy table in the DbContext.

**Comment by divega** [comment]
@jamesrich0855 agreed. BTW, besides #1862, another approach we have thought about is to allow entity types to be included in the model that are not mapped to an actual table. 

If you are using EF Core migrations this would be equivalent to including (i.e. not ignoring) KpiMeasureList in the model, but then taking out any scaffolded migrations that try to create or modify that corresponding table in the database. EF Core will "think" that the entity is mapped and that the table exist so it will allow using the type in `FromSql()` calls.

**Comment by jamesrich0855** [comment]
I think allowing "dummy" tables in the DbContext is a good idea, especially for reports and complex grids which draw from many tables in the database. That way, most of the work can be done at the database level.
Thanks for your help, I now have the collection filling correctly. Performance is good, but the object numbers small. I'll wait for the GroupBy clause to be working.
For anyone coming later, here is the current code.

        public IQueryable<KpiMeasure> GetKpiMeasures()
        {
            //TODO: Impliment a better solution when GroupBy clause is working in EF7
            //items.GroupBy(test => test.Name)
            //.Select(grp => grp.First());
            List<KpiMeasure> kpiMeasures = new List<KpiMeasure>();

            var items = (from ml in _context.MeasureLists.AsNoTracking()
                       join kpim in _context.KpiMeasures.AsNoTracking() on ml.KpiMeasureId equals kpim.Id
                       join m in _context.Measures.AsNoTracking() on ml.MeasureId equals m.Id
                       join kpi in _context.Kpis.AsNoTracking() on kpim.Id equals kpi.KpiMeasureId
                       join kpin in _context.KpiNames.AsNoTracking() on kpi.KpiNameId equals kpin.Id
                       join a in _context.Measures.AsNoTracking() on kpim.AssociatedMeasureId equals a.Id into am
                       join f in _context.Formulas.AsNoTracking() on kpim.FormulaId equals f.Id into fm
                       join agg in _refContext.AggregatorFunctions.AsNoTracking().ToList() on kpim.AggregatorFunctionId equals agg.Id into aggm
                       join s in _refContext.Sites.AsNoTracking().ToList() on kpim.SiteId equals s.Id into sm
                       from assocm in am.DefaultIfEmpty(new Kpis.Domain.Measure { Description = "" })
                       from formula in fm.DefaultIfEmpty(new Kpis.Domain.Formula { FormulaText = "" })
                       from aggFunc in aggm.DefaultIfEmpty(new Maintenance.Domain.AggregatorFunction { Description = "" })
                       from site in sm.DefaultIfEmpty(new Maintenance.Domain.Site { Description = "" })
                       where kpim.IsActive
                       orderby kpin.Description
                       select
                       new
                       {
                           kpim.Id,
                           Name = kpin.Description,
                           formula.FormulaText,
                           AggFunc = aggFunc.Description,
                           MeasureName = m.Description,
                           Site = site.Description,
                           AssocMeasure = assocm.Description,
                           kpim.IsVariableKpi,
                           kpim.IsActive
                       }).ToList();

            string previousName = "";
            foreach (var item in items)
            {
                if (!previousName.Equals(item.Name))
                {
                    previousName = item.Name;
                    kpiMeasures.Add(KpiMeasure.Create
                    (
                        item.Id,
                        item.Name,
                        string.IsNullOrEmpty(item.FormulaText) ? item.AggFunc + "(" + item.MeasureName + ")" : item.FormulaText,
                        item.Site,
                        item.AssocMeasure,
                        item.IsVariableKpi,
                        item.IsActive
                    ));
                }
            }

            return kpiMeasures.AsQueryable();
        }

**Comment by jamesrich0855** [comment]
Sorry, did not mean to reopen.

**Comment by ajcvickers** [comment]
Re-opening so we can triage/track the DbSetInitializer issue.
