### ISSUE TITLE
ExecuteSqlCommand/Async usability issues

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#7100]
1) When passing a strongly typed array for the parameters arg: E.g.
```c#
context.Database.ExecuteSqlCommand(
    "SELECT * FROM Orders WHERE OrderID = {0} OR CustomerID = {1}", 
    new [] { 1, 2 }));
```
We crash because the parameters object[] ends up with a single int[] element.

2) The Async overloads require passing a cancellation token when specifying parameters.

Test coverage of these methods is low. We should beef it up.

**Comment by rowanmiller** [comment]
We should look at adopting the pattern we use elsewhere for async methods (not combining `params` and `CancellationToken`). We should also look at an overload that takes an IEnumerable of parameters rather than `params`.
