### ISSUE TITLE
System.AggregateException occurred.  InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by mdmoura** [aspnet/EntityFramework#7119]
### Steps to reproduce

I have the following Entities in Entity Framework Core 1.1:

``` C#
    public class Question {
      public Int32 Id { get; set; }
      public Int32 AuthorId { get; set; }
      public String Content { get; set; }
      public virtual User Author { get; set; }
      public virtual ICollection<Answer> Answers { get; set; }
    } 

    public class Answer {
      public Int32 Id { get; set; }
      public Int32 QuestionId { get; set; }
      public Int32 AuthorId { get; set; }
      public String Content { get; set; }  
      public virtual Question Question { get; set; }
      public virtual User Author { get; set; }
    }

    public class User : IdentityUser<Int32> {
      public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();
      public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
    }

    public class Context : IdentityDbContext<User, Role, Int32> {
      public DbSet<Answer> Answers { get; set; }
      public DbSet<Question> Questions { get; set; }

      public Context(DbContextOptions<Context> options) : base(options) { }

      protected override void OnModelCreating(ModelBuilder builder) {
        base.OnModelCreating(builder);

        builder.Entity<Question>(b =>
          b.ToTable("Questions");
          b.HasKey(x => x.Id);
          b.Property(x => x.Content).HasMaxLength(400).IsRequired(true);
          b.HasOne(x => x.Author).WithMany(x => x.Questions).HasForeignKey(x => x.AuthorId).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
        });

        builder.Entity<Answer>(b =>
          b.ToTable("Answers");
          b.HasKey(x => x.Id);
          b.Property(x => x.Content).HasMaxLength(4000).IsRequired(true);
          b.HasOne(x => x.Author).WithMany(x => x.Answers).HasForeignKey(x => x.AuthorId).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
          b.HasOne(x => x.Question).WithMany(x => x.Answers).HasForeignKey(x => x.AuthorId).IsRequired(true).OnDelete(DeleteBehavior.Cascade);        
        });
      }
    }
```

### The issue

I tried to create a list of questions (in the following code I am adding only one):

``` C#
        List<Question> questions = new List<Question>();

        questions.Add(new Question {
          Approved = DateTime.UtcNow,
          Author = context.Users.First(),
          Content = "question",
          Created = DateTime.UtcNow,
          IsApproved = true,
          Level = context.Levels.First(),
          Updated = DateTime.UtcNow,
          Answers = new List<Answer> {
            new Answer {
              Approved = DateTime.UtcNow,
              Author = context.Users.Last(),
              Content = "answer",
              Created = DateTime.UtcNow,
              IsApproved = true,
              Updated = DateTime.UtcNow  
            }
          }
        });

        context.AddRange(questions);
        await context.SaveChangesAsync();
```

When adding the questions I get the following error:

```
    System.AggregateException occurred   
    InvalidOperationException: Collection was modified; enumeration operation may not execute.
```

This was working on EntityFramework 1.0.1. I got the error when migrating to 1.1.

If I comment the code line `Author = context.Users.Last(),` in Answer then it works fine.

Am I missing something?

### Further technical details

EF Core version: 1.1
Visual Studio version: VS 2017 RC

**Comment by ajcvickers** [comment]
@mdmoura Can you post the stack trace?

**Comment by mdmoura** [comment]
@ajcvickers 

The stack trace is the following:

`
Unhandled Exception: System.AggregateException: One or more errors occurred. (Collection was modified; enumeration operation may not execute.) ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
   at WebProj.DataSeedExtensions.<SeedDataAsync>d__5.MoveNext() in c:\...\WebProj\DataSeedExtensions.cs:line 74
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WebProj.DataSeedExtensions.SeedData(IApplicationBuilder builder, DataSeedType type) in c:\...\WebProj\DataSeedExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebProj.Program.Main(String[] args) in c:\...\WebProj\Program.cs:line 14
`

Does it help? 

What is strange is that the same code worked fine in ASP.NET Core 1.0.1
