### ISSUE TITLE
Suggestion: Enhance issue template

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#7134]
Request information about which EF provider the issue concerns, often issues now  appear to be provider specific and there are also more 3rd party providers available now

**Comment by rowanmiller** [comment]
Great idea, I will do this.

**Comment by rowanmiller** [comment]
Done in https://github.com/aspnet/EntityFramework/commit/b31c3d762c868fb96cfa92f482ed89c1802761ae
