### ISSUE TITLE
ConventionSet API XML Document Error

### ISSUE THREAD

**Issue by hqywork** [aspnet/EntityFramework#7177]
### The issue

XML Document on "IndexRemovedConventions" of "ConventionSet" has error, should was "Removed".

[Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/Metadata/Conventions/ConventionSet.cs)

**Comment by smitpatel** [comment]
Can I poach this? :trollface:

**Comment by hqywork** [comment]
What is the 'poach'?





At 2017-04-28 14:24:14, "Smit Patel" <notifications@github.com> wrote:


Can I poach this?

**Comment by smitpatel** [comment]
poach
VERB
illegally hunt or catch (game or fish) on land that is not one's own, or in contravention of official protection.
synonyms: hunt illegally · catch illegally · jacklight · jack · steal

In simple terms, I wanted to take over the issue so I can fix it 😄

**Comment by hqywork** [comment]
I see. OK.





在 2017-05-02 09:02:10，"Smit Patel" <notifications@github.com> 写道：


poach
VERB
illegally hunt or catch (game or fish) on land that is not one's own, or in contravention of official protection.
synonyms: hunt illegally · catch illegally · jacklight · jack · steal

In simple terms, I wanted to take over the issue so I can fix it 😄
