### ISSUE TITLE
OrderBy with Contains emits invalid SQL to the DB

### ISSUE THREAD

**Issue by gdoron** [aspnet/EntityFramework#7178]
var headerStories = await _context.Stories
                .Where(x => x.IsPublished)
                .Include(x => x.StoryCategories)
                .ThenInclude(x => x.Category)
                .ThenInclude(x => x.ParentCategory)
                .Include(x => x.Images)
                .Include(x => x.User)
                .OrderByDescending(x => headerIds.Contains(x.Id))
                .OrderByDescending(x => x.PublishDate)
                .Take(3)
                .AsNoTracking()
                .ToListAsync();

### SQL:

> SELECT TOP(@__p_1) [x].[Id], [x].[ActivityLocation], [x].[CanNotBeFeaturedOnHomePage], [x].[City], [x].[Country], [x].[GooglePlaceId], [x].[InsertDate], [x].[IsDeleted], [x].[IsProductsReviewed], [x].[IsPublished], [x].[LastUpdateDate], [x].[Latitude], [x].[LikesCount], [x].[Longitude], [x].[PostalCode], [x].[PublishDate], [x].[Quote], [x].[State], [x].[StreetName], [x].[StreetNumber], [x].[Title], [x].[UsedProducts], [x].[UserId], [x].[ViewsCount], [x].[YouTubeId], [u].[Id], [u].[AboutMe], [u].[AccessFailedCount], [u].[City], [u].[ConcurrencyStamp], [u].[Country], [u].[Email], [u].[EmailConfirmed], [u].[FirstName], [u].[HeaderImageUrl], [u].[InsertDate], [u].[InstagramUserName], [u].[LastName], [u].[Latitude], [u].[Location], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[Longitude], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[PictureUrl], [u].[PostalCode], [u].[SecurityStamp], [u].[State], [u].[TwoFactorEnabled], [u].[UserName]
FROM [Stories] AS [x]
INNER JOIN [Users] AS [u] ON [x].[UserId] = [u].[Id]
WHERE [x].[IsPublished] = 1
ORDER BY [x].[PublishDate] DESC, [x].[Id] IN (379) DESC, [x].[Id]

EF Core version: (1.0.0) - sorry can't upgrade to 1.1.0 yet.
Operating system:  Windows 10
Visual Studio version: (VS 2015)

I don't think the entire model classes are required, let me know if not.

Thanks.

**Comment by gdoron** [comment]
p.s. I'm not looking for a workaround like splitting the query into two, as I already did that.
I'm just reporting the bug.

**Comment by maumar** [comment]
This works in the current bits. We produce the following query (removed includes for simplicity):

```sql
SELECT TOP(@__p_1) [x].[Id], [x].[IsPublished], [x].[PublishDate]
FROM [Stories] AS [x]
WHERE [x].[IsPublished] = 1
ORDER BY [x].[PublishDate] DESC, CASE
    WHEN [x].[Id] IN (1, 2, 3)
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END DESC
```

**Comment by gdoron** [comment]
Thanks 🌷
