### ISSUE TITLE
Migrations: Make generated code play well with StyleCop

### ISSUE THREAD

**Issue by patriksvensson** [aspnet/EntityFramework#7189]
### Steps to reproduce
Add a new migration

### The issue
Let me start with saying "Thanks for an awesome project".

This isn't a huge problem, but for all of us that uses StyleCop, adding a new migration creates a lot of warnings (and errors for release builds where warnings-as-errors are enabled).

* Namespaces in `Migrations/MyAppDbContextModelSnapshot` are not ordered alphabetically.
* Namespaces in `Migrations/20161205224611_MyMigration.cs` are not ordered alphabetically.
* Namespaces in `Migrations/20161205224611_MyMigration.Designer.cs` are not ordered alphabetically.
* Access modifier for `Migrations/MyAppDbContextModelSnapshot` class is implicit.
* Access modifier for `Migrations/20161205224611_MyMigration.Designer.cs` class is implicit.

I would be happy to provide a PR to fix this if you think it's worth doing.
Another solution to this would be to add the standard `<auto-generated>` header to the generated files.

### Further technical details

EF Core version: (found in project.json or packages.config)
Operating system: Windows 10
Visual Studio version: VS 2015

**Comment by bricelam** [comment]
The implicit modifiers in the `.Designer` partial classes is by design. It allows you to change the class's access in a single location--the migration file. We could probably mark those files as auto-generated since they'll rarely have to be modified after being generated.

**Comment by rowanmiller** [comment]
@patriksvensson we'd love to take a PR on this one. Here is what we think should be done...

* Add `<auto-generated>` to the `.designer` files and to the model snapshot
* Do the alphabetical sorting of using statements

**Comment by rowanmiller** [comment]
Putting on the backlog, but we'd take the PR into 1.2 if it is ready in time.

**Comment by patriksvensson** [comment]
@rowanmiller I can submit a PR for this, but I'm not sure when 1.2 is due (the milestone gives me no information about this).

**Comment by rowanmiller** [comment]
@patriksvensson if you can get it in sometime in the next month or so that would give us time to have it in one of the pre-releases for the next release.

**Comment by patriksvensson** [comment]
@rowanmiller Sounds good to me. I have plenty of free time the next month or so, so sign me up for this one.

**Comment by bricelam** [comment]
Here's where to start digging in: [CSharpMigrationsGenerator](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs) 😉

**Comment by simra** [comment]
Hi, I don't want to re-open this issue but I wonder if it's somehow related to this one, which I encountered while running migrations during a publish step: https://github.com/StyleCop/StyleCop/issues/201  Any insights or suggestions would be appreciated.

**Comment by bricelam** [comment]
Doesn't seem related

**Comment by patriksvensson** [comment]
Is there a specific reason this PR was reverted (or, rather, the functionality was removed)? 

I'm seeing my analyzers light up like a Christmas tree after revisiting the project after a couple of years, and the `<autogenerated />` tag is no longer added to new migrations.

**Comment by vslee** [comment]
Looks like it's still there:
https://github.com/dotnet/efcore/blob/99d0c74454b683a2d432968794b4627dee6b41e3/src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs#L141

**Comment by patriksvensson** [comment]
Odd, because it's not being added to new migrations.
