### ISSUE TITLE
SaveChanges: Unique indexes not taken into account during topological sort

### ISSUE THREAD

**Issue by Jupakabra** [aspnet/EntityFramework#7193]
### Steps to reproduce
```C#
public void Insert()
{
   context.Set<Model>().RemoveRange(context.Set<Model>());
   context.Add(new Model());
   context.SaveChanges();
}
```
### The issue
Execution order is always insert then delete, resulting in unique constraint violations.
As I remember EF6 didn't have these problems because every insert/update/delete was reordered?

### Further technical details

EF Core version: 1.1.0
Operating system: Windows 7 Ultimate

**Comment by ajcvickers** [comment]
@Jupakabra What is the exception message and stack trace you are seeing?

**Comment by Jupakabra** [comment]
Im just getting sql exception
```
Cannot insert duplicate key row in object 'dbo.Model' with unique index 'IX_Model_Title'.
The duplicate key value is (Test).
```

**Comment by smitpatel** [comment]
Our topological sort of commands does sorting for foreign keys only (which takes care of unique indexes created for FK by conventions) but we don't sort commands for explicit unique indexes yet.

**Comment by AndriySvyryd** [comment]
@Jupakabra Could you share the `Model` class and the context?
The topological sort puts deletes before updates and inserts targeting the same table.

**Comment by Jupakabra** [comment]
```C#
public abstract class BaseModel
{
    [Key]
    public Int32 Id { get; set; }
}

public class Model : BaseModel
{
    [Required]
    [StringLength(128)]
    [Index(IsUnique = true)]
    public String Title { get; set; }
}

public class Context : DbContext
{
    protected DbSet<Model> Model { get; set; }

    protected IConfiguration Config { get; }

    public Context(IConfiguration config)
    {
        Config = config;
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        foreach (IEntityType entity in builder.Model.GetEntityTypes())
            foreach (PropertyInfo property in entity.ClrType.GetProperties())
            {
                IndexAttribute index = property.GetCustomAttribute<IndexAttribute>(false);
                if (index != null) builder.Entity(entity.ClrType).HasIndex(property.Name).IsUnique(index.IsUnique);
            }

        foreach (IMutableForeignKey key in builder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            key.DeleteBehavior = DeleteBehavior.Restrict;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder builder)
    {
        builder.UseSqlServer(Config["Data:Connection"]);
    }
}

```
I do however delete it's children and stuff, I will try creating an isolated solution tomorrow, if you can't repro. Maybe some particular scenario doesn't work.

**Comment by AndriySvyryd** [comment]
@Jupakabra Please attach a repro, as I don't see the exception with the code provided so far.

**Comment by Jupakabra** [comment]
[Here's](https://github.com/Jupakabra/UniqueConstraint) a repro, I'm sorry I kind of misinformed you, because I found out that it only happens when entities are being inserted as a part of an object graph.
That is
```C#
context.RemoveRange(context.Set<Relation>());
context.RemoveRange(context.Set<Model>());
context.Add(new Model
{
    Relation = new Relation
    {
        Title = "Title" // Unique
    }
});
```
