### ISSUE TITLE
Set ValueGenerated for store-generated properties using a convention

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#7205]
Currently setting `DefaultValue`, `DefaultValueSql`, `ComputedColumnSql` or `SqlServer().ValueGenerationStrategy` sets `ValueGenerated` in the Fluent API using `ConfigurationSource.Convention`.

This means that `ValueGenerated` is not updated when the mentioned facets are set using the Metadata API.

Also it might get out of date when merging the property facets since it doesn't use the same ConfigurationSource:
If `DefaultValue` is set by convention on base type, but `ComputedColumnSql` is set explicitly on base. When the base type is set the property will have `ComputedColumnSql` configured, but it could still have  `ValueGenerated` set to `OnAdd`

**Comment by divega** [comment]
We should consider looking at other fluent APIs that do multiple things and can switch to using conventions. We should also evaluate if the complexity increase is worth the functional improvement we expect (in this case, mainly it is that setting the value in metadata APIs will have the same observable effect as doing it on the fluent API).

**Comment by love125828499** [comment]
More learning, mutual guidance
