### ISSUE TITLE
Tools: Confusing warning message "The key {'PropertyName'} on entity type 'TypeName' contains properties in shadow state"

### ISSUE THREAD

**Issue by andresmoschini** [aspnet/EntityFramework#7238]
I have migrated from RC2 and now I am having this warning when I generate migrations:

`The key {'Id'} on entity type 'ExtraDeliveryCostByVolume' contains properties in shadow state - {'Id'}. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'CoreEventId.ModelValidationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.`

I understand that `Id` property is shadow, it is true, but, why is it a warning? is there any problem on having a shadow property as primary key?

The model is configured in the follow way:

```c#
  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    . . .
    modelBuilder.Entity<ExtraDeliveryCostByVolume>(entity =>
    {
      entity.Property<int>("Id").UseSqlServerIdentityColumn();
      entity.Property(x => x.ExtraDeliveryCost).HasColumnType("decimal(12,8)");
      entity.HasKey("Id");
      . . .
```

### Further technical details

EF Core version: 1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: Visual Studio 2015

**Comment by divega** [comment]
**EF Team Triage**: We believe we shouldn't warn, at least if the key was created explicitly in shadow state. We can discuss what to do if we would ever create the key by convention, but we can't remember if we ever do that.

**Comment by smitpatel** [comment]
Can I poach this?
