### ISSUE TITLE
PMC: dotnet exec needs a managed .dll or .exe extension

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#7241]
Sometimes on VS2017 (haven't figured out why yet), the `NuGetPackageRoot` property goes missing on the new .NET Core projects. This results in the following error.

> dotnet exec needs a managed .dll or .exe extension. The application specified was 'bin\Debug\netcoreapp1.0\ConsoleApp1.runtimeconfig.json'

I've mitigated this in the [feature work nightly builds](https://dotnet.myget.org/gallery/aspnetcore-feature-work), but we should try to get to the bottom of it.

**Comment by Ponant** [comment]
I just has this issue with VS 2017 on the 12.12.2016 update. What I do not get is that the one week-old project (under the previous release of VS 2017 RC) still runs fine, but I get the error you mention with add-migration the package manager console for a new .Net Core Console. I assume there is no workaround (?) for now.

**Comment by Ponant** [comment]
Might be related (it is in my case)
https://developercommunity.visualstudio.com/content/problem/3341/issue-when-running-migrated-xproj-projects-oldtree.html
https://developercommunity.visualstudio.com/content/problem/4809/systemargumentexception-the-given-trees-are-not-re.html
https://developercommunity.visualstudio.com/content/problem/7427/cusersusernamepath-appears-in-solution-explorer-th.html

**Comment by bricelam** [comment]
It might, but you should be using 1.0.0-msbuild2-final (or the aspnet-feature-work nightlies) on VS 2017.

**Comment by haefele** [comment]
I'm running into the same issue, is there a workaround?

**Comment by bricelam** [comment]
You can probably add the following inside a `PropertyGroup` to make it work on the NuGet releases.

```xml
<NuGetPackageRoot> $(USERPROFILE)\.nuget\packages\</NuGetPackageRoot>
```
