### ISSUE TITLE
Wrong url in Wiki page

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#7244]
This page: https://github.com/aspnet/EntityFramework/wiki/Getting-and-Building-the-Code
Include this advice: 

1. Check that https://myget.org/gallery/aspnetcidev and https://nuget.org are accessible.

Maybe change to:
1. Check that the package source URLs listed in the Nuget.config file in the root of the repository are accessible.

**Comment by Eilon** [comment]
Plus, that's the wrong MyGet feed!

**Comment by ErikEJ** [comment]
@Eilon Exactly, that is what I meant by "wrong url" - better to just refer to nuget.config, as they change over time

**Comment by Eilon** [comment]
@ErikEJ ah, sure. I think it would be valuable to put the exact feed in there though. It doesn't change very often...

**Comment by rowanmiller** [comment]
Updated
