### ISSUE TITLE
Child entities not persisting when using AddRangeAsync and SaveChangesAsync

### ISSUE THREAD

**Issue by cdarrigo** [aspnet/EntityFramework#7298]
Attempting to add a graph of entities where there is a 1:m relationship (parent: children) using the AddRangeAsync and Savechanges Async method will prevent the children from being persisted to the DB.

In the code below, the a collection of StoreProductEntity (Parent) are being persisted in the DBContext . Each StoreProductEntity has an IList<StoreProductPriceEntity> (child).  After calling AddRangeAsync() and SaveChangesAsync(), only the parent entities are persisted, the children are not.

This is different behavior than the corresponding synchronous methods, AddRange() and SaveChanges(), where in the entire graph (parent and children) are persisted to the DB.

```c#
[Table("StoreProduct")]
    public class StoreProductEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        
        public virtual IList<StoreProductPriceEntity> Prices { get; set; }

    }
    [Table("StoreProductPrice")]
    public class StoreProductPriceEntity
    {
        public int Id { get; set; }
        public decimal SalesPrice { get; set; }
        public virtual StoreProductEntity StoreProduct { get; set; }
        public int StoreProductId { get; set; }
    }

    public class Provider
    {
        private readonly DataContext dataContext;

        public Provider(DataContext dataContext)
        {
            this.dataContext = dataContext;
        }
        public async Task<int> AddAndSaveAsync(IEnumerable<StoreProductEntity> entities)
        {
            await this.dataContext.StoreProducts.AddRangeAsync(entities);
            var numAdded = await this.dataContext.SaveChangesAsync();
            // StoreProductEntities are saved, the children StoreProductPrice entities are not saving.
            return numAdded;
        }
    }

    public class Sample
    {
        private readonly Provider provider;

        public Sample(Provider provider)
        {
            this.provider = provider;
        }
        public async Task<int> SaveEntitiesSample()
        {
            var entities = new List<StoreProductEntity>
            {
                new StoreProductEntity
                {
                    Name = "A",
                    Prices = new List<StoreProductPriceEntity>
                    {
                        new StoreProductPriceEntity {SalesPrice = 1m}
                    }
                },
                new StoreProductEntity
                {
                    Name = "B",
                    Prices = new List<StoreProductPriceEntity>
                    {
                        new StoreProductPriceEntity {SalesPrice = 2m}
                    }
                }
            };

            // This call will persist the StoreProducts, but not the nested storeproductPrices.
            return await this.provider.AddAndSaveAsync(entities);

            //Also Tried. 
            foreach (var entity in entities)
            {
                foreach (var price in entity.Prices)
                {
                    price.StoreProduct = entity;
                }
            }
            // same result.  Store Products are persisted, but not the nested/child storeproductprices.
            return await this.provider.AddAndSaveAsync(entities);


        }
    }
```

### Further technical details
EF Core version: 1.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE:  Visual Studio 2015

**Comment by mkprajeen** [comment]
I too face same issue while adding enity with child collection using AddRangeAsync with  SaveChangesAsync

**Comment by ajcvickers** [comment]
Note for triage: looks like async Add methods are, at least sometimes, only acting on a single object.

@cdarrigo @mkprajeen You almost certainly don't need to use the async methods for Add/AddRange. They provide no benefit over the sync versions except when using the specialized sequence value generator. (It would be great to know if you are actually using that value generator.)

**Comment by mkprajeen** [comment]
It works fine when I changed to AddRange instead of AddRangeAsync.  thanks ajcvickers

**Comment by ajcvickers** [comment]
@divega @rowanmiller Should this also go in 1.1.1? AddAsync first shipped in 1.1.

**Comment by rowanmiller** [comment]
To me it seems like a serious enough issue to warrant a patch.

**Comment by ajcvickers** [comment]
Talked to @divega and moving.

**Comment by ajcvickers** [comment]
Justification: The behavior of Add and AddAsync should be the same. The async versions not doing graph behavior is a copy/paste error.
Risk: Low-risk; copy/paste error.

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by anpete** [comment]
✅ Verified
