### ISSUE TITLE
Attempt to run tests with XUnit VS runner fails

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#7320]
During attempt to run the specification tests using VS Test Explorer from the SQL Compact provider solution, I encountered the issue reported here: https://github.com/xunit/xunit/issues/1062

**Comment by bradwilson** [comment]
The linked issue shows a simple fix: adding an empty, parameterless constructor to SkipReasonTestCase (with some attributes to ward away direct callers).

**Comment by ErikEJ** [comment]
Happy to do a PR based on triage decision!

**Comment by divega** [comment]
Sounds reasonable. @ErikEJ feel free to send a PR.

**Comment by ErikEJ** [comment]
@divega Will do, I would really like to see the VS Test Explorer work (again) with the EF specification tests

**Comment by divega** [comment]
Thanks @ErikEJ. I wonder if this is the only such issue in our tests.

**Comment by ErikEJ** [comment]
@divega Found another one (potential)
