### ISSUE TITLE
CLI Tools: Honor ASPNETCORE_ENVIRONMENT

### ISSUE THREAD

**Issue by Eilon** [aspnet/EntityFramework#7353]
_From @opensrcken on November 2, 2016 7:57_

Representative of the script I'm using when I encounter said bug.

```
SET ASPNETCORE_ENVIRONMENT=Test
dotnet ef database update
```

`env.EnvironmentName` does not not seem to be aware of `ASPNETCORE_ENVIRONMENT` when running the second command. Instead, it is always set to `Development`.

_Copied from original issue: dotnet/core#327_

**Comment by Eilon** [comment]
_From @Petermarcu on January 5, 2017 0:51_

@Eilon , Where's the best place to track this?

**Comment by Eilon** [comment]
Bug might not be in EF, but at least we should start the investigation here.

**Comment by mgolois** [comment]
did you try using "Setx" instead of "Set"?
http://batcheero.blogspot.com/2008/02/set-and-setx.html

**Comment by bricelam** [comment]
We don't currently honor the `ASPNETCORE_ENVIRONMENT` environment variable. You should be able to get it working by using the following.

    dotnet ef database update --environment %ASPNETCORE_ENVIRONMENT%

**Comment by Eilon** [comment]
@bricelam should we add support for that env var? It's a bit gross to tie the two together, but it's also a very common scenario to use EF in ASP.NET.

**Comment by bricelam** [comment]
We should definitely consider it.

**Comment by Eilon** [comment]
I love definite maybes! 😄

**Comment by bricelam** [comment]
It has worked since version 2.0.0-preview1. Note, if you're using PowerShell, the syntax to set an environment variable is different than command prompt:
``` powershell
$env:ASPNETCORE_ENVIRONMENT = 'Production'
```

**Comment by univhack** [comment]
That's great news thanks for the update @bricelam!

**Comment by mrtgr** [comment]
I'm writing $env:ASPNETCORE_ENVIRONMENT = 'Production' in Package Manager Console and then tunning Update-Database but still gives the same warning "No Migrations were applied". It is still not respecting to my ASPNETCORE_ENVIRONMENT.

**Comment by ajcvickers** [comment]
@mrtgr Can you please file a new issue and include a runnable project/solution that demonstrates the behavior you are seeing?

**Comment by 242846** [comment]
I have recently had a problem with EF tool not using connection strings from my "appsettings.Production" file, it Turns out that if EF Tool has trouble with the "appsettings.Production"(E.g null string) , it will revert to using appsettings. I have not been able to see this written to the console by the EF tool, but using the "-verbose" flag with database update, the environment will be written to the console. Just wanted to mention this as I have not seen this documented anywhere.
