### ISSUE TITLE
Query : ToString() method that takes a formatter argument should translated on the server

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#7364]
Currently ToString calls with formatter (e.g ToString("X")) are translated to SQL and the formatter is ignored, we should instead translate it on the client.

**Comment by divega** [comment]
We could consider actually supporting translation in some specific cases.

**Comment by maumar** [comment]
change translating ToString with formatter to the client has been checked in here: 8b0ef7f550cf5ab5b08efed14d079a707306ba2a

**Comment by smitpatel** [comment]
@maumar - Is this fixed?

**Comment by maumar** [comment]
partially: the part about ignoring formatter is fixed (i.e. now we do client evaluation rather than ignoring the formatter), but what @divega was suggesting (i.e. translate some of the formatters to SQL) is not.

**Comment by divega** [comment]
@maumar I think that was a note I took in triage but the original suggestion came from @anpete. If we can take a quick look and what formatters would make a lot of sense to translate then I think we can create a new issue for that and prioritize it in triage.

**Comment by smitpatel** [comment]
We need to do analysis on formatters here. There are multiple formatters for each type, with different set of formatters on client/server side.

**Comment by smitpatel** [comment]
@divega - Can you provide specific set of formatters which we want translated?

**Comment by divega** [comment]
@smitpatel Here is the link to the spec:  [https://github.com/aspnet/EntityFramework/wiki/it-does-not-work-like-that](https://www.youtube.com/watch?v=dQw4w9WgXcQ). 

:trollface:  

Actually, I am glad that you ask because it forces me to think. I believe this issue should have been closed as soon as we took @maumar's fix to switch to client evaluation rather than ignoring the formatters. We can always look into translating specific formatters to SQL based on customer data, but we don't have any at the moment. 

Clearing up the milestone so we can make a final decision in triage.

**Comment by ajcvickers** [comment]
Ensure that we are doing client eval. Wait for feedback before deciding to do any translation of formatters.

**Comment by smitpatel** [comment]
We are doing client eval already. @maumar 's PR fixed it. Looks like we forgot to close the issue earlier.

**Comment by los93sol** [comment]
In my specific issue #10227, evaluating on the client does not resolve the issue for me

**Comment by los93sol** [comment]
For clarity, when and logic is applied to the where then doing this on the client is fine, but when we or the logic together with other fields you have a potential for unexpected results

**Comment by smitpatel** [comment]
@los93sol - Client evaluation does not work by breaking into pieces without consequences. It will translate where clause appropritately & evaluate on in memory whatever cannot and always give correct results regardless of AND/OR logic. If you are having a repro code which demonstrate incorrect results for client evaluation then please file a new issue.
