### ISSUE TITLE
Provide access to referencing entity in TrackGraph

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#7389]
TrackGraph provides the callback with the inbound navigation property that was used to discover the current entity. However, it does not provide access to the actual instance that referenced the current instance. This can then be hard to find if something about that instance is needed, the navigation is uni-directional, and FK values are not yet set. See #7308. It would be trivial to add this information to the EntityEntryGraphNode.

**Comment by tonysneed** [comment]
:+1 On providing access to the referencing entity.
