### ISSUE TITLE
Handle differences in nullability between foreign and principal key properties

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#740]
Fixup often involves taking an FK value and using it to set a principal key value, or vice versa. However, sometimes nullability is different between the two properties; the appropriate value conversions should be performed in such cases.

**Comment by ajcvickers** [comment]
Note for triage: I don't know if this is still an issue since incremental changes may have fixed the issues. There is one place in the code that references this issue--search for #740. Other than that, test coverage should be added where needed and issues fixed as found. Anyone could work on this.

**Comment by rowanmiller** [comment]
Ask @ajcvickers  about this one

**Comment by mikary** [comment]
Reviewed and removed the comment relating to #740 and added test / fix in PR #1557
New test covers non-nullable FK to nullable primary case.
