### ISSUE TITLE
Make sure we throw when an instance of an unmapped derived type is use

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#743]
Regardless of whether inheritance is being mapped in the model, it is always possible that the runtime type of an instance passed to the context is actually an unmapped derived type. In EF6 we explicitly disallowed this, except that we made a special exception for proxies. The fact that we made this exception shows that sometimes using an unmapped derived type can be useful, so it maybe useful to allow this in EF7. However, doing so means that code cannot rely on a certain type, which may result in additional complexity and/or subtle bugs.

**Comment by rowanmiller** [comment]
@smitpatel work with @ajcvickers  on this one

**Comment by rowanmiller** [comment]
Make  we test what happens when you try to map a base type

**Comment by smitpatel** [comment]
Currently when an instance of unmapped derived type is used, we are not able to find the mapped EntityType in the model and we throw following exception
````
Microsoft.Data.Entity.Metadata.ModelItemNotFoundException: The entity type 'DerivedProduct' was not found. Ensure that the entity type has been added to the model.
````
Which looks good enough. Though there are no tests to cover this.
Clearing flags for re-triage.

**Comment by rowanmiller** [comment]
@smitpatel can you add a test for this
