### ISSUE TITLE
Add a version of the ExecuteInTransaction() that supports specifying the isolation level

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#7431]
Currently `IExecutionStrategy.ExecuteInTransaction()` always calls `Context.Database.BeginTransaction()` with no arguments. This means if you want to use an isolation level different from the default you have resort to `Execute()` and calling `BeginTransaction()` explicitly as described at https://github.com/aspnet/EntityFramework/issues/7318#issuecomment-269742840. 

It looks like it would be easy to add an overload that takes the isolation level.

**Comment by AndriySvyryd** [comment]
We also need to add overloads that make the simple use-case easier to use. Currently it looks like this:

```C#
using (var db = new BloggingContext())
{
    var strategy = db.Database.CreateExecutionStrategy();

    strategy.ExecuteInTransaction<object, int>(
        operation: (_) =>
        {
            using (var transaction = db.Database.BeginTransaction())
            {
                db.Blogs.Add(new Blog { Url = "http://blogs.msdn.com/dotnet" });
                db.SaveChanges();

                db.Blogs.Add(new Blog { Url = "http://blogs.msdn.com/visualstudio" });
                db.SaveChanges();

                transaction.Commit();
            }

            return 0;
        },
        verifySucceeded: (_) =>
        {
            return db.Blogs
                .Where(b => b.Url == "http://blogs.msdn.com/dotnet" 
                            || b.Url == "http://blogs.msdn.com/visualstudio")
                .Count() == 2;
        },
        state: null,
        context: db);
}
```
The main issues are:
* Having to specify a `TResult` when there isn't a result. I just used a fake int result to make it compile
* Having to specify `TState` when there isn't any state
* Having to specify `state` and `context` parameters

**Comment by divega** [comment]
Once we improve the usability of the API we should update the connection resiliency doc topic to use it.
