### ISSUE TITLE
PMC Tools: Error when using Docker tools

### ISSUE THREAD

**Issue by glennc** [aspnet/EntityFramework#7439]
VS creates a project that is set as the startup project when you are running a solution inside containers, but it doesn't have any code in it.

This means that if you run Add-Migration without specifying a startup project it will fail. I am told that for some project types we provide an error message telling people what they have to do. Given that it will never be correct to use the docker project for migrations can we do the same here?

//cc @dazhao-msft

**Comment by bricelam** [comment]
*Anything* is possible, Glenn. Shun the non-believer...

**Comment by bricelam** [comment]
I wonder if it's worth trying to work our way backwards from the Docker Compose project to the actual web application project. This will only work when there's a 1:1 relationship between them, but it seems like it would be fairly common to have multiple images in a solution. We'd also have to scan all of the projects which has been brittle in the past.
