### ISSUE TITLE
Integrate updating entity state and the committing of generated values into entities with user-controlled transactions

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#744]
Values generated in the update pipeline are saved in sidecars so that if the save fails these values can be discarded. Currently the values are always committed from sidecars into the actual entity instances when SaveChanges ends. But if the user is handling transactions manually then this commit should not happen until the transaction is committed.

Likewise, entity state is updated at the end of SaveChanges, but again this should only be done when the transaction is actually committed--this is the AcceptChanges functionality in EF6.

**Comment by AndriySvyryd** [comment]
We will add an overload: DbContext.SaveChanges(bool acceptAllChangesOnSuccess) that allows to turn off the automatic AcceptChanges and we will provide ChangeTracker.AcceptAllChanges() that can called manually.
