### ISSUE TITLE
Add paramter objects and service rewriting code to avoid breaking base class D.I. constructors in patch/point releases

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#7465]
When a service is overridden by a provider, the provider must call the base service constructor. This means it becomes a breaking change when base service gets new dependencies such that its constructor needs to change.

We previously implemented a mechanism whereby additional services could be injected as part of the provider service resolution mechanism. This worked because provider services were always registered through a delegate, and so we could add code to that delegate as needed to inject services. Following #7457 services are registered by the provider explicitly in the container, which is much preferable for perf, but means that there is no hook to inject services.

**Comment by jnm2** [comment]
I'm super curious what you come up with. I've hit this in my own unrelated architectures.
I've been thinking about the fact that the BCL best practice for adding parameters to event handlers in a back-compatible way is by defining an `EventArgs` from the start.
Compared to straight up constructor injection it feels like quite some overhead to write a `DependencyArgs` for each class, yet we've done it for every event for years so maybe not as bad is it first seems. The `DependencyArgs` subclass could itself be recognized and constructor injected by the IoC container and it could provide getter-only autoproperties which could be added to at any time.

**Comment by popcatalin81** [comment]
How about just passing a single IServiceCollection parameter to all base services, and to allow customization of per provider create a wrapper IServiceCollection for each provider.

**Comment by ajcvickers** [comment]
@jnm2 @popcatalin81 Passing an IServiceProvider is probably what we will end up doing, but also what we hope to avoid doing because it results in use of the service locator pattern, which then obscures dependencies. I suspect we will use this pattern along with adding [Obsolete] to the existing constructor while at the same time introducing a new constructor with the new dependency added explicitly. Then at next major version rev we will remove the obsolete constructor.

**Comment by ajcvickers** [comment]
Discussed in design meeting and decided to try the parameter object approach for services, using sealed classes. Considered composition, but this would be a big change to the architecture and design of certain services.
