### ISSUE TITLE
Provide good feedback when providers don't implement services

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#7469]
Prior to #7464, providers used a base class as a guide for which services to implement. Services for which there were no defaults had abstract members in the base class, which meant a provider could not ship without having some implementation for all required services.

Post #7464, there is no base class. This means that there is nothing forcing providers to implement required services. If provider doesn't implement a required service, then the application is likely to crash at some point with an unhelpful message from D.I. It would be better if there was some mechanism to either force providers to implement all required services or throw a more helpful message when a service is not implemented.

**Comment by ErikEJ** [comment]
Could the specification tests help with this?

**Comment by ajcvickers** [comment]
@ErikEJ Yes, that is one of the things we have talked about. But I think we can also do more.

**Comment by ajcvickers** [comment]
Discussed in the design meeting and decided:
- Will add test to the specification test focused on this.
- Will not at this time add default implementations that throw
- Will not at this time do automatic validation on service collections
- Will not at this time add other runtime validation that can be called by anyone

**Comment by ajcvickers** [comment]
See also the discussion here: #8818
