### ISSUE TITLE
Trace connection open and close in RelationalConnection

### ISSUE THREAD

**Issue by fitzchak** [aspnet/EntityFramework#7479]
RelationalCommand has tracing but RelationalConnection connection is missing.
Adding ConnectionOpened and ConnectionClosed will help us trace this events in order to integrate with EntityFrameworkProfiler.
A PR is on the way.

**Comment by ajcvickers** [comment]
Re-opening since community PR to complete this was not building and we decided to track the work as a regular issue.

**Comment by anpete** [comment]
Closing as I think @ajcvickers has fully addressed this with the recent diagnostics work.
