### ISSUE TITLE
Disable use of shadow state entities except for model snapshot

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#748]
Shadow state entities (that is entities without any backing CLR types) are not fully supported in many places; most notably query. We should fail early if code tries to use them. However, the Migrations model snapshot does make use of them, so this should be disabled.

**Comment by rowanmiller** [comment]
Work with @bricelam (for model snapshot) and @ajcvickers on this one

**Comment by rowanmiller** [comment]
@smitpatel ask @ajcvickers about this one

**Comment by lajones** [comment]
Note: Reverse Engineering uses shadow state entities too - to represent the entities for which it is about to output the code.

**Comment by rowanmiller** [comment]
@lajones the plan is to throw from DbContext if you try and use a model with shadow entities to actually perform 'context stuff'. Core metadata will still support having them.

**Comment by rowanmiller** [comment]
Decision was to remove shadow entities APIs from ModelBuilder but still allow them in core metadata. We'll block using a model with shadow entities at the DbContext level.

As part of this we should remove the `public virtual EntityBuilder Entity([NotNull] string name)` from `ModelBuilder`
