### ISSUE TITLE
Skip with Count always returns 0

### ISSUE THREAD

**Issue by archanasoni** [aspnet/EntityFramework#7523]
We are working to have Core support for IBM EntityFramework Provider.
For one of our internal test application, we have to skip few rows and and return remaining total number of rows.
Our query is:
context.ArchTable1.OrderBy(c=>c.Id).Skip(1).Count()

It always returns output:
skip count 0
We have used UseRowNumberForPaging() via optionsBuilder.

The similar Application when we run against SQL Server 2008, we do see same issue.
Generated SQL is:
SELECT [t].[c0]
FROM (
    SELECT COUNT(*) AS [c0], ROW_NUMBER() OVER(ORDER BY @@RowCount) AS [__RowNumber__]
    FROM [ArchTable1] AS [a]
) AS [t]
WHERE [t].[__RowNumber__] > 1

With manual modification in above query, if we run from SQL management Studio it returns the desired output:
  SELECT COUNT(*) AS [c0] from
    (select ROW_NUMBER() OVER(ORDER BY @@RowCount) AS [__RowNumber__]
    FROM [ArchTable1] AS [a]
) AS [t]
WHERE [t].[__RowNumber__] > 1

Now questions are:
1. Though user mentioned OrdeyBy clause, but why it's not reflecting in generated query ?
2. PushDownSubquery() basically pushes down the current query. How do we inject some new SQL (i.e. select statement to achieve above working query) in between in current selectExpression ?

**Comment by ajcvickers** [comment]
@archanasoni If you are still using RowNumberForPaging, could you please comment on issue #13959 and let us know why?
