### ISSUE TITLE
Handle creating delegates for private setters on base types

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#753]
Properties can be defined in a base type with a private setter and then overridden. In such cases the setter does not show up in the .NET Reflection metadata for the property in the derived type. We therefore need to use special code to go down the hierarchy and find the private setter on the base type so it can be mapped to a delegate and called. (See EF6 codebase for examples.) (The same is true for getters so we should probably support both cases, although I've never seen the getter case in the wild.)

**Comment by MatthewMWR** [comment]
+1. I got nailed by this my first time out trying EF7 (experienced as per https://github.com/aspnet/EntityFramework/issues/1026 ).

**Comment by phillip-haydon** [comment]
So EF 7 is supporting private setters ?

**Comment by rowanmiller** [comment]
@phillip-haydon They are actually supported already. The following code works with EF7 Beta 4. Private property setters were actually supported in previous version of EF too.

```c#
using Microsoft.Data.Entity;
using System;

namespace ConsoleApplication39
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new BloggingContext())
            {
                db.Database.EnsureCreated();

                db.Blogs.Add(new Blog("romiller.com"));
                db.SaveChanges();

                foreach (var item in db.Blogs)
                {
                    Console.WriteLine(item.Url);
                }
            }
        }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=PrivateSetters;Trusted_Connection=True;");
        }
    }

    public class Blog
    {
        private Blog()
        { }

        public Blog(string url)
        {
            Url = url;
        }

        public int BlogId { get; private set; }
        public string Url { get; private set; }
    }
}
```
