### ISSUE TITLE
Upgrade to VS 2017

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#7538]
Tracking issue

cc @bricelam

**Comment by natemcmaster** [comment]
@bricelam what's the status of #7542 ? EF and MVC are the only un-migrated repos now.

**Comment by bricelam** [comment]
No blocking issues. I'll merge when @divega or @Eilon tell me to. 😄

**Comment by bricelam** [comment]
(I'm holding off as long as possible to give tooling time to bake.)
