### ISSUE TITLE
Query: Translating Date using ".Contains" / EF 1.1.0

### ISSUE THREAD

**Issue by ole1986** [aspnet/EntityFramework#7548]
Using an IEnumarable of DateTime.Date will not properly translated:

Example:

```
ctx.User.Where(p => dates.Contains(p.Created.Date))
```

Will be translated without "Where" condition

```
SELECT [p].[ID], [p].[Created], [p].[UserName]
FROM [User] AS [p]
```

### Workaround

A possible workaround (but of course not the best) is the following:

```
var dateStr = "'" + String.Join("','", dates.Select(p => p.ToString("yyyy-MM-dd"))) + "'";
ctx.User..FromSql("SELECT * FROM User WHERE Cast(Created as date) IN ("+dateStr+")");
```

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by maumar** [comment]
Still repros in current bits. Problem is in SqlTranslatingExpressionVisitor -> VisitSubquery:

```
var aliasExpression = VisitMember(memberItem) as AliasExpression;
```

when trying to create InExpression we expect operand to be an AliasExpression and what we get instead is `"CONVERT"("Date, p.Created")`
