### ISSUE TITLE
Navigations: Inverse one-to-one references not rewritten

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#7573]
In the following queries, the second nav. in each projection (ParentBackNavigation) is not processed during nav. rewrite. In the first case, it triggers a null-ref at execution time, and in the second, the EF.Property call is present in the final compiled query tree.
```c#
context.Children
	.Select(c => new
	{
		c.SelfReferenceBackNavigation,
		c.SelfReferenceBackNavigation.ParentBackNavigation
	});


context.Children
	.Select(c => new
	{
		SelfReferenceBackNavigation
		= EF.Property<IChild3409>(c, "SelfReferenceBackNavigation"),
		ParentBackNavigationB
		= EF.Property<IParent3409>(
			EF.Property<IChild3409>(c, "SelfReferenceBackNavigation"),
			"ParentBackNavigation")
	});
```

**Comment by maumar** [comment]
Test enabled ineabc74efb9f4565bc489f638b3c64755c9b84200
