### ISSUE TITLE
Fix reflection object equality comparisons.

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#7591]
Using '==' to compare reflection objects can fail on some platforms that haven't implemented the operator. I.e. .NET Native.

**Comment by anpete** [comment]
Risk: Very low, moving from '==' to calling the Equals method for reflection object comparisons is essentially a no-op on most platforms because the operator simply delegates to the method anyway.
Impact: High on .NET Native. Enables EF's internal caches to operate correctly on .NET Native.

**Comment by divega** [comment]
Reopening to go through approval process.

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by AndriySvyryd** [comment]
✅ Verified
