### ISSUE TITLE
Missing translators for Math functions in SqlServer provider

### ISSUE THREAD

**Issue by rpawlaszek** [aspnet/EntityFramework#7601]
There is quite a number of [math functions not translated](https://github.com/aspnet/EntityFramework/tree/c9b5916a4e0fff763febea00da793ebd4113632d/src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal): ```Math.Exp, Math.Log10, Math.Log, Math.Sqrt, Math.Acos, Math.Asin, Math.Atan2, Math.Atan, Math.Cos, Math.Sin, Math.Tan```. The implementation is as easy as for the ones translated that derive from [```MultipleOverloadStaticMethodCallTranslator```](https://github.com/aspnet/EntityFramework/blob/c9b5916a4e0fff763febea00da793ebd4113632d/src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionTranslators/MultipleOverloadStaticMethodCallTranslator.cs). Could I ask to implement them? I implemented them locally and they all work fine.

### Further technical details
EF Core version: all
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2015

**Comment by rpawlaszek** [comment]
@rowanmiller what does the label "up-for-grabs" mean?

**Comment by rowanmiller** [comment]
@rpawlaszek we use it to identify items that would be good candidates for a contribution from the community. It doesn't mean we're not going to do it, just that someone from the community may want to pick it up before we get to it.

**Comment by rpawlaszek** [comment]
Great:) As I understand this includes implementing the functionality AND the tests, right? And if I would like to do it is [this](https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md#contributing-code-and-content) the procedure? Sorry if it is obvious, I just haven't done this ever before.

**Comment by rowanmiller** [comment]
@rpawlaszek correct. It is also best to start with a small contribution for your first one. So if you plan to tackle this, probably start with one method until you get the hang of how the process works and the type of feedback you get on the code review etc.

**Comment by rpawlaszek** [comment]
@rowanmiller I started with a [translator for ```Math.Exp```](https://github.com/rpawlaszek/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerMathExpTranslator.cs) looking at the definition of the [translator for ```Math.Abs```](https://github.com/rpawlaszek/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerMathAbsTranslator.cs), included it in [```_methodCallTranslators``` in ```SqlServerCompositeMethodCallTranslator```](https://github.com/rpawlaszek/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerCompositeMethodCallTranslator.cs#L23) and then added [```Where_math_exp```](https://github.com/rpawlaszek/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs#L4825). Any comments?

**Comment by smitpatel** [comment]
@rpawlaszek - Submit a pull request to this repo so that we can review the diff and give you feedback.

**Comment by ErikEJ** [comment]
http://ardalis.com/github-pull-request-checklist - and also check the contributing guide

**Comment by maumar** [comment]
fixed in 074fd1b7afe4da26850eaafbc38e6fae671fd76c

**Comment by rpawlaszek** [comment]
Just a small update as I omitted one more function that is translated 1-1: [```Math.Sign```](https://msdn.microsoft.com/en-us/library/ywb0xks3(v=vs.110).aspx) that [Sql Server supports](https://msdn.microsoft.com/en-us/library/ms188420.aspx)

**Comment by maumar** [comment]
@rpawlaszek please open new PR for that
