### ISSUE TITLE
Bring back Tools

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#7624]
Once Tools RTW, their releases will be back in step with the runtime. We can merge the [aspnet/EntityFramework.Tools](https://github.com/aspnet/EntityFramework.Tools) repo back into this one.

**Comment by natemcmaster** [comment]
cc @Eilon looks like we have another dead repo 😢

**Comment by bricelam** [comment]
Not dead yet. We may need to service the 1.0.0 or 1.1.0 release.

**Comment by Eilon** [comment]
Not dead, done 😄

**Comment by bricelam** [comment]
Note, if we update the EntityFramework repo's servicing branches to csproj I can move that code and the repo can be deleted.

**Comment by Eilon** [comment]
@bricelam that's being considered, but it's a ton of work and I personally believe it's very high risk. That is, how can we guarantee that switching the build system will produce packages that are essentially identical? I guess we could do the binary diffing thing (which I believe you now have experience with)...

**Comment by bricelam** [comment]
I'm all for doing it. In my mind me, it lowers the long term cost of maintenance. I don't think verification will be too difficult. An API diff, embedded resource diff, and nupkg diff could all be automated.
