### ISSUE TITLE
Stop using MOQ

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#7627]
It is rarely used in new tests and tends to cause stability issues when updating dependencies, so we should probably go through and remove it from existing tests.

**Comment by smitpatel** [comment]
Clearing milestone. We may need to or should do it because at present we depend on pre-release version of Moq & we should not release stable 2.0 with pre-release dependency.
https://github.com/aspnet/EntityFramework/blob/dev/build/dependencies.props#L11

**Comment by ajcvickers** [comment]
Since only tests depend on this it is okay to continue to use a pre-release version.

**Comment by bricelam** [comment]
Marking for re-triag. The urgency is higher now that it produces so many restore warnings.

**Comment by mikeharder** [comment]
Do we understand why 4.7 causes tests to fail?

**Comment by smitpatel** [comment]
#7907
