### ISSUE TITLE
Query/Cleanup : remove redundant compilations of subquery models when processing MainFromClause, AdditionalFromClause and Join/GroupJoin clauses

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#7647]
When processing MainFromClause, AdditionalFromClause, JoinClause inner sequence and GroupJoin inner sequence, we first compile the expression and then check if its a subquery (and if so, compile again).

We should revert the order, first try to compile as subquery, and only if that fails compile the second time. This will simplify the query compilation as well as fix some more instances of issue described in https://github.com/aspnet/EntityFramework/issues/7476

**Comment by tuespetre** [comment]
I have addressed this with changes in #7543. It's part of the whole 'impossible to split further' thing.

**Comment by maumar** [comment]
This would be a great candidate to break off that big PR - it should be just few lines of code (call LiftSubquery before CompileMainFromClauseExpression/CompileAdditionalFromClauseExpression/CompileJoinClauseInnerSequenceExpression/CompileGroupJoinInnerSequenceExpression with some extra checks) and it provides decent value on its own.

**Comment by maumar** [comment]
fixed in 49112ba68e5352a8c7d1c1f4ba6cb73176ef7e08
