### ISSUE TITLE
Remove StartsWith, EndsWith, Contains translator for 2.0

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#7656]
Relational currently contains 3 query translators that provide incorrect results - since they are implemented with SQL LIKE and don't escape, % and _ are treated as wildcards and not as literals (#474). These emit warnings about the possibly incorrect results.

2.0 seems like the right version to remove these, forcing providers to write their own, correct translators.

**Comment by rowanmiller** [comment]
@roji feel free to send a PR if you just want to do this 😄
