### ISSUE TITLE
Allow custom SQLite builds (winsqlite3, SQLCipher, etc.)

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#7667]
`Microsoft.Data.Sqlite` has switched to SQLitePCL.raw. By introducing a `Microsoft.EntityFrameworkCore.Sqlite.Core` package, we'll enable consuming projects to choose one of the native SQLite implementations provided by SQLitePCL.raw.

For example, to use `winsqlite3.dll`, use this:
```XML
<ItemGroup>
  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="1.2.0-*"/>
  <PackageReference Include="SQLitePCLRaw.bundle_winsqlite3" Version="1.1.2"/>
</ItemGroup>
```

The current SQLitePCLRaw.bundle_* packages they provide are:
* **e_sqlite3**--An up-to-date version of SQLite configured consistently across platforms
* **green** *(default)*--Same as e_sqlite3 except on iOS where the system's SQLite is used
* **sqlcipher**--A version of SQLite with encryption (exposed via `PRAGMA key`)
* **winsqlite3**--The version of SQLite included in the UWP SDK

You could also "drop" down to using specific providers (e.g. to use the system-wide SQLite library everywhere), but that scenario is more advanced so I won't cover it here.

For more information about SQLitePCL.raw, see [the project's README file](https://github.com/ericsink/SQLitePCL.raw/blob/master/README.md).

**Comment by kaushalswapnil** [comment]
Getting Error in release mode that "'C:\ProgramFiles(x86)\MicrosoftSDKs\UWPNuGetPackages\runtime.win10-x86.microsoft.net.native.compiler\2.1.8\tools\x86\ilc\Tools\nutc_driver.exe ' returned exit code 1	

and Error: NUTC303B:Internal Compiler Error: Method 'instance System.Int32 SQLitePCL.ISQLite3Provider.sqlite3_blob_open(System.IntPtr, System.Byte[], System.Byte[], System.Byte[], System.Int64, System.Int32, System.IntPtr&)' is missing implementation on type 'SQLitePCL.SQLite3Provider_e_sqlite3' from assembly 'SQLitePCLRaw.provider.e_sqlite3' while loading type 'SQLitePCL.SQLite3Provider_e_sqlite3'. while computing compilation roots.

**Comment by bricelam** [comment]
Ensure you're not mixing versions of SQLitePCL.raw packages. Try updating to the latest versions
