### ISSUE TITLE
Design: Allow script/update etc. to run when context is not in target project, but can be found in services

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#7710]
Listing DbContext's will return contexts that are registered in services, even if they reside in another project. Some commands (such as adding a migration) require the target project, since they generate code files, but others only need a context instance and could run by getting the context from services.

Perhaps we could also consider making this work if there is an IDbContextFactory in the target project.

This will help ASP.NET Core publishing.

cc @vijayrkn @mlorbetske

**Comment by ajcvickers** [comment]
@Eilon And this one is "patch proposed" as of  this afternoon. Guess we have some conversions to have. 😺

**Comment by ajcvickers** [comment]
@bricelam Just from reading this it isn't clear why this should go into the patch. Can you explain some more?

**Comment by bricelam** [comment]
This was an ask from the Scaffolding team. Issue aspnet/Tooling#898 describes the end-to-end scenario.

**Comment by Eilon** [comment]
This patch fix is *approved*. Please follow the normal code review / pull request process and make sure you make the change in the correct branch.
