### ISSUE TITLE
Port #7710 to 1.1.2 - Tools: Allow script/update etc. to run when context is not in target project, but can be found in services 

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#7711]
Putting this fix in 1.0 and 1.1 patches will allow ASP.NET Core publishing to rely on the fix.

**Comment by ajcvickers** [comment]
Re-opening for patch approval process.

**Comment by Eilon** [comment]
This patch fix is *approved*. Please follow the normal code review / pull request process and make sure you make the change in the correct branch.

**Comment by Eilon** [comment]
Preview builds of this patch fix should be available on the following feeds:

* https://dotnet.myget.org/gallery/aspnet-1-0-5-may2017-patch-public (for fixes in the 1.0.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-0-5-may2017-patch-public/api/v3/index.json
* https://dotnet.myget.org/gallery/aspnet-1-1-2-may2017-patch-public (for fixes in the 1.1.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-1-2-may2017-patch-public/api/v3/index.json

If you have a chance, please try out these preview builds and let us know if you have any feedback!
