### ISSUE TITLE
Unable to get latest dev build from myget to .NET 4.5.1 class library

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#7791]
Installing the EFCore.Relational package, I get this NuGet error, 
which blocks me from adopting the latest base changes in preparation for 1.2/2.0:

Attempting to gather dependency information for package 'Microsoft.EntityFrameworkCore.Relational.1.2.0-preview1-23731' with respect to project 'EntityFramework.SqlServerCompact40', targeting '.NETFramework,Version=v4.5.1'
Gathering dependency information took 42,82 sec
Attempting to resolve dependencies for package 'Microsoft.EntityFrameworkCore.Relational.1.2.0-preview1-23731' with DependencyBehavior 'Lowest'
Unable to find a version of 'System.Runtime.CompilerServices.Unsafe' that is compatible with 'Microsoft.Extensions.Primitives 1.2.0-preview1-23731 constraint: System.Runtime.CompilerServices.Unsafe (>= 4.4.0-beta-25027-01)'.

### Steps to reproduce
Create a .NET 4.5.1 class library.

Install EFCore.Relational pacakge from dev feed on MyGet   

### Further technical details
EF Core version: 1.2.0-preview1-23731
Database Provider: N/A
Operating system: Windows 10
IDE: VS 2015 with NuGet 3.5.0.1484

**Comment by bricelam** [comment]
I'm surprised to see a `4.4.0` corefx package. I thought we went back to `4.3.0` because of issues like this...

Is this resolved in the latest nightly build (23738)?

**Comment by ErikEJ** [comment]
@bricelam Nope:

Attempting to resolve dependencies for package 'Microsoft.EntityFrameworkCore.Relational.1.2.0-preview1-23738' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Microsoft.EntityFrameworkCore.Relational 1.2.0-preview1-23339'
Unable to resolve dependencies. 'System.Runtime.CompilerServices.Unsafe 4.4.0-beta-24913-01' is not compatible with 'Microsoft.Extensions.Primitives 1.2.0-preview1-23738 constraint: System.Runtime.CompilerServices.Unsafe (>= 4.4.0-beta-25104-02)'.

**Comment by roji** [comment]
Getting a possibly related error... Using VS2017 RTM, the new simplified csproj and the very latest packages from aspnetcore-dev, building fails with error:

```
C:\Program Files\dotnet\sdk\1.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(154,5): error : Unexpected dependency 'System.Runtime.CompilerServices.Unsafe' with no version number. [C:\projects\Npgsql.EntityFrameworkCore.PostgreSQL\src\Npgsql.EntityFrameworkCore.PostgreSQL\Npgsql.EntityFrameworkCore.PostgreSQL.csproj]
```

Adding an explicit package reference with version `4.4.0-*` into my own csproj makes the error go away. Referencing version `4.3.0` warns about multiple versions.

**Comment by roji** [comment]
Got @ErikEJ error while restore. Adding a package reference in all csproj files to version 4.3.0 seems to work around the issue.

**Comment by ErikEJ** [comment]
@roji So ?
- Add NuGet pacakge System.Runtime.CompilerServices.Unsafe version 4.3.0
- Add NuGet package MS.EFCore.Realtional

**Comment by roji** [comment]
@ErikEJ I have the following references in my provider csproj (among others):

```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="1.2.0-*" />
<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.3.0" />
```

I'm getting warnings but stuff seems to work.

**Comment by ErikEJ** [comment]
Thanks; I will give it a try with Classic csproj and Nuget 3.5... There are some many provider changes I need to catch up with

**Comment by roji** [comment]
I feel your pain... I'm also in the midst of a blitz of conversions and build work...

**Comment by ErikEJ** [comment]
not pain - "improvements" for EF Core 2! 😏

**Comment by bricelam** [comment]
We <3 you guys. We're trying to get all of the planned 2.0 breaking changes in now to give you plenty of time to react.

P.S. I'll dig into this issue today to see if I can get to the bottom of it.

**Comment by ErikEJ** [comment]
@bricelam Thanks, Brice, confident that you are on top of the situation as always!

**Comment by ErikEJ** [comment]
Any update? @bricelam

**Comment by bricelam** [comment]
Sill haven't dug into it... ☹️

**Comment by bricelam** [comment]
I'm not able to repro this. .NET Framework 4.5.1 projects on both VS 2015 & 2017 install the latest version of the package without error...

**Comment by ErikEJ** [comment]
What build is that?

**Comment by bricelam** [comment]
1.2.0-preview1-24025 (from the [aspnetcore-dev](https://dotnet.myget.org/gallery/aspnetcore-dev) feed)

**Comment by bricelam** [comment]
The latest from [aspnetcore-ci-dev](https://dotnet.myget.org/gallery/aspnetcore-ci-dev) also worked for me.

**Comment by ErikEJ** [comment]
Magic!

**Comment by roji** [comment]
Same here!
