### ISSUE TITLE
Test: Cannot create file '*.mdf' because it already exists.

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#7815]
Something about running the tests with `vstest.console`, using LocalDB, and running as a service account are causing this error to be thrown. @smitpatel may have a few more details. For now, we've limited our TeamCity configuration to only use agents running as an actual user, but we should see if there's something we can do to re-enable the ones running as a service.

**Comment by bricelam** [comment]
@dougbu is going to try cleaning out all the databases before running to see if that helps.

**Comment by dougbu** [comment]
Self-assigning for now. Will not close when I get the script working. Suspect it's not currently working because the local dB master database still thinks it knows about the no-longer-existing databases / files.

**Comment by dougbu** [comment]
Reassigning because @bricelam is working on the EF fix.

**Comment by bricelam** [comment]
This is resolved. We're no longer using a service account to connect to LocalDB.
