### ISSUE TITLE
SQL Server: Error better when no database name

### ISSUE THREAD

**Issue by cstrachan88** [aspnet/EntityFramework#7816]
I followed along with the VS Launch live stream and tested a .NETCore console app with EFCore, but I am running into an error while deleting the database. Exception below:

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=The string argument 'identifier' cannot be empty.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerSqlGenerationHelper.DelimitIdentifier(String identifier)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(SqlServerDropDatabaseOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Delete()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureDeleted()
```

### Steps to reproduce

So I tried it with my own code first, and then copied and pasted the code from [this repo](https://github.com/skimedic/EFCoreTopTen/tree/master/Migrations) in order to factor out anything I was doing wrong (code is from the live stream demo).

I am using a local database file created by going to Server Explorer, right-clicking on Data Connections and hitting, "Add Connection..." I selected the `Microsoft SQL Server Database File` then chose a file location with everything else in the default configuration.

The connection string I'm using in the code below came directly from the connection string property when I highlighted this created database file.

The only other steps taken were to run an Add-Migration and an Update-Database commands in the Package Manager Console.

```c#
using Microsoft.EntityFrameworkCore;
using System;

namespace EFCore_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var db = new BloggingContext();
            db.Database.EnsureDeleted();
            db.Database.Migrate();
        }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionString = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=""...\NewDB.mdf"";Integrated Security=True;Connect Timeout=30"; 
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(connectionString);
            }
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        public int Rating { get; set; }
        public List<Post> Posts { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }
}
```

### Further technical details
- Package References:
  * Microsoft.EntityFrameworkCore.SqlServer v1.1.1
  * Microsoft.EntityFrameworkCore.Tools v1.1.0
- Operating system: Windows 10 Pro
- IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@cstrachan88 EF Core currently doesn't support connection strings that do not specify a database name (initial catalog). If you add one to your connection string, then you should no longer get this exception.

That being said, we should provide a better message when this fails. Assigning to @bricelam for that.

**Comment by bricelam** [comment]
cc @axelheer (in case he's interested in submitting a PR for this)

**Comment by axelheer** [comment]
@bricelam thanks for mentioning me! But I'm quite busy at the moment. :(

**Comment by bricelam** [comment]
lol, no worries. They pay me to fix bugs... 😉

**Comment by bricelam** [comment]
Looks like we anticipated this bug a while ago: #775
