### ISSUE TITLE
OrderBy_correlated_subquery_lol2 seems to be a very slow test

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#7864]
The `OrderBy_correlated_subquery_lol2` test seems to run slowly on SQLite, In-memory, and SQL Server. We should check if there is a way to make it faster while still testing what it needs to test.

* QuerySqliteTest.OrderBy_correlated_subquery_lol2: 145 seconds
* QueryInMemoryTest.OrderBy_correlated_subquery_lol2: 86 seconds
* RowNumberPagingTest.OrderBy_correlated_subquery_lol2: 82 seconds
* QuerySqlServerTest.OrderBy_correlated_subquery_lol2: 81 seconds

Lol.

**Comment by ajcvickers** [comment]
@maumar Can you make this your second priority, after the 1.1.0 to 1.1.1 regressions? We can discuss again if there are no easy wins here.

**Comment by ajcvickers** [comment]
Also related to #7837.

**Comment by maumar** [comment]
Fixed in c402d73796551929cdff1a50c77c326e62c309f3

**Comment by smitpatel** [comment]
@divega - This does not seem to be enhancement. It was just test which used to pull a lot of data. We trimmed down the size of result to speed up. No product code changes.
