### ISSUE TITLE
Max(), Min(), etc. do not differentiate between no results and zero

### ISSUE THREAD

**Issue by oatkins** [aspnet/EntityFramework#7901]
The `Min()` and `Max()` aggregate functions, and their async counterparts, make it difficult to differentiate between the case that there are no matching rows on which to perform the aggregate, and the minimum or maximum is zero.

Interestingly, the standard behaviour for the LINQ `Min()` and `Max()` functions is to throw `InvalidOperationException` if there are no matching rows. This is a bit of a pain—returning `null` makes more sense really—but it would be helpful if this difference was clearly documented.

    class Program
    {
        static void Main(string[] args)
        {
            // Using EF Core 1.1.1 and matching SQL Server provider in full .NET Framework
            // on Windows 10 with RTM version of VS 2017.
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureCreated();

                // If the value being aggregated is nullable, we're fine - null
                // is returned if there are no matching rows.
                int? a = ctx.Things.Max(x => x.OtherThing);

                // We can explicitly invoke an overload of Max() that *does* return
                // a nullable value.
                int? b = ctx.Things.Max(new Func<Thing, int?>(x => x.ThingyWotsit));

                // That works after a .Select() too.
                int? c = (from s in ctx.Things
                          select s).Max(new Func<Thing, int?>(x => x.ThingyWotsit));

                // All these alternatives fail with similar errors:
                // System.ArgumentException: 'Expression of type 'System.Collections.Generic.IEnumerable`1[System.Int32]' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[System.Nullable`1[System.Int32]]''
                int? d = ctx.Things.Select(x => (int?)x.ThingyWotsit).Max();

                int? e = ctx.Things.Select<Thing, int?>(x => x.ThingyWotsit).Max();

                int? f = (from s in ctx.Things
                          select s).Max<Thing, int?>(x => x.ThingyWotsit);

                int? g = ctx.Things.Select(x => x.ThingyWotsit).Max<int, int?>(x => x);
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<Thing> Things => Set<Thing>();

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Initial Catalog=MyDb;Integrated Security=true");
        }
    }

    public class Thing
    {
        public int ThingId { get; set; }

        public int ThingyWotsit { get; set; }

        public int? OtherThing { get; set; }
    }

**Comment by ajcvickers** [comment]
We discussed this in triage and we are going to investigate throwing. However, this needs some more thought, so adding the needs-design tag to do more thinking.

**Comment by oatkins** [comment]
> adding the needs-design tag to do more thinking.

👍 

[Apparently](http://stackoverflow.com/questions/31154798/why-is-enumerable-min-or-max-inconsistent-between-collections-of-reference-and-v), `Enumerable.Min()` etc. only throws for non-nullable types.

A quick test using the C# REPL gives:

```
> new string[0].Min()
null
> new int[0].Min()
Sequence contains no elements
  + System.Linq.Enumerable.Min(IEnumerable<int>)
> new int?[0].Min()
null
> struct S { };
> new S[0].Min()
Sequence contains no elements
  + System.Linq.Enumerable.Min<TSource>(IEnumerable<TSource>)
```

Unfortunately, these functions are most often used on numeric values, and (even without involving SQL), the default behaviour [often surprises](https://binged.it/2mbGu7y) developers.

I'd suggest there are two things to handle here:

- Fix query translation so that casting to a nullable type doesn't throw `ArgumentException`. This should be A Good Thing for everyone; I can't think of any downside.

- *Consider* changing to throw `InvalidOperationException` instead of returning `default(T)` for non-nullable types. This might be a problem for anyone who doesn't expect it. (I've just written code that would be broken. I suspect plenty of other people would be affected too.)

**Comment by oatkins** [comment]
Great! Love the idea of having an analyzer warning about the possibly unexpected exception.
