### ISSUE TITLE
PropertyEntry.CurrentValue should throw an exception

### ISSUE THREAD

**Issue by sjb-sjb** [aspnet/EntityFramework#7920]
When the value assigned to propertyEntry.CurrentValue cannot be assigned into the database field, then the CurrentValue is not updated, but also no exception is thrown. This makes it harder to debug failed assignments. An exception should be thrown by CurrentValue (and, I suppose, OriginalValue) if the value cannot be assigned.

An example of this is a database table created with an entity property of type bool, which in the CLR was then changed to bool?. However no migration or change was made to the table. When the database was reopened, the bool values were assigned into the bool? CLR property. The propertyEntry CLR type was bool?, but propertyEntry.IsNullable was false. Then I tried to assign null to propertyEntry.CurrentValue. It did not do the assignment (value of CurrentValue was unchanged), but it also did not throw an exception.

**Comment by ajcvickers** [comment]
@sjb-sjb The correct behavior (per current design) for this case would be that setting the CurrentValue should succeed and the value should be set to null. I have verified that this does not happen--the value does not get set to null. This is a bug we will fix.

That being said, CurrentValue should not throw in this case. In general, setting the CurrentValue should succeed any time that the property value is compatible with the CLR type of the property. One example of where this is important is store generated values where the CLR type may be nullable to allow null sentinels that indicate that the value to be used must be obtained from the store. In this case, the CLR type is bool?, null values are allowed in the entity, but the property can be marked as Required (IsNullable false) and no null value will be stored in the database.

**Comment by sjb-sjb** [comment]
I should mention then that my entity property had the [Required] attribute.
I had assumed, though, that this attribute would only be used for
validation and would not affect the database table scheme. Does it?

**Comment by ajcvickers** [comment]
@sjb-sjb [Required] will make the column non-nullable in the store.

**Comment by sjb-sjb** [comment]
So: non-nullable in the database, but nullable CLR type; currently cannot assign null to CurrentValue but this is a bug and one should be able to assign null to it. 

 

So if I assign null in the entity and then try SaveChanges … an exception occurs, I guess. 

 

Of course that would only happen if I didn’t validate the entity properly (using the [Required] attribute). First assign null to the CLR entity and then validate it to find out the value is not valid. Makes sense.

 

Steve

**Comment by sjb-sjb** [comment]
Thanks for the fix!

Just a comment on a potential 'gotcha' ... if you have a non-nullable CLR property, say of type bool, and you try to assign null to it using

     propertyInfo.SetValue( this, null)

then it will assign the default value instead of throwing an exception. All perfectly legitimate and it is documented that way in PropertyInfo.SetValue. 

However if you have a Required property of type bool? and you change it to bool, you will not get the same results even though the table property was bool all along. 

Not really an EntityFrameworkCore problem at all, it's just one of those things that can creep out and bite you.
