### ISSUE TITLE
What's DatabaseName used for?

### ISSUE THREAD

**Issue by xyting** [aspnet/EntityFramework#7936]
Today, I test some ef core features, I assume the `test_db1` and `test_db2` in the same machine:
step1: I use database named `test_db1` in connection string
step2: I change the database name in  `OnModelCreating(ModelBuilder modelBuilder)` method like this:

```csharp
builder.Model.Relational().DatabaseName = "test_db2";
```
step3: I check where the data inserted, in test_db1? or in test_db2?

The result is data inserted into `test_db1`, so, my question is waht's the `DatabaseName` property of `RelationalModelAnnotations` used for?

**Comment by ajcvickers** [comment]
@xyting The database to use is controlled only by the connection string. The DatabaseName is stored in the model as part of the reverse engineering process, but is otherwise not used.

Note for triage: Consider removing sugar API for this annotation if it is only needed by reverse engineering.

**Comment by xyting** [comment]
@ajcvickers Thanks, I got it as I had investigated the source code last night. Have any easy way to dynamic change the database name initial determined by connection string?

**Comment by xyting** [comment]
@ajcvickers Thanks.

**Comment by bricelam** [comment]
Re-opening so we can address @ajcvickers's comment in triage.

**Comment by lajones** [comment]
Added `breaking change` tag as we would be removing public API.

**Comment by ajcvickers** [comment]
Should do this for 2.0, since it is a breaking change.

**Comment by lajones** [comment]
Fixed with PR #8247.

**Comment by xyting** [comment]
Good job, thanks!

**Comment by xyting** [comment]
@lajones Make it a Scaffolding() one instead is ok if it is only needed by reverse engineering, but, the reason why I test this feature is I want to dynamically change the database name at runtime. That's to say I want support multiple databases/tables sharding (in the same maching, I assume) in the same model. For MySQL, the Schema is the same as database, so for MySQL, I can dynamically change the the Schema to To achieve the same purpose. see [this test](https://github.com/Arch/UnitOfWork/blob/master/src/Microsoft.EntityFrameworkCore.UnitOfWork/UnitOfWork.cs#L53-L82)

**Comment by bricelam** [comment]
@xyting Couldn't you just use a new connection string pointing to a different database?
```C#
var newConnectionString = new SqlConnectionStringBuilder(oldConnectionString) { InitialCatalog = newDatabase }.ToString();
```
You may also be looking for #4019

**Comment by xyting** [comment]
@bricelam Yes, this is one choose. Right row, I use a DbContextFactory to dynamic create DbContext to support different maching multiple databases/tables sharding in the same model. In the same machine, I do not need to recreate the DbContext, I only change the MySQL Schema to archeve the database change.

OK,  the all for test purpose, I haven't use in my production.
