### ISSUE TITLE
System.InvalidOperationException when trying to moq data and call AsNoTracking method

### ISSUE THREAD

**Issue by cdie** [aspnet/EntityFramework#7937]
We've created an abstraction on top of EF that will be our main data access. When we try to moq it in order to retrieve test data to test business logic, this exception is thrown when returning a list as queryable.

```
System.InvalidOperationException : 'There is no method 'AsNoTracking' on type 'Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions' that matches the specified arguments'
```

Note that it doesn't throw any exception in EF6 (same code with EF6 just works well)
Note also that .Include() doesn't throw anything

### Steps to reproduce
Here's code to reproduce the issue

```c#
 class Program
    {

        static void Main(string[] args)
        {
            var data = new List<EntityTest>
            {
                new EntityTest{ Id=1, Value = "value1"},
                new EntityTest { Id = 1, Value = "value2" },
                new EntityTest { Id = 1, Value = "value3" }
            };
            var repoMoq = new Mock<Repository>();
            repoMoq.Setup(r => r.Get()).Returns(data.AsQueryable());

            var b = new Business(repoMoq.Object);

            Console.WriteLine(string.Join(",", b.GetAll().Select(u => u.Value)));

            Console.ReadKey();
        }
    }

    public class Business
    {
        Repository _repo;

        public Business(Repository repo)
        {
            _repo = repo;
        }

        public IEnumerable<EntityTest> GetAll()
            => _repo.Get()
            .AsNoTracking() // Explodes here
            .ToList();
    }

    public interface Repository
    {
        IQueryable<EntityTest> Get();
    }

    public class EntityTest
    {
        public int Id { get; set; }
        public string Value { get; set; }
    }
```

### Further technical details
EF Core version:  1.1.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Winodws 10
IDE: VS 2017 RTW

**Comment by ajcvickers** [comment]
@smitpatel to investigate, checking with @anpete who did some related changes in this area previously.

**Comment by tinchou** [comment]
This piece of code suggests there's no special handling https://github.com/aspnet/EntityFramework/blob/f386095005e46ea3aa4d677e4439cdac113dbfb1/src/EFCore/EntityFrameworkQueryableExtensions.cs#L2451

**Comment by cdwaddell** [comment]
I came across this same issue today and ended up writing my own gated version of AsNoTracking() as a workaround.

**Comment by ajcvickers** [comment]
Looks like Include/ThenInclude has the special handling, but AsNoTracking does not. Changing from "investigate" to bug. We should also make sure that there aren't other extension methods that need similar changes. (AsTracking is the obvious one. 😄)

**Comment by bassebaba** [comment]
@cdwaddell  Would you be willing to share your workaround?

**Comment by cdwaddell** [comment]
@bassebaba sure. Basically, I did the same thing that the other IQueryable extensions did in a custom IQueryable extension.
```
  public static class QueryableExtensions
  {
    public static IQueryable<T> AsGatedNoTracking<T>(this IQueryable<T> source) where T : class
    {
      if (source.Provider is EntityQueryProvider)
        return source.AsNoTracking<T>();
      return source;
    }
  }
```
To use this, you change
```myquery.AsNoTracking()```
To
```myquery.AsGatedNoTracking()```

-- Daniel
