### ISSUE TITLE
EF Core Benchmark test failing

### ISSUE THREAD

**Issue by jbagga** [aspnet/EntityFramework#7998]
Benchmarks.EF6.CreateAndDisposeUnusedContext(collector: NullMetricCollector { MemoryDelta = 0, TimeElapsed = 0 }, cold

exception message: `System.IO.FileLoadException : Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`
[Details](http://aspnetci/viewLog.html?buildId=193003&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe)

cc @smitpatel

**Comment by smitpatel** [comment]
Adding binding redirects did not help in above case. It still tries to load incorrect assembly version. The incorrect assembly is being called from dependency - Configuration.FileSystemExtensions. Also the calling code is in different test project. It happens only when using `ColdStartSandbox` which is net46 specific code. Same code works fine when sandbox is not used. There are 6 tests disabled in #7999 3 in each EF6 & EC core benchmarks. 

Side note: When binding redirects are not added to EF6 benchmarks project, it doesn't run any tests in VS.

**Comment by smitpatel** [comment]
In `ColdStartSandBox` we needed to copy over binding redirects while creating new app domain.
