### ISSUE TITLE
RelationalDiagnostics: Naming inconsistencies

### ISSUE THREAD

**Issue by NickCraver** [aspnet/EntityFramework#8001]
I'm working on a `DiagnosticListener` approach in #7939 and noticed some inconsistencies in [`RelationalDiagnostics.cs`](https://github.com/aspnet/EntityFramework/blob/f386095005e46ea3aa4d677e4439cdac113dbfb1/src/EFCore.Relational/Internal/RelationalDiagnostics.cs):

1. ConnectionError is incorrect, `nameof(ConnectionClosed)` (repeated)` should be `nameof(ConnectionError)`. I've submitted PR #8000 to correct this.

```c#
public const string ConnectionClosed = NamePrefix + nameof(ConnectionClosed);
public const string ConnectionError = NamePrefix + nameof(ConnectionClosed);
```

2. "TransactionRolledBack" isn't title cased:
```c#
public const string TransactionRolledback = NamePrefix + nameof(TransactionRolledback);
```
^ this should have a capital `B` to be consistent with all other events. in the class, e.g. 
```c#
public const string TransactionRolledBack = NamePrefix + nameof(TransactionRolledBack);
```

1 is an obvious bug (unless I'm nuts) and causing active harm re-firing the closed event on errors, not just closes. While there's a workaround of using the `exception` arg on the close listener and seeing if it's null, this is both a) not ensure to be reliable, and b) just plain wrong.

2 is minor, but a breaking change to listeners all the same. At the same time, I can't find anyone even using this yet (or someone would have noticed these things?) - should we fix it properly now?

See https://github.com/aspnet/EntityFramework/issues/7939#issuecomment-288206394 for additional concerns I have about the stability of these APIs. Since everyone is (as far as I know) copying these strings because they are internally restricted, there's no scenario fixed by a simple recompile. Issues like this would be better served in the event names were exposed and compilationally reliable.

**Comment by ajcvickers** [comment]
@NickCraver Thanks for the PR for 1. We would also take a PR for 2, since we can take reasonable breaking changes in the 2.0 release. Would you be willing to send a PR?

**Comment by anpete** [comment]
I think this has all been taken care of with @ajcvickers rework of this area.
