### ISSUE TITLE
Feature request: add instanceId (Guid) to RelationalDataReader for DiagnosticSource

### ISSUE THREAD

**Issue by NickCraver** [aspnet/EntityFramework#8007]
Related issues: #8001 and #7939

In RelationalDiagnostics there's an `instanceId` (a `Guid`) added to each event type so that things like `WriteCommandBefore` and `WriteCommandAfter` can be tracked together in the linear logging format that is DiagnosticSource. 

For reference, the DiagnosticsListener bits are here: [RelationalDiagnostics.cs](https://github.com/aspnet/EntityFramework/blob/69d25a0b89a62cba4b74f8530941b67211108fc3/src/EFCore.Relational/Internal/RelationalDiagnostics.cs) and an example usage here: [RelationalConnection#298-329](https://github.com/aspnet/EntityFramework/blob/7e177106f08f788539107fd9165ecf92cb0229f6/src/EFCore.Relational/Storage/RelationalConnection.cs#L298-L329). The gist of it is:

```c#
var instanceId = Guid.NewGuid();
DiagnosticSource.WriteConnectionOpening(_connection.Value,
    ConnectionId,
    instanceId,
    startTimestamp,
    async: false);

try
{
    _connection.Value.Open();
    wasOpened = true;

    var currentTimestamp = Stopwatch.GetTimestamp();
    DiagnosticSource.WriteConnectionOpened(_connection.Value, 
        ConnectionId,
        instanceId,
        startTimestamp, 
        currentTimestamp,
        async: false);
}
catch (Exception e)
{
    var currentTimestamp = Stopwatch.GetTimestamp();
    DiagnosticSource.WriteConnectionError(_connection.Value, 
        ConnectionId, 
        e,
        instanceId,
        startTimestamp,
        currentTimestamp,
        async: false);
    throw;
}
```

That `instanceId` allows a DiagnosticSource listener to tie these two events together. In my case of MiniProfiler, I can time these things and log them as a profiling step. However, `RelationalDataReader` is missing this. Where it's created in `RelationalCommand` [via the `Execute()` call](https://github.com/aspnet/EntityFramework/blob/f386095005e46ea3aa4d677e4439cdac113dbfb1/src/EFCore.Relational/Storage/Internal/RelationalCommand.cs#L226-L231), there's no ID given, so when [`DataReaderDisposing` is fired](https://github.com/aspnet/EntityFramework/blob/f386095005e46ea3aa4d677e4439cdac113dbfb1/src/EFCore.Relational/Storage/RelationalDataReader.cs#L79-L85), there's no ID to go off of:
```c#
_diagnosticSource.WriteDataReaderDisposing(
    _connection.DbConnection,
    _connection.ConnectionId,
    _reader,
    _reader.RecordsAffected,
    _startTimestamp,
    currentTimestamp);
```

Ultimately, this results in a `BeforeExecuteCommand `, `AfterExecuteCommand`, and `CommandExecutionError` events that you can't correlate to  the `DataReaderDisposing` event. So it's both inconsistent and without a way to resolve what's open vs. complete. A connection can have multiple readers (e.g. MARS connections), so the `connectionId` isn't useful, ordered, or unique. But the command `instanceId` already allocated is unique and 1:1.

### Proposed Solution
1. Add a `Guid InstanceId` property to `RelationalDataReader`
2. Assign `InstanceId` from the one already present when creating it ([here](https://github.com/aspnet/EntityFramework/blob/f386095005e46ea3aa4d677e4439cdac113dbfb1/src/EFCore.Relational/Storage/Internal/RelationalCommand.cs#L189))
    - via new constructor? (non-breaking)
    - via `internal` property setter? (also non-breaking)
    - add to existing constructor **(breaking)**
3. Add  `instanceId` to [the `WriteDataReaderDisposing` call](https://github.com/aspnet/EntityFramework/blob/69d25a0b89a62cba4b74f8530941b67211108fc3/src/EFCore.Relational/Internal/RelationalDiagnostics.cs#L338) (internal, so non-breaking)
4. Add `instanceId` to the anonymous object [inside the `WriteDataReaderDisposing` call](https://github.com/aspnet/EntityFramework/blob/69d25a0b89a62cba4b74f8530941b67211108fc3/src/EFCore.Relational/Internal/RelationalDiagnostics.cs#L350-L358) for consumers

If this is a welcomed change, please advise on the options for Item 2 about backwards compatibility preferences and I'm happy to submit a PR.

**Comment by ajcvickers** [comment]
@NickCraver We would love to see a PR for this. With regard to item 2, please add it to the existing constructor. This is the cleanest and we don't think that any code outside of ours will be calling this constructor anyway. If they are, then 2.0 is a breaking release anyway and the change to their code should be minimal.

**Comment by ajcvickers** [comment]
Assigning to @anpete to handle the PR when it arrives.

**Comment by NickCraver** [comment]
@ajcvickers roger - really busy at the moment but 2.0 has some time so I'll try and get to this in the next week or so. Thanks for taking a look!

**Comment by NickCraver** [comment]
@anpete I've thrown up a PR in #8110, let me know what else you need!

**Comment by anpete** [comment]
Moving to @ajcvickers who is working on this.

**Comment by ajcvickers** [comment]
@NickCraver I believe now that #8351 is merged the correlation IDs that you have asked for are available. Specifically, the CommandId is now exposed for DataReaderClosing. I also tried to be more consistent about exposing correlation IDs. If there are others or I missed something, then please let me know--or file a new PR. 

(Note we're still doing some investigation into using DiagnosticSource Activities, so depending on where we land on that it is possible that we will change some of the correlation stuff again.)

**Comment by NickCraver** [comment]
@ajcvickers +1 - awesome set of changes and totally agreed on fixes. HUGE improvements, ❤️
