### ISSUE TITLE
The binary operator Equal is not defined for the types 'System.Nullable`1[System.Boolean]' and 'System.Boolean'.

### ISSUE THREAD

**Issue by twenzel** [aspnet/EntityFramework#8065]
This error will be produced by the weird OData filter query and can be reproduced using following query:
```
 _db.Assets.Where(a => ((a.SerialNumber == null || false) ? null : (bool?)a.SerialNumber.Contains("123")) == true)
```

My entity looks like:
```
public class Asset
    {     
        public int Id { get; set; }
  
        public string SerialNumber { get; set; }
    }
```
The OData controller:
```
public class AssetsController : System.Web.OData.ODataController
    {
        private readonly DataContext _db;

        public AssetsController(DataContext db)
        {
            _db = db;
        }

        [EnableQuery]
        public IQueryable<Asset> Get()
        {                       
            return _db.Assets;
        }     
    }
```

The OData query request looks like:

> http://localhost:52001/odata/Assets?$filter=contains(SerialNumber,'30Q')

I'm using EFCore 1.1.1.

**Comment by maumar** [comment]
Verified that this is fixed in current bits. As a temporary workaround you can try disabling null propagation in OData:

Modify ODataController’s EnableQueryAttribute, by including: 
```HandleNullPropagation = HandleNullPropagationOption.False```
