### ISSUE TITLE
IsKeySet returns false if a basic type has its default value and is part of key

### ISSUE THREAD

**Issue by cdie** [aspnet/EntityFramework#8100]
The IsKeySet property is not always returning a good value. I have encounter a situation where I have an entity and it's primary key is defined as couple of Guids and a boolean.

If the boolean is at false, the IsKeySet always returning false, even if retrieved from database.
I think this is because of the IsKeySetImplementation 

```
public virtual bool IsKeySet => !EntityType.FindPrimaryKey().Properties.Any(
            p => HasDefaultValue(p)
                 && (p.ValueGenerated == ValueGenerated.OnAdd
                     || p.IsForeignKey()));

```

Because false is the default value, it will always returns false for those cases.
I won't argue whereas it's a good or bad practice to have a boolean as part of a key, the fact is, with a specific table, I retrieve a false info.

### Steps to reproduce
Just create an entity that has a composed key with a standard type with some legit value

### Further technical details
EF Core version: 1.1.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Creators Update
IDE: VS 2017 (15.1)

**Comment by ajcvickers** [comment]
@cdie If there is a Boolean property that is marked as store-generated, then if the value of that property is false it means that EF will ask for the database to generate a different value. The IsKeySet API reflects that. See #7163
