### ISSUE TITLE
Update Scaffolding - can now use Identity on a byte property

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework#8140]
Previously EF did not allow the `Identity` strategy to be used on properties which had the data type `byte`.

We enforce this in [SqlServerScaffoldingModelFactory](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.SqlServer.Design/Internal/SqlServerScaffoldingModelFactory.cs#L161) by issuing a warning if we are trying to put Identity on a byte property.

Discussion with @ajcvickers resulted in discovery that EF no longer disallows this. So we should stop issuing the warning and just set `UseSqlServerIdentityColumn()` on that column as we do for other data types.

**Comment by bricelam** [comment]
@smitpatel Do we get this for free now?

**Comment by smitpatel** [comment]
The warning is gone. item 4 on #8688  was about that. I scratched that. We don't need to do anything extra for this issue. We can close this.
