### ISSUE TITLE
Tools: Port #7889 to 1.1.1

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#8142]
The 1.0.1 tools fix for #7889 should be ported to 1.1.1

**Comment by ajcvickers** [comment]
@bricelam Forgive me for not keeping this all straight, but should this then ship as part of the upcoming 1.1.2 patch?

**Comment by bricelam** [comment]
Yes, I was going to check with you and @Eilon about what milestone these should be in...

**Comment by bricelam** [comment]
Tracking in the corresponding EntityFramework milestones for simplicity. The patch build system has been updated to do the right thing.

**Comment by ajcvickers** [comment]
@Eilon @bricelam Looking at #7889 an seeing that a "tone of people" are hitting this, and given that we already have the fix coded and just need to port it, I think we should get approval for this in 1.1.2.

**Comment by Eilon** [comment]
This patch fix is *approved*. Please follow the normal code review / pull request process and make sure you make the change in the correct branch.
