### ISSUE TITLE
Consider specifying NULL columns explicitly in DDL

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#8146]
(copied from a conversation in https://github.com/aspnet/EntityFramework/issues/8113)

Currently for an entity type like this:

``` csharp
    public class Meter
    {
        [Key]
        public int MeterId { get; set; }
        public float Base { get; set; }
        public float? Base2 { get; set; }
    }
```

For SQL Server we generate DDL like this:

``` sql
    CREATE TABLE [Meter] (
    [MeterId] int NOT NULL IDENTITY,
    [Base] real NOT NULL,
    [Base2] real,
    CONSTRAINT [PK_Meter] PRIMARY KEY ([MeterId])
);
```

As mentioned by @ErikEJ the nullability of `Base2` is ambiguous in the script and it can even be altered globally by `SET ANSI_NULL_DFLT_ON OFF` (see https://docs.microsoft.com/en-us/sql/t-sql/statements/set-ansi-null-dflt-on-transact-sql).

The proposal is to specify NULL explicitly instead of relying on the default behavior, e.g.:

``` sql
    CREATE TABLE [Meter] (
    [MeterId] int NOT NULL IDENTITY,
    [Base] real NOT NULL,
    [Base2] real NULL,
    CONSTRAINT [PK_Meter] PRIMARY KEY ([MeterId])
);
```

**Comment by divega** [comment]
In triage we decided we will give @bricelam the last word on this, so adding my argument here:

SQL is a language I for once only use occasionally, and so I prefer to rely very little on previous knowledge about rules and conventions in order to understand things that the code is doing implicitly. 

I actually don't feel strongly about it, but I do believe it would be better to be explicit.

**Comment by bricelam** [comment]
Given that we decided to always make it explicit in C#, and it was explicit in EF6, I think we should do it.

Personally, I don't like it since NULL just means don't add a null constraint to the column, and telling the database not to do something it wouldn't have is silly. ☺

**Comment by ErikEJ** [comment]
Also, SQLCE does not like having it not specified (see the EF6 issue)
