### ISSUE TITLE
DbSet.Find() doesn't work for nullable properties

### ISSUE THREAD

**Issue by marcoregueira** [aspnet/EntityFramework#8189]
I use nullable properties for primary keys. When I declare an entity like this:

    public class Client {
         public long? Id { get; set;} //primary key with nullable property
         ...

Everything seems to work as expected. But the Find method introduced in version 1.1, doesn't seem to work.

When calling:
`
long clientId = 1;
dbContext.Find<Client>(clientId);
`

EF Returns 

**_The key value at position 0 of the call to 'DbSet<Cliente>.Find' was of type 'long', which does not match the property type of 'Nullable\<long\>'_**

Of course, the alternative syntax using SingleOrDefault works perfectly.

    ...DbSet<Client>().SingleOrDefault(x => x.ClientId == clientId); 

The exception message is pretty descriptive and I could easily workaround this, but I would rather prefer keep using null for unsaved entities instead of 0 or reverting to SingleOrDefault. I think Find() should be able to properly translate the nullable value to the corresponding type.

### Further technical details
EF Core version: 1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by cdie** [comment]
A primary key cannot be null, it's impossible. Any element of a PK should be not null in SQLServer.
Check your column into VS SQL object explorer or through SSMS to see it.
Also, because it's not null into your database, EF cannot make the link between a nullable into your C# code and a standard long.

**Comment by ajcvickers** [comment]
@cdie It's perfectly reasonable to the CLR type to be nullable, where null then means that the key value has not been set.

@marcoregueira Thanks for reporting this. We'll get it fixed for 2.0.
