### ISSUE TITLE
Hidden columns are scaffolded

### ISSUE THREAD

**Issue by rposener** [aspnet/EntityFramework#8192]
When scaffolding  a database to EF Core, Hidden Columns are not excluded.  As a result, columns used for SQL Temporal Tables get scaffolded back into the application. As a result, if the DB has not had those turned on, it breaks the EF code against another database which does not have them.

### Steps to reproduce
Create a Database Project and scaffold it to a SQL Server.
Now run Scaffold-DbContext to build your EF context off that server.
Then in SQL Server follow these steps https://docs.microsoft.com/en-us/sql/relational-databases/tables/creating-a-system-versioned-temporal-table#alter-non-temporal-table-to-be-system-versioned-temporal-table to add Temporal System Versioning.  
Now scaffold from the database again.  Notice that the versioning columns are added, despite the fact they are marked as hidden in SQL.

**Comment by ErikEJ** [comment]
Note that is_hidden in sys.columns only applies to SQL Server 2016 and Azure SQL Database

**Comment by ajcvickers** [comment]
We think that hidden columns should not be scaffolded. We're not going to do it for 2.0, but we would consider a well coded PR to do it.

**Comment by ErikEJ** [comment]
@ajcvickers @lajones What SQL Server version does the SQL Server design tests run against?

**Comment by smitpatel** [comment]
@lajones - Everything going into dev now is 2.0.0 milestone. We already branched.

**Comment by lajones** [comment]
@smitpatel Sorry - selected wrong dropdown. Thx for fixing.
