### ISSUE TITLE
Diagnostics: Report number of rows returned by server on reader dispose

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#8197]
This is information can in turn be used by a profiler, e.g. to display a warning if the number of rows goes over certain threshold. 

This is related but not the same as https://github.com/aspnet/EntityFramework/issues/5089, which is about warning on the log.

**Comment by ajcvickers** [comment]
@divega The diagnostics payload already contains "recordsAffected", which comes from DbDataReader.RecordsAffected. Is this different from what you are asking for?

**Comment by divega** [comment]
@ajcvickers if the information is there and is correct for all SELECT queries then we shouldn't need anything else.

**Comment by ajcvickers** [comment]
@divega It's the value from the DbDataReader as it is being disposed. Can you be more specific about how it might be incorrect so I can write tests for that, or we can file bugs to do so? Likewise, can you be specific about what you want me to test for "all SELECT queries".

**Comment by divega** [comment]
@ajcvickers I mean all queries, e.g. LINQ, `FromSql()`, and other APIs that can return multiple rows in results. If we do this consistently for the queries we execute as part of `SaveChanges()` that is a plus.  

One of my concerns is that over the years I have seen APIs similar to this property be a bit fragile and fail to report the actual row count, depending on providers and or the text in the query. E.g. IIRC, with SQL Server, if `SET NOCOUNT ON` is issued as part of the query (which is super common and even considered a good practice), then RecordsAffected will not be able to obtain the correct row count and will report -1 (not that I haven't tested this recently, it could apply to a previous data access API and not ADO.NET).

If this was the case, I guess we should discuss whether and how much we want to go out of our way in order to obtain a reliable count. 

Another concern I have is how things get reported when we have LINQ queries that result in sending multiple SQL queries to the database. This concern is almost orthogonal to this issue, but it is related in the sense that we want tools and users to be able to make sense of the diagnostic data (including the row counts) produced for those cases.

**Comment by ajcvickers** [comment]
@divega Okay, thanks I get what you are saying now. I checked the code and AFAICT we we always get this event and have this available whenever we use a data reader--we don't have different data reader paths, even in update.

However, marking this for re-triage to decide how much work to do report the "real" value when ADO.NET doesn't give us back something useful.
