### ISSUE TITLE
Query: Anonymous type projections should use member names as column aliases wherever possible

### ISSUE THREAD

**Issue by mojtabakaviani** [aspnet/EntityFramework#8204]
For example anonymous type with new property names:
```
var schools = db.Students.Select(p => new { 
      p.Id, 
      School = p.Name, 
      Score = p.Scores.Sum(s =>  s.Score) 
});
```
generated t-sql:
```
SELECT [p].[Id], [p].[Name], (
                SELECT SUM([s].[Score])
                FROM [Scores] AS [s]
                WHERE [p].[Id] = [s].[StudentId]
            )
            FROM [Students] AS [p]
```
improvement t-sql:
```
SELECT [p].[Id], [p].[Name] AS [School] , (
                SELECT SUM([s].[Score])
                FROM [Scores] AS [s]
                WHERE [p].[Id] = [s].[StudentId]
            ) AS [Score]
            FROM [Students] AS [p]
```

**Comment by smitpatel** [comment]
We don't alias column names unless we need to. Only in a subquery all columns need to have unique names. At top level aliasing is not needed at all. What is improvement here?

**Comment by anpete** [comment]
@smitpatel It can make the generated SQL easier to understand (map back to the original LINQ query). We already do this for QSREs when we can.

**Comment by smitpatel** [comment]
Note to implementer:
While storing member info to projected expression information inside selectexpression during projection visitor, convert the projected expression to alias expression with alias being name of the member info.
