### ISSUE TITLE
Commands: Use startup project

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#823]
...for config files, data directory, relative paths, etc.

There are TODOs in the code for this, just logging an issue to track the work too

**Comment by lukewaters** [comment]
Fixed in #1416

**Comment by bricelam** [comment]
This isn't finished. We need to enable this functionality on the ASP.NET commands too.

**Comment by bricelam** [comment]
We also need to consider whether the `-StartUpProject` parameter is needed on the NuGet commands.

**Comment by lukewaters** [comment]
Fixed in #1416 #1503 and #1507
