### ISSUE TITLE
The generated identifiers in multi level queries are too long for SQLServer

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#8255]
Paste into ComplexNavigationsQueryTestBase, run in ComplexNavigationsQuerySqlServerTest:

```C#
[ConditionalFact]
public virtual void Level4_Include()
{
    using (var context = CreateContext())
    {
        var query = context.LevelOne
            .Select(l1 => l1.OneToOne_Required_PK).Where(t => t != null)
            .Select(l2 => l2.OneToOne_Required_PK).Where(t => t != null)
            .Select(l3 => l3.OneToOne_Required_PK).Where(t => t != null)
            .Select(l4 => l4.OneToOne_Required_FK_Inverse.OneToOne_Required_FK_Inverse)
            .Include(l2 => l2.OneToOne_Optional_FK);

        Assert.Equal(10, query.ToList().Count);
    }
}
```

Exception: `The identifier that starts with 'l1.OneToOne_Required_PK.OneToOne_Required_PK.OneToOne_Required_PK.OneToOne_Required_FK_Inverse.OneToOne_Required_FK_Inverse.OneT' is too long. Maximum length is 128.`

**Comment by roji** [comment]
I've just run into this issue with PostgreSQL, which limits identifies to 63 characters (I see you set MaxTableAliasLength to 128). This made ComplexNavigationsQueryNpgsqlTest.Level4_Include fail.

Is setting MaxTableAliasLength in my QueryCompilationContext to 63 enough to get around this issue?

**Comment by smitpatel** [comment]
@roji - That should do the trick. That property is overridable so that providers can provide max length and the function to unique-fy table names would strip down according to that.

**Comment by roji** [comment]
@smitpatel ok thanks!

**Comment by grahamehorner** [comment]
FYI , the same query with the same Oracle database works when using ef core 2.0? will this be fixed in previous ef core versions?

**Comment by smitpatel** [comment]
@grahamehorner - The same query will work with version 2.0 compatible provider version without any changes in user code or database. Though this will not be fixed in previous versions.
