### ISSUE TITLE
Attaching entity and setting different IsModified values to different property prevent update

### ISSUE THREAD

**Issue by ShaZeh** [aspnet/EntityFramework#8265]
I am not quite sure if this is me doing something wrong, I am pretty sure I have been using this technique without any issues for a good while. But it might be possible that I might never have noticed that some fields were not updating. It might also be possible that the update only fail under very specific circonstances.

So far I have only reproduced the issue while having two property explicitly set to false and true on the second.

Also, it seems that by simply having another entity being saved within the same transaction automatically resolved problem, the IsModified was being taken into account properly.

### Steps to reproduce
- Run the code below
- Notice that the username will remain to "name" even though the last property is set to isModified true.

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;

namespace ConsoleApplication
{
    class Program
    {
        static Context context;
        static void Main(string[] args)
        {
            Task.Run(async () => { await UpdateEntity(); }).GetAwaiter().GetResult();
        }

        static async Task UpdateEntity()
        {
            context = new Context();
            context.Database.EnsureCreated();

            var user = new Users();
            user.UserName = "name";
            user.City = "city";
            context.Add(user);
            await context.SaveChangesAsync();

            int id = user.Id;
            context.Entry(user).State = EntityState.Detached;


            user = new Users { Id = id, UserName = "New" };

            context.Attach(user);
            context.Entry(user).Property(x => x.City).IsModified = false;
            context.Entry(user).Property(x => x.UserName).IsModified = true;
            //context.Update(user);

            await context.SaveChangesAsync();

            user = await context.Users.Where(x => x.Id == id).FirstOrDefaultAsync();
            Console.WriteLine(user.UserName);
        }
    }

    public class Users
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string City { get; set; }
    }
    public class Context : DbContext
    {
        public virtual DbSet<Users> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Users>(b =>
            {
                b.HasKey(r => r.Id);

                b.Property(x => x.UserName).IsRequired();
            });
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //optionsBuilder.UseSqlServer("Server=.\\SQLEXPRESS;Initial Catalog=Test;Trusted_Connection=True;MultipleActiveResultSets=true");
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=TestDB;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }
}
```

### Further technical details
EF Core version: 1.1.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Win10
IDE: (e.g. Visual Studio 2015)
Observed on EF Core 1.1.0 as well.

Similar issues
https://github.com/aspnet/EntityFramework/issues/7798
https://github.com/aspnet/EntityFramework/issues/7227

**Comment by ajcvickers** [comment]
Note for triage: Confirmed that this is a bug. Doing this works:
```C#
context.Attach(user);
context.Entry(user).Property(x => x.UserName).IsModified = true;
context.Entry(user).Property(x => x.City).IsModified = false;
```
But moving the `IsModified = false` first makes it fail:
```C#
context.Attach(user);
context.Entry(user).Property(x => x.City).IsModified = false;
context.Entry(user).Property(x => x.UserName).IsModified = true;
```

**Comment by evgenisokolov** [comment]
It looks like it still reproducible with in-memory database. Could you please elaborate on that?

**Comment by ajcvickers** [comment]
@evgenisokolov This is an old issue. If you are still running into problems, then please file a _new_ issue and include a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.
