### ISSUE TITLE
Query: Some double & float literals are wrong

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#8270]
Values over/under a certain value have two `E`s in them.

Type | Value | Literal
---- | ----- | -------
float<br />double | 1e-5 | `1E-05E0`
float | 1e7 | `1E+07E0`
double | 1e15 | `1E+15E0`

**Comment by divega** [comment]
@smitpatel  [closed-fixed] but not closed?

**Comment by smitpatel** [comment]
Float are generated using `ToString("R")` which is roundtrippable format.
doubles are generated using `ToString("G17")` (since R has issues on x64 system)

Also double will add `E0` on SQL Server only if it is absent in literal string.
