### ISSUE TITLE
Consider removing UseSqlServerIdentityColumn and ForSqlServerUseSequenceHiLo

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#8271]
Nobody really knows what they mean, when to use them, or where they are valid.

**Comment by ajcvickers** [comment]
Note from triage: Consider adding strategy for column-constraint-based Sequence.

**Comment by ajcvickers** [comment]
May be a breaking change, depending on what we do.

**Comment by ajcvickers** [comment]
@divega I think we should remove these for 2.0 and then look at bringing them back, possibly with different names and/or other strategies added. Thoughts?

**Comment by ajcvickers** [comment]
Discussed with @divega and @AndriySvyryd. We are going to make UseSqlServerIdentityColumn work for non key properties without having it trigger client side value generation at all. ForSqlServerUseSequenceHiLo will still throw for non-key columns. 

Still need to sync with @bricelam on Migrations behavior.

**Comment by bricelam** [comment]
Migrations should work fine. If the annotation is on the column, [it will](https://github.com/aspnet/EntityFramework/blob/92e381e70923e6998d0c2ea4e011189183067bff/test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs#L65-L84) create an IDENTITY column.

**Comment by AndriySvyryd** [comment]
@bricelam That test is for the migration annotation. But now with https://github.com/aspnet/EntityFramework/issues/8795 the model identity annotation will always be translated to a migrations annotation.
