### ISSUE TITLE
Revisit concurrency detector

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#8305]
Need to make sure:
* If async paths are intended to be serialized, then make sure this works for all async paths--i.e. done at appropriate level
  * Consider overhead for doing this when there really isn't any async code in the async path--i.e. when Task.FromResult is used.
* New code paths that have been added after the concurrency detector was introduced are making the right calls into the detector.
  * How do we make sure this stays up-to-date going forward?

See also #8026

**Comment by anpete** [comment]
@ajcvickers We currently do the throwing check in the following:

- ExecuteSqlCommand
- ExecuteSqlCommandAsync
- SaveChanges
- SaveChangesAsync
- MoveNext (sync query)

And we do the async waiting check (interleaving) only in:

- MoveNextAsync (async query)

Obviously there are many more top-level APIs that we could add the check too. Do we want to do that?

**Comment by anpete** [comment]
ping @ajcvickers

**Comment by ajcvickers** [comment]
Design meeting notes:
* We will not attempt to make the context completely thread-safe since there is too much complexity in the implementation and the extra overhead for the normal single-threaded use may be too much.
* @ajcvickers to propose other places to add the check. It doesn't need to be added everywhere, but we want to add in places where it is likely to get hit so that apps will more likely throw a good exception rather than just some random exception from multi-threaded access. (Note to self--context initialization?)
* @ajcvickers to do some tests to make sure common patterns will hit the check

**Comment by AndriySvyryd** [comment]
Also the concurrency detector doesn't fire reliably on `.First()`, see the `Throws_on_concurrent_query_first()` test.

**Comment by AndriySvyryd** [comment]
See also https://github.com/aspnet/EntityFramework/pull/8865
