### ISSUE TITLE
Tools: Remove logic to invoke Startup.ConfigureServices

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#8328]
The ASP.NET Core templates are changing in a way that breaks how `dotnet ef` and the PMC commands invoke `Startup.ConfigureServices()` at design-time to discover and instantiate `DbContext` derived types.

A new design-time entry point of `Program.BuildWebHost()` is being added, and we're considering adding first-class support for it in #8164.

We're taking this opportunity to try a much simpler design-time approach and clean up some of the abstractions around `Startup.ConfigureServices()` that leaked into our implementation.

The most noticeable change is that we're going to stop attempting to call `Startup.ConfigureServices()`. This means that if your `DbContext` derived type doesn't have a default constructor or isn't in either your startup or target project, you'll need to add an implementation of `IDbContextFactory<TContext>`. The tools will automatically discover this implementation on types in your startup or target project and use it. We've added a default implementation to the ASP.NET Core templates for 2.0.0-preview1 so EF Core Migrations commands will continue to work with new projects.

The rippling effects of removing the `Startup.ConfigureServices()` code are as follows.
* The `--environment` (`-Environment` in PMC) option on `dotnet ef` is being removed. Use the `ASPNETCORE_ENVIRONMENT` environment variable instead.
* `DbContextFactoryOptions` is being removed. Use `AppContext.BaseDirectory` instead of the `ApplicationBasePath` property; and `Directory.GetCurrentDirectory()` instead of `ContentRootPath`.
* We no longer discover a method named `ConfigureDesignTimeServices` on your `Startup` class. Instead, implement the `IDesignTimeServices` interface on a type in your startup project.

**Comment by julielerman** [comment]
Is there any chance there's been a regression with EF COre 2.2.2?
I'm in VS2017 15.9.7.

 I've set
$Env:ASPNETCORE_ENVIRONMENT = "Development"
then run
get-dbcontext
and it always outputs the context info specified in appsettings.json, not appsettings.Development.json.
The database name in the connection string is different in the two files so I can see which one is being read. In fact if I remove the connection string from appsettings.json, then i get an error that the connection string value is null.
I've been trying many different things ...casing, spacing, restarting VS, restarting my machine. I just don't know how else to troubleshoot this. Am I doing something stupid or should I create a unique issue? THanks
