### ISSUE TITLE
Throw error on ignored includes

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#8398]
We currently warn when a query has an `Include` call that is ignored. We decided to change this to throw by default, with the ability to switch back to a warning. This is because the cases where people are intentionally and knowingly ignoring includes is much less common that the cases where the include should just be removed.

**Comment by ajcvickers** [comment]
@divega Can we get a fwlink for this? Probably just pointing to https://docs.microsoft.com/en-us/ef/core/querying/related-data unless you think that it would be better to have a special page? (Either way, if we get a fwlink now we can change where it points later.)

(Rowan always got fwlinks for me, so now I am asking you. 😸)

**Comment by divega** [comment]
@ajcvickers We already had http://go.microsoft.com/fwlink/?LinkID=746393 pointing to that page for ambiguous one-to-one, but I went ahead and created a new one https://go.microsoft.com/fwlink/?linkid=850303, in case some day we decide we need a special page.

**Comment by divega** [comment]
I tweaked it a bit more. It now points to https://docs.microsoft.com/en-us/ef/core/querying/related-data#eager-loading.
