### ISSUE TITLE
DbContext.GetInfrastructure() method missing in 2.0 preview?

### ISSUE THREAD

**Issue by jemiller0** [aspnet/EntityFramework#8440]
In my DbContext I with EF Core 1.1.2, I'm able to use the following code to register my logging provider.

`this.GetInfrastructure().GetService<ILoggerFactory>().AddProvider(new LoggingProvider());
`

For some reason the compiler says that the `GetInfrastructure()` method doesn't exist with 2.0. If I comment out the call to `GetInfrastructure()` and just call `GetService()` directly, it seems to work fine.

Should the documentation at https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging be updated?

**Comment by jemiller0** [comment]
Also, it complains about the method being obsolete.

![image](https://cloud.githubusercontent.com/assets/15931877/25973894/b79b3baa-366b-11e7-924e-b8791d4c59c4.png)

**Comment by ajcvickers** [comment]
@jemiller0 The GetInfrastructure issue is an unintentional breaking change. We will look into this and decide what to do.

With regard to logging, there was a breaking change made here: https://github.com/aspnet/Announcements/issues/238

We need to do some investigation as to how best to hook up logging to EF following this change, as well as updating the documentation.

**Comment by ajcvickers** [comment]
Look at making the new thing not Infrastructure.

**Comment by jemiller0** [comment]
The more you can hide the dependency injection stuff that ASP.NET uses the better IMHO. I've always just used System.Diagnostics tracing which is far from perfect, but, I prefer it over the dependency injection hoops that ASP.NET seems to force on people, making assumptions that you are running a web app when you may just be using a console app and not using dependency injection.

**Comment by ajcvickers** [comment]
@jemiller0 Hopefully that will be covered by #1199.
