### ISSUE TITLE
Review and update CUD APIs for migrations

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#8471]
As part of the data seeding work now tracked in https://github.com/aspnet/EntityFramework/issues/629, we created CUD APIs that can be used inside migrations. 

The data seeding work is currently not scheduled to make it in 2.0, but the CUD APIs are already in.

Before we release 2.0.0 we should make sure the CUD APIs are in the state we want them to be, e.g.

1. Are compatible with the usage in the current PR https://github.com/aspnet/EntityFramework/pull/7824
2. Are very usable and we are confident we won't want to make breaking changes on them after we ship.

Otherwise we should consider either fixing them or pulling them from the release.

cc @ajcvickers

**Comment by bricelam** [comment]
We should also `SET IDENTITY_INSERT` for you on SQL Server when inserting.

**Comment by bricelam** [comment]
It needs a bit of cleanup, but it'll fit into Preview 2. I believe we can ship without making breaking changes to enable seed data later.
