### ISSUE TITLE
Update to xunit 2.3

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#8487]
Other aspnet repos have upgrade xunit to 2.3 while EF remains on 2.2. Upgrading to 2.3 will be a non-trivial task because this upgrade bundles xunit.analyzers which will fail the build.

Possible solutions:
 - Upgrade to the xunit 2.3 runtime but exclude the analyzer. Currently difficult because of: https://github.com/dotnet/sdk/issues/1212
 - Fix all of the analyzer errors
 - Upgrade to 2.3 but add a ruleset to make xunit.analyzer errors  "Info" or "Hidden" instead: see https://github.com/dotnet/roslyn/blob/master/docs/compilers/Rule%20Set%20Format.md

FYI - here are the warnings and errors triggered by xunit.analyzers:

```
Name            Count   Meaning
----            -----   -------
xUnit1000       10      Test classes must be public
xUnit1003       420     Theory methods must have test data
xUnit1004       220     Test methods should not be skipped
xUnit1005       210     Fact methods should not have test data
xUnit1008       24      Test data attribute should only be used on a Theory
xUnit1010       1148    Type mismatch between InlineData and method parameter
xUnit1013       4848    Public method on a test class is not marked as Fact or Theory
xUnit2000       76      A literal or constant value is given as the 'actual' value in a call to Assert.Equal(expected, actual)
xUnit2002       64      Do not use Assert.NotNull() on value type 'bool'.
xUnit2003       108     Do not use Assert.Equal() to check for null value. (Use Assert.NotNull or Assert.Null)
xUnit2004       188     Do not use Assert.Equal() to check for boolean conditions. (Use Assert.True or Assert.False)
```

By the way, I suspect the total number is actually half as many. The errors/warnings appear once per target framework and tests currently target net46 and netcoreapp2.0

**Comment by smitpatel** [comment]
I will tackle some of these (small count ones to fix. May ignore the one with 4848 count.

**Comment by natemcmaster** [comment]
@smitpatel here's the build log produced from compiling https://github.com/natemcmaster/EntityFramework/commit/fe05abd219b72e2f67b7ec2dca8c8b4a580e2960. It contains the files/line numbers that produced these warnings.

[ef.txt](https://github.com/aspnet/EntityFramework/files/1005500/ef.txt)

**Comment by smitpatel** [comment]
Note: also there are various skipped test warning coming up in test output due to theories having duplicated data. Clean up that part too.
