### ISSUE TITLE
Move and rename IDbContextFactory

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#8499]
We've talked about this recently. I'm submitting an issue for us to make a decision.

The two points of dislike are:
1. It doesn't convey anything about design time
2. It's tucked away in the Infrastructure namespace

**Comment by ajcvickers** [comment]
IDesignTimeDbContextFactory obsolete and inherit. Move to Design namespace.

**Comment by smithaitufe** [comment]
Please what is the namespace for this: IDesignTimeDbContextFactory in dotnet core.

**Comment by bricelam** [comment]
Microsoft.EntityFrameworkCore.Design namespace in the Microsoft.EntityFrameworkCore assembly/package.

**Comment by smithaitufe** [comment]
@bricelam Sorry to bother you. But it is not working. Here is my .csproj dependencies

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Library.Core/Library.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.0-preview1-final"/>
  </ItemGroup>


</Project>
```
I did `dotnet restore ` and tried `dotnet build` then I got the following errors

```
Context/LibraryDbContext.cs(6,37): error CS0234: The type or namespace name 'Design' does not exist in the namespace 'M
icrosoft.EntityFrameworkCore' (are you missing an assembly reference?) [/home/smith/Desktop/library/src/Library.Repo/Li
brary.Repo.csproj]
Context/LibraryDbContext.cs(212,43): error CS0246: The type or namespace name 'IDesignTimeDbContextFactory<>' could not
 be found (are you missing a using directive or an assembly reference?) [/home/smith/Desktop/library/src/Library.Repo/L
ibrary.Repo.csproj]
/usr/share/dotnet/sdk/2.0.0-preview1-005977/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(94,5): error : Canno
t find project info for '/home/smith/Desktop/library/src/Library.Core/Library.Core.csproj'. This can indicate
```

**Comment by smitpatel** [comment]
@smithaitufe - This is fixed in preview2 bits. Not in preview1.
For Preview1 use `IDbContextFactory` in `Microsoft.EntityFrameworkCore.Infrastructure` namespace

**Comment by smithaitufe** [comment]
@smitpatel @bricelam Please can you look into this issue. It contains a link to a sample repository in my github account.

https://github.com/aspnet/EntityFramework/issues/8873#issue-236383505

Please this problem has been on for almost a week and yet I can't resolve it.

If preview2 will help to solve it. tell me how to upgrade to preview2. I can't find it in [here](https://www.microsoft.com/net/core/preview#linuxubuntu)

**Comment by weitzhandler** [comment]
How do I register the `IDesignTimeDbContextFactory` when setting up the DI container (i.e. during `ConfigureServices` in _Startup.cs_) to be the default factory?

**Comment by weitzhandler** [comment]
@bricelam 

How do I register an implementation of `IDesignTimeDbContextFactory` when setting up the DI container (i.e. during `ConfigureServices` in _Startup.cs_) to be the default factory?'

Thank you!

**Comment by smitpatel** [comment]
@weitzhandler - You don't need to register `IDesignTimeDbContextFactory` in DI. We search for implementation of it in assembly and directly use it to create context.

**Comment by weitzhandler** [comment]
@smitpatel I appreciate your response.
I'm not sure how to implement that interface, I only exposed a ctor accepting `DbContextOptions` in my `DbContext`, how can I initialize this in the factory? Is there any tutorial on how to use this interface?
