### ISSUE TITLE
Tools: Default to Development environment

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#8514]
Right now, we do nothing which defaults to Production in Hosting.

We should ensure Development is used during development.

There are a couple of ways this be done:
1. Set the `ASPNETCORE_ENVIRONMENT` environment variable to `Development` if it's unset.
2. Wait for the launch settings feature and ensure it lights up in our tooling. (dotnet/cli#6617)

**Comment by ajcvickers** [comment]
@bricelam to follow up with hosting team.

**Comment by bricelam** [comment]
dotnet/cli#6617 is the issue tracking the `launchSettings.json` work.
