### ISSUE TITLE
InMemory: Consider bringing back overload of UseInMemoryDatabase() that takes no parameters as obsolete

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#8548]
I get many questions from people starting to use 2.0 who wonder what happened to the API :smile_cat:

We first decided the parameter-less overload would become its own method: `UseTransientInMemoryDatabase()`. More recently we decided we are going to get rid of the latter. 

Given the outcome is that the database name is now required, I think bringing back `UseInMemoryDatabase()` (with no parameters) as `[Obsolete(,IsError:true)]` can help users figure out what they need to do.

**Comment by ajcvickers** [comment]
Obsolete, not as error.

**Comment by ajcvickers** [comment]
Resolved in #8573
