### ISSUE TITLE
Propose name/location for non-interpolating string type

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#8558]

**Comment by divega** [comment]
**Proposal:** `Microsoft.EntityFrameworkCore.RawSqlString`

The type...
- Is not nested and can be shared between `FromSql()` and `ExecuteSqlCommand()`
- Conveys an appropriate meaning when it shows up freely in Intellisense under the EFCore namespace
- Helps differentiate from the overload that takes `FormattableString`  when it shows up in Intellisense. 
- Aligns with the way we currently explain/document both overloads, e.g. for `FromSql()`:
  - `FormattableString` overload -> _Creates a LINQ query based on an interpolated string SQL query._
  -  `RawSqlString` overload -> _Creates a LINQ query based on a raw SQL query._

**Comment by divega** [comment]
@ajcvickers, I talked to @anpete and he won't push back on this proposal. Let me know if you think we should still discuss it in person before he makes the change.

**Comment by ajcvickers** [comment]
:shipit:

**Comment by ajcvickers** [comment]
Poaching since @anpete is out today.
