### ISSUE TITLE
HasFilter generating migrations with string quotes missing

### ISSUE THREAD

**Issue by marekr** [aspnet/EntityFramework#8575]
Describe what is not working as expected.

I have a model which defines

```
    public class Part
    {
        public int Id { get; set; }

        public DateTime? DeletedAt { get; set; }
    }
```
and then I have a index defined via fluent api.
```
            builder.Entity<Part>(b =>
            {
                b.HasKey(r => r.Id);

                b.HasIndex(r => r.DeletedAt).HasFilter("DeletedAt Is NULL");
            });
```

This results in a funny migration being generated.

The just migration.designer.cs file results in
```
                    b.HasIndex("DeletedAt")
                        .HasFilter(DeletedAt Is NULL)
                        .HasAnnotation("Relational:Filter", "DeletedAt Is NULL");
```
where the HasFilter loses its string quotes and it can not compile.

The snapshot also has the same index statement without the quotes

### Steps to reproduce
Create model like above, throw in model configuration in BuildModel for the db context. Run Add-Migration.

### Further technical details
EF Core version: 2.0.0-preview1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 Preview

**Comment by ajcvickers** [comment]
Also, note that the annotation should not be present if the fluent call is generated.

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs#L349

This code should use `GenerateFluentApiForAnnotation` function to generate the filter instead of processing by itself.
