### ISSUE TITLE
Dose EF Core Support `DateAdd` ?

### ISSUE THREAD

**Issue by John0King** [aspnet/EntityFramework#8590]
`DateTime.AddMinutes()` and `DateTimeOffset.AddMinutes()` dosn't translate to sql

### Steps to reproduce

```c#
//model
    public class Show
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime StartTime { get; set; }
        public TimeSpan DurationAsTimeSpan { get; set; }
        public int DurationAsInt32 { get; set; }  //minutes , same as DurationAsTimeSpan , juset for test
    }

//linq 
var y = _db.Shows.Where(r => r.StartTime.AddMinutes(r.DurationAsInt32) > dt ).ToList();

//and this is the out sql 
/*
SELECT [r].[Id], [r].[DurationAsInt32], [r].[DurationAsTimeSpan], [r].[StartTime], [r].[Title]
FROM [Shows] AS [r]
*/
```

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win7-x64
IDE:  Visual Studio 2017

**Comment by pmiddleton** [comment]
DateAdd support has been added to the 2.0 branch for DateTime, but not for DateTimeOffset.

**Comment by sdanyliv** [comment]
Maybe EF should have simple way to support custom functions also, for example as an extensions? Real DB projects has many functions that speedup queries instead of calculating almost everyting on the client side.

**Comment by John0King** [comment]
@pmiddleton  Why it doesn't support `DateTimeOffset` , left or by design?

**Comment by pmiddleton** [comment]
@John0King -  my best guess is because its low priority so no one has it on their todo list.
