### ISSUE TITLE
Replace RelationalTypeMapping.GenerateLiteral(DbType)

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework#8609]
Currently we have a method [RelationalTypeMapping.GenerateLiteral(DbType)](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Relational/Storage/RelationalTypeMapping.cs#L387). This is only used by the query pipeline in order to replace the first parameter of the CONVERT function with the store type to which to cast the result.

This method is supported by the following `Dictionary` in `RelationalTypeMapping`:

```
        private readonly Dictionary<DbType, string> _dbTypeNameMapping = new Dictionary<DbType, string>
        {
            { System.Data.DbType.Byte, "tinyint" },
            { System.Data.DbType.Decimal, "decimal" },
            { System.Data.DbType.Double, "float" },
            { System.Data.DbType.Int16, "smallint" },
            { System.Data.DbType.Int32, "int" },
            { System.Data.DbType.Int64, "bigint" },
            { System.Data.DbType.String, "nvarchar" },
            { System.Data.DbType.Date, "date" }
        };
```

This is wrong for a couple of reasons:

1. These types are SQL Server specific - yet this is the **Relational**TypeMapping, not the SQL Server specific one.
2. More importantly, the return value of the `Dictionary` is not a literal representing an instance of something that could be represented in a column of that `DbType`, but is instead the name of the storeType to which that `DbType` is mapped.

I talked this over with @maumar and what is really wanted here is a `RelationalTypeMapper.FindMapping(DbType)` method which would return a `RelationalTypeMapping` - from which the StoreType could be obtained; and then updates to the query pipeline to treat the CONVERT function and it's first parameter differently, specifically to call the new `FindMapping(DbType)` method we would have added.

**Comment by maumar** [comment]
To fix Convert problem we could add a dedicated expression node for it, rather than reusing SqlFunctionExpression - this way we control how parameters are interpreted

**Comment by ajcvickers** [comment]
Is there a reason this has to be DbType and not CLR type?

As a temporary fix that removes the API could we:
- Make the dictionary DbType -> CLR Type
- Co-locate the dictionary with the calling code in query--static and private/internal
- Find the type mapping for the CLR type and use literal generation from that

**Comment by lajones** [comment]
@ajcvickers @maumar  I don't think that would work - the problem is the query pipeline is not really doing literal generation at all here - the answer the pipeline wants here is not a literal of any given type (they have only a `DbType` to pass in, no "value"); what they want is the name of the store type that maps to that `DbType` for that provider.

Query treated it as a literal because if they do that they can treat the `DbType` like any other argument to a function. I think it's fair to say that they kind of usurped the `GenerateLiteral()` apparatus by adding something that generated what they want when you call `GenerateLiteral(DbType)` - but it really isn't a literal that they get so it really doesn't belong there.

On the other hand a mapping from `DbType` -> TypeMapping does seem like something the TypeMapper should provide, just as it provides mappings from storeType -> TypeMapping and CLR-type -> TypeMapping.

**Comment by ajcvickers** [comment]
I'll investigate and look at the code a bit more today.

**Comment by lajones** [comment]
OK. E.g. `QuerySqlServerTest.Convert_ToDouble()` is a good test to debug.
