### ISSUE TITLE
Migrations: InsertData() causes error "Table 'table_name' does not have the identity property. Cannot perform SET operation."

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#8618]
Our implementation for SQL Server is incorrect because `SET IDENTITY_INSERT table_name ON` is only valid when the table does actually have an identity column. I see a few options:

1. Have a flag indicating if the statement should be generated
2. Have a separate method e.g. `InsertDataOverridingIdentity` :smile_cat:
3. Query for schema metadata in the SQL (might not work if we don't have enough permissions).

**Comment by divega** [comment]
cc @javiercn @bricelam

**Comment by divega** [comment]
This indicates we are also missing testing.

**Comment by bricelam** [comment]
Another option:
* Use the backing model when generating SQL to determine if `SET IDENTITY_INSERT` is needed. Out-of-band tables would need to manually add the statements using `migraitonBuilder.Sql()`.

**Comment by divega** [comment]
@bricelam that option seems avoids leaking the SQL Server-specific requirement and sets other provider to do whatever they need.

**Comment by bricelam** [comment]
I'm leaning toward the SQL:

```SQL
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [object_id] = OBJECT_ID(N'People'))
    SET IDENTITY_INSERT [People] ON;
INSERT INTO [People] ([Id], [Name])
VALUES (1, N'Brice');
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [object_id] = OBJECT_ID(N'People'))
    SET IDENTITY_INSERT [People] OFF;
```

I'll have a PR out in a few minutes if it works.

**Comment by bricelam** [comment]
It works.
