### ISSUE TITLE
MigrationsScaffolder is a public type registered in D.I. with no contract or dependency objects

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#8623]
Typically all our public services:
- Are defined by a contract interface
- Use dependency object pattern so that we can add new dependencies without breaking inheritors

MigrationsScaffolder doesn't do these things. It's only added to the design-time container so maybe it doesn't matter, but it seems like it may still have the same issues as runtime services, so creating this issue to discuss.

**Comment by bricelam** [comment]
We should do this. It should also be using `IOperationReporter` instead of `IDiagnosticsLogger`
