### ISSUE TITLE
Exists check logs error "An error occurred using the connection..."

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#8651]
I am seeing a lot of errors like this when using the tools.

> An error occurred using the connection to database 'main' on server 'Test.db'.

There are two issues with them:
1. We expect these errors when checking if the database exists. Can we suppress (or dampen their log level) in this case?
2. ~~Logging errors terminates the process in PMC meaning you have to call `Update-Database` a few times before it succeeds.~~ (fixed)

**Comment by ajcvickers** [comment]
Log a debug message when using the path from Exists.
