### ISSUE TITLE
HasMaxLength(4000) set to NVARCHAR(MAX)

### ISSUE THREAD

**Issue by stevanuz** [aspnet/EntityFramework#8685]
### Steps to reproduce
I have the following API:
builder.Entity<EventLog>() .Property(p => p.Message).IsRequired().HasMaxLength(4000);

However, SQL Server uses NVARCHAR(MAX) instead of NVARCHAR(4000).

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 1.1.2
Operating system: Windows 7
IDE: Visual Studio Community 2017

**Comment by stevanuz** [comment]
Note that the Migration's Up() method correctly generate the following codes:
migrationBuilder.AddColumn<string>(
                name: "Message",
                table: "EventLogs",
                maxLength: 4000,
                nullable: false);

**Comment by smitpatel** [comment]
Can you explain what do you mean by this?
> However, SQL Server uses NVARCHAR(MAX) instead of NVARCHAR(4000).

**Comment by stevanuz** [comment]
What I meant is that the datatype is NVARCHAR(MAX) instead of NVARCHAR(4000).

**Comment by smitpatel** [comment]
Can you also post output of `Script-Migration` (dotnet ef migration script if using dotnet cli)

**Comment by stevanuz** [comment]
That's a good idea, let me take a look.

**Comment by stevanuz** [comment]
1. Fluent API
![8685_1](https://cloud.githubusercontent.com/assets/16387544/26713592/c1b0fde0-47b0-11e7-8eec-c692c8eed6a4.png) 

2. Migration
![8685_2](https://cloud.githubusercontent.com/assets/16387544/26713603/ca842618-47b0-11e7-8236-f3badfeeafe6.png)

3. SQL
![8685_3](https://cloud.githubusercontent.com/assets/16387544/26713607/ce35b970-47b0-11e7-8584-d009d194d0a1.png)

The above screenshots should describe the problem. Thanks.

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql

`nvarchar(4000)` should be equivalent of `nvarchar(max)`

**Comment by stevanuz** [comment]
"Variable-length Unicode string data. n defines the string length and can be a value from 1 through 4,000"
In SQL you can DECLARE @_string AS NVARCHAR(4000)
So, I don't think  nvarchar(4000)  should be equivalent of nvarchar(max)  is correct.

**Comment by ajcvickers** [comment]
Off by one.

**Comment by bricelam** [comment]
This no longer repros on dev. Somebody must have inadvertently fixed it. 😉

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFramework/commit/ae2277ed90c782500df29d2bf735491f316da9a8
Which removed the always setting size for parameters of string type. Instead null are now allowed which makes them nvarchar(max) again.
