### ISSUE TITLE
Pragma out obsolete warnings in generated code

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#8703]
While discussing #8654, one of the sticking points was that making the existing API obsolete would result in obsolete code in model snapshots. We could start preemptively pragmaing out obsolete warnings in this generated code so in the future as long as the obsolete code keeps working, we can do it without "breaking" generated code.

**Comment by bricelam** [comment]
```C#
partial class MyMigration
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        // ...
#pragma warning restore 612, 618
    }
}
```
```C#
partial class MyModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        // ...
#pragma warning restore 612, 618
    }
}
```
Look good?
