### ISSUE TITLE
RevEng: Clean up DatabaseModel

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#8714]
We should evaluate whether it would be worth making the DatabaseModel classes look a little more like the Migraitons operations classes.

**Comment by bricelam** [comment]
![classdiagram1](https://user-images.githubusercontent.com/1226749/26840523-443c697e-4a9b-11e7-97cb-ca3c3ecce9b5.png)

**Comment by ErikEJ** [comment]
Index.IncludedColumns ? (List<Column>)

**Comment by bricelam** [comment]
This was just a sketch. I think the main points we want to address are:
* Align type and property names with the rest of the stack
* Consider removing `Ordinal` (inherent in IList) and `DisplayName` (should be a well-known annotation)
* Make `PrimaryKey` and `UniqueConstraint` first-class concepts

**Comment by Eilon** [comment]
Do we need to move this to the 2.0.0 milestone?

**Comment by Eilon** [comment]
cc @ajcvickers
