### ISSUE TITLE
API Review: Scaffolding changes

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#8739]
* Rename AnnotationRendererBase to AnnotationCodeGenerator
* Rename IAnnotationRenderer to IAnnotationCodeGenerator
* Remove the following
  * RelationalForeignKeyAnnotations.GetDefaultForeignKeyName
  * RelationalIndexAnnotations.GetDefaultIndexName
* Revert making RelationalKeyAnnotations.GetDefaultName public
* Move the following to Internal namespace or remove them if they'll show up on app code
  * ScaffoldingEntityTypeAnnotations
  * ScaffoldingMetadataExtensions
  * ScaffoldingModelAnnotations
  * ScaffoldingPropertyAnnotations
* Rename IScaffoldingHelper to IScaffoldingCodeGenerator
* Rename IScaffoldingHelper.GetProviderOptionsBuilder to GenerateUseProvider
* Move IScaffoldingHelper.GetTypeScaffoldingInfo to a different interface or investigate improving its design
* Investigate whether ScaffoldingTypeMapper can move to Internal namespace

**Comment by weitzhandler** [comment]
I'm waiting for this to come live.

I'd really love to see an end-to-end entity graph management for disconnected clients.
Something like [Breeze#](https://github.com/Breeze/breeze.sharp) or [Trackable-Entities](https://github.com/TrackableEntities/trackable-entities).

I believe with scaffolding this will become a step closer.

**Comment by ajcvickers** [comment]
@weitzhandler What are you waiting for here? These are just renames, and they were already pushed and released in preview2.

**Comment by weitzhandler** [comment]
Sorry then.
I'm not really using EF7 yet (it's missing Complex-types and TPT - mandatory to me).
When I shall start using it, I'm noting to myself a point where gathering metadata can be made easier.

Really I wish the EF team would adopt an in-house solution for disconnected graphs manipulating and caching for clients. Especially to support *UWP* and *Xamarin.Forms* apps, which is currently a nightmare.

**Comment by bricelam** [comment]
Have you seen [Azure Mobile Apps](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-offline-data-sync)? Not sure if it's quite what you're looking for...

**Comment by weitzhandler** [comment]
Thanks for the reply @bricelam
I've fiddled with it a little bit, and from what I understood, it's good if you bid your project from scratch based on it, additionally I haven't found support for graph changes.
I wish I'm wrong, can you mention here someone from the Azure team?

**Comment by weitzhandler** [comment]
Besides Azure tables doesn't give an answer to dealing with complex entity graphs, like TrackableEntities or Breeze does. Please see #5536.
