### ISSUE TITLE
AddDbContext with ServiceLifetime.Scoped should pass scoped IServiceProvider to optionsAction

### ISSUE THREAD

**Issue by prochnowc** [aspnet/EntityFramework#8797]
When registering DbContext via AddDbContext(Action<IServiceProvider, DbContextOptionsBuilder>) with ServiceLifetime.Scoped i expect IServiceProvider argument passed to the optionsAction to be IServiceProvider from IServiceScope.

Unfortunately AddDbContext adds DbContextOptions as singleton. Should'nt DbContextOptions be also added scoped when using ServiceLifetime.Scoped ?

In my case i resolve many DbContext's which need to use same DbConnection provided by a scoped IDbConnectionProvider. This enables me to call SaveChanges on different contexts in same transaction.

### Steps to reproduce

```c#
services.AddScoped<IDbConnectionProvider, DbConnectionProvider>();
services.AddDbContext<DbContextA>(o => (sp, o) => o.UseSqlServer(sp.GetRequiredService<IDbConnectionProvider>().GetConnection());
services.AddDbContext<DbContextB>(o => (sp, o) => o.UseSqlServer(sp.GetRequiredService<IDbConnectionProvider>().GetConnection());
```
sp argument in AddDbContext should be instance provided by IServiceScope.

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@prochnowc DbContextOptions is intentionally registered as singleton. See #6863 for details.

Note for triage: capturing the scoped service provider is a good idea. I wasn't sure how to do it before, but I think I have an idea now.

**Comment by prochnowc** [comment]
Thanks for the reply. I've already worked it around registering DbContextOptions on my own as scoped service.
