### ISSUE TITLE
Migrations: MaxLength not honored

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#882]
Adding a maxLength parameter to a string column does not result in the correct data type being generated. I.e. the following code generates nvarchar(max) for RoleId

```
migrationBuilder.CreateTable("AspNetRoleClaims",
    c => new
        {
            Id = c.Int(nullable: false, identity: true),
            ClaimType = c.String(),
            ClaimValue = c.String(),
            RoleId = c.String(maxLength: 128)
        })
    .PrimaryKey("PK_AspNetRoleClaims", t => t.Id);
```

**Comment by ScriptiZer** [comment]
hi rowanmiller,
any updates regarding this issue ?
please keep me posted

**Comment by rowanmiller** [comment]
@ScriptiZer - @bricelam is busy tidying up a whole bunch of migrations stuff at the moment, so this should be resolved shortly (if it isn't already).

**Comment by ScriptiZer** [comment]
Thanks

**Comment by dridgely** [comment]
I'm not sure if this should be a new issue, but MaxLength does not appear to work properly for migrations of sub types. 

I have a sub type like:
    public class SubType: SuperType {
        public string RelatedTypeKey {get;set;}
        public RelatedType Related {get;set;}
    }

The model builder looks like:
    modelBuilder.Entity<SubType>(entityBuilder => {
        entityBuilder.Property(subType => subType.RelatedTypeKey).MaxLength(50) 
    });

The migration sql that results produces RelatedTypeKey nvarchar(max).

I've tried use attributes, as well, with the same result.

**Comment by rowanmiller** [comment]
@dridgely can you open a new issue, this issue is tracking something that has already been fixed.

**Comment by dridgely** [comment]
Done: #4238

**Comment by rowanmiller** [comment]
@dridgely thanks, between typing my response and you opening the issue I actually came across another issue that someone else had opened (#4146) :smile:
