### ISSUE TITLE
Benchmarks: Rework Benchmark Infra

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#8842]
`BenchmarkAttribute` is a `FactAttribute` but it is used on tests with parameters & alongwith `DataAttribute` like `BenchmarkVariation` which are generally used on `Theory`. As always xUnit does not like our mess and shows errors. 😝 

This errors/warnings are explicitly disabled in csproj files at present. Rework this infrastructure and remove nowarns.

**Comment by anpete** [comment]
Even better, lets start using [BenchmarkDotNet](http://benchmarkdotnet.org/)

**Comment by ajcvickers** [comment]
Includes getting comparison of EF6/1,.1/2.0.

**Comment by smitpatel** [comment]
Decided in ad-hoc discussion today that benchmarks on current dev will not be run as xUnit test as a part of build.
- They will be included in same solution so that any API breaks/usages can be found.
- It will not run as xUnit test so if there is functional break then it will be not caught during build.cmd run though given coverage in other tests there should be minimal impact. (Also there is a way to run it manually)
- If any functional breaks happen then we can react to it.

**Comment by smitpatel** [comment]
Blocked on https://github.com/dotnet/BenchmarkDotNet/issues/481

**Comment by smitpatel** [comment]
We have moved to use BenchmarkDotNet for our benchmark runs.
