### ISSUE TITLE
Automatic eager loading of owned types

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#8843]
(previously tracked as part of https://github.com/aspnet/EntityFramework/issues/2953) 

Owned types currently don't get eager loaded automatically, i.e. you need to use `Include()` like with any other entity type. Early on we said we wanted the `Include()` call to be unnecessary and we devised that we would create an annotation in the model that marked navigation properties as "always include" and a convention would annotate the navigations to owned types as such automatically. The annotation would provide a way to opt out, and we could create fluent API for it.

We are closer to be done with 2.0 and we believe the full design does not fit, but there can be smaller versions of it that do.

One of the main problems with not doing this by default is the kind of queries users need to write in order for navigations which are defined in derived types to be included. There is currently no API for Include() that works with navigations defined in derived types, hence you have to split your query, e.g.:

``` C#
var ds =context.Ds.Where(predicate);
var derived = ds.OfType<D1>().Include(d1=>d1.NavA).Concat(ds.OfType<D2>().Include(d2=>d2.NavB)).Concat(…);
```

Also, `Concat()` is evaluated in memory.

**Comment by ajcvickers** [comment]
I won't be in triage tomorrow (if you guys still do it) but I'm good in principle with doing just the non-API work and the convention.
