### ISSUE TITLE
SqlServer: Aggregate functions can return different data type

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#8906]
As https://github.com/aspnet/EntityFramework/issues/7136 describes for `Sum`, we should verify all other functions where SqlServer changes the return type. Most frequent error I have seen reported by users on StackOverFlow is like this
`Unable to cast object of type 'System.Double' to type 'System.Nullable`1[System.Single]'.`

**Comment by maumar** [comment]
this should be done already, fix for #7136 covers SUM and AVG, other result operators (at least the ones we support) return the same type as the input (Min/Max/Avg/Count/LongCount/First(OrDefault)

**Comment by smitpatel** [comment]
Feel free to close if you are certain that we have covered all functions.

**Comment by maumar** [comment]
will double check the fringe result ops (stdev, etc). I don't think we support them but always good to have tests for the future.
