### ISSUE TITLE
Detached entities appear in ChangeTracker.Entries()

### ISSUE THREAD

**Issue by Wain123** [aspnet/EntityFramework#8921]
```
var u = ctx.Posts.First();
ctx.Entry(u).State = EntityState.Detached;
Console.WriteLine(ctx.ChangeTracker.Entries().Count());
ctx.Entry(u);
Console.WriteLine(ctx.ChangeTracker.Entries().Count());
```
This code outputs "0 1". Simply looking at u's entry after detaching u causes the entry to appear in the ChangeTracker, even though u is detached. Is this working as intended?

**Comment by ajcvickers** [comment]
Note for triage: confirmed repro on 1.1.2.
