### ISSUE TITLE
Post-process model snapshot to massage metadata

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#8925]
The model snapshot may contain provider-specific annotations that are now only supported as relational annotation. For example, `SqlServer:TableName`. After building the snapshot we could process it to change these to `Relational:Xxx` based on looking for any annotation that ends in `:SomeRelationalAnnotation`. If this results in conflict (should be rare) we can pick one and warn saying that this is not supported anymore--note that it wouldn't have worked in migrations anyway.

This hook could also be generally useful in the future for other tweaks to metadata that may result in residual code in the snapshot that needs to be massaged.

**Comment by ajcvickers** [comment]
Look at the version and only do it when needed.

**Comment by AndriySvyryd** [comment]
@smitpatel Poaching this
