### ISSUE TITLE
API Review Updates for HasDbFunction, etc.

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#8942]
- [x] HasDbFunction
  - [x] Investigate adding HasDbFunction that takes an expression instead of a MethodInfo
  - [x] Remove name/schema from HasDbFunction in favor of leaving HasName and HasSchema on builder
- [x] DbFunctionAttribute
  - [x] Unseal
  - [x] Move to root namespace
  - [x] Change NotNull to NotEmpty on Name property
  - [x] Make `schema` optional in constructor
  - [x] Rename Name to FunctionName
- [x] DbFunctionBuilder
  - [x] Move to Builders namespace
  - [x] Remove HasParameter
  - [x] Investigate if ReturnType is needed or if it is the same as the CLR type of the method
  - [x] Rename TranslateWith to HasTranslation
  - [x] Change SqlFunctionExpression to Expression
- [x] Remove DbFunctionParameterAttribute, DbFunctionParameterBuilder, IDbFunctionParameter, IMutableDbFunctionParameter
- [x] IDbFunction/IDbMutableFunction
  - [x] Rename Name to FunctionName
  - [x] Remove Parameters
  - [x] Remove AddParameter
  - [x] Change SqlFunctionExpression to Expression
  - [x] Rename TranslateCallback to Translation

**Comment by pmiddleton** [comment]
I can make most of these changes tonight. 

 DbFunctionBuilder.HasParameter and DbFunctionBuilder.ReturnType were added at the request of @AndriySvyryd.  They are needed if/when the ability to remove the default conventions is added.  HasParameter was originally GetParameter which allowed a fluent way to find a dbFunctionParameter.  

For DbFunctionParameter the only property which the users need to be able to set is Index.  It is possible to be in a situation where the database function and the .Net method parameters are in different orders and this property allows parameters to be mapped correctly.  If we drop HasParameter and DbFunctionParameterBuilder then the fluent api is lost and the user will have to fish around in the DbFunction.Parameters collection using linq.

Alternatively we can just say tough luck and if the parameter orders doesn't match up then just write a custom translation and reorder the parameters yourself.  

DbFunctionParameterAttribute was a nice to have so you could reorder parameters without needing to use the fluent api - no functionality would be lost by removing it.

**Comment by anpete** [comment]
Thanks @pmiddleton!

> Alternatively we can just say tough luck and if the parameter orders doesn't match up then just write a custom translation and reorder the parameters yourself.

This is exactly where we landed after some discussion.

**Comment by pmiddleton** [comment]
Ok so these changes have been discussed already?  If so I can plow through them.

**Comment by anpete** [comment]
Yes, we do an internal API review when we get close to shipping. They are normally just with the core team, but only due to practical reasons. I'm curious would you have been interested in participating?

**Comment by ajcvickers** [comment]
@pmiddleton It's really great to work with a contributor like you. Keep up the good work!

**Comment by pmiddleton** [comment]
Yes I would have.  It would have been interesting to hear the thoughts/feedback on the feature set and api surface.

I fully understand why you keep the review limited, otherwise discussions could become unyielding and offtrack fast.

Thanks @ajcvickers

**Comment by pmiddleton** [comment]
Should these changes be made based on the dev branch?

**Comment by ajcvickers** [comment]
Yep, dev branch.

**Comment by pmiddleton** [comment]
Should the file DbFunctionBuilder.cs be moved into the Builders subfolder as well as be placed in the Microsoft.EntityFrameworkCore.Metadata.Builders namespace?

**Comment by ajcvickers** [comment]
Yep. We try to keep folders aligned with namespaces, but sometimes things get out of sync and it doesn't matter too much. But yep, move it.

**Comment by pmiddleton** [comment]
Removing name/schema from HasDbFunction will cause some internal methods to no longer need name/schema as well.  Did you discuss if you want the removal to carry through the call entire hierarchy?

I don't see a reason not to remove them from those methods as well.
