### ISSUE TITLE
DbContextPooling is broken

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#9024]
Test 'Microsoft.EntityFrameworkCore.DbContextPoolingTest.Concurrency_test' failed: Assert.InRange() Failure
Range:  (30 - 500)
Actual: 95657
	C:\enlistments\Universe\EntityFramework\test\EFCore.SqlServer.FunctionalTests\DbContextPoolingTest.cs(363,0): at Microsoft.EntityFrameworkCore.DbContextPoolingTest.<Concurrency_test>d__15.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by smitpatel** [comment]
Super flaky :trollface:

**Comment by anpete** [comment]
That number '95657' is not flakiness but something not working at all. Did something change?

**Comment by smitpatel** [comment]
Options life time went from singleton to scope I think.
Though without any change the next run passed on CI. Also appveyor is working fine. So seems like one of the rare outlier on efci. We should make the test more deterministic.

**Comment by anpete** [comment]
We can disable the test. But we need to be confident that we haven't broken it.

**Comment by ajcvickers** [comment]
DbContextOptions lifetime is still Singleton when using AddDbContextPool.

**Comment by ajcvickers** [comment]
Or at least, it is supposed to be. 😸

**Comment by AndriySvyryd** [comment]
Found and filed the issue in DI: https://github.com/aspnet/DependencyInjection/issues/541
