### ISSUE TITLE
Add DbContext Validate to CLI/PS commands

### ISSUE THREAD

**Issue by julielerman** [aspnet/EntityFramework#9052]
The validation that EF does when you run a migrations command provides very helpful error messages.

Is it possible to have a command just for that task so you don't have to add a migration just to check to see if the model is valid?

CLI
dotnet ef dbcontext validate

Powershell
validate-dbcontext  (follows pattern of scaffold-dbcontext)

**Comment by bricelam** [comment]
Hmm, we have `dotnet ef dbcontext info`, but no PMC equivelant.

**Comment by bricelam** [comment]
Then again, it may never actually build the model...

**Comment by bricelam** [comment]
#9096 Adds `Get-DbContext` in addition to `dotnet ef dbcontext info`. These commands will run model validation and print out information about the context (provider name, database server, DbContextOptions, etc.)

There is a small bug in the way we log (#8350), but if you're using an ASP.NET Core project, everything will work as expected.
