### ISSUE TITLE
React to feedback on warning as error for ignored calls to Include()

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#9064]
We have got quite a bit of feedback over at https://github.com/aspnet/EntityFramework/issues/9030 (please keep the discussion there). Most of it is positive about the change but some legitimate concerns have been raised about general purpose code which can take any existing query and perform operations such as `Count()` on it, which will now throw the error if the original query has any calls to `Include()`.

Just to list some of the possible options:

0. Go ahead with what we have right now: the warning causes an error and the error can be avoided by removing the `Include()` or disabling the error globally.
1. Revert the changes so that ignored `Include()` are again just warnings
2. Go ahead with what we have but add a way to avoid the error at the query level
3. Somehow special-case aggregate operations such as `Count()` so that they don't cause the error
4. Revert the change but enable the error in ASP.NET templates 
5. Revert but create a new `Include()` method, e.g. `MustInclude()` which has stronger semantics and throws if ignored.

**Comment by ajcvickers** [comment]
After much discussion, we have decided to revert this back to a pure warning for 2.0. The main reasons for this are:
* Third-party packages may build query expressions in a generic way what sometimes use Includes, and application code would have little control over this. In this case a warning that can be communicated to the third party package is more appropriate than an exception.
* It's valid to have ignored includes when intentionally building expressions in a generic way that are then sometimes used in a way that needs the include, and sometimes in a way that doesn't.
* The EF code cannot know for 100% sure that the ignored Include is an error in the way the query was written--see first two points--so when comparing to, for example, compiler warnings/errors, this is more of a warning than an error.

We will continue to investigate ways to make the warning more visible, as well as work with other means to educate on what Include means. For example, this could be something detected profiler/diagnostics tools--see #1084.

In the future we may consider additional API additions/changes, but it is too late in the schedule to do this for 2.0. We will monitor the situation and file new issues if/when appropriate.

**Comment by smitpatel** [comment]
@ajcvickers - #1084 may not be issue you wanted to reference.

**Comment by ajcvickers** [comment]
Thanks @smitpatel. Updated.
