### ISSUE TITLE
Tools: Ignore errors in design time DbContext discovery 

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#9073]
Any errors are thrown by creating the service container or trying to resolve `DbContext` from it in an ASP.NET Core apps should be ignored so that we can proceed to discover any `IDesignTimeDbContextFactory<T>`s. 

From https://github.com/aspnet/EntityFramework/issues/9033#issuecomment-313213884, we believe we may have regressed.

cc @bricelam @ajcvickers

**Comment by lajones** [comment]
@divega What happens if you are trying to resolve a `DbContext` from an ASP.NET Core app? Could we put the errors out as debug/log messages to help debugging that scenario (but then continue on as you suggest above)?

**Comment by divega** [comment]
I think @bricelam’s PR puts the error in the log.

**Comment by bricelam** [comment]
Yep. Same logic as before: You'll see a warning containing the exception message, and `--verbose` will also give you the full stack trace.

**Comment by lajones** [comment]
@divega @bricelam Sounds great 👍
