### ISSUE TITLE
Remove BasicModelBuilder

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#908]
Investigate having just one model builder that can work without conventions.

**Comment by divega** [comment]
@smitpatel please talk to @AndriySvyryd about how to approach this.

**Comment by ajcvickers** [comment]
@smitpatel @AndriySvyryd @divega @bricelam Migrations must stop using the BasicModelBuilder before it can be removed,

**Comment by divega** [comment]
@smitpatel I talked to @bricelam, @ajcvickers and @AndriySvyryd and we agreed to replace Migrations usage of BasicModelBuilder in model scaffolding with direct calls to the core metadata API. I have created issue #1484 for that, and it is also assigned to you.

**Comment by anpete** [comment]
Metadata API Review: Try and remove metadata builder marker interfaces i.e. IForeignKeyBuilder etc. after BasicModelBuilder is removed.
