### ISSUE TITLE
Revisit functional test pattern

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#9098]
We now have a new way to clean the database and setup the services, so the template for functional tests can be simplified.

**Comment by smitpatel** [comment]
What is the new way? 😀

**Comment by AndriySvyryd** [comment]
The "new" here is relative to the last time the pattern was revised, about 2 years ago.

**Comment by ajcvickers** [comment]
"Make it easy to add a new test!" - @AndriySvyryd

**Comment by AndriySvyryd** [comment]
Also ensure `SqlServerTestStore.ExecuteCommand` and `SqlServerTestStore.ExecuteCommandAsync` close the connection

**Comment by smitpatel** [comment]
Once this issue is fixed, can we have a design meeting slot on how to add a new fixture & testbase?
