### ISSUE TITLE
MusicStore fails to run against sql azure database unless clustered indexes are explicitly added for all entities

### ISSUE THREAD

**Issue by kirthik** [aspnet/EntityFramework#911]
When I used Sql azure database to run MusicStore, I got the following error
```
Microsoft.Data.Entity.Update.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Tables without a clustered index are not supported in this version of SQL Server. Please create a clustered index and try again.
```
This worked with older builds

To fix this error, I had to add this statement to every entity
`builder.Entity<"EntityName">().Index("Id").ForSqlServer().Clustered();`

If an app has large number of entities, then having to add this statement to every entity in addition to adding keys seems pretty bad, experience wise. We should make the experience better here.

Also its not easy for the user to figure out what went wrong and how to fix the issue.

**Comment by ajcvickers** [comment]
With current defaults and Migrations this is no longer an issue.
