### ISSUE TITLE
DbFunctions: Schema not specified when calling DbFunction in projection

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#9214]
Seeing this on preview2; may be fixed in RTM..
```
fail: Microsoft.EntityFrameworkCore.Database.Command[200102]
      Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT ComputePostCount([b].[BlogId])
      FROM [Blogs] AS [b]
System.Data.SqlClient.SqlException (0x80131904): 'ComputePostCount' is not a recognized built-in function name.
```

**Comment by pmiddleton** [comment]
Do you have a repo example?

**Comment by pmiddleton** [comment]
I can't repo on the latest code.  Where are you setting the schema; globally, via attribute, or HasSchema on the function?

**Comment by anpete** [comment]
Not setting it at all. It should be defaulting to 'dbo'.

**Comment by pmiddleton** [comment]
Where are you expecting the default to be happening?  DbFunctions default to empty schema.  I have always seen the global schema default to empty as well.

**Comment by anpete** [comment]
Maybe this is just a new requirement based on how functions need to be called in TSQL?

**Comment by pmiddleton** [comment]
Adding a default of dbo for Sql Server makes sense.  I'm not sure the best way to do it.

We can add it during sql generation, but we need to key off of something.  Keying off of a null schema makes the most sense, but the built in IMethodCallTranslators are using null for schema.  They would have to change over to using a empty string.

Otherwise we would have to find a place in the dbFunction creation pipeline to derive off a class that can set the default value.

**Comment by pmiddleton** [comment]
@anpete @ajcvickers 

Do either of you have any suggestions or examples on how to inject a factory into the relational annotations?  I would like to create a SqlDbFunction class which can set the default schema.  The issue I am having is that I don't see a clean way to inject a dbFunction factory into the RelationalModelAnnotations class.    The only approach I see is storing it in the IModel and that just doesn't seem like the right way to go.

Has the team had any discussions around getting factories into the annotations?

**Comment by anpete** [comment]
It may be easier to have a SQL Server IModelAnnotationChangedConvention that just defaults the schema...

**Comment by pmiddleton** [comment]
Thanks - I forgot those notifications were there.  I will take a look into that approach.

**Comment by pmiddleton** [comment]
and yes I realize the irony in forgetting about it when I was the one who created it :)

**Comment by smitpatel** [comment]
Fixed via 7529563ec9136359a78a223f6e69441641a03924

**Comment by danobri** [comment]
@pmiddleton - I have two very similar functions, both decorated with the same DbFunction annotation:

`[DbFunction(Schema = "dbo")]`

One of them outputs the schema in generated queries and the other does not, causing the generated query to fail.  If I cut and paste the query from the debug window, and add the schema prefix to the UDF manually the query succeeds.  Despite lots of review and comparison, I see no difference in the way these functions are defined or wired up, so unfortunately can't provide steps to reproduce.  Any ideas how this could happen?

**Comment by smitpatel** [comment]
@danobri - Without reproduction steps it is near impossible to guess what is happening.

**Comment by pmiddleton** [comment]
@danobri - are you also using the fluent api on the problem function?  Could you accidentally be overwriting the schema there?

Beyond that guess I would need to see repo code like @smitpatel mentioned.  Can you post a minimal repo.

**Comment by pmiddleton** [comment]
@danobri - can you also open a new issue when you have the repo code.

**Comment by danobri** [comment]
I am not using the fluent api on the function wire up.  I believe I've found the problem though, so will open a new issue.

**Comment by danobri** [comment]
Just created #10421
