### ISSUE TITLE
When I use raw sql and include(), not all the navigation properties are setted (2.0.0-preview2)

### ISSUE THREAD

**Issue by ComptonAlvaro** [aspnet/EntityFramework#9271]
I am using T-Sql to get some records and in the same query I use Include() to include related entities of the entities that I get in the T-Sql.

At the end, in the dbContext, I have all the entities, the entities that I get from the T-Sql and the entities that I get from the Include(), but EF only relates the entities that I get from the T-Sql, but not the entities that I get from the Include().

I add the link to on drive with an example that reproduces this error. The application has two tests, the test that reproduce this error is the Test02, and I have comments in the code that explain the expected behavior and comment the result that I get.

[https://1drv.ms/u/s!AiTepLSbavZ0gRfxbvJr6mkF2fAo](https://1drv.ms/u/s!AiTepLSbavZ0gRfxbvJr6mkF2fAo)

**Comment by smitpatel** [comment]
Issue:
When we query data, (without include) changetracker does fix up of all navigations.
When we query data with include, the include pipeline fixup navigation included and change tracker deals with the rest of navigations. this was done as optimization.
But the include was doing limited fixup in the sense that it would fix up included navigations in direct results but it would not fix up navigations of included objects even if available in memory.

This repros in 1.1.2 but works correctly in 2.0.0 packages.
