### ISSUE TITLE
Benchmarks: Upgrade to latest released package of BenchmarkDotNet on NuGet

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#9285]
Fix for https://github.com/dotnet/BenchmarkDotNet/issues/481 is needed for our benchmark runs. We currently depend on their nightly builds. Once the fix is available on NuGet we should remove the nightly build and depend on what is available on NuGet.

**Comment by AndreyAkinshin** [comment]
BenchmarkDotNet v0.10.9 (with fix for https://github.com/dotnet/BenchmarkDotNet/issues/481) has been released, it's already available on nuget.org: https://www.nuget.org/packages/BenchmarkDotNet/0.10.9

**Comment by smitpatel** [comment]
Thanks @AndreyAkinshin - I will update the code. At present we are stuck on merging due to windows defender raising virus alert (seems like https://github.com/dotnet/BenchmarkDotNet/issues/364)

**Comment by smitpatel** [comment]
Fixed with 0a31b87c1c044c24e5ffd8219e710fbc0faa38aa
