### ISSUE TITLE
RevEng: Default/Computed Value processing

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#9323]
At present, DefaultValueSql does not set ValueGenerated on DatabaseColumn but ComputedValueSql sets it to AddOrUpdate.
If we are assuming that calling `HasDefaultValueSql` will set ValueGenerated by itself then same should also be true for `HasComputedValueSql` hence setting ValueGenerated for it is redundant. 
If it is incorrect assumption then, DefaultValue should set to ValueGenerated.OnAdd.

Identity must set ValueGenerated.OnAdd & rowversion must set OnAddOrUpdate.

**Comment by ajcvickers** [comment]
@smitpatel Where did we end up with this? Hopefully, if we scaffold HasDefaultValueSql, then we don't also scaffold ValueGeneratedOnAdd, and likewise for HasComputedValueSql and ValueGeneratedOnAddOrUpdate?

**Comment by smitpatel** [comment]
We would generate `ValueGenerated*` only if it would be different from conventions. For the case of HasDefaultValueSql, convention would give the same result so we were not scaffolding the function. (like wise for computed column.

This change was just to make sure, that DatabaseModel SqlServer is passing to Design does not have redundant data. DatabaseModel was setting ValueGenerated.OnAddOrUpdate even though it wasn't needed.

**Comment by ajcvickers** [comment]
Thanks @smitpatel. Sounds perfect.
