### ISSUE TITLE
RevEng: Warnings for null names for objects which requires name

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#9333]
We have "warnings" for sequence/column/index not having names but it is impossible to create them without name. There seem to be no way to actually hit that code path. Should we have warnings for them?

**Comment by smitpatel** [comment]
Also there are warnings for Columns of an index is not mapped but we don't map column only if the table is skipped. In which case other objects with cause warning for missing table as per #9334 and we will never hit missing index column warning.

**Comment by ErikEJ** [comment]
For all database engines?

**Comment by smitpatel** [comment]
This is for SqlServer provider. I was trying to write tests to verify the warning but couldn't find a way to actually achieve the error.

**Comment by ErikEJ** [comment]
Ah. Yes, I had same concern with sqlce
