### ISSUE TITLE
Metadata: Schema mismatch in user defined function

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#9360]
https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Relational/Metadata/Conventions/Internal/RelationalDbFunctionConvention.cs#L37

Above line sets schema for UDF to Model.DefaultSchema if it is not set on attribute & only when the DbFunction is added to the model.

Issues:
- If the function is found using FunctionFinder via Attribute then OnModelCreating has not run yet so no default schema. Which makes DbFunction.Schema would be null even if the model has default schema.
- If you define function first and then define default schema then schema will remain null in the function.

We need to pull the logic out of that convention which sets the schema to model's default schema.

**Comment by divega** [comment]
**EF Triage:** we should make it work the same way it works for tables.

**Comment by pmiddleton** [comment]
How does it work for tables?  I was going to look at this tonight along with the updates for #9303

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Relational/Metadata/RelationalEntityTypeAnnotations.cs#L113

This is how it works for table. The getter of schema looks into model.

**Comment by smitpatel** [comment]
fixed via 7529563ec9136359a78a223f6e69441641a03924
