### ISSUE TITLE
Logging: Remove unused resources 

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#9370]
There are some design time logging messages which are removed in reverse engineering, especially in SqlServer.
There is some issue with EventIds defined for them (even though not being used actually) which makes removing them harder.

Investigate if we can remove them without breaking public surface & tests.
If not mark as obsolete.

**Comment by divega** [comment]
We will try to obsolete IDs that are not used anymore and modify the test to ignore those.
