### ISSUE TITLE
Make sure that our multithreaded code works correctly across different platforms

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#960]
EF contains some custom types that we use for thread safe code such as AsyncLock,  ThreadSafeDictionaryCache, and ThreadSafeLazyRef in which we might be making assumptions about the memory model. We should make sure the locking patterns are safe to use on other platforms.

**Comment by divega** [comment]
Moving this out of @AndriySvyryd's plate since this can be done by someone else.

**Comment by ajcvickers** [comment]
Closing since we are now using standard types for all these things.
