### ISSUE TITLE
StateManager :: duplicate entries for entities that reference same entity in two two-way navigations

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#968]
Consider the following:

```
    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public List<Person> Siblings { get; set; }
        public Person Lover { get; set; }
        public Person LoverReverse { get; set; }
        public Person SiblingReverse { get; set; }
    }

    public class GoTContext : DbContext
    {
        public DbSet<Person> People { get; set; }
        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>().OneToMany(p => p.Siblings, p => p.SiblingReverse);
            modelBuilder.Entity<Person>().OneToOne(p => p.Lover, p => p.LoverReverse);

            modelBuilder.Entity<Person>().OneToMany(p => p.Siblings).Required(false);
            modelBuilder.Entity<Person>().OneToOne(p => p.Lover).Required(false);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=StateManagerBug;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }


            using (var ctx = new GoTContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();
                var cersei = new Person { Name = "Cersei" };
                var jamie = new Person { Name = "Jamie" };

                cersei.Lover = jamie;
                cersei.Siblings = new List<Person> { jamie, };

                ctx.People.AddRange(new[] { cersei, jamie, });
                ctx.SaveChanges();
            }
```

throws:

System.InvalidOperationException: The instance of entity type 'Include3.Person'
cannot be tracked because another instance of this type with the same key is alr
eady being tracked. For new entities consider using an IIdentityGenerator to gen
erate unique key values.
   at Microsoft.Data.Entity.ChangeTracking.StateManager.StartTracking(StateEntry
 entry)
   at Microsoft.Data.Entity.ChangeTracking.StateEntry.SetEntityState(EntityState
 oldState, EntityState newState)
   at Microsoft.Data.Entity.ChangeTracking.StateEntry.SetEntityState(EntityState
 entityState)
   at Microsoft.Data.Entity.ChangeTracking.StateEntry.set_EntityState(EntityStat
e value)
   at Microsoft.Data.Entity.DbContext.Add[TEntity](TEntity entity)
   at Microsoft.Data.Entity.DbSet`1.Add(TEntity entity)
   at Microsoft.Data.Entity.DbSet`1.AddRange(IEnumerable`1 entities)

**Comment by ajcvickers** [comment]
Note for triage: unassigning since anyone could work on this.

**Comment by lukewaters** [comment]
This issue no longer repro's as there have been improvements to change tracker.  Filed new issues #1697 and #1699
