### ISSUE TITLE
Commands: PMC cmdlets for xproj

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#978]
Having to drop down to the cmd line and use dnx is very jarring compared to staying in VS.

We need to do some work to enable this, but most of it is in NuGet and xproj tooling:
* https://github.com/NuGet/Home/issues/1174
* https://github.com/aspnet/Tooling-Internal/issues/443

**Comment by rowanmiller** [comment]
Work is required in NuGet and xproj tooling before we can light this up

**Comment by bricelam** [comment]
Moving to RTM. This won't be unblocked for RC1.
